### ISSUE TITLE
Failed to perform http request

### ISSUE THREAD

**Issue by Boblet67** [minecraft-linux/mcpelauncher-manifest#1004]
I get the error:
Failed to perform http request to https://play.googleapis.com/download/by-token/download?token=BLAHBLAHBLAH : CURLcode 18 Details: transfer closed with 2564790 bytes remaining to read
That has since stopped probably due to a better internet. 
And the error:
Failed to perform http request to https://play.googleapis.com/download/by-token/download?token=BLAHBLAHBLAH : CURLcode 56 Details: OpenSSL SSL_read: error:0A000126:SSL routines::unexpected eof while reading, errno 0

I have tried the AppImage and the packages for Ubuntu. 
I run it, sign in, and press download and play and it gives me about 3 of these errors before finishing. Nothing happens and no file is in the data directory. Nothing seems to change. :(

I don't want a pirated version of it. If I could get my x86_64 version of the minecraft another way then that would help. 
I have bought the game and no other errors appear can anyone help me with this? 

 - OS: Ubuntu 22.04 x86_64

**Comment by Boblet67** [comment]
Is there a curl command to get the apk I could test with?

**Comment by ChristopherHX** [comment]
the url of the error is an apk url, but you need more that this one to have the game installed.

Debug builds of https://github.com/minecraft-linux/mcpelauncher-ui-manifest prints all urls to console

I could consider providing all url in the ui to paste in the webbrowser

**Comment by Boblet67** [comment]
How could I get the older versions to get the URLs and if I do, what do I do with those files?
Is there any way to see the underlying issue?
Any ideas welcome.

**Comment by Boblet67** [comment]
Ill just use java I don't think anyone else has this issue. :(

**Comment by Boblet67** [comment]
Ill just use java I don't think anyone else has this issue. :(

**Comment by olzbolzz** [comment]
not just you, I get it too

**Comment by ChristopherHX** [comment]
Long time passed, [the nightly of the launcher (soon normal releases too like 0.15.2 or 0.16.0)](https://github.com/minecraft-linux/mcpelauncher-manifest/releases/tag/nightly) now has an plan b for people with internet issues to allow using the webbrowser (a well tested tool to download files, not like this launcher) to download the wanted game version and import the files manually


![image](https://github.com/minecraft-linux/mcpelauncher-wiki/assets/44845461/b4e6eb24-c24c-4c3d-aaf8-530b4dd0638d)
Then click download apk, you will see something like
![image](https://github.com/minecraft-linux/mcpelauncher-wiki/assets/44845461/a93b6884-ee9f-4917-bc04-087f8bc60812)

Select the Version you want, you might need to select the correct architecture from the versions dropdown

Finally via Get Download Info you get all links to the splitted apk
![image](https://github.com/minecraft-linux/mcpelauncher-wiki/assets/44845461/d9e1b5be-7fe1-44cd-bc47-7dbd94d6bb1a)

Press all of the blue links, probably one after the other in case your internet struggels

If clicking doesn't work select the whole text field by mouse and copy / paste it to gedit, then you can paste the links manually in the browser


_The dialog doesn't show the full links so screenshots don't share the full url to the game_

_Issue Group https://github.com/minecraft-linux/mcpelauncher-wiki/issues/89, to backlink everything together_
