### ISSUE TITLE
Can you add .apk minecraft support?

### ISSUE THREAD

**Issue by HafizBeyy** [minecraft-linux/mcpelauncher-manifest#1014]
i will never buy it from google. cause i already did from microsoft. i can setup minecraft.apk on my phone. i can login microsoft, and get in the servers. is there a way to say mcpelauncher "hey, you can get application data from path/to/minecraft.apk" ?

**Comment by ChristopherHX** [comment]
For both Minecraft Trial & Edu is this planned, for all other use cases please look for alternatives like installing Android x86 or Windows 11 etc.

**Comment by HafizBeyy** [comment]
> For both Minecraft Trial & Edu is this planned, for all other use cases please look for alternatives like installing Android x86 or Windows 11 etc.

But they're both free versions. İf the app is like waydroid, installing apks should possible @ChristopherHX

**Comment by ChristopherHX** [comment]
This app is not like waydroid, this is a heavy Minecraft Android Mod that uses techniques like wine to run it in a native linux/macOS process.

Additionally this app modifies parts of the game that are in legal grey zone, therefore allowing you and anyone else to use this app via apk import of the paid apk (without owning that one on google play) is illegal in my country and have legal consequences for me not limiting to termination of this app as a whole

The Trial allows you to try this out without paying anything, in case you thing this app would be scam or not trustworthy

Trial Apk Import is available in nightly, importing a paid app is rejected.

**Comment by ChristopherHX** [comment]
> Trial Apk Import is available in nightly, importing a paid app is rejected.

I admit, this is still broken without a logged in google account

**Comment by HafizBeyy** [comment]
> > Trial Apk Import is available in nightly, importing a paid app is rejected.
> 
> I admit, this is still broken without a logged in google account

İ hope you find a way out and let us not to scam by google 😔🤲

**Comment by ChristopherHX** [comment]
Apks provided by third party sites that are neither amazon / google / mojang are obviously scam if they are not signed by one of the mentioned.

Many apk's that can be found are for arm phones not intel laptops and are modified with potential harmful changes. 

That's how it will look in 24h in nightly
![image](https://github.com/minecraft-linux/mcpelauncher-manifest/assets/44845461/c51a7c63-3f1c-44e3-b023-54eeaecaed08)

- Message 1, the app can't download apk's from the store, not even trial apks even that needs a login
- Message 2, trial mode is on non trial versions won't open or import
- Message 3, related to Message 1

What you have asked for won't happen for paid apk's

**Comment by HafizBeyy** [comment]
> Apks provided by third party sites that are neither amazon / google / mojang are obviously scam if they are not signed by one of the mentioned.
> 
> Many apk's that can be found are for arm phones not intel laptops and are modified with potential harmful changes. 
> 
> That's how it will look in 24h in nightly
> ![image](https://github.com/minecraft-linux/mcpelauncher-manifest/assets/44845461/c51a7c63-3f1c-44e3-b023-54eeaecaed08)
> 
> - Message 1, the app can't download apk's from the store, not even trial apks even that needs a login
> - Message 2, trial mode is on non trial versions won't open or import
> - Message 3, related to Message 1
> 
> What you have asked for won't happen for paid apk's

it doesnt matter. microsoft doesnt see i use an apk. İt just logs in to my account

**Comment by HafizBeyy** [comment]
it doesnt need to download an apk, i'm gonna provide the apk and all the app's left to do is run it as usual

**Comment by ChristopherHX** [comment]
> i'm gonna provide the apk and all the app's left to do is run it as usual

I'm closing this as not planned, because I don't support illegal activity in any way.

As you mentioned, just use waydroid that doesn't have such restrictions.

Waydroid doesn't alter the code that validates the legitimacy of the game license, therefore has an uncompareable legal situation.

**Comment by NicholasFlamy** [comment]
> illegal in my country and have legal consequences for me not limiting to termination of this app as a whole

Out of curiosity, what country are you in that has such laws?
