### ISSUE TITLE
You are olmost out of data storage error [32bit game]

### ISSUE THREAD

**Issue by FroggLive123** [minecraft-linux/mcpelauncher-manifest#1019]
OS:Linux Mint 21.3
Program version: Minecraft_Bedrock_Launcher-sdl3-x86_64-v0.15.2.401.AppImage

Error description: 
Just downloaded programm but Minecraft do not let create world because haven`t available space.

![error](https://github.com/minecraft-linux/mcpelauncher-manifest/assets/108540979/d16d264b-3a87-49ab-b431-e0a7c350e7eb)

**Comment by FroggLive123** [comment]
Error works only on minecraft 1.21.2.02 but does not work on older versions

**Comment by ChristopherHX** [comment]
Confirmed: Only happens on 32bit, please downgrade the launcher to v0.15.0 (non nightly) this will be fixed soon.

**Comment by FroggLive123** [comment]
Thanks
