### ISSUE TITLE
Download failed after updating to v0.15.2.796

### ISSUE THREAD

**Issue by Code-With-Reza** [minecraft-linux/mcpelauncher-manifest#1020]
**Describe the bug**
I can't download the latest version which in the time I'm writing this, Minecraft version 1.21.2.02

**To Reproduce**
1. Go to Linux Minecraft Launcher
2. Add new profile with version 1.21.2.02 (No matter Latest or Google Play)
3. Click on Download and Play
4. Wait for it to download
5. See error

**Expected behavior**
After download progress bar is completed, I should be able to open Minecraft.

**Screenshots**
[Error](https://i.imgur.com/SM2jRQA.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Version : v0.15.2.796-AppImage-x86_64 (build 796)
 - Installation Type : AppImage (Auto Update)

**Comment by ChristopherHX** [comment]
This could be one of
- corrupted download (probably unlikely)
- the zip format is now newer than what libzip of ubuntu 16.04 supports
  - Bookworm appimage / apt pkg / rpm pkg / flatpak can avoid this issue

~~Nightly versions as linked in the readme have an download apk feature, which allows you to download all the apk's of 1.21.2.02 via your browser and then just import it~~

Oh I forget importing would fail in this case

**Comment by ChristopherHX** [comment]
I misread your issue

- Open Settings
- Open Versions tab
- Delete old versions of the game to get enough diskspace to complete the download

If your disk is full you get an error named `Failed to open output file`

**Comment by ChristopherHX** [comment]
I'm improving the error to be more like
```
.........
Details:
Failed to write to file /tmp/test-data/mcpelauncher/versions/temp-EOmvKp/assets/gui/dist/hbui/fonts/NotoSansTC-Regular-2eeaf.otf: No space left on device
```

**Comment by Code-With-Reza** [comment]
Thank you for your response. I got it working after I deleted the old version of the game that I didnt used. My storage seems to be full at that time. Once again thank you!

**Comment by Code-With-Reza** [comment]
closed
