### ISSUE TITLE
"Drowned" error when logging into MS account (popup flashes and disappears)

### ISSUE THREAD

**Issue by GGORG0** [minecraft-linux/mcpelauncher-manifest#1025]
**Describe the bug**
When clicking log in, a big white window pops up for half a second and closes. Then I get the drowned error.

**To Reproduce**
1. click on log in
2. see white window flash
3. see drowned error

**Expected behavior**
a microsoft login page

**Screenshots**

https://github.com/user-attachments/assets/e67299a5-d34d-4a24-b70b-a09e00500b15

**Desktop (please complete the following information):**
 - OS: Linux (NixOS + `appimage-run`)
 - Version Minecraft_Bedrock_Launcher-x86_64-v0.15.2.796.AppImage
 - Installation Type AppImage

**Comment by ChristopherHX** [comment]
goto game settings and switch xbox login to use device code then restart

Now you should see an guide to use your browser to enter your creds


I assume the webview is not compatible with your setup and crashs

**Comment by GGORG0** [comment]
Thanks, that worked!

**Comment by Oughie** [comment]
@ChristopherHX Sorry for necroposting but I'm currently having this issue too. I'm not sure where to find what you describe in your solution:  `goto game settings and switch xbox login to use device code then restart`. Where do I find this option? Is it in the launcher or is it in the game? Either way, I can't find it...
