### ISSUE TITLE
Cracking the Game

### ISSUE THREAD

**Issue by wu21-web** [minecraft-linux/mcpelauncher-manifest#1029]
I already bought pe on app store, and I bought java and bedrock on minecraft.net. But I have to buy bedrock again on the play store, that wasn't fair!

**Comment by ChristopherHX** [comment]
Not planned, please find alternatives for your scenario.

I would only grant you to play the trial to try this if it would be worth to use this buggy software

- currently only in nightly: https://github.com/minecraft-linux/mcpelauncher-manifest/releases
