### ISSUE TITLE
Audio Not Working On Latest Version For Mac OS

### ISSUE THREAD

**Issue by clafloy** [minecraft-linux/mcpelauncher-manifest#1033]
So I Have The Newest Version Of MCPE Launcher For Mac, And For Some Reason The audio won't work. Help!

**Comment by ChristopherHX** [comment]
But I didn't even release ver v1.0.0 for mac yet with breaking audio, idk what you are using

> Newest Version Of MCPE Launcher For Mac

This is not a version, something like v0.15.2-474 is one that I can use to know what you are using.

**Comment by Vivian-Adriana** [comment]
![image](https://github.com/user-attachments/assets/f4938c12-5c37-4c00-a2b7-e787051064dc)
i think they meant the one found in actions tab, i use that too

**Comment by ChristopherHX** [comment]
Release 1.0.0 is dropped for macOS by now and will never release.

March 2025 is the End of Support by Mojang for this launcher port.
