### ISSUE TITLE
Crash on minecraft mcpe launcher for mac

### ISSUE THREAD

**Issue by xXAndres2001Xx** [minecraft-linux/mcpelauncher-manifest#1040]
When I play and run de minecraft launcher, it crash and will not charge the minecraft. In the begining works, but a few days ago, it's stops to work normally.

This is what is says: 

23:17:41 Info  [Launcher] Version: client 4c5f4fd / manifest 80770c4
23:17:41 Info  [Launcher] OS: macOS, Arch: x86_64
23:17:41 Info  [Launcher] CPU: GenuineIntel        Intel(R) Core(TM) i5-2400S CPU @ 2.50GHz
23:17:41 Info  [Launcher] CPU supports SSSE3: YES
23:17:41 Info  [Launcher] Reading Launcher Settings File: /Users/macos/Library/Application Support/mcpelauncher/mcpelauncher-client-settings.txt
23:17:41 Info  [Launcher] Applied Launcher Settings
23:17:41 Trace [Launcher] Loading android libraries
23:17:41 Trace [Launcher] linker loaded
23:17:41 Trace [REDIRECT] /data/data/com.mojang.minecraftpe to /Users/macos/Library/Application Support/mcpelauncher/
23:17:41 Trace [REDIRECT] /data/data/Applications/Minecraft Bedrock Launcher.app/Contents/proc/712/cmdline to /Users/macos/Library/Application Support/mcpelauncher/
23:17:41 Trace [REDIRECT] /data/data/Applications/Minecraft Bedrock Launcher.app/Contents/MacOS/./mcpelauncher-client to /Users/macos/Library/Application Support/mcpelauncher/
23:17:41 Trace [REDIRECT] /data/data to /Users/macos/Library/Application Support/mcpelauncher/
23:17:41 Trace [REDIRECT] . to /Users/macos/Library/Application Support/mcpelauncher/versions/1.21.23.01/assets/
23:17:41 Trace [REDIRECT] /proc to /Users/macos/Library/Application Support/mcpelauncher/proc/
23:17:41 Trace [REDIRECT] /sys to /Users/macos/Library/Application Support/mcpelauncher/sys/
23:17:41 Trace [LinkerUtils] Loaded OS library libm.dylib
23:17:41 Trace [LinkerUtils] Loaded OS library libz.dylib
23:17:41 Warn  [FMOD] Failed to load host libfmod: 'Failed to find data file: lib/native/x86_64/libfmod.dylib', use experimental pulseaudio backend if available
23:17:41 Trace [Launcher] Loading Minecraft library
linker: mcpelauncher_linker_notifylldb /Users/macos/Library/Application Support/mcpelauncher/versions/1.21.23.01/lib/x86_64/libc++_shared.so 0x2575c0000
linker: mcpelauncher_linker_notifylldb /Users/macos/Library/Application Support/mcpelauncher/versions/1.21.23.01/lib/x86_64/libfmod.so 0x257740000
23:17:45 Error [MinecraftUtils] Failed to load Minecraft: dlopen failed: cannot locate symbol "glBindRenderbuffer" referenced by "/Users/macos/Library/Application Support/mcpelauncher/versions/1.21.23.01/lib/x86_64/libminecraftpe.so"...
23:17:45 Info  [Launcher] Loading gamepad mappings
23:17:45 Trace [Launcher] Loading gamepad mappings: /Applications/Minecraft Bedrock Launcher.app/Contents/Resources/mcpelauncher/gamecontrollerdb.txt
23:17:45 Info  [Launcher] Creating window
2024-09-15 23:17:45.361 mcpelauncher-client[712:7660] NSSoftLinking - The function 'SLSTransactionEnsureSpaceSwitchToActiveProcess' can't be found in the (null) framework.
linker: mcpelauncher_linker_notifylldb /Users/macos/Library/Application Support/mcpelauncher/versions/1.21.23.01/lib/x86_64/libc++_shared.so 0x259200000
linker: mcpelauncher_linker_notifylldb /Users/macos/Library/Application Support/mcpelauncher/versions/1.21.23.01/lib/x86_64/libminecraftpe.so 0x25ac80000
Found hook: _ZN11AppPlatform16showMousePointerEv @ 0x104d5fb00
Found hook: _ZN11AppPlatform16hideMousePointerEv @ 0x104d5fae0
Found hook: _ZN11AppPlatform17setFullscreenModeE14FullscreenMode @ 0x104d5fb20
Found hook: _ZN4FMOD6System4initEijPv @ 0x104eb1220
Found hook: _ZN3rtc10getifaddrsEPP7ifaddrs @ 0x104f08670
Found hook: _ZN3rtc11freeifaddrsEP7ifaddrs @ 0x104f08a30
23:17:48 Info  [Launcher] Loaded Minecraft library
23:17:48 Debug [Launcher] Minecraft is at offset 0x25AC80000
23:17:48 Info  [Launcher] Game version: 0.0.0.0
23:17:48 Info  [Launcher] Applying patches
23:17:48 Debug [CorePatches] Failed to patch, vtable _ZTV21AppPlatform_android23 not found
23:17:48 Info  [Launcher] Initializing JNI
23:17:48 Error [JniSupport] Missing native symbol: Java_com_mojang_minecraftpe_MainActivity_nativeRegisterThis
23:17:48 Error [JniSupport] Missing native symbol: Java_com_mojang_minecraftpe_MainActivity_nativeInitializeWithApplicationContext
23:17:48 Error [JniSupport] Missing native symbol: Java_com_mojang_minecraftpe_MainActivity_nativeUnregisterThis
23:17:48 Error [JniSupport] Missing native symbol: Java_com_mojang_minecraftpe_MainActivity_nativeInitializeXboxLive
23:17:48 Error [JniSupport] Missing native symbol: Java_com_mojang_minecraftpe_MainActivity_nativeinitializeLibHttpClient
23:17:48 Error [JniSupport] Missing native symbol: Java_com_mojang_minecraftpe_MainActivity_nativeInitializeLibHttpClient
23:17:48 Error [JniSupport] Missing native symbol: Java_com_microsoft_xal_browser_WebView_urlOperationSucceeded
23:17:48 Error [JniSupport] Missing native symbol: Java_com_mojang_minecraftpe_PlayIntegrity_nativePlayIntegrityComplete
23:17:48 Info  [Launcher] Executing main thread
23:17:48 Trace [Minecraft] Entering JNI_OnLoad 0x70000b2fe000
23:17:48 Trace [Minecraft] JNI_OnLoad completed
23:17:48 Trace [JniSupport] Invoking nativeRegisterThis
23:17:48 Trace [JniSupport] Invoking ANativeActivity_onCreate
23:17:48 Warn  [Main] Android stub called
23:17:48 Warn  [Main] Android stub called
23:17:48 Warn  [Main] Android stub called
23:17:48 Warn  [Main] Android stub called
23:17:48 Info  [Minecraft] android_main starting. internalDataPath is '/internal', externalDataPath is '/external'
23:17:48 Trace [JniSupport] Invoking start activity callbacks
23:17:48 Error [MCPE] *** setCachedDeviceId(34cb97f0-7d8a-4270-8292-5080561183c5)
23:17:48 Info  [Bedrock] configureBreakpad with directory: /crash, sessionid is: 188fb5ff-c4e1-4a32-b337-a89d9771c4c4
23:17:48 Info  [Bedrock] configureBreakpad called, directory is: /crash, sessionid is: 188fb5ff-c4e1-4a32-b337-a89d9771c4c4
23:17:48 Info  [Minecraft] NO LOG FILE! - AppPlatform_android::setStorageDirectory - using External dir (NEW) - CurrentFileStoragePath is now '/Users/macos/Library/Application Support/mcpelauncher/'
23:17:48 Warn  [Minecraft] NO LOG FILE! - [Graphics] The graphics context was gained
23:17:48 Warn  [Minecraft] NO LOG FILE! - [Graphics] The graphics context was gained
2024-09-15 23:17:48.810 mcpelauncher-client[712:7660] NSSoftLinking - The function 'SLSTransactionSetWindowTags' can't be found in the (null) framework.
2024-09-15 23:17:48.810 mcpelauncher-client[712:7660] NSSoftLinking - The function 'SLSTransactionReorderWindows' can't be found in the (null) framework.
2024-09-15 23:17:48.811 mcpelauncher-client[712:7660] NSSoftLinking - The function 'SLSTransactionOrderWindowGroupFrontConditionally' can't be found in the (null) framework.
23:17:48 Warn  [Minecraft] MinecraftGame::init && MinecraftGame::setSize!
23:17:48 Warn  [FakeEGL] eglQueryString 308d
23:17:48 Warn  [Main] Android stub called
23:17:48 Info  [GL] Vendor: Google Inc.
23:17:48 Info  [GL] Renderer: ANGLE (ATI Technologies Inc., AMD Radeon HD 6750M OpenGL Engine, OpenGL 4.1 core)
23:17:48 Info  [GL] Version: OpenGL ES 3.0.0 (ANGLE 2.1.14073 git hash: 26930173647b)
23:17:48 Info  [GL] Vendor: Google Inc.
23:17:48 Info  [GL] Renderer: ANGLE (ATI Technologies Inc., AMD Radeon HD 6750M OpenGL Engine, OpenGL 4.1 core)
23:17:48 Info  [GL] Version: OpenGL ES 3.0.0 (ANGLE 2.1.14073 git hash: 26930173647b)
23:17:48 Warn  [Main] Android stub called
linker: mcpelauncher_linker_notifylldb /Users/macos/Library/Application Support/mcpelauncher/versions/1.21.23.01/lib/x86_64/libMediaDecoders_Android.so 0x26c740000

23:17:59 Info  [GL] Vendor: Google Inc.
23:17:59 Info  [GL] Renderer: ANGLE (ATI Technologies Inc., AMD Radeon HD 6750M OpenGL Engine, OpenGL 4.1 core)
23:17:59 Info  [GL] Version: OpenGL ES 3.0.0 (ANGLE 2.1.14073 git hash: 26930173647b)
23:17:59 Warn  [Main] Android stub called
Signal 10 received
Backtrace elements: 4
#0 0   mcpelauncher-client                 0x0000000104ea9b28 _ZN12CrashHandler12handleSignalEiPv + 344
#1 1   mcpelauncher-client                 0x0000000104ea9f55 _ZN12CrashHandler15handle_fs_faultEiPvS0_ + 133
#2 2   libsystem_platform.dylib            0x00007ff80ccf55ed _sigtramp + 29
#3 3   ???                                 0x000000003f800000 0x0 + 1065353216
Dumping stack...
#9 LINKER (null)+0x257862668 in /Users/macos/Library/Application Support/mcpelauncher/versions/1.21.23.01/lib/x86_64/libfmod.so+0x122668 [0x257862668]
#47 LINKER (null)+0x25785ac38 in /Users/macos/Library/Application Support/mcpelauncher/versions/1.21.23.01/lib/x86_64/libfmod.so+0x11ac38 [0x25785ac38]
#153 LINKER (null)+0x257879230 in /Users/macos/Library/Application Support/mcpelauncher/versions/1.21.23.01/lib/x86_64/libfmod.so+0x139230 [0x257879230]
#162 LINKER (null)+0x25780bb0d in /Users/macos/Library/Application Support/mcpelauncher/versions/1.21.23.01/lib/x86_64/libfmod.so+0xcbb0d [0x25780bb0d]
#163 LINKER (null)+0x2578791d4 in /Users/macos/Library/Application Support/mcpelauncher/versions/1.21.23.01/lib/x86_64/libfmod.so+0x1391d4 [0x2578791d4]
#168 LINKER (null)+0x25779c7e9 in /Users/macos/Library/Application Support/mcpelauncher/versions/1.21.23.01/lib/x86_64/libfmod.so+0x5c7e9 [0x25779c7e9]
#172 LINKER (null)+0x257780385 in /Users/macos/Library/Application Support/mcpelauncher/versions/1.21.23.01/lib/x86_64/libfmod.so+0x40385 [0x257780385]
#178 LINKER (null)+0x25778ea1d in /Users/macos/Library/Application Support/mcpelauncher/versions/1.21.23.01/lib/x86_64/libfmod.so+0x4ea1d [0x25778ea1d]
#190 LINKER (null)+0x25778184d in /Users/macos/Library/Application Support/mcpelauncher/versions/1.21.23.01/lib/x86_64/libfmod.so+0x4184d [0x25778184d]
#194 LINKER FMOD::System::setOutput(FMOD_OUTPUTTYPE)+0x35 in /Users/macos/Library/Application Support/mcpelauncher/versions/1.21.23.01/lib/x86_64/libfmod.so+0xc1fe9 [0x257801fe9]
#202 LINKER (null)+0x2578947c4 in /Users/macos/Library/Application Support/mcpelauncher/versions/1.21.23.01/lib/x86_64/libfmod.so+0x1547c4 [0x2578947c4]
#210 LINKER (null)+0x2578947c4 in /Users/macos/Library/Application Support/mcpelauncher/versions/1.21.23.01/lib/x86_64/libfmod.so+0x1547c4 [0x2578947c4]
#211 LINKER (null)+0x257860160 in /Users/macos/Library/Application Support/mcpelauncher/versions/1.21.23.01/lib/x86_64/libfmod.so+0x120160 [0x257860160]
#213 LINKER (null)+0x2578604d8 in /Users/macos/Library/Application Support/mcpelauncher/versions/1.21.23.01/lib/x86_64/libfmod.so+0x1204d8 [0x2578604d8]
#214 LINKER (null)+0x25780a944 in /Users/macos/Library/Application Support/mcpelauncher/versions/1.21.23.01/lib/x86_64/libfmod.so+0xca944 [0x25780a944]
#216 LINKER (null)+0x2578604d8 in /Users/macos/Library/Application Support/mcpelauncher/versions/1.21.23.01/lib/x86_64/libfmod.so+0x1204d8 [0x2578604d8]
#220 LINKER (null)+0x2577663da in /Users/macos/Library/Application Support/mcpelauncher/versions/1.21.23.01/lib/x86_64/libfmod.so+0x263da [0x2577663da]
#224 LINKER (null)+0x257767c5b in /Users/macos/Library/Application Support/mcpelauncher/versions/1.21.23.01/lib/x86_64/libfmod.so+0x27c5b [0x257767c5b]
#226 LINKER FMOD::System::getVersion(unsigned int*)+0x86 in /Users/macos/Library/Application Support/mcpelauncher/versions/1.21.23.01/lib/x86_64/libfmod.so+0xc4f60 [0x257804f60]
#234 LINKER (null)+0x2691cf82c in /Users/macos/Library/Application Support/mcpelauncher/versions/1.21.23.01/lib/x86_64/libminecraftpe.so+0xe54f82c [0x2691cf82c]
#246 LINKER (null)+0x269534562 in /Users/macos/Library/Application Support/mcpelauncher/versions/1.21.23.01/lib/x86_64/libminecraftpe.so+0xe8b4562 [0x269534562]
#247 LINKER (null)+0x26a13c4f8 in /Users/macos/Library/Application Support/mcpelauncher/versions/1.21.23.01/lib/x86_64/libminecraftpe.so+0xf4bc4f8 [0x26a13c4f8]
#248 LINKER operator new(unsigned long)+0x25 in /Users/macos/Library/Application Support/mcpelauncher/versions/1.21.23.01/lib/x86_64/libminecraftpe.so+0xe8a8a75 [0x269528a75]
#252 LINKER (null)+0x2691cf700 in /Users/macos/Library/Application Support/mcpelauncher/versions/1.21.23.01/lib/x86_64/libminecraftpe.so+0xe54f700 [0x2691cf700]
#253 LINKER (null)+0x269d60d60 in /Users/macos/Library/Application Support/mcpelauncher/versions/1.21.23.01/lib/x86_64/libminecraftpe.so+0xf0e0d60 [0x269d60d60]
#258 LINKER (null)+0x47 in /Users/macos/Library/Application Support/mcpelauncher/versions/1.21.23.01/lib/x86_64/libfmod.so+0x26432 [0x257766432]
#270 LINKER (null)+0x2629170dc in /Users/macos/Library/Application Support/mcpelauncher/versions/1.21.23.01/lib/x86_64/libminecraftpe.so+0x7c970dc [0x2629170dc]
#293 LINKER (null)+0x26a270e38 in /Users/macos/Library/Application Support/mcpelauncher/versions/1.21.23.01/lib/x86_64/libminecraftpe.so+0xf5f0e38 [0x26a270e38]
#301 LINKER (null)+0x269d60d60 in /Users/macos/Library/Application Support/mcpelauncher/versions/1.21.23.01/lib/x86_64/libminecraftpe.so+0xf0e0d60 [0x269d60d60]
#306 LINKER (null)+0x26a2c8178 in /Users/macos/Library/Application Support/mcpelauncher/versions/1.21.23.01/lib/x86_64/libminecraftpe.so+0xf648178 [0x26a2c8178]
#308 LINKER (null)+0x26a270e38 in /Users/macos/Library/Application Support/mcpelauncher/versions/1.21.23.01/lib/x86_64/libminecraftpe.so+0xf5f0e38 [0x26a270e38]
#444 LINKER (null)+0x261830838 in /Users/macos/Library/Application Support/mcpelauncher/versions/1.21.23.01/lib/x86_64/libminecraftpe.so+0x6bb0838 [0x261830838]
#456 LINKER (null)+0x26181a04d in /Users/macos/Library/Application Support/mcpelauncher/versions/1.21.23.01/lib/x86_64/libminecraftpe.so+0x6b9a04d [0x26181a04d]
#458 LINKER (null)+0x26a3bffa0 in /Users/macos/Library/Application Support/mcpelauncher/versions/1.21.23.01/lib/x86_64/libminecraftpe.so+0xf73ffa0 [0x26a3bffa0]
#460 LINKER (null)+0x26a3bffa0 in /Users/macos/Library/Application Support/mcpelauncher/versions/1.21.23.01/lib/x86_64/libminecraftpe.so+0xf73ffa0 [0x26a3bffa0]
#463 LINKER (null)+0x26a3bfaf0 in /Users/macos/Library/Application Support/mcpelauncher/versions/1.21.23.01/lib/x86_64/libminecraftpe.so+0xf73faf0 [0x26a3bfaf0]
#472 LINKER (null)+0x261948924 in /Users/macos/Library/Application Support/mcpelauncher/versions/1.21.23.01/lib/x86_64/libminecraftpe.so+0x6cc8924 [0x261948924]
#478 LINKER (null)+0x26a2c8178 in /Users/macos/Library/Application Support/mcpelauncher/versions/1.21.23.01/lib/x86_64/libminecraftpe.so+0xf648178 [0x26a2c8178]
#483 LINKER (null)+0x269c392b8 in /Users/macos/Library/Application Support/mcpelauncher/versions/1.21.23.01/lib/x86_64/libminecraftpe.so+0xefb92b8 [0x269c392b8]
#484 LINKER (null)+0x2618b3e82 in /Users/macos/Library/Application Support/mcpelauncher/versions/1.21.23.01/lib/x86_64/libminecraftpe.so+0x6c33e82 [0x2618b3e82]
#494 LINKER (null)+0x26183dfa8 in /Users/macos/Library/Application Support/mcpelauncher/versions/1.21.23.01/lib/x86_64/libminecraftpe.so+0x6bbdfa8 [0x26183dfa8]
#513 LINKER (null)+0x26a280948 in /Users/macos/Library/Application Support/mcpelauncher/versions/1.21.23.01/lib/x86_64/libminecraftpe.so+0xf600948 [0x26a280948]
#535 LINKER (null)+0x269c33020 in /Users/macos/Library/Application Support/mcpelauncher/versions/1.21.23.01/lib/x86_64/libminecraftpe.so+0xefb3020 [0x269c33020]
#541 LINKER (null)+0x269c32f20 in /Users/macos/Library/Application Support/mcpelauncher/versions/1.21.23.01/lib/x86_64/libminecraftpe.so+0xefb2f20 [0x269c32f20]
#547 LINKER (null)+0x269c32ea0 in /Users/macos/Library/Application Support/mcpelauncher/versions/1.21.23.01/lib/x86_64/libminecraftpe.so+0xefb2ea0 [0x269c32ea0]
#553 LINKER (null)+0x269c32e20 in /Users/macos/Library/Application Support/mcpelauncher/versions/1.21.23.01/lib/x86_64/libminecraftpe.so+0xefb2e20 [0x269c32e20]
#583 LINKER (null)+0x269c32ba0 in /Users/macos/Library/Application Support/mcpelauncher/versions/1.21.23.01/lib/x86_64/libminecraftpe.so+0xefb2ba0 [0x269c32ba0]
#586 LINKER (null)+0x2685b3222 in /Users/macos/Library/Application Support/mcpelauncher/versions/1.21.23.01/lib/x86_64/libminecraftpe.so+0xd933222 [0x2685b3222]
#596 LINKER (null)+0x26183b819 in /Users/macos/Library/Application Support/mcpelauncher/versions/1.21.23.01/lib/x86_64/libminecraftpe.so+0x6bbb819 [0x26183b819]
#598 LINKER (null)+0x2685b4618 in /Users/macos/Library/Application Support/mcpelauncher/versions/1.21.23.01/lib/x86_64/libminecraftpe.so+0xd934618 [0x2685b4618]
#616 LINKER (null)+0x26a2689b0 in /Users/macos/Library/Application Support/mcpelauncher/versions/1.21.23.01/lib/x86_64/libminecraftpe.so+0xf5e89b0 [0x26a2689b0]
#637 LINKER (null)+0x26a0e1608 in /Users/macos/Library/Application Support/mcpelauncher/versions/1.21.23.01/lib/x86_64/libminecraftpe.so+0xf461608 [0x26a0e1608]
#643 LINKER (null)+0x26a0e1588 in /Users/macos/Library/Application Support/mcpelauncher/versions/1.21.23.01/lib/x86_64/libminecraftpe.so+0xf461588 [0x26a0e1588]
#656 LINKER (null)+0x264e60f8c in /Users/macos/Library/Application Support/mcpelauncher/versions/1.21.23.01/lib/x86_64/libminecraftpe.so+0xa1e0f8c [0x264e60f8c]
#667 LINKER (null)+0x264e60e90 in /Users/macos/Library/Application Support/mcpelauncher/versions/1.21.23.01/lib/x86_64/libminecraftpe.so+0xa1e0e90 [0x264e60e90]
#671 LINKER (null)+0x264e60e90 in /Users/macos/Library/Application Support/mcpelauncher/versions/1.21.23.01/lib/x86_64/libminecraftpe.so+0xa1e0e90 [0x264e60e90]
#681 LINKER (null)+0x0 in /Users/macos/Library/Application Support/mcpelauncher/versions/1.21.23.01/lib/x86_64/libminecraftpe.so+0xd930010 [0x2685b0010]
#682 LINKER (null)+0x0 in /Users/macos/Library/Application Support/mcpelauncher/versions/1.21.23.01/lib/x86_64/libminecraftpe.so+0xd930030 [0x2685b0030]
#683 LINKER (null)+0x0 in /Users/macos/Library/Application Support/mcpelauncher/versions/1.21.23.01/lib/x86_64/libminecraftpe.so+0xd930040 [0x2685b0040]
#684 LINKER (null)+0x0 in /Users/macos/Library/Application Support/mcpelauncher/versions/1.21.23.01/lib/x86_64/libminecraftpe.so+0xd92ffe0 [0x2685affe0]
#697 LINKER (null)+0x25ac80000 in /Users/macos/Library/Application Support/mcpelauncher/versions/1.21.23.01/lib/x86_64/libminecraftpe.so+ 0x0 [0x25ac80000]
#698 LINKER (null)+0x25ac80000 in /Users/macos/Library/Application Support/mcpelauncher/versions/1.21.23.01/lib/x86_64/libminecraftpe.so+ 0x0 [0x25ac80000]
#789 LINKER (null)+0x0 in /Users/macos/Library/Application Support/mcpelauncher/versions/1.21.23.01/lib/x86_64/libminecraftpe.so+0xd930010 [0x2685b0010]
#790 LINKER (null)+0x0 in /Users/macos/Library/Application Support/mcpelauncher/versions/1.21.23.01/lib/x86_64/libminecraftpe.so+0xd930030 [0x2685b0030]
#791 LINKER (null)+0x0 in /Users/macos/Library/Application Support/mcpelauncher/versions/1.21.23.01/lib/x86_64/libminecraftpe.so+0xd930040 [0x2685b0040]
#792 LINKER (null)+0x0 in /Users/macos/Library/Application Support/mcpelauncher/versions/1.21.23.01/lib/x86_64/libminecraftpe.so+0xd92ffe0 [0x2685affe0]
program failed with unix signal number: 10

Process exited with unexpected exit code: 10

- I want to know if someone can help me to fix the problem, 'cause before it worked perfectly well, without bugs or anything. 

![Captura de pantalla 2024-09-15 a la(s) 23 36 28](https://github.com/user-attachments/assets/83be1fcc-624e-4b44-9b9d-ad46aa635bbb)
![Captura de pantalla 2024-09-15 a la(s) 23 36 19](https://github.com/user-attachments/assets/b10c44c2-b87b-4efc-b688-dfa072302eaf)

 - OS: 13.6.3 Ventura
 - Version v1.0.1-macOS-x86_64-0.2.477 (build 477)
 - Installation Type: dmg

I could make it worked installing a previous version, but it's rare, because this version works without any problem, but now don't.

 #904

**Comment by ChristopherHX** [comment]
Fixed in release v0.16.0 for 1.21.30+ (Yes macOS is now on 0.x again)

**Comment by ChristopherHX** [comment]
Regarding the second bug, logout and login in settings.

~~You might got an mail, from google telling you they signed you out~~ False positive, it's just more verbose now

**Comment by ChristopherHX** [comment]
On the Other hand.

Your dns cannot resolve a google domain, the check changed as well
