### ISSUE TITLE
Support 1.21.30.03

### ISSUE THREAD

**Issue by dawsonc623** [minecraft-linux/mcpelauncher-manifest#1041]
**Is your feature request related to a problem? Please describe.**
This version is needed to play with other players on version 1.21.30.03

**Describe the solution you'd like**
Add support for this version

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by jplatte** [comment]
As described on https://github.com/minecraft-linux/mcpelauncher-manifest/issues/797, it works (for me) with the commandline flag `-df`.

Originally, two or three days ago audio was broken as described there. However now with v1.0.0 of mcpelauncher, audio works but I get "Please check your Keyboard Layout. No Fallback Implemented" in a separate window (window title "EGLUT Unknown Key") a couple of times. Fortunately I don't see it when Minecraft is fullscreen, and no keyboard functionality seems to actually be broken.

**Comment by ChristopherHX** [comment]
> window title "EGLUT Unknown Key")

You are on a **debug** build then, this is for diagnosing issues while developing

Those errors are suppressed by -DNDEBUG / Release mode of cmake

**Comment by ChristopherHX** [comment]
This feature request has insufficient details, because 1.21.30 were supported by v1.0.x releases **before** this issue has been opened.
