### ISSUE TITLE
Minecraft crashes on launch macOS sequoia

### ISSUE THREAD

**Issue by KeyFlyz** [minecraft-linux/mcpelauncher-manifest#1043]
This is the log file I've tried previous versions of Minecraft and still same results**Describe the bug**06:02:02 Info  [Launcher] Version: client 4c5f4fd / manifest 80770c4
06:02:02 Info  [Launcher] OS: macOS, Arch: x86_64
06:02:02 Info  [Launcher] CPU: GenuineIntel Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
06:02:02 Info  [Launcher] CPU supports SSSE3: YES
06:02:02 Info  [Launcher] Reading Launcher Settings File: /Users/keyflysmacbook/Library/Application Support/mcpelauncher/mcpelauncher-client-settings.txt
06:02:02 Info  [Launcher] Applied Launcher Settings
06:02:02 Trace [Launcher] Loading android libraries
06:02:02 Trace [Launcher] linker loaded
06:02:02 Trace [REDIRECT] /data/data/com.mojang.minecraftpe to /Users/keyflysmacbook/Library/Application Support/mcpelauncher/
06:02:02 Trace [REDIRECT] /data/data/Applications/Minecraft Bedrock Launcher.app/Contents/proc/1319/cmdline to /Users/keyflysmacbook/Library/Application Support/mcpelauncher/
06:02:02 Trace [REDIRECT] /data/data/Applications/Minecraft Bedrock Launcher.app/Contents/MacOS/./mcpelauncher-client to /Users/keyflysmacbook/Library/Application Support/mcpelauncher/
06:02:02 Trace [REDIRECT] /data/data to /Users/keyflysmacbook/Library/Application Support/mcpelauncher/
06:02:02 Trace [REDIRECT] . to /Users/keyflysmacbook/Library/Application Support/mcpelauncher/versions/1.21.30.03/assets/
06:02:02 Trace [REDIRECT] /proc to /Users/keyflysmacbook/Library/Application Support/mcpelauncher/proc/
06:02:02 Trace [REDIRECT] /sys to /Users/keyflysmacbook/Library/Application Support/mcpelauncher/sys/
06:02:02 Trace [LinkerUtils] Loaded OS library libm.dylib
06:02:02 Trace [LinkerUtils] Loaded OS library libz.dylib
06:02:02 Warn  [FMOD] Failed to load host libfmod: 'Failed to find data file: lib/native/x86_64/libfmod.dylib', use experimental pulseaudio backend if available
06:02:02 Trace [Launcher] Loading Minecraft library
linker: mcpelauncher_linker_notifylldb /Users/keyflysmacbook/Library/Application Support/mcpelauncher/versions/1.21.30.03/lib/x86_64/libc++_shared.so 0x1155c0000
linker: mcpelauncher_linker_notifylldb /Users/keyflysmacbook/Library/Application Support/mcpelauncher/versions/1.21.30.03/lib/x86_64/libfmod.so 0x115740000
06:02:03 Error [MinecraftUtils] Failed to load Minecraft: dlopen failed: cannot locate symbol "glBindRenderbuffer" referenced by "/Users/keyflysmacbook/Library/Application Support/mcpelauncher/versions/1.21.30.03/lib/x86_64/libminecraftpe.so"...
06:02:03 Info  [Launcher] Loading gamepad mappings
06:02:03 Trace [Launcher] Loading gamepad mappings: /Applications/Minecraft Bedrock Launcher.app/Contents/Resources/mcpelauncher/gamecontrollerdb.txt
06:02:03 Info  [Launcher] Creating window
linker: mcpelauncher_linker_notifylldb /Users/keyflysmacbook/Library/Application Support/mcpelauncher/versions/1.21.30.03/lib/x86_64/libc++_shared.so 0x1185c0000
linker: mcpelauncher_linker_notifylldb /Users/keyflysmacbook/Library/Application Support/mcpelauncher/versions/1.21.30.03/lib/x86_64/libminecraftpe.so 0x11b580000
Found hook: _ZN11AppPlatform16showMousePointerEv @ 0x10f96cb00
Found hook: _ZN11AppPlatform16hideMousePointerEv @ 0x10f96cae0
Found hook: _ZN11AppPlatform17setFullscreenModeE14FullscreenMode @ 0x10f96cb20
Found hook: _ZN4FMOD6System4initEijPv @ 0x10fabe220
Found hook: _ZN3rtc10getifaddrsEPP7ifaddrs @ 0x10fb15670
Found hook: _ZN3rtc11freeifaddrsEP7ifaddrs @ 0x10fb15a30
06:02:05 Info  [Launcher] Loaded Minecraft library
06:02:05 Debug [Launcher] Minecraft is at offset 0x11B580000
06:02:05 Info  [Launcher] Game version: 0.0.0.0
06:02:05 Info  [Launcher] Applying patches
06:02:05 Debug [CorePatches] Failed to patch, vtable _ZTV21AppPlatform_android23 not found
06:02:05 Info  [Launcher] Initializing JNI
06:02:05 Error [JniSupport] Missing native symbol: Java_com_mojang_minecraftpe_MainActivity_nativeRegisterThis
06:02:05 Error [JniSupport] Missing native symbol: Java_com_mojang_minecraftpe_MainActivity_nativeInitializeWithApplicationContext
06:02:05 Error [JniSupport] Missing native symbol: Java_com_mojang_minecraftpe_MainActivity_nativeUnregisterThis
06:02:05 Error [JniSupport] Missing native symbol: Java_com_mojang_minecraftpe_MainActivity_nativeInitializeXboxLive
06:02:05 Error [JniSupport] Missing native symbol: Java_com_mojang_minecraftpe_MainActivity_nativeinitializeLibHttpClient
06:02:05 Error [JniSupport] Missing native symbol: Java_com_mojang_minecraftpe_MainActivity_nativeInitializeLibHttpClient
06:02:05 Error [JniSupport] Missing native symbol: Java_com_microsoft_xal_browser_WebView_urlOperationSucceeded
06:02:05 Error [JniSupport] Missing native symbol: Java_com_mojang_minecraftpe_PlayIntegrity_nativePlayIntegrityComplete
06:02:05 Trace [Minecraft] Entering JNI_OnLoad 0x7000042c3000
06:02:05 Trace [Minecraft] JNI_OnLoad completed
06:02:05 Trace [JniSupport] Invoking nativeRegisterThis
06:02:05 Trace [JniSupport] Invoking ANativeActivity_onCreate
06:02:05 Info  [Launcher] Executing main thread
06:02:05 Warn  [Main] Android stub called
06:02:05 Warn  [Main] Android stub called
06:02:05 Warn  [Main] Android stub called
06:02:05 Warn  [Main] Android stub called
06:02:05 Info  [Minecraft] android_main starting. internalDataPath is '/internal', externalDataPath is '/external'
06:02:05 Trace [JniSupport] Invoking start activity callbacks
06:02:05 Error [MCPE] *** setCachedDeviceId(254624cb-50b8-422e-824f-9ecb8cb93a6f)
06:02:05 Info  [Bedrock] configureBreakpad with directory: /crash, sessionid is: 6b9b1a90-798a-4c0b-b398-29489fc39858
06:02:05 Info  [Bedrock] configureBreakpad called, directory is: /crash, sessionid is: 6b9b1a90-798a-4c0b-b398-29489fc39858
06:02:05 Info  [Minecraft] NO LOG FILE! - AppPlatform_android::setStorageDirectory - using External dir (NEW) - CurrentFileStoragePath is now '/Users/keyflysmacbook/Library/Application Support/mcpelauncher/'
06:02:05 Warn  [Minecraft] NO LOG FILE! - [Graphics] The graphics context was gained
06:02:05 Warn  [Minecraft] NO LOG FILE! - [Graphics] The graphics context was gained
06:02:05 Warn  [Minecraft] MinecraftGame::init && MinecraftGame::setSize!
06:02:05 Warn  [FakeEGL] eglQueryString 308d
06:02:05 Warn  [Main] Android stub called
06:02:05 Info  [GL] Vendor: Google Inc.
06:02:05 Info  [GL] Renderer: ANGLE (ATI Technologies Inc., AMD Radeon Pro 5500M OpenGL Engine, OpenGL 4.1 core)
06:02:05 Info  [GL] Version: OpenGL ES 3.0.0 (ANGLE 2.1.14073 git hash: 26930173647b)
06:02:05 Info  [GL] Vendor: Google Inc.
06:02:05 Info  [GL] Renderer: ANGLE (ATI Technologies Inc., AMD Radeon Pro 5500M OpenGL Engine, OpenGL 4.1 core)
06:02:05 Info  [GL] Version: OpenGL ES 3.0.0 (ANGLE 2.1.14073 git hash: 26930173647b)
06:02:05 Warn  [Main] Android stub called
2024-09-23 06:02:05.237 mcpelauncher-client[1319:38143] +[IMKClient subclass]: chose IMKClient_Legacy
2024-09-23 06:02:05.237 mcpelauncher-client[1319:38143] +[IMKInputSession subclass]: chose IMKInputSession_Legacy
linker: mcpelauncher_linker_notifylldb /Users/keyflysmacbook/Library/Application Support/mcpelauncher/versions/1.21.30.03/lib/x86_64/libMediaDecoders_Android.so 0x130000000

06:02:05 Info  [GL] Vendor: Google Inc.
06:02:05 Info  [GL] Renderer: ANGLE (ATI Technologies Inc., AMD Radeon Pro 5500M OpenGL Engine, OpenGL 4.1 core)
06:02:05 Info  [GL] Version: OpenGL ES 3.0.0 (ANGLE 2.1.14073 git hash: 26930173647b)
06:02:05 Warn  [Main] Android stub called
Signal 10 received
Backtrace elements: 3
#0 0   mcpelauncher-client                 0x000000010fab6b28 _ZN12CrashHandler12handleSignalEiPv + 344
#1 1   mcpelauncher-client                 0x000000010fab6f55 _ZN12CrashHandler15handle_fs_faultEiPvS0_ + 133
#2 2   libsystem_platform.dylib            0x00007ff81a20de9d _sigtramp + 29
Dumping stack...
#9 LINKER (null)+0x115870a88 in /Users/keyflysmacbook/Library/Application Support/mcpelauncher/versions/1.21.30.03/lib/x86_64/libfmod.so+0x130a88 [0x115870a88]
#47 LINKER (null)+0x115867ec8 in /Users/keyflysmacbook/Library/Application Support/mcpelauncher/versions/1.21.30.03/lib/x86_64/libfmod.so+0x127ec8 [0x115867ec8]
#153 LINKER (null)+0x1158891b8 in /Users/keyflysmacbook/Library/Application Support/mcpelauncher/versions/1.21.30.03/lib/x86_64/libfmod.so+0x1491b8 [0x1158891b8]
#154 LINKER (null)+0x11583a3c7 in /Users/keyflysmacbook/Library/Application Support/mcpelauncher/versions/1.21.30.03/lib/x86_64/libfmod.so+0xfa3c7 [0x11583a3c7]
#162 LINKER (null)+0x11583b5af in /Users/keyflysmacbook/Library/Application Support/mcpelauncher/versions/1.21.30.03/lib/x86_64/libfmod.so+0xfb5af [0x11583b5af]
#163 LINKER (null)+0x11588915c in /Users/keyflysmacbook/Library/Application Support/mcpelauncher/versions/1.21.30.03/lib/x86_64/libfmod.so+0x14915c [0x11588915c]
#168 LINKER (null)+0x1157c6759 in /Users/keyflysmacbook/Library/Application Support/mcpelauncher/versions/1.21.30.03/lib/x86_64/libfmod.so+0x86759 [0x1157c6759]
#174 LINKER (null)+0x1157aa2fc in /Users/keyflysmacbook/Library/Application Support/mcpelauncher/versions/1.21.30.03/lib/x86_64/libfmod.so+0x6a2fc [0x1157aa2fc]
#180 LINKER (null)+0x1157b7a71 in /Users/keyflysmacbook/Library/Application Support/mcpelauncher/versions/1.21.30.03/lib/x86_64/libfmod.so+0x77a71 [0x1157b7a71]
#190 LINKER (null)+0x1157ab93b in /Users/keyflysmacbook/Library/Application Support/mcpelauncher/versions/1.21.30.03/lib/x86_64/libfmod.so+0x6b93b [0x1157ab93b]
#194 LINKER FMOD::System::setOutput(FMOD_OUTPUTTYPE)+0x35 in /Users/keyflysmacbook/Library/Application Support/mcpelauncher/versions/1.21.30.03/lib/x86_64/libfmod.so+0xf1845 [0x115831845]
#220 LINKER (null)+0x115790296 in /Users/keyflysmacbook/Library/Application Support/mcpelauncher/versions/1.21.30.03/lib/x86_64/libfmod.so+0x50296 [0x115790296]
#224 LINKER (null)+0x115791b5f in /Users/keyflysmacbook/Library/Application Support/mcpelauncher/versions/1.21.30.03/lib/x86_64/libfmod.so+0x51b5f [0x115791b5f]
#226 LINKER FMOD::System::getVersion(unsigned int*)+0x86 in /Users/keyflysmacbook/Library/Application Support/mcpelauncher/versions/1.21.30.03/lib/x86_64/libfmod.so+0xf47c2 [0x1158347c2]
#234 LINKER (null)+0x12980289c in /Users/keyflysmacbook/Library/Application Support/mcpelauncher/versions/1.21.30.03/lib/x86_64/libminecraftpe.so+0xe28289c [0x12980289c]
#246 LINKER (null)+0x12a0350b2 in /Users/keyflysmacbook/Library/Application Support/mcpelauncher/versions/1.21.30.03/lib/x86_64/libminecraftpe.so+0xeab50b2 [0x12a0350b2]
#247 LINKER (null)+0x12ac34478 in /Users/keyflysmacbook/Library/Application Support/mcpelauncher/versions/1.21.30.03/lib/x86_64/libminecraftpe.so+0xf6b4478 [0x12ac34478]
#248 LINKER operator new(unsigned long)+0x25 in /Users/keyflysmacbook/Library/Application Support/mcpelauncher/versions/1.21.30.03/lib/x86_64/libminecraftpe.so+0xeaa95b5 [0x12a0295b5]
#252 LINKER (null)+0x129802770 in /Users/keyflysmacbook/Library/Application Support/mcpelauncher/versions/1.21.30.03/lib/x86_64/libminecraftpe.so+0xe282770 [0x129802770]
#253 LINKER (null)+0x12a85c488 in /Users/keyflysmacbook/Library/Application Support/mcpelauncher/versions/1.21.30.03/lib/x86_64/libminecraftpe.so+0xf2dc488 [0x12a85c488]
#255 LINKER (null)+0x11586db78 in /Users/keyflysmacbook/Library/Application Support/mcpelauncher/versions/1.21.30.03/lib/x86_64/libfmod.so+0x12db78 [0x11586db78]
#256 LINKER (null)+0x11579fa84 in /Users/keyflysmacbook/Library/Application Support/mcpelauncher/versions/1.21.30.03/lib/x86_64/libfmod.so+0x5fa84 [0x11579fa84]
#258 LINKER (null)+0xac in /Users/keyflysmacbook/Library/Application Support/mcpelauncher/versions/1.21.30.03/lib/x86_64/libfmod.so+0x50353 [0x115790353]
#270 LINKER (null)+0x1232295ec in /Users/keyflysmacbook/Library/Application Support/mcpelauncher/versions/1.21.30.03/lib/x86_64/libminecraftpe.so+0x7ca95ec [0x1232295ec]
#293 LINKER (null)+0x12ad686b8 in /Users/keyflysmacbook/Library/Application Support/mcpelauncher/versions/1.21.30.03/lib/x86_64/libminecraftpe.so+0xf7e86b8 [0x12ad686b8]
#301 LINKER (null)+0x12a85c488 in /Users/keyflysmacbook/Library/Application Support/mcpelauncher/versions/1.21.30.03/lib/x86_64/libminecraftpe.so+0xf2dc488 [0x12a85c488]
#306 LINKER (null)+0x12adc04a0 in /Users/keyflysmacbook/Library/Application Support/mcpelauncher/versions/1.21.30.03/lib/x86_64/libminecraftpe.so+0xf8404a0 [0x12adc04a0]
#308 LINKER (null)+0x12ad686b8 in /Users/keyflysmacbook/Library/Application Support/mcpelauncher/versions/1.21.30.03/lib/x86_64/libminecraftpe.so+0xf7e86b8 [0x12ad686b8]
#444 LINKER (null)+0x12213d498 in /Users/keyflysmacbook/Library/Application Support/mcpelauncher/versions/1.21.30.03/lib/x86_64/libminecraftpe.so+0x6bbd498 [0x12213d498]
#456 LINKER (null)+0x122125f4d in /Users/keyflysmacbook/Library/Application Support/mcpelauncher/versions/1.21.30.03/lib/x86_64/libminecraftpe.so+0x6ba5f4d [0x122125f4d]
#458 LINKER (null)+0x12aebaf10 in /Users/keyflysmacbook/Library/Application Support/mcpelauncher/versions/1.21.30.03/lib/x86_64/libminecraftpe.so+0xf93af10 [0x12aebaf10]
#460 LINKER (null)+0x12aebaf10 in /Users/keyflysmacbook/Library/Application Support/mcpelauncher/versions/1.21.30.03/lib/x86_64/libminecraftpe.so+0xf93af10 [0x12aebaf10]
#463 LINKER (null)+0x12aebaa60 in /Users/keyflysmacbook/Library/Application Support/mcpelauncher/versions/1.21.30.03/lib/x86_64/libminecraftpe.so+0xf93aa60 [0x12aebaa60]
#472 LINKER (null)+0x122254424 in /Users/keyflysmacbook/Library/Application Support/mcpelauncher/versions/1.21.30.03/lib/x86_64/libminecraftpe.so+0x6cd4424 [0x122254424]
#478 LINKER (null)+0x12adc04a0 in /Users/keyflysmacbook/Library/Application Support/mcpelauncher/versions/1.21.30.03/lib/x86_64/libminecraftpe.so+0xf8404a0 [0x12adc04a0]
#483 LINKER (null)+0x12a735750 in /Users/keyflysmacbook/Library/Application Support/mcpelauncher/versions/1.21.30.03/lib/x86_64/libminecraftpe.so+0xf1b5750 [0x12a735750]
#484 LINKER (null)+0x1221c0622 in /Users/keyflysmacbook/Library/Application Support/mcpelauncher/versions/1.21.30.03/lib/x86_64/libminecraftpe.so+0x6c40622 [0x1221c0622]
#494 LINKER (null)+0x12214a288 in /Users/keyflysmacbook/Library/Application Support/mcpelauncher/versions/1.21.30.03/lib/x86_64/libminecraftpe.so+0x6bca288 [0x12214a288]
#513 LINKER (null)+0x12ad78670 in /Users/keyflysmacbook/Library/Application Support/mcpelauncher/versions/1.21.30.03/lib/x86_64/libminecraftpe.so+0xf7f8670 [0x12ad78670]
#535 LINKER (null)+0x12a72f5b8 in /Users/keyflysmacbook/Library/Application Support/mcpelauncher/versions/1.21.30.03/lib/x86_64/libminecraftpe.so+0xf1af5b8 [0x12a72f5b8]
#541 LINKER (null)+0x12a72f4b8 in /Users/keyflysmacbook/Library/Application Support/mcpelauncher/versions/1.21.30.03/lib/x86_64/libminecraftpe.so+0xf1af4b8 [0x12a72f4b8]
#547 LINKER (null)+0x12a72f438 in /Users/keyflysmacbook/Library/Application Support/mcpelauncher/versions/1.21.30.03/lib/x86_64/libminecraftpe.so+0xf1af438 [0x12a72f438]
#553 LINKER (null)+0x12a72f3b8 in /Users/keyflysmacbook/Library/Application Support/mcpelauncher/versions/1.21.30.03/lib/x86_64/libminecraftpe.so+0xf1af3b8 [0x12a72f3b8]
#583 LINKER (null)+0x12a72f138 in /Users/keyflysmacbook/Library/Application Support/mcpelauncher/versions/1.21.30.03/lib/x86_64/libminecraftpe.so+0xf1af138 [0x12a72f138]
#586 LINKER (null)+0x128f70552 in /Users/keyflysmacbook/Library/Application Support/mcpelauncher/versions/1.21.30.03/lib/x86_64/libminecraftpe.so+0xd9f0552 [0x128f70552]
#596 LINKER (null)+0x122147af9 in /Users/keyflysmacbook/Library/Application Support/mcpelauncher/versions/1.21.30.03/lib/x86_64/libminecraftpe.so+0x6bc7af9 [0x122147af9]
#598 LINKER (null)+0x128f71948 in /Users/keyflysmacbook/Library/Application Support/mcpelauncher/versions/1.21.30.03/lib/x86_64/libminecraftpe.so+0xd9f1948 [0x128f71948]
#616 LINKER (null)+0x12ad60428 in /Users/keyflysmacbook/Library/Application Support/mcpelauncher/versions/1.21.30.03/lib/x86_64/libminecraftpe.so+0xf7e0428 [0x12ad60428]
#637 LINKER (null)+0x12abd86e8 in /Users/keyflysmacbook/Library/Application Support/mcpelauncher/versions/1.21.30.03/lib/x86_64/libminecraftpe.so+0xf6586e8 [0x12abd86e8]
#643 LINKER (null)+0x12abd8668 in /Users/keyflysmacbook/Library/Application Support/mcpelauncher/versions/1.21.30.03/lib/x86_64/libminecraftpe.so+0xf658668 [0x12abd8668]
#656 LINKER (null)+0x12573b38c in /Users/keyflysmacbook/Library/Application Support/mcpelauncher/versions/1.21.30.03/lib/x86_64/libminecraftpe.so+0xa1bb38c [0x12573b38c]
#667 LINKER (null)+0x12573b290 in /Users/keyflysmacbook/Library/Application Support/mcpelauncher/versions/1.21.30.03/lib/x86_64/libminecraftpe.so+0xa1bb290 [0x12573b290]
#671 LINKER (null)+0x12573b290 in /Users/keyflysmacbook/Library/Application Support/mcpelauncher/versions/1.21.30.03/lib/x86_64/libminecraftpe.so+0xa1bb290 [0x12573b290]
#681 LINKER (null)+0x0 in /Users/keyflysmacbook/Library/Application Support/mcpelauncher/versions/1.21.30.03/lib/x86_64/libminecraftpe.so+0xd9ed340 [0x128f6d340]
#682 LINKER (null)+0x0 in /Users/keyflysmacbook/Library/Application Support/mcpelauncher/versions/1.21.30.03/lib/x86_64/libminecraftpe.so+0xd9ed360 [0x128f6d360]
#683 LINKER (null)+0x0 in /Users/keyflysmacbook/Library/Application Support/mcpelauncher/versions/1.21.30.03/lib/x86_64/libminecraftpe.so+0xd9ed370 [0x128f6d370]
#684 LINKER (null)+0x0 in /Users/keyflysmacbook/Library/Application Support/mcpelauncher/versions/1.21.30.03/lib/x86_64/libminecraftpe.so+0xd9ed310 [0x128f6d310]
#697 LINKER (null)+0x11b580000 in /Users/keyflysmacbook/Library/Application Support/mcpelauncher/versions/1.21.30.03/lib/x86_64/libminecraftpe.so+ 0x0 [0x11b580000]
#698 LINKER (null)+0x11b580000 in /Users/keyflysmacbook/Library/Application Support/mcpelauncher/versions/1.21.30.03/lib/x86_64/libminecraftpe.so+ 0x0 [0x11b580000]
#789 LINKER (null)+0x0 in /Users/keyflysmacbook/Library/Application Support/mcpelauncher/versions/1.21.30.03/lib/x86_64/libminecraftpe.so+0xd9ed340 [0x128f6d340]
#790 LINKER (null)+0x0 in /Users/keyflysmacbook/Library/Application Support/mcpelauncher/versions/1.21.30.03/lib/x86_64/libminecraftpe.so+0xd9ed360 [0x128f6d360]
#791 LINKER (null)+0x0 in /Users/keyflysmacbook/Library/Application Support/mcpelauncher/versions/1.21.30.03/lib/x86_64/libminecraftpe.so+0xd9ed370 [0x128f6d370]
#792 LINKER (null)+0x0 in /Users/keyflysmacbook/Library/Application Support/mcpelauncher/versions/1.21.30.03/lib/x86_64/libminecraftpe.so+0xd9ed310 [0x128f6d310]
program failed with unix signal number: 10

**Comment by ChristopherHX** [comment]
Fixed in release v0.16.0 for 1.21.30+ (Yes macOS is now on 0.x again)
