### ISSUE TITLE
launcher clashed

### ISSUE THREAD

**Issue by rif4869** [minecraft-linux/mcpelauncher-manifest#1044]
**Describe the bug**
minecraft bedrock launcher ver1.21.30 crashes when starting

**To Reproduce**
1. Click on 'PLAY'

**Expected behavior**
minecraft is starting

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - Version v1.0.1-macOS-x86_64-0.2.477(build477)
 - Installation Type [e.g. AppImage, flatpak, dmg or built from source]

**Additional context**

**Comment by ChristopherHX** [comment]
Fixed in release v0.16.0 for 1.21.30+ (Yes macOS is now on 0.x again)
