### ISSUE TITLE
闪退

### ISSUE THREAD

**Issue by huangyucheni** [minecraft-linux/mcpelauncher-manifest#1046]
**Describe the bug**
启动 MINECRAFT 1.21.31.04 (X86_64) 的一瞬间会闪退

**To Reproduce**
1 启动 MINECRAFT 1.21.31.04 (X86_64)
2 出现 MINECRAFT 1.21.31.04 (X86_64)的窗口
3 闪退

**崩溃日志**
13:17:58 Info  [Launcher] Version: client 4c5f4fd / manifest 80770c4
13:17:58 Info  [Launcher] OS: macOS, Arch: x86_64
13:17:58 Info  [Launcher] CPU: GenuineIntel Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
13:17:58 Info  [Launcher] CPU supports SSSE3: YES
13:17:58 Info  [Launcher] Reading Launcher Settings File: /Applications/Minecraft Bedrock Launcher.app/Contents/Resources/mcpelauncher-client-settings.txt
13:17:58 Info  [Launcher] Applied Launcher Settings
13:17:58 Trace [Launcher] Loading android libraries
13:17:58 Trace [Launcher] linker loaded
13:17:58 Trace [REDIRECT] /data/data/com.mojang.minecraftpe to /Applications/Minecraft Bedrock Launcher.app/Contents/Resources/
13:17:58 Trace [REDIRECT] /data/data/Applications/Minecraft Bedrock Launcher.app/Contents/proc/15124/cmdline to /Applications/Minecraft Bedrock Launcher.app/Contents/Resources/
13:17:58 Trace [REDIRECT] /data/data/Applications/Minecraft Bedrock Launcher.app/Contents/MacOS/./mcpelauncher-client to /Applications/Minecraft Bedrock Launcher.app/Contents/Resources/
13:17:58 Trace [REDIRECT] /data/data to /Applications/Minecraft Bedrock Launcher.app/Contents/Resources/
13:17:58 Trace [REDIRECT] . to /Users/chenshengying/Library/Application Support/mcpelauncher/versions/1.21.31.04/assets/
13:17:58 Trace [REDIRECT] /proc to /Applications/Minecraft Bedrock Launcher.app/Contents/Resources/proc/
13:17:58 Trace [REDIRECT] /sys to /Applications/Minecraft Bedrock Launcher.app/Contents/Resources/sys/
13:17:58 Trace [LinkerUtils] Loaded OS library libm.dylib
13:17:58 Trace [LinkerUtils] Loaded OS library libz.dylib
13:17:58 Warn  [FMOD] Failed to load host libfmod: 'Failed to find data file: lib/native/x86_64/libfmod.dylib', use experimental pulseaudio backend if available
13:17:58 Trace [Launcher] Loading Minecraft library
linker: mcpelauncher_linker_notifylldb /Users/chenshengying/Library/Application Support/mcpelauncher/versions/1.21.31.04/lib/x86_64/libc++_shared.so 0x10e600000
linker: mcpelauncher_linker_notifylldb /Users/chenshengying/Library/Application Support/mcpelauncher/versions/1.21.31.04/lib/x86_64/libfmod.so 0x10e740000
13:18:00 Error [MinecraftUtils] Failed to load Minecraft: dlopen failed: cannot locate symbol "glBindRenderbuffer" referenced by "/Users/chenshengying/Library/Application Support/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so"...
13:18:00 Info  [Launcher] Loading gamepad mappings
13:18:00 Info  [Launcher] Creating window
linker: mcpelauncher_linker_notifylldb /Users/chenshengying/Library/Application Support/mcpelauncher/versions/1.21.31.04/lib/x86_64/libc++_shared.so 0x110800000
linker: mcpelauncher_linker_notifylldb /Users/chenshengying/Library/Application Support/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so 0x112780000
Found hook: _ZN11AppPlatform16showMousePointerEv @ 0x1082fdb00
Found hook: _ZN11AppPlatform16hideMousePointerEv @ 0x1082fdae0
Found hook: _ZN11AppPlatform17setFullscreenModeE14FullscreenMode @ 0x1082fdb20
Found hook: _ZN4FMOD6System4initEijPv @ 0x10844f220
Found hook: _ZN3rtc10getifaddrsEPP7ifaddrs @ 0x1084a6670
Found hook: _ZN3rtc11freeifaddrsEP7ifaddrs @ 0x1084a6a30
13:18:02 Info  [Launcher] Loaded Minecraft library
13:18:02 Debug [Launcher] Minecraft is at offset 0x112780000
13:18:02 Info  [Launcher] Game version: 0.0.0.0
13:18:02 Info  [Launcher] Applying patches
13:18:02 Debug [CorePatches] Failed to patch, vtable _ZTV21AppPlatform_android23 not found
13:18:02 Info  [Launcher] Initializing JNI
13:18:02 Error [JniSupport] Missing native symbol: Java_com_mojang_minecraftpe_MainActivity_nativeRegisterThis
13:18:02 Error [JniSupport] Missing native symbol: Java_com_mojang_minecraftpe_MainActivity_nativeInitializeWithApplicationContext
13:18:02 Error [JniSupport] Missing native symbol: Java_com_mojang_minecraftpe_MainActivity_nativeUnregisterThis
13:18:02 Error [JniSupport] Missing native symbol: Java_com_mojang_minecraftpe_MainActivity_nativeInitializeXboxLive
13:18:02 Error [JniSupport] Missing native symbol: Java_com_mojang_minecraftpe_MainActivity_nativeinitializeLibHttpClient
13:18:02 Error [JniSupport] Missing native symbol: Java_com_mojang_minecraftpe_MainActivity_nativeInitializeLibHttpClient
13:18:02 Error [JniSupport] Missing native symbol: Java_com_microsoft_xal_browser_WebView_urlOperationSucceeded
13:18:02 Error [JniSupport] Missing native symbol: Java_com_mojang_minecraftpe_PlayIntegrity_nativePlayIntegrityComplete
13:18:02 Trace [Minecraft] Entering JNI_OnLoad 0x70000e761000
13:18:02 Trace [Minecraft] JNI_OnLoad completed
13:18:02 Trace [JniSupport] Invoking nativeRegisterThis
13:18:02 Trace [JniSupport] Invoking ANativeActivity_onCreate
13:18:02 Info  [Launcher] Executing main thread
13:18:02 Warn  [Main] Android stub called
13:18:02 Warn  [Main] Android stub called
13:18:02 Warn  [Main] Android stub called
13:18:02 Warn  [Main] Android stub called
13:18:02 Info  [Minecraft] android_main starting. internalDataPath is '/internal', externalDataPath is '/external'
13:18:02 Trace [JniSupport] Invoking start activity callbacks
13:18:02 Error [MCPE] *** setCachedDeviceId(da2f23c0-e89a-4286-827a-f8ac06f10add)
13:18:02 Info  [Bedrock] configureBreakpad with directory: /crash, sessionid is: df3a3fb8-22cb-4c65-9314-b76c8be686df
13:18:02 Info  [Bedrock] configureBreakpad called, directory is: /crash, sessionid is: df3a3fb8-22cb-4c65-9314-b76c8be686df
13:18:02 Info  [Minecraft] NO LOG FILE! - AppPlatform_android::setStorageDirectory - using External dir (NEW) - CurrentFileStoragePath is now '/Applications/Minecraft Bedrock Launcher.app/Contents/Resources/'
13:18:02 Warn  [Minecraft] NO LOG FILE! - [Graphics] The graphics context was gained
13:18:02 Warn  [Minecraft] NO LOG FILE! - [Graphics] The graphics context was gained
13:18:02 Warn  [Minecraft] MinecraftGame::init && MinecraftGame::setSize!
13:18:02 Warn  [FakeEGL] eglQueryString 308d
13:18:02 Warn  [Main] Android stub called
13:18:02 Info  [GL] Vendor: Google Inc.
13:18:02 Info  [GL] Renderer: ANGLE (ATI Technologies Inc., AMD Radeon Pro 555X OpenGL Engine, OpenGL 4.1 core)
13:18:02 Info  [GL] Version: OpenGL ES 3.0.0 (ANGLE 2.1.14073 git hash: 26930173647b)
13:18:02 Info  [GL] Vendor: Google Inc.
13:18:02 Info  [GL] Renderer: ANGLE (ATI Technologies Inc., AMD Radeon Pro 555X OpenGL Engine, OpenGL 4.1 core)
13:18:02 Info  [GL] Version: OpenGL ES 3.0.0 (ANGLE 2.1.14073 git hash: 26930173647b)
13:18:02 Warn  [Main] Android stub called
linker: mcpelauncher_linker_notifylldb /Users/chenshengying/Library/Application Support/mcpelauncher/versions/1.21.31.04/lib/x86_64/libMediaDecoders_Android.so 0x125600000

13:18:02 Info  [GL] Vendor: Google Inc.
13:18:02 Info  [GL] Renderer: ANGLE (ATI Technologies Inc., AMD Radeon Pro 555X OpenGL Engine, OpenGL 4.1 core)
13:18:02 Info  [GL] Version: OpenGL ES 3.0.0 (ANGLE 2.1.14073 git hash: 26930173647b)
13:18:02 Warn  [Main] Android stub called
Signal 10 received
Backtrace elements: 3
#0 0   mcpelauncher-client                 0x0000000108447b28 _ZN12CrashHandler12handleSignalEiPv + 344
#1 1   mcpelauncher-client                 0x0000000108447f55 _ZN12CrashHandler15handle_fs_faultEiPvS0_ + 133
#2 2   libsystem_platform.dylib            0x00007ff80c4d3fdd _sigtramp + 29
Dumping stack...
#9 LINKER (null)+0x10e870a88 in /Users/chenshengying/Library/Application Support/mcpelauncher/versions/1.21.31.04/lib/x86_64/libfmod.so+0x130a88 [0x10e870a88]
#47 LINKER (null)+0x10e867ec8 in /Users/chenshengying/Library/Application Support/mcpelauncher/versions/1.21.31.04/lib/x86_64/libfmod.so+0x127ec8 [0x10e867ec8]
#153 LINKER (null)+0x10e8891b8 in /Users/chenshengying/Library/Application Support/mcpelauncher/versions/1.21.31.04/lib/x86_64/libfmod.so+0x1491b8 [0x10e8891b8]
#154 LINKER (null)+0x10e83a3c7 in /Users/chenshengying/Library/Application Support/mcpelauncher/versions/1.21.31.04/lib/x86_64/libfmod.so+0xfa3c7 [0x10e83a3c7]
#162 LINKER (null)+0x10e83b5af in /Users/chenshengying/Library/Application Support/mcpelauncher/versions/1.21.31.04/lib/x86_64/libfmod.so+0xfb5af [0x10e83b5af]
#163 LINKER (null)+0x10e88915c in /Users/chenshengying/Library/Application Support/mcpelauncher/versions/1.21.31.04/lib/x86_64/libfmod.so+0x14915c [0x10e88915c]
#168 LINKER (null)+0x10e7c6759 in /Users/chenshengying/Library/Application Support/mcpelauncher/versions/1.21.31.04/lib/x86_64/libfmod.so+0x86759 [0x10e7c6759]
#174 LINKER (null)+0x10e7aa2fc in /Users/chenshengying/Library/Application Support/mcpelauncher/versions/1.21.31.04/lib/x86_64/libfmod.so+0x6a2fc [0x10e7aa2fc]
#180 LINKER (null)+0x10e7b7a71 in /Users/chenshengying/Library/Application Support/mcpelauncher/versions/1.21.31.04/lib/x86_64/libfmod.so+0x77a71 [0x10e7b7a71]
#190 LINKER (null)+0x10e7ab93b in /Users/chenshengying/Library/Application Support/mcpelauncher/versions/1.21.31.04/lib/x86_64/libfmod.so+0x6b93b [0x10e7ab93b]
#194 LINKER FMOD::System::setOutput(FMOD_OUTPUTTYPE)+0x35 in /Users/chenshengying/Library/Application Support/mcpelauncher/versions/1.21.31.04/lib/x86_64/libfmod.so+0xf1845 [0x10e831845]
#220 LINKER (null)+0x10e790296 in /Users/chenshengying/Library/Application Support/mcpelauncher/versions/1.21.31.04/lib/x86_64/libfmod.so+0x50296 [0x10e790296]
#224 LINKER (null)+0x10e791b5f in /Users/chenshengying/Library/Application Support/mcpelauncher/versions/1.21.31.04/lib/x86_64/libfmod.so+0x51b5f [0x10e791b5f]
#226 LINKER FMOD::System::getVersion(unsigned int*)+0x86 in /Users/chenshengying/Library/Application Support/mcpelauncher/versions/1.21.31.04/lib/x86_64/libfmod.so+0xf47c2 [0x10e8347c2]
#234 LINKER (null)+0x120a02dec in /Users/chenshengying/Library/Application Support/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0xe282dec [0x120a02dec]
#246 LINKER (null)+0x121235612 in /Users/chenshengying/Library/Application Support/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0xeab5612 [0x121235612]
#247 LINKER (null)+0x121e348c8 in /Users/chenshengying/Library/Application Support/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0xf6b48c8 [0x121e348c8]
#248 LINKER operator new(unsigned long)+0x25 in /Users/chenshengying/Library/Application Support/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0xeaa9b15 [0x121229b15]
#252 LINKER (null)+0x120a02cc0 in /Users/chenshengying/Library/Application Support/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0xe282cc0 [0x120a02cc0]
#253 LINKER (null)+0x121a5c968 in /Users/chenshengying/Library/Application Support/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0xf2dc968 [0x121a5c968]
#255 LINKER (null)+0x10e86db78 in /Users/chenshengying/Library/Application Support/mcpelauncher/versions/1.21.31.04/lib/x86_64/libfmod.so+0x12db78 [0x10e86db78]
#256 LINKER (null)+0x10e79fa84 in /Users/chenshengying/Library/Application Support/mcpelauncher/versions/1.21.31.04/lib/x86_64/libfmod.so+0x5fa84 [0x10e79fa84]
#258 LINKER (null)+0xac in /Users/chenshengying/Library/Application Support/mcpelauncher/versions/1.21.31.04/lib/x86_64/libfmod.so+0x50353 [0x10e790353]
#270 LINKER (null)+0x11a4288bc in /Users/chenshengying/Library/Application Support/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0x7ca88bc [0x11a4288bc]
#293 LINKER (null)+0x121f68b08 in /Users/chenshengying/Library/Application Support/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0xf7e8b08 [0x121f68b08]
#301 LINKER (null)+0x121a5c968 in /Users/chenshengying/Library/Application Support/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0xf2dc968 [0x121a5c968]
#306 LINKER (null)+0x121fc0900 in /Users/chenshengying/Library/Application Support/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0xf840900 [0x121fc0900]
#308 LINKER (null)+0x121f68b08 in /Users/chenshengying/Library/Application Support/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0xf7e8b08 [0x121f68b08]
#444 LINKER (null)+0x11933c768 in /Users/chenshengying/Library/Application Support/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0x6bbc768 [0x11933c768]
#456 LINKER (null)+0x11932521d in /Users/chenshengying/Library/Application Support/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0x6ba521d [0x11932521d]
#458 LINKER (null)+0x1220bb340 in /Users/chenshengying/Library/Application Support/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0xf93b340 [0x1220bb340]
#460 LINKER (null)+0x1220bb340 in /Users/chenshengying/Library/Application Support/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0xf93b340 [0x1220bb340]
#463 LINKER (null)+0x1220bae90 in /Users/chenshengying/Library/Application Support/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0xf93ae90 [0x1220bae90]
#472 LINKER (null)+0x1194536f4 in /Users/chenshengying/Library/Application Support/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0x6cd36f4 [0x1194536f4]
#478 LINKER (null)+0x121fc0900 in /Users/chenshengying/Library/Application Support/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0xf840900 [0x121fc0900]
#483 LINKER (null)+0x121935c30 in /Users/chenshengying/Library/Application Support/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0xf1b5c30 [0x121935c30]
#484 LINKER (null)+0x1193bf8f2 in /Users/chenshengying/Library/Application Support/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0x6c3f8f2 [0x1193bf8f2]
#494 LINKER (null)+0x119349558 in /Users/chenshengying/Library/Application Support/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0x6bc9558 [0x119349558]
#513 LINKER (null)+0x121f78a90 in /Users/chenshengying/Library/Application Support/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0xf7f8a90 [0x121f78a90]
#535 LINKER (null)+0x12192fa98 in /Users/chenshengying/Library/Application Support/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0xf1afa98 [0x12192fa98]
#541 LINKER (null)+0x12192f998 in /Users/chenshengying/Library/Application Support/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0xf1af998 [0x12192f998]
#547 LINKER (null)+0x12192f918 in /Users/chenshengying/Library/Application Support/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0xf1af918 [0x12192f918]
#553 LINKER (null)+0x12192f898 in /Users/chenshengying/Library/Application Support/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0xf1af898 [0x12192f898]
#583 LINKER (null)+0x12192f618 in /Users/chenshengying/Library/Application Support/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0xf1af618 [0x12192f618]
#586 LINKER (null)+0x120171fa2 in /Users/chenshengying/Library/Application Support/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0xd9f1fa2 [0x120171fa2]
#596 LINKER (null)+0x119346dc9 in /Users/chenshengying/Library/Application Support/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0x6bc6dc9 [0x119346dc9]
#598 LINKER (null)+0x120173398 in /Users/chenshengying/Library/Application Support/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0xd9f3398 [0x120173398]
#616 LINKER (null)+0x121f60878 in /Users/chenshengying/Library/Application Support/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0xf7e0878 [0x121f60878]
#637 LINKER (null)+0x121dd8bb8 in /Users/chenshengying/Library/Application Support/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0xf658bb8 [0x121dd8bb8]
#643 LINKER (null)+0x121dd8b38 in /Users/chenshengying/Library/Application Support/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0xf658b38 [0x121dd8b38]
#656 LINKER (null)+0x11c93cfcc in /Users/chenshengying/Library/Application Support/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0xa1bcfcc [0x11c93cfcc]
#667 LINKER (null)+0x11c93ced0 in /Users/chenshengying/Library/Application Support/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0xa1bced0 [0x11c93ced0]
#671 LINKER (null)+0x11c93ced0 in /Users/chenshengying/Library/Application Support/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0xa1bced0 [0x11c93ced0]
#681 LINKER (null)+0x0 in /Users/chenshengying/Library/Application Support/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0xd9eed90 [0x12016ed90]
#682 LINKER (null)+0x0 in /Users/chenshengying/Library/Application Support/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0xd9eedb0 [0x12016edb0]
#683 LINKER (null)+0x0 in /Users/chenshengying/Library/Application Support/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0xd9eedc0 [0x12016edc0]
#684 LINKER (null)+0x0 in /Users/chenshengying/Library/Application Support/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0xd9eed60 [0x12016ed60]
#697 LINKER (null)+0x112780000 in /Users/chenshengying/Library/Application Support/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+ 0x0 [0x112780000]
#698 LINKER (null)+0x112780000 in /Users/chenshengying/Library/Application Support/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+ 0x0 [0x112780000]
#789 LINKER (null)+0x0 in /Users/chenshengying/Library/Application Support/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0xd9eed90 [0x12016ed90]
#790 LINKER (null)+0x0 in /Users/chenshengying/Library/Application Support/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0xd9eedb0 [0x12016edb0]
#791 LINKER (null)+0x0 in /Users/chenshengying/Library/Application Support/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0xd9eedc0 [0x12016edc0]
#792 LINKER (null)+0x0 in /Users/chenshengying/Library/Application Support/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0xd9eed60 [0x12016ed60]
program failed with unix signal number: 10

Process exited with unexpected exit code: 10

**Desktop (please complete the following information):**
 - OS: macOS
 - Version: 14.6.1
 - Installation Type: Update

**Comment by ChristopherHX** [comment]
Fixed in release v0.16.0 for 1.21.30+ (Yes macOS is now on 0.x again)
