### ISSUE TITLE
Linux mobile invisible

### ISSUE THREAD

**Issue by Henry-Hiles** [minecraft-linux/mcpelauncher-manifest#1047]
**Describe the bug**
The minecraft window is invisible on linux mobile.

**To Reproduce**
1. Install app on gnome mobile (probably other DEs too)
2. Log in
3. Launch
4. See invisible window

**Expected behavior**
The window should be visible.

**Screenshots**
![Screenshot from 2024-10-12 23-54-53](https://github.com/user-attachments/assets/443b497f-190b-424e-bf6a-18995da20dd8)

**Desktop (please complete the following information):**
 - OS: Linux
 - Version 1.0.0
 - Installation Type: Flatpak

**Comment by Henry-Hiles** [comment]
Could actually be a driver issue ig.

**Comment by Henry-Hiles** [comment]
fixed with update

**Comment by ChristopherHX** [comment]
Wait what?

Which update ? (flatpak runtime, flatpak package, OS update), I definetly didn't do anything other than rereleasing (aka rebuilding on latest sdk) the exact same UI of the launcher with a different game client

**Comment by Henry-Hiles** [comment]
To be honest, I'm not sure. I ran both a system and flatpak update and it now works. Not sure what it was, but if it works it works.
