### ISSUE TITLE
Placing End Gateway block crashes game

### ISSUE THREAD

**Issue by Mhowser** [minecraft-linux/mcpelauncher-manifest#105]
I was able to place the End Gateway blocks just fine in my game session, now it keeps crashing everytime I try to place it.

https://0bin.net/paste/LGmPVo4ndDc8vW7k#-MgpPDLpD3iVVBcfigu7UZfQiX6FETVYPSLPp/6itJa

**Comment by MCMrARM** [comment]
Note: the paste has expired.

**Comment by Mhowser** [comment]
This doesn't occur anymore inn the latest versions.
