### ISSUE TITLE
Deferred technical preview wont work and it wont force start it

### ISSUE THREAD

**Issue by Godbacon0304** [minecraft-linux/mcpelauncher-manifest#1062]
In the latest bundles of bravery update instead of saying force deferred rendering it says enable deferred rendering

Now when i go to video it doesn't let me chose it and has the default Minecraft video settings
![Screenshot 2024-11-09 151216](https://github.com/user-attachments/assets/36f5a684-de3b-405a-8015-bb138ee5e1b1)

In the last update render dragon worked fine

**Comment by Godbacon0304** [comment]
I need help please

**Comment by ChristopherHX** [comment]
Report this to BetterRenderdragon not here, this software doesn't support windows.

**Comment by Godbacon0304** [comment]
ty

**Comment by Nudey1** [comment]
![Screenshot (39)](https://github.com/user-attachments/assets/7d65dc81-763d-40ca-a6ac-469b91cb4199)
I have the same problem, I used better renderdragon a few months ago and it worked, I stopped playing minecraft and came back a  few days ago and I noticed this too, hope they fix it. I think the 1.21 update broke it.
