### ISSUE TITLE
Cannot open mcpelauncher-ui-qt

### ISSUE THREAD

**Issue by leonardrua** [minecraft-linux/mcpelauncher-manifest#1063]
**Describe the bug**
Cannot open the qt launcher because the protobuf version is outdated

**To Reproduce**
1. Open mcpelaucher-ui-qt

**Expected behavior**
The launcher open normally

**Screenshots**
![gambar](https://github.com/user-attachments/assets/3fedeca6-4b53-4181-b90b-fe7027c21c9f)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Version: mcpelauncher-linux-git: 1.1.1.r12.gf9ee837-1, mcpelauncher-ui-git: 1.0.1.r0.g992bc7b-1.3
 - Installation Type; chaotic-aur

**Additional context**

**Comment by ChristopherHX** [comment]
Please report this to chaotic aur, not our issue.

> Installation Type; chaotic-aur

Not provided by me, official binaries don't have this packaging problem.

Archlinux evolves faster that the mcpelauncher-ui-qt get's updates from my side, chaotic-aur have to rebuild their package if protobuf changes however they wait for code changes instead.
