### ISSUE TITLE
1.21.44.01 Support

### ISSUE THREAD

**Issue by soahclacipyta** [minecraft-linux/mcpelauncher-manifest#1064]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]: 

Incompatible with latest version of Minecraft Android, rendering Realms unusable.

**Describe the solution you'd like**: 

Kindly add support for 1.21.44.01 :)

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the feature request here.: 

I didn't see it posted so I apologize if this request is redundant.

**Comment by Samenal-sys** [comment]
i havent had a update on launcher for like 20 days and i have the version provide information about your system if you want them to fix the issue although im running with dev mode so try that and allow unverified versions

**Comment by soahclacipyta** [comment]
This is user error, my launcher was out of date. Thank you, your comment helped.
