### ISSUE TITLE
Crash in v1.0.0.549-Appimage-x86_64 and can't open flatpak version

### ISSUE THREAD

**Issue by Saa456** [minecraft-linux/mcpelauncher-manifest#1067]
### **Force close after update appimage and can't open flatpak version**
After update Appimage, I always try when done update. but, in this version, i can't open my minecraft. when the game loading to 99% it wll crash. When open stabble or unverified version, its always the same. before update, the game in that 2 version run normal and no crash, but after this update the game crash. so i tried download flatpak version,but it can't open launcher. 
i dont know whats wrong, This is Gamelog from Appimage version
### Gamelog
`14:20:54 Info  [Launcher] Version: client d081dc7 / manifest 63c0436
14:20:54 Info  [Launcher] OS: Linux, Arch: x86_64
14:20:54 Info  [Launcher] CPU: GenuineIntel Intel(R) Celeron(R) CPU 4205U @ 1.80GHz
14:20:54 Info  [Launcher] CPU supports SSSE3: YES
14:20:54 Info  [Launcher] Reading Launcher Settings File: /home/restanda/.local/share/mcpelauncher/mcpelauncher-client-settings.txt
14:20:54 Info  [Launcher] Applied Launcher Settings
14:20:54 Trace [Launcher] Loading android libraries
14:20:54 Trace [Launcher] linker loaded
14:20:55 Trace [REDIRECT] /data/data/com.mojang.minecraftpe to /home/restanda/.local/share/mcpelauncher/
14:20:55 Trace [REDIRECT] /data/data/tmp/.mount_MinecrInKTEi/usr/proc/4430/cmdline to /home/restanda/.local/share/mcpelauncher/
14:20:55 Trace [REDIRECT] /data/data/tmp/.mount_MinecrInKTEi/usr/bin/./mcpelauncher-client to /home/restanda/.local/share/mcpelauncher/
14:20:55 Trace [REDIRECT] /data/data to /home/restanda/.local/share/mcpelauncher/
14:20:55 Trace [REDIRECT] . to /home/restanda/.local/share/mcpelauncher/versions/1.21.31.04/assets/
14:20:55 Trace [LinkerUtils] Loaded OS library libm.so.6
14:20:55 Trace [LinkerUtils] Loaded OS library libz.so.1
14:20:55 Info  [FMOD] Failed to load host libfmod: 'Failed to find data file: lib/native/x86_64/libfmod.so.12.0', use pulseaudio/sdl3 backend with android fmod if available
14:20:55 Info  [Launcher] Loading gamepad mappings
14:20:55 Trace [Launcher] Loading gamepad mappings: /tmp/.mount_MinecrInKTEi/usr/share/mcpelauncher/gamecontrollerdb.txt
14:20:55 Info  [Launcher] Creating window
14:20:55 Info  [ModLoader] Loading mods
14:20:55 Info  [ModLoader] Loading mod: libfullbright.so
linker: mcpelauncher_linker_notifylldb /home/restanda/.local/share/mcpelauncher/mods/libfullbright.so 0x76501cec0000
14:20:55 Info  [ModLoader] Loaded 1 mods
14:20:55 Trace [Launcher] Loading Minecraft library
linker: mcpelauncher_linker_notifylldb /home/restanda/.local/share/mcpelauncher/versions/1.21.31.04/lib/x86_64/libc++_shared.so 0x76501cd00000
linker: mcpelauncher_linker_notifylldb /home/restanda/.local/share/mcpelauncher/versions/1.21.31.04/lib/x86_64/libfmod.so 0x76501c880000
linker: mcpelauncher_linker_notifylldb /home/restanda/.local/share/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so 0x764fe4600000
Found hook: _ZN11AppPlatform16showMousePointerEv @ 0xe4cc10
Found hook: _ZN11AppPlatform16hideMousePointerEv @ 0xe4cbe0
Found hook: _ZN11AppPlatform17setFullscreenModeE14FullscreenMode @ 0xe4cc30
Found hook: _ZN4FMOD6System4initEijPv @ 0xf9c9a0
Found hook: _ZN3rtc10getifaddrsEPP7ifaddrs @ 0x100ba50
Found hook: _ZN3rtc11freeifaddrsEP7ifaddrs @ 0x100bec0
14:20:59 Info  [Launcher] Loaded Minecraft library
14:20:59 Debug [Launcher] Minecraft is at offset 0x764FE4600000
14:20:59 Info  [ModLoader] Loading mods
14:20:59 Info  [ModLoader] Loading mod: libfullbright.so
14:21:02 Info  [ModLoader] Loaded 1 mods
14:21:02 Info  [Launcher] Game version: 0.0.0.0
14:21:02 Info  [Launcher] Applying patches
14:21:02 Debug [CorePatches] Failed to patch, vtable _ZTV21AppPlatform_android23 not found
14:21:02 Info  [Launcher] Initializing JNI
14:21:02 Error [JniSupport] Missing native symbol: Java_com_mojang_minecraftpe_MainActivity_nativeRegisterThis
14:21:02 Error [JniSupport] Missing native symbol: Java_com_mojang_minecraftpe_MainActivity_nativeInitializeWithApplicationContext
14:21:02 Error [JniSupport] Missing native symbol: Java_com_mojang_minecraftpe_MainActivity_nativeUnregisterThis
14:21:02 Error [JniSupport] Missing native symbol: Java_com_mojang_minecraftpe_MainActivity_nativeInitializeXboxLive
14:21:02 Error [JniSupport] Missing native symbol: Java_com_mojang_minecraftpe_MainActivity_nativeinitializeLibHttpClient
14:21:02 Error [JniSupport] Missing native symbol: Java_com_mojang_minecraftpe_MainActivity_nativeInitializeLibHttpClient
14:21:02 Error [JniSupport] Missing native symbol: Java_com_microsoft_xal_browser_WebView_urlOperationSucceeded
14:21:02 Error [JniSupport] Missing native symbol: Java_com_mojang_minecraftpe_PlayIntegrity_nativePlayIntegrityComplete
14:21:02 Info  [Launcher] Executing main thread
14:21:02 Trace [Minecraft] Entering JNI_OnLoad 0x765007e006c0
14:21:02 Trace [Minecraft] JNI_OnLoad completed
14:21:02 Trace [JniSupport] Invoking nativeRegisterThis
14:21:02 Trace [JniSupport] Invoking ANativeActivity_onCreate
14:21:02 Warn  [Main] Android stub called
14:21:02 Warn  [Main] Android stub called
14:21:02 Warn  [Main] Android stub called
14:21:02 Warn  [Main] Android stub called
14:21:02 Info  [Minecraft] android_main starting. internalDataPath is '/internal', externalDataPath is '/external'
14:21:02 Trace [JniSupport] Invoking start activity callbacks
14:21:02 Error [MCPE] *** setCachedDeviceId(16c93d55-a8e7-4cfa-8c6e-83ab557c550a)
14:21:02 Info  [Bedrock] configureBreakpad with directory: /crash, sessionid is: 9d839c93-d7e9-4d6c-afff-87ec7472250e
14:21:02 Info  [Bedrock] configureBreakpad called, directory is: /crash, sessionid is: 9d839c93-d7e9-4d6c-afff-87ec7472250e
14:21:02 Info  [Minecraft] NO LOG FILE! - AppPlatform_android::setStorageDirectory - using External dir (NEW) - CurrentFileStoragePath is now '/home/restanda/.local/share/mcpelauncher/'
14:21:02 Warn  [Minecraft] NO LOG FILE! - [Graphics] The graphics context was gained
14:21:02 Warn  [Minecraft] NO LOG FILE! - [Graphics] The graphics context was gained
14:21:02 Warn  [Minecraft] MinecraftGame::init && MinecraftGame::setSize!
14:21:02 Warn  [FakeEGL] eglQueryString 308d
14:21:02 Warn  [Main] Android stub called
14:21:02 Info  [GL] Vendor: Intel
14:21:02 Info  [GL] Renderer: Mesa Intel(R) UHD Graphics 610 (WHL GT1)
14:21:02 Info  [GL] Version: OpenGL ES 3.2 Mesa 24.0.9-0ubuntu0.2
14:21:02 Info  [GL] Vendor: Intel
14:21:02 Info  [GL] Renderer: Mesa Intel(R) UHD Graphics 610 (WHL GT1)
14:21:02 Info  [GL] Version: OpenGL ES 3.2 Mesa 24.0.9-0ubuntu0.2
14:21:02 Warn  [Main] Android stub called
linker: mcpelauncher_linker_notifylldb /home/restanda/.local/share/mcpelauncher/versions/1.21.31.04/lib/x86_64/libMediaDecoders_Android.so 0x764ff8600000
14:21:04 Info  [GL] Vendor: Intel
14:21:04 Info  [GL] Renderer: Mesa Intel(R) UHD Graphics 610 (WHL GT1)
14:21:04 Info  [GL] Version: OpenGL ES 3.2 Mesa 24.0.9-0ubuntu0.2
14:21:04 Warn  [Main] Android stub called
14:21:08 Debug [HttpCallStaticGlue] Successfully registerered HttpCall methods
14:21:08 Debug [XboxLiveAppConfig] Successfully registerered XboxLiveAppConfig methods
14:21:08 Debug [XSAPI.Android] Successfully registerered HttpCall tcuiMethods
14:21:09 Info  [Minecraft] NO LOG FILE! - AppPlatform_android::setStorageDirectory - using AppData dir - CurrentFileStoragePath is now '/home/restanda/.local/share/mcpelauncher/'
14:21:09 Info  [Minecraft] NO LOG FILE! - AppPlatform_android::setStorageDirectory - using External dir (NEW) - CurrentFileStoragePath is now '/home/restanda/.local/share/mcpelauncher/'
14:21:13 Info  [Minecraft] NO LOG FILE! - Time played notifier not required for 'en'
14:21:13 Info  [Minecraft] NO LOG FILE! - IPv4 not supported
14:21:13 Info  [Minecraft] NO LOG FILE! - IPv6 supported, port: 0
Signal 11 received
Backtrace elements: 3
# 0 /tmp/.mount_MinecrInKTEi/usr/bin/./mcpelauncher-client(_ZN12CrashHandler12handleSignalEiPv+0x156) [0xf97866]
# 1 /lib/x86_64-linux-gnu/libc.so.6(+0x45320) [0x76501ba45320]
# 2 LINKER (null)+0x764fee54694a in /home/restanda/.local/share/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0x0x9f4694a [0x0x764fee54694a]
Dumping stack...
# 18 LINKER (null)+0x764ff3e3cf98 in /home/restanda/.local/share/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0xf83cf98 [0x764ff3e3cf98]
# 25 LINKER (null)+0x764fee54694a in /home/restanda/.local/share/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0x9f4694a [0x764fee54694a]
# 33 LINKER std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >::append(char const*, unsigned long)+0x87 in /home/restanda/.local/share/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0xdaa39c7 [0x764ff20a39c7]
# 45 LINKER (null)+0x764fe6b61ee0 in /home/restanda/.local/share/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0x2561ee0 [0x764fe6b61ee0]
# 47 LINKER operator delete(void*)+0x22 in /home/restanda/.local/share/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0xeaa9ab2 [0x764ff30a9ab2]
# 49 LINKER (null)+0x764ff30fe1cb in /home/restanda/.local/share/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0xeafe1cb [0x764ff30fe1cb]
# 52 LINKER std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >::__grow_by(unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long)+0xa1 in /home/restanda/.local/share/mcpelauncher/versions/1.21.31.04/lib/x86_64/libc++_shared.so+0xd2881 [0x76501cdd2881]
# 113 LINKER vtable for std::__ndk1::basic_stringstream<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >+0x68 in /home/restanda/.local/share/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0xf0b1198 [0x764ff36b1198]
# 114 LINKER vtable for std::__ndk1::basic_stringbuf<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >+0x10 in /home/restanda/.local/share/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0xf0aab10 [0x764ff36aab10]
# 115 LINKER (null)+0x764fe6adccb4 in /home/restanda/.local/share/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0x24dccb4 [0x764fe6adccb4]
# 117 LINKER (null)+0x764ff357f40a in /home/restanda/.local/share/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0xef7f40a [0x764ff357f40a]
# 138 LINKER (null)+0x76501ce07730 in /home/restanda/.local/share/mcpelauncher/versions/1.21.31.04/lib/x86_64/libc++_shared.so+0x107730 [0x76501ce07730]
# 153 LINKER std::__ndk1::ios_base::~ios_base()+0x5f in /home/restanda/.local/share/mcpelauncher/versions/1.21.31.04/lib/x86_64/libc++_shared.so+0x8e48f [0x76501cd8e48f]
# 154 LINKER construction vtable for std::__ndk1::basic_ostream<char, std::__ndk1::char_traits<char> >-in-std::__ndk1::basic_ostringstream<char, std::__ndk1::char_traits<char>, cohtml::TempStdAllocator<char> >+0x10 in /home/restanda/.local/share/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0xf304900 [0x764ff3904900]
# 156 LINKER vtable for std::__ndk1::basic_stringbuf<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >+0x10 in /home/restanda/.local/share/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0xf0aab10 [0x764ff36aab10]
# 157 LINKER (null)+0x764fee4b486b in /home/restanda/.local/share/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0x9eb486b [0x764fee4b486b]
# 158 LINKER vtable for std::__ndk1::basic_stringstream<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >+0x18 in /home/restanda/.local/share/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0xf0b1148 [0x764ff36b1148]
# 159 LINKER vtable for std::__ndk1::basic_stringstream<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >+0x40 in /home/restanda/.local/share/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminec
aftpe.so+0xf0b1170 [0x764ff36b1170]
# 163 LINKER vtable for std::__ndk1::basic_stringstream<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >+0x18 in /home/restanda/.local/share/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0xf0b1148 [0x764ff36b1148]
# 165 LINKER vtable for std::__ndk1::basic_stringstream<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >+0x40 in /home/restanda/.local/share/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0xf0b1170 [0x764ff36b1170]
# 166 LINKER vtable for std::__ndk1::basic_streambuf<char, std::__ndk1::char_traits<char> >+0x10 in /home/restanda/.local/share/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0xf3049d0 [0x764ff39049d0]
# 167 LINKER (null)+0x76501ce07730 in /home/restanda/.local/share/mcpelauncher/versions/1.21.31.04/lib/x86_64/libc++_shared.so+0x107730 [0x76501ce07730]
# 179 LINKER vtable for std::__ndk1::ios_base+0x10 in /home/restanda/.local/share/mcpelauncher/versions/1.21.31.04/lib/x86_64/libc++_shared.so+0xf7ba8 [0x76501cdf7ba8]
# 201 LINKER (null)+0x764ff30b5612 in /home/restanda/.local/share/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0xeab5612 [0x764ff30b5612]
# 205 LINKER (null)+0x764ff3e3cf98 in /home/restanda/.local/share/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0xf83cf98 [0x764ff3e3cf98]
# 207 LINKER (null)+0x764fe9c47b58 in /home/restanda/.local/share/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0x5647b58 [0x764fe9c47b58]
# 219 LINKER (null)+0x764fee5468e7 in /home/restanda/.local/share/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0x9f468e7 [0x764fee5468e7]
# 245 LINKER std::__ndk1::recursive_mutex::unlock()+0x6 in /home/restanda/.local/share/mcpelauncher/versions/1.21.31.04/lib/x86_64/libc++_shared.so+0xcd146 [0x76501cdcd146]
# 247 LINKER (null)+0x764fee54303c in /home/restanda/.local/share/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0x9f4303c [0x764fee54303c]
# 255 LINKER (null)+0x764fee543fde in /home/restanda/.local/share/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0x9f43fde [0x764fee543fde]
# 269 LINKER (null)+0x764ff3e70cf0 in /home/restanda/.local/share/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0xf870cf0 [0x764ff3e70cf0]
# 273 LINKER (null)+0x764fee543c3d in /home/restanda/.local/share/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0x9f43c3d [0x764fee543c3d]
# 281 LINKER std::__ndk1::mutex::unlock()+0x6 in /home/restanda/.local/share/mcpelauncher/versions/1.21.31.04/lib/x86_64/libc++_shared.so+0xcd066 [0x76501cdcd066]
# 285 LINKER (null)+0x764fee4a1e28 in /home/restanda/.local/share/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0x9ea1e28 [0x764fee4a1e28]
# 287 LINKER (null)+0x764ff3e70cf0 in /home/restanda/.local/share/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0xf870cf0 [0x764ff3e70cf0]
# 295 LINKER (null)+0x764ff025fa15 in /home/restanda/.local/share/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0xbc5fa15 [0x764ff025fa15]
# 312 LINKER (null)+0x764ff3e70c00 in /home/restanda/.local/share/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0xf870c00 [0x764ff3e70c00]
# 325 LINKER (null)+0x764feb273b52 in /home/restanda/.local/share/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0x6c73b52 [0x764feb273b52]
# 327 LINKER (null)+0x764feb285699 in /home/restanda/.local/share/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0x6c85699 [0x764feb285699]
# 339 LINKER std::__ndk1::mutex::unlock()+0x6 in /home/restanda/.local/share/mcpelauncher/versions/1.21.31.04/lib/x86_64/libc++_shared.so+0xcd066 [0x76501cdcd066]
# 343 LINKER (null)+0x764feb749201 in /home/restanda/.local/share/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0x7149201 [0x764feb749201]
# 351 LINKER (null)+0x764feb285169 in /home/restanda/.local/share/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0x6c85169 [0x764feb285169]
# 365 LINKER std::__ndk1::chrono::steady_c
ock::now()+0x1f in /home/restanda/.local/share/mcpelauncher/versions/1.21.31.04/lib/x86_64/libc++_shared.so+0x7fc7f [0x76501cd7fc7f]
# 379 LINKER operator delete(void*)+0x22 in /home/restanda/.local/share/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0xeaa9ab2 [0x764ff30a9ab2]
# 381 LINKER (null)+0x764ff2fd6218 in /home/restanda/.local/share/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0xe9d6218 [0x764ff2fd6218]
# 389 LINKER (null)+0x20 in /home/restanda/.local/share/mcpelauncher/versions/1.21.31.04/lib/x86_64/libc++_shared.so+0xf43c0 [0x76501cdf43c0]
# 392 LINKER (null)+0x764ff3de11e8 in /home/restanda/.local/share/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0xf7e11e8 [0x764ff3de11e8]
# 395 LINKER (null)+0x764ff27a926b in /home/restanda/.local/share/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0xe1a926b [0x764ff27a926b]
# 447 LINKER (null)+0x764ff3e40900 in /home/restanda/.local/share/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0xf840900 [0x764ff3e40900]
# 449 LINKER (null)+0x764ff3e40b70 in /home/restanda/.local/share/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0xf840b70 [0x764ff3e40b70]
# 459 LINKER std::__ndk1::chrono::steady_clock::now()+0x1f in /home/restanda/.local/share/mcpelauncher/versions/1.21.31.04/lib/x86_64/libc++_shared.so+0x7fc7f [0x76501cd7fc7f]
# 463 LINKER (null)+0x764ff310ffd6 in /home/restanda/.local/share/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0xeb0ffd6 [0x764ff310ffd6]
# 464 LINKER (null)+0x764ff3e40b70 in /home/restanda/.local/share/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0xf840b70 [0x764ff3e40b70]
# 465 LINKER (null)+0x764feac5265b in /home/restanda/.local/share/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0x665265b [0x764feac5265b]
# 479 LINKER (null)+0x764feb23dd46 in /home/restanda/.local/share/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0x6c3dd46 [0x764feb23dd46]
# 480 LINKER (null)+0x764ff3dfabb8 in /home/restanda/.local/share/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0xf7fabb8 [0x764ff3dfabb8]
# 486 LINKER (null)+0x764ff39d4300 in /home/restanda/.local/share/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0xf3d4300 [0x764ff39d4300]
# 489 LINKER std::__ndk1::chrono::system_clock::now()+0x51 in /home/restanda/.local/share/mcpelauncher/versions/1.21.31.04/lib/x86_64/libc++_shared.so+0x7fc01 [0x76501cd7fc01]
# 495 LINKER (null)+0x764feb1fd62b in /home/restanda/.local/share/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0x6bfd62b [0x764feb1fd62b]
# 499 LINKER (null)+0x764feb1c9f35 in /home/restanda/.local/share/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0x6bc9f35 [0x764feb1c9f35]
# 508 LINKER (null)+0x764ff37af4f0 in /home/restanda/.local/share/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0xf1af4f0 [0x764ff37af4f0]
# 519 LINKER (null)+0x764feb1c7ab0 in /home/restanda/.local/share/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0x6bc7ab0 [0x764feb1c7ab0]
# 538 LINKER (null)+0x764ff3df8a90 in /home/restanda/.local/share/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0xf7f8a90 [0x764ff3df8a90]
# 554 LINKER (null)+0x764ff3de8b08 in /home/restanda/.local/share/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0xf7e8b08 [0x764ff3de8b08]
# 572 LINKER (null)+0x764ff37af918 in /home/restanda/.local/share/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0xf1af918 [0x764ff37af918]
# 584 LINKER (null)+0x764ff37af818 in /home/restanda/.local/share/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0xf1af818 [0x764ff37af818]
# 590 LINKER (null)+0x764ff37af798 in /home/restanda/.local/share/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0xf1af798 [0x764ff37af798]
# 596 LINKER (null)+0x764ff37af718 in /home/restanda/.local/share/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0xf1af718 [0x764ff37af718]
# 608 LINKER (null)+0x764ff37af618 in /home/restanda
.local/share/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0xf1af618 [0x764ff37af618]
# 611 LINKER (null)+0x764ff1ff1fa2 in /home/restanda/.local/share/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0xd9f1fa2 [0x764ff1ff1fa2]
# 621 LINKER (null)+0x764feb1c6dc9 in /home/restanda/.local/share/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0x6bc6dc9 [0x764feb1c6dc9]
# 623 LINKER (null)+0x764ff1ff3398 in /home/restanda/.local/share/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0xd9f3398 [0x764ff1ff3398]
# 641 LINKER (null)+0x764ff3de0878 in /home/restanda/.local/share/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0xf7e0878 [0x764ff3de0878]
# 662 LINKER (null)+0x764ff3c58bb8 in /home/restanda/.local/share/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0xf658bb8 [0x764ff3c58bb8]
# 668 LINKER (null)+0x764ff3c58b38 in /home/restanda/.local/share/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0xf658b38 [0x764ff3c58b38]
# 681 LINKER (null)+0x764fee7bcfcc in /home/restanda/.local/share/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0xa1bcfcc [0x764fee7bcfcc]
# 690 LINKER (null)+0x764fee7bced0 in /home/restanda/.local/share/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0xa1bced0 [0x764fee7bced0]
# 696 LINKER (null)+0x764fee7bced0 in /home/restanda/.local/share/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0xa1bced0 [0x764fee7bced0]
# 708 LINKER (null)+(nil) in /home/restanda/.local/share/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0xd9eed90 [0x764ff1feed90]
# 709 LINKER (null)+(nil) in /home/restanda/.local/share/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0xd9eedb0 [0x764ff1feedb0]
# 710 LINKER (null)+(nil) in /home/restanda/.local/share/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0xd9eedc0 [0x764ff1feedc0]
# 711 LINKER (null)+(nil) in /home/restanda/.local/share/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+0xd9eed60 [0x764ff1feed60]
# 724 LINKER (null)+0x764fe4600000 in /home/restanda/.local/share/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+(nil) [0x764fe4600000]
# 725 LINKER (null)+0x764fe4600000 in /home/restanda/.local/share/mcpelauncher/versions/1.21.31.04/lib/x86_64/libminecraftpe.so+(nil) [0x764fe4600000]
program failed with unix signal number: 11

Process exited with unexpected exit code: 11
`

**Comment by ChristopherHX** [comment]
Thanks for reporting this, should be fixed in next nightly.

You are not using a regular release, so nothing guards you from my checkins.

You can freely download older appimages from both nightly and release pages.

E.g. the nightly from last Sunday would be a downgrade target until CI builds again
