### ISSUE TITLE
request for Minecraft 1.21.51.01 support

### ISSUE THREAD

**Issue by BrianGLHF** [minecraft-linux/mcpelauncher-manifest#1073]
Minecraft 1.21.51.01 was released today as a hot fix. Kindly requesting support of this version. Thank you!

**Comment by ChristopherHX** [comment]
I'm confused 1.21.5**1**.**01** is in the database now, please verify and close this if it applies.

1.21.5**0**.**07** has been in the database before this issue.

**Comment by BrianGLHF** [comment]
sorry, this was a typo for 1.21.51.01 and was requested before it was added. will close. thank you
