### ISSUE TITLE
request for Minecraft 1.21.51.02 support

### ISSUE THREAD

**Issue by BrianGLHF** [minecraft-linux/mcpelauncher-manifest#1074]
Minecraft 1.21.51.**02** was released today as a hot fix. Kindly requesting support of this version. Thank you!

**Comment by ChristopherHX** [comment]
Done in [1.21.51.02](https://github.com/minecraft-linux/mcpelauncher-versiondb/commit/b972d2fb5b6fa3fa6ecca88ff752e347b21b07b2)

This happens earlier if you propose a change to the mentioned repo.

We have no Changelog of `1.21.51.02`, it's not clear for me what this even change

**Comment by BrianGLHF** [comment]
noted. thank you!
