### ISSUE TITLE
Touchpad not working when walking or sprinting

### ISSUE THREAD

**Issue by WahajGul** [minecraft-linux/mcpelauncher-manifest#1076]
When i walk or Sprint my laptop's touchpad doesn't work means I can't change direction and look anywhere using my touchpad but my trackball(other mouse that is usually in Thinkpads in the middle of keyboard) seems to work when I'm walking 

When I'm holding WSAD i cannot use my touchpad 

OS : Arch Linux Kernel 6.12
Laptop model : Dell latitude e6320 with 4GB RAM and Intel 3000 graphics 
Installed via flatpak: 1.1.2 version 
Qt (org.kde) = 5.15

**Comment by ChristopherHX** [comment]
Go into Settings (I only know that gnome settings contain this)

Somewhere is a Touchpad delay setting after keyboard press. Then disable this or set to 0s, years ago I have changed this for my DELL 9070 and never had this bad Touchpad feature again.

**Comment by WahajGul** [comment]
> Go into Settings (I only know that gnome settings contain this)
> 
> Somewhere is a Touchpad delay setting after keyboard press. Then disable this or set to 0s, years ago I have changed this for my DELL 9070 and never had this bad Touchpad feature again.

I'm using i3wm and my touchpad works fine everywhere but when I'm in Minecraft and walking or sprinting (or holding any button) i can't use my touchpad in the game

**Comment by ChristopherHX** [comment]
> touchpad works fine everywhere

For ego shooter like Minecraft and others as well?

What you describle is the default dell touchpad behavior on linux and windows.

When you type disable key presses of the touchpad.

This launcher just receives the input event as they are provided by linux.

**Comment by WahajGul** [comment]
I have never noticed. I don't play any games. And yes it is the definition behaviour i just checked by typing in the terminal and while typing i can't use my touchpad outside either. Is there a way to specifically disable this behaviour only for mcpe launcher 

Edit : i was not aware of the default behavior (touchpad being disabled when typing) and i stupidly opened this issue sorry for the inconvenience I'm going to disable this default behavior when playing the game as a temporary solution or a script to toggle this behaviour so i can enable and disable it when I'm playing the game
