### ISSUE TITLE
Created A Script Which Auto-Packages MCPELauncher into a APT Repo

### ISSUE THREAD

**Issue by TheBrokenRail** [minecraft-linux/mcpelauncher-manifest#11]
### Script

https://github.com/TheBrokenRail/mcpelauncher-apt

### How to Use

```bash
# Add Repo
sudo dpkg --add-architecture i386
wget -O - https://thebrokenrail.github.io/mcpelauncher-apt/conf/key | sudo apt-key add -
sudo add-apt-repository 'deb https://thebrokenrail.github.io/mcpelauncher-apt/ bionic main'
sudo apt update

# Install
sudo apt install sudo apt install msa-daemon msa-ui-qt mcpelauncher-client mcpelauncher-ui-qt mcpelauncher-ui-qt-icon mcpelauncher-linux-bin

# Install Server
sudo apt install mcpelauncher-server
```
### Info

This has only been tested on Ubuntu 18.04.

**Comment by Mhowser** [comment]
shouldn't this be a pull request?

**Comment by Mhowser** [comment]
when i tried to add your repo, it says the architecture 'i386' is not supported.

In repo/conf/distributions, the arch is set to amd64.

so which one is it for?? @TheBrokenRail ?

**Comment by TheBrokenRail** [comment]
i386 (32 bit) is not supported
amd64 (64 bit) is supported

**Comment by Mhowser** [comment]
can you edit the commands accordingly to prevent future confusion please?

**Comment by TheBrokenRail** [comment]
Where is the confusion?

**Comment by Mhowser** [comment]
The confusion is caused by the first of the commands you provide, by adding
the architecture 'i386'. Shouldn't it be amd64 instead?

On Nov 5, 2018 6:47 PM, "TheBrokenRail" <notifications@github.com> wrote:

Where is the confusion?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/minecraft-linux/mcpelauncher-manifest/issues/11#issuecomment-436112895>,
or mute the thread

**Comment by TheBrokenRail** [comment]
This is because the packages while they are amd64 require i386 dependencies.

**Comment by Mhowser** [comment]
I tried to add the repo to my 64bit machine and i still get "i386 is not supported"

**Comment by TheBrokenRail** [comment]
MCPELauncher is not distributed in 32bit but requires 32bit dependencies.

**Comment by Mhowser** [comment]
I still cannot get this to work, can you join the discord server so we can discuss this in greater detail?

**Comment by TheBrokenRail** [comment]
Is this an error with the ```dpkg``` command or addin the rpo + apt update? Post a log of the commands.

**Comment by MCMrARM** [comment]
Replaced by my own repository.
