### ISSUE TITLE
Won't start on Pop! OS 19.04

### ISSUE THREAD

**Issue by SupDroidStudio** [minecraft-linux/mcpelauncher-manifest#111]
Before you say "Pop! OS is not supported", it is. Pop! OS is basically just Ubuntu 19.04 but more lightweight and aesthetically pleasing.

Upon attempting to launch Minecraft from the Linux Launcher, it says the following:
![Screenshot from 2019-07-02 18-29-01](https://user-images.githubusercontent.com/51241115/60533347-4f221680-9cf7-11e9-9819-49140d32bcdc.png)

Any help would be greatly appreciated!

**Comment by TrackRunny** [comment]
Try these two commands!
`sudo apt install libegl1-mesa:i386 libegl1-mesa-dev:i386`
`sudo apt install libegl1-mesa:i386`
Let me know if those work!

**Comment by SupDroidStudio** [comment]
It says they are already installed...

**Comment by SupDroidStudio** [comment]
It turns out the issue was fixable by simply building from source instead of installing directly.
