### ISSUE TITLE
Can't move player with wasd and player spins in circles

### ISSUE THREAD

**Issue by Skeletron331** [minecraft-linux/mcpelauncher-manifest#112]
It looks like the game keeps on mapping my keyboard to a game controller maybe it causes the problem?

**Comment by MCMrARM** [comment]
Never heard of this sort of issues, are you by any chance using a VM?

**Comment by Skeletron331** [comment]
Sorry it was a problem at my side. I did not know that my controller was
connected and it had a little bit of drift. Turns out it actually works
great. Thank you for this amazing app. Keep up the great work.
