### ISSUE TITLE
Mcpe 1.13.0.1

### ISSUE THREAD

**Issue by coolkidsrule101** [minecraft-linux/mcpelauncher-manifest#116]
06:32:09 Info  [Launcher] Version: client 9d41f29 / manifest 88ad96a
06:32:09 Info  [Launcher] CPU: AuthenticAMD AMD Ryzen 3 2200U with Radeon Vega Mobile Gfx  
06:32:09 Info  [Launcher] CPU supports SSSE3: YES
06:32:09 Trace [Launcher] Loading hybris libraries
06:32:09 Trace [HybrisUtils] Loaded OS library /usr/share/mcpelauncher/libs/native/libfmod.so.9.16
06:32:09 Trace [HybrisUtils] Loaded OS library libm.so.6
06:32:09 Trace [HybrisUtils] Loaded OS library libz.so.1
06:32:09 Trace [Launcher] Loading Minecraft library
06:32:12 Info  [Launcher] Loaded Minecraft library
06:32:12 Debug [Launcher] Minecraft is at offset 0xe5a1f000
06:32:12 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance16initializeServerER13IMinecraftAppR9WhitelistP15PermissionsFileP15FilePathManagerNSt6chrono8durationIxSt5ratioILx1ELx1EEEESsSsSs13LevelSettingsib20ConnectionDefinitionbRKSt6vectorISsSaISsEESsRKN3mce4UUIDER18IMinecraftEventingR22ResourcePackRepositoryRK18ContentTierManagerR19ResourcePackManagerSt8functionIFSt10unique_ptrI12LevelStorageSt14default_deleteISZ_EER9SchedulerEERKSsP9LevelDataSsSsSY_I16EducationOptionsS10_IS1B_EEPSV_SX_IFvS18_EES1G_P13ServerMetricsP13DebugEndPoint
06:32:12 Error [MinecraftSymbols] Unresolved symbol: _ZN2v82V810InitializeEv
06:32:12 Error [MinecraftSymbols] Unresolved symbol: _ZN2v82V818InitializePlatformEPNS_8PlatformE
06:32:12 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftEventingC2ERKSs
06:32:12 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance16_syncDestroyGameEv
06:32:12 Error [MinecraftSymbols] Unresolved symbol: _ZN9Scheduler17processCoroutinesENSt6chrono8durationIxSt5ratioILx1ELx1000000000EEEE
06:32:12 Error [MinecraftSymbols] Unresolved symbol: _ZN15FilePathManagerC2ESsb
06:32:12 Error [MinecraftSymbols] Unresolved symbol: _ZNK15FilePathManager11getRootPathEv
06:32:12 Error [MinecraftSymbols] Unresolved symbol: _ZNK15FilePathManager15getUserDataPathEv
06:32:12 Error [MinecraftSymbols] Unresolved symbol: _ZNK15FilePathManager13getWorldsPathEv
06:32:12 Error [MinecraftSymbols] Unresolved symbol: _ZN15FilePathManager14setPackagePathESs
06:32:12 Error [MinecraftSymbols] Unresolved symbol: _ZNK15FilePathManager14getPackagePathEv
06:32:12 Error [MinecraftSymbols] Unresolved symbol: _ZN15FilePathManager15setSettingsPathESs
06:32:12 Error [MinecraftSymbols] Unresolved symbol: _ZNK15FilePathManager15getSettingsPathEv
06:32:12 Error [MinecraftSymbols] Unresolved symbol: _ZN15PermissionsFileC2ERKSs
06:32:12 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServiceLocatorI11AppPlatformE15mDefaultServiceE
06:32:12 Error [MinecraftSymbols] Unresolved symbol: _ZN11AppPlatform12showKeyboardERKSsibbbiRK4Vec2
06:32:12 Error [MinecraftSymbols] Unresolved symbol: _ZNK11AppPlatform22getHardwareInformationEv
06:32:12 Error [MinecraftSymbols] Unresolved symbol: _ZN17AppResourceLoaderC2ESt8functionIFSsvEE
06:32:12 Error [MinecraftSymbols] Unresolved symbol: _ZN19ServerCommandOriginC2ERKSsR11ServerLevel
06:32:12 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social12XboxLiveUser22_handleUISignInNoErrorERN4xbox8services6system14sign_in_resultESt8functionIFvNS_12SignInResultEbEE
06:32:12 Error [MinecraftSymbols] Unresolved symbol: _ZN17PackSourceFactoryC2EP7Options
06:32:12 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepositoryC2ER18IMinecraftEventingR19PackManifestFactoryR29IContentAccessibilityProviderP15FilePathManagerR17PackSourceFactoryb
06:32:12 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepository21addWorldResourcePacksERKSs
06:32:12 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManagerC2ESt8functionIFSsvEERK18ContentTierManagerb
06:32:12 Error [MinecraftSymbols] Unresolved symbol: _ZN30ExternalFileLevelStorageSourceC2EP15FilePathManagerSt10shared_ptrI22SaveTransactionManagerE
06:32:12 Info  [Launcher] Game version: 1.13.0.1
06:32:12 Info  [Launcher] Applying patches
06:32:12 Trace [Store] Vtable size = 37
06:32:12 Trace [Patch] Patching - original: 85 83 87 86 131
06:32:12 Trace [Patch] Patching - result: 233 51 203 80 111
06:32:12 Trace [Patch] Patching - original: 83 87 86 131 236
06:32:12 Trace [Patch] Patching - result: 233 165 104 143 110
06:32:12 Trace [Patch] Patching - original: 85 83 87 86 129
06:32:12 Trace [Patch] Patching - result: 233 139 31 22 108
06:32:12 Trace [Patch] Patching - original: 85 83 87 86 129
06:32:12 Trace [Patch] Patching - result: 233 75 79 84 108
06:32:12 Trace [Patch] Patching - original: 85 83 87 86 129
06:32:12 Trace [Patch] Patching - result: 233 161 95 84 108
06:32:12 Trace [Patch] Patching - original: 85 83 87 86 129
06:32:12 Trace [Patch] Patching - result: 233 21 76 84 108
06:32:12 Trace [Patch] Patching - original: 85 83 87 86 129
06:32:12 Trace [Patch] Patching - result: 233 93 179 83 108
06:32:12 Trace [Patch] Patching - original: 85 83 87 86 129
06:32:12 Trace [Patch] Patching - result: 233 105 167 83 108
06:32:12 Trace [Patch] Patching - original: 85 83 87 86 129
06:32:12 Trace [Patch] Patching - result: 233 63 219 85 108
06:32:12 Trace [Patch] Patching - original: 83 87 86 131 236
06:32:12 Trace [Patch] Patching - result: 233 157 70 84 108
06:32:12 Trace [Patch] Patching - original: 85 83 87 86 129
06:32:12 Trace [Patch] Patching - result: 233 89 113 84 108
06:32:12 Trace [Patch] Patching - original: 49 192 195 141 182
06:32:12 Trace [Patch] Patching - result: 233 197 126 66 111
06:32:12 Trace [Patch] Patching - original: 83 131 236 8 232
06:32:12 Trace [Patch] Patching - result: 233 159 65 114 108
06:32:12 Trace [Patch] Patching - original: 137 76 36 4 137
06:32:12 Trace [Patch] Patching - result: 232 98 108 39 108
06:32:12 Trace [Patch] Patching - original: 36 88 139 65 12
06:32:12 Trace [Patch] Patching - result: 232 109 108 39 108
06:32:12 Trace [TexelAAPatch] Found patch at @2d67
06:32:12 Trace [TexelAAPatch] LDR instruction invalid; patch incompatible
06:32:12 Trace [Patch] Patching - original: 85 83 87 86 131
06:32:12 Trace [Patch] Patching - result: 233 56 217 83 111
06:32:12 Trace [Patch] Patching - original: 85 83 87 86 129
06:32:12 Trace [Patch] Patching - result: 233 5 216 83 111
06:32:12 Trace [Patch] Patching - original: 83 87 86 131 236
06:32:12 Trace [Patch] Patching - result: 233 209 216 83 111
06:32:12 Trace [Patch] Patching - original: 85 83 87 86 131
06:32:12 Trace [Patch] Patching - result: 233 38 230 13 108
06:32:12 Trace [Patch] Patching - original: 85 83 87 86 131
06:32:12 Trace [Patch] Patching - result: 233 113 104 128 110
06:32:12 Trace [Patch] Patching - original: 232 141 59 40 253
06:32:12 Trace [Patch] Patching - result: 232 141 49 161 108
06:32:12 Info  [Launcher] Creating window
06:32:12 Trace [Launcher] Loading gamepad mappings: /usr/share/mcpelauncher/gamecontrollerdb.txt
06:32:12 Trace [Launcher] Loading gamepad mappings: /usr/share/mcpelauncher/gamecontrollerdb.txt
06:32:13 Trace [Launcher] Initializing AppPlatform (vtable)
06:32:13 Trace [AppPlatform] Vtable size = 268
06:32:13 Trace [Launcher] Initializing AppPlatform (create instance)
Signal 11 received
Backtrace elements: 2
#0 /usr/bin/mcpelauncher-client(_ZN12CrashHandler12handleSignalEiPv+0xc5) [0x567773e9]
#1 linux-gate.so.1(__kernel_sigreturn+0) [0xf7f3c950]
Dumping stack...
#249 HYBRIS (null)+-436667875 in libminecraftpe.so+0x570a1d [0xe5f8fa1d]
#254 HYBRIS (null)+-442371820 in libminecraftpe.so+0x0114 [0xe5a1f114]
Process exited with unexpected exit code: 6

**Comment by Mhowser** [comment]
Mrarm is working on 1.13 support.

**Comment by MCMrARM** [comment]
Supported now

**Comment by FoxyelperroDJ** [comment]
(/ ˘ ³˘)/
