### ISSUE TITLE
Slowly looking down when xbox controller connected

### ISSUE THREAD

**Issue by jj11hh** [minecraft-linux/mcpelauncher-manifest#125]
After I attached my xbox 360 controller, the camera is very slowly looking down although I haven't touch the thumbstick. When I push the thumbstick up slightly, the move of the camera stops, and I can control it normally.
This controller works fine when I play the Windows 10 edition, my OS is Arch Linux, using the AppImage version.

**Comment by Mhowser** [comment]
You need to manually set the deadzones for the controller, see https://wiki.archlinux.org/index.php/Gamepad#evdev_API_deadzones

**Comment by jj11hh** [comment]
> You need to manually set the deadzones for the controller, see https://wiki.archlinux.org/index.php/Gamepad#evdev_API_deadzones

it works, thanks!
