### ISSUE TITLE
Minecraft 1.12.0 Crash on Launch

### ISSUE THREAD

**Issue by haveyouwantto** [minecraft-linux/mcpelauncher-manifest#127]
Crash log:
https://paste.ubuntu.com/p/r6trY7KSvV/

**Comment by nfugal** [comment]
Mine is crashing too:
https://pastebin.com/HZ3EEKRg

Running on Arch. What other info is helpful in chasing this down?

**Comment by charveey** [comment]
Same for me

**Comment by MCMrARM** [comment]
Dup of https://github.com/minecraft-linux/mcpelauncher-manifest/issues/104
