### ISSUE TITLE
1.12 could not launch

### ISSUE THREAD

**Issue by michaeldai7** [minecraft-linux/mcpelauncher-manifest#135]
> 16:47:01 Info  [Launcher] Version: client b63fb08 / manifest 769df90
16:47:01 Info  [Launcher] CPU: GenuineIntel Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
16:47:01 Info  [Launcher] CPU supports SSSE3: YES
16:47:01 Trace [Launcher] Loading hybris libraries
16:47:01 Trace [HybrisUtils] Loaded OS library /usr/share//mcpelauncher/libs/native/libfmod.so.9.16
16:47:01 Trace [HybrisUtils] Loaded OS library libm.so.6
16:47:01 Trace [Launcher] Loading Minecraft library
16:47:02 Info  [Launcher] Loaded Minecraft library
16:47:02 Debug [Launcher] Minecraft is at offset 0xed82d000
16:47:02 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance16initializeServerER13IMinecraftAppR9WhitelistP15PermissionsFileP15FilePathManagerNSt6chrono8durationIxSt5ratioILx1ELx1EEEESsSsSs13LevelSettingsibiiibRKSt6vectorISsSaISsEESsRKN3mce4UUIDER18IMinecraftEventingR22ResourcePackRepositoryRK18ContentTierManagerR19ResourcePackManagerSt8functionIFSt10unique_ptrI12LevelStorageSt14default_deleteISY_EER9SchedulerEERKSsP9LevelDataSsSsSX_I16EducationOptionsSZ_IS1A_EEPSU_SW_IFvS17_EES1F_P28ServerCommunicationInterface
16:47:02 Error [MinecraftSymbols] Unresolved symbol: _ZN2v82V810InitializeEv
16:47:02 Error [MinecraftSymbols] Unresolved symbol: _ZN2v82V818InitializePlatformEPNS_8PlatformE
16:47:02 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance16_syncDestroyGameEv
16:47:02 Error [MinecraftSymbols] Unresolved symbol: _ZN8Keyboard4feedEhi
16:47:02 Error [MinecraftSymbols] Unresolved symbol: _ZN9Scheduler17processCoroutinesENSt6chrono8durationIxSt5ratioILx1ELx1000000000EEEE
16:47:02 Error [MinecraftSymbols] Unresolved symbol: _ZN15FilePathManagerC2ESsb
16:47:02 Error [MinecraftSymbols] Unresolved symbol: _ZNK15FilePathManager11getRootPathEv
16:47:02 Error [MinecraftSymbols] Unresolved symbol: _ZNK15FilePathManager15getUserDataPathEv
16:47:02 Error [MinecraftSymbols] Unresolved symbol: _ZNK15FilePathManager13getWorldsPathEv
16:47:02 Error [MinecraftSymbols] Unresolved symbol: _ZN15FilePathManager14setPackagePathESs
16:47:02 Error [MinecraftSymbols] Unresolved symbol: _ZNK15FilePathManager14getPackagePathEv
16:47:02 Error [MinecraftSymbols] Unresolved symbol: _ZN15FilePathManager15setSettingsPathESs
16:47:02 Error [MinecraftSymbols] Unresolved symbol: _ZNK15FilePathManager15getSettingsPathEv
16:47:02 Error [MinecraftSymbols] Unresolved symbol: _ZN17AppResourceLoaderC2ESt8functionIFSsvEE
16:47:02 Error [MinecraftSymbols] Unresolved symbol: _ZN19ServerCommandOriginC2ERKSsR11ServerLevel
16:47:02 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social12XboxLiveUser22_handleUISignInNoErrorERN4xbox8services6system14sign_in_resultESt8functionIFvNS_12SignInResultEbEE
16:47:02 Error [MinecraftSymbols] Unresolved symbol: _ZN17PackSourceFactoryC2EP7Options
16:47:02 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepositoryC2ER18IMinecraftEventingR19PackManifestFactoryR29IContentAccessibilityProviderP15FilePathManagerR17PackSourceFactoryb
16:47:02 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepository21addWorldResourcePacksERKSs
16:47:02 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManagerC2ESt8functionIFSsvEERK18ContentTierManager
16:47:02 Error [MinecraftSymbols] Unresolved symbol: _ZN30ExternalFileLevelStorageSourceC2EP15FilePathManagerSt10shared_ptrI22SaveTransactionManagerE
16:47:02 Info  [Launcher] Game version: 1.12.0
16:47:02 Info  [Launcher] Applying patches
16:47:02 Trace [Store] Vtable size = 34
16:47:02 Trace [Patch] Patching - original: 85 83 87 86 131
16:47:02 Trace [Patch] Patching - result: 233 163 49 147 103
16:47:02 Trace [Patch] Patching - original: 83 87 86 131 236
16:47:02 Trace [Patch] Patching - result: 233 41 101 239 102
16:47:02 Trace [Patch] Patching - original: 85 83 87 86 129
16:47:02 Trace [Patch] Patching - result: 233 65 48 175 100
16:47:02 Trace [Patch] Patching - original: 85 83 87 86 129
16:47:02 Trace [Patch] Patching - result: 233 1 100 237 100
16:47:02 Trace [Patch] Patching - original: 85 83 87 86 129
16:47:02 Trace [Patch] Patching - result: 233 87 116 237 100
16:47:02 Trace [Patch] Patching - original: 85 83 87 86 129
16:47:02 Trace [Patch] Patching - result: 233 203 96 237 100
16:47:02 Trace [Patch] Patching - original: 85 83 87 86 129
16:47:02 Trace [Patch] Patching - result: 233 231 203 236 100
16:47:02 Trace [Patch] Patching - original: 85 83 87 86 129
16:47:02 Trace [Patch] Patching - result: 233 109 201 236 100
16:47:02 Trace [Patch] Patching - original: 85 83 87 86 129
16:47:02 Trace [Patch] Patching - result: 233 231 253 238 100
16:47:02 Trace [Patch] Patching - original: 83 87 86 131 236
16:47:02 Trace [Patch] Patching - result: 233 69 105 237 100
16:47:02 Trace [Patch] Patching - original: 85 83 87 86 129
16:47:02 Trace [Patch] Patching - result: 233 1 148 237 100
16:47:02 Trace [Patch] Patching - original: 49 192 195 141 182
16:47:02 Trace [Patch] Patching - result: 233 109 211 140 103
16:47:02 Trace [Patch] Patching - original: 83 131 236 8 232
16:47:02 Trace [Patch] Patching - result: 233 113 232 10 101
16:47:02 Trace [Patch] Patching - original: 137 76 36 4 137
16:47:02 Trace [Patch] Patching - result: 232 76 18 192 100
16:47:02 Trace [Patch] Patching - original: 36 88 139 65 12
16:47:02 Trace [Patch] Patching - result: 232 87 18 192 100
16:47:02 Trace [Patch] Patching - original: 85 83 87 86 131
16:47:02 Trace [Patch] Patching - result: 233 130 40 150 103
16:47:02 Trace [Patch] Patching - original: 85 83 87 86 129
16:47:02 Trace [Patch] Patching - result: 233 79 39 150 103
16:47:02 Trace [Patch] Patching - original: 83 87 86 131 236
16:47:02 Trace [Patch] Patching - result: 233 27 40 150 103
16:47:02 Trace [Patch] Patching - original: 85 137 229 83 87
16:47:02 Trace [Patch] Patching - result: 233 52 54 167 100
16:47:02 Trace [Patch] Patching - original: 85 83 87 86 131
16:47:02 Trace [Patch] Patching - result: 233 175 164 224 102
16:47:02 Trace [Patch] Patching - original: 232 173 62 122 253
16:47:02 Trace [Patch] Patching - result: 232 179 116 49 101
16:47:02 Info  [Launcher] Creating window
16:47:02 Trace [Launcher] Loading gamepad mappings: /usr/share//mcpelauncher/gamecontrollerdb.txt
16:47:02 Trace [Launcher] Loading gamepad mappings: /usr/share/mcpelauncher/gamecontrollerdb.txt
16:47:02 Trace [Launcher] Initializing AppPlatform (vtable)
16:47:02 Trace [AppPlatform] Vtable size = 265
16:47:02 Trace [Launcher] Initializing AppPlatform (create instance)
16:47:02 Trace [Launcher] Initializing AppPlatform (initialize call)
pure virtual method called
terminate called without an active exception
Signal 6 received
Backtrace elements: 11
#0 /usr/bin/mcpelauncher-client(_ZN12CrashHandler12handleSignalEiPv+0xc5) [0x56760f83]
#1 linux-gate.so.1(__kernel_sigreturn+0) [0xf7f29950]
#2 linux-gate.so.1(__kernel_vsyscall+0x9) [0xf7f29939]
#3 /lib/i386-linux-gnu/libc.so.6(gsignal+0xc2) [0xf7778182]
#4 /lib/i386-linux-gnu/libc.so.6(abort+0xf0) [0xf77622b6]
#5 HYBRIS __gnu_cxx::__verbose_terminate_handler()+469 in libminecraftpe.so+0x5488bd5 [0xf2cb5bd5]
#6 HYBRIS __cxxabiv1::__terminate(void (*)())+25 in libminecraftpe.so+0x542a589 [0xf2c57589]
#7 HYBRIS __cxxabiv1::__unexpected(void (*)())+0 in libminecraftpe.so+0x542a620 [0xf2c57620]
#8 HYBRIS (null)+-221937837 in libminecraftpe.so+0x542af53 [0xf2c57f53]
#9 /usr/bin/mcpelauncher-client(main+0x14ac) [0x56715568]
#10 /lib/i386-linux-gnu/libc.so.6(__libc_start_main+0xf1) [0xf7763751]
Dumping stack...
#13 HYBRIS (null)+-310194176 in libminecraftpe.so+0x0000 [0xed82d000]
#21 HYBRIS __gnu_cxx::__verbose_terminate_handler()+469 in libminecraftpe.so+0x5488bd5 [0xf2cb5bd5]
#22 HYBRIS __cxxabiv1::__terminate(void (*)())+25 in libminecraftpe.so+0x542a589 [0xf2c57589]
#23 HYBRIS __cxxabiv1::__unexpected(void (*)())+0 in libminecraftpe.so+0x542a620 [0xf2c57620]
#24 HYBRIS (null)+-221937837 in libminecraftpe.so+0x542af53 [0xf2c57f53]
#272 HYBRIS (null)+-221607767 in libminecraftpe.so+0x547b8a9 [0xf2ca88a9]
#284 HYBRIS PlayFab::ClientModels::UserTitleInfo::ToJson() const+1152 in libminecraftpe.so+0x27d3000 [0xf0000000]
#299 HYBRIS (null)+-221607767 in libminecraftpe.so+0x547b8a9 [0xf2ca88a9]
#318 HYBRIS PlayFab::ClientModels::ToJsonEnum(PlayFab::ClientModels::Currency, Json::Value&)+4992 in libminecraftpe.so+0x27d2000 [0xeffff000]
#565 HYBRIS (null)+-307990317 in libminecraftpe.so+0x21a0d3 [0xeda470d3]
#578 HYBRIS (null)+-310193900 in libminecraftpe.so+0x0114 [0xed82d114]
#579 HYBRIS (null)+-308023596 in libminecraftpe.so+0x211ed4 [0xeda3eed4]
#706 HYBRIS (null)+-220183576 in libminecraftpe.so+0x55d73e8 [0xf2e043e8]
#721 HYBRIS (null)+-220183576 in libminecraftpe.so+0x55d73e8 [0xf2e043e8]
#726 HYBRIS (null)+-195316664 in libminecraftpe.so+0x6d8e448 [0xf45bb448]
#728 HYBRIS __gnu_cxx::__verbose_terminate_handler()+469 in libminecraftpe.so+0x5488bd5 [0xf2cb5bd5]
#729 HYBRIS (null)+-220183576 in libminecraftpe.so+0x55d73e8 [0xf2e043e8]
#743 HYBRIS __gnu_cxx::__verbose_terminate_handler()+11 in libminecraftpe.so+0x5488a0b [0xf2cb5a0b]
#744 HYBRIS (null)+-195316664 in libminecraftpe.so+0x6d8e448 [0xf45bb448]
#748 HYBRIS __cxxabiv1::__terminate(void (*)())+25 in libminecraftpe.so+0x542a589 [0xf2c57589]
#749 HYBRIS std::unique_ptr<Core::DiskAccessTracker, std::default_delete<Core::DiskAccessTracker> >::~unique_ptr()+0 in libminecraftpe.so+0x3c921f0 [0xf14bf1f0]
#751 HYBRIS (null)+-193022544 in libminecraftpe.so+0x6fbe5b0 [0xf47eb5b0]
#755 HYBRIS __cxxabiv1::__terminate(void (*)())+11 in libminecraftpe.so+0x542a57b [0xf2c5757b]
#756 HYBRIS (null)+-195316664 in libminecraftpe.so+0x6d8e448 [0xf45bb448]
#760 HYBRIS __cxxabiv1::__unexpected(void (*)())+0 in libminecraftpe.so+0x542a620 [0xf2c57620]
#761 HYBRIS __gnu_cxx::__verbose_terminate_handler()+0 in libminecraftpe.so+0x5488a00 [0xf2cb5a00]
#762 HYBRIS (null)+-193022548 in libminecraftpe.so+0x6fbe5ac [0xf47eb5ac]
#763 HYBRIS (null)+-194920448 in libminecraftpe.so+0x6def000 [0xf461c000]
#765 HYBRIS std::terminate()+9 in libminecraftpe.so+0x542a609 [0xf2c57609]
#766 HYBRIS (null)+-195316664 in libminecraftpe.so+0x6d8e448 [0xf45bb448]
#768 HYBRIS (null)+-221937837 in libminecraftpe.so+0x542af53 [0xf2c57f53]
#770 HYBRIS (null)+-220235926 in libminecraftpe.so+0x55ca76a [0xf2df776a]
#774 HYBRIS (null)+6 in libminecraftpe.so+0x542af26 [0xf2c57f26]
#775 HYBRIS (null)+-195316664 in libminecraftpe.so+0x6d8e448 [0xf45bb448]
#776 HYBRIS AppPlatform::getLoggingPath() const+31 in libminecraftpe.so+0x2acfecf [0xf02fcecf]
#778 HYBRIS (null)+-195316664 in libminecraftpe.so+0x6d8e448 [0xf45bb448]
#779 HYBRIS (null)+-195316664 in libminecraftpe.so+0x6d8e448 [0xf45bb448]
#780 HYBRIS AppPlatform::initialize()+47 in libminecraftpe.so+0x2acceff [0xf02f9eff]
#942 HYBRIS cohtml::css::AnimationController::TickSelectedAnimations(cohtml::dom::Element const* const*, unsigned int)+822 in libminecraftpe.so+0x47d1356 [0xf1ffe356]
Process exited with unexpected exit code: 6

**Comment by MCMrARM** [comment]
You're using an outdated version of the launcher, please update.
