### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by screenslaver5963** [minecraft-linux/mcpelauncher-manifest#137]
/usr/bin/mcpelauncher-client: error while loading shared libraries: libEGL.so.1: cannot open shared object file: No such file or directory
Process exited with unexpected exit code: 127

**Comment by MCMrARM** [comment]
https://mcpelauncher.readthedocs.io/en/latest/troubleshooting.html#graphics-performance-issues-software-rendering-eglut-failed-to-initialize-egl-display
