### ISSUE TITLE
Hi res resource packs crash game

### ISSUE THREAD

**Issue by cncz42** [minecraft-linux/mcpelauncher-manifest#139]
It appears that when I load a resource pack that isn't standard (like the classic textures) it crashes the game, for example purebdcraft crashes when it is applied. I am running the appimage version on manjaro linux.
Here is the crash log: https://pastebin.com/biyk6fPX

**Comment by ChristopherHX** [comment]
```
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
```
Out of Memory?
The old launcher was 32bit only, now there is a experimental 64bit one which can utilize far more than 4GiB of your RAM (if you have enough)

duplicate of #121
