### ISSUE TITLE
Can't log to microsoft account

### ISSUE THREAD

**Issue by vinesnts** [minecraft-linux/mcpelauncher-manifest#146]
I click Sign In, then I pick my Microsoft Account, the msa-qt-ui closes and the game shows a box "Connecting" for some seconds then closes.
Check out the log message:
02:46:36 Info  [Launcher] Version: client a48cb4c / manifest d9cc8d9
02:46:36 Info  [Launcher] CPU: GenuineIntel Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz
02:46:36 Info  [Launcher] CPU supports SSSE3: YES
02:46:36 Trace [Launcher] Loading hybris libraries
02:46:36 Trace [HybrisUtils] Loaded OS library /usr/share//mcpelauncher/libs/native/libfmod.so.9.16
02:46:36 Trace [HybrisUtils] Loaded OS library libm.so.6
02:46:36 Trace [HybrisUtils] Loaded OS library libz.so.1
02:46:36 Trace [Launcher] Loading Minecraft library
02:46:38 Info  [Launcher] Loaded Minecraft library
02:46:38 Debug [Launcher] Minecraft is at offset 0xedb1c000
02:46:38 Error [MinecraftSymbols] Unresolved symbol: _ZN11AppPlatform12showKeyboardERKSsibbbiRKN3glm5tvec2IfLNS2_9precisionE0EEE
02:46:38 Error [MinecraftSymbols] Unresolved symbol: _ZN17AppResourceLoaderC2ESt8functionIFSsvEE
02:46:38 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance16_syncDestroyGameEv
02:46:38 Error [MinecraftSymbols] Unresolved symbol: _ZN30ExternalFileLevelStorageSourceC2EP15FilePathManagerSt10shared_ptrI22SaveTransactionManagerE
02:46:38 Error [MinecraftSymbols] Unresolved symbol: _ZN15FilePathManagerC2ESsb
02:46:38 Error [MinecraftSymbols] Unresolved symbol: _ZNK15FilePathManager11getRootPathEv
02:46:38 Error [MinecraftSymbols] Unresolved symbol: _ZNK15FilePathManager15getUserDataPathEv
02:46:38 Error [MinecraftSymbols] Unresolved symbol: _ZNK15FilePathManager13getWorldsPathEv
02:46:38 Error [MinecraftSymbols] Unresolved symbol: _ZN15FilePathManager14setPackagePathESs
02:46:38 Error [MinecraftSymbols] Unresolved symbol: _ZNK15FilePathManager14getPackagePathEv
02:46:38 Error [MinecraftSymbols] Unresolved symbol: _ZN15FilePathManager15setSettingsPathESs
02:46:38 Error [MinecraftSymbols] Unresolved symbol: _ZNK15FilePathManager15getSettingsPathEv
02:46:38 Error [MinecraftSymbols] Unresolved symbol: _ZN17PackSourceFactoryC2EP7Options
02:46:38 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepositoryC2ER18IMinecraftEventingR19PackManifestFactoryR29IContentAccessibilityProviderP15FilePathManagerR17PackSourceFactoryb
02:46:38 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepository21addWorldResourcePacksERKSs
02:46:38 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManagerC2ESt8functionIFSsvEERK18ContentTierManagerb
02:46:38 Error [MinecraftSymbols] Unresolved symbol: _ZN9Scheduler17processCoroutinesENSt6chrono8durationIxSt5ratioILx1ELx1000000000EEEE
02:46:38 Error [MinecraftSymbols] Unresolved symbol: _ZN19ServerCommandOriginC2ERKSsR11ServerLevel
02:46:38 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance16initializeServerER13IMinecraftAppR9WhitelistP15PermissionsFileP15FilePathManagerNSt6chrono8durationIxSt5ratioILx1ELx1EEEESsSsSs13LevelSettingsib20ConnectionDefinitionbRKSt6vectorISsSaISsEESsRKN3mce4UUIDER18IMinecraftEventingR22ResourcePackRepositoryRK18ContentTierManagerR19ResourcePackManagerSt8functionIFSt10unique_ptrI12LevelStorageSt14default_deleteISZ_EER9SchedulerEERKSsP9LevelDataSsSsSY_I16EducationOptionsS10_IS1B_EEPSV_SX_IFvS18_EES1G_P13ServerMetricsP13DebugEndPoint
02:46:38 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social12XboxLiveUser22_handleUISignInNoErrorERN4xbox8services6system14sign_in_resultESt8functionIFvNS_12SignInResultEbEE
02:46:38 Error [MinecraftSymbols] Unresolved symbol: _ZN2v82V810InitializeEv
02:46:38 Error [MinecraftSymbols] Unresolved symbol: _ZN2v82V818InitializePlatformEPNS_8PlatformE
02:46:38 Info  [Launcher] Game version: 1.12.0
02:46:38 Info  [Launcher] Applying patches
02:46:38 Trace [Store] Vtable size = 34
02:46:38 Trace [Patch] Patching - original: 85 83 87 86 131
02:46:38 Trace [Patch] Patching - result: 233 124 240 102 103
02:46:38 Trace [Patch] Patching - original: 83 87 86 131 236
02:46:38 Trace [Patch] Patching - result: 233 159 239 194 102
02:46:38 Trace [Patch] Patching - original: 85 83 87 86 129
02:46:38 Trace [Patch] Patching - result: 233 255 0 131 100
02:46:38 Trace [Patch] Patching - original: 85 83 87 86 129
02:46:38 Trace [Patch] Patching - result: 233 191 52 193 100
02:46:38 Trace [Patch] Patching - original: 85 83 87 86 129
02:46:38 Trace [Patch] Patching - result: 233 21 69 193 100
02:46:38 Trace [Patch] Patching - original: 85 83 87 86 129
02:46:38 Trace [Patch] Patching - result: 233 137 49 193 100
02:46:38 Trace [Patch] Patching - original: 85 83 87 86 129
02:46:38 Trace [Patch] Patching - result: 233 209 152 192 100
02:46:38 Trace [Patch] Patching - original: 85 83 87 86 129
02:46:38 Trace [Patch] Patching - result: 233 221 140 192 100
02:46:38 Trace [Patch] Patching - original: 85 83 87 86 129
02:46:38 Trace [Patch] Patching - result: 233 179 192 194 100
02:46:38 Trace [Patch] Patching - original: 83 87 86 131 236
02:46:38 Trace [Patch] Patching - result: 233 17 44 193 100
02:46:38 Trace [Patch] Patching - original: 85 83 87 86 129
02:46:38 Trace [Patch] Patching - result: 233 205 86 193 100
02:46:38 Trace [Patch] Patching - original: 49 192 195 141 182
02:46:38 Trace [Patch] Patching - result: 233 57 150 96 103
02:46:38 Trace [Patch] Patching - original: 83 131 236 8 232
02:46:38 Trace [Patch] Patching - result: 233 243 52 223 100
02:46:38 Trace [Patch] Patching - original: 137 76 36 4 137
02:46:38 Trace [Patch] Patching - result: 232 151 91 148 100
02:46:38 Trace [Patch] Patching - original: 36 88 139 65 12
02:46:38 Trace [Patch] Patching - result: 232 162 91 148 100
02:46:38 Trace [TexelAAPatch] Found patch at @2d9d
02:46:38 Trace [Patch] Patching - original: 85 83 87 86 131
02:46:38 Trace [Patch] Patching - result: 233 210 234 105 103
02:46:38 Trace [Patch] Patching - original: 85 83 87 86 129
02:46:38 Trace [Patch] Patching - result: 233 159 233 105 103
02:46:38 Trace [Patch] Patching - original: 83 87 86 131 236
02:46:38 Trace [Patch] Patching - result: 233 107 234 105 103
02:46:38 Trace [Patch] Patching - original: 85 137 229 83 87
02:46:38 Trace [Patch] Patching - result: 233 176 192 122 100
02:46:38 Trace [Patch] Patching - original: 85 83 87 86 131
02:46:38 Trace [Patch] Patching - result: 233 43 47 180 102
02:46:38 Trace [Patch] Patching - original: 232 173 62 122 253
02:46:38 Trace [Patch] Patching - result: 232 91 18 5 101
02:46:38 Info  [Launcher] Creating window
02:46:38 Trace [Launcher] Loading gamepad mappings: /usr/share//mcpelauncher/gamecontrollerdb.txt
02:46:38 Trace [Launcher] Loading gamepad mappings: /usr/share/mcpelauncher/gamecontrollerdb.txt
02:46:39 Trace [Launcher] Initializing AppPlatform (vtable)
02:46:39 Trace [AppPlatform] Vtable size = 265
02:46:39 Trace [Launcher] Initializing AppPlatform (create instance)
02:46:39 Trace [Launcher] Initializing AppPlatform (initialize call)
02:46:39 Trace [AppPlatform] createDeviceID (from file): e8c0ebba-41d1-42cc-9562-09f16c661d12
02:46:39 Info  [Launcher] OpenGL: version: OpenGL ES 3.1 Mesa 19.1.2 - padoka PPA, renderer: Mesa DRI Intel(R) HD Graphics 5500 (Broadwell GT2) x86/MMX/SSE2, vendor: Intel Open Source Technology Center
02:46:39 Trace [Launcher] Initializing MinecraftGame (create instance)
02:46:39 Trace [AppPlatform] getSystemRegion: en_US
02:46:39 Trace [Launcher] Initializing MinecraftGame (init call)
02:46:39 Info  [Launcher] Game initialized
02:46:39 Trace [AppPlatform] getDataUrl: /home/vinesnts/.local/share/mcpelauncher/versions/1.12.0.28/assets/
02:46:39 Info  [Cohtml] Initializing COHTML ver. 1.1.0.4
02:46:39 Info  [Cohtml] Coherent Renoir library initialized!
02:46:39 Info  [Cohtml] COHTML library initialized!
02:46:39 Debug [Cohtml] Media decoders module not loaded, video playback disabled.
02:46:39 Debug [Cohtml] Inspector is disabled
02:46:39 Warn  [Cohtml] Unable to load default font name Noto Sans
02:46:39 Trace [AppPlatform] getDataUrl: /home/vinesnts/.local/share/mcpelauncher/versions/1.12.0.28/assets/
02:46:39 Error [XSAPI.Android] read_local_storage: ifstream failureMalformed token
02:46:39 Trace [XboxLive] Reading xbox config file
02:46:39 Error [XSAPI.Android] java interop not initialized properly
02:46:39 Trace [Launcher] Creating store
02:46:39 Trace [Store] registerLicenseChangeCallback
02:46:39 Trace [Store] restoreFromCache
02:46:39 Trace [Launcher] HTTPRequestInternalAndroid::send stub called
02:46:39 Info  [Minecraft] NO LOG FILE! - IPv4 supported, port: 54473
02:46:39 Info  [Minecraft] NO LOG FILE! - IPv6 supported, port: 56056
02:46:39 Trace [AppPlatform] isTablet: true
02:46:39 Trace [AppPlatform] getSystemRegion: en_US
02:46:39 Trace [AppPlatform] getApplicationId: com.mojang.minecraftpe
02:46:39 Trace [Launcher] HTTPRequestInternalAndroid::send stub called
02:46:39 Trace [Launcher] HTTPRequestInternalAndroid::send stub called
02:46:39 Trace [Launcher] HTTPRequestInternalAndroid::send stub called
02:46:39 Trace [Launcher] HTTPRequestInternalAndroid::send stub called
02:46:39 Trace [Store] getStoreId: android.googleplay
02:46:39 Debug [Cohtml] Force prunning all orphaned images.
02:46:39 Debug [Cohtml] Force prunning all orphaned svgs.
02:46:39 Trace [Store] getStoreId: android.googleplay
02:46:39 Trace [Store] receivedLicenseResponse: true
02:46:39 Trace [Store] isGameLicensed: true
02:46:39 Warn  [Store] getExtraLicenseData - not implemented
02:46:39 Trace [Launcher] HTTPRequestInternalAndroid::send stub called
02:46:39 Trace [Launcher] HTTPRequestInternalAndroid::send stub called
02:46:39 Trace [XboxLive] verify_cert_chain_platform_specific stub called
02:46:39 Trace [XboxLive] verify_cert_chain_platform_specific stub called
02:46:40 Trace [XboxLive] verify_cert_chain_platform_specific stub called
02:46:40 Trace [XboxLive] verify_cert_chain_platform_specific stub called
02:46:40 Trace [XboxLive] verify_cert_chain_platform_specific stub called
02:46:40 Trace [XboxLive] verify_cert_chain_platform_specific stub called
02:46:40 Debug [Cohtml] Force prunning all orphaned images.
02:46:40 Debug [Cohtml] Force prunning all orphaned svgs.
02:46:40 Trace [Launcher] HTTPRequestInternalAndroid::send stub called
02:46:40 Trace [XboxLive] verify_cert_chain_platform_specific stub called
02:46:40 Trace [XboxLive] verify_cert_chain_platform_specific stub called
02:46:41 Trace [XboxLive] verify_cert_chain_platform_specific stub called
02:46:41 Trace [XboxLive] verify_cert_chain_platform_specific stub called
02:46:41 Trace [XboxLive] verify_cert_chain_platform_specific stub called
02:46:41 Trace [XboxLive] verify_cert_chain_platform_specific stub called
02:46:42 Trace [XboxLive] verify_cert_chain_platform_specific stub called
02:46:42 Trace [XboxLive] verify_cert_chain_platform_specific stub called
02:46:42 Trace [XboxLive] verify_cert_chain_platform_specific stub called
02:46:42 Trace [XboxLive] verify_cert_chain_platform_specific stub called
02:46:43 Trace [XboxLive] verify_cert_chain_platform_specific stub called
02:46:43 Trace [XboxLive] verify_cert_chain_platform_specific stub called
02:46:43 Trace [XboxLive] verify_cert_chain_platform_specific stub called
02:46:43 Trace [XboxLive] verify_cert_chain_platform_specific stub called
02:46:43 Trace [Store] getStoreId: android.googleplay
02:46:43 Trace [Store] onPrimaryUserConnectedToPlatform
02:46:43 Info  [Minecraft] NO LOG FILE! - IPv4 supported, port: 35834
02:46:43 Info  [Minecraft] NO LOG FILE! - IPv6 supported, port: 51157
02:46:43 Trace [Store] queryProducts
02:46:43 Trace [Store] queryProducts
02:46:43 Trace [Launcher] HTTPRequestInternalAndroid::send stub called
02:46:43 Trace [Store] queryPurchases
02:46:43 Trace [Launcher] HTTPRequestInternalAndroid::send stub called
02:46:43 Trace [Launcher] HTTPRequestInternalAndroid::send stub called
02:46:43 Trace [Launcher] HTTPRequestInternalAndroid::send stub called
02:46:43 Trace [XboxLive] verify_cert_chain_platform_specific stub called
02:46:43 Trace [XboxLive] verify_cert_chain_platform_specific stub called
02:46:43 Trace [Launcher] HTTPRequestInternalAndroid::send stub called
02:46:43 Trace [Launcher] HTTPRequestInternalAndroid::send stub called
02:46:44 Trace [XboxLive] verify_cert_chain_platform_specific stub called
02:46:44 Trace [XboxLive] verify_cert_chain_platform_specific stub called
02:46:44 Trace [XboxLive] verify_cert_chain_platform_specific stub called
02:46:44 Trace [XboxLive] verify_cert_chain_platform_specific stub called
02:46:44 Trace [XboxLive] verify_cert_chain_platform_specific stub called
02:46:44 Trace [XboxLive] verify_cert_chain_platform_specific stub called
02:46:44 Trace [XboxLive] verify_cert_chain_platform_specific stub called
02:46:44 Trace [XboxLive] verify_cert_chain_platform_specific stub called
02:46:44 Trace [XboxLive] verify_cert_chain_platform_specific stub called
02:46:44 Trace [XboxLive] verify_cert_chain_platform_specific stub called
02:46:46 Trace [XboxLive] verify_cert_chain_platform_specific stub called
02:46:46 Trace [XboxLive] verify_cert_chain_platform_specific stub called
02:46:46 Trace [XboxLive] verify_cert_chain_platform_specific stub called
02:46:46 Trace [XboxLive] verify_cert_chain_platform_specific stub called
02:46:48 Trace [Launcher] HTTPRequestInternalAndroid::send stub called
02:46:48 Trace [XboxLive] verify_cert_chain_platform_specific stub called
02:46:48 Trace [XboxLive] verify_cert_chain_platform_specific stub called
02:46:48 Trace [XboxLive] verify_cert_chain_platform_specific stub called
02:46:48 Trace [XboxLive] verify_cert_chain_platform_specific stub called
02:46:48 Trace [XboxLive] verify_cert_chain_platform_specific stub called
02:46:48 Trace [XboxLive] verify_cert_chain_platform_specific stub called
02:46:48 Trace [XboxLive] verify_cert_chain_platform_specific stub called
02:46:48 Trace [XboxLive] verify_cert_chain_platform_specific stub called
02:46:50 Trace [XboxLive] verify_cert_chain_platform_specific stub called
02:46:50 Trace [XboxLive] verify_cert_chain_platform_specific stub called
02:46:50 Trace [Launcher] HTTPRequestInternalAndroid::send stub called
02:46:52 Trace [XboxLive] verify_cert_chain_platform_specific stub called
02:46:52 Trace [XboxLive] verify_cert_chain_platform_specific stub called
02:46:54 Trace [Launcher] HTTPRequestInternalAndroid::send stub called
02:46:55 Trace [Launcher] HTTPRequestInternalAndroid::send stub called
02:46:55 Trace [XboxLive] verify_cert_chain_platform_specific stub called
02:46:55 Trace [XboxLive] verify_cert_chain_platform_specific stub called
02:46:55 Trace [XboxLive] verify_cert_chain_platform_specific stub called
02:46:55 Trace [XboxLive] verify_cert_chain_platform_specific stub called
02:46:55 Trace [XboxLive] verify_cert_chain_platform_specific stub called
02:46:55 Trace [XboxLive] verify_cert_chain_platform_specific stub called
02:46:57 Trace [XboxLive] verify_cert_chain_platform_specific stub called
02:46:57 Trace [XboxLive] verify_cert_chain_platform_specific stub called
02:47:00 Trace [XboxLive] verify_cert_chain_platform_specific stub called
02:47:00 Trace [XboxLive] verify_cert_chain_platform_specific stub called
02:47:02 Debug [XSAPI.Android] sign_in_impl: will NOT be showing UI
02:47:02 Trace [XboxLive] log_telemetry_signin 1 Entering
02:47:02 Trace [Launcher] init_sign_in_activity 1
02:47:02 Trace [XboxLive] log_telemetry_signin 1 Exiting - user_interaction_required
02:47:02 Trace [Launcher] HTTPRequestInternalAndroid::send stub called
02:47:02 Debug [XSAPI.Android] sign_in_impl: will be showing UI
02:47:02 Debug [XSAPI.Android] sign_in_impl: native activity, continuing on
02:47:02 Trace [XboxLive] log_telemetry_signin 0 Entering
02:47:02 Trace [Launcher] init_sign_in_activity 1
02:47:02 Trace [XboxLive] invoke_auth_flow
02:47:02 Trace [Launcher] HTTPRequestInternalAndroid::send stub called
02:47:02 Trace [Launcher] HTTPRequestInternalAndroid::send stub called
02:47:39 Trace [Launcher] HTTPRequestInternalAndroid::send stub called
02:48:39 Trace [Launcher] HTTPRequestInternalAndroid::send stub called
02:48:52 Trace [XboxLiveGameInterface] Got account CID and token
02:48:52 Trace [XboxLiveGameInterface] Invoking XBL login
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to initialize default nsal
Signal 6 received
Backtrace elements: 25
#0 /usr/bin/mcpelauncher-client(_ZN12CrashHandler12handleSignalEiPv+0xc5) [0x5679620f]
#1 linux-gate.so.1(__kernel_sigreturn+0) [0xf7ef2960]
#2 linux-gate.so.1(__kernel_vsyscall+0x9) [0xf7ef2949]
#3 /lib/i386-linux-gnu/libc.so.6(gsignal+0xc2) [0xf77c8832]
#4 /lib/i386-linux-gnu/libc.so.6(abort+0x121) [0xf77c9cc1]
#5 /usr/lib/i386-linux-gnu/libstdc++.so.6(+0x6e97d) [0xf7b2697d]
#6 /usr/lib/i386-linux-gnu/libstdc++.so.6(+0x760f4) [0xf7b2e0f4]
#7 /usr/lib/i386-linux-gnu/libstdc++.so.6(+0x7615d) [0xf7b2e15d]
#8 /usr/lib/i386-linux-gnu/libstdc++.so.6(+0x7645c) [0xf7b2e45c]
#9 /usr/bin/mcpelauncher-client(_ZN28XboxLiveDefaultGameInterface14invokeXblLoginIN4xbox8services6system12auth_managerEEEDaRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESC_+0x146) [0x567834da]
#10 /usr/bin/mcpelauncher-client(_ZN28XboxLiveDefaultGameInterface23completeAndroidAuthFlowERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES7_+0x8d) [0x5678187b]
#11 /usr/bin/mcpelauncher-client(+0x20bec5) [0x56780ec5]
#12 /usr/bin/mcpelauncher-client(+0x20d497) [0x56782497]
#13 /usr/bin/mcpelauncher-client(_ZNKSt8functionIFvRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES7_EEclES7_S7_+0x59) [0x567747c3]
#14 /usr/bin/mcpelauncher-client(+0x1fb975) [0x56770975]
#15 /usr/bin/mcpelauncher-client(+0x1fcbb3) [0x56771bb3]
#16 /usr/bin/mcpelauncher-client(_ZNKSt8functionIFvN9simpleipc10rpc_resultISt10shared_ptrIN3msa6client5TokenEEEEEEclES7_+0x4a) [0x56775c6c]
#17 /usr/bin/mcpelauncher-client(_ZZN9simpleipc6client8rpc_callISt10shared_ptrIN3msa6client5TokenEEE4callESt8functionIFvNS_10rpc_resultIS6_EEEEENKUlNS9_IN8nlohmann10basic_jsonISt3mapSt6vectorNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEbxydSaNSD_14adl_serializerEEEEEE_clESP_+0x55) [0x56774881]
#18 /usr/bin/mcpelauncher-client(_ZNSt17_Function_handlerIFvN9simpleipc10rpc_resultIN8nlohmann10basic_jsonISt3mapSt6vectorNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEbxydSaNS2_14adl_serializerEEEEEEZNS0_6client8rpc_callISt10shared_ptrIN3msa6client5TokenEEE4callESt8functionIFvNS1_ISM_EEEEEUlSE_E_E9_M_invokeERKSt9_Any_dataOSE_+0x65) [0x56776fa0]
#19 /usr/bin/mcpelauncher-client(_ZNKSt8functionIFvN9simpleipc10rpc_resultIN8nlohmann10basic_jsonISt3mapSt6vectorNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEbxydSaNS2_14adl_serializerEEEEEEEclESE_+0x4a) [0x5682ceb6]
#20 /usr/bin/mcpelauncher-client(_ZN9simpleipc6client14service_client14handle_messageERKNS_16response_messageE+0xb8) [0x5682bbf0]
#21 /usr/bin/mcpelauncher-client(_ZN9simpleipc6client24base_service_client_impl14handle_messageERNS_10connectionERKNS_16response_messageE+0x4f) [0x56818d6d]
#22 /usr/bin/mcpelauncher-client(_ZN9simpleipc19connection_internal10on_messageERKNS_17message_containerE+0x78) [0x568365d4]
#23 /usr/bin/mcpelauncher-client(_ZN9simpleipc19connection_internal21handle_data_availableEv+0x35a) [0x5683615c]
#24 /usr/bin/mcpelauncher-client(+0x2c02fb) [0x568352fb]
Dumping stack...
#130 HYBRIS (null)+-192240568 in libminecraftpe.so+0x6d8e448 [0xf48aa448]
#131 HYBRIS (null)+-189587392 in libminecraftpe.so+0x7016040 [0xf4b32040]
#132 HYBRIS boost::asio::ssl::detail::openssl_init_base::do_init::openssl_locking_func(int, int, char const*, int)+61 in libminecraftpe.so+0x15c125d [0xef0dd25d]
#135 HYBRIS (null)+-217206511 in libminecraftpe.so+0x55bf111 [0xf30db111]
#162 HYBRIS (null)+-192240568 in libminecraftpe.so+0x6d8e448 [0xf48aa448]
#163 HYBRIS (null)+-189587392 in libminecraftpe.so+0x7016040 [0xf4b32040]
#164 HYBRIS boost::asio::ssl::detail::openssl_init_base::do_init::openssl_locking_func(int, int, char const*, int)+61 in libminecraftpe.so+0x15c125d [0xef0dd25d]
#167 HYBRIS (null)+-217206511 in libminecraftpe.so+0x55bf111 [0xf30db111]
#175 HYBRIS (null)+-192240568 in libminecraftpe.so+0x6d8e448 [0xf48aa448]
#176 HYBRIS (null)+64 in libminecraftpe.so+0x5318940 [0xf2e34940]
#179 HYBRIS (null)+-217206511 in libminecraftpe.so+0x55bf111 [0xf30db111]
#185 HYBRIS (null)+7 in libminecraftpe.so+0x5318907 [0xf2e34907]
#186 HYBRIS (null)+-192240568 in libminecraftpe.so+0x6d8e448 [0xf48aa448]
#187 HYBRIS (null)+-217206511 in libminecraftpe.so+0x55bf111 [0xf30db111]
#188 HYBRIS (null)+150 in libminecraftpe.so+0x5318ef6 [0xf2e34ef6]
#191 HYBRIS (null)+-217206511 in libminecraftpe.so+0x55bf111 [0xf30db111]
#193 HYBRIS (null)+-217206511 in libminecraftpe.so+0x55bf111 [0xf30db111]
#194 HYBRIS (null)+-192240568 in libminecraftpe.so+0x6d8e448 [0xf48aa448]
#196 HYBRIS boost::asio::ssl::detail::openssl_init_base::do_init::openssl_locking_func(int, int, char const*, int)+61 in libminecraftpe.so+0x15c125d [0xef0dd25d]
#198 HYBRIS (null)+6 in libminecraftpe.so+0x5318546 [0xf2e34546]
#199 HYBRIS (null)+-192240568 in libminecraftpe.so+0x6d8e448 [0xf48aa448]
#203 HYBRIS (null)+9 in libminecraftpe.so+0x5318e69 [0xf2e34e69]
#204 HYBRIS (null)+-192240568 in libminecraftpe.so+0x6d8e448 [0xf48aa448]
#206 HYBRIS (null)+-217206511 in libminecraftpe.so+0x55bf111 [0xf30db111]
#208 HYBRIS (null)+-219806865 in libminecraftpe.so+0x534436f [0xf2e6036f]
#209 HYBRIS (null)+-189587392 in libminecraftpe.so+0x7016040 [0xf4b32040]
#272 HYBRIS (null)+-218531671 in libminecraftpe.so+0x547b8a9 [0xf2f978a9]
#299 HYBRIS (null)+-218531671 in libminecraftpe.so+0x547b8a9 [0xf2f978a9]
#730 HYBRIS (null)+-191771596 in libminecraftpe.so+0x6e00c34 [0xf491cc34]
Process exited with unexpected exit code: 6

**Comment by Mhowser** [comment]
Please update the launcher and msa components.

**Comment by zvillager10** [comment]
> Please update the launcher and msa components.

How? I am having a similar problem to this.. everytime I click sign in it says that I failed to sign in at the moment

**Comment by Mhowser** [comment]
What OS did you install it on? Are you using a package manager or the appimage?

**Comment by zvillager10** [comment]
ya about that, turns out it was my faul that was happening, but anyways I
got it to work. Any news about getting the new version fixed already?

**Comment by Mhowser** [comment]
Would you mind sharing the steps you took to fix it for others?

**Comment by zvillager10** [comment]
I highly doubt what I was experiencing was what they're experiencing.. and
my solution is only a reasonable solution if you don't have much files or
important thins in your computer, for I had to reset my os (using gainings
resetter) and that solve whatever stupid mistake I did. But again, any news
about the new update getting fixed? I really am looking forward to it
