### ISSUE TITLE
Minecraft crashes when clicking mouse buttons

### ISSUE THREAD

**Issue by ElLucioVpe** [minecraft-linux/mcpelauncher-manifest#15]
Minecraft crashes when you press any mouse button that isn't a "click" one or the wheel. For example, if you press the forward mouse button, Minecraft crashes.

**Comment by MCMrARM** [comment]
Fixed with https://github.com/minecraft-linux/mcpelauncher-manifest/commit/78e4fdd2a84309b0bbc72cc035747e748395f49d
