### ISSUE TITLE
Xbox Live login not working on AppImage: Workaround

### ISSUE THREAD

**Issue by PoizonCloud** [minecraft-linux/mcpelauncher-manifest#152]
There is two problems:

The AppImage includes the msa-daemon binary but doesn't call it.
The msa-daemon will not let you login if you don't preload libnss3.so.

To be able to run the msa-daemon from the AppImage you will have to mount it on a folder:

1- Create a folder in your home directory to mount the AppImage. I'll use "mcpelauncher_appimage" as an example.

2- Navigate to the folder where you have the MCPELauncher AppImage, open a terminal and run it like this: `./Minecraft_Bedrock_Launcher.AppImage --appimage-offset` and copy the output number.

3- Mount the AppImage with `sudo mount path/to/appimage/Minecraft_Bedrock_Launcher.AppImage ~/mcpelauncher_appimage -o offset=(output number from previous command)`.

4- Launch the MSA daemon with the libnss3.so library preloaded (library location may be different): `LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libnss3.so ~/mcpelauncher_appimage/usr/bin/./msa-daemon` leave this terminal open.

5- Navigate to ~/mcpelauncher_appimage in your file manager and open the AppRun file or open a second terminal and run `~/mcpelauncher_appimage/usr/bin/./mcpelauncher-ui-qt` to run the launcher and open the game.

After that, Xbox Live login should work

The AppImage itself can't be run while it's mounted. To go back as normal, unmount it with `sudo umount ~/mcpelauncher_appimage`.

**Comment by mikaelprag** [comment]
Works for me (Debian 10), thanks!

**Comment by ChristopherHX** [comment]
This bug of the AppImage was fixed by my PR small https://github.com/minecraft-linux/linux-packaging-scripts/pull/3

Also fixed google login crash
