### ISSUE TITLE
1.13.0.13 Support

### ISSUE THREAD

**Issue by Titaniumtown** [minecraft-linux/mcpelauncher-manifest#153]
When I run minecraft pe version 1.13.0.13 I get this error immediately:

16:05:22 Info  [Launcher] Version: client a83f857 / manifest a94d2ef
16:05:22 Info  [Launcher] CPU: GenuineIntel        Intel(R) Core(TM) i7-3520M CPU @ 2.90GHz
16:05:22 Info  [Launcher] CPU supports SSSE3: YES
16:05:22 Trace [Launcher] Loading hybris libraries
16:05:22 Trace [HybrisUtils] Loaded OS library /home/simon/mcpelauncher-manifest/mcpelauncher-linux-bin/libs/native/libfmod.so.9.16
16:05:22 Trace [HybrisUtils] Loaded OS library libm.so.6
16:05:22 Trace [HybrisUtils] Loaded OS library libz.so.1
16:05:22 Trace [Launcher] Loading Minecraft library
16:05:23 Info  [Launcher] Loaded Minecraft library
16:05:23 Debug [Launcher] Minecraft is at offset 0xee23e000
16:05:23 Error [MinecraftSymbols] Unresolved symbol: _ZN3App4initER10AppContext
16:05:23 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App4quitERKSsS1_
16:05:23 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App6updateEv
16:05:23 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App16setRenderingSizeEii
16:05:23 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App17setUISizeAndScaleEiif
16:05:23 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App10wantToQuitEv
16:05:23 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServiceLocatorI11AppPlatformE15mDefaultServiceE
16:05:23 Error [MinecraftSymbols] Unresolved symbol: _ZNK11AppPlatform22getHardwareInformationEv
16:05:23 Error [MinecraftSymbols] Unresolved symbol: _ZN17AppResourceLoaderC2ESt8functionIFSsvEE
16:05:23 Error [MinecraftSymbols] Unresolved symbol: _ZN10Automation16AutomationClientC2ER13IMinecraftApp
16:05:23 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance7getUserEv
16:05:23 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance15_startLeaveGameEv
16:05:23 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance16_syncDestroyGameEv
16:05:23 Error [MinecraftSymbols] Unresolved symbol: _ZNK13CommandOutput11getMessagesEv
16:05:23 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender9translateERKSt6vectorISsSaISsEE
16:05:23 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSenderC2ERN10Automation16AutomationClientE
16:05:23 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSenderD2Ev
16:05:23 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender4sendERK13CommandOriginRK13CommandOutput
16:05:23 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender22registerOutputCallbackERKSt8functionIFvR19AutomationCmdOutputEE
16:05:23 Error [MinecraftSymbols] Unresolved symbol: _ZN6Common23getGameVersionStringNetEv
16:05:23 Error [MinecraftSymbols] Unresolved symbol: _ZN30ExternalFileLevelStorageSourceC2EP15FilePathManagerSt10shared_ptrI22SaveTransactionManagerE
16:05:23 Error [MinecraftSymbols] Unresolved symbol: _ZN30ExternalFileLevelStorageSource18createLevelStorageER9SchedulerRKSsRK15ContentIdentityRK19IContentKeyProvider
16:05:23 Error [MinecraftSymbols] Unresolved symbol: _ZN15FilePathManagerC2ESsb
16:05:23 Error [MinecraftSymbols] Unresolved symbol: _ZNK15FilePathManager11getRootPathEv
16:05:23 Error [MinecraftSymbols] Unresolved symbol: _ZNK15FilePathManager15getUserDataPathEv
16:05:23 Error [MinecraftSymbols] Unresolved symbol: _ZNK15FilePathManager13getWorldsPathEv
16:05:23 Error [MinecraftSymbols] Unresolved symbol: _ZN15FilePathManager14setPackagePathESs
16:05:23 Error [MinecraftSymbols] Unresolved symbol: _ZNK15FilePathManager14getPackagePathEv
16:05:23 Error [MinecraftSymbols] Unresolved symbol: _ZN15FilePathManager15setSettingsPathESs
16:05:23 Error [MinecraftSymbols] Unresolved symbol: _ZNK15FilePathManager15getSettingsPathEv
16:05:23 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourceLoadManagerC2Ev
16:05:23 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourceLoadManager4syncE16ResourceLoadType
16:05:23 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n3getERKSsRKSt6vectorISsSaISsEE
16:05:23 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n14chooseLanguageERKSs
16:05:23 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n13loadLanguagesER19ResourcePackManagerR19ResourceLoadManagerRKSs
16:05:23 Error [MinecraftSymbols] Unresolved symbol: _ZN5Level16createRandomSeedEv
16:05:23 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettingsC2Ev
16:05:23 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettingsC2ERKS_
16:05:23 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettings15parseSeedStringERKSsj
16:05:23 Error [MinecraftSymbols] Unresolved symbol: _ZN9Minecraft11getCommandsEv
16:05:23 Error [MinecraftSymbols] Unresolved symbol: _ZNK9Minecraft8getLevelEv
16:05:23 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftCommands15setOutputSenderESt10unique_ptrI19CommandOutputSenderSt14default_deleteIS1_EE
16:05:23 Error [MinecraftSymbols] Unresolved symbol: _ZNK17MinecraftCommands23requestCommandExecutionESt10unique_ptrI13CommandOriginSt14default_deleteIS1_EERKSsib
16:05:23 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftEventingC2ERKSs
16:05:23 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftEventing4initEv
16:05:23 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGameC2EiPPc
16:05:23 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGameD2Ev
16:05:23 Error [MinecraftSymbols] Unresolved symbol: _ZNK13MinecraftGame8isInGameEv
16:05:23 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame16requestLeaveGameEbb
16:05:23 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame24doPrimaryClientReadyWorkESt8functionIFvvEE
16:05:23 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame21getPrimaryUserOptionsEv
16:05:23 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame24getPrimaryClientInstanceEv
16:05:23 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame14startLeaveGameEv
16:05:23 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame17continueLeaveGameEv
16:05:23 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame14setTextboxTextERKSsi
16:05:23 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel32navigateToXblConsoleSignInScreenERKSsS1_
16:05:23 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel41navigateToXblConsoleSignInSucceededScreenERKN6Social12SignInResultESt8functionIFvS1_EEb
16:05:23 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel11leaveScreenEv
16:05:23 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social14MultiplayerXBLC2Ev
16:05:23 Error [MinecraftSymbols] Unresolved symbol: _ZTV22NullTextToSpeechClient
16:05:23 Error [MinecraftSymbols] Unresolved symbol: _ZNK7Options13getFullscreenEv
16:05:23 Error [MinecraftSymbols] Unresolved symbol: _ZN7Options13setFullscreenEb
16:05:23 Error [MinecraftSymbols] Unresolved symbol: _ZN15PermissionsFileC2ERKSs
16:05:23 Error [MinecraftSymbols] Unresolved symbol: _ZN19SkinPackKeyProviderC2Ev
16:05:23 Error [MinecraftSymbols] Unresolved symbol: _ZN19PackManifestFactoryC2ER14IPackTelemetry
16:05:23 Error [MinecraftSymbols] Unresolved symbol: _ZN17PackSourceFactoryC2EP7Options
16:05:23 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepositoryC2ER18IMinecraftEventingR19PackManifestFactoryR29IContentAccessibilityProviderP15FilePathManagerR17PackSourceFactoryb
16:05:23 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepository21addWorldResourcePacksERKSs
16:05:23 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepository12refreshPacksEv
16:05:23 Error [MinecraftSymbols] Unresolved symbol: _ZN18ContentTierManagerC2Ev
16:05:23 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManagerC2ESt8functionIFSsvEERK18ContentTierManagerb
16:05:23 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManager8setStackESt10unique_ptrI17ResourcePackStackSt14default_deleteIS1_EE21ResourcePackStackTypeb
16:05:23 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManager17onLanguageChangedEv
16:05:23 Error [MinecraftSymbols] Unresolved symbol: _ZN12PackInstanceC2EP12ResourcePackibP12PackSettings
16:05:23 Error [MinecraftSymbols] Unresolved symbol: _ZTV17ResourcePackStack
16:05:23 Error [MinecraftSymbols] Unresolved symbol: _ZN17ResourcePackStack3addE12PackInstanceRK22ResourcePackRepositoryb
16:05:23 Error [MinecraftSymbols] Unresolved symbol: _ZN22SaveTransactionManagerC2ESt8functionIFvbEE
16:05:23 Error [MinecraftSymbols] Unresolved symbol: _ZN9Scheduler17processCoroutinesENSt6chrono8durationIxSt5ratioILx1ELx1000000000EEEE
16:05:23 Error [MinecraftSymbols] Unresolved symbol: _ZN18MinecraftScheduler6clientEv
16:05:23 Error [MinecraftSymbols] Unresolved symbol: _ZN19ServerCommandOriginC2ERKSsR11ServerLevel
16:05:23 Error [MinecraftSymbols] Unresolved symbol: _ZN16EducationOptionsC2EP19ResourcePackManager
16:05:23 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstanceC2ER13IMinecraftAppR30ServerInstanceEventCoordinator
16:05:23 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance16initializeServerER13IMinecraftAppR9WhitelistP15PermissionsFileP15FilePathManagerNSt6chrono8durationIxSt5ratioILx1ELx1EEEESsSsSs13LevelSettingsib20ConnectionDefinitionbRKSt6vectorISsSaISsEESsRKN3mce4UUIDER18IMinecraftEventingR22ResourcePackRepositoryRK18ContentTierManagerR19ResourcePackManagerSt8functionIFSt10unique_ptrI12LevelStorageSt14default_deleteISZ_EER9SchedulerEERKSsP9LevelDataSsSsSY_I16EducationOptionsS10_IS1B_EEPSV_SX_IFvS18_EES1G_P13ServerMetricsP13DebugEndPoint
16:05:23 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstanceD2Ev
16:05:23 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance17startServerThreadEv
16:05:23 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance13leaveGameSyncEv
16:05:23 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance20queueForServerThreadESt8functionIFvvEE
16:05:23 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12MajorVersionE
16:05:23 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12MinorVersionE
16:05:23 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12PatchVersionE
16:05:23 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants15RevisionVersionE
16:05:23 Error [MinecraftSymbols] Unresolved symbol: _ZNK6Social4User11getLiveUserEv
16:05:23 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social12XboxLiveUser22_handleUISignInNoErrorERN4xbox8services6system14sign_in_resultESt8functionIFvNS_12SignInResultEbEE
16:05:23 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN9GameStore18onStoreInitializedEb
16:05:23 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN9GameStore22onQueryProductsSuccessERKSt6vectorI11ProductInfoSaIS1_EE
16:05:23 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social11UserManager17CreateUserManagerEv
16:05:23 Error [MinecraftSymbols] Unresolved symbol: _ZN2v82V810InitializeEv
16:05:23 Error [MinecraftSymbols] Unresolved symbol: _ZN2v82V818InitializePlatformEPNS_8PlatformE
16:05:23 Error [MinecraftSymbols] Unresolved symbol: _ZNK4pplx4taskIN4xbox8services16xbox_live_resultINS2_6system26token_and_signature_resultEEEE3getEv
16:05:23 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl15getOpenGLVendorEv
16:05:23 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl17getOpenGLRendererEv
16:05:23 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl16getOpenGLVersionEv
16:05:23 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl19getOpenGLExtensionsEv
16:05:23 Error [MinecraftSymbols] Unresolved symbol: _ZN3mce8Platform3OGL12InitBindingsEv
Signal 11 received
Backtrace elements: 2
#0 /usr/local/bin/mcpelauncher-client(_ZN12CrashHandler12handleSignalEiPv+0xc5) [0x56862ab1]
#1 linux-gate.so.1(__kernel_sigreturn+0) [0xf7ee7940]
Dumping stack...
#2 HYBRIS (null)+-210793428 in libminecraftpe.so+0x54bac2c [0xf36f8c2c]
#13 HYBRIS (null)+-299638784 in libminecraftpe.so+0x0000 [0xee23e000]
#20 HYBRIS (null)+-210793428 in libminecraftpe.so+0x54bac2c [0xf36f8c2c]
#21 HYBRIS (null)+-210793471 in libminecraftpe.so+0x54bac01 [0xf36f8c01]
#23 HYBRIS (null)+-210793428 in libminecraftpe.so+0x54bac2c [0xf36f8c2c]
#24 HYBRIS (null)+-210793471 in libminecraftpe.so+0x54bac01 [0xf36f8c01]
#26 HYBRIS (null)+-210793428 in libminecraftpe.so+0x54bac2c [0xf36f8c2c]
#27 HYBRIS (null)+-210793471 in libminecraftpe.so+0x54bac01 [0xf36f8c01]
#29 HYBRIS (null)+-210793428 in libminecraftpe.so+0x54bac2c [0xf36f8c2c]
#30 HYBRIS (null)+-210793471 in libminecraftpe.so+0x54bac01 [0xf36f8c01]
#32 HYBRIS (null)+-210793428 in libminecraftpe.so+0x54bac2c [0xf36f8c2c]
#33 HYBRIS (null)+-210793471 in libminecraftpe.so+0x54bac01 [0xf36f8c01]
#109 HYBRIS std::unordered_map<unsigned char, std::string, std::hash<unsigned char>, std::equal_to<unsigned char>, std::allocator<std::pair<unsigned char const, std::string> > >::~unordered_map()+0 in libminecraftpe.so+0x3c91bb0 [0xf1ecfbb0]
#110 HYBRIS (null)+-179433448 in libminecraftpe.so+0x72a3018 [0xf54e1018]
#111 HYBRIS (null)+-180092928 in libminecraftpe.so+0x7202000 [0xf5440000]
#114 HYBRIS (null)+-180200804 in libminecraftpe.so+0x71e7a9c [0xf5425a9c]
#116 HYBRIS (null)+-290498424 in libminecraftpe.so+0x8b7888 [0xeeaf5888]
#117 HYBRIS std::unordered_map<unsigned char, std::string, std::hash<unsigned char>, std::equal_to<unsigned char>, std::allocator<std::pair<unsigned char const, std::string> > >::~unordered_map()+0 in libminecraftpe.so+0x3c91bb0 [0xf1ecfbb0]
#118 HYBRIS (null)+-179433448 in libminecraftpe.so+0x72a3018 [0xf54e1018]
#137 HYBRIS (null)+-236422524 in libminecraftpe.so+0x3c49a84 [0xf1e87a84]
#139 HYBRIS (null)+-239950971 in libminecraftpe.so+0x38ec385 [0xf1b2a385]
#143 HYBRIS (null)+-239939449 in libminecraftpe.so+0x38ef087 [0xf1b2d087]
#149 HYBRIS (null)+-239939446 in libminecraftpe.so+0x38ef08a [0xf1b2d08a]
#163 HYBRIS (null)+-210960373 in libminecraftpe.so+0x549200b [0xf36d000b]
#164 HYBRIS (null)+-180200804 in libminecraftpe.so+0x71e7a9c [0xf5425a9c]
#167 HYBRIS xbox::services::serviceLocales+0 in libminecraftpe.so+0x72a4250 [0xf54e2250]
#168 HYBRIS std::_Hashtable<std::string, std::pair<std::string const, std::string>, std::allocator<std::pair<std::string const, std::string> >, std::__detail::_Select1st, std::equal_to<std::string>, std::hash<std::string>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::_M_insert_unique_node(unsigned int, unsigned int, std::__detail::_Hash_node<std::pair<std::string const, std::string>, true>*)+71 in libminecraftpe.so+0x966227 [0xeeba4227]
#170 HYBRIS xbox::services::serviceLocales+16 in libminecraftpe.so+0x72a4260 [0xf54e2260]
#174 HYBRIS (null)+-180200804 in libminecraftpe.so+0x71e7a9c [0xf5425a9c]
#176 HYBRIS operator new(unsigned int)+39 in libminecraftpe.so+0x54413a7 [0xf367f3a7]
#179 HYBRIS (null)+-239891559 in libminecraftpe.so+0x38fab99 [0xf1b38b99]
#180 HYBRIS xbox::services::serviceLocales+8 in libminecraftpe.so+0x72a4258 [0xf54e2258]
#181 HYBRIS (null)+-210934528 in libminecraftpe.so+0x5498500 [0xf36d6500]
#186 HYBRIS (null)+-180200804 in libminecraftpe.so+0x71e7a9c [0xf5425a9c]
#188 HYBRIS std::pair<std::__detail::_Node_iterator<std::pair<std::string const, std::string>, false, true>, bool> std::_Hashtable<std::string, std::pair<std::string const, std::string>, std::allocator<std::pair<std::string const, std::string> >, std::__detail::_Select1st, std::equal_to<std::string>, std::hash<std::string>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::_M_insert<std::pair<std::string const, std::string> const&, std::__detail::_AllocNode<std::allocator<std::__detail::_Hash_node<std::pair<std::string const, std::string>, true> > > >(std::pair<std::string const, std::string> const&, std::__detail::_AllocNode<std::allocator<std::__detail::_Hash_node<std::pair<std::string const, std::string>, true> > > const&, std::integral_constant<bool, true>)+212 in libminecraftpe.so+0x17b0d34 [0xef9eed34]
#190 HYBRIS xbox::services::serviceLocales+0 in libminecraftpe.so+0x72a4250 [0xf54e2250]
#196 HYBRIS std::pair<std::__detail::_Node_iterator<std::pair<std::string const, std::string>, false, true>, bool> std::_Hashtable<std::string, std::pair<std::string const, std::string>, std::allocator<std::pair<std::string const, std::string> >, std::__detail::_Select1st, std::equal_to<std::string>, std::hash<std::string>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::_M_insert<std::pair<std::string const, std::string> const&, std::__detail::_AllocNode<std::allocator<std::__detail::_Hash_node<std::pair<std::string const, std::string>, true> > > >(std::pair<std::string const, std::string> const&, std::__detail::_AllocNode<std::allocator<std::__detail::_Hash_node<std::pair<std::string const, std::string>, true> > > const&, std::integral_constant<bool, true>)+12 in libminecraftpe.so+0x17b0c6c [0xef9eec6c]
#206 HYBRIS (null)+-180200804 in libminecraftpe.so+0x71e7a9c [0xf5425a9c]
#208 HYBRIS std::_Hashtable<std::string, std::pair<std::string const, std::string>, std::allocator<std::pair<std::string const, std::string> >, std::__detail::_Select1st, std::equal_to<std::string>, std::hash<std::string>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::_Hashtable<std::pair<std::string const, std::string> const*>(std::pair<std::string const, std::string> const*, std::pair<std::string const, std::string> const*, unsigned int, std::hash<std::string> const&, std::__detail::_Mod_range_hashing const&, std::__detail::_Default_ranged_hash const&, std::equal_to<std::string> const&, std::__detail::_Select1st const&, std::allocator<std::pair<std::string const, std::string> > const&)+236 in libminecraftpe.so+0x21d81fc [0xf04161fc]
#210 HYBRIS xbox::services::serviceLocales+0 in libminecraftpe.so+0x72a4250 [0xf54e2250]
#213 HYBRIS (null)+-239851606 in libminecraftpe.so+0x39047aa [0xf1b427aa]
#214 HYBRIS (null)+-180200804 in libminecraftpe.so+0x71e7a9c [0xf5425a9c]
#216 HYBRIS operator new(unsigned int)+39 in libminecraftpe.so+0x54413a7 [0xf367f3a7]
#219 HYBRIS xbox::services::serviceLocales+0 in libminecraftpe.so+0x72a4250 [0xf54e2250]
#221 HYBRIS std::unordered_map<std::string, std::string, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, std::string> > >::~unordered_map()+0 in libminecraftpe.so+0xc399f0 [0xeee779f0]
#222 HYBRIS (null)+-179314568 in libminecraftpe.so+0x72c0078 [0xf54fe078]
#223 HYBRIS xbox::services::serviceLocales+0 in libminecraftpe.so+0x72a4250 [0xf54e2250]
#230 HYBRIS (null)+-180200804 in libminecraftpe.so+0x71e7a9c [0xf5425a9c]
#233 HYBRIS std::unordered_map<std::string, std::string, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, std::string> > >::~unordered_map()+0 in libminecraftpe.so+0xc399f0 [0xeee779f0]
#234 HYBRIS xbox::services::serviceLocales+0 in libminecraftpe.so+0x72a4250 [0xf54e2250]
#235 HYBRIS (null)+-180092928 in libminecraftpe.so+0x7202000 [0xf5440000]
#240 HYBRIS (null)+-290458924 in libminecraftpe.so+0x8c12d4 [0xeeaff2d4]
#241 HYBRIS std::unordered_map<std::string, std::string, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, std::string> > >::~unordered_map()+0 in libminecraftpe.so+0xc399f0 [0xeee779f0]
#242 HYBRIS xbox::services::serviceLocales+0 in libminecraftpe.so+0x72a4250 [0xf54e2250]
#243 HYBRIS (null)+-180092928 in libminecraftpe.so+0x7202000 [0xf5440000]
#244 HYBRIS (null)+-290463761 in libminecraftpe.so+0x8bffef [0xeeafdfef]
#511 HYBRIS vtable for xbox::services::local_config+8 in libminecraftpe.so+0x71abfb0 [0xf53e9fb0]
#785 HYBRIS (null)+-290596168 in libminecraftpe.so+0x89fab8 [0xeeaddab8]
Process exited with unexpected exit code: 6

**Comment by Mhowser** [comment]
1.13.0 is unsupported due to lack of debugging symbols. Possibly future
releases as well.

**Comment by Planetworks** [comment]
> 1.13.0 is unsupported due to lack of debugging symbols. Possibly future releases as well.

1.13.0.6 works just fine though
this is a wild guess, but could it instead be an issue with the dragon rendering engine? I seem to recall that was implemented in 1.13.0.13
