### ISSUE TITLE
Is there a way I could use this to run other APKs?

### ISSUE THREAD

**Issue by CobreDev** [minecraft-linux/mcpelauncher-manifest#157]
Not really an issue, but I couldn't find anywhere to contact you. I would like to be able to run other Android apps on my Mac, but I'm not really sure how to go about doing this. Would someone be able to help me? Thanks!

**Comment by ChristopherHX** [comment]
No without much additional work, like rewritting the whole java UI and code. Only limited native libraries can be loaded by this launcher.
