### ISSUE TITLE
1.13.0.15 Not working

### ISSUE THREAD

**Issue by XPool17** [minecraft-linux/mcpelauncher-manifest#158]
So I recently signed up for the 1.13 beta, and 1.13.0.6 runs well, but the latest one (1.13.0.15) Crashes before it can start.

Here's the Game Log:
13:26:30 Info  [Launcher] Version: client a48cb4c / manifest d9cc8d9
13:26:30 Info  [Launcher] CPU: GenuineIntel Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz
13:26:30 Info  [Launcher] CPU supports SSSE3: YES
13:26:30 Trace [Launcher] Loading hybris libraries
13:26:30 Trace [HybrisUtils] Loaded OS library /Applications/Minecraft Bedrock Launcher.app/Contents/Resources/mcpelauncher/libs/native/libfmod.dylib
13:26:30 Trace [HybrisUtils] Loaded OS library libm.dylib
13:26:30 Error [HybrisUtils] Failed to load OS library libz.so.1
13:26:30 Trace [Launcher] Loading Minecraft library
13:26:30 Info  [Launcher] Loaded Minecraft library
13:26:30 Debug [Launcher] Minecraft is at offset 0x2b5a000
13:26:30 Error [MinecraftSymbols] Unresolved symbol: _ZN3App4initER10AppContext
13:26:30 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App4quitERKSsS1_
13:26:30 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App6updateEv
13:26:30 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App16setRenderingSizeEii
13:26:30 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App17setUISizeAndScaleEiif
13:26:30 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App10wantToQuitEv
13:26:30 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServiceLocatorI11AppPlatformE15mDefaultServiceE
13:26:30 Error [MinecraftSymbols] Unresolved symbol: _ZNK11AppPlatform22getHardwareInformationEv
13:26:30 Error [MinecraftSymbols] Unresolved symbol: _ZN17AppResourceLoaderC2ESt8functionIFSsvEE
13:26:30 Error [MinecraftSymbols] Unresolved symbol: _ZN10Automation16AutomationClientC2ER13IMinecraftApp
13:26:30 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance7getUserEv
13:26:30 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance15_startLeaveGameEv
13:26:30 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance16_syncDestroyGameEv
13:26:30 Error [MinecraftSymbols] Unresolved symbol: _ZNK13CommandOutput11getMessagesEv
13:26:30 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender9translateERKSt6vectorISsSaISsEE
13:26:30 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSenderC2ERN10Automation16AutomationClientE
13:26:30 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSenderD2Ev
13:26:30 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender4sendERK13CommandOriginRK13CommandOutput
13:26:30 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender22registerOutputCallbackERKSt8functionIFvR19AutomationCmdOutputEE
13:26:30 Error [MinecraftSymbols] Unresolved symbol: _ZN6Common23getGameVersionStringNetEv
13:26:30 Error [MinecraftSymbols] Unresolved symbol: _ZN30ExternalFileLevelStorageSourceC2EP15FilePathManagerSt10shared_ptrI22SaveTransactionManagerE
13:26:30 Error [MinecraftSymbols] Unresolved symbol: _ZN30ExternalFileLevelStorageSource18createLevelStorageER9SchedulerRKSsRK15ContentIdentityRK19IContentKeyProvider
13:26:30 Error [MinecraftSymbols] Unresolved symbol: _ZN15FilePathManagerC2ESsb
13:26:30 Error [MinecraftSymbols] Unresolved symbol: _ZNK15FilePathManager11getRootPathEv
13:26:30 Error [MinecraftSymbols] Unresolved symbol: _ZNK15FilePathManager15getUserDataPathEv
13:26:30 Error [MinecraftSymbols] Unresolved symbol: _ZNK15FilePathManager13getWorldsPathEv
13:26:30 Error [MinecraftSymbols] Unresolved symbol: _ZN15FilePathManager14setPackagePathESs
13:26:30 Error [MinecraftSymbols] Unresolved symbol: _ZNK15FilePathManager14getPackagePathEv
13:26:30 Error [MinecraftSymbols] Unresolved symbol: _ZN15FilePathManager15setSettingsPathESs
13:26:30 Error [MinecraftSymbols] Unresolved symbol: _ZNK15FilePathManager15getSettingsPathEv
13:26:30 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourceLoadManagerC2Ev
13:26:30 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourceLoadManager4syncE16ResourceLoadType
13:26:30 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n3getERKSsRKSt6vectorISsSaISsEE
13:26:30 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n14chooseLanguageERKSs
13:26:30 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n13loadLanguagesER19ResourcePackManagerR19ResourceLoadManagerRKSs
13:26:30 Error [MinecraftSymbols] Unresolved symbol: _ZN5Level16createRandomSeedEv
13:26:30 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettingsC2Ev
13:26:30 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettingsC2ERKS_
13:26:30 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettings15parseSeedStringERKSsj
13:26:30 Error [MinecraftSymbols] Unresolved symbol: _ZN9Minecraft11getCommandsEv
13:26:30 Error [MinecraftSymbols] Unresolved symbol: _ZNK9Minecraft8getLevelEv
13:26:30 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftCommands15setOutputSenderESt10unique_ptrI19CommandOutputSenderSt14default_deleteIS1_EE
13:26:30 Error [MinecraftSymbols] Unresolved symbol: _ZNK17MinecraftCommands23requestCommandExecutionESt10unique_ptrI13CommandOriginSt14default_deleteIS1_EERKSsib
13:26:30 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftEventingC2ERKSs
13:26:30 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftEventing4initEv
13:26:30 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGameC2EiPPc
13:26:30 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGameD2Ev
13:26:30 Error [MinecraftSymbols] Unresolved symbol: _ZNK13MinecraftGame8isInGameEv
13:26:30 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame16requestLeaveGameEbb
13:26:30 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame24doPrimaryClientReadyWorkESt8functionIFvvEE
13:26:30 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame21getPrimaryUserOptionsEv
13:26:30 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame24getPrimaryClientInstanceEv
13:26:30 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame14startLeaveGameEv
13:26:30 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame17continueLeaveGameEv
13:26:30 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame14setTextboxTextERKSsi
13:26:30 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel32navigateToXblConsoleSignInScreenERKSsS1_
13:26:30 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel41navigateToXblConsoleSignInSucceededScreenERKN6Social12SignInResultESt8functionIFvS1_EEb
13:26:30 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel11leaveScreenEv
13:26:30 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social14MultiplayerXBLC2Ev
13:26:30 Error [MinecraftSymbols] Unresolved symbol: _ZTV22NullTextToSpeechClient
13:26:30 Error [MinecraftSymbols] Unresolved symbol: _ZNK7Options13getFullscreenEv
13:26:30 Error [MinecraftSymbols] Unresolved symbol: _ZN7Options13setFullscreenEb
13:26:30 Error [MinecraftSymbols] Unresolved symbol: _ZN15PermissionsFileC2ERKSs
13:26:30 Error [MinecraftSymbols] Unresolved symbol: _ZN19SkinPackKeyProviderC2Ev
13:26:30 Error [MinecraftSymbols] Unresolved symbol: _ZN19PackManifestFactoryC2ER14IPackTelemetry
13:26:30 Error [MinecraftSymbols] Unresolved symbol: _ZN17PackSourceFactoryC2EP7Options
13:26:30 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepositoryC2ER18IMinecraftEventingR19PackManifestFactoryR29IContentAccessibilityProviderP15FilePathManagerR17PackSourceFactoryb
13:26:30 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepository21addWorldResourcePacksERKSs
13:26:30 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepository12refreshPacksEv
13:26:30 Error [MinecraftSymbols] Unresolved symbol: _ZN18ContentTierManagerC2Ev
13:26:30 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManagerC2ESt8functionIFSsvEERK18ContentTierManagerb
13:26:30 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManager8setStackESt10unique_ptrI17ResourcePackStackSt14default_deleteIS1_EE21ResourcePackStackTypeb
13:26:30 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManager17onLanguageChangedEv
13:26:30 Error [MinecraftSymbols] Unresolved symbol: _ZN12PackInstanceC2EP12ResourcePackibP12PackSettings
13:26:30 Error [MinecraftSymbols] Unresolved symbol: _ZTV17ResourcePackStack
13:26:30 Error [MinecraftSymbols] Unresolved symbol: _ZN17ResourcePackStack3addE12PackInstanceRK22ResourcePackRepositoryb
13:26:30 Error [MinecraftSymbols] Unresolved symbol: _ZN22SaveTransactionManagerC2ESt8functionIFvbEE
13:26:30 Error [MinecraftSymbols] Unresolved symbol: _ZN9Scheduler17processCoroutinesENSt6chrono8durationIxSt5ratioILx1ELx1000000000EEEE
13:26:30 Error [MinecraftSymbols] Unresolved symbol: _ZN18MinecraftScheduler6clientEv
13:26:30 Error [MinecraftSymbols] Unresolved symbol: _ZN19ServerCommandOriginC2ERKSsR11ServerLevel
13:26:30 Error [MinecraftSymbols] Unresolved symbol: _ZN16EducationOptionsC2EP19ResourcePackManager
13:26:30 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstanceC2ER13IMinecraftAppR30ServerInstanceEventCoordinator
13:26:30 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance16initializeServerER13IMinecraftAppR9WhitelistP15PermissionsFileP15FilePathManagerNSt6chrono8durationIxSt5ratioILx1ELx1EEEESsSsSs13LevelSettingsib20ConnectionDefinitionbRKSt6vectorISsSaISsEESsRKN3mce4UUIDER18IMinecraftEventingR22ResourcePackRepositoryRK18ContentTierManagerR19ResourcePackManagerSt8functionIFSt10unique_ptrI12LevelStorageSt14default_deleteISZ_EER9SchedulerEERKSsP9LevelDataSsSsSY_I16EducationOptionsS10_IS1B_EEPSV_SX_IFvS18_EES1G_P13ServerMetricsP13DebugEndPoint
13:26:30 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstanceD2Ev
13:26:30 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance17startServerThreadEv
13:26:30 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance13leaveGameSyncEv
13:26:30 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance20queueForServerThreadESt8functionIFvvEE
13:26:30 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12MajorVersionE
13:26:30 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12MinorVersionE
13:26:30 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12PatchVersionE
13:26:30 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants15RevisionVersionE
13:26:30 Error [MinecraftSymbols] Unresolved symbol: _ZNK6Social4User11getLiveUserEv
13:26:30 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social12XboxLiveUser22_handleUISignInNoErrorERN4xbox8services6system14sign_in_resultESt8functionIFvNS_12SignInResultEbEE
13:26:30 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN9GameStore18onStoreInitializedEb
13:26:30 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN9GameStore22onQueryProductsSuccessERKSt6vectorI11ProductInfoSaIS1_EE
13:26:30 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social11UserManager17CreateUserManagerEv
13:26:30 Error [MinecraftSymbols] Unresolved symbol: _ZN2v82V810InitializeEv
13:26:30 Error [MinecraftSymbols] Unresolved symbol: _ZN2v82V818InitializePlatformEPNS_8PlatformE
13:26:30 Error [MinecraftSymbols] Unresolved symbol: _ZNK4pplx4taskIN4xbox8services16xbox_live_resultINS2_6system26token_and_signature_resultEEEE3getEv
13:26:30 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl15getOpenGLVendorEv
13:26:30 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl17getOpenGLRendererEv
13:26:30 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl16getOpenGLVersionEv
13:26:30 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl19getOpenGLExtensionsEv
13:26:30 Error [MinecraftSymbols] Unresolved symbol: _ZN3mce8Platform3OGL12InitBindingsEv
Signal 11 received
Backtrace elements: 5
#0 0   mcpelauncher-client                 0x001b4f2e _ZN12CrashHandler12handleSignalEiPv + 318
#1 1   libsystem_platform.dylib            0xa756f02b _sigtramp + 43
#2 2   ???                                 0xffffffff 0x0 + 4294967295
#3 3   mcpelauncher-client                 0x000fb244 main + 10532
#4 4   libdyld.dylib                       0xa7266611 start + 1
Dumping stack...
#283 HYBRIS (null)+45457408 in libminecraftpe.so+0x0000 [0x2b5a000]
#327 HYBRIS (null)+45457408 in libminecraftpe.so+0x0000 [0x2b5a000]
Process exited with unexpected exit code: 6

**Comment by ChristopherHX** [comment]
@XPool17 
The new versions after 1.13.0.6 lacks critical binary Symbols and are **unsupported**

**Comment by VoxelDraqon** [comment]
> The new versions after 1.13.0.6 lacks critical binary Symbols and are **unsupported**

Is it possible new versions will be supported in the future, or is the situation too far gone?

**Comment by ChristopherHX** [comment]
Maybe there will be a symbolless Version some day, but probably without
- Xbox live services
- armv7 / x86 dedicated Server support (only official x64 ubuntu version)

Maybe the x64 official ubuntu dedicated server will run on macos like the android one now.
My attempt was trying to simulate Java Native Interface and using the android native interface to comunicate with Minecraft (this isn't currently working at all)

**Comment by wiktorpp** [comment]
Ok, so what should I do if I don't have an older version of the apk?

**Comment by ChristopherHX** [comment]
Yust select another version from the launcher, 
if you not using the qt launcher I havn't any ideas
Edit Profile (Current, bottom left gear)
- select Version 1.12.1.1 from dropdown

**Comment by MattPark** [comment]
Now says outdated client when running 1.13.6...

**Comment by Mhowser** [comment]
Thank you for the crash report, We are consolidating all issues related to 1.13+ crashes to #165
