### ISSUE TITLE
1.13.0.18 not working

### ISSUE THREAD

**Issue by ItsSapphire** [minecraft-linux/mcpelauncher-manifest#159]
When I try launching version 1.13.0.18, I get this error;
`16:55:26 Info  [Launcher] Version: client a48cb4c / manifest d9cc8d9
16:55:26 Info  [Launcher] CPU: AuthenticAMD AMD A6-9225 RADEON R4, 5 COMPUTE CORES 2C+3G   
16:55:26 Info  [Launcher] CPU supports SSSE3: YES
16:55:26 Trace [Launcher] Loading hybris libraries
16:55:26 Trace [HybrisUtils] Loaded OS library /usr/share//mcpelauncher/libs/native/libfmod.so.9.16
16:55:26 Trace [HybrisUtils] Loaded OS library libm.so.6
16:55:26 Trace [HybrisUtils] Loaded OS library libz.so.1
16:55:26 Trace [Launcher] Loading Minecraft library
16:55:27 Info  [Launcher] Loaded Minecraft library
16:55:27 Debug [Launcher] Minecraft is at offset 0xe7ed0000
16:55:27 Error [MinecraftSymbols] Unresolved symbol: _ZN3App4initER10AppContext
16:55:27 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App4quitERKSsS1_
16:55:27 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App6updateEv
16:55:27 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App16setRenderingSizeEii
16:55:27 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App17setUISizeAndScaleEiif
16:55:27 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App10wantToQuitEv
16:55:27 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServiceLocatorI11AppPlatformE15mDefaultServiceE
16:55:27 Error [MinecraftSymbols] Unresolved symbol: _ZNK11AppPlatform22getHardwareInformationEv
16:55:27 Error [MinecraftSymbols] Unresolved symbol: _ZN17AppResourceLoaderC2ESt8functionIFSsvEE
16:55:27 Error [MinecraftSymbols] Unresolved symbol: _ZN10Automation16AutomationClientC2ER13IMinecraftApp
16:55:27 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance7getUserEv
16:55:27 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance15_startLeaveGameEv
16:55:27 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance16_syncDestroyGameEv
16:55:27 Error [MinecraftSymbols] Unresolved symbol: _ZNK13CommandOutput11getMessagesEv
16:55:27 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender9translateERKSt6vectorISsSaISsEE
16:55:27 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSenderC2ERN10Automation16AutomationClientE
16:55:27 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSenderD2Ev
16:55:27 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender4sendERK13CommandOriginRK13CommandOutput
16:55:27 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender22registerOutputCallbackERKSt8functionIFvR19AutomationCmdOutputEE
16:55:27 Error [MinecraftSymbols] Unresolved symbol: _ZN6Common23getGameVersionStringNetEv
16:55:27 Error [MinecraftSymbols] Unresolved symbol: _ZN30ExternalFileLevelStorageSourceC2EP15FilePathManagerSt10shared_ptrI22SaveTransactionManagerE
16:55:27 Error [MinecraftSymbols] Unresolved symbol: _ZN30ExternalFileLevelStorageSource18createLevelStorageER9SchedulerRKSsRK15ContentIdentityRK19IContentKeyProvider
16:55:27 Error [MinecraftSymbols] Unresolved symbol: _ZN15FilePathManagerC2ESsb
16:55:27 Error [MinecraftSymbols] Unresolved symbol: _ZNK15FilePathManager11getRootPathEv
16:55:27 Error [MinecraftSymbols] Unresolved symbol: _ZNK15FilePathManager15getUserDataPathEv
16:55:27 Error [MinecraftSymbols] Unresolved symbol: _ZNK15FilePathManager13getWorldsPathEv
16:55:27 Error [MinecraftSymbols] Unresolved symbol: _ZN15FilePathManager14setPackagePathESs
16:55:27 Error [MinecraftSymbols] Unresolved symbol: _ZNK15FilePathManager14getPackagePathEv
16:55:27 Error [MinecraftSymbols] Unresolved symbol: _ZN15FilePathManager15setSettingsPathESs
16:55:27 Error [MinecraftSymbols] Unresolved symbol: _ZNK15FilePathManager15getSettingsPathEv
16:55:27 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourceLoadManagerC2Ev
16:55:27 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourceLoadManager4syncE16ResourceLoadType
16:55:27 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n3getERKSsRKSt6vectorISsSaISsEE
16:55:27 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n14chooseLanguageERKSs
16:55:27 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n13loadLanguagesER19ResourcePackManagerR19ResourceLoadManagerRKSs
16:55:27 Error [MinecraftSymbols] Unresolved symbol: _ZN5Level16createRandomSeedEv
16:55:27 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettingsC2Ev
16:55:27 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettingsC2ERKS_
16:55:27 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettings15parseSeedStringERKSsj
16:55:27 Error [MinecraftSymbols] Unresolved symbol: _ZN9Minecraft11getCommandsEv
16:55:27 Error [MinecraftSymbols] Unresolved symbol: _ZNK9Minecraft8getLevelEv
16:55:27 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftCommands15setOutputSenderESt10unique_ptrI19CommandOutputSenderSt14default_deleteIS1_EE
16:55:27 Error [MinecraftSymbols] Unresolved symbol: _ZNK17MinecraftCommands23requestCommandExecutionESt10unique_ptrI13CommandOriginSt14default_deleteIS1_EERKSsib
16:55:27 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftEventingC2ERKSs
16:55:27 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftEventing4initEv
16:55:27 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGameC2EiPPc
16:55:27 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGameD2Ev
16:55:27 Error [MinecraftSymbols] Unresolved symbol: _ZNK13MinecraftGame8isInGameEv
16:55:27 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame16requestLeaveGameEbb
16:55:27 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame24doPrimaryClientReadyWorkESt8functionIFvvEE
16:55:27 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame21getPrimaryUserOptionsEv
16:55:27 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame24getPrimaryClientInstanceEv
16:55:27 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame14startLeaveGameEv
16:55:27 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame17continueLeaveGameEv
16:55:27 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame14setTextboxTextERKSsi
16:55:27 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel32navigateToXblConsoleSignInScreenERKSsS1_
16:55:27 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel41navigateToXblConsoleSignInSucceededScreenERKN6Social12SignInResultESt8functionIFvS1_EEb
16:55:27 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel11leaveScreenEv
16:55:27 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social14MultiplayerXBLC2Ev
16:55:27 Error [MinecraftSymbols] Unresolved symbol: _ZTV22NullTextToSpeechClient
16:55:27 Error [MinecraftSymbols] Unresolved symbol: _ZNK7Options13getFullscreenEv
16:55:27 Error [MinecraftSymbols] Unresolved symbol: _ZN7Options13setFullscreenEb
16:55:27 Error [MinecraftSymbols] Unresolved symbol: _ZN15PermissionsFileC2ERKSs
16:55:27 Error [MinecraftSymbols] Unresolved symbol: _ZN19SkinPackKeyProviderC2Ev
16:55:27 Error [MinecraftSymbols] Unresolved symbol: _ZN19PackManifestFactoryC2ER14IPackTelemetry
16:55:27 Error [MinecraftSymbols] Unresolved symbol: _ZN17PackSourceFactoryC2EP7Options
16:55:27 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepositoryC2ER18IMinecraftEventingR19PackManifestFactoryR29IContentAccessibilityProviderP15FilePathManagerR17PackSourceFactoryb
16:55:27 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepository21addWorldResourcePacksERKSs
16:55:27 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepository12refreshPacksEv
16:55:27 Error [MinecraftSymbols] Unresolved symbol: _ZN18ContentTierManagerC2Ev
16:55:27 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManagerC2ESt8functionIFSsvEERK18ContentTierManagerb
16:55:27 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManager8setStackESt10unique_ptrI17ResourcePackStackSt14default_deleteIS1_EE21ResourcePackStackTypeb
16:55:27 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManager17onLanguageChangedEv
16:55:27 Error [MinecraftSymbols] Unresolved symbol: _ZN12PackInstanceC2EP12ResourcePackibP12PackSettings
16:55:27 Error [MinecraftSymbols] Unresolved symbol: _ZTV17ResourcePackStack
16:55:27 Error [MinecraftSymbols] Unresolved symbol: _ZN17ResourcePackStack3addE12PackInstanceRK22ResourcePackRepositoryb
16:55:27 Error [MinecraftSymbols] Unresolved symbol: _ZN22SaveTransactionManagerC2ESt8functionIFvbEE
16:55:27 Error [MinecraftSymbols] Unresolved symbol: _ZN9Scheduler17processCoroutinesENSt6chrono8durationIxSt5ratioILx1ELx1000000000EEEE
16:55:27 Error [MinecraftSymbols] Unresolved symbol: _ZN18MinecraftScheduler6clientEv
16:55:27 Error [MinecraftSymbols] Unresolved symbol: _ZN19ServerCommandOriginC2ERKSsR11ServerLevel
16:55:27 Error [MinecraftSymbols] Unresolved symbol: _ZN16EducationOptionsC2EP19ResourcePackManager
16:55:27 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstanceC2ER13IMinecraftAppR30ServerInstanceEventCoordinator
16:55:27 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance16initializeServerER13IMinecraftAppR9WhitelistP15PermissionsFileP15FilePathManagerNSt6chrono8durationIxSt5ratioILx1ELx1EEEESsSsSs13LevelSettingsib20ConnectionDefinitionbRKSt6vectorISsSaISsEESsRKN3mce4UUIDER18IMinecraftEventingR22ResourcePackRepositoryRK18ContentTierManagerR19ResourcePackManagerSt8functionIFSt10unique_ptrI12LevelStorageSt14default_deleteISZ_EER9SchedulerEERKSsP9LevelDataSsSsSY_I16EducationOptionsS10_IS1B_EEPSV_SX_IFvS18_EES1G_P13ServerMetricsP13DebugEndPoint
16:55:27 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstanceD2Ev
16:55:27 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance17startServerThreadEv
16:55:27 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance13leaveGameSyncEv
16:55:27 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance20queueForServerThreadESt8functionIFvvEE
16:55:27 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12MajorVersionE
16:55:27 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12MinorVersionE
16:55:27 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12PatchVersionE
16:55:27 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants15RevisionVersionE
16:55:27 Error [MinecraftSymbols] Unresolved symbol: _ZNK6Social4User11getLiveUserEv
16:55:27 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social12XboxLiveUser22_handleUISignInNoErrorERN4xbox8services6system14sign_in_resultESt8functionIFvNS_12SignInResultEbEE
16:55:27 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN9GameStore18onStoreInitializedEb
16:55:27 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN9GameStore22onQueryProductsSuccessERKSt6vectorI11ProductInfoSaIS1_EE
16:55:27 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social11UserManager17CreateUserManagerEv
16:55:27 Error [MinecraftSymbols] Unresolved symbol: _ZN2v82V810InitializeEv
16:55:27 Error [MinecraftSymbols] Unresolved symbol: _ZN2v82V818InitializePlatformEPNS_8PlatformE
16:55:27 Error [MinecraftSymbols] Unresolved symbol: _ZNK4pplx4taskIN4xbox8services16xbox_live_resultINS2_6system26token_and_signature_resultEEEE3getEv
16:55:27 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl15getOpenGLVendorEv
16:55:27 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl17getOpenGLRendererEv
16:55:27 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl16getOpenGLVersionEv
16:55:27 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl19getOpenGLExtensionsEv
16:55:27 Error [MinecraftSymbols] Unresolved symbol: _ZN3mce8Platform3OGL12InitBindingsEv
Signal 11 received
Backtrace elements: 2
#0 /usr/bin/mcpelauncher-client(_ZN12CrashHandler12handleSignalEiPv+0xc5) [0x567f920f]
#1 linux-gate.so.1(__kernel_sigreturn+0) [0xf7fbebf0]
Dumping stack...
#1 HYBRIS (null)+-314617860 in libminecraftpe.so+0x5524ffc [0xed3f4ffc]
#2 HYBRIS (null)+-314618111 in libminecraftpe.so+0x5524f01 [0xed3f4f01]
#13 HYBRIS (null)+-403898368 in libminecraftpe.so+0x0000 [0xe7ed0000]
#19 HYBRIS (null)+-314617860 in libminecraftpe.so+0x5524ffc [0xed3f4ffc]
#20 HYBRIS (null)+-314618111 in libminecraftpe.so+0x5524f01 [0xed3f4f01]
#22 HYBRIS (null)+-314617860 in libminecraftpe.so+0x5524ffc [0xed3f4ffc]
#23 HYBRIS (null)+-314618111 in libminecraftpe.so+0x5524f01 [0xed3f4f01]
#25 HYBRIS (null)+-314617860 in libminecraftpe.so+0x5524ffc [0xed3f4ffc]
#26 HYBRIS (null)+-314618111 in libminecraftpe.so+0x5524f01 [0xed3f4f01]
#28 HYBRIS (null)+-314617860 in libminecraftpe.so+0x5524ffc [0xed3f4ffc]
#29 HYBRIS (null)+-314618111 in libminecraftpe.so+0x5524f01 [0xed3f4f01]
#31 HYBRIS (null)+-314617860 in libminecraftpe.so+0x5524ffc [0xed3f4ffc]
#32 HYBRIS (null)+-314618111 in libminecraftpe.so+0x5524f01 [0xed3f4f01]
#34 HYBRIS (null)+-314617860 in libminecraftpe.so+0x5524ffc [0xed3f4ffc]
#35 HYBRIS (null)+-314618111 in libminecraftpe.so+0x5524f01 [0xed3f4f01]
#37 HYBRIS (null)+-314617860 in libminecraftpe.so+0x5524ffc [0xed3f4ffc]
#38 HYBRIS (null)+-314618111 in libminecraftpe.so+0x5524f01 [0xed3f4f01]
#40 HYBRIS (null)+-314617860 in libminecraftpe.so+0x5524ffc [0xed3f4ffc]
#112 HYBRIS std::pair<std::__detail::_Node_iterator<std::pair<unsigned char const, std::string>, false, false>, bool> std::_Hashtable<unsigned char, std::pair<unsigned char const, std::string>, std::allocator<std::pair<unsigned char const, std::string> >, std::__detail::_Select1st, std::equal_to<unsigned char>, std::hash<unsigned char>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true> >::_M_insert<std::pair<unsigned char const, std::string> const&, std::__detail::_AllocNode<std::allocator<std::__detail::_Hash_node<std::pair<unsigned char const, std::string>, false> > > >(std::pair<unsigned char const, std::string> const&, std::__detail::_AllocNode<std::allocator<std::__detail::_Hash_node<std::pair<unsigned char const, std::string>, false> > > const&, std::integral_constant<bool, true>)+12 in libminecraftpe.so+0x3cfec9c [0xebbcec9c]
#113 HYBRIS operator new(unsigned int)+12 in libminecraftpe.so+0x54ab74c [0xed37b74c]
#115 HYBRIS (null)+-283809160 in libminecraftpe.so+0x7286a78 [0xef156a78]
#117 HYBRIS std::unordered_map<unsigned char, std::string, std::hash<unsigned char>, std::equal_to<unsigned char>, std::allocator<std::pair<unsigned char const, std::string> > >::~unordered_map()+0 in libminecraftpe.so+0x3cfbe50 [0xebbcbe50]
#118 HYBRIS (null)+-283039560 in libminecraftpe.so+0x73428b8 [0xef2128b8]
#119 HYBRIS (null)+-283701248 in libminecraftpe.so+0x72a1000 [0xef171000]
#122 HYBRIS (null)+-283809160 in libminecraftpe.so+0x7286a78 [0xef156a78]
#124 HYBRIS (null)+-394745112 in libminecraftpe.so+0x8baae8 [0xe878aae8]
#125 HYBRIS std::unordered_map<unsigned char, std::string, std::hash<unsigned char>, std::equal_to<unsigned char>, std::allocator<std::pair<unsigned char const, std::string> > >::~unordered_map()+0 in libminecraftpe.so+0x3cfbe50 [0xebbcbe50]
#126 HYBRIS (null)+-283039560 in libminecraftpe.so+0x73428b8 [0xef2128b8]
#127 HYBRIS (null)+-283701248 in libminecraftpe.so+0x72a1000 [0xef171000]
#157 HYBRIS (null)+-343778166 in libminecraftpe.so+0x3955c8a [0xeb825c8a]
#167 HYBRIS (null)+-343756657 in libminecraftpe.so+0x395b08f [0xeb82b08f]
#171 HYBRIS (null)+-314784821 in libminecraftpe.so+0x54fc3cb [0xed3cc3cb]
#178 HYBRIS xbox::services::serviceLocales+16 in libminecraftpe.so+0x7343b00 [0xef213b00]
#214 HYBRIS (null)+-283809160 in libminecraftpe.so+0x7286a78 [0xef156a78]
#224 HYBRIS operator new(unsigned int)+39 in libminecraftpe.so+0x54ab767 [0xed37b767]
#230 HYBRIS (null)+-282920648 in libminecraftpe.so+0x735f938 [0xef22f938]
#231 HYBRIS xbox::services::serviceLocales+0 in libminecraftpe.so+0x7343af0 [0xef213af0]
#239 HYBRIS (null)+-283809160 in libminecraftpe.so+0x7286a78 [0xef156a78]
#241 HYBRIS std::unordered_map<std::string, std::string, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, std::string> > >::~unordered_map()+0 in libminecraftpe.so+0xc3f290 [0xe8b0f290]
#242 HYBRIS xbox::services::serviceLocales+0 in libminecraftpe.so+0x7343af0 [0xef213af0]
#243 HYBRIS (null)+-283701248 in libminecraftpe.so+0x72a1000 [0xef171000]
#248 HYBRIS (null)+-394705612 in libminecraftpe.so+0x8c4534 [0xe8794534]
#249 HYBRIS std::unordered_map<std::string, std::string, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, std::string> > >::~unordered_map()+0 in libminecraftpe.so+0xc3f290 [0xe8b0f290]
#250 HYBRIS xbox::services::serviceLocales+0 in libminecraftpe.so+0x7343af0 [0xef213af0]
#251 HYBRIS (null)+-283701248 in libminecraftpe.so+0x72a1000 [0xef171000]
#252 HYBRIS (null)+-394710449 in libminecraftpe.so+0x8c324f [0xe879324f]
#519 HYBRIS vtable for xbox::services::local_config+8 in libminecraftpe.so+0x724afa0 [0xef11afa0]
Process exited with unexpected exit code: 6`
Can someone help with this issue?

**Comment by Logos-Coder** [comment]
I had the same issue, but according to this it will be awhile (if at all) before it works again.

> @XPool17 
> The new versions after 1.13.0.6 lacks critical binary Symbols and are **unsupported**

_Originally posted by @ChristopherHX in https://github.com/minecraft-linux/mcpelauncher-manifest/issues/158#issuecomment-536339084_

**Comment by Mhowser** [comment]
Thank you for the crash report, We are consolidating all issues related to 1.13+ crashes to #165
