### ISSUE TITLE
Add server 1.12 support

### ISSUE THREAD

**Issue by haveyouwantto** [minecraft-linux/mcpelauncher-manifest#160]

**Comment by ChristopherHX** [comment]
More details please,
I'm unable to force this repo to update,
but the initial x86 support of 1.12.x is merged in fully in master of
[minecraft-symbols](https://github.com/minecraft-linux/minecraft-symbols) and [mcpelauncher-server](https://github.com/minecraft-linux/mcpelauncher-server)
just type in the cloned folder
`cd minecraft-symbols`
`git checkout master`
`cd ../mcpelauncher-server`
`git checkout master`
It has probably minor issues with custom world resourcepacks,
Build the server again, please be patient...

PS for ubuntu x64 you can download an [offical dedicated server](https://www.minecraft.net/de-de/download/server/bedrock/)

**Comment by MCMrARM** [comment]
I'll merge it into the manifest soon.

**Comment by ChristopherHX** [comment]
Its solved now at least for x86
