### ISSUE TITLE
Error While Loading Shared Libraries (1.12.1.1)

### ISSUE THREAD

**Issue by ThisNekoGuy** [minecraft-linux/mcpelauncher-manifest#161]
![minecraft_error](https://user-images.githubusercontent.com/28468662/66619795-d0fdc780-eba3-11e9-9b2e-ccdb9d709546.png)
![Installed](https://user-images.githubusercontent.com/28468662/66619863-0e625500-eba4-11e9-9c7c-3d5bc3b470b8.png)

I have installed the component that it's giving an error about?
Not sure what went wrong here...

**Comment by LuthfiDoesCode** [comment]
what's the solution? Have you found it?

**Comment by ThisNekoGuy** [comment]
> what's the solution? Have you found it?

Yeah, I just missed a dependency during the installation.
I read MESA and assumed that because I have an Nvidia GPU that it must've not applied to me :p
I was evidently incorrect

**Comment by LuthfiDoesCode** [comment]
> > what's the solution? Have you found it?
> 
> Yeah, I just missed a dependency during the installation.
> I read MESA and assumed that because I have an Nvidia GPU that it must've not applied to me :p
> I was evidently incorrect

so uhh... how do you get the missing dependency?
