### ISSUE TITLE
MCPE 1.14.0.1 Beta

### ISSUE THREAD

**Issue by kenrcastillo** [minecraft-linux/mcpelauncher-manifest#163]
16:24:31 Info  [Launcher] Version: client a48cb4c / manifest d9cc8d9
16:24:31 Info  [Launcher] CPU: GenuineIntel Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz
16:24:31 Info  [Launcher] CPU supports SSSE3: YES
16:24:31 Trace [Launcher] Loading hybris libraries
16:24:31 Trace [HybrisUtils] Loaded OS library /usr/share/mcpelauncher/libs/native/libfmod.so.9.16
16:24:31 Trace [HybrisUtils] Loaded OS library libm.so.6
16:24:31 Trace [HybrisUtils] Loaded OS library libz.so.1
16:24:31 Trace [Launcher] Loading Minecraft library
16:24:31 Info  [Launcher] Loaded Minecraft library
16:24:31 Debug [Launcher] Minecraft is at offset 0xed927000
16:24:31 Error [MinecraftSymbols] Unresolved symbol: _ZN3App4initER10AppContext
16:24:31 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App4quitERKSsS1_
16:24:31 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App6updateEv
16:24:31 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App16setRenderingSizeEii
16:24:31 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App17setUISizeAndScaleEiif
16:24:31 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App10wantToQuitEv
16:24:31 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServiceLocatorI11AppPlatformE15mDefaultServiceE
16:24:31 Error [MinecraftSymbols] Unresolved symbol: _ZNK11AppPlatform22getHardwareInformationEv
16:24:31 Error [MinecraftSymbols] Unresolved symbol: _ZN17AppResourceLoaderC2ESt8functionIFSsvEE
16:24:31 Error [MinecraftSymbols] Unresolved symbol: _ZN10Automation16AutomationClientC2ER13IMinecraftApp
16:24:31 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance7getUserEv
16:24:31 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance15_startLeaveGameEv
16:24:31 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance16_syncDestroyGameEv
16:24:31 Error [MinecraftSymbols] Unresolved symbol: _ZNK13CommandOutput11getMessagesEv
16:24:31 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender9translateERKSt6vectorISsSaISsEE
16:24:31 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSenderC2ERN10Automation16AutomationClientE
16:24:31 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSenderD2Ev
16:24:31 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender4sendERK13CommandOriginRK13CommandOutput
16:24:31 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender22registerOutputCallbackERKSt8functionIFvR19AutomationCmdOutputEE
16:24:31 Error [MinecraftSymbols] Unresolved symbol: _ZN6Common23getGameVersionStringNetEv
16:24:31 Error [MinecraftSymbols] Unresolved symbol: _ZN30ExternalFileLevelStorageSourceC2EP15FilePathManagerSt10shared_ptrI22SaveTransactionManagerE
16:24:31 Error [MinecraftSymbols] Unresolved symbol: _ZN30ExternalFileLevelStorageSource18createLevelStorageER9SchedulerRKSsRK15ContentIdentityRK19IContentKeyProvider
16:24:31 Error [MinecraftSymbols] Unresolved symbol: _ZN15FilePathManagerC2ESsb
16:24:31 Error [MinecraftSymbols] Unresolved symbol: _ZNK15FilePathManager11getRootPathEv
16:24:31 Error [MinecraftSymbols] Unresolved symbol: _ZNK15FilePathManager15getUserDataPathEv
16:24:31 Error [MinecraftSymbols] Unresolved symbol: _ZNK15FilePathManager13getWorldsPathEv
16:24:31 Error [MinecraftSymbols] Unresolved symbol: _ZN15FilePathManager14setPackagePathESs
16:24:31 Error [MinecraftSymbols] Unresolved symbol: _ZNK15FilePathManager14getPackagePathEv
16:24:31 Error [MinecraftSymbols] Unresolved symbol: _ZN15FilePathManager15setSettingsPathESs
16:24:31 Error [MinecraftSymbols] Unresolved symbol: _ZNK15FilePathManager15getSettingsPathEv
16:24:31 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourceLoadManagerC2Ev
16:24:31 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourceLoadManager4syncE16ResourceLoadType
16:24:31 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n3getERKSsRKSt6vectorISsSaISsEE
16:24:31 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n14chooseLanguageERKSs
16:24:31 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n13loadLanguagesER19ResourcePackManagerR19ResourceLoadManagerRKSs
16:24:31 Error [MinecraftSymbols] Unresolved symbol: _ZN5Level16createRandomSeedEv
16:24:31 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettingsC2Ev
16:24:31 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettingsC2ERKS_
16:24:31 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettings15parseSeedStringERKSsj
16:24:31 Error [MinecraftSymbols] Unresolved symbol: _ZN9Minecraft11getCommandsEv
16:24:31 Error [MinecraftSymbols] Unresolved symbol: _ZNK9Minecraft8getLevelEv
16:24:31 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftCommands15setOutputSenderESt10unique_ptrI19CommandOutputSenderSt14default_deleteIS1_EE
16:24:31 Error [MinecraftSymbols] Unresolved symbol: _ZNK17MinecraftCommands23requestCommandExecutionESt10unique_ptrI13CommandOriginSt14default_deleteIS1_EERKSsib
16:24:31 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftEventingC2ERKSs
16:24:31 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftEventing4initEv
16:24:31 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGameC2EiPPc
16:24:31 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGameD2Ev
16:24:31 Error [MinecraftSymbols] Unresolved symbol: _ZNK13MinecraftGame8isInGameEv
16:24:31 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame16requestLeaveGameEbb
16:24:31 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame24doPrimaryClientReadyWorkESt8functionIFvvEE
16:24:31 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame21getPrimaryUserOptionsEv
16:24:31 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame24getPrimaryClientInstanceEv
16:24:31 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame14startLeaveGameEv
16:24:31 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame17continueLeaveGameEv
16:24:31 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame14setTextboxTextERKSsi
16:24:31 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel32navigateToXblConsoleSignInScreenERKSsS1_
16:24:31 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel41navigateToXblConsoleSignInSucceededScreenERKN6Social12SignInResultESt8functionIFvS1_EEb
16:24:31 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel11leaveScreenEv
16:24:31 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social14MultiplayerXBLC2Ev
16:24:31 Error [MinecraftSymbols] Unresolved symbol: _ZTV22NullTextToSpeechClient
16:24:31 Error [MinecraftSymbols] Unresolved symbol: _ZNK7Options13getFullscreenEv
16:24:31 Error [MinecraftSymbols] Unresolved symbol: _ZN7Options13setFullscreenEb
16:24:31 Error [MinecraftSymbols] Unresolved symbol: _ZN15PermissionsFileC2ERKSs
16:24:31 Error [MinecraftSymbols] Unresolved symbol: _ZN19SkinPackKeyProviderC2Ev
16:24:31 Error [MinecraftSymbols] Unresolved symbol: _ZN19PackManifestFactoryC2ER14IPackTelemetry
16:24:31 Error [MinecraftSymbols] Unresolved symbol: _ZN17PackSourceFactoryC2EP7Options
16:24:31 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepositoryC2ER18IMinecraftEventingR19PackManifestFactoryR29IContentAccessibilityProviderP15FilePathManagerR17PackSourceFactoryb
16:24:31 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepository21addWorldResourcePacksERKSs
16:24:31 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepository12refreshPacksEv
16:24:31 Error [MinecraftSymbols] Unresolved symbol: _ZN18ContentTierManagerC2Ev
16:24:31 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManagerC2ESt8functionIFSsvEERK18ContentTierManagerb
16:24:31 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManager8setStackESt10unique_ptrI17ResourcePackStackSt14default_deleteIS1_EE21ResourcePackStackTypeb
16:24:31 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManager17onLanguageChangedEv
16:24:31 Error [MinecraftSymbols] Unresolved symbol: _ZN12PackInstanceC2EP12ResourcePackibP12PackSettings
16:24:31 Error [MinecraftSymbols] Unresolved symbol: _ZTV17ResourcePackStack
16:24:31 Error [MinecraftSymbols] Unresolved symbol: _ZN17ResourcePackStack3addE12PackInstanceRK22ResourcePackRepositoryb
16:24:31 Error [MinecraftSymbols] Unresolved symbol: _ZN22SaveTransactionManagerC2ESt8functionIFvbEE
16:24:31 Error [MinecraftSymbols] Unresolved symbol: _ZN9Scheduler17processCoroutinesENSt6chrono8durationIxSt5ratioILx1ELx1000000000EEEE
16:24:31 Error [MinecraftSymbols] Unresolved symbol: _ZN18MinecraftScheduler6clientEv
16:24:31 Error [MinecraftSymbols] Unresolved symbol: _ZN19ServerCommandOriginC2ERKSsR11ServerLevel
16:24:31 Error [MinecraftSymbols] Unresolved symbol: _ZN16EducationOptionsC2EP19ResourcePackManager
16:24:31 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstanceC2ER13IMinecraftAppR30ServerInstanceEventCoordinator
16:24:31 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance16initializeServerER13IMinecraftAppR9WhitelistP15PermissionsFileP15FilePathManagerNSt6chrono8durationIxSt5ratioILx1ELx1EEEESsSsSs13LevelSettingsib20ConnectionDefinitionbRKSt6vectorISsSaISsEESsRKN3mce4UUIDER18IMinecraftEventingR22ResourcePackRepositoryRK18ContentTierManagerR19ResourcePackManagerSt8functionIFSt10unique_ptrI12LevelStorageSt14default_deleteISZ_EER9SchedulerEERKSsP9LevelDataSsSsSY_I16EducationOptionsS10_IS1B_EEPSV_SX_IFvS18_EES1G_P13ServerMetricsP13DebugEndPoint
16:24:31 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstanceD2Ev
16:24:31 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance17startServerThreadEv
16:24:31 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance13leaveGameSyncEv
16:24:31 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance20queueForServerThreadESt8functionIFvvEE
16:24:31 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12MajorVersionE
16:24:31 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12MinorVersionE
16:24:31 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12PatchVersionE
16:24:31 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants15RevisionVersionE
16:24:31 Error [MinecraftSymbols] Unresolved symbol: _ZNK6Social4User11getLiveUserEv
16:24:31 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social12XboxLiveUser22_handleUISignInNoErrorERN4xbox8services6system14sign_in_resultESt8functionIFvNS_12SignInResultEbEE
16:24:31 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN9GameStore18onStoreInitializedEb
16:24:31 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN9GameStore22onQueryProductsSuccessERKSt6vectorI11ProductInfoSaIS1_EE
16:24:31 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social11UserManager17CreateUserManagerEv
16:24:31 Error [MinecraftSymbols] Unresolved symbol: _ZN2v82V810InitializeEv
16:24:31 Error [MinecraftSymbols] Unresolved symbol: _ZN2v82V818InitializePlatformEPNS_8PlatformE
16:24:31 Error [MinecraftSymbols] Unresolved symbol: _ZNK4pplx4taskIN4xbox8services16xbox_live_resultINS2_6system26token_and_signature_resultEEEE3getEv
16:24:31 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl15getOpenGLVendorEv
16:24:31 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl17getOpenGLRendererEv
16:24:31 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl16getOpenGLVersionEv
16:24:31 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl19getOpenGLExtensionsEv
16:24:31 Error [MinecraftSymbols] Unresolved symbol: _ZN3mce8Platform3OGL12InitBindingsEv
Signal 11 received
Backtrace elements: 2
#0 /usr/bin/mcpelauncher-client(_ZN12CrashHandler12handleSignalEiPv+0xc5) [0x56868c77]
#1 linux-gate.so.1(__kernel_sigreturn+0) [0xf7fc8950]
Dumping stack...
#1 HYBRIS (null)+-219383972 in libminecraftpe.so+0x55a075c [0xf2ec775c]
#2 HYBRIS (null)+-219384063 in libminecraftpe.so+0x55a0701 [0xf2ec7701]
#13 HYBRIS (null)+-309170176 in libminecraftpe.so+0x0000 [0xed927000]
#19 HYBRIS (null)+-219383972 in libminecraftpe.so+0x55a075c [0xf2ec775c]
#20 HYBRIS (null)+-219384063 in libminecraftpe.so+0x55a0701 [0xf2ec7701]
#22 HYBRIS (null)+-219383972 in libminecraftpe.so+0x55a075c [0xf2ec775c]
#23 HYBRIS (null)+-219384063 in libminecraftpe.so+0x55a0701 [0xf2ec7701]
#25 HYBRIS (null)+-219383972 in libminecraftpe.so+0x55a075c [0xf2ec775c]
#26 HYBRIS (null)+-219384063 in libminecraftpe.so+0x55a0701 [0xf2ec7701]
#28 HYBRIS (null)+-219383972 in libminecraftpe.so+0x55a075c [0xf2ec775c]
#29 HYBRIS (null)+-219384063 in libminecraftpe.so+0x55a0701 [0xf2ec7701]
#31 HYBRIS (null)+-219383972 in libminecraftpe.so+0x55a075c [0xf2ec775c]
#32 HYBRIS (null)+-219384063 in libminecraftpe.so+0x55a0701 [0xf2ec7701]
#34 HYBRIS (null)+-219383972 in libminecraftpe.so+0x55a075c [0xf2ec775c]
#35 HYBRIS (null)+-219384063 in libminecraftpe.so+0x55a0701 [0xf2ec7701]
#37 HYBRIS (null)+-219383972 in libminecraftpe.so+0x55a075c [0xf2ec775c]
#38 HYBRIS (null)+-219384063 in libminecraftpe.so+0x55a0701 [0xf2ec7701]
#40 HYBRIS (null)+-219383972 in libminecraftpe.so+0x55a075c [0xf2ec775c]
#77 HYBRIS (null)+-219384063 in libminecraftpe.so+0x55a0701 [0xf2ec7701]
#79 HYBRIS (null)+-219383972 in libminecraftpe.so+0x55a075c [0xf2ec775c]
#116 HYBRIS (null)+-219384063 in libminecraftpe.so+0x55a0701 [0xf2ec7701]
#158 HYBRIS (null)+-188347884 in libminecraftpe.so+0x7339a14 [0xf4c60a14]
#159 HYBRIS (null)+-219550901 in libminecraftpe.so+0x5577b4b [0xf2e9eb4b]
#162 HYBRIS (null)+-187577224 in libminecraftpe.so+0x73f5c78 [0xf4d1cc78]
#165 HYBRIS std::unordered_map<unsigned char, std::string, std::hash<unsigned char>, std::equal_to<unsigned char>, std::allocator<std::pair<unsigned char const, std::string> > >::~unordered_map()+0 in libminecraftpe.so+0x3d77160 [0xf169e160]
#177 HYBRIS std::unordered_map<unsigned char, std::string, std::hash<unsigned char>, std::equal_to<unsigned char>, std::allocator<std::pair<unsigned char const, std::string> > >::~unordered_map()+0 in libminecraftpe.so+0x3d77160 [0xf169e160]
#178 HYBRIS (null)+-187577224 in libminecraftpe.so+0x73f5c78 [0xf4d1cc78]
#217 HYBRIS (null)+-248542070 in libminecraftpe.so+0x39d1c8a [0xf12f8c8a]
#231 HYBRIS (null)+-219550901 in libminecraftpe.so+0x5577b4b [0xf2e9eb4b]
#232 HYBRIS (null)+-188347884 in libminecraftpe.so+0x7339a14 [0xf4c60a14]
#235 HYBRIS xbox::services::serviceLocales+0 in libminecraftpe.so+0x73f6eb0 [0xf4d1deb0]
#236 HYBRIS std::_Hashtable<std::string, std::pair<std::string const, std::string>, std::allocator<std::pair<std::string const, std::string> >, std::__detail::_Select1st, std::equal_to<std::string>, std::hash<std::string>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::_M_insert_unique_node(unsigned int, unsigned int, std::__detail::_Hash_node<std::pair<std::string const, std::string>, true>*)+71 in libminecraftpe.so+0x96e7a7 [0xee2957a7]
#238 HYBRIS xbox::services::serviceLocales+16 in libminecraftpe.so+0x73f6ec0 [0xf4d1dec0]
#242 HYBRIS (null)+-188347884 in libminecraftpe.so+0x7339a14 [0xf4c60a14]
#244 HYBRIS operator new(unsigned int)+39 in libminecraftpe.so+0x5526a67 [0xf2e4da67]
#248 HYBRIS xbox::services::serviceLocales+8 in libminecraftpe.so+0x73f6eb8 [0xf4d1deb8]
#249 HYBRIS (null)+-219525120 in libminecraftpe.so+0x557e000 [0xf2ea5000]
#254 HYBRIS (null)+-188347884 in libminecraftpe.so+0x7339a14 [0xf4c60a14]
#256 HYBRIS std::pair<std::__detail::_Node_iterator<std::pair<std::string const, std::string>, false, true>, bool> std::_Hashtable<std::string, std::pair<std::string const, std::string>, std::allocator<std::pair<std::string const, std::string> >, std::__detail::_Select1st, std::equal_to<std::string>, std::hash<std::string>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::_M_insert<std::pair<std::string const, std::string> const&, std::__detail::_AllocNode<std::allocator<std::__detail::_Hash_node<std::pair<std::string const, std::string>, true> > > >(std::pair<std::string const, std::string> const&, std::__detail::_AllocNode<std::allocator<std::__detail::_Hash_node<std::pair<std::string const, std::string>, true> > > const&, std::integral_constant<bool, true>)+212 in libminecraftpe.so+0xd931a4 [0xee6ba1a4]
#258 HYBRIS xbox::services::serviceLocales+0 in libminecraftpe.so+0x73f6eb0 [0xf4d1deb0]
#525 HYBRIS (null)+-306932824 in libminecraftpe.so+0x2223a8 [0xedb493a8]
#530 HYBRIS (null)+-309169900 in libminecraftpe.so+0x0114 [0xed927114]
#531 HYBRIS (null)+-308512012 in libminecraftpe.so+0xa0af4 [0xed9c7af4]
#559 HYBRIS xbox::services::system::user_impl_android::get_instance()+0 in libminecraftpe.so+0x40c19a0 [0xf19e89a0]
#579 HYBRIS vtable for xbox::services::local_config+8 in libminecraftpe.so+0x72fded0 [0xf4c24ed0]
#856 HYBRIS (null)+-301718233 in libminecraftpe.so+0x71b527 [0xee042527]
Process exited with unexpected exit code: 6

**Comment by VasyanyaGI** [comment]
i have too this problem

**Comment by Theone1053** [comment]
i have the same problem

**Comment by ChristopherHX** [comment]
Please wait at least till some days after its offical Release, **betas** (1.13.0.9+) are **not Supported in this Repo**
If you can't wait to play it, build my [**Fork**](https://github.com/ChristopherHX/mcpelauncher-manifest) of this Launcher which utilizes another approach since the **disappearing of a lot of used Debugging Information**.
