### ISSUE TITLE
On exiting Minecraft the launcher errors with a non-zero error

### ISSUE THREAD

**Issue by ChrisR009** [minecraft-linux/mcpelauncher-manifest#166]
Minecraft plays fine. 

On save & quit from Minecraft the Launcher gives an error.
"Minecraft has exited with a non-zero error code" 

Xubuntu 18.4
15:02:35 Info  [Launcher] Version: client c735370 / manifest eb0bc83
15:02:35 Info  [Launcher] CPU: GenuineIntel        Intel(R) Core(TM) i5-2540M CPU @ 2.60GHz
15:02:35 Info  [Launcher] CPU supports SSSE3: YES
15:02:35 Trace [Launcher] Loading hybris libraries
15:02:35 Trace [HybrisUtils] Loaded OS library /usr/share/mcpelauncher/libs/native/libfmod.so.9.16
15:02:35 Trace [HybrisUtils] Loaded OS library libm.so.6
15:02:35 Trace [HybrisUtils] Loaded OS library libz.so.1
15:02:35 Trace [Launcher] Loading Minecraft library
15:02:35 Info  [Launcher] Loaded Minecraft library
15:02:35 Debug [Launcher] Minecraft is at offset 0xedac8000
15:02:35 Trace [Launcher] Initializing vtables
15:02:35 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServiceLocatorI11AppPlatformE15mDefaultServiceE
15:02:35 Error [MinecraftSymbols] Unresolved symbol: _ZNK11AppPlatform22getHardwareInformationEv
15:02:35 Error [MinecraftSymbols] Unresolved symbol: _ZN17AppResourceLoaderC1ESt8functionIFN4Core10PathBufferISsEEvEE
15:02:35 Error [MinecraftSymbols] Unresolved symbol: _ZN10Automation16AutomationClientC2ER13IMinecraftApp
15:02:35 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance7getUserEv
15:02:35 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance15_startLeaveGameEv
15:02:35 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance16_syncDestroyGameEv
15:02:35 Error [MinecraftSymbols] Unresolved symbol: _ZNK13CommandOutput11getMessagesEv
15:02:35 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender9translateERKSt6vectorISsSaISsEE
15:02:35 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSenderC2ERN10Automation16AutomationClientE
15:02:35 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSenderD2Ev
15:02:35 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender4sendERK13CommandOriginRK13CommandOutput
15:02:35 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender22registerOutputCallbackERKSt8functionIFvR19AutomationCmdOutputEE
15:02:35 Error [MinecraftSymbols] Unresolved symbol: _ZN30ExternalFileLevelStorageSourceC2EPN4Core15FilePathManagerESt10shared_ptrI22SaveTransactionManagerE
15:02:35 Error [MinecraftSymbols] Unresolved symbol: _ZN30ExternalFileLevelStorageSource18createLevelStorageER9SchedulerRKSsRK15ContentIdentityRK19IContentKeyProvider
15:02:35 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourceLoadManagerC2Ev
15:02:35 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourceLoadManager4syncE16ResourceLoadType
15:02:35 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n3getERKSsRKSt6vectorISsSaISsEE
15:02:35 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n14chooseLanguageERKSs
15:02:35 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n13loadLanguagesER19ResourcePackManagerR19ResourceLoadManagerRKSs
15:02:35 Error [MinecraftSymbols] Unresolved symbol: _ZN5Level16createRandomSeedEv
15:02:35 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettingsC2Ev
15:02:35 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettingsC2ERKS_
15:02:35 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettings15parseSeedStringERKSsj
15:02:35 Error [MinecraftSymbols] Unresolved symbol: _ZN9Minecraft11getCommandsEv
15:02:35 Error [MinecraftSymbols] Unresolved symbol: _ZNK9Minecraft8getLevelEv
15:02:35 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftCommands15setOutputSenderESt10unique_ptrI19CommandOutputSenderSt14default_deleteIS1_EE
15:02:35 Error [MinecraftSymbols] Unresolved symbol: _ZNK17MinecraftCommands23requestCommandExecutionESt10unique_ptrI13CommandOriginSt14default_deleteIS1_EERKSsib
15:02:35 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftEventingC2ERKSs
15:02:35 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftEventing4initEv
15:02:35 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGameD2Ev
15:02:35 Error [MinecraftSymbols] Unresolved symbol: _ZNK13MinecraftGame8isInGameEv
15:02:35 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame16requestLeaveGameEbb
15:02:35 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame24getPrimaryClientInstanceEv
15:02:35 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame14startLeaveGameEv
15:02:35 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame17continueLeaveGameEv
15:02:35 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel32navigateToXblConsoleSignInScreenERKSsS1_
15:02:35 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel41navigateToXblConsoleSignInSucceededScreenERKN6Social12SignInResultESt8functionIFvS1_EEb
15:02:35 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel11leaveScreenEv
15:02:35 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social14MultiplayerXBLC2Ev
15:02:35 Error [MinecraftSymbols] Unresolved symbol: _ZN15PermissionsFileC2ERKSs
15:02:35 Error [MinecraftSymbols] Unresolved symbol: _ZN19SkinPackKeyProviderC2Ev
15:02:35 Error [MinecraftSymbols] Unresolved symbol: _ZN19PackManifestFactoryC2ER14IPackTelemetry
15:02:35 Error [MinecraftSymbols] Unresolved symbol: _ZN17PackSourceFactoryC2Ev
15:02:35 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepositoryC2ER18IMinecraftEventingR19PackManifestFactoryR29IContentAccessibilityProviderPN4Core15FilePathManagerER17PackSourceFactoryb
15:02:35 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepository21addWorldResourcePacksERKN4Core4PathE
15:02:35 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepository12refreshPacksEv
15:02:35 Error [MinecraftSymbols] Unresolved symbol: _ZN18ContentTierManagerC2Ev
15:02:35 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManagerC2ESt8functionIFN4Core10PathBufferISsEEvEERK18ContentTierManagerb
15:02:35 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManager8setStackESt10unique_ptrI17ResourcePackStackSt14default_deleteIS1_EE21ResourcePackStackTypeb
15:02:35 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManager17onLanguageChangedEv
15:02:35 Error [MinecraftSymbols] Unresolved symbol: _ZN12PackInstanceC2EP12ResourcePackibP12PackSettings
15:02:35 Error [MinecraftSymbols] Unresolved symbol: _ZTV17ResourcePackStack
15:02:35 Error [MinecraftSymbols] Unresolved symbol: _ZN17ResourcePackStack3addE12PackInstanceRK22ResourcePackRepositoryb
15:02:35 Error [MinecraftSymbols] Unresolved symbol: _ZN22SaveTransactionManagerC2ESt8functionIFvbEE
15:02:35 Error [MinecraftSymbols] Unresolved symbol: _ZN9Scheduler17processCoroutinesENSt6chrono8durationIxSt5ratioILx1ELx1000000000EEEE
15:02:35 Error [MinecraftSymbols] Unresolved symbol: _ZN18MinecraftScheduler6clientEv
15:02:35 Error [MinecraftSymbols] Unresolved symbol: _ZN19ServerCommandOriginC2ERKSsR11ServerLevel22CommandPermissionLevel
15:02:35 Error [MinecraftSymbols] Unresolved symbol: _ZN16EducationOptionsC2EP19ResourcePackManager
15:02:35 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstanceC2ER13IMinecraftAppR30ServerInstanceEventCoordinator
15:02:35 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance16initializeServerER13IMinecraftAppR9WhitelistP15PermissionsFilePN4Core15FilePathManagerENSt6chrono8durationIxSt5ratioILx1ELx1EEEESsSsSs13LevelSettingsib20ConnectionDefinitionbRKSt6vectorISsSaISsEESsRKN3mce4UUIDER18IMinecraftEventingR22ResourcePackRepositoryRK18ContentTierManagerR19ResourcePackManagerSt8functionIFSt10unique_ptrI12LevelStorageSt14default_deleteIS10_EER9SchedulerEERKSsP9LevelDataSsSsSZ_I16EducationOptionsS11_IS1C_EEPSW_SY_IFvvEES1H_P13ServerMetricsP13DebugEndPointb
15:02:35 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstanceD2Ev
15:02:35 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance17startServerThreadEv
15:02:35 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance13leaveGameSyncEv
15:02:35 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance20queueForServerThreadESt8functionIFvvEE
15:02:35 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12MajorVersionE
15:02:35 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12MinorVersionE
15:02:35 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12PatchVersionE
15:02:35 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants15RevisionVersionE
15:02:35 Error [MinecraftSymbols] Unresolved symbol: _ZNK6Social4User11getLiveUserEv
15:02:35 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social12XboxLiveUser22_handleUISignInNoErrorERN4xbox8services6system14sign_in_resultESt8functionIFvNS_12SignInResultEbEE
15:02:35 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social11UserManager17CreateUserManagerEv
15:02:35 Error [MinecraftSymbols] Unresolved symbol: _ZN2v82V810InitializeEv
15:02:35 Error [MinecraftSymbols] Unresolved symbol: _ZN2v82V818InitializePlatformEPNS_8PlatformE
15:02:35 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl15getOpenGLVendorEv
15:02:35 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl17getOpenGLRendererEv
15:02:35 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl16getOpenGLVersionEv
15:02:35 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl19getOpenGLExtensionsEv
15:02:35 Trace [AppPlatform] Vtable size = 288
15:02:35 Trace [Store] Vtable size = 40
15:02:35 Info  [Launcher] Game version: 1.13.0
15:02:35 Info  [Launcher] Applying patches
15:02:35 Trace [Patch] Patching - original: 85 83 87 86 131
15:02:35 Trace [Patch] Patching - result: 233 10 180 56 104
15:02:35 Trace [Patch] Patching - original: 83 87 86 131 236
15:02:35 Trace [Patch] Patching - result: 233 103 86 59 104
15:02:35 Trace [Patch] Patching - original: 85 83 87 86 129
15:02:35 Trace [Patch] Patching - result: 233 189 167 144 100
15:02:35 Trace [Patch] Patching - original: 85 83 87 86 129
15:02:35 Trace [Patch] Patching - result: 233 189 197 206 100
15:02:35 Trace [Patch] Patching - original: 85 83 87 86 129
15:02:35 Trace [Patch] Patching - result: 233 19 214 206 100
15:02:35 Trace [Patch] Patching - original: 85 83 87 86 129
15:02:35 Trace [Patch] Patching - result: 233 135 194 206 100
15:02:35 Trace [Patch] Patching - original: 85 83 87 86 129
15:02:35 Trace [Patch] Patching - result: 233 207 41 206 100
15:02:35 Trace [Patch] Patching - original: 85 83 87 86 129
15:02:35 Trace [Patch] Patching - result: 233 219 29 206 100
15:02:35 Trace [Patch] Patching - original: 85 83 87 86 129
15:02:35 Trace [Patch] Patching - result: 233 177 81 208 100
15:02:35 Trace [Patch] Patching - original: 83 87 86 131 236
15:02:35 Trace [Patch] Patching - result: 233 15 189 206 100
15:02:35 Trace [Patch] Patching - original: 85 83 87 86 129
15:02:35 Trace [Patch] Patching - result: 233 203 231 206 100
15:02:35 Trace [Patch] Patching - original: 83 131 236 8 232
15:02:35 Trace [Patch] Patching - result: 233 255 197 236 100
15:02:35 Trace [Patch] Patching - original: 137 76 36 4 137
15:02:35 Trace [Patch] Patching - result: 232 243 249 161 100
15:02:35 Trace [Patch] Patching - original: 36 88 139 65 12
15:02:35 Trace [Patch] Patching - result: 232 254 249 161 100
15:02:35 Trace [Patch] Patching - original: 85 83 87 86 131
15:02:35 Trace [Patch] Patching - result: 233 152 116 136 100
15:02:35 Error [SplitscreenPatch] Not patching splitscreen - incompatible code
15:02:35 Info  [Launcher] Creating window
15:02:35 Trace [Launcher] Loading gamepad mappings: /usr/share/mcpelauncher/gamecontrollerdb.txt
15:02:35 Trace [Launcher] Loading gamepad mappings: /usr/share/mcpelauncher/gamecontrollerdb.txt
15:02:35 Trace [Launcher] Loading gamepad mappings: /usr/share/mcpelauncher/gamecontrollerdb.txt
15:02:35 Trace [Launcher] Initializing AppPlatform (create instance)
15:02:35 Trace [Launcher] Initializing AppPlatform (initialize call)
15:02:35 Trace [AppPlatform] createDeviceID (from file): 0bd32f53-faa1-4d59-b584-6ec8175ea30a
15:02:35 Trace [Launcher] Initializing MinecraftGame (create instance)
15:02:35 Trace [Launcher] Initializing MinecraftGame (init call)
15:02:35 Info  [Launcher] Game initialized
15:02:35 Trace [AppPlatform] getDataUrl: /home/chris/.local/share/mcpelauncher/versions/1.13.0.34/assets/
15:02:35 Error [LauncherAppPlatform] readAssetFile: not found: /home/chris/.local/share/mcpelauncher/versions/1.13.0.34/assets/skin_packs/vanilla/contents.json
15:02:35 Error [LauncherAppPlatform] readAssetFile: not found: /home/chris/.local/share/mcpelauncher/versions/1.13.0.34/assets/skin_packs/persona/contents.json
15:02:35 Error [LauncherAppPlatform] readAssetFile: not found: /home/chris/.local/share/mcpelauncher/versions/1.13.0.34/assets/skin_packs/persona/geometry.json
15:02:35 Error [LauncherAppPlatform] readAssetFile: not found: /home/chris/.local/share/mcpelauncher/versions/1.13.0.34/assets/skin_packs/vanilla/contents.json
15:02:35 Trace [AppPlatform] getDataUrl: /home/chris/.local/share/mcpelauncher/versions/1.13.0.34/assets/
15:02:36 Trace [XboxLive] Reading xbox config file
15:02:36 Error [XSAPI.Android] java interop not initialized properly
15:02:36 Trace [Launcher] Creating store
15:02:36 Trace [Store] registerLicenseChangeCallback
15:02:36 Error [LauncherAppPlatform] readAssetFile: not found: /home/chris/.local/share/mcpelauncher/versions/1.13.0.34/assets/resource_packs/persona/geometry.json
15:02:36 Trace [AppPlatform] isTablet: true
15:02:36 Trace [AppPlatform] getApplicationId: com.mojang.minecraftpe
15:02:36 Trace [Store] getStoreId: android.googleplay
15:02:36 Error [LauncherAppPlatform] readAssetFile: not found: /home/chris/.local/share/mcpelauncher/versions/1.13.0.34/assets/resource_packs/vanilla_base/models/mobs.json
15:02:36 Trace [XboxLive] verify_cert_chain_platform_specific stub called
15:02:36 Trace [XboxLive] verify_cert_chain_platform_specific stub called
15:02:36 Trace [Store] getStoreId: android.googleplay
15:02:36 Trace [XboxLive] verify_cert_chain_platform_specific stub called
15:02:36 Trace [XboxLive] verify_cert_chain_platform_specific stub called
15:02:36 Trace [XboxLive] verify_cert_chain_platform_specific stub called
15:02:36 Trace [XboxLive] verify_cert_chain_platform_specific stub called
15:02:36 Debug [XSAPI.Android] sign_in_impl: will NOT be showing UI
15:02:36 Trace [XboxLive] log_telemetry_signin 1 Entering
15:02:36 Trace [Launcher] init_sign_in_activity 1
15:02:36 Trace [DaemonLauncher] Starting daemon: /usr/bin/msa-daemon
15:02:36 Trace [XboxLive] verify_cert_chain_platform_specific stub called
15:02:36 Trace [XboxLive] verify_cert_chain_platform_specific stub called
15:02:36 Trace [XboxLive] verify_cert_chain_platform_specific stub called
15:02:36 Trace [XboxLive] verify_cert_chain_platform_specific stub called
15:02:37 Trace [XboxLive] verify_cert_chain_platform_specific stub called
15:02:37 Trace [XboxLive] verify_cert_chain_platform_specific stub called
15:02:37 Trace [XboxLive] verify_cert_chain_platform_specific stub called
15:02:37 Trace [XboxLive] verify_cert_chain_platform_specific stub called
15:02:37 Trace [XboxLive] verify_cert_chain_platform_specific stub called
15:02:37 Trace [XboxLive] verify_cert_chain_platform_specific stub called
Signal 11 received
Backtrace elements: 2
#0 /usr/bin/mcpelauncher-client(_ZN12CrashHandler12handleSignalEiPv+0xc5) [0x568077db]
#1 linux-gate.so.1(__kernel_sigreturn+0) [0xf7f58950]
Dumping stack...
#272 HYBRIS (null)+-294970696 in libminecraftpe.so+0xbe9ab8 [0xee6b1ab8]
#299 HYBRIS (null)+-294970696 in libminecraftpe.so+0xbe9ab8 [0xee6b1ab8]
Process exited with unexpected exit code: 6

**Comment by Mhowser** [comment]
Thank you for the crash report, We are consolidating all issues related to 1.13+ crashes to #165
