### ISSUE TITLE
Missing libpng12.so.0

### ISSUE THREAD

**Issue by KamenkoTV** [minecraft-linux/mcpelauncher-manifest#167]
`mcpelauncher
/usr/local/share/mcpelauncher/bin/mcpelauncher: error while loading shared libraries: libpng12.so.0: cannot open shared object file: No such file or directory`

i tried 
`wget http://security.ubuntu.com/ubuntu/pool/main/libp/libpng/libpng12-0_1.2.54-1ubuntu1.1_amd64.deb  && sudo apt install ./libpng12-0_1.2.54-1ubuntu1.1_amd64.deb`

but I still have the same issue can someone please help me.??

OS: Xubuntu Latest LTS release: 18.04, Bionic Beaver
Kernel: 5.0.0-32-generic

**Comment by Nikita11790** [comment]
try 
[This](https://www.linuxuprising.com/2018/05/fix-libpng12-0-missing-in-ubuntu-1804.html)

**Comment by KamenkoTV** [comment]
> try
> [This](https://www.linuxuprising.com/2018/05/fix-libpng12-0-missing-in-ubuntu-1804.html)

it doesn't work all the steps on site i alerdy did thats the command i said that i tried
`wget http://security.ubuntu.com/ubuntu/pool/main/libp/libpng/libpng12-0_1.2.54-1ubuntu1.1_amd64.deb && sudo apt install ./libpng12-0_1.2.54-1ubuntu1.1_amd64.deb`

**Comment by ChristopherHX** [comment]
You need `sudo apt install libpng12-0:i386`, the launcher was (is) 32bit only for a long time

My fork for running latest Minecraft
https://github.com/ChristopherHX/linux-packaging-scripts/releases/tag/appimage
