### ISSUE TITLE
1.13.0.34 crashes on launching game

### ISSUE THREAD

**Issue by MaryCBaylis** [minecraft-linux/mcpelauncher-manifest#168]
I get this error when I click the giant green play button:

23:42:33 Info  [Launcher] Version: client a48cb4c / manifest d9cc8d9
23:42:33 Info  [Launcher] CPU: GenuineIntel Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz
23:42:33 Info  [Launcher] CPU supports SSSE3: YES
23:42:33 Trace [Launcher] Loading hybris libraries
23:42:33 Trace [HybrisUtils] Loaded OS library /Applications/Minecraft Bedrock Launcher.app/Contents/Resources/mcpelauncher/libs/native/libfmod.dylib
23:42:33 Trace [HybrisUtils] Loaded OS library libm.dylib
23:42:33 Error [HybrisUtils] Failed to load OS library libz.so.1
23:42:33 Trace [Launcher] Loading Minecraft library
23:42:34 Info  [Launcher] Loaded Minecraft library
23:42:34 Debug [Launcher] Minecraft is at offset 0x2b9f000
23:42:34 Error [MinecraftSymbols] Unresolved symbol: _ZN3App4initER10AppContext
23:42:34 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App4quitERKSsS1_
23:42:34 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App6updateEv
23:42:34 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App16setRenderingSizeEii
23:42:34 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App17setUISizeAndScaleEiif
23:42:34 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App10wantToQuitEv
23:42:34 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServiceLocatorI11AppPlatformE15mDefaultServiceE
23:42:34 Error [MinecraftSymbols] Unresolved symbol: _ZNK11AppPlatform22getHardwareInformationEv
23:42:34 Error [MinecraftSymbols] Unresolved symbol: _ZN17AppResourceLoaderC2ESt8functionIFSsvEE
23:42:34 Error [MinecraftSymbols] Unresolved symbol: _ZN10Automation16AutomationClientC2ER13IMinecraftApp
23:42:34 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance7getUserEv
23:42:34 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance15_startLeaveGameEv
23:42:34 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance16_syncDestroyGameEv
23:42:34 Error [MinecraftSymbols] Unresolved symbol: _ZNK13CommandOutput11getMessagesEv
23:42:34 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender9translateERKSt6vectorISsSaISsEE
23:42:34 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSenderC2ERN10Automation16AutomationClientE
23:42:34 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSenderD2Ev
23:42:34 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender4sendERK13CommandOriginRK13CommandOutput
23:42:34 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender22registerOutputCallbackERKSt8functionIFvR19AutomationCmdOutputEE
23:42:34 Error [MinecraftSymbols] Unresolved symbol: _ZN6Common23getGameVersionStringNetEv
23:42:34 Error [MinecraftSymbols] Unresolved symbol: _ZN30ExternalFileLevelStorageSourceC2EP15FilePathManagerSt10shared_ptrI22SaveTransactionManagerE
23:42:34 Error [MinecraftSymbols] Unresolved symbol: _ZN30ExternalFileLevelStorageSource18createLevelStorageER9SchedulerRKSsRK15ContentIdentityRK19IContentKeyProvider
23:42:34 Error [MinecraftSymbols] Unresolved symbol: _ZN15FilePathManagerC2ESsb
23:42:34 Error [MinecraftSymbols] Unresolved symbol: _ZNK15FilePathManager11getRootPathEv
23:42:34 Error [MinecraftSymbols] Unresolved symbol: _ZNK15FilePathManager15getUserDataPathEv
23:42:34 Error [MinecraftSymbols] Unresolved symbol: _ZNK15FilePathManager13getWorldsPathEv
23:42:34 Error [MinecraftSymbols] Unresolved symbol: _ZN15FilePathManager14setPackagePathESs
23:42:34 Error [MinecraftSymbols] Unresolved symbol: _ZNK15FilePathManager14getPackagePathEv
23:42:34 Error [MinecraftSymbols] Unresolved symbol: _ZN15FilePathManager15setSettingsPathESs
23:42:34 Error [MinecraftSymbols] Unresolved symbol: _ZNK15FilePathManager15getSettingsPathEv
23:42:34 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourceLoadManagerC2Ev
23:42:34 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourceLoadManager4syncE16ResourceLoadType
23:42:34 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n3getERKSsRKSt6vectorISsSaISsEE
23:42:34 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n14chooseLanguageERKSs
23:42:34 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n13loadLanguagesER19ResourcePackManagerR19ResourceLoadManagerRKSs
23:42:34 Error [MinecraftSymbols] Unresolved symbol: _ZN5Level16createRandomSeedEv
23:42:34 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettingsC2Ev
23:42:34 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettingsC2ERKS_
23:42:34 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettings15parseSeedStringERKSsj
23:42:34 Error [MinecraftSymbols] Unresolved symbol: _ZN9Minecraft11getCommandsEv
23:42:34 Error [MinecraftSymbols] Unresolved symbol: _ZNK9Minecraft8getLevelEv
23:42:34 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftCommands15setOutputSenderESt10unique_ptrI19CommandOutputSenderSt14default_deleteIS1_EE
23:42:34 Error [MinecraftSymbols] Unresolved symbol: _ZNK17MinecraftCommands23requestCommandExecutionESt10unique_ptrI13CommandOriginSt14default_deleteIS1_EERKSsib
23:42:34 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftEventingC2ERKSs
23:42:34 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftEventing4initEv
23:42:34 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGameC2EiPPc
23:42:34 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGameD2Ev
23:42:34 Error [MinecraftSymbols] Unresolved symbol: _ZNK13MinecraftGame8isInGameEv
23:42:34 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame16requestLeaveGameEbb
23:42:34 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame24doPrimaryClientReadyWorkESt8functionIFvvEE
23:42:34 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame21getPrimaryUserOptionsEv
23:42:34 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame24getPrimaryClientInstanceEv
23:42:34 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame14startLeaveGameEv
23:42:34 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame17continueLeaveGameEv
23:42:34 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame14setTextboxTextERKSsi
23:42:34 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel32navigateToXblConsoleSignInScreenERKSsS1_
23:42:34 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel41navigateToXblConsoleSignInSucceededScreenERKN6Social12SignInResultESt8functionIFvS1_EEb
23:42:34 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel11leaveScreenEv
23:42:34 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social14MultiplayerXBLC2Ev
23:42:34 Error [MinecraftSymbols] Unresolved symbol: _ZTV22NullTextToSpeechClient
23:42:34 Error [MinecraftSymbols] Unresolved symbol: _ZNK7Options13getFullscreenEv
23:42:34 Error [MinecraftSymbols] Unresolved symbol: _ZN7Options13setFullscreenEb
23:42:34 Error [MinecraftSymbols] Unresolved symbol: _ZN15PermissionsFileC2ERKSs
23:42:34 Error [MinecraftSymbols] Unresolved symbol: _ZN19SkinPackKeyProviderC2Ev
23:42:34 Error [MinecraftSymbols] Unresolved symbol: _ZN19PackManifestFactoryC2ER14IPackTelemetry
23:42:34 Error [MinecraftSymbols] Unresolved symbol: _ZN17PackSourceFactoryC2EP7Options
23:42:34 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepositoryC2ER18IMinecraftEventingR19PackManifestFactoryR29IContentAccessibilityProviderP15FilePathManagerR17PackSourceFactoryb
23:42:34 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepository21addWorldResourcePacksERKSs
23:42:34 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepository12refreshPacksEv
23:42:34 Error [MinecraftSymbols] Unresolved symbol: _ZN18ContentTierManagerC2Ev
23:42:34 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManagerC2ESt8functionIFSsvEERK18ContentTierManagerb
23:42:34 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManager8setStackESt10unique_ptrI17ResourcePackStackSt14default_deleteIS1_EE21ResourcePackStackTypeb
23:42:34 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManager17onLanguageChangedEv
23:42:34 Error [MinecraftSymbols] Unresolved symbol: _ZN12PackInstanceC2EP12ResourcePackibP12PackSettings
23:42:34 Error [MinecraftSymbols] Unresolved symbol: _ZTV17ResourcePackStack
23:42:34 Error [MinecraftSymbols] Unresolved symbol: _ZN17ResourcePackStack3addE12PackInstanceRK22ResourcePackRepositoryb
23:42:34 Error [MinecraftSymbols] Unresolved symbol: _ZN22SaveTransactionManagerC2ESt8functionIFvbEE
23:42:34 Error [MinecraftSymbols] Unresolved symbol: _ZN9Scheduler17processCoroutinesENSt6chrono8durationIxSt5ratioILx1ELx1000000000EEEE
23:42:34 Error [MinecraftSymbols] Unresolved symbol: _ZN18MinecraftScheduler6clientEv
23:42:34 Error [MinecraftSymbols] Unresolved symbol: _ZN19ServerCommandOriginC2ERKSsR11ServerLevel
23:42:34 Error [MinecraftSymbols] Unresolved symbol: _ZN16EducationOptionsC2EP19ResourcePackManager
23:42:34 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstanceC2ER13IMinecraftAppR30ServerInstanceEventCoordinator
23:42:34 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance16initializeServerER13IMinecraftAppR9WhitelistP15PermissionsFileP15FilePathManagerNSt6chrono8durationIxSt5ratioILx1ELx1EEEESsSsSs13LevelSettingsib20ConnectionDefinitionbRKSt6vectorISsSaISsEESsRKN3mce4UUIDER18IMinecraftEventingR22ResourcePackRepositoryRK18ContentTierManagerR19ResourcePackManagerSt8functionIFSt10unique_ptrI12LevelStorageSt14default_deleteISZ_EER9SchedulerEERKSsP9LevelDataSsSsSY_I16EducationOptionsS10_IS1B_EEPSV_SX_IFvS18_EES1G_P13ServerMetricsP13DebugEndPoint
23:42:34 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstanceD2Ev
23:42:34 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance17startServerThreadEv
23:42:34 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance13leaveGameSyncEv
23:42:34 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance20queueForServerThreadESt8functionIFvvEE
23:42:34 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12MajorVersionE
23:42:34 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12MinorVersionE
23:42:34 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12PatchVersionE
23:42:34 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants15RevisionVersionE
23:42:34 Error [MinecraftSymbols] Unresolved symbol: _ZNK6Social4User11getLiveUserEv
23:42:34 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social12XboxLiveUser22_handleUISignInNoErrorERN4xbox8services6system14sign_in_resultESt8functionIFvNS_12SignInResultEbEE
23:42:34 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN9GameStore18onStoreInitializedEb
23:42:34 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN9GameStore22onQueryProductsSuccessERKSt6vectorI11ProductInfoSaIS1_EE
23:42:34 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social11UserManager17CreateUserManagerEv
23:42:34 Error [MinecraftSymbols] Unresolved symbol: _ZN2v82V810InitializeEv
23:42:34 Error [MinecraftSymbols] Unresolved symbol: _ZN2v82V818InitializePlatformEPNS_8PlatformE
23:42:34 Error [MinecraftSymbols] Unresolved symbol: _ZNK4pplx4taskIN4xbox8services16xbox_live_resultINS2_6system26token_and_signature_resultEEEE3getEv
23:42:34 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl15getOpenGLVendorEv
23:42:34 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl17getOpenGLRendererEv
23:42:34 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl16getOpenGLVersionEv
23:42:34 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl19getOpenGLExtensionsEv
23:42:34 Error [MinecraftSymbols] Unresolved symbol: _ZN3mce8Platform3OGL12InitBindingsEv
Signal 11 received
Backtrace elements: 5
#0 0   mcpelauncher-client                 0x00102f2e _ZN12CrashHandler12handleSignalEiPv + 318
#1 1   libsystem_platform.dylib            0xa7ccabae _sigtramp + 46
#2 2   ???                                 0xffffffff 0x0 + 4294967295
#3 3   mcpelauncher-client                 0x00049244 main + 10532
#4 4   libdyld.dylib                       0xa7ae1051 start + 1
Dumping stack...
#283 HYBRIS (null)+45740032 in libminecraftpe.so+0x0000 [0x2b9f000]
#327 HYBRIS (null)+45740032 in libminecraftpe.so+0x0000 [0x2b9f000]
Process exited with unexpected exit code: 6

**Comment by alissonlauffer** [comment]
Update your launcher version to the latest (revision eb0bc83).

**Comment by MaryCBaylis** [comment]
I appreciate the response. I've tried that a couple of times. I get this error:

22:26:30 Info  [Launcher] Version: client c735370 / manifest eb0bc83
22:26:30 Info  [Launcher] CPU: GenuineIntel Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz
22:26:30 Info  [Launcher] CPU supports SSSE3: YES
22:26:30 Trace [Launcher] Loading hybris libraries
22:26:30 Trace [HybrisUtils] Loaded OS library /Applications/Minecraft Bedrock Launcher.app/Contents/Resources/mcpelauncher/libs/native/libfmod.dylib
22:26:30 Trace [HybrisUtils] Loaded OS library libm.dylib
22:26:30 Error [HybrisUtils] Failed to load OS library libz.so.1
22:26:30 Trace [Launcher] Loading Minecraft library
22:26:31 Info  [Launcher] Loaded Minecraft library
22:26:31 Debug [Launcher] Minecraft is at offset 0x2c3e000
22:26:31 Trace [Launcher] Initializing vtables
22:26:31 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServiceLocatorI11AppPlatformE15mDefaultServiceE
22:26:31 Error [MinecraftSymbols] Unresolved symbol: _ZNK11AppPlatform22getHardwareInformationEv
22:26:31 Error [MinecraftSymbols] Unresolved symbol: _ZN17AppResourceLoaderC1ESt8functionIFN4Core10PathBufferISsEEvEE
22:26:31 Error [MinecraftSymbols] Unresolved symbol: _ZN10Automation16AutomationClientC2ER13IMinecraftApp
22:26:31 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance7getUserEv
22:26:31 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance15_startLeaveGameEv
22:26:31 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance16_syncDestroyGameEv
22:26:31 Error [MinecraftSymbols] Unresolved symbol: _ZNK13CommandOutput11getMessagesEv
22:26:31 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender9translateERKSt6vectorISsSaISsEE
22:26:31 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSenderC2ERN10Automation16AutomationClientE
22:26:31 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSenderD2Ev
22:26:31 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender4sendERK13CommandOriginRK13CommandOutput
22:26:31 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender22registerOutputCallbackERKSt8functionIFvR19AutomationCmdOutputEE
22:26:31 Error [MinecraftSymbols] Unresolved symbol: _ZN30ExternalFileLevelStorageSourceC2EPN4Core15FilePathManagerESt10shared_ptrI22SaveTransactionManagerE
22:26:31 Error [MinecraftSymbols] Unresolved symbol: _ZN30ExternalFileLevelStorageSource18createLevelStorageER9SchedulerRKSsRK15ContentIdentityRK19IContentKeyProvider
22:26:31 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourceLoadManagerC2Ev
22:26:31 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourceLoadManager4syncE16ResourceLoadType
22:26:31 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n3getERKSsRKSt6vectorISsSaISsEE
22:26:31 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n14chooseLanguageERKSs
22:26:31 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n13loadLanguagesER19ResourcePackManagerR19ResourceLoadManagerRKSs
22:26:31 Error [MinecraftSymbols] Unresolved symbol: _ZN5Level16createRandomSeedEv
22:26:31 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettingsC2Ev
22:26:31 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettingsC2ERKS_
22:26:31 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettings15parseSeedStringERKSsj
22:26:31 Error [MinecraftSymbols] Unresolved symbol: _ZN9Minecraft11getCommandsEv
22:26:31 Error [MinecraftSymbols] Unresolved symbol: _ZNK9Minecraft8getLevelEv
22:26:31 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftCommands15setOutputSenderESt10unique_ptrI19CommandOutputSenderSt14default_deleteIS1_EE
22:26:31 Error [MinecraftSymbols] Unresolved symbol: _ZNK17MinecraftCommands23requestCommandExecutionESt10unique_ptrI13CommandOriginSt14default_deleteIS1_EERKSsib
22:26:31 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftEventingC2ERKSs
22:26:31 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftEventing4initEv
22:26:31 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGameD2Ev
22:26:31 Error [MinecraftSymbols] Unresolved symbol: _ZNK13MinecraftGame8isInGameEv
22:26:31 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame16requestLeaveGameEbb
22:26:31 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame24getPrimaryClientInstanceEv
22:26:31 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame14startLeaveGameEv
22:26:31 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame17continueLeaveGameEv
22:26:31 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel32navigateToXblConsoleSignInScreenERKSsS1_
22:26:31 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel41navigateToXblConsoleSignInSucceededScreenERKN6Social12SignInResultESt8functionIFvS1_EEb
22:26:31 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel11leaveScreenEv
22:26:31 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social14MultiplayerXBLC2Ev
22:26:31 Error [MinecraftSymbols] Unresolved symbol: _ZN15PermissionsFileC2ERKSs
22:26:31 Error [MinecraftSymbols] Unresolved symbol: _ZN19SkinPackKeyProviderC2Ev
22:26:31 Error [MinecraftSymbols] Unresolved symbol: _ZN19PackManifestFactoryC2ER14IPackTelemetry
22:26:31 Error [MinecraftSymbols] Unresolved symbol: _ZN17PackSourceFactoryC2Ev
22:26:31 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepositoryC2ER18IMinecraftEventingR19PackManifestFactoryR29IContentAccessibilityProviderPN4Core15FilePathManagerER17PackSourceFactoryb
22:26:31 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepository21addWorldResourcePacksERKN4Core4PathE
22:26:31 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepository12refreshPacksEv
22:26:31 Error [MinecraftSymbols] Unresolved symbol: _ZN18ContentTierManagerC2Ev
22:26:31 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManagerC2ESt8functionIFN4Core10PathBufferISsEEvEERK18ContentTierManagerb
22:26:31 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManager8setStackESt10unique_ptrI17ResourcePackStackSt14default_deleteIS1_EE21ResourcePackStackTypeb
22:26:31 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManager17onLanguageChangedEv
22:26:31 Error [MinecraftSymbols] Unresolved symbol: _ZN12PackInstanceC2EP12ResourcePackibP12PackSettings
22:26:31 Error [MinecraftSymbols] Unresolved symbol: _ZTV17ResourcePackStack
22:26:31 Error [MinecraftSymbols] Unresolved symbol: _ZN17ResourcePackStack3addE12PackInstanceRK22ResourcePackRepositoryb
22:26:31 Error [MinecraftSymbols] Unresolved symbol: _ZN22SaveTransactionManagerC2ESt8functionIFvbEE
22:26:31 Error [MinecraftSymbols] Unresolved symbol: _ZN9Scheduler17processCoroutinesENSt6chrono8durationIxSt5ratioILx1ELx1000000000EEEE
22:26:31 Error [MinecraftSymbols] Unresolved symbol: _ZN18MinecraftScheduler6clientEv
22:26:31 Error [MinecraftSymbols] Unresolved symbol: _ZN19ServerCommandOriginC2ERKSsR11ServerLevel22CommandPermissionLevel
22:26:31 Error [MinecraftSymbols] Unresolved symbol: _ZN16EducationOptionsC2EP19ResourcePackManager
22:26:31 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstanceC2ER13IMinecraftAppR30ServerInstanceEventCoordinator
22:26:31 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance16initializeServerER13IMinecraftAppR9WhitelistP15PermissionsFilePN4Core15FilePathManagerENSt6chrono8durationIxSt5ratioILx1ELx1EEEESsSsSs13LevelSettingsib20ConnectionDefinitionbRKSt6vectorISsSaISsEESsRKN3mce4UUIDER18IMinecraftEventingR22ResourcePackRepositoryRK18ContentTierManagerR19ResourcePackManagerSt8functionIFSt10unique_ptrI12LevelStorageSt14default_deleteIS10_EER9SchedulerEERKSsP9LevelDataSsSsSZ_I16EducationOptionsS11_IS1C_EEPSW_SY_IFvvEES1H_P13ServerMetricsP13DebugEndPointb
22:26:31 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstanceD2Ev
22:26:31 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance17startServerThreadEv
22:26:31 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance13leaveGameSyncEv
22:26:31 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance20queueForServerThreadESt8functionIFvvEE
22:26:31 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12MajorVersionE
22:26:31 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12MinorVersionE
22:26:31 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12PatchVersionE
22:26:31 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants15RevisionVersionE
22:26:31 Error [MinecraftSymbols] Unresolved symbol: _ZNK6Social4User11getLiveUserEv
22:26:31 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social12XboxLiveUser22_handleUISignInNoErrorERN4xbox8services6system14sign_in_resultESt8functionIFvNS_12SignInResultEbEE
22:26:31 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social11UserManager17CreateUserManagerEv
22:26:31 Error [MinecraftSymbols] Unresolved symbol: _ZN2v82V810InitializeEv
22:26:31 Error [MinecraftSymbols] Unresolved symbol: _ZN2v82V818InitializePlatformEPNS_8PlatformE
22:26:31 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl15getOpenGLVendorEv
22:26:31 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl17getOpenGLRendererEv
22:26:31 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl16getOpenGLVersionEv
22:26:31 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl19getOpenGLExtensionsEv
22:26:31 Trace [AppPlatform] Vtable size = 288
22:26:31 Trace [Store] Vtable size = 40
22:26:31 Info  [Launcher] Game version: 1.13.0
22:26:31 Info  [Launcher] Applying patches
22:26:31 Trace [Patch] Patching - original: 85 83 87 86 131
22:26:31 Trace [Patch] Patching - result: 233 251 89 178 252
22:26:31 Trace [Patch] Patching - original: 83 87 86 131 236
22:26:31 Trace [Patch] Patching - result: 233 11 247 183 252
22:26:31 Trace [Patch] Patching - original: 85 83 87 86 129
22:26:31 Trace [Patch] Patching - result: 233 43 107 10 249
22:26:31 Trace [Patch] Patching - original: 85 83 87 86 129
22:26:31 Trace [Patch] Patching - result: 233 59 137 72 249
22:26:31 Trace [Patch] Patching - original: 85 83 87 86 129
22:26:31 Trace [Patch] Patching - result: 233 203 162 72 249
22:26:31 Trace [Patch] Patching - original: 85 83 87 86 129
22:26:31 Trace [Patch] Patching - result: 233 107 143 72 249
22:26:31 Trace [Patch] Patching - original: 85 83 87 86 129
22:26:31 Trace [Patch] Patching - result: 233 139 246 71 249
22:26:31 Trace [Patch] Patching - original: 85 83 87 86 129
22:26:31 Trace [Patch] Patching - result: 233 155 234 71 249
22:26:31 Trace [Patch] Patching - original: 85 83 87 86 129
22:26:31 Trace [Patch] Patching - result: 233 59 39 74 249
22:26:31 Trace [Patch] Patching - original: 83 87 86 131 236
22:26:31 Trace [Patch] Patching - result: 233 219 136 72 249
22:26:31 Trace [Patch] Patching - original: 85 83 87 86 129
22:26:31 Trace [Patch] Patching - result: 233 155 179 72 249
22:26:31 Trace [Patch] Patching - original: 83 131 236 8 232
22:26:31 Trace [Patch] Patching - result: 233 171 210 105 249
22:26:31 Trace [Patch] Patching - original: 137 76 36 4 137
22:26:31 Trace [Patch] Patching - result: 232 113 35 31 249
22:26:31 Trace [Patch] Patching - original: 36 88 139 65 12
22:26:31 Trace [Patch] Patching - result: 232 124 35 31 249
22:26:31 Trace [Patch] Patching - original: 85 83 87 86 131
22:26:31 Trace [Patch] Patching - result: 233 91 22 5 249
22:26:31 Error [SplitscreenPatch] Not patching splitscreen - incompatible code
Signal 11 received
Backtrace elements: 6
#0 0   mcpelauncher-client                 0x0016b88e _ZN12CrashHandler12handleSignalEiPv + 318
#1 1   libsystem_platform.dylib            0xa7ccabae _sigtramp + 46
#2 2   ???                                 0xffffffff 0x0 + 4294967295
#3 3   mcpelauncher-client                 0x001315b6 _ZN11GLCorePatch7installEPv + 662
#4 4   mcpelauncher-client                 0x000b1a95 main + 10981
#5 5   libdyld.dylib                       0xa7ae1051 start + 1
Dumping stack...
#78 HYBRIS (null)+135530281 in libminecraftpe.so+0x5502729 [0x8140729]
#128 HYBRIS (null)+56283728 in libminecraftpe.so+0x96f250 [0x35ad250]
#129 HYBRIS (null)+56283792 in libminecraftpe.so+0x96f290 [0x35ad290]
#130 HYBRIS (null)+56283808 in libminecraftpe.so+0x96f2a0 [0x35ad2a0]
#131 HYBRIS (null)+56283824 in libminecraftpe.so+0x96f2b0 [0x35ad2b0]
#277 HYBRIS mce::ShaderGroupBase::loadShader(std::string const&, Core::Path const&, Core::Path const&, Core::Path const&)+0 in libminecraftpe.so+0x3afbde0 [0x6739de0]
#386 HYBRIS (null)+46391296 in libminecraftpe.so+0x0000 [0x2c3e000]
#387 HYBRIS (null)+46391296 in libminecraftpe.so+0x0000 [0x2c3e000]
Process exited with unexpected exit code: 6

**Comment by Mhowser** [comment]
Thank you for the crash report, We are consolidating all issues related to 1.13+ crashes to #165
