### ISSUE TITLE
Minecraft 1.13.0.34 crash.

### ISSUE THREAD

**Issue by bobby4343** [minecraft-linux/mcpelauncher-manifest#169]
18:20:42 Info  [Launcher] Version: client a48cb4c / manifest d9cc8d9
18:20:42 Info  [Launcher] CPU: GenuineIntel Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
18:20:42 Info  [Launcher] CPU supports SSSE3: YES
18:20:42 Trace [Launcher] Loading hybris libraries
18:20:42 Trace [HybrisUtils] Loaded OS library /Users/andrewstarliper/Desktop/Minecraft Bedrock Launcher.app/Contents/Resources/mcpelauncher/libs/native/libfmod.dylib
18:20:42 Trace [HybrisUtils] Loaded OS library libm.dylib
18:20:42 Error [HybrisUtils] Failed to load OS library libz.so.1
18:20:42 Trace [Launcher] Loading Minecraft library
18:20:43 Info  [Launcher] Loaded Minecraft library
18:20:43 Debug [Launcher] Minecraft is at offset 0x323e000
18:20:43 Error [MinecraftSymbols] Unresolved symbol: _ZN3App4initER10AppContext
18:20:43 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App4quitERKSsS1_
18:20:43 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App6updateEv
18:20:43 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App16setRenderingSizeEii
18:20:43 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App17setUISizeAndScaleEiif
18:20:43 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App10wantToQuitEv
18:20:43 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServiceLocatorI11AppPlatformE15mDefaultServiceE
18:20:43 Error [MinecraftSymbols] Unresolved symbol: _ZNK11AppPlatform22getHardwareInformationEv
18:20:43 Error [MinecraftSymbols] Unresolved symbol: _ZN17AppResourceLoaderC2ESt8functionIFSsvEE
18:20:43 Error [MinecraftSymbols] Unresolved symbol: _ZN10Automation16AutomationClientC2ER13IMinecraftApp
18:20:43 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance7getUserEv
18:20:43 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance15_startLeaveGameEv
18:20:43 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance16_syncDestroyGameEv
18:20:43 Error [MinecraftSymbols] Unresolved symbol: _ZNK13CommandOutput11getMessagesEv
18:20:43 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender9translateERKSt6vectorISsSaISsEE
18:20:43 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSenderC2ERN10Automation16AutomationClientE
18:20:43 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSenderD2Ev
18:20:43 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender4sendERK13CommandOriginRK13CommandOutput
18:20:43 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender22registerOutputCallbackERKSt8functionIFvR19AutomationCmdOutputEE
18:20:43 Error [MinecraftSymbols] Unresolved symbol: _ZN6Common23getGameVersionStringNetEv
18:20:43 Error [MinecraftSymbols] Unresolved symbol: _ZN30ExternalFileLevelStorageSourceC2EP15FilePathManagerSt10shared_ptrI22SaveTransactionManagerE
18:20:43 Error [MinecraftSymbols] Unresolved symbol: _ZN30ExternalFileLevelStorageSource18createLevelStorageER9SchedulerRKSsRK15ContentIdentityRK19IContentKeyProvider
18:20:43 Error [MinecraftSymbols] Unresolved symbol: _ZN15FilePathManagerC2ESsb
18:20:43 Error [MinecraftSymbols] Unresolved symbol: _ZNK15FilePathManager11getRootPathEv
18:20:43 Error [MinecraftSymbols] Unresolved symbol: _ZNK15FilePathManager15getUserDataPathEv
18:20:43 Error [MinecraftSymbols] Unresolved symbol: _ZNK15FilePathManager13getWorldsPathEv
18:20:43 Error [MinecraftSymbols] Unresolved symbol: _ZN15FilePathManager14setPackagePathESs
18:20:43 Error [MinecraftSymbols] Unresolved symbol: _ZNK15FilePathManager14getPackagePathEv
18:20:43 Error [MinecraftSymbols] Unresolved symbol: _ZN15FilePathManager15setSettingsPathESs
18:20:43 Error [MinecraftSymbols] Unresolved symbol: _ZNK15FilePathManager15getSettingsPathEv
18:20:43 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourceLoadManagerC2Ev
18:20:43 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourceLoadManager4syncE16ResourceLoadType
18:20:43 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n3getERKSsRKSt6vectorISsSaISsEE
18:20:43 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n14chooseLanguageERKSs
18:20:43 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n13loadLanguagesER19ResourcePackManagerR19ResourceLoadManagerRKSs
18:20:43 Error [MinecraftSymbols] Unresolved symbol: _ZN5Level16createRandomSeedEv
18:20:43 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettingsC2Ev
18:20:43 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettingsC2ERKS_
18:20:43 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettings15parseSeedStringERKSsj
18:20:43 Error [MinecraftSymbols] Unresolved symbol: _ZN9Minecraft11getCommandsEv
18:20:43 Error [MinecraftSymbols] Unresolved symbol: _ZNK9Minecraft8getLevelEv
18:20:43 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftCommands15setOutputSenderESt10unique_ptrI19CommandOutputSenderSt14default_deleteIS1_EE
18:20:43 Error [MinecraftSymbols] Unresolved symbol: _ZNK17MinecraftCommands23requestCommandExecutionESt10unique_ptrI13CommandOriginSt14default_deleteIS1_EERKSsib
18:20:43 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftEventingC2ERKSs
18:20:43 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftEventing4initEv
18:20:43 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGameC2EiPPc
18:20:43 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGameD2Ev
18:20:43 Error [MinecraftSymbols] Unresolved symbol: _ZNK13MinecraftGame8isInGameEv
18:20:43 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame16requestLeaveGameEbb
18:20:43 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame24doPrimaryClientReadyWorkESt8functionIFvvEE
18:20:43 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame21getPrimaryUserOptionsEv
18:20:43 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame24getPrimaryClientInstanceEv
18:20:43 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame14startLeaveGameEv
18:20:43 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame17continueLeaveGameEv
18:20:43 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame14setTextboxTextERKSsi
18:20:43 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel32navigateToXblConsoleSignInScreenERKSsS1_
18:20:43 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel41navigateToXblConsoleSignInSucceededScreenERKN6Social12SignInResultESt8functionIFvS1_EEb
18:20:43 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel11leaveScreenEv
18:20:43 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social14MultiplayerXBLC2Ev
18:20:43 Error [MinecraftSymbols] Unresolved symbol: _ZTV22NullTextToSpeechClient
18:20:43 Error [MinecraftSymbols] Unresolved symbol: _ZNK7Options13getFullscreenEv
18:20:43 Error [MinecraftSymbols] Unresolved symbol: _ZN7Options13setFullscreenEb
18:20:43 Error [MinecraftSymbols] Unresolved symbol: _ZN15PermissionsFileC2ERKSs
18:20:43 Error [MinecraftSymbols] Unresolved symbol: _ZN19SkinPackKeyProviderC2Ev
18:20:43 Error [MinecraftSymbols] Unresolved symbol: _ZN19PackManifestFactoryC2ER14IPackTelemetry
18:20:43 Error [MinecraftSymbols] Unresolved symbol: _ZN17PackSourceFactoryC2EP7Options
18:20:43 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepositoryC2ER18IMinecraftEventingR19PackManifestFactoryR29IContentAccessibilityProviderP15FilePathManagerR17PackSourceFactoryb
18:20:43 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepository21addWorldResourcePacksERKSs
18:20:43 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepository12refreshPacksEv
18:20:43 Error [MinecraftSymbols] Unresolved symbol: _ZN18ContentTierManagerC2Ev
18:20:43 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManagerC2ESt8functionIFSsvEERK18ContentTierManagerb
18:20:43 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManager8setStackESt10unique_ptrI17ResourcePackStackSt14default_deleteIS1_EE21ResourcePackStackTypeb
18:20:43 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManager17onLanguageChangedEv
18:20:43 Error [MinecraftSymbols] Unresolved symbol: _ZN12PackInstanceC2EP12ResourcePackibP12PackSettings
18:20:43 Error [MinecraftSymbols] Unresolved symbol: _ZTV17ResourcePackStack
18:20:43 Error [MinecraftSymbols] Unresolved symbol: _ZN17ResourcePackStack3addE12PackInstanceRK22ResourcePackRepositoryb
18:20:43 Error [MinecraftSymbols] Unresolved symbol: _ZN22SaveTransactionManagerC2ESt8functionIFvbEE
18:20:43 Error [MinecraftSymbols] Unresolved symbol: _ZN9Scheduler17processCoroutinesENSt6chrono8durationIxSt5ratioILx1ELx1000000000EEEE
18:20:43 Error [MinecraftSymbols] Unresolved symbol: _ZN18MinecraftScheduler6clientEv
18:20:43 Error [MinecraftSymbols] Unresolved symbol: _ZN19ServerCommandOriginC2ERKSsR11ServerLevel
18:20:43 Error [MinecraftSymbols] Unresolved symbol: _ZN16EducationOptionsC2EP19ResourcePackManager
18:20:43 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstanceC2ER13IMinecraftAppR30ServerInstanceEventCoordinator
18:20:43 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance16initializeServerER13IMinecraftAppR9WhitelistP15PermissionsFileP15FilePathManagerNSt6chrono8durationIxSt5ratioILx1ELx1EEEESsSsSs13LevelSettingsib20ConnectionDefinitionbRKSt6vectorISsSaISsEESsRKN3mce4UUIDER18IMinecraftEventingR22ResourcePackRepositoryRK18ContentTierManagerR19ResourcePackManagerSt8functionIFSt10unique_ptrI12LevelStorageSt14default_deleteISZ_EER9SchedulerEERKSsP9LevelDataSsSsSY_I16EducationOptionsS10_IS1B_EEPSV_SX_IFvS18_EES1G_P13ServerMetricsP13DebugEndPoint
18:20:43 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstanceD2Ev
18:20:43 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance17startServerThreadEv
18:20:43 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance13leaveGameSyncEv
18:20:43 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance20queueForServerThreadESt8functionIFvvEE
18:20:43 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12MajorVersionE
18:20:43 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12MinorVersionE
18:20:43 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12PatchVersionE
18:20:43 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants15RevisionVersionE
18:20:43 Error [MinecraftSymbols] Unresolved symbol: _ZNK6Social4User11getLiveUserEv
18:20:43 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social12XboxLiveUser22_handleUISignInNoErrorERN4xbox8services6system14sign_in_resultESt8functionIFvNS_12SignInResultEbEE
18:20:43 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN9GameStore18onStoreInitializedEb
18:20:43 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN9GameStore22onQueryProductsSuccessERKSt6vectorI11ProductInfoSaIS1_EE
18:20:43 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social11UserManager17CreateUserManagerEv
18:20:43 Error [MinecraftSymbols] Unresolved symbol: _ZN2v82V810InitializeEv
18:20:43 Error [MinecraftSymbols] Unresolved symbol: _ZN2v82V818InitializePlatformEPNS_8PlatformE
18:20:43 Error [MinecraftSymbols] Unresolved symbol: _ZNK4pplx4taskIN4xbox8services16xbox_live_resultINS2_6system26token_and_signature_resultEEEE3getEv
18:20:43 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl15getOpenGLVendorEv
18:20:43 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl17getOpenGLRendererEv
18:20:43 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl16getOpenGLVersionEv
18:20:43 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl19getOpenGLExtensionsEv
18:20:43 Error [MinecraftSymbols] Unresolved symbol: _ZN3mce8Platform3OGL12InitBindingsEv
Signal 11 received
Backtrace elements: 5
#0 0   mcpelauncher-client                 0x000e1f2e _ZN12CrashHandler12handleSignalEiPv + 318
#1 1   libsystem_platform.dylib            0xa7ca4bbe _sigtramp + 46
#2 2   ???                                 0xffffffff 0x0 + 4294967295
#3 3   mcpelauncher-client                 0x00028244 main + 10532
#4 4   libdyld.dylib                       0xa7abb051 start + 1
Dumping stack...
#283 HYBRIS (null)+52682752 in libminecraftpe.so+0x0000 [0x323e000]
#327 HYBRIS (null)+52682752 in libminecraftpe.so+0x0000 [0x323e000]
Process exited with unexpected exit code: 6

im not familiar with coding or anything, I've tried uninstalling the game and redownloading and nothing seems to have helped me.

**Comment by alissonlauffer** [comment]
Please update your launcher version to latest

**Comment by bobby4343** [comment]
Is there a link for that?

**Comment by alissonlauffer** [comment]
Download from the link below:
https://mrarm.io/r/mcpelauncher-osx

**Comment by mwxwidmann** [comment]
It still crashes with Minecraft 1.13.0.34. Any help is highly welcome!

Best

Kai

--------

23:46:39 Info [Launcher] Version: client c735370 / manifest eb0bc83
23:46:39 Info [Launcher] CPU: GenuineIntel Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
23:46:39 Info [Launcher] CPU supports SSSE3: YES
23:46:39 Trace [Launcher] Loading hybris libraries
23:46:39 Trace [HybrisUtils] Loaded OS library /Applications/Minecraft Bedrock Launcher.app/Contents/Resources/mcpelauncher/libs/native/libfmod.dylib
23:46:39 Trace [HybrisUtils] Loaded OS library libm.dylib
23:46:39 Error [HybrisUtils] Failed to load OS library libz.so.1
23:46:39 Trace [Launcher] Loading Minecraft library
23:46:40 Info [Launcher] Loaded Minecraft library
23:46:40 Debug [Launcher] Minecraft is at offset 0x3686000
23:46:40 Trace [Launcher] Initializing vtables
23:46:40 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServiceLocatorI11AppPlatformE15mDefaultServiceE
23:46:40 Error [MinecraftSymbols] Unresolved symbol: _ZNK11AppPlatform22getHardwareInformationEv
23:46:40 Error [MinecraftSymbols] Unresolved symbol: _ZN17AppResourceLoaderC1ESt8functionIFN4Core10PathBufferISsEEvEE
23:46:40 Error [MinecraftSymbols] Unresolved symbol: _ZN10Automation16AutomationClientC2ER13IMinecraftApp
23:46:40 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance7getUserEv
23:46:40 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance15_startLeaveGameEv
23:46:40 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance16_syncDestroyGameEv
23:46:40 Error [MinecraftSymbols] Unresolved symbol: _ZNK13CommandOutput11getMessagesEv
23:46:40 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender9translateERKSt6vectorISsSaISsEE
23:46:40 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSenderC2ERN10Automation16AutomationClientE
23:46:40 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSenderD2Ev
23:46:40 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender4sendERK13CommandOriginRK13CommandOutput
23:46:40 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender22registerOutputCallbackERKSt8functionIFvR19AutomationCmdOutputEE
23:46:40 Error [MinecraftSymbols] Unresolved symbol: _ZN30ExternalFileLevelStorageSourceC2EPN4Core15FilePathManagerESt10shared_ptrI22SaveTransactionManagerE
23:46:40 Error [MinecraftSymbols] Unresolved symbol: _ZN30ExternalFileLevelStorageSource18createLevelStorageER9SchedulerRKSsRK15ContentIdentityRK19IContentKeyProvider
23:46:40 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourceLoadManagerC2Ev
23:46:40 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourceLoadManager4syncE16ResourceLoadType
23:46:40 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n3getERKSsRKSt6vectorISsSaISsEE
23:46:40 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n14chooseLanguageERKSs
23:46:40 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n13loadLanguagesER19ResourcePackManagerR19ResourceLoadManagerRKSs
23:46:40 Error [MinecraftSymbols] Unresolved symbol: _ZN5Level16createRandomSeedEv
23:46:40 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettingsC2Ev
23:46:40 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettingsC2ERKS_
23:46:40 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettings15parseSeedStringERKSsj
23:46:40 Error [MinecraftSymbols] Unresolved symbol: _ZN9Minecraft11getCommandsEv
23:46:40 Error [MinecraftSymbols] Unresolved symbol: _ZNK9Minecraft8getLevelEv
23:46:40 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftCommands15setOutputSenderESt10unique_ptrI19CommandOutputSenderSt14default_deleteIS1_EE
23:46:40 Error [MinecraftSymbols] Unresolved symbol: _ZNK17MinecraftCommands23requestCommandExecutionESt10unique_ptrI13CommandOriginSt14default_deleteIS1_EERKSsib
23:46:40 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftEventingC2ERKSs
23:46:40 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftEventing4initEv
23:46:40 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGameD2Ev
23:46:40 Error [MinecraftSymbols] Unresolved symbol: _ZNK13MinecraftGame8isInGameEv
23:46:40 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame16requestLeaveGameEbb
23:46:40 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame24getPrimaryClientInstanceEv
23:46:40 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame14startLeaveGameEv
23:46:40 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame17continueLeaveGameEv
23:46:40 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel32navigateToXblConsoleSignInScreenERKSsS1_
23:46:40 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel41navigateToXblConsoleSignInSucceededScreenERKN6Social12SignInResultESt8functionIFvS1_EEb
23:46:40 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel11leaveScreenEv
23:46:40 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social14MultiplayerXBLC2Ev
23:46:40 Error [MinecraftSymbols] Unresolved symbol: _ZN15PermissionsFileC2ERKSs
23:46:40 Error [MinecraftSymbols] Unresolved symbol: _ZN19SkinPackKeyProviderC2Ev
23:46:40 Error [MinecraftSymbols] Unresolved symbol: _ZN19PackManifestFactoryC2ER14IPackTelemetry
23:46:40 Error [MinecraftSymbols] Unresolved symbol: _ZN17PackSourceFactoryC2Ev
23:46:40 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepositoryC2ER18IMinecraftEventingR19PackManifestFactoryR29IContentAccessibilityProviderPN4Core15FilePathManagerER17PackSourceFactoryb
23:46:40 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepository21addWorldResourcePacksERKN4Core4PathE
23:46:40 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepository12refreshPacksEv
23:46:40 Error [MinecraftSymbols] Unresolved symbol: _ZN18ContentTierManagerC2Ev
23:46:40 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManagerC2ESt8functionIFN4Core10PathBufferISsEEvEERK18ContentTierManagerb
23:46:40 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManager8setStackESt10unique_ptrI17ResourcePackStackSt14default_deleteIS1_EE21ResourcePackStackTypeb
23:46:40 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManager17onLanguageChangedEv
23:46:40 Error [MinecraftSymbols] Unresolved symbol: _ZN12PackInstanceC2EP12ResourcePackibP12PackSettings
23:46:40 Error [MinecraftSymbols] Unresolved symbol: _ZTV17ResourcePackStack
23:46:40 Error [MinecraftSymbols] Unresolved symbol: _ZN17ResourcePackStack3addE12PackInstanceRK22ResourcePackRepositoryb
23:46:40 Error [MinecraftSymbols] Unresolved symbol: _ZN22SaveTransactionManagerC2ESt8functionIFvbEE
23:46:40 Error [MinecraftSymbols] Unresolved symbol: _ZN9Scheduler17processCoroutinesENSt6chrono8durationIxSt5ratioILx1ELx1000000000EEEE
23:46:40 Error [MinecraftSymbols] Unresolved symbol: _ZN18MinecraftScheduler6clientEv
23:46:40 Error [MinecraftSymbols] Unresolved symbol: _ZN19ServerCommandOriginC2ERKSsR11ServerLevel22CommandPermissionLevel
23:46:40 Error [MinecraftSymbols] Unresolved symbol: _ZN16EducationOptionsC2EP19ResourcePackManager
23:46:40 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstanceC2ER13IMinecraftAppR30ServerInstanceEventCoordinator
23:46:40 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance16initializeServerER13IMinecraftAppR9WhitelistP15PermissionsFilePN4Core15FilePathManagerENSt6chrono8durationIxSt5ratioILx1ELx1EEEESsSsSs13LevelSettingsib20ConnectionDefinitionbRKSt6vectorISsSaISsEESsRKN3mce4UUIDER18IMinecraftEventingR22ResourcePackRepositoryRK18ContentTierManagerR19ResourcePackManagerSt8functionIFSt10unique_ptrI12LevelStorageSt14default_deleteIS10_EER9SchedulerEERKSsP9LevelDataSsSsSZ_I16EducationOptionsS11_IS1C_EEPSW_SY_IFvvEES1H_P13ServerMetricsP13DebugEndPointb
23:46:40 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstanceD2Ev
23:46:40 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance17startServerThreadEv
23:46:40 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance13leaveGameSyncEv
23:46:40 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance20queueForServerThreadESt8functionIFvvEE
23:46:40 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12MajorVersionE
23:46:40 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12MinorVersionE
23:46:40 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12PatchVersionE
23:46:40 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants15RevisionVersionE
23:46:40 Error [MinecraftSymbols] Unresolved symbol: _ZNK6Social4User11getLiveUserEv
23:46:40 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social12XboxLiveUser22_handleUISignInNoErrorERN4xbox8services6system14sign_in_resultESt8functionIFvNS_12SignInResultEbEE
23:46:40 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social11UserManager17CreateUserManagerEv
23:46:40 Error [MinecraftSymbols] Unresolved symbol: _ZN2v82V810InitializeEv
23:46:40 Error [MinecraftSymbols] Unresolved symbol: _ZN2v82V818InitializePlatformEPNS_8PlatformE
23:46:40 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl15getOpenGLVendorEv
23:46:40 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl17getOpenGLRendererEv
23:46:40 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl16getOpenGLVersionEv
23:46:40 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl19getOpenGLExtensionsEv
23:46:40 Trace [AppPlatform] Vtable size = 288
23:46:40 Trace [Store] Vtable size = 40
23:46:40 Info [Launcher] Game version: 1.13.0
23:46:40 Info [Launcher] Applying patches
23:46:40 Trace [Patch] Patching - original: 85 83 87 86 131
23:46:40 Trace [Patch] Patching - result: 233 251 153 4 252
23:46:40 Trace [Patch] Patching - original: 83 87 86 131 236
23:46:40 Trace [Patch] Patching - result: 233 11 55 10 252
23:46:40 Trace [Patch] Patching - original: 85 83 87 86 129
23:46:40 Trace [Patch] Patching - result: 233 43 171 92 248
23:46:40 Trace [Patch] Patching - original: 85 83 87 86 129
23:46:40 Trace [Patch] Patching - result: 233 59 201 154 248
23:46:40 Trace [Patch] Patching - original: 85 83 87 86 129
23:46:40 Trace [Patch] Patching - result: 233 203 226 154 248
23:46:40 Trace [Patch] Patching - original: 85 83 87 86 129
23:46:40 Trace [Patch] Patching - result: 233 107 207 154 248
23:46:40 Trace [Patch] Patching - original: 85 83 87 86 129
23:46:40 Trace [Patch] Patching - result: 233 139 54 154 248
23:46:40 Trace [Patch] Patching - original: 85 83 87 86 129
23:46:40 Trace [Patch] Patching - result: 233 155 42 154 248
23:46:40 Trace [Patch] Patching - original: 85 83 87 86 129
23:46:40 Trace [Patch] Patching - result: 233 59 103 156 248
23:46:40 Trace [Patch] Patching - original: 83 87 86 131 236
23:46:40 Trace [Patch] Patching - result: 233 219 200 154 248
23:46:40 Trace [Patch] Patching - original: 85 83 87 86 129
23:46:40 Trace [Patch] Patching - result: 233 155 243 154 248
23:46:40 Trace [Patch] Patching - original: 83 131 236 8 232
23:46:40 Trace [Patch] Patching - result: 233 171 18 188 248
23:46:40 Trace [Patch] Patching - original: 137 76 36 4 137
23:46:40 Trace [Patch] Patching - result: 232 113 99 113 248
23:46:40 Trace [Patch] Patching - original: 36 88 139 65 12
23:46:40 Trace [Patch] Patching - result: 232 124 99 113 248
23:46:40 Trace [Patch] Patching - original: 85 83 87 86 131
23:46:40 Trace [Patch] Patching - result: 233 91 86 87 248
23:46:40 Error [SplitscreenPatch] Not patching splitscreen - incompatible code
Signal 11 received
Backtrace elements: 7
#0 0 mcpelauncher-client 0x000d788e _ZN12CrashHandler12handleSignalEiPv + 318
#1 1 libsystem_platform.dylib 0xa7ce7bae _sigtramp + 46
#2 2 ??? 0xffffffff 0x0 + 4294967295
#3 3 mcpelauncher-client 0x0009d5b6 _ZN11GLCorePatch7installEPv + 662
#4 4 mcpelauncher-client 0x0001da95 main + 10981
#5 5 libdyld.dylib 0xa7afe051 start + 1
#6 6 ??? 0x00000003 0x0 + 3
Dumping stack...
#78 HYBRIS (null)+146310953 in libminecraftpe.so+0x5502729 [0x8b88729]
#128 HYBRIS (null)+67064400 in libminecraftpe.so+0x96f250 [0x3ff5250]
#129 HYBRIS (null)+67064464 in libminecraftpe.so+0x96f290 [0x3ff5290]
#130 HYBRIS (null)+67064480 in libminecraftpe.so+0x96f2a0 [0x3ff52a0]
#131 HYBRIS (null)+67064496 in libminecraftpe.so+0x96f2b0 [0x3ff52b0]
#277 HYBRIS mce::ShaderGroupBase::loadShader(std::string const&, Core::Path const&, Core::Path const&, Core::Path const&)+0 in libminecraftpe.so+0x3afbde0 [0x7181de0]
#386 HYBRIS (null)+57171968 in libminecraftpe.so+0x0000 [0x3686000]
#387 HYBRIS (null)+57171968 in libminecraftpe.so+0x0000 [0x3686000]
Process exited with unexpected exit code: 6


Am 01.11.2019 um 23:44 schrieb Alisson Lauffer <notifications@github.com<mailto:notifications@github.com>>:


Download from the link below:
https://mrarm.io/r/mcpelauncher-osx

**Comment by alissonlauffer** [comment]
Ah, so MacOS launcher is broken

**Comment by bobby4343** [comment]
Do you know if it’ll get fixed?

**Comment by Yazxoi** [comment]
Same problem here. Hope this gets fixed asap.

**Comment by Xeddius** [comment]
> Ah, so the launcher is broken on MacOS. Because on Linux it is working fine.

Actually Linux launcher has issues with downloading new versions right now as it only works with the (x86) apk files right now.

**Comment by bobby4343** [comment]
Is there a place to submit a ticket? Or is it basically just wait and hope someone fixes it

**Comment by Mhowser** [comment]
The devs are working on it, they have limited time and resources so it will
take some time. Please be patient.

**Comment by bobby4343** [comment]
Thank you!

**Comment by Theone1053** [comment]
im having the same problem

**Comment by Mhowser** [comment]
Thank you for the crash report, We are consolidating all issues related to 1.13+ crashes to #165
