### ISSUE TITLE
1.13.0.34 crashes

### ISSUE THREAD

**Issue by Enderskrill** [minecraft-linux/mcpelauncher-manifest#170]
It crashes whenever I open it

13:51:12 Info  [Launcher] Version: client a48cb4c / manifest d9cc8d9
13:51:12 Info  [Launcher] CPU: GenuineIntel Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz
13:51:12 Info  [Launcher] CPU supports SSSE3: YES
13:51:12 Trace [Launcher] Loading hybris libraries
13:51:12 Trace [HybrisUtils] Loaded OS library /Applications/Minecraft Bedrock Launcher.app/Contents/Resources/mcpelauncher/libs/native/libfmod.dylib
13:51:12 Trace [HybrisUtils] Loaded OS library libm.dylib
13:51:12 Error [HybrisUtils] Failed to load OS library libz.so.1
13:51:12 Trace [Launcher] Loading Minecraft library
13:51:12 Info  [Launcher] Loaded Minecraft library
13:51:12 Debug [Launcher] Minecraft is at offset 0x298e000
13:51:12 Error [MinecraftSymbols] Unresolved symbol: _ZN3App4initER10AppContext
13:51:12 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App4quitERKSsS1_
13:51:12 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App6updateEv
13:51:12 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App16setRenderingSizeEii
13:51:12 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App17setUISizeAndScaleEiif
13:51:12 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App10wantToQuitEv
13:51:12 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServiceLocatorI11AppPlatformE15mDefaultServiceE
13:51:12 Error [MinecraftSymbols] Unresolved symbol: _ZNK11AppPlatform22getHardwareInformationEv
13:51:12 Error [MinecraftSymbols] Unresolved symbol: _ZN17AppResourceLoaderC2ESt8functionIFSsvEE
13:51:12 Error [MinecraftSymbols] Unresolved symbol: _ZN10Automation16AutomationClientC2ER13IMinecraftApp
13:51:12 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance7getUserEv
13:51:12 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance15_startLeaveGameEv
13:51:12 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance16_syncDestroyGameEv
13:51:12 Error [MinecraftSymbols] Unresolved symbol: _ZNK13CommandOutput11getMessagesEv
13:51:12 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender9translateERKSt6vectorISsSaISsEE
13:51:12 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSenderC2ERN10Automation16AutomationClientE
13:51:12 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSenderD2Ev
13:51:12 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender4sendERK13CommandOriginRK13CommandOutput
13:51:12 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender22registerOutputCallbackERKSt8functionIFvR19AutomationCmdOutputEE
13:51:12 Error [MinecraftSymbols] Unresolved symbol: _ZN6Common23getGameVersionStringNetEv
13:51:12 Error [MinecraftSymbols] Unresolved symbol: _ZN30ExternalFileLevelStorageSourceC2EP15FilePathManagerSt10shared_ptrI22SaveTransactionManagerE
13:51:12 Error [MinecraftSymbols] Unresolved symbol: _ZN30ExternalFileLevelStorageSource18createLevelStorageER9SchedulerRKSsRK15ContentIdentityRK19IContentKeyProvider
13:51:12 Error [MinecraftSymbols] Unresolved symbol: _ZN15FilePathManagerC2ESsb
13:51:12 Error [MinecraftSymbols] Unresolved symbol: _ZNK15FilePathManager11getRootPathEv
13:51:12 Error [MinecraftSymbols] Unresolved symbol: _ZNK15FilePathManager15getUserDataPathEv
13:51:12 Error [MinecraftSymbols] Unresolved symbol: _ZNK15FilePathManager13getWorldsPathEv
13:51:12 Error [MinecraftSymbols] Unresolved symbol: _ZN15FilePathManager14setPackagePathESs
13:51:12 Error [MinecraftSymbols] Unresolved symbol: _ZNK15FilePathManager14getPackagePathEv
13:51:12 Error [MinecraftSymbols] Unresolved symbol: _ZN15FilePathManager15setSettingsPathESs
13:51:12 Error [MinecraftSymbols] Unresolved symbol: _ZNK15FilePathManager15getSettingsPathEv
13:51:12 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourceLoadManagerC2Ev
13:51:12 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourceLoadManager4syncE16ResourceLoadType
13:51:12 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n3getERKSsRKSt6vectorISsSaISsEE
13:51:12 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n14chooseLanguageERKSs
13:51:12 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n13loadLanguagesER19ResourcePackManagerR19ResourceLoadManagerRKSs
13:51:12 Error [MinecraftSymbols] Unresolved symbol: _ZN5Level16createRandomSeedEv
13:51:12 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettingsC2Ev
13:51:12 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettingsC2ERKS_
13:51:12 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettings15parseSeedStringERKSsj
13:51:12 Error [MinecraftSymbols] Unresolved symbol: _ZN9Minecraft11getCommandsEv
13:51:12 Error [MinecraftSymbols] Unresolved symbol: _ZNK9Minecraft8getLevelEv
13:51:12 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftCommands15setOutputSenderESt10unique_ptrI19CommandOutputSenderSt14default_deleteIS1_EE
13:51:12 Error [MinecraftSymbols] Unresolved symbol: _ZNK17MinecraftCommands23requestCommandExecutionESt10unique_ptrI13CommandOriginSt14default_deleteIS1_EERKSsib
13:51:12 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftEventingC2ERKSs
13:51:12 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftEventing4initEv
13:51:12 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGameC2EiPPc
13:51:12 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGameD2Ev
13:51:12 Error [MinecraftSymbols] Unresolved symbol: _ZNK13MinecraftGame8isInGameEv
13:51:12 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame16requestLeaveGameEbb
13:51:12 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame24doPrimaryClientReadyWorkESt8functionIFvvEE
13:51:12 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame21getPrimaryUserOptionsEv
13:51:12 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame24getPrimaryClientInstanceEv
13:51:12 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame14startLeaveGameEv
13:51:12 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame17continueLeaveGameEv
13:51:12 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame14setTextboxTextERKSsi
13:51:12 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel32navigateToXblConsoleSignInScreenERKSsS1_
13:51:12 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel41navigateToXblConsoleSignInSucceededScreenERKN6Social12SignInResultESt8functionIFvS1_EEb
13:51:12 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel11leaveScreenEv
13:51:12 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social14MultiplayerXBLC2Ev
13:51:12 Error [MinecraftSymbols] Unresolved symbol: _ZTV22NullTextToSpeechClient
13:51:12 Error [MinecraftSymbols] Unresolved symbol: _ZNK7Options13getFullscreenEv
13:51:12 Error [MinecraftSymbols] Unresolved symbol: _ZN7Options13setFullscreenEb
13:51:12 Error [MinecraftSymbols] Unresolved symbol: _ZN15PermissionsFileC2ERKSs
13:51:12 Error [MinecraftSymbols] Unresolved symbol: _ZN19SkinPackKeyProviderC2Ev
13:51:12 Error [MinecraftSymbols] Unresolved symbol: _ZN19PackManifestFactoryC2ER14IPackTelemetry
13:51:12 Error [MinecraftSymbols] Unresolved symbol: _ZN17PackSourceFactoryC2EP7Options
13:51:12 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepositoryC2ER18IMinecraftEventingR19PackManifestFactoryR29IContentAccessibilityProviderP15FilePathManagerR17PackSourceFactoryb
13:51:12 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepository21addWorldResourcePacksERKSs
13:51:12 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepository12refreshPacksEv
13:51:12 Error [MinecraftSymbols] Unresolved symbol: _ZN18ContentTierManagerC2Ev
13:51:12 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManagerC2ESt8functionIFSsvEERK18ContentTierManagerb
13:51:12 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManager8setStackESt10unique_ptrI17ResourcePackStackSt14default_deleteIS1_EE21ResourcePackStackTypeb
13:51:12 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManager17onLanguageChangedEv
13:51:12 Error [MinecraftSymbols] Unresolved symbol: _ZN12PackInstanceC2EP12ResourcePackibP12PackSettings
13:51:12 Error [MinecraftSymbols] Unresolved symbol: _ZTV17ResourcePackStack
13:51:12 Error [MinecraftSymbols] Unresolved symbol: _ZN17ResourcePackStack3addE12PackInstanceRK22ResourcePackRepositoryb
13:51:12 Error [MinecraftSymbols] Unresolved symbol: _ZN22SaveTransactionManagerC2ESt8functionIFvbEE
13:51:12 Error [MinecraftSymbols] Unresolved symbol: _ZN9Scheduler17processCoroutinesENSt6chrono8durationIxSt5ratioILx1ELx1000000000EEEE
13:51:12 Error [MinecraftSymbols] Unresolved symbol: _ZN18MinecraftScheduler6clientEv
13:51:12 Error [MinecraftSymbols] Unresolved symbol: _ZN19ServerCommandOriginC2ERKSsR11ServerLevel
13:51:12 Error [MinecraftSymbols] Unresolved symbol: _ZN16EducationOptionsC2EP19ResourcePackManager
13:51:12 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstanceC2ER13IMinecraftAppR30ServerInstanceEventCoordinator
13:51:12 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance16initializeServerER13IMinecraftAppR9WhitelistP15PermissionsFileP15FilePathManagerNSt6chrono8durationIxSt5ratioILx1ELx1EEEESsSsSs13LevelSettingsib20ConnectionDefinitionbRKSt6vectorISsSaISsEESsRKN3mce4UUIDER18IMinecraftEventingR22ResourcePackRepositoryRK18ContentTierManagerR19ResourcePackManagerSt8functionIFSt10unique_ptrI12LevelStorageSt14default_deleteISZ_EER9SchedulerEERKSsP9LevelDataSsSsSY_I16EducationOptionsS10_IS1B_EEPSV_SX_IFvS18_EES1G_P13ServerMetricsP13DebugEndPoint
13:51:12 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstanceD2Ev
13:51:12 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance17startServerThreadEv
13:51:12 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance13leaveGameSyncEv
13:51:12 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance20queueForServerThreadESt8functionIFvvEE
13:51:12 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12MajorVersionE
13:51:12 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12MinorVersionE
13:51:12 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12PatchVersionE
13:51:12 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants15RevisionVersionE
13:51:12 Error [MinecraftSymbols] Unresolved symbol: _ZNK6Social4User11getLiveUserEv
13:51:12 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social12XboxLiveUser22_handleUISignInNoErrorERN4xbox8services6system14sign_in_resultESt8functionIFvNS_12SignInResultEbEE
13:51:12 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN9GameStore18onStoreInitializedEb
13:51:12 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN9GameStore22onQueryProductsSuccessERKSt6vectorI11ProductInfoSaIS1_EE
13:51:12 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social11UserManager17CreateUserManagerEv
13:51:12 Error [MinecraftSymbols] Unresolved symbol: _ZN2v82V810InitializeEv
13:51:12 Error [MinecraftSymbols] Unresolved symbol: _ZN2v82V818InitializePlatformEPNS_8PlatformE
13:51:12 Error [MinecraftSymbols] Unresolved symbol: _ZNK4pplx4taskIN4xbox8services16xbox_live_resultINS2_6system26token_and_signature_resultEEEE3getEv
13:51:12 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl15getOpenGLVendorEv
13:51:12 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl17getOpenGLRendererEv
13:51:12 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl16getOpenGLVersionEv
13:51:12 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl19getOpenGLExtensionsEv
13:51:12 Error [MinecraftSymbols] Unresolved symbol: _ZN3mce8Platform3OGL12InitBindingsEv
Signal 11 received
Backtrace elements: 5
#0 0   mcpelauncher-client                 0x00168f2e _ZN12CrashHandler12handleSignalEiPv + 318
#1 1   libsystem_platform.dylib            0xa758102b _sigtramp + 43
#2 2   ???                                 0xffffffff 0x0 + 4294967295
#3 3   mcpelauncher-client                 0x000af244 main + 10532
#4 4   libdyld.dylib                       0xa7278611 start + 1
Dumping stack...
#27 HYBRIS (null)+73531476 in libminecraftpe.so+0x1c92054 [0x4620054]
#283 HYBRIS (null)+43573248 in libminecraftpe.so+0x0000 [0x298e000]
#310 HYBRIS (null)+57468078 in libminecraftpe.so+0xd404ae [0x36ce4ae]
#327 HYBRIS (null)+43573248 in libminecraftpe.so+0x0000 [0x298e000]
Process exited with unexpected exit code: 6

**Comment by alissonlauffer** [comment]
@Enderskrill please update your launcher version to latest

**Comment by Mhowser** [comment]
Thank you for the crash report, We are consolidating all issues related to 1.13+ crashes to #165
