### ISSUE TITLE
1.13 crashes on launch- mac

### ISSUE THREAD

**Issue by EggBennny** [minecraft-linux/mcpelauncher-manifest#171]
18:47:04 Info  [Launcher] Version: client a48cb4c / manifest d9cc8d9
18:47:04 Info  [Launcher] CPU: GenuineIntel       Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz
18:47:04 Info  [Launcher] CPU supports SSSE3: YES
18:47:04 Trace [Launcher] Loading hybris libraries
18:47:04 Trace [HybrisUtils] Loaded OS library /Applications/Minecraft Bedrock Launcher.app/Contents/Resources/mcpelauncher/libs/native/libfmod.dylib
18:47:04 Trace [HybrisUtils] Loaded OS library libm.dylib
18:47:04 Error [HybrisUtils] Failed to load OS library libz.so.1
18:47:04 Trace [Launcher] Loading Minecraft library
18:47:05 Info  [Launcher] Loaded Minecraft library
18:47:05 Debug [Launcher] Minecraft is at offset 0x30b2000
18:47:05 Error [MinecraftSymbols] Unresolved symbol: _ZN3App4initER10AppContext
18:47:05 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App4quitERKSsS1_
18:47:05 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App6updateEv
18:47:05 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App16setRenderingSizeEii
18:47:05 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App17setUISizeAndScaleEiif
18:47:05 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App10wantToQuitEv
18:47:05 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServiceLocatorI11AppPlatformE15mDefaultServiceE
18:47:05 Error [MinecraftSymbols] Unresolved symbol: _ZNK11AppPlatform22getHardwareInformationEv
18:47:05 Error [MinecraftSymbols] Unresolved symbol: _ZN17AppResourceLoaderC2ESt8functionIFSsvEE
18:47:05 Error [MinecraftSymbols] Unresolved symbol: _ZN10Automation16AutomationClientC2ER13IMinecraftApp
18:47:05 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance7getUserEv
18:47:05 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance15_startLeaveGameEv
18:47:05 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance16_syncDestroyGameEv
18:47:05 Error [MinecraftSymbols] Unresolved symbol: _ZNK13CommandOutput11getMessagesEv
18:47:05 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender9translateERKSt6vectorISsSaISsEE
18:47:05 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSenderC2ERN10Automation16AutomationClientE
18:47:05 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSenderD2Ev
18:47:05 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender4sendERK13CommandOriginRK13CommandOutput
18:47:05 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender22registerOutputCallbackERKSt8functionIFvR19AutomationCmdOutputEE
18:47:05 Error [MinecraftSymbols] Unresolved symbol: _ZN6Common23getGameVersionStringNetEv
18:47:05 Error [MinecraftSymbols] Unresolved symbol: _ZN30ExternalFileLevelStorageSourceC2EP15FilePathManagerSt10shared_ptrI22SaveTransactionManagerE
18:47:05 Error [MinecraftSymbols] Unresolved symbol: _ZN30ExternalFileLevelStorageSource18createLevelStorageER9SchedulerRKSsRK15ContentIdentityRK19IContentKeyProvider
18:47:05 Error [MinecraftSymbols] Unresolved symbol: _ZN15FilePathManagerC2ESsb
18:47:05 Error [MinecraftSymbols] Unresolved symbol: _ZNK15FilePathManager11getRootPathEv
18:47:05 Error [MinecraftSymbols] Unresolved symbol: _ZNK15FilePathManager15getUserDataPathEv
18:47:05 Error [MinecraftSymbols] Unresolved symbol: _ZNK15FilePathManager13getWorldsPathEv
18:47:05 Error [MinecraftSymbols] Unresolved symbol: _ZN15FilePathManager14setPackagePathESs
18:47:05 Error [MinecraftSymbols] Unresolved symbol: _ZNK15FilePathManager14getPackagePathEv
18:47:05 Error [MinecraftSymbols] Unresolved symbol: _ZN15FilePathManager15setSettingsPathESs
18:47:05 Error [MinecraftSymbols] Unresolved symbol: _ZNK15FilePathManager15getSettingsPathEv
18:47:05 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourceLoadManagerC2Ev
18:47:05 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourceLoadManager4syncE16ResourceLoadType
18:47:05 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n3getERKSsRKSt6vectorISsSaISsEE
18:47:05 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n14chooseLanguageERKSs
18:47:05 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n13loadLanguagesER19ResourcePackManagerR19ResourceLoadManagerRKSs
18:47:05 Error [MinecraftSymbols] Unresolved symbol: _ZN5Level16createRandomSeedEv
18:47:05 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettingsC2Ev
18:47:05 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettingsC2ERKS_
18:47:05 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettings15parseSeedStringERKSsj
18:47:05 Error [MinecraftSymbols] Unresolved symbol: _ZN9Minecraft11getCommandsEv
18:47:05 Error [MinecraftSymbols] Unresolved symbol: _ZNK9Minecraft8getLevelEv
18:47:05 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftCommands15setOutputSenderESt10unique_ptrI19CommandOutputSenderSt14default_deleteIS1_EE
18:47:05 Error [MinecraftSymbols] Unresolved symbol: _ZNK17MinecraftCommands23requestCommandExecutionESt10unique_ptrI13CommandOriginSt14default_deleteIS1_EERKSsib
18:47:05 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftEventingC2ERKSs
18:47:05 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftEventing4initEv
18:47:05 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGameC2EiPPc
18:47:05 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGameD2Ev
18:47:05 Error [MinecraftSymbols] Unresolved symbol: _ZNK13MinecraftGame8isInGameEv
18:47:05 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame16requestLeaveGameEbb
18:47:05 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame24doPrimaryClientReadyWorkESt8functionIFvvEE
18:47:05 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame21getPrimaryUserOptionsEv
18:47:05 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame24getPrimaryClientInstanceEv
18:47:05 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame14startLeaveGameEv
18:47:05 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame17continueLeaveGameEv
18:47:05 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame14setTextboxTextERKSsi
18:47:05 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel32navigateToXblConsoleSignInScreenERKSsS1_
18:47:05 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel41navigateToXblConsoleSignInSucceededScreenERKN6Social12SignInResultESt8functionIFvS1_EEb
18:47:05 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel11leaveScreenEv
18:47:05 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social14MultiplayerXBLC2Ev
18:47:05 Error [MinecraftSymbols] Unresolved symbol: _ZTV22NullTextToSpeechClient
18:47:05 Error [MinecraftSymbols] Unresolved symbol: _ZNK7Options13getFullscreenEv
18:47:05 Error [MinecraftSymbols] Unresolved symbol: _ZN7Options13setFullscreenEb
18:47:05 Error [MinecraftSymbols] Unresolved symbol: _ZN15PermissionsFileC2ERKSs
18:47:05 Error [MinecraftSymbols] Unresolved symbol: _ZN19SkinPackKeyProviderC2Ev
18:47:05 Error [MinecraftSymbols] Unresolved symbol: _ZN19PackManifestFactoryC2ER14IPackTelemetry
18:47:05 Error [MinecraftSymbols] Unresolved symbol: _ZN17PackSourceFactoryC2EP7Options
18:47:05 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepositoryC2ER18IMinecraftEventingR19PackManifestFactoryR29IContentAccessibilityProviderP15FilePathManagerR17PackSourceFactoryb
18:47:05 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepository21addWorldResourcePacksERKSs
18:47:05 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepository12refreshPacksEv
18:47:05 Error [MinecraftSymbols] Unresolved symbol: _ZN18ContentTierManagerC2Ev
18:47:05 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManagerC2ESt8functionIFSsvEERK18ContentTierManagerb
18:47:05 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManager8setStackESt10unique_ptrI17ResourcePackStackSt14default_deleteIS1_EE21ResourcePackStackTypeb
18:47:05 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManager17onLanguageChangedEv
18:47:05 Error [MinecraftSymbols] Unresolved symbol: _ZN12PackInstanceC2EP12ResourcePackibP12PackSettings
18:47:05 Error [MinecraftSymbols] Unresolved symbol: _ZTV17ResourcePackStack
18:47:05 Error [MinecraftSymbols] Unresolved symbol: _ZN17ResourcePackStack3addE12PackInstanceRK22ResourcePackRepositoryb
18:47:05 Error [MinecraftSymbols] Unresolved symbol: _ZN22SaveTransactionManagerC2ESt8functionIFvbEE
18:47:05 Error [MinecraftSymbols] Unresolved symbol: _ZN9Scheduler17processCoroutinesENSt6chrono8durationIxSt5ratioILx1ELx1000000000EEEE
18:47:05 Error [MinecraftSymbols] Unresolved symbol: _ZN18MinecraftScheduler6clientEv
18:47:05 Error [MinecraftSymbols] Unresolved symbol: _ZN19ServerCommandOriginC2ERKSsR11ServerLevel
18:47:05 Error [MinecraftSymbols] Unresolved symbol: _ZN16EducationOptionsC2EP19ResourcePackManager
18:47:05 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstanceC2ER13IMinecraftAppR30ServerInstanceEventCoordinator
18:47:05 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance16initializeServerER13IMinecraftAppR9WhitelistP15PermissionsFileP15FilePathManagerNSt6chrono8durationIxSt5ratioILx1ELx1EEEESsSsSs13LevelSettingsib20ConnectionDefinitionbRKSt6vectorISsSaISsEESsRKN3mce4UUIDER18IMinecraftEventingR22ResourcePackRepositoryRK18ContentTierManagerR19ResourcePackManagerSt8functionIFSt10unique_ptrI12LevelStorageSt14default_deleteISZ_EER9SchedulerEERKSsP9LevelDataSsSsSY_I16EducationOptionsS10_IS1B_EEPSV_SX_IFvS18_EES1G_P13ServerMetricsP13DebugEndPoint
18:47:05 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstanceD2Ev
18:47:05 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance17startServerThreadEv
18:47:05 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance13leaveGameSyncEv
18:47:05 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance20queueForServerThreadESt8functionIFvvEE
18:47:05 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12MajorVersionE
18:47:05 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12MinorVersionE
18:47:05 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12PatchVersionE
18:47:05 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants15RevisionVersionE
18:47:05 Error [MinecraftSymbols] Unresolved symbol: _ZNK6Social4User11getLiveUserEv
18:47:05 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social12XboxLiveUser22_handleUISignInNoErrorERN4xbox8services6system14sign_in_resultESt8functionIFvNS_12SignInResultEbEE
18:47:05 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN9GameStore18onStoreInitializedEb
18:47:05 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN9GameStore22onQueryProductsSuccessERKSt6vectorI11ProductInfoSaIS1_EE
18:47:05 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social11UserManager17CreateUserManagerEv
18:47:05 Error [MinecraftSymbols] Unresolved symbol: _ZN2v82V810InitializeEv
18:47:05 Error [MinecraftSymbols] Unresolved symbol: _ZN2v82V818InitializePlatformEPNS_8PlatformE
18:47:05 Error [MinecraftSymbols] Unresolved symbol: _ZNK4pplx4taskIN4xbox8services16xbox_live_resultINS2_6system26token_and_signature_resultEEEE3getEv
18:47:05 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl15getOpenGLVendorEv
18:47:05 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl17getOpenGLRendererEv
18:47:05 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl16getOpenGLVersionEv
18:47:05 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl19getOpenGLExtensionsEv
18:47:05 Error [MinecraftSymbols] Unresolved symbol: _ZN3mce8Platform3OGL12InitBindingsEv
Signal 11 received
Backtrace elements: 5
#0 0   mcpelauncher-client                 0x0014af2e _ZN12CrashHandler12handleSignalEiPv + 318
#1 1   libsystem_platform.dylib            0xa7d90bbe _sigtramp + 46
#2 2   ???                                 0xffffffff 0x0 + 4294967295
#3 3   mcpelauncher-client                 0x00091244 main + 10532
#4 4   libdyld.dylib                       0xa7ba7051 start + 1
Dumping stack...
#283 HYBRIS (null)+51060736 in libminecraftpe.so+0x0000 [0x30b2000]
#327 HYBRIS (null)+51060736 in libminecraftpe.so+0x0000 [0x30b2000]
Process exited with unexpected exit code: 6

**Comment by proartti** [comment]
I just updated and still get the same error/crash.

**Comment by ChristopherHX** [comment]
If you currently want to play Minecraft 1.13.0.34 on Mac use the dmg from https://github.com/ChristopherHX/mcpelauncher-manifest/tree/MacOs1.3
I'm working on merge it back, takes some days / weeks.

**Comment by proartti** [comment]
I did my best but could not build the client. A lot of dependencies and build errors to handle... I will wait for you guys to make the magic happens. :)

**Comment by ChristopherHX** [comment]
You can't build it easyly
I had written a wrong link use the DMG https://github.com/ChristopherHX/mcpelauncher-manifest/releases/tag/MacOs1.3

**Comment by proartti** [comment]
It works! Thanks @ChristopherHX you are the best! (the launcher still shows the 'non zero error' after I quit the game, but I am able to play with no problems)

**Comment by EggBennny** [comment]
@ChristopherHX works perfectly! thanks so much
