### ISSUE TITLE
Minecraft 1.13.0.34

### ISSUE THREAD

**Issue by CareerChannel** [minecraft-linux/mcpelauncher-manifest#174]
After Update Minecraft Crashes

**Comment by alissonlauffer** [comment]
> After Update Minecraft Crashes

It is working fine here (on Arch Linux, built from AUR)

**Comment by Yuperness** [comment]
@alissonlauffer , Exactly how do i update my launcher? bc i clicked on update launcher, installed it but it didn't change anything.

**Comment by alissonlauffer** [comment]
> @alissonlauffer , Exactly how do i update my launcher? bc i clicked on update launcher, installed it but it didn't change anything.

Follow the guide here https://mcpelauncher.readthedocs.io/en/latest/getting_started.html

Please note that the launcher is not compatible with 1.14 betas.

**Comment by dwoodworker** [comment]
I am also experiencing the launcher crashing as soon as I try to start it.  I have followed the instructions from the getting_started.html page and it is the same file as before.  Like Yupperness indicated.

**Comment by osirisguitar** [comment]
I've tried both updating through the launcher itself and reinstalling - does not work on MacOS with 1.13.

**Comment by ChristopherHX** [comment]
@osirisguitar If you currently want to play Minecraft 1.13.0.34 on Mac use the dmg from https://github.com/ChristopherHX/mcpelauncher-manifest/tree/MacOs1.3
I'm working on merge it back, takes some days / weeks

All others should reinstall the launcher if updating not works

**Comment by osirisguitar** [comment]
> @osirisguitar If you currently want to play Minecraft 1.13.0.34 on Mac use the dmg from https://github.com/ChristopherHX/mcpelauncher-manifest/releases/tag/MacOs1.3
> I'm working on merge it back, takes some days / weeks **(Update Link was wrong)**

You're my hero! :-D

**Comment by Yuperness** [comment]
Thank you!
