### ISSUE TITLE
Crashes on 1.13.0.34

### ISSUE THREAD

**Issue by Kariosphere** [minecraft-linux/mcpelauncher-manifest#180]
When I try to launch it this error code shows up:
dyld: Library not loaded: /System/Library/PrivateFrameworks/SkyLight.framework/Versions/A/SkyLight
  Referenced from: /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
  Reason: no suitable image found.  Did find:
	/System/Library/PrivateFrameworks/SkyLight.framework/Versions/A/SkyLight: mach-o, but wrong architecture
	/System/Library/PrivateFrameworks/SkyLight.framework/Versions/A/SkyLight: stat() failed with errno=1
	/System/Library/PrivateFrameworks/SkyLight.framework/Versions/A/SkyLight: mach-o, but wrong architecture
Process exited with unexpected exit code: 6

**Comment by rohinarya12** [comment]
Same here

**Comment by KokoDark** [comment]
Same

**Comment by anaypatel** [comment]
same here

**Comment by CareerChannel** [comment]
same here, even version 1.11 is not playable

**Comment by ChristopherHX** [comment]
What are you doing with your MacOs, I think you all installed a graphics patch [from Catalina](https://forums.macrumors.com/threads/macos-10-14-mojave-on-unsupported-macs-thread.2121473/page-701)
**and** 1.13 on MacOs (10.12 - 10.14) currently need my special DMG (will be merged soon to this repo) https://github.com/ChristopherHX/mcpelauncher-manifest/releases/tag/MacOs1.3

**Comment by Craftstar15** [comment]
Same here only 1.12 will work. 1.13 Will not!

**Comment by aeuxial** [comment]
yeah 1.12 does work for me but every time I launch 1.13 it will crash instantly

**Comment by ChristopherHX** [comment]
Orginal issue not the same
Please download a newer launcher or only play older Minecraft Versions
Please read https://github.com/minecraft-linux/mcpelauncher-manifest/issues/165#issuecomment-560015903 to upgrade to `my fork` or `ng preview`

The original issue shouldn't be in the new 64bit of `ng preview`, as it only applies to the 32bit only version.
