### ISSUE TITLE
Minecraft 1.13.1.5 will not run

### ISSUE THREAD

**Issue by ChristopherHX** [minecraft-linux/mcpelauncher-manifest#186]
This launcher will need an update to support it, but will likly take more than a week.
**Downgrade to 1.13.0.34**

**Comment by MissionApollo7** [comment]
How do I roll back to 1.13.0.34? I updated the game and deleted the old version before checking if it worked, and there's no option for it in the dropdown list.

**Comment by ChristopherHX** [comment]
@MissionApollo7 Then you can only rollback using this from discord Pin at `#general`
`yo, workaround for people having issues signing in to google:
  - get the aurora store either on fdroid or here: https://forum.xda-developers.com/android/apps-games/galaxy-playstore-alternative-t3739733
  - before signing in, go to settings -> spoof -> spoof device -> ASUS MeMO Pad 7 x86 -> Apply
  - now sign in with the account that owns minecraft. (this may take a few tries, be patient)
      - if you have 2fa enabled, you will need to generate an app password to use instead of your normal one.
  - find minecraft
  - click the three dots in the top right -> manual download
  - ensure the default build number matches the latest x86 version code listed on the version list above this post (type !version to get a new one)
  - Download
  - Now you have an x86 apk available at /sdcard/Aurora/`
But I don't know its versioncode as the !version was not working

**Comment by Mhowser** [comment]
Thank you for the crash report, We are consolidating all issues related to 1.13+ crashes to #165
