### ISSUE TITLE
Minecraft 1.13.1.5 instant crashes when launched

### ISSUE THREAD

**Issue by aeuxial** [minecraft-linux/mcpelauncher-manifest#189]
17:39:44 Info  [Launcher] Version: client c735370 / manifest eb0bc83
17:39:44 Info  [Launcher] CPU: GenuineIntel Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz
17:39:44 Info  [Launcher] CPU supports SSSE3: YES
17:39:44 Trace [Launcher] Loading hybris libraries
17:39:44 Trace [HybrisUtils] Loaded OS library /Applications/Minecraft Bedrock Launcher.app/Contents/Resources/mcpelauncher/libs/native/libfmod.dylib
17:39:44 Trace [HybrisUtils] Loaded OS library libm.dylib
17:39:44 Error [HybrisUtils] Failed to load OS library libz.so.1
17:39:44 Trace [Launcher] Loading Minecraft library
17:39:44 Info  [Launcher] Loaded Minecraft library
17:39:44 Debug [Launcher] Minecraft is at offset 0x2fb0000
17:39:44 Trace [Launcher] Initializing vtables
17:39:44 Error [MinecraftSymbols] Unresolved symbol: _ZN3App4initER10AppContext
17:39:44 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App4quitERKSsS1_
17:39:44 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App6updateEv
17:39:44 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App16setRenderingSizeEii
17:39:44 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App17setUISizeAndScaleEiif
17:39:44 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App10wantToQuitEv
17:39:44 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServiceLocatorI11AppPlatformE15mDefaultServiceE
17:39:44 Error [MinecraftSymbols] Unresolved symbol: _ZNK11AppPlatform22getHardwareInformationEv
17:39:44 Error [MinecraftSymbols] Unresolved symbol: _ZN17AppResourceLoaderC1ESt8functionIFN4Core10PathBufferISsEEvEE
17:39:44 Error [MinecraftSymbols] Unresolved symbol: _ZN10Automation16AutomationClientC2ER13IMinecraftApp
17:39:44 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance7getUserEv
17:39:44 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance15_startLeaveGameEv
17:39:44 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance16_syncDestroyGameEv
17:39:44 Error [MinecraftSymbols] Unresolved symbol: _ZNK13CommandOutput11getMessagesEv
17:39:44 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender9translateERKSt6vectorISsSaISsEE
17:39:44 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSenderC2ERN10Automation16AutomationClientE
17:39:44 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSenderD2Ev
17:39:44 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender4sendERK13CommandOriginRK13CommandOutput
17:39:44 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender22registerOutputCallbackERKSt8functionIFvR19AutomationCmdOutputEE
17:39:44 Error [MinecraftSymbols] Unresolved symbol: _ZN6Common23getGameVersionStringNetEv
17:39:44 Error [MinecraftSymbols] Unresolved symbol: _ZN30ExternalFileLevelStorageSourceC2EPN4Core15FilePathManagerESt10shared_ptrI22SaveTransactionManagerE
17:39:44 Error [MinecraftSymbols] Unresolved symbol: _ZN30ExternalFileLevelStorageSource18createLevelStorageER9SchedulerRKSsRK15ContentIdentityRK19IContentKeyProvider
17:39:44 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourceLoadManagerC2Ev
17:39:44 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourceLoadManager4syncE16ResourceLoadType
17:39:44 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n3getERKSsRKSt6vectorISsSaISsEE
17:39:44 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n14chooseLanguageERKSs
17:39:44 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n13loadLanguagesER19ResourcePackManagerR19ResourceLoadManagerRKSs
17:39:44 Error [MinecraftSymbols] Unresolved symbol: _ZN5Level16createRandomSeedEv
17:39:44 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettingsC2Ev
17:39:44 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettingsC2ERKS_
17:39:44 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettings15parseSeedStringERKSsj
17:39:44 Error [MinecraftSymbols] Unresolved symbol: _ZN9Minecraft11getCommandsEv
17:39:44 Error [MinecraftSymbols] Unresolved symbol: _ZNK9Minecraft8getLevelEv
17:39:44 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftCommands15setOutputSenderESt10unique_ptrI19CommandOutputSenderSt14default_deleteIS1_EE
17:39:44 Error [MinecraftSymbols] Unresolved symbol: _ZNK17MinecraftCommands23requestCommandExecutionESt10unique_ptrI13CommandOriginSt14default_deleteIS1_EERKSsib
17:39:44 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftEventingC2ERKSs
17:39:44 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftEventing4initEv
17:39:44 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGameC2EiPPc
17:39:44 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGameD2Ev
17:39:44 Error [MinecraftSymbols] Unresolved symbol: _ZNK13MinecraftGame8isInGameEv
17:39:44 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame16requestLeaveGameEbb
17:39:44 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame24doPrimaryClientReadyWorkESt8functionIFvvEE
17:39:44 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame21getPrimaryUserOptionsEv
17:39:44 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame24getPrimaryClientInstanceEv
17:39:44 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame14startLeaveGameEv
17:39:44 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame17continueLeaveGameEv
17:39:44 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame14setTextboxTextERKSsi
17:39:44 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel32navigateToXblConsoleSignInScreenERKSsS1_
17:39:44 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel41navigateToXblConsoleSignInSucceededScreenERKN6Social12SignInResultESt8functionIFvS1_EEb
17:39:44 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel11leaveScreenEv
17:39:44 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social14MultiplayerXBLC2Ev
17:39:44 Error [MinecraftSymbols] Unresolved symbol: _ZTV22NullTextToSpeechClient
17:39:44 Error [MinecraftSymbols] Unresolved symbol: _ZNK7Options13getFullscreenEv
17:39:44 Error [MinecraftSymbols] Unresolved symbol: _ZN7Options13setFullscreenEb
17:39:44 Error [MinecraftSymbols] Unresolved symbol: _ZN15PermissionsFileC2ERKSs
17:39:44 Error [MinecraftSymbols] Unresolved symbol: _ZN19SkinPackKeyProviderC2Ev
17:39:44 Error [MinecraftSymbols] Unresolved symbol: _ZN19PackManifestFactoryC2ER14IPackTelemetry
17:39:44 Error [MinecraftSymbols] Unresolved symbol: _ZN17PackSourceFactoryC2Ev
17:39:44 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepositoryC2ER18IMinecraftEventingR19PackManifestFactoryR29IContentAccessibilityProviderPN4Core15FilePathManagerER17PackSourceFactoryb
17:39:44 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepository21addWorldResourcePacksERKN4Core4PathE
17:39:44 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepository12refreshPacksEv
17:39:44 Error [MinecraftSymbols] Unresolved symbol: _ZN18ContentTierManagerC2Ev
17:39:44 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManagerC2ESt8functionIFN4Core10PathBufferISsEEvEERK18ContentTierManagerb
17:39:44 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManager8setStackESt10unique_ptrI17ResourcePackStackSt14default_deleteIS1_EE21ResourcePackStackTypeb
17:39:44 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManager17onLanguageChangedEv
17:39:44 Error [MinecraftSymbols] Unresolved symbol: _ZN12PackInstanceC2EP12ResourcePackibP12PackSettings
17:39:44 Error [MinecraftSymbols] Unresolved symbol: _ZTV17ResourcePackStack
17:39:44 Error [MinecraftSymbols] Unresolved symbol: _ZN17ResourcePackStack3addE12PackInstanceRK22ResourcePackRepositoryb
17:39:44 Error [MinecraftSymbols] Unresolved symbol: _ZN22SaveTransactionManagerC2ESt8functionIFvbEE
17:39:44 Error [MinecraftSymbols] Unresolved symbol: _ZN9Scheduler17processCoroutinesENSt6chrono8durationIxSt5ratioILx1ELx1000000000EEEE
17:39:44 Error [MinecraftSymbols] Unresolved symbol: _ZN18MinecraftScheduler6clientEv
17:39:44 Error [MinecraftSymbols] Unresolved symbol: _ZN19ServerCommandOriginC2ERKSsR11ServerLevel22CommandPermissionLevel
17:39:44 Error [MinecraftSymbols] Unresolved symbol: _ZN16EducationOptionsC2EP19ResourcePackManager
17:39:44 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstanceC2ER13IMinecraftAppR30ServerInstanceEventCoordinator
17:39:44 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance16initializeServerER13IMinecraftAppR9WhitelistP15PermissionsFilePN4Core15FilePathManagerENSt6chrono8durationIxSt5ratioILx1ELx1EEEESsSsSs13LevelSettingsib20ConnectionDefinitionbRKSt6vectorISsSaISsEESsRKN3mce4UUIDER18IMinecraftEventingR22ResourcePackRepositoryRK18ContentTierManagerR19ResourcePackManagerSt8functionIFSt10unique_ptrI12LevelStorageSt14default_deleteIS10_EER9SchedulerEERKSsP9LevelDataSsSsSZ_I16EducationOptionsS11_IS1C_EEPSW_SY_IFvvEES1H_P13ServerMetricsP13DebugEndPointb
17:39:44 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstanceD2Ev
17:39:44 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance17startServerThreadEv
17:39:44 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance13leaveGameSyncEv
17:39:44 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance20queueForServerThreadESt8functionIFvvEE
17:39:44 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12MajorVersionE
17:39:44 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12MinorVersionE
17:39:44 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12PatchVersionE
17:39:44 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants15RevisionVersionE
17:39:44 Error [MinecraftSymbols] Unresolved symbol: _ZNK6Social4User11getLiveUserEv
17:39:44 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social12XboxLiveUser22_handleUISignInNoErrorERN4xbox8services6system14sign_in_resultESt8functionIFvNS_12SignInResultEbEE
17:39:44 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN9GameStore18onStoreInitializedEb
17:39:44 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN9GameStore22onQueryProductsSuccessERKSt6vectorI11ProductInfoSaIS1_EE
17:39:44 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social11UserManager17CreateUserManagerEv
17:39:44 Error [MinecraftSymbols] Unresolved symbol: _ZN2v82V810InitializeEv
17:39:44 Error [MinecraftSymbols] Unresolved symbol: _ZN2v82V818InitializePlatformEPNS_8PlatformE
17:39:44 Error [MinecraftSymbols] Unresolved symbol: _ZNK4pplx4taskIN4xbox8services16xbox_live_resultINS2_6system26token_and_signature_resultEEEE3getEv
17:39:44 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl15getOpenGLVendorEv
17:39:44 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl17getOpenGLRendererEv
17:39:44 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl16getOpenGLVersionEv
17:39:44 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl19getOpenGLExtensionsEv
17:39:44 Error [MinecraftSymbols] Unresolved symbol: _ZN3mce8Platform3OGL12InitBindingsEv
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: Found no way to resolve library version, Minecraft version likely unsupported
Signal 6 received
Backtrace elements: 14
#0 0   mcpelauncher-client                 0x0012488e _ZN12CrashHandler12handleSignalEiPv + 318
#1 1   libsystem_platform.dylib            0xa7ca4bbe _sigtramp + 46
#2 2   ???                                 0xffffffff 0x0 + 4294967295
#3 3   libsystem_c.dylib                   0xa7b5e80e abort + 133
#4 4   libc++abi.dylib                     0xa5a23177 __cxa_bad_cast + 0
#5 5   libc++abi.dylib                     0xa5a2331f _ZL25default_terminate_handlerv + 232
#6 6   libc++abi.dylib                     0xa5a2e1fd _ZSt11__terminatePFvvE + 14
#7 7   libc++abi.dylib                     0xa5a2dfbc __cxa_get_exception_ptr + 0
#8 8   libc++abi.dylib                     0xa5a21a01 __cxa_get_globals + 0
#9 9   mcpelauncher-client                 0x001a018c _Z21minecraft_get_versionPiS_S_S_ + 396
#10 10  mcpelauncher-client                 0x001267f9 _ZN16MinecraftVersion4initEv + 57
#11 11  mcpelauncher-client                 0x00125f85 _ZN14MinecraftUtils18initSymbolBindingsEPv + 69
#12 12  mcpelauncher-client                 0x0006a790 main + 10208
#13 13  libdyld.dylib                       0xa7abb051 start + 1
Dumping stack...
#467 HYBRIS renoir::GeometryGenerator::GenerateRectBordersForRRects(renoir::ScratchBufferManager*, renoir::GeometryGenerator::RRectStrokesToDraw const*, unsigned int, renoir::GeometryGenerator::DrawInfo&)+2987 in libminecraftpe.so+0x4a5250b [0x7a0250b]
#598 HYBRIS vtable for xbox::services::local_config+8 in libminecraftpe.so+0x7260f60 [0xa210f60]
#599 HYBRIS vtable for xbox::services::local_config+8 in libminecraftpe.so+0x7260f60 [0xa210f60]
#627 HYBRIS (null)+50003968 in libminecraftpe.so+0x0000 [0x2fb0000]
#674 HYBRIS (null)+50003968 in libminecraftpe.so+0x0000 [0x2fb0000]
#675 HYBRIS (null)+50003968 in libminecraftpe.so+0x0000 [0x2fb0000]
Process exited with unexpected exit code: 6

**Comment by Mhowser** [comment]
Thank you for the crash report, We are consolidating all issues related to 1.13+ crashes to #165
