### ISSUE TITLE
Crash after new uptade (1.13.1.5)

### ISSUE THREAD

**Issue by Drodash** [minecraft-linux/mcpelauncher-manifest#190]
02:48:25 Info  [Launcher] Version: client db48703 / manifest 51bcb52
02:48:25 Info  [Launcher] CPU: GenuineIntel        Intel(R) Core(TM) i7-2640M CPU @ 2.80GHz
02:48:25 Info  [Launcher] CPU supports SSSE3: YES
02:48:25 Trace [Launcher] Loading hybris libraries
02:48:25 Trace [HybrisUtils] Loaded OS library /Applications/Minecraft Bedrock Launcher.app/Contents/Resources/mcpelauncher/libs/native/libfmod.dylib
02:48:25 Trace [HybrisUtils] Loaded OS library libm.dylib
02:48:25 Error [HybrisUtils] Failed to load OS library libz.so.1
02:48:25 Trace [Launcher] Loading Minecraft library
02:48:26 Info  [Launcher] Loaded Minecraft library
02:48:26 Debug [Launcher] Minecraft is at offset 0x2d03000
02:48:26 Trace [Launcher] Initializing vtables
02:48:26 Error [MinecraftSymbols] Unresolved symbol: _ZN3App4initER10AppContext
02:48:26 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App4quitERKSsS1_
02:48:26 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App6updateEv
02:48:26 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App16setRenderingSizeEii
02:48:26 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App17setUISizeAndScaleEiif
02:48:26 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App10wantToQuitEv
02:48:26 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServiceLocatorI11AppPlatformE15mDefaultServiceE
02:48:26 Error [MinecraftSymbols] Unresolved symbol: _ZNK11AppPlatform22getHardwareInformationEv
02:48:26 Error [MinecraftSymbols] Unresolved symbol: _ZN17AppResourceLoaderC1ESt8functionIFN4Core10PathBufferISsEEvEE
02:48:26 Error [MinecraftSymbols] Unresolved symbol: _ZN10Automation16AutomationClientC2ER13IMinecraftApp
02:48:26 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance7getUserEv
02:48:26 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance15_startLeaveGameEv
02:48:26 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance16_syncDestroyGameEv
02:48:26 Error [MinecraftSymbols] Unresolved symbol: _ZNK13CommandOutput11getMessagesEv
02:48:26 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender9translateERKSt6vectorISsSaISsEE
02:48:26 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSenderC2ERN10Automation16AutomationClientE
02:48:26 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSenderD2Ev
02:48:26 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender4sendERK13CommandOriginRK13CommandOutput
02:48:26 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender22registerOutputCallbackERKSt8functionIFvR19AutomationCmdOutputEE
02:48:26 Error [MinecraftSymbols] Unresolved symbol: _ZN6Common23getGameVersionStringNetEv
02:48:26 Error [MinecraftSymbols] Unresolved symbol: _ZN30ExternalFileLevelStorageSourceC2EPN4Core15FilePathManagerESt10shared_ptrI22SaveTransactionManagerE
02:48:26 Error [MinecraftSymbols] Unresolved symbol: _ZN30ExternalFileLevelStorageSource18createLevelStorageER9SchedulerRKSsRK15ContentIdentityRK19IContentKeyProvider
02:48:26 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourceLoadManagerC2Ev
02:48:26 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourceLoadManager4syncE16ResourceLoadType
02:48:26 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n3getERKSsRKSt6vectorISsSaISsEE
02:48:26 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n14chooseLanguageERKSs
02:48:26 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n13loadLanguagesER19ResourcePackManagerR19ResourceLoadManagerRKSs
02:48:26 Error [MinecraftSymbols] Unresolved symbol: _ZN5Level16createRandomSeedEv
02:48:26 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettingsC2Ev
02:48:26 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettingsC2ERKS_
02:48:26 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettings15parseSeedStringERKSsj
02:48:26 Error [MinecraftSymbols] Unresolved symbol: _ZN9Minecraft11getCommandsEv
02:48:26 Error [MinecraftSymbols] Unresolved symbol: _ZNK9Minecraft8getLevelEv
02:48:26 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftCommands15setOutputSenderESt10unique_ptrI19CommandOutputSenderSt14default_deleteIS1_EE
02:48:26 Error [MinecraftSymbols] Unresolved symbol: _ZNK17MinecraftCommands23requestCommandExecutionESt10unique_ptrI13CommandOriginSt14default_deleteIS1_EERKSsib
02:48:26 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftEventingC2ERKSs
02:48:26 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftEventing4initEv
02:48:26 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGameC2EiPPc
02:48:26 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGameD2Ev
02:48:26 Error [MinecraftSymbols] Unresolved symbol: _ZNK13MinecraftGame8isInGameEv
02:48:26 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame16requestLeaveGameEbb
02:48:26 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame24doPrimaryClientReadyWorkESt8functionIFvvEE
02:48:26 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame21getPrimaryUserOptionsEv
02:48:26 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame24getPrimaryClientInstanceEv
02:48:26 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame14startLeaveGameEv
02:48:26 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame17continueLeaveGameEv
02:48:26 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame14setTextboxTextERKSsi
02:48:26 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel32navigateToXblConsoleSignInScreenERKSsS1_
02:48:26 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel41navigateToXblConsoleSignInSucceededScreenERKN6Social12SignInResultESt8functionIFvS1_EEb
02:48:26 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel11leaveScreenEv
02:48:26 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social14MultiplayerXBLC2Ev
02:48:26 Error [MinecraftSymbols] Unresolved symbol: _ZTV22NullTextToSpeechClient
02:48:26 Error [MinecraftSymbols] Unresolved symbol: _ZNK7Options13getFullscreenEv
02:48:26 Error [MinecraftSymbols] Unresolved symbol: _ZN7Options13setFullscreenEb
02:48:26 Error [MinecraftSymbols] Unresolved symbol: _ZN15PermissionsFileC2ERKSs
02:48:26 Error [MinecraftSymbols] Unresolved symbol: _ZN19SkinPackKeyProviderC2Ev
02:48:26 Error [MinecraftSymbols] Unresolved symbol: _ZN19PackManifestFactoryC2ER14IPackTelemetry
02:48:26 Error [MinecraftSymbols] Unresolved symbol: _ZN17PackSourceFactoryC2Ev
02:48:26 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepositoryC2ER18IMinecraftEventingR19PackManifestFactoryR29IContentAccessibilityProviderPN4Core15FilePathManagerER17PackSourceFactoryb
02:48:26 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepository21addWorldResourcePacksERKN4Core4PathE
02:48:26 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepository12refreshPacksEv
02:48:26 Error [MinecraftSymbols] Unresolved symbol: _ZN18ContentTierManagerC2Ev
02:48:26 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManagerC2ESt8functionIFN4Core10PathBufferISsEEvEERK18ContentTierManagerb
02:48:26 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManager8setStackESt10unique_ptrI17ResourcePackStackSt14default_deleteIS1_EE21ResourcePackStackTypeb
02:48:26 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManager17onLanguageChangedEv
02:48:26 Error [MinecraftSymbols] Unresolved symbol: _ZN12PackInstanceC2EP12ResourcePackibP12PackSettings
02:48:26 Error [MinecraftSymbols] Unresolved symbol: _ZTV17ResourcePackStack
02:48:26 Error [MinecraftSymbols] Unresolved symbol: _ZN17ResourcePackStack3addE12PackInstanceRK22ResourcePackRepositoryb
02:48:26 Error [MinecraftSymbols] Unresolved symbol: _ZN22SaveTransactionManagerC2ESt8functionIFvbEE
02:48:26 Error [MinecraftSymbols] Unresolved symbol: _ZN9Scheduler17processCoroutinesENSt6chrono8durationIxSt5ratioILx1ELx1000000000EEEE
02:48:26 Error [MinecraftSymbols] Unresolved symbol: _ZN18MinecraftScheduler6clientEv
02:48:26 Error [MinecraftSymbols] Unresolved symbol: _ZN19ServerCommandOriginC2ERKSsR11ServerLevel22CommandPermissionLevel
02:48:26 Error [MinecraftSymbols] Unresolved symbol: _ZN16EducationOptionsC2EP19ResourcePackManager
02:48:26 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstanceC2ER13IMinecraftAppR30ServerInstanceEventCoordinator
02:48:26 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance16initializeServerER13IMinecraftAppR9WhitelistP15PermissionsFilePN4Core15FilePathManagerENSt6chrono8durationIxSt5ratioILx1ELx1EEEESsSsSs13LevelSettingsib20ConnectionDefinitionbRKSt6vectorISsSaISsEESsRKN3mce4UUIDER18IMinecraftEventingR22ResourcePackRepositoryRK18ContentTierManagerR19ResourcePackManagerSt8functionIFSt10unique_ptrI12LevelStorageSt14default_deleteIS10_EER9SchedulerEERKSsP9LevelDataSsSsSZ_I16EducationOptionsS11_IS1C_EEPSW_SY_IFvvEES1H_P13ServerMetricsP13DebugEndPointb
02:48:26 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstanceD2Ev
02:48:26 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance17startServerThreadEv
02:48:26 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance13leaveGameSyncEv
02:48:26 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance20queueForServerThreadESt8functionIFvvEE
02:48:26 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12MajorVersionE
02:48:26 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12MinorVersionE
02:48:26 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12PatchVersionE
02:48:26 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants15RevisionVersionE
02:48:26 Error [MinecraftSymbols] Unresolved symbol: _ZNK6Social4User11getLiveUserEv
02:48:26 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social12XboxLiveUser22_handleUISignInNoErrorERN4xbox8services6system14sign_in_resultESt8functionIFvNS_12SignInResultEbEE
02:48:26 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN9GameStore18onStoreInitializedEb
02:48:26 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN9GameStore22onQueryProductsSuccessERKSt6vectorI11ProductInfoSaIS1_EE
02:48:26 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social11UserManager17CreateUserManagerEv
02:48:26 Error [MinecraftSymbols] Unresolved symbol: _ZN2v82V810InitializeEv
02:48:26 Error [MinecraftSymbols] Unresolved symbol: _ZN2v82V818InitializePlatformEPNS_8PlatformE
02:48:26 Error [MinecraftSymbols] Unresolved symbol: _ZNK4pplx4taskIN4xbox8services16xbox_live_resultINS2_6system26token_and_signature_resultEEEE3getEv
02:48:26 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl15getOpenGLVendorEv
02:48:26 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl17getOpenGLRendererEv
02:48:26 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl16getOpenGLVersionEv
02:48:26 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl19getOpenGLExtensionsEv
02:48:26 Error [MinecraftSymbols] Unresolved symbol: _ZN3mce8Platform3OGL12InitBindingsEv
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: Found no way to resolve library version, Minecraft version likely unsupported
Signal 6 received
Backtrace elements: 14
#0 0   mcpelauncher-client                 0x001aa078 _ZN12CrashHandler12handleSignalEiPv + 312
#1 1   libsystem_platform.dylib            0xa759a02b _sigtramp + 43
#2 2   ???                                 0xffffffff 0x0 + 4294967295
#3 3   libsystem_c.dylib                   0xa733b956 abort + 133
#4 4   libc++abi.dylib                     0xa56fbea7 __cxa_bad_cast + 0
#5 5   libc++abi.dylib                     0xa56fc06a _ZL25default_terminate_handlerv + 250
#6 6   libc++abi.dylib                     0xa5715657 _ZSt11__terminatePFvvE + 14
#7 7   libc++abi.dylib                     0xa57150c1 __cxa_throw + 116
#8 8   mcpelauncher-client                 0x00226d2c _Z21minecraft_get_versionPiS_S_S_ + 396
#9 9   mcpelauncher-client                 0x001ac049 _ZN16MinecraftVersion4initEv + 57
#10 10  mcpelauncher-client                 0x001ab7b6 _ZN14MinecraftUtils18initSymbolBindingsEPv + 70
#11 11  mcpelauncher-client                 0x000ee242 main + 10610
#12 12  libdyld.dylib                       0xa7291611 start + 1
#13 13  ???                                 0x00000003 0x0 + 3
Dumping stack...
#447 HYBRIS (null)+49433360 in libminecraftpe.so+0x221b10 [0x2f24b10]
#593 HYBRIS (null)+47198208 in libminecraftpe.so+0x0000 [0x2d03000]
#639 HYBRIS (null)+47198208 in libminecraftpe.so+0x0000 [0x2d03000]
#640 HYBRIS (null)+47198208 in libminecraftpe.so+0x0000 [0x2d03000]
Process exited with unexpected exit code: 6

**Comment by Mhowser** [comment]
Please add your crash log to #165 via pastebin.com
