### ISSUE TITLE
Game crashes upon startup (LibEGL)

### ISSUE THREAD

**Issue by zvillager10** [minecraft-linux/mcpelauncher-manifest#191]
pls help /usr/bin/mcpelauncher-client: error while loading shared libraries: libEGL.so.1: cannot open shared object file: No such file or directory
Process exited with unexpected exit code: 127

**Comment by Mhowser** [comment]
Install 32 bit graphics drivers, read the docs for which ones.

**Comment by Craftstar15** [comment]
I cant play 1.13!

**Comment by ChristopherHX** [comment]
duplicate of #94
