### ISSUE TITLE
1.13.0.1 crashes

### ISSUE THREAD

**Issue by zvillager10** [minecraft-linux/mcpelauncher-manifest#193]
If you know anyway of fixing this, please tell or do so.. I really appreciate the fact this community works hard to try to help each other with this project, I really hope you continue that atittude

17:28:17 Info  [Launcher] Version: client c735370 / manifest eb0bc83
17:28:17 Info  [Launcher] CPU: GenuineIntel       Intel(R) Celeron(R) CPU  N3060  @ 1.60GHz
17:28:17 Info  [Launcher] CPU supports SSSE3: YES
17:28:17 Trace [Launcher] Loading hybris libraries
17:28:17 Trace [HybrisUtils] Loaded OS library /usr/share/mcpelauncher/libs/native/libfmod.so.9.16
17:28:17 Trace [HybrisUtils] Loaded OS library libm.so.6
17:28:17 Trace [HybrisUtils] Loaded OS library libz.so.1
17:28:17 Trace [Launcher] Loading Minecraft library
17:28:18 Info  [Launcher] Loaded Minecraft library
17:28:18 Debug [Launcher] Minecraft is at offset 0xedac4000
17:28:18 Trace [Launcher] Initializing vtables
17:28:18 Error [MinecraftSymbols] Unresolved symbol: _ZN3App4initER10AppContext
17:28:18 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App4quitERKSsS1_
17:28:18 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App6updateEv
17:28:18 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App16setRenderingSizeEii
17:28:18 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App17setUISizeAndScaleEiif
17:28:18 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App10wantToQuitEv
17:28:18 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServiceLocatorI11AppPlatformE15mDefaultServiceE
17:28:18 Error [MinecraftSymbols] Unresolved symbol: _ZNK11AppPlatform22getHardwareInformationEv
17:28:18 Error [MinecraftSymbols] Unresolved symbol: _ZN17AppResourceLoaderC1ESt8functionIFN4Core10PathBufferISsEEvEE
17:28:18 Error [MinecraftSymbols] Unresolved symbol: _ZN10Automation16AutomationClientC2ER13IMinecraftApp
17:28:18 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance7getUserEv
17:28:18 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance15_startLeaveGameEv
17:28:18 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance16_syncDestroyGameEv
17:28:18 Error [MinecraftSymbols] Unresolved symbol: _ZNK13CommandOutput11getMessagesEv
17:28:18 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender9translateERKSt6vectorISsSaISsEE
17:28:18 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSenderC2ERN10Automation16AutomationClientE
17:28:18 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSenderD2Ev
17:28:18 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender4sendERK13CommandOriginRK13CommandOutput
17:28:18 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender22registerOutputCallbackERKSt8functionIFvR19AutomationCmdOutputEE
17:28:18 Error [MinecraftSymbols] Unresolved symbol: _ZN6Common23getGameVersionStringNetEv
17:28:18 Error [MinecraftSymbols] Unresolved symbol: _ZN30ExternalFileLevelStorageSourceC2EPN4Core15FilePathManagerESt10shared_ptrI22SaveTransactionManagerE
17:28:18 Error [MinecraftSymbols] Unresolved symbol: _ZN30ExternalFileLevelStorageSource18createLevelStorageER9SchedulerRKSsRK15ContentIdentityRK19IContentKeyProvider
17:28:18 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourceLoadManagerC2Ev
17:28:18 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourceLoadManager4syncE16ResourceLoadType
17:28:18 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n3getERKSsRKSt6vectorISsSaISsEE
17:28:18 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n14chooseLanguageERKSs
17:28:18 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n13loadLanguagesER19ResourcePackManagerR19ResourceLoadManagerRKSs
17:28:18 Error [MinecraftSymbols] Unresolved symbol: _ZN5Level16createRandomSeedEv
17:28:18 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettingsC2Ev
17:28:18 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettingsC2ERKS_
17:28:18 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettings15parseSeedStringERKSsj
17:28:18 Error [MinecraftSymbols] Unresolved symbol: _ZN9Minecraft11getCommandsEv
17:28:18 Error [MinecraftSymbols] Unresolved symbol: _ZNK9Minecraft8getLevelEv
17:28:18 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftCommands15setOutputSenderESt10unique_ptrI19CommandOutputSenderSt14default_deleteIS1_EE
17:28:18 Error [MinecraftSymbols] Unresolved symbol: _ZNK17MinecraftCommands23requestCommandExecutionESt10unique_ptrI13CommandOriginSt14default_deleteIS1_EERKSsib
17:28:18 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftEventingC2ERKSs
17:28:18 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftEventing4initEv
17:28:18 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGameC2EiPPc
17:28:18 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGameD2Ev
17:28:18 Error [MinecraftSymbols] Unresolved symbol: _ZNK13MinecraftGame8isInGameEv
17:28:18 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame16requestLeaveGameEbb
17:28:18 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame24doPrimaryClientReadyWorkESt8functionIFvvEE
17:28:18 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame21getPrimaryUserOptionsEv
17:28:18 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame24getPrimaryClientInstanceEv
17:28:18 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame14startLeaveGameEv
17:28:18 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame17continueLeaveGameEv
17:28:18 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame14setTextboxTextERKSsi
17:28:18 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel32navigateToXblConsoleSignInScreenERKSsS1_
17:28:18 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel41navigateToXblConsoleSignInSucceededScreenERKN6Social12SignInResultESt8functionIFvS1_EEb
17:28:18 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel11leaveScreenEv
17:28:18 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social14MultiplayerXBLC2Ev
17:28:18 Error [MinecraftSymbols] Unresolved symbol: _ZTV22NullTextToSpeechClient
17:28:18 Error [MinecraftSymbols] Unresolved symbol: _ZNK7Options13getFullscreenEv
17:28:18 Error [MinecraftSymbols] Unresolved symbol: _ZN7Options13setFullscreenEb
17:28:18 Error [MinecraftSymbols] Unresolved symbol: _ZN15PermissionsFileC2ERKSs
17:28:18 Error [MinecraftSymbols] Unresolved symbol: _ZN19SkinPackKeyProviderC2Ev
17:28:18 Error [MinecraftSymbols] Unresolved symbol: _ZN19PackManifestFactoryC2ER14IPackTelemetry
17:28:18 Error [MinecraftSymbols] Unresolved symbol: _ZN17PackSourceFactoryC2Ev
17:28:18 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepositoryC2ER18IMinecraftEventingR19PackManifestFactoryR29IContentAccessibilityProviderPN4Core15FilePathManagerER17PackSourceFactoryb
17:28:18 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepository21addWorldResourcePacksERKN4Core4PathE
17:28:18 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepository12refreshPacksEv
17:28:18 Error [MinecraftSymbols] Unresolved symbol: _ZN18ContentTierManagerC2Ev
17:28:18 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManagerC2ESt8functionIFN4Core10PathBufferISsEEvEERK18ContentTierManagerb
17:28:18 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManager8setStackESt10unique_ptrI17ResourcePackStackSt14default_deleteIS1_EE21ResourcePackStackTypeb
17:28:18 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManager17onLanguageChangedEv
17:28:18 Error [MinecraftSymbols] Unresolved symbol: _ZN12PackInstanceC2EP12ResourcePackibP12PackSettings
17:28:18 Error [MinecraftSymbols] Unresolved symbol: _ZTV17ResourcePackStack
17:28:18 Error [MinecraftSymbols] Unresolved symbol: _ZN17ResourcePackStack3addE12PackInstanceRK22ResourcePackRepositoryb
17:28:18 Error [MinecraftSymbols] Unresolved symbol: _ZN22SaveTransactionManagerC2ESt8functionIFvbEE
17:28:18 Error [MinecraftSymbols] Unresolved symbol: _ZN9Scheduler17processCoroutinesENSt6chrono8durationIxSt5ratioILx1ELx1000000000EEEE
17:28:18 Error [MinecraftSymbols] Unresolved symbol: _ZN18MinecraftScheduler6clientEv
17:28:18 Error [MinecraftSymbols] Unresolved symbol: _ZN19ServerCommandOriginC2ERKSsR11ServerLevel22CommandPermissionLevel
17:28:18 Error [MinecraftSymbols] Unresolved symbol: _ZN16EducationOptionsC2EP19ResourcePackManager
17:28:18 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstanceC2ER13IMinecraftAppR30ServerInstanceEventCoordinator
17:28:18 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance16initializeServerER13IMinecraftAppR9WhitelistP15PermissionsFilePN4Core15FilePathManagerENSt6chrono8durationIxSt5ratioILx1ELx1EEEESsSsSs13LevelSettingsib20ConnectionDefinitionbRKSt6vectorISsSaISsEESsRKN3mce4UUIDER18IMinecraftEventingR22ResourcePackRepositoryRK18ContentTierManagerR19ResourcePackManagerSt8functionIFSt10unique_ptrI12LevelStorageSt14default_deleteIS10_EER9SchedulerEERKSsP9LevelDataSsSsSZ_I16EducationOptionsS11_IS1C_EEPSW_SY_IFvvEES1H_P13ServerMetricsP13DebugEndPointb
17:28:18 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstanceD2Ev
17:28:18 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance17startServerThreadEv
17:28:18 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance13leaveGameSyncEv
17:28:18 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance20queueForServerThreadESt8functionIFvvEE
17:28:18 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12MajorVersionE
17:28:18 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12MinorVersionE
17:28:18 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12PatchVersionE
17:28:18 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants15RevisionVersionE
17:28:18 Error [MinecraftSymbols] Unresolved symbol: _ZNK6Social4User11getLiveUserEv
17:28:18 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social12XboxLiveUser22_handleUISignInNoErrorERN4xbox8services6system14sign_in_resultESt8functionIFvNS_12SignInResultEbEE
17:28:18 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN9GameStore18onStoreInitializedEb
17:28:18 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN9GameStore22onQueryProductsSuccessERKSt6vectorI11ProductInfoSaIS1_EE
17:28:18 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social11UserManager17CreateUserManagerEv
17:28:18 Error [MinecraftSymbols] Unresolved symbol: _ZN2v82V810InitializeEv
17:28:18 Error [MinecraftSymbols] Unresolved symbol: _ZN2v82V818InitializePlatformEPNS_8PlatformE
17:28:18 Error [MinecraftSymbols] Unresolved symbol: _ZNK4pplx4taskIN4xbox8services16xbox_live_resultINS2_6system26token_and_signature_resultEEEE3getEv
17:28:18 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl15getOpenGLVendorEv
17:28:18 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl17getOpenGLRendererEv
17:28:18 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl16getOpenGLVersionEv
17:28:18 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl19getOpenGLExtensionsEv
17:28:18 Error [MinecraftSymbols] Unresolved symbol: _ZN3mce8Platform3OGL12InitBindingsEv
terminate called after throwing an instance of 'std::runtime_error'
  what():  Found no way to resolve library version, Minecraft version likely unsupported
Signal 6 received
Backtrace elements: 15
#0 /usr/bin/mcpelauncher-client(_ZN12CrashHandler12handleSignalEiPv+0xc5) [0x567b07db]
#1 linux-gate.so.1(__kernel_sigreturn+0) [0xf7f3b090]
#2 linux-gate.so.1(__kernel_vsyscall+0x9) [0xf7f3b079]
#3 /lib/i386-linux-gnu/libc.so.6(gsignal+0xc2) [0xf7819832]
#4 /lib/i386-linux-gnu/libc.so.6(abort+0x121) [0xf781acc1]
#5 /usr/lib/i386-linux-gnu/libstdc++.so.6(+0x6e97d) [0xf7b7797d]
#6 /usr/lib/i386-linux-gnu/libstdc++.so.6(+0x760f4) [0xf7b7f0f4]
#7 /usr/lib/i386-linux-gnu/libstdc++.so.6(+0x7615d) [0xf7b7f15d]
#8 /usr/lib/i386-linux-gnu/libstdc++.so.6(+0x7645c) [0xf7b7f45c]
#9 /usr/bin/mcpelauncher-client(_Z21minecraft_get_versionPiS_S_S_+0x13a) [0x56804f4b]
#10 /usr/bin/mcpelauncher-client(_ZN16MinecraftVersion4initEv+0x34) [0x567b1fd4]
#11 /usr/bin/mcpelauncher-client(_ZN14MinecraftUtils18initSymbolBindingsEPv+0x44) [0x567b1ecc]
#12 /usr/bin/mcpelauncher-client(main+0x10c2) [0x567591de]
#13 /lib/i386-linux-gnu/libc.so.6(__libc_start_main+0xf1) [0xf7804e81]
#14 /usr/bin/mcpelauncher-client(+0x1c8b31) [0x56757b31]
Dumping stack...
#1 HYBRIS (null)+-247665760 in libminecraftpe.so+0x390aba0 [0xf13ceba0]
#2 HYBRIS (null)+-247669456 in libminecraftpe.so+0x3909d30 [0xf13cdd30]
#13 HYBRIS (null)+-307478528 in libminecraftpe.so+0x0000 [0xedac4000]
#32 HYBRIS (null)+-218162692 in libminecraftpe.so+0x552d9fc [0xf2ff19fc]
#35 HYBRIS (null)+-218162692 in libminecraftpe.so+0x552d9fc [0xf2ff19fc]
#36 HYBRIS (null)+-247630079 in libminecraftpe.so+0x3913701 [0xf13d7701]
#37 HYBRIS (null)+-218162692 in libminecraftpe.so+0x552d9fc [0xf2ff19fc]
#38 HYBRIS (null)+-218162943 in libminecraftpe.so+0x552d901 [0xf2ff1901]
#40 HYBRIS (null)+-218162692 in libminecraftpe.so+0x552d9fc [0xf2ff19fc]
#77 HYBRIS (null)+-218162943 in libminecraftpe.so+0x552d901 [0xf2ff1901]
#79 HYBRIS (null)+-218162692 in libminecraftpe.so+0x552d9fc [0xf2ff19fc]
#109 HYBRIS (null)+-218162692 in libminecraftpe.so+0x552d9fc [0xf2ff19fc]
#110 HYBRIS (null)+-218162943 in libminecraftpe.so+0x552d901 [0xf2ff1901]
#112 HYBRIS (null)+-218162692 in libminecraftpe.so+0x552d9fc [0xf2ff19fc]
#113 HYBRIS (null)+-218162943 in libminecraftpe.so+0x552d901 [0xf2ff1901]
#115 HYBRIS (null)+-218162692 in libminecraftpe.so+0x552d9fc [0xf2ff19fc]
#116 HYBRIS (null)+-218162943 in libminecraftpe.so+0x552d901 [0xf2ff1901]
#118 HYBRIS (null)+-218162692 in libminecraftpe.so+0x552d9fc [0xf2ff19fc]
#119 HYBRIS (null)+-218162943 in libminecraftpe.so+0x552d901 [0xf2ff1901]
#121 HYBRIS (null)+-218162692 in libminecraftpe.so+0x552d9fc [0xf2ff19fc]
#122 HYBRIS (null)+-218162943 in libminecraftpe.so+0x552d901 [0xf2ff1901]
#124 HYBRIS (null)+-218162692 in libminecraftpe.so+0x552d9fc [0xf2ff19fc]
#125 HYBRIS (null)+-218162943 in libminecraftpe.so+0x552d901 [0xf2ff1901]
#127 HYBRIS (null)+-218162692 in libminecraftpe.so+0x552d9fc [0xf2ff19fc]
#128 HYBRIS (null)+-218162943 in libminecraftpe.so+0x552d901 [0xf2ff1901]
#130 HYBRIS (null)+-218162692 in libminecraftpe.so+0x552d9fc [0xf2ff19fc]
#131 HYBRIS (null)+-218162943 in libminecraftpe.so+0x552d901 [0xf2ff1901]
#133 HYBRIS (null)+-218162692 in libminecraftpe.so+0x552d9fc [0xf2ff19fc]
#137 HYBRIS (null)+-218162943 in libminecraftpe.so+0x552d901 [0xf2ff1901]
#139 HYBRIS (null)+-218162692 in libminecraftpe.so+0x552d9fc [0xf2ff19fc]
#140 HYBRIS (null)+-218162943 in libminecraftpe.so+0x552d901 [0xf2ff1901]
#143 HYBRIS (null)+-218162943 in libminecraftpe.so+0x552d901 [0xf2ff1901]
#655 HYBRIS (null)+-307478528 in libminecraftpe.so+0x0000 [0xedac4000]
Process exited with unexpected exit code: 6

**Comment by Craftstar15** [comment]
I feel you. It wont let me play 1.13!

**Comment by Mhowser** [comment]
Please add your crash log to #165 via pastebin.com
