### ISSUE TITLE
1.13 (skin update) crashes at launcher

### ISSUE THREAD

**Issue by Craftstar15** [minecraft-linux/mcpelauncher-manifest#194]
1.13 (skin update) crashes at the launcher and i have tried all I know. Anyone else have this problem?
does anyone have solutions? I just wanna play with my friend!

**Comment by Mhowser** [comment]
What version specifically? And can you add your crash log to #165 please (use pastebin.com)

**Comment by ChristopherHX** [comment]
Please download a newer launcher or only play older Minecraft Versions (duplicate of https://github.com/minecraft-linux/mcpelauncher-manifest/issues/165)
Please read https://github.com/minecraft-linux/mcpelauncher-manifest/issues/165#issuecomment-560015903 to upgrade to `my fork` or `ng preview`
