### ISSUE TITLE
how do I play 1.13.1.5 it keeps crashing

### ISSUE THREAD

**Issue by aeuxial** [minecraft-linux/mcpelauncher-manifest#198]
I cant play the latest version all the servers I play is already 1.13

**Comment by Bonicgamer** [comment]
The game keeps crashing for me too. Idk why though.

**Comment by aeuxial** [comment]
I cant even play the game when I click play it won't launch and crashes instantly

**Comment by KodokuOkami** [comment]
use 1.12 for now. it should work.

**Comment by ChristopherHX** [comment]
Please download a newer launcher or only play older Minecraft Versions (duplicate of https://github.com/minecraft-linux/mcpelauncher-manifest/issues/165)
Please read https://github.com/minecraft-linux/mcpelauncher-manifest/issues/165#issuecomment-560015903 to upgrade to `my fork` or `ng preview`
