### ISSUE TITLE
Minecraft: Bedrock Edition 1.13 not downloading

### ISSUE THREAD

**Issue by uzyandev** [minecraft-linux/mcpelauncher-manifest#202]
message subject speaks for itself. mcpelauncher-ui-qt to start in Terminal (for log's)[](url) 
![Снимок экрана от 2019-12-11 16-22-51](https://user-images.githubusercontent.com/55317472/70617694-03bf4d00-1c33-11ea-93ec-bfb743699057.png)

**Comment by ChristopherHX** [comment]
Try logout from Google and login again, but if haven't downloaded it already I guess you cannot download 1.13 anymore without a versionsdb update (1.14.0.9 released yesterday)

**Comment by uzyandev** [comment]
> Try logout from Google and login again, but if haven't downloaded it already I guess you cannot download 1.13 anymore without a versionsdb update (1.14.0.9 released yesterday)

This problem appeared after assembling the mspelauncher

**Comment by ChristopherHX** [comment]
Did it open or not?
Did it crash before showing an GUI?
Did you logged in to google or not?
Did you tried my last answer and it didn't helped?
What Operating System and Version?
Tried the appimage?

**Comment by ChristopherHX** [comment]
Did you tried Downloading 1.13.0.6 (Beta)…?
Then you need to join the Minecraft Beta on googleplay (Minecraft page)
But that is very old Beta

To get an importable 1.13.0.34 apk (last working on the main launcher) https://github.com/minecraft-linux/mcpelauncher-manifest/issues/186#issuecomment-553165689

**Comment by uzyandev** [comment]
> Did it open or not?
> Did it crash before showing an GUI?
> Did you logged in to google or not?
> Did you tried my last answer and it didn't helped?
> What Operating System and Version?
> Tried the appimage?

not open. Downloading not start. Yes, I logged in to google account. YES! Ubuntu 19-10. Not

**Comment by uzyandev** [comment]
> Did you tried Downloading 1.13.0.6 (Beta)…?
> Then you need to join the Minecraft Beta on googleplay (Minecraft page)
> But that is very old Beta
> 
> To get an importable 1.13.0.34 apk (last working on the main launcher) [#186 (comment)](https://github.com/minecraft-linux/mcpelauncher-manifest/issues/186#issuecomment-553165689)

okey, thank

**Comment by uzyandev** [comment]
Is fun. Minecraft: Bedrock Edition 1.14.0.9 downloading and not working

**Comment by ChristopherHX** [comment]
I think this issue is solved now
