### ISSUE TITLE
Do not open the launcher

### ISSUE THREAD

**Issue by BrianMedina0903** [minecraft-linux/mcpelauncher-manifest#203]
I don't open the launcher in linux mint

![image](https://user-images.githubusercontent.com/38367679/70855962-dd025000-1e98-11ea-9d1e-ffefe2c0c033.png)

**Comment by ChristopherHX** [comment]
I don't understand.
> Do not open the launcher

means for me you should not try starting the launcher

Probably you mean, you cannot open the launcher.

Why are you unable to start the launcher?
How did you install it?
Which instruction have you followed, to install the launcher?

I can start it from a Terminal (installed not AppImage)
`mcpelauncher-ui-qt`

I can start it from a Terminal (AppImage)
`./Minecraft_Bedrock_Launcher*.AppImage` (assumes the appimage is in the current working directory)
If this return a error `chmod +x ./Minecraft_Bedrock_Launcher*.AppImage`, retry the first command
