### ISSUE TITLE
Joining friends on xbox live doesn't work

### ISSUE THREAD

**Issue by bentton** [minecraft-linux/mcpelauncher-manifest#220]
My friends are playing minecraft but their game isn't showing up on the Friends tab.
Other friends are playing with them.
Their game is enabled for multiplayer.
I am able to join Servers.
I am signed into Xbox Live.
I am signed into Google Play and legally own Minecraft.
I am using Linux Mint.

**Comment by bentton** [comment]
Solution: Use Christopher's fork.

**Comment by Breece1019** [comment]
could you point me to the solution with a link?  I am using Christopher's launcher and am in 1.14 but Friends are still not showing in my list
