### ISSUE TITLE
My game doesn't start

### ISSUE THREAD

**Issue by ItzLightyHD** [minecraft-linux/mcpelauncher-manifest#226]
![Why?](https://user-images.githubusercontent.com/45460688/73139239-3fd83100-406c-11ea-8dac-910d80829498.png)

I just used a x86 APK, but the game doesn't start.

**Comment by Mhowser** [comment]
Install 32bit graphics drivers
https://mcpelauncher.readthedocs.io/en/latest/troubleshooting.html

**Comment by ItzLightyHD** [comment]
I already did this, probably the launcher doesn't support 1.14

**Comment by Mhowser** [comment]
Are you in the discord support server? I can help you faster there
https://discord.gg/27TUUwf

**Comment by ChristopherHX** [comment]
duplicate of #94
