### ISSUE TITLE
I can't enter Chinese in the game

### ISSUE THREAD

**Issue by wyxa233** [minecraft-linux/mcpelauncher-manifest#230]
I am a Chinese player.When I use this launcher to play Minecraft,I can't enter Chinese through my ime.So I can only copy and paste the text.That's so difficult!I don't know if there are other languages like this.Please help me.
(The level of my English is not very good, so I cannot make too much dialog with you. )

**Comment by ChristopherHX** [comment]
I addresed your issue for linux, in [my fork](https://github.com/ChristopherHX/linux-packaging-scripts/releases).
Prebuilds with this patch are coming soon (Make shure to download a Release newer than this comment)

**Comment by ChristopherHX** [comment]
duplicate of feature request #123
