### ISSUE TITLE
It's been 3 months

### ISSUE THREAD

**Issue by FadeAssassin** [minecraft-linux/mcpelauncher-manifest#234]
People have been having trouble with 1.13 and beyond for well over 3 months. Yes, people look at the issues but nobody ever helps fix the problem. For example, articles about exiting with a non-zero error code and the launcher crashes trying to launch 1.14. What's the point in having a issue sharing forum, if nobody helps each other.
If you finished reading this, thank you for your time.

**Comment by Mhowser** [comment]
@FadeAssassin a lot has gone down in those three months, there is a fork of this launcher maintained by a different developer. His fork uses a different way to patch the game and it works on the latest versions at the moment. https://github.com/ChristopherHX/mcpelauncher-manifest

Eventually this fork will be merged when MrARM is finished with his exams and other things in life.

**Comment by FadeAssassin** [comment]
I'm new to github, thus I don't know what to do with the files after I have
installed them from the fork.

P.S. Thank you for telling me about the fork.

**Comment by FadeAssassin** [comment]
> @FadeAssassin a lot has gone down in those three months, there is a fork of this launcher maintained by a different developer. His fork uses a different way to patch the game and it works on the latest versions at the moment. https://github.com/ChristopherHX/mcpelauncher-manifest
> 
> Eventually this fork will be merged when MrARM is finished with his exams and other things in life.

I'm new to github so I don't know what I am doing.  Could you give me  step-by-step instructions about how to use this fork to be able to launch 1.14. I already have the launcher downloaded from here.

**Comment by ChristopherHX** [comment]
Idk if you understand this, but nothing to discuss here.

Please download a newer launcher or only play older Minecraft Versions (duplicate of https://github.com/minecraft-linux/mcpelauncher-manifest/issues/165)
Please read https://github.com/minecraft-linux/mcpelauncher-manifest/issues/165#issuecomment-560015903 to upgrade to `my fork` or `ng preview`
