### ISSUE TITLE
minecraft apk and sign in crashes in the appimage on raspian 32-bit (christopherHX fork)

### ISSUE THREAD

**Issue by crypto48-lang1** [minecraft-linux/mcpelauncher-manifest#235]
libEGL warning: DRI2: failed to open vc4 (search paths /usr/lib/arm-linux-gnueabihf/dri:\$${ORIGIN}/dri:/usr/lib/dri)
libEGL warning: DRI2: failed to open vc4 (search paths /usr/lib/arm-linux-gnueabihf/dri:\$${ORIGIN}/dri:/usr/lib/dri)
libEGL warning: DRI2: failed to open swrast (search paths /usr/lib/arm-linux-gnueabihf/dri:\$${ORIGIN}/dri:/usr/lib/dri)
libEGL warning: DRI2: failed to open swrast (search paths /usr/lib/arm-linux-gnueabihf/dri:\$${ORIGIN}/dri:/usr/lib/dri)
EGLUT: failed to initialize EGL display
Process exited with unexpected exit code: 1

**Comment by ChristopherHX** [comment]
@crypto48-lang1 Please move to https://github.com/ChristopherHX/mcpelauncher-manifest/issues not an issue of this repo

**Comment by ChristopherHX** [comment]
Should be fixed in newer appimages found here https://github.com/ChristopherHX/mcpelauncher-manifest/releases/tag/stable, you might see a update notification.
I now use an appimage script like the x86_64 version uses
