### ISSUE TITLE
Crashes on CPUs with no SSSE3 (legacy AMD ones)

### ISSUE THREAD

**Issue by AceDolphin** [minecraft-linux/mcpelauncher-manifest#24]
Hello
I am on arch linux and have compiled mcpe using the github instructions
https://github.com/minecraft-linux/mcpelauncher-manifest/wiki/Compiling-from-sources
I run pcpelauncher-ui-qt and when I click Play minecraft 1.7.0.13 the game crashes
This is the log that it shows after it crashes

> 23:18:24 Info  [Launcher] Version: client c2a58e6 / manifest 22c0996
> 23:18:24 Trace [Launcher] Loading hybris libraries
> 23:18:24 Trace [HybrisUtils] Loaded OS library /usr/share/mcpelauncher/libs/native/libfmod.so.9.16
> 23:18:24 Trace [HybrisUtils] Loaded OS library libm.so.6
> 23:18:24 Trace [Launcher] Loading Minecraft library
> 23:18:25 Info  [Launcher] Loaded Minecraft library
> 23:18:25 Debug [Launcher] Minecraft is at offset 0xeca27000
> 23:18:25 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstanceC2ER13IMinecraftAppR9WhitelistRK14PermissionsMapP15FilePathManagerNSt6chrono8durationIxSt5ratioILx1ELx1EEEESsSsSs13LevelSettingsibiiibRKSt6vectorISsSaISsEESsRKN3mce4UUIDER18IMinecraftEventingR22ResourcePackRepositoryRK18ContentTierManagerR19ResourcePackManagerSt8functionIFSt10unique_ptrI12LevelStorageSt14default_deleteISZ_EER9SchedulerEERKSsP9LevelDataP22TextFilteringProcessorPSV_SX_IFvS18_EES1F_
> 23:18:25 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame24doPrimaryClientReadyWorkESt8functionIFvvEE
> 23:18:25 Error [MinecraftSymbols] Unresolved symbol: _ZTV22NullTextToSpeechClient
> 23:18:25 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App4quitERKSsS1_
> 23:18:25 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepositoryC2ER18IMinecraftEventingR19PackManifestFactoryR29IContentAccessibilityProviderP15FilePathManagerR17PackSourceFactory
> 23:18:25 Info  [Launcher] Game version: 1.7.0
> 23:18:25 Info  [Launcher] Applying patches
> 23:18:25 Trace [Store] Vtable size = 33
> 23:18:25 Trace [Patch] Patching - original: 85 83 87 86 131
> 23:18:25 Trace [Patch] Patching - result: 233 27 79 224 104
> 23:18:25 Trace [Patch] Patching - original: 85 83 87 86 129
> 23:18:25 Trace [Patch] Patching - result: 233 59 13 168 102
> 23:18:25 Trace [Patch] Patching - original: 85 83 87 86 129
> 23:18:25 Trace [Patch] Patching - result: 233 91 69 225 102
> 23:18:25 Trace [Patch] Patching - original: 85 83 87 86 129
> 23:18:25 Trace [Patch] Patching - result: 233 235 54 225 102
> 23:18:25 Trace [Patch] Patching - original: 85 83 87 86 129
> 23:18:25 Trace [Patch] Patching - result: 233 139 71 225 102
> 23:18:25 Trace [Patch] Patching - original: 85 83 87 86 129
> 23:18:25 Trace [Patch] Patching - result: 233 75 173 224 102
> 23:18:25 Trace [Patch] Patching - original: 85 83 87 86 129
> 23:18:25 Trace [Patch] Patching - result: 233 139 148 224 102
> 23:18:25 Trace [Patch] Patching - original: 85 83 87 86 129
> 23:18:25 Trace [Patch] Patching - result: 233 171 116 226 102
> 23:18:25 Trace [Patch] Patching - original: 83 87 86 131 236
> 23:18:25 Trace [Patch] Patching - result: 233 219 34 225 102
> 23:18:25 Trace [Patch] Patching - original: 85 83 87 86 129
> 23:18:25 Trace [Patch] Patching - result: 233 219 97 225 102
> 23:18:25 Trace [Patch] Patching - original: 49 192 195 141 182
> 23:18:25 Trace [Patch] Patching - result: 233 75 89 218 104
> 23:18:25 Trace [Patch] Patching - original: 83 131 236 24 232
> 23:18:25 Trace [Patch] Patching - result: 233 235 44 252 102
> 23:18:25 Trace [Patch] Patching - original: 85 83 87 86 131
> 23:18:25 Trace [Patch] Patching - result: 233 171 241 225 104
> 23:18:25 Trace [Patch] Patching - original: 85 83 87 86 129
> 23:18:25 Trace [Patch] Patching - result: 233 27 239 225 104
> 23:18:25 Trace [Patch] Patching - original: 83 87 86 131 236
> 23:18:25 Trace [Patch] Patching - result: 233 235 239 225 104
> 23:18:25 Trace [Patch] Patching - original: 232 29 166 22 254
> 23:18:25 Trace [Patch] Patching - result: 232 141 122 29 103
> 23:18:25 Info  [Launcher] Creating window
> 23:18:25 Trace [Launcher] Initializing AppPlatform (vtable)
> 23:18:25 Trace [AppPlatform] Vtable size = 246
> 23:18:25 Trace [Launcher] Initializing AppPlatform (create instance)
> 23:18:25 Trace [Launcher] Initializing AppPlatform (initialize call)
> 23:18:25 Trace [AppPlatform] createDeviceID: 
> 23:18:25 Info  [Launcher] OpenGL: version: OpenGL ES 3.2 NVIDIA 410.73, renderer: GeForce GTX 1050 Ti/PCIe/SSE2, vendor: NVIDIA Corporation
> 23:18:25 Trace [Launcher] Initializing MinecraftGame (create instance)
> 23:18:25 Trace [AppPlatform] getSystemRegion: en_US
> 23:18:25 Trace [Launcher] Initializing MinecraftGame (init call)
> 23:18:25 Trace [AppPlatform] getDataUrl: /home/ace/.local/share/mcpelauncher/versions/1.7.0.13/assets/
> 23:18:25 Info  [Launcher] Game initialized
> 23:18:25 Trace [AppPlatform] getDataUrl: /home/ace/.local/share/mcpelauncher/versions/1.7.0.13/assets/
> 23:18:25 Trace [XboxLive] Reading xbox config file
> Process exited with unexpected exit code: 4

Any help would be appreciated

Thanks Ace : )

**Comment by MCMrARM** [comment]
Signal 4 is illegal instruction, so I'm afraid your hardware is too old (most likely and old AMD CPU w/o SSSE3)
