### ISSUE TITLE
Crashes when I F11 to fullscreen

### ISSUE THREAD

**Issue by lsdxm** [minecraft-linux/mcpelauncher-manifest#241]
02:32:56 Info  [Launcher] Version: client b5dece1 / manifest 6569d35
02:32:56 Info  [Launcher] CPU: GenuineIntel Intel(R) Core(TM) i3-9100F CPU @ 3.60GHz
02:32:56 Info  [Launcher] CPU supports SSSE3: YES
02:32:56 Trace [Launcher] Loading hybris libraries
02:32:56 Trace [HybrisUtils] Loaded OS library /usr/share//mcpelauncher/libs/native/libfmod.so.9.16
02:32:56 Trace [HybrisUtils] Loaded OS library libm.so.6
02:32:56 Trace [HybrisUtils] Loaded OS library libz.so.1
02:32:56 Info  [Launcher] Creating window
02:32:56 Trace [Launcher] Loading gamepad mappings: /usr/share//mcpelauncher/gamecontrollerdb.txt
02:32:56 Trace [Launcher] Loading gamepad mappings: /usr/share/mcpelauncher/gamecontrollerdb.txt
02:32:56 Trace [Launcher] Loading Minecraft library
02:32:56 Info  [Launcher] Loaded Minecraft library
02:32:56 Debug [Launcher] Minecraft is at offset 0xedc74000
02:32:56 Error [MinecraftSymbols] Unresolved symbol: _ZN3App4initER10AppContext
02:32:56 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App4quitERKSsS1_
02:32:56 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App6updateEv
02:32:56 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App16setRenderingSizeEii
02:32:56 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App17setUISizeAndScaleEiif
02:32:56 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App10wantToQuitEv
02:32:56 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServiceLocatorI11AppPlatformE15mDefaultServiceE
02:32:56 Error [MinecraftSymbols] Unresolved symbol: _ZN11AppPlatform12showKeyboardERKSsibbbiRKN3glm5tvec2IfLNS2_9precisionE0EEE
02:32:56 Error [MinecraftSymbols] Unresolved symbol: _ZNK11AppPlatform22getHardwareInformationEv
02:32:56 Error [MinecraftSymbols] Unresolved symbol: _ZN17AppResourceLoaderC1ESt8functionIFN4Core10PathBufferISsEEvEE
02:32:56 Error [MinecraftSymbols] Unresolved symbol: _ZN10Automation16AutomationClientC2ER13IMinecraftApp
02:32:56 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance7getUserEv
02:32:56 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance15_startLeaveGameEv
02:32:56 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance16_syncDestroyGameEv
02:32:56 Error [MinecraftSymbols] Unresolved symbol: _ZNK13CommandOutput11getMessagesEv
02:32:56 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender9translateERKSt6vectorISsSaISsEE
02:32:56 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSenderC2ERN10Automation16AutomationClientE
02:32:56 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSenderD2Ev
02:32:56 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender4sendERK13CommandOriginRK13CommandOutput
02:32:56 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender22registerOutputCallbackERKSt8functionIFvR19AutomationCmdOutputEE
02:32:56 Error [MinecraftSymbols] Unresolved symbol: _ZN6Common23getGameVersionStringNetEv
02:32:56 Error [MinecraftSymbols] Unresolved symbol: _ZN30ExternalFileLevelStorageSourceC2EPN4Core15FilePathManagerESt10shared_ptrI22SaveTransactionManagerE
02:32:56 Error [MinecraftSymbols] Unresolved symbol: _ZN30ExternalFileLevelStorageSource18createLevelStorageER9SchedulerRKSsRK15ContentIdentityRK19IContentKeyProvider
02:32:56 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourceLoadManagerC2Ev
02:32:56 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourceLoadManager4syncE16ResourceLoadType
02:32:56 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n3getERKSsRKSt6vectorISsSaISsEE
02:32:56 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n14chooseLanguageERKSs
02:32:56 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n13loadLanguagesER19ResourcePackManagerR19ResourceLoadManagerRKSs
02:32:56 Error [MinecraftSymbols] Unresolved symbol: _ZN5Level16createRandomSeedEv
02:32:56 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettingsC2Ev
02:32:56 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettingsC2ERKS_
02:32:56 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettings15parseSeedStringERKSsj
02:32:56 Error [MinecraftSymbols] Unresolved symbol: _ZN9Minecraft11getCommandsEv
02:32:56 Error [MinecraftSymbols] Unresolved symbol: _ZNK9Minecraft8getLevelEv
02:32:56 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftCommands15setOutputSenderESt10unique_ptrI19CommandOutputSenderSt14default_deleteIS1_EE
02:32:56 Error [MinecraftSymbols] Unresolved symbol: _ZNK17MinecraftCommands23requestCommandExecutionESt10unique_ptrI13CommandOriginSt14default_deleteIS1_EERKSsib
02:32:56 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftEventingC2ERKSs
02:32:56 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftEventing4initEv
02:32:56 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGameC2EiPPc
02:32:56 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGameD2Ev
02:32:56 Error [MinecraftSymbols] Unresolved symbol: _ZNK13MinecraftGame8isInGameEv
02:32:56 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame16requestLeaveGameEbb
02:32:56 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame24doPrimaryClientReadyWorkESt8functionIFvvEE
02:32:56 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame21getPrimaryUserOptionsEv
02:32:56 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame24getPrimaryClientInstanceEv
02:32:56 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame14startLeaveGameEv
02:32:56 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame17continueLeaveGameEv
02:32:56 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame14setTextboxTextERKSsi
02:32:56 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel32navigateToXblConsoleSignInScreenERKSsS1_
02:32:56 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel41navigateToXblConsoleSignInSucceededScreenERKN6Social12SignInResultESt8functionIFvS1_EEb
02:32:56 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel11leaveScreenEv
02:32:56 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social14MultiplayerXBLC2Ev
02:32:56 Error [MinecraftSymbols] Unresolved symbol: _ZTV22NullTextToSpeechClient
02:32:56 Error [MinecraftSymbols] Unresolved symbol: _ZNK7Options13getFullscreenEv
02:32:56 Error [MinecraftSymbols] Unresolved symbol: _ZN7Options13setFullscreenEb
02:32:56 Error [MinecraftSymbols] Unresolved symbol: _ZN15PermissionsFileC2ERKSs
02:32:56 Error [MinecraftSymbols] Unresolved symbol: _ZN19SkinPackKeyProviderC2Ev
02:32:56 Error [MinecraftSymbols] Unresolved symbol: _ZN19PackManifestFactoryC2ER14IPackTelemetry
02:32:56 Error [MinecraftSymbols] Unresolved symbol: _ZN17PackSourceFactoryC2Ev
02:32:56 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepositoryC2ER18IMinecraftEventingR19PackManifestFactoryR29IContentAccessibilityProviderPN4Core15FilePathManagerER17PackSourceFactoryb
02:32:56 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepository21addWorldResourcePacksERKN4Core4PathE
02:32:56 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepository12refreshPacksEv
02:32:56 Error [MinecraftSymbols] Unresolved symbol: _ZN18ContentTierManagerC2Ev
02:32:56 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManagerC2ESt8functionIFN4Core10PathBufferISsEEvEERK18ContentTierManagerb
02:32:56 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManager8setStackESt10unique_ptrI17ResourcePackStackSt14default_deleteIS1_EE21ResourcePackStackTypeb
02:32:56 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManager17onLanguageChangedEv
02:32:56 Error [MinecraftSymbols] Unresolved symbol: _ZN12PackInstanceC2EP12ResourcePackibP12PackSettings
02:32:56 Error [MinecraftSymbols] Unresolved symbol: _ZTV17ResourcePackStack
02:32:56 Error [MinecraftSymbols] Unresolved symbol: _ZN17ResourcePackStack3addE12PackInstanceRK22ResourcePackRepositoryb
02:32:56 Error [MinecraftSymbols] Unresolved symbol: _ZN22SaveTransactionManagerC2ESt8functionIFvbEE
02:32:56 Error [MinecraftSymbols] Unresolved symbol: _ZN9Scheduler17processCoroutinesENSt6chrono8durationIxSt5ratioILx1ELx1000000000EEEE
02:32:56 Error [MinecraftSymbols] Unresolved symbol: _ZN18MinecraftScheduler6clientEv
02:32:56 Error [MinecraftSymbols] Unresolved symbol: _ZN19ServerCommandOriginC2ERKSsR11ServerLevel22CommandPermissionLevel
02:32:56 Error [MinecraftSymbols] Unresolved symbol: _ZN16EducationOptionsC2EP19ResourcePackManager
02:32:56 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstanceC2ER13IMinecraftAppR30ServerInstanceEventCoordinator
02:32:56 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance16initializeServerER13IMinecraftAppR9WhitelistP15PermissionsFilePN4Core15FilePathManagerENSt6chrono8durationIxSt5ratioILx1ELx1EEEESsSsSs13LevelSettingsib20ConnectionDefinitionbRKSt6vectorISsSaISsEESsRKN3mce4UUIDER18IMinecraftEventingR22ResourcePackRepositoryRK18ContentTierManagerR19ResourcePackManagerSt8functionIFSt10unique_ptrI12LevelStorageSt14default_deleteIS10_EER9SchedulerEERKSsP9LevelDataSsSsSZ_I16EducationOptionsS11_IS1C_EEPSW_SY_IFvvEES1H_P13ServerMetricsP13DebugEndPointb
02:32:56 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstanceD2Ev
02:32:56 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance17startServerThreadEv
02:32:56 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance13leaveGameSyncEv
02:32:56 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance20queueForServerThreadESt8functionIFvvEE
02:32:56 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12MajorVersionE
02:32:56 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12MinorVersionE
02:32:56 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12PatchVersionE
02:32:56 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants15RevisionVersionE
02:32:56 Error [MinecraftSymbols] Unresolved symbol: _ZNK6Social4User11getLiveUserEv
02:32:56 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social12XboxLiveUser22_handleUISignInNoErrorERN4xbox8services6system14sign_in_resultESt8functionIFvNS_12SignInResultEbEE
02:32:56 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN9GameStore18onStoreInitializedEb
02:32:56 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN9GameStore22onQueryProductsSuccessERKSt6vectorI11ProductInfoSaIS1_EE
02:32:56 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social11UserManager17CreateUserManagerEv
02:32:56 Error [MinecraftSymbols] Unresolved symbol: _ZN2v82V810InitializeEv
02:32:56 Error [MinecraftSymbols] Unresolved symbol: _ZN2v82V818InitializePlatformEPNS_8PlatformE
02:32:56 Error [MinecraftSymbols] Unresolved symbol: _ZNK4pplx4taskIN4xbox8services16xbox_live_resultINS2_6system26token_and_signature_resultEEEE3getEv
02:32:56 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl15getOpenGLVendorEv
02:32:56 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl17getOpenGLRendererEv
02:32:56 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl16getOpenGLVersionEv
02:32:56 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl19getOpenGLExtensionsEv
02:32:56 Error [MinecraftSymbols] Unresolved symbol: _ZN3mce8Platform3OGL12InitBindingsEv
02:32:56 Trace [Patch] Patching - original: 85 83 87 86 131
02:32:56 Trace [Patch] Patching - result: 233 11 34 66 100
02:32:56 Warn  [Launcher] Android stub called
02:32:56 Warn  [Launcher] Android stub called
02:32:56 Warn  [Launcher] Android stub called
02:32:56 Warn  [Launcher] Android stub called
02:32:56 Warn  [Launcher] Android stub called
02:32:56 Info  [Minecraft] android_main starting. internalDataPath is './idata/', externalDataPath is './edata/'
02:32:56 Info  [Minecraft] NO LOG FILE! - AppPlatform_android::setStorageDirectory - using External dir - CurrentFileStoragePath is now '/home/krash/.local/share/mcpelauncher/'
02:32:56 Error [JNIVM] Object not found in current local layer
02:32:56 Debug [HttpCallStaticGlue] Successfully registerered HttpCall methods
02:32:56 Error [JNIVM] Object not found in current local layer
02:32:56 Debug [XSAPI.Android] Successfully registerered HttpCall methods
02:32:56 Error [JNIVM] Object not found in current local layer
02:32:56 Debug [HttpCallStaticGlue] Successfully registerered HttpCall methods
02:32:56 Error [JNIVM] Object not found in current local layer
02:32:56 Debug [XboxLiveAppConfig] Successfully registerered XboxLiveAppConfig methods
02:32:56 Error [JNIVM] Object not found in current local layer
02:32:56 Debug [XSAPI.Android] Successfully registerered HttpCall tcuiMethods
02:32:56 Trace [XBOXLive] Reading xbox config file
02:32:56 Warn  [Launcher] Android stub called
02:32:56 Warn  [Launcher] EGL stub eglMakeCurrent called
02:32:56 Warn  [Launcher] EGL stub eglMakeCurrent called
02:32:56 Warn  [Launcher] Android stub called
02:32:56 Warn  [Launcher] EGL stub eglMakeCurrent called
02:32:56 Warn  [Minecraft] NO LOG FILE! - [Device Lost] The graphics context was gained
02:32:56 Warn  [Minecraft] MinecraftGame::init && MinecraftGame::setSize!
02:32:57 Info  [Minecraft] NO LOG FILE! - IPv4 supported, port: 40600
02:32:57 Info  [Minecraft] NO LOG FILE! - IPv6 supported, port: 46082
02:32:57 Debug [XSAPI.Android] sign_in_impl: will NOT be showing UI
02:32:57 Info  [com::microsoft::xbox::idp::interop::Interop::LogTelemetrySignIn] API - signin_silently - :Entering
02:32:57 Trace [DaemonLauncher] Starting daemon: /bin/msa-daemon
02:33:06 Info  [com::microsoft::xbox::idp::interop::Interop::LogTelemetrySignIn] API - signin_silently - :Exiting
02:33:09 Info  [Minecraft] NO LOG FILE! - IPv4 supported, port: 36088
02:33:09 Info  [Minecraft] NO LOG FILE! - IPv6 supported, port: 59249
Signal 11 received
Backtrace elements: 7
#0 /bin/mcpelauncher-client(_ZN12CrashHandler12handleSignalEiPv+0xcc) [0x566bfb3c]
#1 linux-gate.so.1(__kernel_sigreturn+0) [0xf7f22ad0]
#2 /usr/lib32/libX11.so.6(Xutf8LookupString+0x4) [0xf7d4d8d4]
#3 /bin/mcpelauncher-client(+0xc1fb6) [0x566e8fb6]
#4 /bin/mcpelauncher-client(eglutPollEvents+0x27) [0x566e9377]
#5 HYBRIS AppPlatform_android::swapBuffers()+134 in libminecraftpe.so+0x968046 [0xee5dc046]
#6 [0x3f800000]
Dumping stack...
#5 HYBRIS (null)+-305709056 in libminecraftpe.so+0x0000 [0xedc74000]
#13 HYBRIS AppPlatform_android::swapBuffers()+134 in libminecraftpe.so+0x968046 [0xee5dc046]
#18 HYBRIS (null)+-183543548 in libminecraftpe.so+0x7481904 [0xf50f5904]
#67 HYBRIS (null)+-183543548 in libminecraftpe.so+0x7481904 [0xf50f5904]
#107 HYBRIS (null)+-183543548 in libminecraftpe.so+0x7481904 [0xf50f5904]
#134 HYBRIS (null)+0 in libminecraftpe.so+0x755bcd4 [0xf51cfcd4]
#145 HYBRIS (null)+0 in libminecraftpe.so+0x755bcd4 [0xf51cfcd4]
#159 HYBRIS (null)+-183543548 in libminecraftpe.so+0x7481904 [0xf50f5904]
#160 HYBRIS (null)+-242054475 in libminecraftpe.so+0x3cb4ab5 [0xf1928ab5]
#167 HYBRIS (null)+-214259600 in libminecraftpe.so+0x5736870 [0xf33aa870]
#170 HYBRIS (null)+-183543548 in libminecraftpe.so+0x7481904 [0xf50f5904]
#172 HYBRIS (null)+-277965880 in libminecraftpe.so+0x1a753c8 [0xef6e93c8]
#176 HYBRIS (null)+-271758379 in libminecraftpe.so+0x2060bd5 [0xefcd4bd5]
#179 HYBRIS (null)+-183543548 in libminecraftpe.so+0x7481904 [0xf50f5904]
#180 HYBRIS mcr::bindMigrationTextures(mce::RenderContext&, mce::GlobalConstantBuffers&, gsl::span<nonstd::variants::variant<nonstd::variants::monostate, mce::TexturePtr, mce::ClientResourcePointer<mce::ResourcePointer<mce::Texture, mce::ResourceBlockTemplate<mce::Texture, mce::PerFrameHandleTracker, mce::ResourceServiceTextureDescription>, std::shared_ptr> >, mce::ServerResourcePointer<mce::ResourcePointer<mce::Texture, mce::ResourceBlockTemplate<mce::Texture, mce::PerFrameHandleTracker, mce::ResourceServiceTextureDescription>, std::shared_ptr>, mce::AssertResourceServiceErrorHandler>, nonstd::variants::detail::TX<nonstd::variants::detail::S4>, nonstd::variants::detail::TX<nonstd::variants::detail::S5>, nonstd::variants::detail::TX<nonstd::variants::detail::S6>, nonstd::variants::detail::TX<nonstd::variants::detail::S7>, nonstd::variants::detail::TX<nonstd::variants::detail::S8>, nonstd::variants::detail::TX<nonstd::variants::detail::S9>, nonstd::variants::detail::TX<nonstd::variants::detail::S10>, nonstd::variants::detail::TX<nonstd::variants::detail::S11>, nonstd::variants::detail::TX<nonstd::variants::detail::S12>, nonstd::variants::detail::TX<nonstd::variants::detail::S13>, nonstd::variants::detail::TX<nonstd::variants::detail::S14>, nonstd::variants::detail::TX<nonstd::variants::detail::S15> > const, -1>)+1282 in libminecraftpe.so+0x3c24da2 [0xf1898da2]
#197 HYBRIS (null)+-215128697 in libminecraftpe.so+0x5662587 [0xf32d6587]
#198 HYBRIS (null)+-183543548 in libminecraftpe.so+0x7481904 [0xf50f5904]
#200 HYBRIS mce::TexturePtr::TexturePtr(mce::TexturePtr const&)+77 in libminecraftpe.so+0x3c45ffd [0xf18b9ffd]
#204 HYBRIS mce::TexturePtr::~TexturePtr()+11 in libminecraftpe.so+0x3c4615b [0xf18ba15b]
#210 HYBRIS (null)+-183543548 in libminecraftpe.so+0x7481904 [0xf50f5904]
#212 HYBRIS (null)+-271761347 in libminecraftpe.so+0x206003d [0xefcd403d]
#221 HYBRIS (null)+-183543548 in libminecraftpe.so+0x7481904 [0xf50f5904]
#250 HYBRIS (null)+-183543548 in libminecraftpe.so+0x7481904 [0xf50f5904]
#252 HYBRIS (null)+-271761251 in libminecraftpe.so+0x206009d [0xefcd409d]
#318 HYBRIS (null)+-188481536 in libminecraftpe.so+0x6fcc000 [0xf4c40000]
#637 HYBRIS (null)+-183278180 in libminecraftpe.so+0x74c259c [0xf513659c]
#653 HYBRIS (null)+-183543548 in libminecraftpe.so+0x7481904 [0xf50f5904]
#654 HYBRIS (null)+-183278180 in libminecraftpe.so+0x74c259c [0xf513659c]
#656 HYBRIS AppPlatform_android::swapBuffers()+134 in libminecraftpe.so+0x968046 [0xee5dc046]
#659 HYBRIS (null)+-213507872 in libminecraftpe.so+0x57ee0e0 [0xf34620e0]
#660 HYBRIS AppPlatform_android::swapBuffers()+8 in libminecraftpe.so+0x967fc8 [0xee5dbfc8]
#661 HYBRIS AppPlatform_android::swapBuffers()+0 in libminecraftpe.so+0x967fc0 [0xee5dbfc0]
#663 HYBRIS (null)+-183543548 in libminecraftpe.so+0x7481904 [0xf50f5904]
#664 HYBRIS (null)+-293091496 in libminecraftpe.so+0xc08758 [0xee87c758]
#665 HYBRIS (null)+-183278180 in libminecraftpe.so+0x74c259c [0xf513659c]
#666 HYBRIS (null)+-183270812 in libminecraftpe.so+0x74c4264 [0xf5138264]
#671 HYBRIS (null)+-183271028 in libminecraftpe.so+0x74c418c [0xf513818c]
#672 HYBRIS (null)+-183278180 in libminecraftpe.so+0x74c259c [0xf513659c]
#677 HYBRIS (null)+-184702532 in libminecraftpe.so+0x73669bc [0xf4fda9bc]
#689 HYBRIS (null)+-183183780 in libminecraftpe.so+0x74d965c [0xf514d65c]
#710 HYBRIS (null)+-183543548 in libminecraftpe.so+0x7481904 [0xf50f5904]
#712 HYBRIS BackgroundTaskQueue::_fetchAllAvailableTasks()+409 in libminecraftpe.so+0x3e61cd9 [0xf1ad5cd9]
#713 HYBRIS (null)+-183543548 in libminecraftpe.so+0x7481904 [0xf50f5904]
#722 HYBRIS (null)+-183543548 in libminecraftpe.so+0x7481904 [0xf50f5904]
#724 HYBRIS BackgroundTaskQueue::_fetchAllAvailableTasks()+409 in libminecraftpe.so+0x3e61cd9 [0xf1ad5cd9]
#728 HYBRIS BackgroundTaskQueue::tryPop(int)+685 in libminecraftpe.so+0x3e61a6d [0xf1ad5a6d]
#729 HYBRIS (null)+-183271008 in libminecraftpe.so+0x74c41a0 [0xf51381a0]
#736 HYBRIS (null)+-183543548 in libminecraftpe.so+0x7481904 [0xf50f5904]
#737 HYBRIS (null)+-183270920 in libminecraftpe.so+0x74c41f8 [0xf51381f8]
#774 HYBRIS (null)+-183543548 in libminecraftpe.so+0x7481904 [0xf50f5904]
#787 HYBRIS (null)+-215193111 in libminecraftpe.so+0x56529e9 [0xf32c69e9]
#790 HYBRIS (null)+-183543548 in libminecraftpe.so+0x7481904 [0xf50f5904]
#793 HYBRIS (null)+-183270812 in libminecraftpe.so+0x74c4264 [0xf5138264]
#797 HYBRIS (null)+-183270832 in libminecraftpe.so+0x74c4250 [0xf5138250]
#800 HYBRIS (null)+-215193077 in libminecraftpe.so+0x5652a0b [0xf32c6a0b]
#801 HYBRIS (null)+-183270852 in libminecraftpe.so+0x74c423c [0xf513823c]
#804 HYBRIS getTimeS()+38 in libminecraftpe.so+0x3e49bd6 [0xf1abdbd6]
#805 HYBRIS (null)+-183270940 in libminecraftpe.so+0x74c41e4 [0xf51381e4]
#811 HYBRIS (null)+-215193111 in libminecraftpe.so+0x56529e9 [0xf32c69e9]
#812 HYBRIS (null)+-183543548 in libminecraftpe.so+0x7481904 [0xf50f5904]
#850 HYBRIS (null)+-183543548 in libminecraftpe.so+0x7481904 [0xf50f5904]
#852 HYBRIS (null)+-293112303 in libminecraftpe.so+0xc03611 [0xee877611]
#863 HYBRIS (null)+-183271679 in libminecraftpe.so+0x74c3f01 [0xf5137f01]
#867 HYBRIS (null)+-183271679 in libminecraftpe.so+0x74c3f01 [0xf5137f01]
#873 HYBRIS (null)+-183271468 in libminecraftpe.so+0x74c3fd4 [0xf5137fd4]
#877 HYBRIS (null)+-183271696 in libminecraftpe.so+0x74c3ef0 [0xf5137ef0]
#885 HYBRIS (null)+-292820480 in libminecraftpe.so+0xc4aa00 [0xee8bea00]
#886 HYBRIS (null)+-292821360 in libminecraftpe.so+0xc4a690 [0xee8be690]
#889 HYBRIS (null)+-292821472 in libminecraftpe.so+0xc4a620 [0xee8be620]
#890 HYBRIS (null)+-292822080 in libminecraftpe.so+0xc4a3c0 [0xee8be3c0]
#893 HYBRIS (null)+-292822176 in libminecraftpe.so+0xc4a360 [0xee8be360]
#894 HYBRIS (null)+-292822320 in libminecraftpe.so+0xc4a2d0 [0xee8be2d0]
#897 HYBRIS (null)+-292822784 in libminecraftpe.so+0xc4a100 [0xee8be100]
#898 HYBRIS (null)+-292822992 in libminecraftpe.so+0xc4a030 [0xee8be030]
#901 HYBRIS (null)+-292823088 in libminecraftpe.so+0xc49fd0 [0xee8bdfd0]
#902 HYBRIS (null)+-292823136 in libminecraftpe.so+0xc49fa0 [0xee8bdfa0]
#917 HYBRIS (null)+-183271448 in libminecraftpe.so+0x74c3fe8 [0xf5137fe8]
#921 HYBRIS (null)+-183271508 in libminecraftpe.so+0x74c3fac [0xf5137fac]
#927 HYBRIS (null)+-183271636 in libminecraftpe.so+0x74c3f2c [0xf5137f2c]
#928 HYBRIS (null)+-295762612 in libminecraftpe.so+0x97c54c [0xee5f054c]
#933 HYBRIS (null)+-183271616 in libminecraftpe.so+0x74c3f40 [0xf5137f40]
#935 HYBRIS (null)+-187957248 in libminecraftpe.so+0x704c000 [0xf4cc0000]
#940 HYBRIS (null)+-183278080 in libminecraftpe.so+0x74c2600 [0xf5136600]
#942 HYBRIS (null)+-183543548 in libminecraftpe.so+0x7481904 [0xf50f5904]
#944 HYBRIS (null)+1112 in libminecraftpe.so+0x97ae88 [0xee5eee88]
#954 HYBRIS (null)+-183278180 in libminecraftpe.so+0x74c259c [0xf513659c]
#958 HYBRIS (null)+-281745232 in libminecraftpe.so+0x16da8b0 [0xef34e8b0]
#976 HYBRIS (null)+-295739632 in libminecraftpe.so+0x981f10 [0xee5f5f10]
#980 HYBRIS (null)+-214953844 in libminecraftpe.so+0x568d08c [0xf330108c]
#994 HYBRIS (null)+-295740432 in libminecraftpe.so+0x981bf0 [0xee5f5bf0]
#995 HYBRIS (null)+-295740656 in libminecraftpe.so+0x981b10 [0xee5f5b10]
#998 HYBRIS (null)+-183362252 in libminecraftpe.so+0x74add34 [0xf5121d34]
#999 HYBRIS (null)+-182653500 in libminecraftpe.so+0x755adc4 [0xf51cedc4]
Process exited with unexpected exit code: 6

**Comment by ChristopherHX** [comment]
This crash is resolved with https://github.com/ChristopherHX/mcpelauncher-manifest/commit/4701b0f25ebe63652f34c1dd6bc0c3c56759a75d
Your libX11 is broken (only some distros) and crash if IME isn't disabled
**/usr/lib32/libX11.so.6(Xutf8LookupString+0x4) [0xf7d4d8d4]**
Xutf8LookupString should never crash, if used correctly
