### ISSUE TITLE
Some suggestion about that how select the game version

### ISSUE THREAD

**Issue by srauni** [minecraft-linux/mcpelauncher-manifest#245]
In commits, MCMrARM say that '1.14.1.3 and 1.14.1.5 support', So we should search 'download minecraft pe x86 1.14.1.3' with Google.
the link of results is my recommendation [https://www.apksum.com/download/com.mojang.minecraftpe_1.14.1.3_x86](url)
My server is running latest bedrock version(1.14.32.1)，The version of game can running well at my server.

**Comment by ChristopherHX** [comment]
> So we should search 'download minecraft pe x86 1.14.1.3' with Google.
# No it is illegal to pirate the game!
Buy the Game **(Google Play)**
login to your google account
select a version from the versionseditor

You can play any Minecraft 0.12 to 1.16.0 version with if you buy the Game on google play with my updated launcher https://github.com/ChristopherHX/mcpelauncher-manifest/releases/tag/stable
