### ISSUE TITLE
Can't sign into Google on macOS Catalina

### ISSUE THREAD

**Issue by Kurgol** [minecraft-linux/mcpelauncher-manifest#251]
When I launch the Linux Minecraft Launcher on macOS Catalina 10.15.3 It prompts me to `Sign in with Google`.  When I click to sign in I get an error message telling me my browser or app may not be secure:

![Screen Shot 2020-03-23 at 3 13 59 PM](https://user-images.githubusercontent.com/15245142/77332899-8f5c7580-6d1a-11ea-8673-f7a9e5926275.png)

**Comment by gerardreches** [comment]
Same here

**Comment by Mhowser** [comment]
Catalina is unsupported due to it unable to run 32bit programs. Minecraft is 32bit.

**Comment by Mhowser** [comment]
Downgrade to Mojave or switch to Linux.

**Comment by Kurgol** [comment]
You should probably update the documentation to say it doesn't support Catalina then, as it's [not mentioned in the documentation](https://mcpelauncher.readthedocs.io/en/latest/getting_started.html#macos) @Mhowser .
