### ISSUE TITLE
Any plan to support 64-bit Catalina?

### ISSUE THREAD

**Issue by le0-VV** [minecraft-linux/mcpelauncher-manifest#253]
Cant launch game in macOS Catalina due to bad cpu type (ie: 32-bit app not supported)

Is there a plan to add 64-bit support in the future?

**Comment by Mhowser** [comment]
No, not until Minecraft is released as a 64bit program, currently it is 32bit.

If you want to play now, either downgrade to Mojave or switch to Linux. ElementaryOS has a similar UI to Mac.
