### ISSUE TITLE
game keeps crashing during gameplay after appimage update (1.16 beta)

### ISSUE THREAD

**Issue by teh404guy** [minecraft-linux/mcpelauncher-manifest#255]
Output:
19:08:21 Info  [Launcher] Version: client 7c17ac3 / manifest 3e4d79d
19:08:21 Info  [Launcher] CPU: GenuineIntel        Intel(R) Core(TM) i5-2540M CPU @ 2.60GHz
19:08:21 Info  [Launcher] CPU supports SSSE3: YES
19:08:21 Trace [Launcher] Loading hybris libraries
19:08:21 Trace [HybrisUtils] Loaded OS library /tmp/.mount_MinecrIaimig/usr/share/mcpelauncher/libs/native/libfmod.so.9.16
19:08:21 Trace [HybrisUtils] Loaded OS library libm.so.6
19:08:21 Trace [HybrisUtils] Loaded OS library libz.so.1
19:08:21 Info  [Launcher] Creating window
19:08:21 Trace [Launcher] Loading gamepad mappings: /tmp/.mount_MinecrIaimig/usr/share/mcpelauncher/gamecontrollerdb.txt
_eglutReadPNG: fopen failed
19:08:21 Trace [Launcher] Loading Minecraft library
19:08:21 Info  [Launcher] Loaded Minecraft library
19:08:21 Debug [Launcher] Minecraft is at offset 0xe30f6000
19:08:21 Trace [AppPlatform] Vtable size = 300
19:08:21 Trace [Patch] Patching - original: 85 83 87 86 129
19:08:21 Trace [Patch] Patching - result: 233 165 2 68 32
19:08:21 Trace [Patch] Patching - original: 85 83 87 86 131
19:08:21 Trace [Patch] Patching - result: 233 50 203 59 32
19:08:21 Warn  [Launcher] Android stub called
19:08:21 Warn  [Launcher] Android stub called
19:08:21 Warn  [Launcher] Android stub called
19:08:21 Warn  [Launcher] Android stub called
19:08:21 Warn  [Launcher] Android stub called
19:08:21 Info  [Minecraft] android_main starting. internalDataPath is './idata/', externalDataPath is './edata/'
19:08:21 Info  [Minecraft] NO LOG FILE! - AppPlatform_android::setStorageDirectory - using External dir - CurrentFileStoragePath is now '/home/ilyas/.local/share/mcpelauncher/'
19:08:21 Error [JNIVM] Object not found in current local layer
19:08:21 Debug [HttpCallStaticGlue] Successfully registerered HttpCall methods
19:08:21 Error [JNIVM] Object not found in current local layer
19:08:21 Debug [XSAPI.Android] Successfully registerered HttpCall methods
19:08:21 Error [JNIVM] Object not found in current local layer
19:08:21 Debug [HttpCallStaticGlue] Successfully registerered HttpCall methods
19:08:21 Error [JNIVM] Object not found in current local layer
19:08:21 Debug [XboxLiveAppConfig] Successfully registerered XboxLiveAppConfig methods
19:08:21 Error [JNIVM] Object not found in current local layer
19:08:21 Debug [XSAPI.Android] Successfully registerered HttpCall tcuiMethods
19:08:21 Trace [XBOXLive] Reading xbox config file
19:08:21 Warn  [Launcher] Android stub called
19:08:21 Warn  [Launcher] EGL stub eglMakeCurrent called
19:08:21 Warn  [Launcher] EGL stub eglMakeCurrent called
19:08:21 Warn  [Launcher] Android stub called
19:08:21 Warn  [Launcher] EGL stub eglMakeCurrent called
19:08:21 Warn  [Minecraft] NO LOG FILE! - [Device Lost] The graphics context was gained
19:08:21 Warn  [Minecraft] MinecraftGame::init && MinecraftGame::setSize!
19:08:22 Warn  [Launcher] Android stub called
19:08:22 Warn  [Launcher] Android stub called
19:08:22 Warn  [Launcher] Android stub called
19:08:22 Warn  [Launcher] Android stub called
19:08:22 Warn  [Launcher] Android stub called
19:08:22 Warn  [Launcher] Android stub called
19:08:22 Warn  [Launcher] Android stub called
19:08:22 Warn  [Launcher] Android stub called
19:08:22 Warn  [Launcher] Android stub called
19:08:22 Warn  [Launcher] Android stub called
19:08:22 Warn  [Launcher] Android stub called
19:08:22 Warn  [Launcher] Android stub called
19:08:22 Warn  [Launcher] Android stub called
19:08:23 Debug [XSAPI.Android] sign_in_impl: will NOT be showing UI
19:08:23 Info  [com::microsoft::xbox::idp::interop::Interop::LogTelemetrySignIn] API - signin_silently - :Entering
19:08:23 Trace [DaemonLauncher] Starting daemon: /tmp/.mount_MinecrIaimig/usr/bin/./msa-daemon
19:08:24 Info  [com::microsoft::xbox::idp::interop::Interop::LogTelemetrySignIn] API - signin_silently - :Exiting
19:08:28 Warn  [Launcher] Android stub called
19:08:29 Info  [Minecraft] NO LOG FILE! - IPv4 supported, port: 34333
19:08:29 Info  [Minecraft] NO LOG FILE! - IPv6 supported, port: 45942
19:08:29 Info  [Minecraft] NO LOG FILE! - IPv4 supported, port: 59325
19:08:29 Info  [Minecraft] NO LOG FILE! - IPv6 supported, port: 37367
19:08:34 Warn  [Launcher] Android stub called
19:09:00 Info  [Minecraft] NO LOG FILE! - opening /home/ilyas/.local/share/mcpelauncher/games/com.mojang/minecraftWorlds/kQt2XnJqFQA=/db
19:09:01 Info  [Minecraft] NO LOG FILE! - IPv4 supported, port: 49807
19:09:01 Info  [Minecraft] NO LOG FILE! - IPv6 supported, port: 47342
19:09:01 Info  [Minecraft] NO LOG FILE! - IPv4 supported, port: 19132
19:09:01 Info  [Minecraft] NO LOG FILE! - IPv6 supported, port: 19133
19:09:01 Info  [Minecraft] NO LOG FILE! - Player connected: Teh404guy, xuid: 2535471983349619
19:09:02 Warn  [Launcher] Android stub called
19:09:02 Trace [Minecraft] NO LOG FILE! - DBStorage - Compaction Starting...
19:09:02 Trace [Minecraft] NO LOG FILE! - DBStorage - Compaction Complete.
19:09:02 Trace [Minecraft] NO LOG FILE! - Scheduling AutoCompaction...
19:09:02 Trace [Minecraft] NO LOG FILE! - DBStorage - Compaction Starting...
19:09:03 Trace [Minecraft] NO LOG FILE! - DBStorage - Compaction Complete.
19:09:03 Trace [Minecraft] NO LOG FILE! - Scheduling AutoCompaction...
Signal 11 received
Backtrace elements: 5
#0 /tmp/.mount_MinecrIaimig/usr/bin/./mcpelauncher-client(_ZN12CrashHandler12handleSignalEiPv+0xb7) [0x8325aa5]
#1 linux-gate.so.1(__kernel_sigreturn+0) [0xf7f3cb60]
#2 HYBRIS (null)+-433488701 in libminecraftpe.so+0x31a1cc3 [0xe6297cc3]
#3 [(nil)]
#4 [0x180]
Dumping stack...
#13 HYBRIS (null)+-485531648 in libminecraftpe.so+0x0000 [0xe30f6000]
#18 HYBRIS (null)+-433488701 in libminecraftpe.so+0x31a1cc3 [0xe6297cc3]
#22 HYBRIS (null)+-351957492 in libminecraftpe.so+0x7f62e0c [0xeb058e0c]
#24 HYBRIS (null)+-425897672 in libminecraftpe.so+0x38df138 [0xe69d5138]
#28 HYBRIS (null)+-425898325 in libminecraftpe.so+0x38deeab [0xe69d4eab]
#36 HYBRIS (null)+-473097172 in libminecraftpe.so+0xbdbc2c [0xe3cd1c2c]
#77 HYBRIS (null)+-351957492 in libminecraftpe.so+0x7f62e0c [0xeb058e0c]
#90 HYBRIS (null)+-351957492 in libminecraftpe.so+0x7f62e0c [0xeb058e0c]
#96 HYBRIS (null)+-433488701 in libminecraftpe.so+0x31a1cc3 [0xe6297cc3]
#104 HYBRIS (null)+-425897672 in libminecraftpe.so+0x38df138 [0xe69d5138]
#108 HYBRIS (null)+-425898325 in libminecraftpe.so+0x38deeab [0xe69d4eab]
#116 HYBRIS (null)+-427723135 in libminecraftpe.so+0x3721681 [0xe6817681]
#126 HYBRIS (null)+-386460777 in libminecraftpe.so+0x5e7b397 [0xe8f71397]
#127 HYBRIS (null)+-386460758 in libminecraftpe.so+0x5e7b3aa [0xe8f713aa]
#128 HYBRIS (null)+-386460689 in libminecraftpe.so+0x5e7b3ef [0xe8f713ef]
#129 HYBRIS (null)+-386460617 in libminecraftpe.so+0x5e7b437 [0xe8f71437]
#140 HYBRIS (null)+-427749495 in libminecraftpe.so+0x371af89 [0xe6810f89]
#146 HYBRIS (null)+-351957492 in libminecraftpe.so+0x7f62e0c [0xeb058e0c]
#148 HYBRIS (null)+-425895953 in libminecraftpe.so+0x38df7ef [0xe69d57ef]
#152 HYBRIS (null)+-434422260 in libminecraftpe.so+0x30bde0c [0xe61b3e0c]
#163 HYBRIS (null)+-386460777 in libminecraftpe.so+0x5e7b397 [0xe8f71397]
#172 HYBRIS (null)+-434422260 in libminecraftpe.so+0x30bde0c [0xe61b3e0c]
#175 HYBRIS (null)+-386460777 in libminecraftpe.so+0x5e7b397 [0xe8f71397]
#178 HYBRIS (null)+-351957492 in libminecraftpe.so+0x7f62e0c [0xeb058e0c]
#180 HYBRIS (null)+-434569014 in libminecraftpe.so+0x309a0ca [0xe61900ca]
#184 HYBRIS (null)+-434577759 in libminecraftpe.so+0x3097ea1 [0xe618dea1]
#195 HYBRIS std::string::assign(std::string const&)+9 in libgnustl_shared.so+0xca699 [0xeb1f8699]
#196 HYBRIS (null)+-351957492 in libminecraftpe.so+0x7f62e0c [0xeb058e0c]
#199 HYBRIS (null)+-351957492 in libminecraftpe.so+0x7f62e0c [0xeb058e0c]
#200 HYBRIS StringKey::operator==(StringKey const&) const+207 in libminecraftpe.so+0x466ffcf [0xe7765fcf]
#224 HYBRIS (null)+-459087140 in libminecraftpe.so+0x19382dc [0xe4a2e2dc]
#230 HYBRIS (null)+-351993854 in libminecraftpe.so+0x7f5a002 [0xeb050002]
#232 HYBRIS (null)+-425776125 in libminecraftpe.so+0x38fcc03 [0xe69f2c03]
#240 HYBRIS (null)+-350011884 in libgnustl_shared.so+0x105e14 [0xeb233e14]
#244 HYBRIS operator delete(void*)+28 in libgnustl_shared.so+0x4e09c [0xeb17c09c]
#247 HYBRIS (null)+-351957492 in libminecraftpe.so+0x7f62e0c [0xeb058e0c]
#250 HYBRIS operator delete(void*)+6 in libgnustl_shared.so+0x4e086 [0xeb17c086]
#251 HYBRIS (null)+-351957492 in libminecraftpe.so+0x7f62e0c [0xeb058e0c]
#252 HYBRIS (null)+-425871457 in libminecraftpe.so+0x38e579f [0xe69db79f]
#259 HYBRIS (null)+-351957492 in libminecraftpe.so+0x7f62e0c [0xeb058e0c]
#264 HYBRIS (null)+-425909316 in libminecraftpe.so+0x38dc3bc [0xe69d23bc]
#268 HYBRIS (null)+-425932602 in libminecraftpe.so+0x38d68c6 [0xe69cc8c6]
#295 HYBRIS (null)+-425932602 in libminecraftpe.so+0x38d68c6 [0xe69cc8c6]
#404 HYBRIS (null)+-425785399 in libminecraftpe.so+0x38fa7c9 [0xe69f07c9]
#408 HYBRIS (null)+-425785652 in libminecraftpe.so+0x38fa6cc [0xe69f06cc]
#504 HYBRIS (null)+-423195540 in libminecraftpe.so+0x3b72c6c [0xe6c68c6c]
#510 HYBRIS (null)+-351957492 in libminecraftpe.so+0x7f62e0c [0xeb058e0c]
#512 HYBRIS (null)+-433488765 in libminecraftpe.so+0x31a1c83 [0xe6297c83]
#519 HYBRIS (null)+-351957492 in libminecraftpe.so+0x7f62e0c [0xeb058e0c]
#520 HYBRIS (null)+-433471610 in libminecraftpe.so+0x31a5f86 [0xe629bf86]
#524 HYBRIS (null)+-433471685 in libminecraftpe.so+0x31a5f3b [0xe629bf3b]
#538 HYBRIS (null)+-351957492 in libminecraftpe.so+0x7f62e0c [0xeb058e0c]
#540 HYBRIS (null)+-433382556 in libminecraftpe.so+0x31bbb64 [0xe62b1b64]
#550 HYBRIS (null)+-351957492 in libminecraftpe.so+0x7f62e0c [0xeb058e0c]
#552 HYBRIS (null)+-435756373 in libminecraftpe.so+0x2f782ab [0xe606e2ab]
#565 HYBRIS (null)+-351600320 in libminecraftpe.so+0x7fba140 [0xeb0b0140]
#576 HYBRIS (null)+-350011884 in libgnustl_shared.so+0x105e14 [0xeb233e14]
#585 HYBRIS (null)+-435756992 in libminecraftpe.so+0x2f78040 [0xe606e040]
#586 HYBRIS (null)+-351957492 in libminecraftpe.so+0x7f62e0c [0xeb058e0c]
#588 HYBRIS (null)+-425359324 in libminecraftpe.so+0x3962824 [0xe6a58824]
#591 HYBRIS (null)+-351957492 in libminecraftpe.so+0x7f62e0c [0xeb058e0c]
#595 HYBRIS (null)+-351957492 in libminecraftpe.so+0x7f62e0c [0xeb058e0c]
#596 HYBRIS (null)+-425430328 in libminecraftpe.so+0x39512c8 [0xe6a472c8]
#615 HYBRIS (null)+-351498696 in libminecraftpe.so+0x7fd2e38 [0xeb0c8e38]
#627 HYBRIS (null)+-425359312 in libminecraftpe.so+0x3962830 [0xe6a58830]
#628 HYBRIS (null)+-425359392 in libminecraftpe.so+0x39627e0 [0xe6a587e0]
#631 HYBRIS (null)+-425359488 in libminecraftpe.so+0x3962780 [0xe6a58780]
#632 HYBRIS (null)+-425359792 in libminecraftpe.so+0x3962650 [0xe6a58650]
#635 HYBRIS (null)+-425359888 in libminecraftpe.so+0x39625f0 [0xe6a585f0]
#636 HYBRIS (null)+-425359952 in libminecraftpe.so+0x39625b0 [0xe6a585b0]
#646 HYBRIS (null)+-351957492 in libminecraftpe.so+0x7f62e0c [0xeb058e0c]
#648 HYBRIS (null)+-435770689 in libminecraftpe.so+0x2f74abf [0xe606aabf]
#652 HYBRIS std::chrono::_V2::steady_clock::now()+43 in libgnustl_shared.so+0xb74fb [0xeb1e54fb]
#662 HYBRIS (null)+-351957492 in libminecraftpe.so+0x7f62e0c [0xeb058e0c]
#664 HYBRIS (null)+-419366892 in libminecraftpe.so+0x3f19814 [0xe700f814]
#667 HYBRIS (null)+-351957492 in libminecraftpe.so+0x7f62e0c [0xeb058e0c]
#668 HYBRIS (null)+-422880908 in libminecraftpe.so+0x3bbf974 [0xe6cb5974]
#670 HYBRIS (null)+-351496316 in libminecraftpe.so+0x7fd3784 [0xeb0c9784]
#673 HYBRIS (null)+-449345080 in libminecraftpe.so+0x22829c8 [0xe53789c8]
#692 HYBRIS (null)+-351957492 in libminecraftpe.so+0x7f62e0c [0xeb058e0c]
#696 HYBRIS getTimeMs()+38 in libminecraftpe.so+0x467ab26 [0xe7770b26]
#703 HYBRIS (null)+-351496316 in libminecraftpe.so+0x7fd3784 [0xeb0c9784]
#711 HYBRIS (null)+-351957492 in libminecraftpe.so+0x7f62e0c [0xeb058e0c]
#712 HYBRIS (null)+-434742430 in libminecraftpe.so+0x306fb62 [0xe6165b62]
#715 HYBRIS std::chrono::_V2::steady_clock::now()+9 in libgnustl_shared.so+0xb74d9 [0xeb1e54d9]
#718 HYBRIS (null)+-351957492 in libminecraftpe.so+0x7f62e0c [0xeb058e0c]
#720 HYBRIS (null)+-435789462 in libminecraftpe.so+0x2f7016a [0xe606616a]
#726 HYBRIS operator delete(void*)+6 in libgnustl_shared.so+0x4e086 [0xeb17c086]
#728 HYBRIS (null)+-350011884 in libgnustl_shared.so+0x105e14 [0xeb233e14]
#732 HYBRIS operator delete(void*)+28 in libgnustl_shared.so+0x4e09c [0xeb17c09c]
#735 HYBRIS (null)+-351957492 in libminecraftpe.so+0x7f62e0c [0xeb058e0c]
#736 HYBRIS (null)+-430370158 in libminecraftpe.so+0x349b292 [0xe6591292]
#738 HYBRIS operator delete(void*)+6 in libgnustl_shared.so+0x4e086 [0xeb17c086]
#739 HYBRIS (null)+-351957492 in libminecraftpe.so+0x7f62e0c [0xeb058e0c]
#740 HYBRIS (null)+-430366545 in libminecraftpe.so+0x349c0af [0xe65920af]
#747 HYBRIS (null)+-351600344 in libminecraftpe.so+0x7fba128 [0xeb0b0128]
#748 HYBRIS (null)+-430369431 in libminecraftpe.so+0x349b569 [0xe6591569]
#749 HYBRIS (null)+-351600412 in libminecraftpe.so+0x7fba0e4 [0xeb0b00e4]
#758 HYBRIS (null)+-351957492 in libminecraftpe.so+0x7f62e0c [0xeb058e0c]
#760 HYBRIS (null)+-435779878 in libminecraftpe.so+0x2f726da [0xe60686da]
#774 HYBRIS (null)+-452443870 in libminecraftpe.so+0x1f8e122 [0xe5084122]
#776 HYBRIS (null)+-435779136 in libminecraftpe.so+0x2f729c0 [0xe60689c0]
#786 HYBRIS (null)+-350011884 in libgnustl_shared.so+0x105e14 [0xeb233e14]
#788 HYBRIS (null)+47 in libgnustl_shared.so+0xbca5f [0xeb1eaa5f]
#792 HYBRIS (null)+8 in libgnustl_shared.so+0xbca38 [0xeb1eaa38]
Process exited with unexpected exit code: 6

OS:5.4.24-1-MANJARO

**Comment by ChristopherHX** [comment]
Wrong repo, refer to my version on github.
Found under forks.
1.16 beta is unstable, consider going back to 1.14.30.2

**Comment by ChristopherHX** [comment]
I close this, because some 1.16 beta's wasn't working fine.
But newer betas are more stable again.
I won't fix Minecraft Betas to be more stable than they are.

Minecraft displays on world loading something like "More crashes in beta, less in the Release"
