### ISSUE TITLE
Error occured while extracting .apk appimage version

### ISSUE THREAD

**Issue by SuperEndermanSM** [minecraft-linux/mcpelauncher-manifest#258]
see the screenshot here
[http://www.shenmo.tech:38324/other/%26%2328145%3B%26%2324230%3B%26%2325130%3B%26%2322270%3B_%26%2336873%3B%26%2325321%3B%26%2321306%3B%26%2322495%3B_20200325214827.png](url)

**Comment by SuperEndermanSM** [comment]
http://www.shenmo.tech:38324/other/%26%2328145%3B%26%2324230%3B%26%2325130%3B%26%2322270%3B_%26%2336873%3B%26%2325321%3B%26%2321306%3B%26%2322495%3B_20200325214827.png

**Comment by SuperEndermanSM** [comment]
http://www.shenmo.tech:38324/other/%26%2328145%3B%26%2324230%3B%26%2325130%3B%26%2322270%3B_%26%2336873%3B%26%2325321%3B%26%2321306%3B%26%2322495%3B_20200325214827.png

**Comment by ChristopherHX** [comment]
Only unencryped legal apk's are tested **and** working.
Can be obtained by this launcher via google login.
Using the Aurora Store Android App proved to work too.

**Comment by SuperEndermanSM** [comment]
> Only unencryped legal apk's are tested **and** working.
> Can be obtained by this launcher via google login.
> Using the Aurora Store Android App proved to work too.

Can I unzip the apk and repack in .zip?
As you know,I cannot login my google account in China mainland

**Comment by ChristopherHX** [comment]
I think yes normal zip archiver generates readable archives for the launcher.

**Comment by SuperEndermanSM** [comment]
> I think yes normal zip archiver generates readable archives for the launcher.

sorry to bother you,but there was another error occured while I use the repacked .zip
http://www.shenmo.tech:38324/other/%26%2328145%3B%26%2324230%3B%26%2325130%3B%26%2322270%3B_%26%2336873%3B%26%2325321%3B%26%2321306%3B%26%2322495%3B_20200327175604.png
This time it unziped correctly
It occored even when I run it as root.
The zip file was a repack of the apk from google play(I got it from my friend)
I think maybe I should look for some VPN access  :-(

**Comment by SuperEndermanSM** [comment]
BTW the distro is deepin 15.11 stable,Kernel: x86_64 Linux 5.4.0-050400-generic
My friend told me that it was an important information for the Software Engineers to solve problems

**Comment by ChristopherHX** [comment]
You can extract it yourself the folder should look like this.
```
~/.local/share/mcpelauncher/versions/0.0.0.0/
├── assets
│   ├── animation
│   ├── behavior_packs
│   ├── credits
│   ├── def_action_test.json
│   ├── definitions
│   ├── Empty.txt
│   ├── fonts
│   ├── gui
│   ├── icon.png
│   ├── profanity_filter.wlist
│   ├── renderer
│   ├── resource_packs
│   ├── shaders
│   ├── skin_packs
│   ├── store
│   ├── structures
│   ├── texture_backwards_compatibility_mapping.json
│   ├── transferMarkers
│   ├── treatments
│   ├── uniforms.json
│   └── xboxservices.config
└── libs
    └── libminecraftpe.so
```

And the parent folder have a file called `~/.local/share/mcpelauncher/versions/versions.ini`
Which contains all installed version, (1.16.0.53 should be the folder name, versionCode should be a number like the one for Beta 1.16.0.53)
```
[1.16.0.53]
versionCode=942160053
versionName=1.16.0.53
```

These Versions are known to work with this repository 0.12-1.13.0.6, 1.13.0.15(\*), 1.13.0.34(\*), 1.14.1.3(\*) and 1.14.1.5(\*)
\*: Only Linux/x86
Try my version if you wish to run newer versions (1.13+) not covered by the list
Link under github forks.

**Comment by ChristopherHX** [comment]
BTW The apk must be the x86 Version, not the one used by a almost all Phones, only Tablets running Android x86(_64) use the same apk

**Comment by SuperEndermanSM** [comment]
> BTW The apk must be the x86 Version, not the one used by a almost all Phones, only Tablets running Android x86(_64) use the same apk

I think I've got the point, I was using an arm package
I will try to get a x86 package
thank you very much for answering mu question!
;-)
