### ISSUE TITLE
Error occured while trying to login with google account (Appimage version)

### ISSUE THREAD

**Issue by SuperEndermanSM** [minecraft-linux/mcpelauncher-manifest#260]
qrc:/qml/ThemedControls/PlayButton.qml:8:30: Unable to assign null to QString
[18779:18818:0328/193121.637489:ERROR:nss_util.cc(712)] Error initializing NSS with a persistent database (sql:/home/sesm/.pki/nssdb): libsoftokn3.so: 无法打开共享对象文件: 没有那个文件或目录
[18779:18818:0328/193121.637738:ERROR:nss_util.cc(201)] Error initializing NSS without a persistent database: NSS error code: -5925
[18779:18818:0328/193121.637769:FATAL:nss_util.cc(203)] nss_error=-5925, os_error=0
#0 0x7f447408a16e <unknown>
#1 0x7f447409c8ae <unknown>
#2 0x7f44748592da <unknown>
#3 0x7f44748596e0 <unknown>
#4 0x7f4474787dc5 <unknown>
#5 0x7f44746747e7 <unknown>
#6 0x7f447463fad7 <unknown>
#7 0x7f44737d689a <unknown>
#8 0x7f44737d7e06 <unknown>
#9 0x7f44737d9dd7 <unknown>
#10 0x7f44739b2857 <unknown>
#11 0x7f4473ce90b0 <unknown>
#12 0x7f44740ffc59 <unknown>
#13 0x7f44740a4ff0 <unknown>
#14 0x7f44740a6cbd <unknown>
#15 0x7f44740a7178 <unknown>
#16 0x7f44740a8610 <unknown>
#17 0x7f44740a4095 <unknown>
#18 0x7f44740c0bba <unknown>
#19 0x7f44739eba68 <unknown>
#20 0x7f44739ebc4b <unknown>
#21 0x7f44740d8890 <unknown>
#22 0x7f44740d496d <unknown>
#23 0x7f4470cec494 start_thread
#24 0x7f447018facf clone

**Comment by SuperEndermanSM** [comment]
It  crashed after I press ther login button

**Comment by ChristopherHX** [comment]
My fix is now merged, redownload the AppImage from the wiki and login to google won't crash anymore.

**Comment by SuperEndermanSM** [comment]
> My fix is now merged, redownload the AppImage from the wiki and login to google won't crash anymore.

Cannot login to Microsoft profile

**Comment by SuperEndermanSM** [comment]
> My fix is now merged, redownload the AppImage from the wiki and login to google won't crash anymore.

Cannot login to Microsoft profile
Appimage version！
