### ISSUE TITLE
Multiplayer

### ISSUE THREAD

**Issue by jollyzen** [minecraft-linux/mcpelauncher-manifest#261]
I get the pop up to sign in with my microsoft account (which is actually my gmail sign in). I Can see my friend to invite if I create a world. They never get the invite. They are playing on PS4 and I am on linux (ubuntu 19.10)

**Comment by ChristopherHX** [comment]
Handling invites is not supported, e.g. this launcher can't receive them to join a world.

**Comment by ChristopherHX** [comment]
duplicate of #134
