### ISSUE TITLE
/usr/bin/mcpelauncher-client: error while loading shared libraries: libEGL.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by SkycladObserver0** [minecraft-linux/mcpelauncher-manifest#262]
Title basically says it all. Full error says
`/usr/bin/mcpelauncher-client: error while loading shared libraries: libEGL.so.1: cannot open shared object file: No such file or directory
Process exited with unexpected exit code: 127`
Trying to run Minecraft 1.14.1.5

**Comment by Mhowser** [comment]
Install 32bit graphics drivers as per the instructions found in the wiki.

**Comment by AtomynosAtom** [comment]
Just use the forked one by ChristopherHX.

**Comment by ChristopherHX** [comment]
duplicate of #94
