### ISSUE TITLE
Minecraft has exited with a non-zero error code

### ISSUE THREAD

**Issue by trumpetdootdoot** [minecraft-linux/mcpelauncher-manifest#266]
I recently went to elementaryOS (after already having used elementaryOS and having downloaded and running this on elementaryOS and other distros) and it doesn't seem to be working. This is the error I got:

/tmp/.mount_MinecrA9Vviz/usr/bin/./mcpelauncher-client: error while loading shared libraries: libX11.so.6: cannot open shared object file: No such file or directory
Process exited with unexpected exit code: 127

I do not really know what to do and I would really appreciate some help...Thank you!

**Comment by Raiden1024** [comment]
Maybe you need 32bits package for your distribution. I Don't know very well elementaryOS but if it's debian based so maybe install package libx11 ou in 32bit libx11:386 (somethink like that). You could ask on elementaryOS forum: https://elementaryos.stackexchange.com/

**Comment by ChristopherHX** [comment]
[My fork's AppImage has a description](https://github.com/ChristopherHX/linux-packaging-scripts/releases/tag/appimage) with known dependencies per distro / arch like `libx11-6:i386` for debian i386 or amd64
