### ISSUE TITLE
unable to sign into google account 

### ISSUE THREAD

**Issue by emmygoalie23** [minecraft-linux/mcpelauncher-manifest#268]
I had to delete the launcher off my mac and when I re downloaded I went to set up, but when I tried to sign into my google acc it said the browser isn't secure. not sure if this is happening to anyone else but I don't know what to do. just want to get to play again :/

**Comment by InductedPine** [comment]
hey, the same thing happened to me, you have to delete your current version and download a newer version. sorry, I don't have the link but if you search your issue up, with a little bit of searching, you should be able to find the newest launcher.

**Comment by ChristopherHX** [comment]
You may use the launcher found here https://github.com/ChristopherHX/mcpelauncher-manifest/releases, or login may fail on macOS

**Comment by ChristopherHX** [comment]
duplicate of #140
