### ISSUE TITLE
Missing libEGL.so.1

### ISSUE THREAD

**Issue by Leon422** [minecraft-linux/mcpelauncher-manifest#27]
My GPU in my laptop is a Nvidia 820M, using the proprietary Nvidia drivers (390 since it's Fermi)

I get this at launch:
/usr/bin/mcpelauncher-client: error while loading shared libraries: libEGL.so.1: cannot open shared object file: No such file or directory
Process exited with unexpected exit code: 127

Ubuntu 18.10 64 bit

I get the same error even if I switch to the intel integrated GPU

**Comment by MCMrARM** [comment]
You will need to install 32 bit graphics drivers - for integrated graphics and most AMD GPUs libegl1-mesa will work.
