### ISSUE TITLE
Sad day!

### ISSUE THREAD

**Issue by Gustavekkj** [minecraft-linux/mcpelauncher-manifest#270]
The 1.14.1.5 wont connect to our realms server. and the never versions wont run. My siblings are sad since we cannot play together again. Is there anything i can do?

23:52:50 Info  [Launcher] Version: client c735370 / manifest b3dd620
23:52:50 Info  [Launcher] CPU: GenuineIntel Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
23:52:50 Info  [Launcher] CPU supports SSSE3: YES
23:52:50 Trace [Launcher] Loading hybris libraries
23:52:50 Trace [HybrisUtils] Loaded OS library /tmp/.mount_MinecrTBwsRk/usr/share/mcpelauncher/libs/native/libfmod.so.9.16
23:52:50 Trace [HybrisUtils] Loaded OS library libm.so.6
23:52:50 Trace [HybrisUtils] Loaded OS library libz.so.1
23:52:50 Trace [Launcher] Loading Minecraft library
linkerProcess exited with unexpected exit code: 11

**Comment by ChristopherHX** [comment]
Please refer to #271 (I know the number is higher :)

In the first days this issue appeared,
I didn't matched this error to the same problem
