### ISSUE TITLE
a bug of apk

### ISSUE THREAD

**Issue by purofle** [minecraft-linux/mcpelauncher-manifest#276]
"Error while extracting the file: Failed to open zip 21"

**Comment by IvanTurgenev** [comment]
same error here

**Comment by thetbw** [comment]
apk must x86 version.
not arm

**Comment by purofle** [comment]
> apk must x86 version.
> not arm

Thank you very much.

**Comment by NickWilde263** [comment]
I still get Failed to open zip 21
i tried open the apk and look is there a x86 subfolder in lib folder and it really for x86 but still got the error

**Comment by NickWilde263** [comment]
repacking the apk manually is not working
