### ISSUE TITLE
Error on starting

### ISSUE THREAD

**Issue by Kerblif** [minecraft-linux/mcpelauncher-manifest#277]
20:19:23 Info  [Launcher] Version: client c735370 / manifest b3dd620
20:19:23 Info  [Launcher] CPU: GenuineIntel       Intel(R) Core(TM) i7-3630QM CPU @ 2.40GHz
20:19:23 Info  [Launcher] CPU supports SSSE3: YES
20:19:23 Trace [Launcher] Loading hybris libraries
20:19:23 Trace [HybrisUtils] Loaded OS library /usr/share//mcpelauncher/libs/native/libfmod.so.9.16
20:19:23 Trace [HybrisUtils] Loaded OS library libm.so.6
20:19:23 Trace [HybrisUtils] Loaded OS library libz.so.1
20:19:23 Trace [Launcher] Loading Minecraft library
linkerterminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to load Minecraft: Cannot load library: link_image[1965]:     0 could not load needed library 'libgnustl_shared.so' for 'libminecraftpe.so' (load_library[1115]: Library 'libgnustl_shared.so' not found)
Signal 6 received
Backtrace elements: 13
#0 /usr/bin/mcpelauncher-client(_ZN12CrashHandler12handleSignalEiPv+0xc5) [0x56859729]
#1 linux-gate.so.1(__kernel_sigreturn+0) [0xf7fbab70]
#2 linux-gate.so.1(__kernel_vsyscall+0x9) [0xf7fbab59]
#3 /lib/i386-linux-gnu/libc.so.6(gsignal+0xc2) [0xf7884d62]
#4 /lib/i386-linux-gnu/libc.so.6(abort+0xf0) [0xf786eb06]
#5 /usr/lib/i386-linux-gnu/libstdc++.so.6(+0x6e97d) [0xf7be897d]
#6 /usr/lib/i386-linux-gnu/libstdc++.so.6(+0x76174) [0xf7bf0174]
#7 /usr/lib/i386-linux-gnu/libstdc++.so.6(+0x761dd) [0xf7bf01dd]
#8 /usr/lib/i386-linux-gnu/libstdc++.so.6(+0x764dc) [0xf7bf04dc]
#9 /usr/bin/mcpelauncher-client(_ZN14MinecraftUtils16loadMinecraftLibERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x183) [0x5685ac03]
#10 /usr/bin/mcpelauncher-client(main+0xff8) [0x567f56d4]
#11 /lib/i386-linux-gnu/libc.so.6(__libc_start_main+0xf1) [0xf7870391]
#12 /usr/bin/mcpelauncher-client(+0x1dc0f1) [0x567f40f1]
Dumping stack...
Process exited with unexpected exit code: 6

**Comment by Kerblif** [comment]
How to fix it?

**Comment by MistRuan** [comment]
did you fix this? i have same error
