### ISSUE TITLE
Corrupted title bar in ubuntu 18.04

### ISSUE THREAD

**Issue by pellcorp** [minecraft-linux/mcpelauncher-manifest#28]
Not sure if its possible to fix this, as it looks really ugly.  I realise its probably not a high priority, but it would certainly improve the experience.

![screenshot from 2018-11-29 23-47-48](https://user-images.githubusercontent.com/274990/49222971-89f66000-f431-11e8-8d56-e668d1e32175.png)

**Comment by Mhowser** [comment]
I am also getting the corrupted text on 18.04.

**Comment by MCMrARM** [comment]
Anybody has any ideas why this happens in the first place?

**Comment by pellcorp** [comment]
Something to do with setting a gtk wmclass.  Similar issue with java swing apps except no corruption just dodgy name.

**Comment by MCMrARM** [comment]
I guess I'm going to set up an VM for testing this.

**Comment by MCMrARM** [comment]
Fixed with https://github.com/minecraft-linux/game-window/commit/fa70ea83fdcb4b548f8ce9ab6e5f96e56d6c6cb4

**Comment by pellcorp** [comment]
after the update it now won't run a game at all, crashes.

10:35:01 Info  [Launcher] Version: client 393152b / manifest 770da87
10:35:01 Info  [Launcher] CPU supports SSSE3: YES
10:35:01 Trace [Launcher] Loading hybris libraries
10:35:01 Trace [HybrisUtils] Loaded OS library /usr/share/mcpelauncher/libs/native/libfmod.so.9.16
10:35:01 Trace [HybrisUtils] Loaded OS library libm.so.6
10:35:01 Trace [Launcher] Loading Minecraft library
Signal 6 received
Backtrace elements: 16
#0 /usr/bin/mcpelauncher-client(_ZN12CrashHandler12handleSignalEiPv+0xc5) [0x5677ff4b]
#1 linux-gate.so.1(__kernel_sigreturn+0) [0xf7ee6060]
#2 linux-gate.so.1(__kernel_vsyscall+0x9) [0xf7ee6049]
#3 /lib/i386-linux-gnu/libc.so.6(gsignal+0xc2) [0xf77b0512]
#4 /lib/i386-linux-gnu/libc.so.6(abort+0xf0) [0xf779a2b6]
#5 /usr/bin/mcpelauncher-client(+0x22e6f8) [0x567cb6f8]
#6 /usr/bin/mcpelauncher-client(notify_gdb_of_load+0x39) [0x567cb90b]
#7 /usr/bin/mcpelauncher-client(+0x2356f7) [0x567d26f7]
#8 /usr/bin/mcpelauncher-client(+0x231e06) [0x567cee06]
#9 /usr/bin/mcpelauncher-client(find_library+0x295) [0x567cf0d2]
#10 /usr/bin/mcpelauncher-client(android_dlopen+0x2f) [0x567cb2b9]
#11 /usr/bin/mcpelauncher-client(hybris_dlopen+0x21) [0x567ca346]
#12 /usr/bin/mcpelauncher-client(_ZN14MinecraftUtils16loadMinecraftLibERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x42) [0x56780d64]
#13 /usr/bin/mcpelauncher-client(main+0xf91) [0x567360bd]
#14 /lib/i386-linux-gnu/libc.so.6(__libc_start_main+0xf1) [0xf779bb41]
#15 /usr/bin/mcpelauncher-client(+0x197b41) [0x56734b41]
Dumping stack...
#716 HYBRIS (null)+-267456204 in libminecraftpe.so+0x165134 [0xf00ef134]
#717 HYBRIS (null)+-259960823 in libminecraftpe.so+0x88b009 [0xf0815009]
#760 HYBRIS (null)+-197958352 in libminecraftpe.so+0x43ac530 [0xf4336530]
#761 HYBRIS (null)+-268918732 in libminecraftpe.so+0x0034 [0xeff8a034]
#766 HYBRIS (null)+-198799360 in libminecraftpe.so+0x42df000 [0xf4269000]
Process exited with unexpected exit code: 6

**Comment by pellcorp** [comment]
Been suggested it's because I am on 18.10, I will downgrade to 18.04 don't really need 18.10 anyway and see if that resolves issue

**Comment by MCMrARM** [comment]
No, it shouldn't be the issue. I messed some stuff now, it should be fixed.
