### ISSUE TITLE
Unable to import apk

### ISSUE THREAD

**Issue by DLGodMc** [minecraft-linux/mcpelauncher-manifest#283]

**Comment by DLGodMc** [comment]
When I import an app file, it says there's an issue with the file for a split second, then the launcher completely dies, I have to hard restart my MacBook to solve the issue. any clue why this happened?

**Comment by ChristopherHX** [comment]
> Unable to import apk

If this apk is not directly from Google Play (unmodified), it is unsupported.
Why not just log into google, the launcher downloads it for you?
You may use the launcher found here https://github.com/ChristopherHX/mcpelauncher-manifest/releases, or login may fail on macOS
