### ISSUE TITLE
Start error

### ISSUE THREAD

**Issue by AirKetchPLAYZ** [minecraft-linux/mcpelauncher-manifest#284]
15:47:24 Info  [Launcher] Version: client c735370 / manifest b3dd620
15:47:24 Info  [Launcher] CPU: GenuineIntel Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
15:47:24 Info  [Launcher] CPU supports SSSE3: YES
15:47:24 Trace [Launcher] Loading hybris libraries
15:47:24 Trace [HybrisUtils] Loaded OS library /tmp/.mount_MinecrB4yo8k/usr/share/mcpelauncher/libs/native/libfmod.so.9.16
15:47:24 Trace [HybrisUtils] Loaded OS library libm.so.6
15:47:24 Trace [HybrisUtils] Loaded OS library libz.so.1
15:47:24 Trace [Launcher] Loading Minecraft library
linkerterminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to load Minecraft: Cannot load library: link_image[1965]:     0 could not load needed library 'libgnustl_shared.so' for 'libminecraftpe.so' (load_library[1115]: Library 'libgnustl_shared.so' not found)
Signal 6 received
Backtrace elements: 13
#0 /tmp/.mount_MinecrB4yo8k/usr/bin/./mcpelauncher-client(_ZN12CrashHandler12handleSignalEiPv+0xb7) [0x82f3a0f]
#1 linux-gate.so.1(__kernel_sigreturn+0) [0xf7f2fb60]
#2 linux-gate.so.1(__kernel_vsyscall+0x9) [0xf7f2fb49]
#3 /lib/i386-linux-gnu/libc.so.6(gsignal+0xc6) [0xf75c14c6]
#4 /lib/i386-linux-gnu/libc.so.6(abort+0x130) [0xf75a93f7]
#5 /lib/i386-linux-gnu/libstdc++.so.6(+0x7db54) [0xf793eb54]
#6 /lib/i386-linux-gnu/libstdc++.so.6(+0x8bdd8) [0xf794cdd8]
#7 /lib/i386-linux-gnu/libstdc++.so.6(+0x8be61) [0xf794ce61]
#8 /lib/i386-linux-gnu/libstdc++.so.6(__cxa_rethrow+0) [0xf794d1a0]
#9 /tmp/.mount_MinecrB4yo8k/usr/bin/./mcpelauncher-client(_ZN14MinecraftUtils16loadMinecraftLibERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x14c) [0x82f4b52]
#10 /tmp/.mount_MinecrB4yo8k/usr/bin/./mcpelauncher-client(main+0xece) [0x829e6b0]
#11 /lib/i386-linux-gnu/libc.so.6(__libc_start_main+0xf5) [0xf75aaee5]
#12 /tmp/.mount_MinecrB4yo8k/usr/bin/./mcpelauncher-client() [0x829d311]
Dumping stack...
Process exited with unexpected exit code: 6

**Comment by kai4785** [comment]
I'm getting the exact same error

**Comment by AirKetchPLAYZ** [comment]
@kai4785 I found a solution! Use the fork by ChristopherHX. In the releases, if you scroll down there is a release called AppImage and you can download it and it will work! 
Linux: https://github.com/ChristopherHX/linux-packaging-scripts/releases
Mac: https://github.com/ChristopherHX/mcpelauncher-manifest/releases
