### ISSUE TITLE
Error code: 127

### ISSUE THREAD

**Issue by NeoLight1010** [minecraft-linux/mcpelauncher-manifest#299]
I'm getting this error:

> /tmp/.mount_MinecrHQntwA/usr/bin/./mcpelauncher-client: error while loading shared libraries: libEGL.so.1: cannot open shared object file: No such file or directory
> Process exited with unexpected exit code: 127

My specs are:
RAM: 8Gb
Processor: Intel Core i7-6700 3.40GHz x 8
Graphics: Nvidia Geforce GT 730
OS type: 64-bit

**Comment by NeoLight1010** [comment]
My OS is Zorus 15.2, based on Ubuntu.

**Comment by ChristopherHX** [comment]
Please read https://mcpelauncher.readthedocs.io/en/latest/getting_started.html more careful, you need to install 32bit graphics drivers

**Comment by ChristopherHX** [comment]
duplicate of #94
