### ISSUE TITLE
1.16.63 is crashing (i can't launch it)

### ISSUE THREAD

**Issue by Jullegaming04** [minecraft-linux/mcpelauncher-manifest#308]
13:29:47 Info  [Launcher] Version: client 7c17ac3 / manifest 05861bf
13:29:47 Info  [Launcher] CPU: GenuineIntel        Intel(R) Core(TM) i7-3520M CPU @ 2.90GHz
13:29:47 Info  [Launcher] CPU supports SSSE3: YES
13:29:47 Trace [Launcher] Loading hybris libraries
13:29:47 Trace [HybrisUtils] Loaded OS library /usr/share//mcpelauncher/libs/native/libfmod.so.9.16
13:29:47 Trace [HybrisUtils] Loaded OS library libm.so.6
13:29:47 Trace [HybrisUtils] Loaded OS library libz.so.1
13:29:47 Info  [Launcher] Creating window
13:29:47 Trace [Launcher] Loading gamepad mappings: /usr/share//mcpelauncher/gamecontrollerdb.txt
13:29:47 Trace [Launcher] Loading gamepad mappings: /usr/share/mcpelauncher/gamecontrollerdb.txt
_eglutReadPNG: fopen failed
13:29:47 Trace [Launcher] Loading Minecraft library
linkerterminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to load Minecraft: Cannot load library: reloc_library[1378]:     0 cannot locate '_ZN4FMOD14ChannelControl9getVolumeEPf'...

Process exited with unexpected exit code: 11

**Comment by ChristopherHX** [comment]
Fixed
