### ISSUE TITLE
PS3 Controller won´t work with mcpe

### ISSUE THREAD

**Issue by maximilian1003g** [minecraft-linux/mcpelauncher-manifest#31]
I have a littel problem with my mcpe when i want to start a game it crashes or the controller won´t work with it. On the legacy Version on my old Laptop it worked here it won´t work. Here is my Game log:
[Game Log.txt](https://github.com/minecraft-linux/mcpelauncher-manifest/files/2659479/Game.Log.txt)

I hope you can help me.

**Comment by MCMrARM** [comment]
You will need to use a SDL gamepad mapping tool and then copy the resulting mapping to ~/.local/share/mcpelauncher/gamecontrollerdb.txt

**Comment by maximilian1003g** [comment]
OK Thank you. Do you know some tools?

(My English is Not very good)

**Comment by cybercyst** [comment]
Some tools are listed here: https://github.com/gabomdq/SDL_GameControllerDB

**Comment by maximilian1003g** [comment]
Thanks i have No more problems
