### ISSUE TITLE
Minecraft crashes. MacOS Mojave(10.14)

### ISSUE THREAD

**Issue by DeFishy** [minecraft-linux/mcpelauncher-manifest#311]
14:23:02 Info  [Launcher] Version: client 4432ade / manifest 830d61c
14:23:02 Info  [Launcher] CPU: GenuineIntel Intel(R) Core(TM) i5-4260U CPU @ 1.40GHz
14:23:02 Info  [Launcher] CPU supports SSSE3: YES
14:23:02 Trace [Launcher] Loading hybris libraries
14:23:02 Trace [HybrisUtils] Loaded OS library /Applications/Minecraft Bedrock Launcher.app/Contents/Resources/mcpelauncher/libs/native/libfmod.dylib
14:23:02 Trace [HybrisUtils] Loaded OS library libm.dylib
14:23:02 Error [HybrisUtils] Failed to load OS library libz.so.1
14:23:02 Info  [Launcher] Creating window
14:23:02 Trace [Launcher] Loading gamepad mappings: /Applications/Minecraft Bedrock Launcher.app/Contents/Resources/mcpelauncher/gamecontrollerdb.txt
14:23:03 Trace [Launcher] Loading Minecraft library
14:23:03 Info  [Launcher] Loaded Minecraft library
14:23:03 Debug [Launcher] Minecraft is at offset 0x652f000
14:23:03 Trace [AppPlatform] Vtable size = 295
14:23:03 Trace [Patch] Patching - original: 85 83 87 86 129
14:23:03 Trace [Patch] Patching - result: 233 171 246 99 245
14:23:03 Trace [Patch] Patching - original: 85 83 87 86 131
14:23:03 Trace [Patch] Patching - result: 233 219 52 99 245
14:23:04 Warn  [Launcher] Android stub called
14:23:04 Warn  [Launcher] Android stub called
14:23:04 Warn  [Launcher] Android stub called
14:23:04 Warn  [Launcher] Android stub called
14:23:04 Warn  [Launcher] Android stub called
14:23:04 Info  [Minecraft] android_main starting. internalDataPath is './idata/', externalDataPath is './edata/'
14:23:04 Info  [Minecraft] NO LOG FILE! - AppPlatform_android::setStorageDirectory - using External dir - CurrentFileStoragePath is now '/Users/marianna/Library/Application Support/mcpelauncher/'
14:23:04 Error [JNIVM] Object not found in current local layer
14:23:04 Debug [HttpCallStaticGlue] Successfully registerered HttpCall methods
14:23:04 Error [JNIVM] Object not found in current local layer
14:23:04 Debug [XSAPI.Android] Successfully registerered HttpCall methods
14:23:04 Error [JNIVM] Object not found in current local layer
14:23:04 Debug [HttpCallStaticGlue] Successfully registerered HttpCall methods
14:23:04 Error [JNIVM] Object not found in current local layer
14:23:04 Debug [XboxLiveAppConfig] Successfully registerered XboxLiveAppConfig methods
14:23:04 Error [JNIVM] Object not found in current local layer
14:23:04 Debug [XSAPI.Android] Successfully registerered HttpCall tcuiMethods
14:23:04 Trace [XBOXLive] Reading xbox config file
unsupported prctl 15
unsupported prctl 15
unsupported prctl 15
unsupported prctl 15
unsupported prctl 15
unsupported prctl 15
unsupported prctl 15
unsupported prctl 15
14:23:04 Warn  [Launcher] Android stub called
14:23:04 Warn  [Launcher] EGL stub eglMakeCurrent called
14:23:04 Warn  [Launcher] EGL stub eglMakeCurrent called
14:23:04 Warn  [Launcher] Android stub called
14:23:04 Warn  [Launcher] EGL stub eglMakeCurrent called
14:23:04 Warn  [Minecraft] NO LOG FILE! - [Device Lost] The graphics context was gained
14:23:04 Warn  [Minecraft] MinecraftGame::init && MinecraftGame::setSize!
14:23:05 Info  [Minecraft] NO LOG FILE! - IPv4 supported, port: 51491
14:23:05 Info  [Minecraft] NO LOG FILE! - IPv6 supported, port: 51492
14:23:06 Debug [XSAPI.Android] sign_in_impl: will NOT be showing UI
14:23:06 Info  [com::microsoft::xbox::idp::interop::Interop::LogTelemetrySignIn] API - signin_silently - :Entering
14:23:06 Trace [DaemonLauncher] Starting daemon: /Applications/Minecraft Bedrock Launcher.app/Contents/MacOS/./msa-daemon
14:23:07 Info  [com::microsoft::xbox::idp::interop::Interop::LogTelemetrySignIn] API - signin_silently - :Exiting
14:23:07 Trace [com::microsoft::xbox::idp::interop::Interop::LogCLL] log_cll 2535472242709391 Microsoft.XboxLive.T1739947436.SignInToXboxLive {"baseData":{"measurements":null,"name":"SignInToXboxLive","playerSessionId":"dc0036e6-3fda-418e-963e-766820b403a5","properties":{"AccountType":1,"ActiveSessionID":"a6c1169f-dfda-42ab-a6ba-4885e433c18a","AppSessionID":"3d92973c-af8b-410f-9f63-30544e8c8a67","Build":"1.14.60","BuildPlat":1,"Cheevos":1,"ClientId":"19af3ae9-b15a-44b0-a3c2-aa2c66df489e","CurrentInput":2,"DeviceSessionId":"3d92973c-af8b-410f-9f63-30544e8c8a67","Plat":"","SchemaCommitHash":"19b6ec0744c3c83a00ecbd840f48cb080c7bc64d","Seq":7,"SignInUI":0,"Stage":4,"TimeStamp":4.6575930000000003,"Treatments":"mc-rp-pacman:mc-perf-plat-12-20:mc-perf-plat-1-20:mc-perf-plat-2-20:mc-perf-plat-4-20:mc-perf-plat-7-20:mc-perf-plat-13-20:mc-perf-plat-11-20:mc-rp-pdp-order:mc-rp-playfab","UserId":"2535472242709391","locale":"en"},"serviceConfigId":"00000000-0000-0000-0000-000067b57dac","titleId":"1739947436","userId":"2535472242709391","ver":1},"baseType":"Microsoft.XboxLive.InGame"}
Signal 11 received
Backtrace elements: 4
#0 0   mcpelauncher-client                 0x001d2c71 _ZN12CrashHandler12handleSignalEiPv + 273
#1 1   libsystem_platform.dylib            0xa7dfebae _sigtramp + 46
#2 2   ???                                 0xffffffff 0x0 + 4294967295
#3 3   mcpelauncher-client                 0x0015dff7 _ZNSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE7__allocEv + 23
Dumping stack...
#3 HYBRIS std::string::_Rep::_S_empty_rep_storage+12 in libgnustl_shared.so+0x10cb84 [0x652eb84]
#4 HYBRIS std::string::_Rep::_S_empty_rep_storage+12 in libgnustl_shared.so+0x10cb84 [0x652eb84]
#19 HYBRIS std::ios_base::~ios_base()+7 in libgnustl_shared.so+0x6b707 [0x648d707]
#24 HYBRIS (null)+227886984 in libminecraftpe.so+0x7425788 [0xd954788]
#81 HYBRIS (null)+119776720 in libminecraftpe.so+0xd0b5d0 [0x723a5d0]
#85 HYBRIS std::string::_Rep::_S_empty_rep_storage+12 in libgnustl_shared.so+0x10cb84 [0x652eb84]
#86 HYBRIS std::string::_Rep::_S_empty_rep_storage+12 in libgnustl_shared.so+0x10cb84 [0x652eb84]
#87 HYBRIS std::string::_Rep::_S_empty_rep_storage+12 in libgnustl_shared.so+0x10cb84 [0x652eb84]
#88 HYBRIS std::string::_Rep::_S_empty_rep_storage+12 in libgnustl_shared.so+0x10cb84 [0x652eb84]
#242 HYBRIS xbox::services::system::user_auth_android::get_uploader_x_token_callback(_JNIEnv*, _jclass*, unsigned char)+2007 in libminecraftpe.so+0x417c677 [0xa6ab677]
#269 HYBRIS std::string::_Rep::_S_empty_rep_storage+12 in libgnustl_shared.so+0x10cb84 [0x652eb84]
#287 HYBRIS std::string::_Rep::_S_empty_rep_storage+12 in libgnustl_shared.so+0x10cb84 [0x652eb84]
#306 HYBRIS xbox::services::system::user_auth_android::get_uploader_x_token_callback(_JNIEnv*, _jclass*, unsigned char)+0 in libminecraftpe.so+0x417bea0 [0xa6aaea0]
#409 HYBRIS (null)+130046248 in libminecraftpe.so+0x16d6928 [0x7c05928]

Process exited with unexpected exit code: 6

**Comment by ChristopherHX** [comment]
Please retry starting it, at least 5 times.
It is macOS specfic issue with xbox live archivements.
Disabling xbox live archivements was the previous now removed WORKAROUND

**Comment by ChristopherHX** [comment]
Proposed fix starting with version 0.0.136 (stable), should be available soon.
