### ISSUE TITLE
Unable to launch the game with NVIDIA On-Demand

### ISSUE THREAD

**Issue by MATRIX-feather** [minecraft-linux/mcpelauncher-manifest#323]
**Description:**
As the title said, when I try to launch the game with environment variable `__GLX_VENDOR_LIBRARY_NAME=nvidia` and `__NV_PRIME_RENDER_OFFLOAD=1`( which makes the game to render by the NVIDIA card ), the game crashes instantly.

**Screenshot:**
![2020-06-04 01-36-59 的屏幕截图](https://user-images.githubusercontent.com/55654482/83669399-1c1d8c80-a604-11ea-8abe-789631a2df8c.png)

**Comment by MATRIX-feather** [comment]
Yes, all works fine.

**Comment by ChristopherHX** [comment]
I actually don't know if glx* are using the mobile opengl es 2 with libEGL.so or just normal opengl 4 different driver (but not compatible with bedrock). Currently I'm unable to reproduce or fix anything (No nvidia offload to test against).
The legacy NVIDIA (PERFORMANCE MODE) is the only working mode for me. (the intel mode => blackscreen, your mode not available.

**Comment by ChristopherHX** [comment]
same error as #233, both using (probably broken) 32bit nvidia libEGL drivers
