### ISSUE TITLE
game show minecraft loading screen and crash after this

### ISSUE THREAD

**Issue by thatisfolks302** [minecraft-linux/mcpelauncher-manifest#325]
libEGL warning: DRI2: failed to authenticate
21:43:53 Info  [Launcher] Version: client 4432ade / manifest b4136d7
21:43:53 Info  [Launcher] CPU: AuthenticAMD AMD Athlon(tm) 64 X2 Dual Core Processor 4000+
21:43:53 Info  [Launcher] CPU supports SSSE3: NO
21:43:53 Trace [Launcher] Loading hybris libraries
21:43:53 Trace [HybrisUtils] Loaded OS library /tmp/.mount_MC.AppyfI0Rh/usr/share/mcpelauncher/libs/native/libfmod.so.9.16
21:43:53 Trace [HybrisUtils] Loaded OS library libm.so.6
21:43:53 Trace [HybrisUtils] Loaded OS library libz.so.1
21:43:53 Info  [Launcher] Creating window
21:43:53 Trace [Launcher] Loading gamepad mappings: /tmp/.mount_MC.AppyfI0Rh/usr/share/mcpelauncher/gamecontrollerdb.txt
21:43:53 Trace [Launcher] Loading Minecraft library
21:43:54 Info  [Launcher] Loaded Minecraft library
21:43:54 Debug [Launcher] Minecraft is at offset 0xe9a12000
21:43:54 Trace [AppPlatform] Vtable size = 295
21:43:54 Trace [Patch] Patching - original: 85 83 87 86 129
21:43:54 Trace [Patch] Patching - result: 233 219 113 44 26
21:43:54 Trace [Patch] Patching - original: 85 83 87 86 131
21:43:54 Trace [Patch] Patching - result: 233 203 26 39 26
21:43:54 Warn  [Launcher] Android stub called
21:43:54 Warn  [Launcher] Android stub called
21:43:54 Warn  [Launcher] Android stub called
21:43:54 Warn  [Launcher] Android stub called
21:43:54 Warn  [Launcher] Android stub called
21:43:54 Info  [Minecraft] android_main starting. internalDataPath is './idata/', externalDataPath is './edata/'
21:43:54 Info  [Minecraft] NO LOG FILE! - AppPlatform_android::setStorageDirectory - using External dir - CurrentFileStoragePath is now '/home/teste/.local/share/mcpelauncher/'
21:43:54 Error [JNIVM] Object not found in current local layer
21:43:54 Debug [HttpCallStaticGlue] Successfully registerered HttpCall methods
21:43:54 Error [JNIVM] Object not found in current local layer
21:43:54 Debug [XSAPI.Android] Successfully registerered HttpCall methods
21:43:54 Error [JNIVM] Object not found in current local layer
21:43:54 Debug [HttpCallStaticGlue] Successfully registerered HttpCall methods
21:43:54 Error [JNIVM] Object not found in current local layer
21:43:54 Debug [XboxLiveAppConfig] Successfully registerered XboxLiveAppConfig methods
21:43:54 Error [JNIVM] Object not found in current local layer
21:43:54 Debug [XSAPI.Android] Successfully registerered HttpCall tcuiMethods
21:43:54 Trace [XBOXLive] Reading xbox config file
21:43:54 Warn  [Launcher] Android stub called
21:43:54 Warn  [Launcher] EGL stub eglMakeCurrent called
21:43:54 Warn  [Launcher] EGL stub eglMakeCurrent called
21:43:54 Warn  [Launcher] Android stub called
21:43:54 Warn  [Launcher] EGL stub eglMakeCurrent called
21:43:54 Warn  [Minecraft] NO LOG FILE! - [Device Lost] The graphics context was gained
21:43:54 Warn  [Minecraft] MinecraftGame::init && MinecraftGame::setSize!

Process exited with unexpected exit code: 4

mcpe edition is 1.14.25.1

**Comment by ChristopherHX** [comment]
Sorry your old amd CPU is incompatible with the game.
https://github.com/minecraft-linux/mcpelauncher-manifest/issues/143
