### ISSUE TITLE
game show minecraft loading screen and crash after this

### ISSUE THREAD

**Issue by CAVP16** [minecraft-linux/mcpelauncher-manifest#330]
16:06:57 Info  [Launcher] Version: client 4432ade / manifest 04dd224
16:06:57 Info  [Launcher] CPU: AuthenticAMD AMD Turion(tm) X2 Ultra Dual-Core Mobile ZM-82
16:06:57 Info  [Launcher] CPU supports SSSE3: NO
16:06:57 Trace [Launcher] Loading hybris libraries
16:06:57 Trace [HybrisUtils] Loaded OS library /tmp/.mount_MinecriWYTGu/usr/share/mcpelauncher/libs/native/libfmod.so.9.16
16:06:57 Trace [HybrisUtils] Loaded OS library libm.so.6
16:06:57 Trace [HybrisUtils] Loaded OS library libz.so.1
16:06:57 Info  [Launcher] Creating window
16:06:57 Trace [Launcher] Loading gamepad mappings: /tmp/.mount_MinecriWYTGu/usr/share/mcpelauncher/gamecontrollerdb.txt
16:06:57 Trace [Launcher] Loading Minecraft library
16:06:58 Info  [Launcher] Loaded Minecraft library
16:06:58 Debug [Launcher] Minecraft is at offset 0xe7634000
16:06:58 Trace [AppPlatform] Vtable size = 295
16:06:58 Trace [Patch] Patching - original: 85 83 87 86 129
16:06:58 Trace [Patch] Patching - result: 233 91 85 103 28
16:06:58 Trace [Patch] Patching - original: 85 83 87 86 131
16:06:58 Trace [Patch] Patching - result: 233 75 254 97 28
16:06:58 Warn  [Launcher] Android stub called
16:06:58 Warn  [Launcher] Android stub called
16:06:58 Warn  [Launcher] Android stub called
16:06:58 Warn  [Launcher] Android stub called
16:06:58 Warn  [Launcher] Android stub called
16:06:58 Info  [Minecraft] android_main starting. internalDataPath is './idata/', externalDataPath is './edata/'
16:06:58 Info  [Minecraft] NO LOG FILE! - AppPlatform_android::setStorageDirectory - using External dir - CurrentFileStoragePath is now '/home/andres/.local/share/mcpelauncher/'
16:06:58 Debug [HttpCallStaticGlue] Successfully registerered HttpCall methods
16:06:58 Debug [XSAPI.Android] Successfully registerered HttpCall methods
16:06:58 Debug [HttpCallStaticGlue] Successfully registerered HttpCall methods
16:06:58 Debug [XboxLiveAppConfig] Successfully registerered XboxLiveAppConfig methods
16:06:58 Debug [XSAPI.Android] Successfully registerered HttpCall tcuiMethods
16:06:58 Trace [XBOXLive] Reading xbox config file
16:06:58 Warn  [Launcher] Android stub called
16:06:58 Warn  [Launcher] EGL stub eglMakeCurrent called
16:06:58 Warn  [Launcher] EGL stub eglMakeCurrent called
16:06:58 Warn  [Launcher] Android stub called
16:06:58 Warn  [Launcher] EGL stub eglMakeCurrent called
16:06:58 Warn  [Minecraft] NO LOG FILE! - [Device Lost] The graphics context was gained
16:06:58 Warn  [Minecraft] MinecraftGame::init && MinecraftGame::setSize!

Process exited with unexpected exit code: 4

**Comment by ChristopherHX** [comment]
> CPU supports SSSE3: NO
This is a death flag you need a newer computer to use this launcher.
