### ISSUE TITLE
On Debian it fails

### ISSUE THREAD

**Issue by TamasSzerb** [minecraft-linux/mcpelauncher-manifest#335]
14:52:12 Info  [Launcher] Version: client c735370 / manifest b3dd620
14:52:12 Info  [Launcher] CPU: GenuineIntel Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz
14:52:12 Info  [Launcher] CPU supports SSSE3: YES
14:52:12 Trace [Launcher] Loading hybris libraries
14:52:12 Trace [HybrisUtils] Loaded OS library /tmp/.mount_MinecrqH0T5G/usr/share/mcpelauncher/libs/native/libfmod.so.9.16
14:52:12 Trace [HybrisUtils] Loaded OS library libm.so.6
14:52:12 Trace [HybrisUtils] Loaded OS library libz.so.1
14:52:12 Trace [Launcher] Loading Minecraft library
linkerterminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to load Minecraft: Cannot load library: link_image[1965]:     0 could not load needed library 'libgnustl_shared.so' for 'libminecraftpe.so' (load_library[1115]: Library 'libgnustl_shared.so' not found)
Signal 6 received
Backtrace elements: 13
#0 /tmp/.mount_MinecrqH0T5G/usr/bin/./mcpelauncher-client(_ZN12CrashHandler12handleSignalEiPv+0xb7) [0x82f3a0f]
#1 linux-gate.so.1(__kernel_sigreturn+0) [0xf7fcc180]
#2 linux-gate.so.1(__kernel_vsyscall+0x9) [0xf7fcc169]
#3 /lib/i386-linux-gnu/libc.so.6(gsignal+0xc2) [0xf76648e2]
#4 /lib/i386-linux-gnu/libc.so.6(abort+0x12c) [0xf764d309]
#5 /usr/lib/i386-linux-gnu/libstdc++.so.6(+0x79994) [0xf79d2994]
#6 /usr/lib/i386-linux-gnu/libstdc++.so.6(+0x87364) [0xf79e0364]
#7 /usr/lib/i386-linux-gnu/libstdc++.so.6(+0x873dd) [0xf79e03dd]
#8 /usr/lib/i386-linux-gnu/libstdc++.so.6(+0x876dc) [0xf79e06dc]
#9 /tmp/.mount_MinecrqH0T5G/usr/bin/./mcpelauncher-client(_ZN14MinecraftUtils16loadMinecraftLibERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x14c) [0x82f4b52]
#10 /tmp/.mount_MinecrqH0T5G/usr/bin/./mcpelauncher-client(main+0xece) [0x829e6b0]
#11 /lib/i386-linux-gnu/libc.so.6(__libc_start_main+0xf1) [0xf764eef1]
#12 /tmp/.mount_MinecrqH0T5G/usr/bin/./mcpelauncher-client() [0x829d311]
Dumping stack...
Process exited with unexpected exit code: 6

**Comment by ChristopherHX** [comment]
You are using the unsupported appimage from the wiki?
It would be worth installing this appimage instead https://github.com/ChristopherHX/linux-packaging-scripts/releases/tag/appimage

It will tell you to redownload the game after update (important)

**Comment by ChristopherHX** [comment]
Stale issue
