### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Aenoxic** [minecraft-linux/mcpelauncher-manifest#339]
How to fix? Ubuntu 20.04

18:35:05 Info  [Launcher] Version: client c735370 / manifest e405b8c
18:35:05 Info  [Launcher] CPU: GenuineIntel Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz
18:35:05 Info  [Launcher] CPU supports SSSE3: YES
18:35:05 Trace [Launcher] Loading hybris libraries
18:35:05 Trace [HybrisUtils] Loaded OS library /usr/share//mcpelauncher/libs/native/libfmod.so.9.16
18:35:05 Trace [HybrisUtils] Loaded OS library libm.so.6
18:35:05 Trace [HybrisUtils] Loaded OS library libz.so.1
18:35:05 Trace [Launcher] Loading Minecraft library
linkerProcess exited with unexpected exit code: 11

**Comment by ChristopherHX** [comment]
You are using the unsupported release from the wiki?
It would be worth installing this instead https://github.com/ChristopherHX/linux-packaging-scripts/releases/tag/appimage

**Comment by ChristopherHX** [comment]
Stale issue
Your installed launcher can only launch selected (4) versions above 1.13.0.6. (1.13.0.15, 1.13.0.34, 1.14.1.3, 1.14.1.5)

Please read this section to get 1.16.1.02 working
https://mcpelauncher.readthedocs.io/en/latest/getting_started.html#a-note-for-new-users
