### ISSUE TITLE
Crashes in 1.9.0.3

### ISSUE THREAD

**Issue by Kevadro** [minecraft-linux/mcpelauncher-manifest#34]
17:27:41 Info  [Launcher] Version: client 2d58c35 / manifest 5127a58
17:27:41 Trace [Launcher] Loading hybris libraries
17:27:41 Trace [HybrisUtils] Loaded OS library /usr/local/share/mcpelauncher/libs/native/libfmod.so.9.16
17:27:41 Trace [HybrisUtils] Loaded OS library libm.so.6
17:27:41 Trace [Launcher] Loading Minecraft library
17:27:42 Info  [Launcher] Loaded Minecraft library
17:27:42 Debug [Launcher] Minecraft is at offset 0xee2b8000
17:27:42 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN4xbox8services12local_config28get_value_from_local_storageERKSs
17:27:42 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN4xbox8services12local_config28write_value_to_local_storageERKSsS3_
17:27:42 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstanceC2ER13IMinecraftAppR9WhitelistRK14PermissionsMapP15FilePathManagerNSt6chrono8durationIxSt5ratioILx1ELx1EEEESsSsSs13LevelSettingsibiiibRKSt6vectorISsSaISsEESsRKN3mce4UUIDER18IMinecraftEventingR22ResourcePackRepositoryRK18ContentTierManagerR19ResourcePackManagerSt8functionIFSt10unique_ptrI12LevelStorageSt14default_deleteISZ_EER9SchedulerEERKSsP9LevelDataP22TextFilteringProcessorPSV_SX_IFvS18_EES1F_
17:27:42 Error [MinecraftSymbols] Unresolved symbol: _ZN14PermissionsMapC2Eb
17:27:42 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n13loadLanguagesER19ResourcePackManagerRKSs
17:27:42 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance16_syncDestroyGameEv
17:27:42 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepositoryC2ER18IMinecraftEventingR19PackManifestFactoryR29IContentAccessibilityProviderP15FilePathManagerR17PackSourceFactory
17:27:42 Error [MinecraftSymbols] Unresolved symbol: _ZN28DedicatedServerCommandOriginC2ERKSsR9Minecraft
17:27:42 Info  [Launcher] Game version: 1.9.0.3
17:27:42 Info  [Launcher] Applying patches
17:27:42 Trace [Store] Vtable size = 33
17:27:42 Trace [Patch] Patching - original: 85 83 87 86 131
17:27:42 Trace [Patch] Patching - result: 233 70 75 13 103
17:27:42 Trace [Patch] Patching - original: 83 87 86 131 236
17:27:42 Trace [Patch] Patching - result: 233 89 46 28 102
17:27:42 Trace [Patch] Patching - original: 85 83 87 86 129
17:27:42 Trace [Patch] Patching - result: 233 7 49 163 100
17:27:42 Trace [Patch] Patching - original: 85 83 87 86 129
17:27:42 Trace [Patch] Patching - result: 233 71 112 225 100
17:27:42 Trace [Patch] Patching - original: 85 83 87 86 129
17:27:42 Trace [Patch] Patching - result: 233 157 128 225 100
17:27:42 Trace [Patch] Patching - original: 85 83 87 86 129
17:27:42 Trace [Patch] Patching - result: 233 17 109 225 100
17:27:42 Trace [Patch] Patching - original: 85 83 87 86 129
17:27:42 Trace [Patch] Patching - result: 233 195 215 224 100
17:27:42 Trace [Patch] Patching - original: 85 83 87 86 129
17:27:42 Trace [Patch] Patching - result: 233 49 213 224 100
17:27:42 Trace [Patch] Patching - original: 85 83 87 86 129
17:27:42 Trace [Patch] Patching - result: 233 203 13 227 100
17:27:42 Trace [Patch] Patching - original: 83 87 86 131 236
17:27:42 Trace [Patch] Patching - result: 233 9 117 225 100
17:27:42 Trace [Patch] Patching - original: 85 83 87 86 129
17:27:42 Trace [Patch] Patching - result: 233 197 159 225 100
17:27:42 Trace [Patch] Patching - original: 49 192 195 141 182
17:27:42 Trace [Patch] Patching - result: 233 81 11 7 103
17:27:42 Trace [Patch] Patching - original: 83 131 236 8 232
17:27:42 Trace [Patch] Patching - result: 233 45 174 254 100
17:27:42 Trace [Patch] Patching - original: 85 83 87 86 131
17:27:42 Trace [Patch] Patching - result: 233 166 2 16 103
17:27:42 Trace [Patch] Patching - original: 85 83 87 86 129
17:27:42 Trace [Patch] Patching - result: 233 51 1 16 103
17:27:42 Trace [Patch] Patching - original: 83 87 86 131 236
17:27:42 Trace [Patch] Patching - result: 233 255 1 16 103
17:27:42 Trace [Patch] Patching - original: 232 13 121 245 253
17:27:42 Trace [Patch] Patching - result: 232 165 206 35 101
17:27:42 Info  [Launcher] Creating window
17:27:42 Trace [Launcher] Loading gamepad mappings: /usr/local/share/mcpelauncher/gamecontrollerdb.txt
Invalid mapping in /usr/local/share/mcpelauncher/gamecontrollerdb.txt: Invalid mapping
Invalid mapping in /usr/local/share/mcpelauncher/gamecontrollerdb.txt: Invalid mapping
Invalid mapping in /usr/local/share/mcpelauncher/gamecontrollerdb.txt: Invalid mapping
Invalid mapping in /usr/local/share/mcpelauncher/gamecontrollerdb.txt: Invalid mapping
Invalid mapping in /usr/local/share/mcpelauncher/gamecontrollerdb.txt: Invalid mapping
Invalid mapping in /usr/local/share/mcpelauncher/gamecontrollerdb.txt: Invalid mapping
Invalid mapping in /usr/local/share/mcpelauncher/gamecontrollerdb.txt: Invalid mapping
17:27:42 Trace [Launcher] Loading gamepad mappings: /usr/share/mcpelauncher/gamecontrollerdb.txt
Invalid mapping in /usr/share/mcpelauncher/gamecontrollerdb.txt: Invalid mapping
Invalid mapping in /usr/share/mcpelauncher/gamecontrollerdb.txt: Invalid mapping
Invalid mapping in /usr/share/mcpelauncher/gamecontrollerdb.txt: Invalid mapping
Invalid mapping in /usr/share/mcpelauncher/gamecontrollerdb.txt: Invalid mapping
Invalid mapping in /usr/share/mcpelauncher/gamecontrollerdb.txt: Invalid mapping
Invalid mapping in /usr/share/mcpelauncher/gamecontrollerdb.txt: Invalid mapping
Invalid mapping in /usr/share/mcpelauncher/gamecontrollerdb.txt: Invalid mapping
17:27:43 Trace [Launcher] Loading gamepad mappings: /usr/local/share/mcpelauncher/gamecontrollerdb.txt
Invalid mapping in /usr/local/share/mcpelauncher/gamecontrollerdb.txt: Invalid mapping
Invalid mapping in /usr/local/share/mcpelauncher/gamecontrollerdb.txt: Invalid mapping
Invalid mapping in /usr/local/share/mcpelauncher/gamecontrollerdb.txt: Invalid mapping
Invalid mapping in /usr/local/share/mcpelauncher/gamecontrollerdb.txt: Invalid mapping
Invalid mapping in /usr/local/share/mcpelauncher/gamecontrollerdb.txt: Invalid mapping
Invalid mapping in /usr/local/share/mcpelauncher/gamecontrollerdb.txt: Invalid mapping
Invalid mapping in /usr/local/share/mcpelauncher/gamecontrollerdb.txt: Invalid mapping
17:27:43 Trace [Launcher] Initializing AppPlatform (vtable)
17:27:43 Trace [AppPlatform] Vtable size = 255
17:27:43 Trace [Launcher] Initializing AppPlatform (create instance)
17:27:43 Trace [Launcher] Initializing AppPlatform (initialize call)
17:27:43 Trace [AppPlatform] createDeviceID: 
17:27:43 Info  [Launcher] OpenGL: version: OpenGL ES 3.2 NVIDIA 390.87, renderer: GeForce 710M/PCIe/SSE2, vendor: NVIDIA Corporation
17:27:43 Trace [Launcher] Initializing MinecraftGame (create instance)
17:27:43 Trace [AppPlatform] getSystemRegion: en_US
17:27:43 Trace [Launcher] Initializing MinecraftGame (init call)
17:27:43 Info  [Launcher] Game initialized
17:27:43 Trace [AppPlatform] getDataUrl: /home/kevin/.local/share/mcpelauncher/versions/1.9.0.3/assets/
17:27:43 Error [CoHTML] Java VM not found! Make sure you loaded your library with Java's System.load() API and you've set the Java VM pointer in the library params!
Signal 11 received
Backtrace elements: 3
#0 /usr/local/bin/mcpelauncher-client(_ZN12CrashHandler12handleSignalEiPv+0xc5) [0x567c2ead]
#1 linux-gate.so.1(__kernel_sigreturn+0) [0xf7f7b070]
#2 HYBRIS hbui::Library::_initializeSystem(cohtml::PlatformSpecificParams const&, Json::Value)+2056 in libminecraftpe.so+0x1ded708 [0xf00a5708]
Dumping stack...
#18 HYBRIS hbui::Library::_initializeSystem(cohtml::PlatformSpecificParams const&, Json::Value)+2056 in libminecraftpe.so+0x1ded708 [0xf00a5708]
#100 HYBRIS hbui::Library::_initializeSystem(cohtml::PlatformSpecificParams const&, Json::Value)+2056 in libminecraftpe.so+0x1ded708 [0xf00a5708]
#108 HYBRIS Core::FileStorageArea::_addReadOperation(bool, unsigned long long)+135 in libminecraftpe.so+0x332c837 [0xf15e4837]
#120 HYBRIS Core::FileStorageArea::_addReadOperation(bool, unsigned long long)+135 in libminecraftpe.so+0x332c837 [0xf15e4837]
#132 HYBRIS Core::FileSystemImpl::_readOperation(Core::Result&&, unsigned long long)+284 in libminecraftpe.so+0x333b2fc [0xf15f32fc]
#144 HYBRIS Core::Result::~Result()+9 in libminecraftpe.so+0x3361f69 [0xf1619f69]
#148 HYBRIS Core::FileSystemImpl::openFile(std::unique_ptr<Core::FileImpl, std::default_delete<Core::FileImpl> >&, Core::Path, Core::FileOpenMode, Core::FileBufferingMode)+1401 in libminecraftpe.so+0x333a9b9 [0xf15f29b9]
#156 HYBRIS Core::FileStorageArea::_beginTransaction(Core::FileSystemImpl*, bool)+792 in libminecraftpe.so+0x332c098 [0xf15e4098]
#180 HYBRIS Core::FileSystemImpl::FileSystemImpl(Core::FileAccessType, std::shared_ptr<Core::FileStorageArea>, std::shared_ptr<Core::FlatFileManifestTracker>)+8 in libminecraftpe.so+0x3339fe8 [0xf15f1fe8]
#184 HYBRIS Core::FileSystem_generic::FileSystem_generic(Core::FileAccessType, std::shared_ptr<Core::FileStorageArea>, std::shared_ptr<Core::FlatFileManifestTracker>)+132 in libminecraftpe.so+0x335ff64 [0xf1617f64]
#196 HYBRIS std::_MakeUniq<Core::FileSystem_generic>::__single_object std::make_unique<Core::FileSystem_generic, Core::FileAccessType&, std::shared_ptr<Core::FileStorageArea>, std::shared_ptr<Core::FlatFileManifestTracker> >(Core::FileAccessType&, std::shared_ptr<Core::FileStorageArea>&&, std::shared_ptr<Core::FlatFileManifestTracker>&&)+137 in libminecraftpe.so+0x1bbffc9 [0xefe77fc9]
#212 HYBRIS Core::BasicDirectoryStorageArea<Core::FileSystem_generic>::createTransaction(Core::FileAccessType)+151 in libminecraftpe.so+0x1bbfc37 [0xefe77c37]
#217 HYBRIS Core::FileStorageArea::sStorageAreaLock+0 in libminecraftpe.so+0x645313c [0xf470b13c]
#224 HYBRIS Core::Result::~Result()+9 in libminecraftpe.so+0x3361f69 [0xf1619f69]
#228 HYBRIS Core::FileSystem::openFile(Core::Path, Core::File&, Core::FileOpenMode, Core::FileBufferingMode)+840 in libminecraftpe.so+0x332ef58 [0xf15e6f58]
#257 HYBRIS vtable for Core::FileSystemImpl+8 in libminecraftpe.so+0x619aeb0 [0xf4452eb0]
#260 HYBRIS Core::FileSystemImpl::FileSystemImpl(Core::FileAccessType, std::shared_ptr<Core::FileStorageArea>, std::shared_ptr<Core::FlatFileManifestTracker>)+250 in libminecraftpe.so+0x333a0da [0xf15f20da]
#404 HYBRIS hbui::LogHandler::WriteLog(cohtml::Logging::Severity, char const*, unsigned int)+116 in libminecraftpe.so+0x1df24b4 [0xf00aa4b4]
#508 HYBRIS Json::Value::operator[](char const*)+34 in libminecraftpe.so+0x32afeb2 [0xf1567eb2]
#516 HYBRIS hbui::Library::_initializeSystem(cohtml::PlatformSpecificParams const&, Json::Value)+2053 in libminecraftpe.so+0x1ded705 [0xf00a5705]
#556 HYBRIS std::_Rb_tree<Json::Value::CZString, std::pair<Json::Value::CZString const, Json::Value>, std::_Select1st<std::pair<Json::Value::CZString const, Json::Value> >, std::less<Json::Value::CZString>, std::allocator<std::pair<Json::Value::CZString const, Json::Value> > >::_M_copy(std::_Rb_tree_node<std::pair<Json::Value::CZString const, Json::Value> > const*, std::_Rb_tree_node<std::pair<Json::Value::CZString const, Json::Value> >*)+394 in libminecraftpe.so+0x32b1c6a [0xf1569c6a]
#580 HYBRIS hbui::Library::Library(hbui::IFeature const&, cohtml::PlatformSpecificParams const&, std::unique_ptr<cohtml::IAllocator, std::default_delete<cohtml::IAllocator> >, std::unique_ptr<cohtml::IFileSystemReader, std::default_delete<cohtml::IFileSystemReader> >, std::unique_ptr<hbui::ResourceHandler, std::default_delete<hbui::ResourceHandler> >, std::unique_ptr<hbui::LocalizationManager, std::default_delete<hbui::LocalizationManager> >, mce::ShaderGroup&, mce::RenderContext&, std::unique_ptr<cohtml::Logging::ILogHandler, std::default_delete<cohtml::Logging::ILogHandler> >)+743 in libminecraftpe.so+0x1dec9e7 [0xf00a49e7]
#592 HYBRIS AppPlatform::supportsInPackageRecursion() const+1 in libminecraftpe.so+0x269c201 [0xf0954201]
#628 HYBRIS operator new(unsigned int)+39 in libminecraftpe.so+0x4b75127 [0xf2e2d127]
#636 HYBRIS std::_MakeUniq<hbui::Library>::__single_object std::make_unique<hbui::Library, hbui::IFeature const&, cohtml::PlatformSpecificParams&, std::unique_ptr<hbui::Allocator, std::default_delete<hbui::Allocator> >, std::unique_ptr<hbui::FileSystemReader, std::default_delete<hbui::FileSystemReader> >, std::unique_ptr<hbui::ResourceHandler, std::default_delete<hbui::ResourceHandler> >, std::unique_ptr<hbui::LocalizationManager, std::default_delete<hbui::LocalizationManager> >, mce::ShaderGroup&, mce::RenderContext&, std::unique_ptr<hbui::LogHandler, std::default_delete<hbui::LogHandler> > >(hbui::IFeature const&, cohtml::PlatformSpecificParams&, std::unique_ptr<hbui::Allocator, std::default_delete<hbui::Allocator> >&&, std::unique_ptr<hbui::FileSystemReader, std::default_delete<hbui::FileSystemReader> >&&, std::unique_ptr<hbui::ResourceHandler, std::default_delete<hbui::ResourceHandler> >&&, std::unique_ptr<hbui::LocalizationManager, std::default_delete<hbui::LocalizationManager> >&&, mce::ShaderGroup&, mce::RenderContext&, std::unique_ptr<hbui::LogHandler, std::default_delete<hbui::LogHandler> >&&)+201 in libminecraftpe.so+0x1deadf9 [0xf00a2df9]
#652 HYBRIS operator new(unsigned int)+39 in libminecraftpe.so+0x4b75127 [0xf2e2d127]
#660 HYBRIS hbui::makeUILibrary(hbui::IFeature const&, Core::IFileSystem&, IFileAccess&, std::shared_ptr<hbui::ITextureLoader>, mce::ShaderGroup&, mce::RenderContext&, std::string const&, ResourcePackManager const&)+392 in libminecraftpe.so+0x1dea9c8 [0xf00a29c8]
#676 HYBRIS operator new(unsigned int)+39 in libminecraftpe.so+0x4b75127 [0xf2e2d127]
#684 HYBRIS std::__shared_ptr<hbui::TextureLoader, (__gnu_cxx::_Lock_policy)2>::__shared_ptr<std::allocator<hbui::TextureLoader>, mce::TextureGroup&, bool>(std::_Sp_make_shared_tag, std::allocator<hbui::TextureLoader> const&, mce::TextureGroup&, bool&&)+150 in libminecraftpe.so+0x14cf286 [0xef787286]
#692 HYBRIS HummingbirdUI::_initializeLibrary()+425 in libminecraftpe.so+0x14cea59 [0xef786a59]
#708 HYBRIS Option::getBool() const+49 in libminecraftpe.so+0x268f391 [0xf0947391]
#716 HYBRIS HummingbirdUI::HummingbirdUI(Option*, Option*, std::function<void ()>, Core::IFileSystem&, IFileAccess&, std::unique_ptr<mce::TextureGroup, std::default_delete<mce::TextureGroup> >, mce::ShaderGroup&, mce::RenderContext&, std::string const&, ResourcePackManager const&)+167 in libminecraftpe.so+0x14ce697 [0xef786697]
#728 HYBRIS operator new(unsigned int)+39 in libminecraftpe.so+0x4b75127 [0xf2e2d127]
#736 HYBRIS std::_MakeUniq<HummingbirdUI>::__single_object std::make_unique<HummingbirdUI, Option*, Option*, std::function<void ()>&, Core::IFileSystem&, IFileAccess&, std::unique_ptr<mce::TextureGroup, std::default_delete<mce::TextureGroup> >, mce::ShaderGroup&, mce::RenderContext&, std::string, ResourcePackManager&>(Option*&&, Option*&&, std::function<void ()>&, Core::IFileSystem&, IFileAccess&, std::unique_ptr<mce::TextureGroup, std::default_delete<mce::TextureGroup> >&&, mce::ShaderGroup&, mce::RenderContext&, std::string&&, ResourcePackManager&)+181 in libminecraftpe.so+0x143daa5 [0xef6f5aa5]
#748 HYBRIS std::_MakeUniq<HummingbirdUI>::__single_object std::make_unique<HummingbirdUI, Option*, Option*, std::function<void ()>&, Core::IFileSystem&, IFileAccess&, std::unique_ptr<mce::TextureGroup, std::default_delete<mce::TextureGroup> >, mce::ShaderGroup&, mce::RenderContext&, std::string, ResourcePackManager&>(Option*&&, Option*&&, std::function<void ()>&, Core::IFileSystem&, IFileAccess&, std::unique_ptr<mce::TextureGroup, std::default_delete<mce::TextureGroup> >&&, mce::ShaderGroup&, mce::RenderContext&, std::string&&, ResourcePackManager&)+12 in libminecraftpe.so+0x143d9fc [0xef6f59fc]
#764 HYBRIS MinecraftGame::_initHummingbirdUI(SerialWorkList::WorkSections&)+556 in libminecraftpe.so+0x143206c [0xef6ea06c]
#784 HYBRIS BackgroundWorker::_processNextTask()+47 in libminecraftpe.so+0x3396b7f [0xf164eb7f]
#800 HYBRIS std::_Function_handler<SerialWorkList::WorkResult (SerialWorkList::WorkSections&), std::_Bind<std::_Mem_fn<SerialWorkList::WorkResult (MinecraftGame::*)(SerialWorkList::WorkSections&)> (MinecraftGame*, std::_Placeholder<1>)> >::_M_invoke(std::_Any_data const&, SerialWorkList::WorkSections&)+50 in libminecraftpe.so+0x1474492 [0xef72c492]
#804 HYBRIS std::_Function_handler<SerialWorkList::WorkResult (SerialWorkList::WorkSections&), std::_Bind<std::_Mem_fn<SerialWorkList::WorkResult (MinecraftGame::*)(SerialWorkList::WorkSections&)> (MinecraftGame*, std::_Placeholder<1>)> >::_M_invoke(std::_Any_data const&, SerialWorkList::WorkSections&)+8 in libminecraftpe.so+0x1474468 [0xef72c468]
#808 HYBRIS SerialWorkList::processNextWorkItem(IMinecraftEventing&)+174 in libminecraftpe.so+0x143a03e [0xef6f203e]
#828 HYBRIS Social::UserManager::getPrimaryUser() const+58 in libminecraftpe.so+0x1bc2c6a [0xefe7ac6a]
#836 HYBRIS MinecraftGame::getPrimaryUserOptions()+67 in libminecraftpe.so+0x14298e3 [0xef6e18e3]
#844 HYBRIS MinecraftGame::update()+4529 in libminecraftpe.so+0x1449491 [0xef701491]
Process exited with unexpected exit code: 6

**Comment by MCMrARM** [comment]
Please upgrade the launcher https://github.com/minecraft-linux/mcpelauncher-manifest/wiki/Troubleshooting#18-does-not-work-and-crashes-with-failed-to-locate-madvise
