### ISSUE TITLE
Process exited with unexpected exit code: 127 on Debian 10

### ISSUE THREAD

**Issue by Aaron-Pazdera** [minecraft-linux/mcpelauncher-manifest#342]
```
/tmp/.mount_Minecr0HXiUa/usr/bin/./mcpelauncher-client: error while loading shared libraries: libEGL.so.1: cannot open shared object file: No such file or directory
Process exited with unexpected exit code: 127
```
I'm unsure if this is related to #275, although it's quite possible that I just haven't gotten that far yet.

Also, looking at the troubleshooting information, it tells me that my CPU has no SSSE3 support and that the game may crash on startup, even though /proc/cpuinfo says that I do in fact support that instruction set.

**Comment by ChristopherHX** [comment]
You are using the unsupported appimage fr the wiki?
It would be worth installing the debian dependencies like written here https://github.com/ChristopherHX/linux-packaging-scripts/releases/tag/appimage

Because my appimages now tell you to read the page to fix it yourself.
