### ISSUE TITLE
it's not work on endless os

### ISSUE THREAD

**Issue by Andrei700** [minecraft-linux/mcpelauncher-manifest#347]
WHY NOT WORK?

**Comment by ChristopherHX** [comment]
**More information needed**
- What does not work?
- How have you installed the launcher?
For endless OS (flatpak) it would be https://flathub.org/apps/details/io.mrarm.mcpelauncher
Alternative for Linux (AppImage)
https://github.com/ChristopherHX/linux-packaging-scripts/releases/tag/appimage
Currently outdated and won't work for 1.16
https://mcpelauncher.readthedocs.io/

**Comment by Andrei700** [comment]
i hive the launcher!!!
