### ISSUE TITLE
Code:7

### ISSUE THREAD

**Issue by Murtadha27827** [minecraft-linux/mcpelauncher-manifest#348]
I try to install minecraft 1.14.1.2
in ubuntu 20.04 with the appimage
12:46:20 Info  [Launcher] Version: client c735370 / manifest b3dd620
12:46:20 Info  [Launcher] CPU: GenuineIntel Intel(R) Celeron(R) N4000 CPU @ 1.10GHz
12:46:20 Info  [Launcher] CPU supports SSSE3: YES
12:46:20 Trace [Launcher] Loading hybris libraries
12:46:20 Trace [HybrisUtils] Loaded OS library /tmp/.mount_MinecrAx996H/usr/share/mcpelauncher/libs/native/libfmod.so.9.16
12:46:20 Trace [HybrisUtils] Loaded OS library libm.so.6
12:46:20 Trace [HybrisUtils] Loaded OS library libz.so.1
12:46:20 Trace [Launcher] Loading Minecraft library
Process exited with unexpected exit code: 7
![Screenshot from 2020-07-03 12-55-13](https://user-images.githubusercontent.com/67784414/86457547-8113f180-bd2c-11ea-91c6-c84d5de4d7b4.png)

**Comment by ChristopherHX** [comment]
> minecraft 1.14.1.2

Your installed launcher can only launch selected (4) versions above 1.13.0.6
beta 1.14.1.2 is not included,
I gues you don't own the game.

Read this section to get 1.14.1.2 working
https://mcpelauncher.readthedocs.io/en/latest/getting_started.html#a-note-for-new-users
