### ISSUE TITLE
Minecraft has exited with a non-zero error code. (Catalina 10.15.5)

### ISSUE THREAD

**Issue by Minecrafter69** [minecraft-linux/mcpelauncher-manifest#349]
Minecraft (x86_64):
  Supported on your Device? Yes
  Game Installed? No
  Launcher Installed? Yes
Minecraft (x86):
  Supported on your Device? No
  Game Installed? Yes
  Launcher Installed? Yes
Minecraft (armeabi-v7a):
  Supported on your Device? N/A
  Game Installed? No
  Launcher Installed? No
Minecraft (arm64-v8a):
  Supported on your Device? N/A
  Game Installed? No
  Launcher Installed? No

What does this mean lmao?
Thanks in advance

**Comment by Mhowser** [comment]
Did you sign in to your google account so the launcher can get the game?

**Comment by Minecrafter69** [comment]
oh yes, it just worked magically, thanks for the advice nonetheless. now im having problems with crashes. sad
