### ISSUE TITLE
Minecraft has exited with non zero error code

### ISSUE THREAD

**Issue by Shalmon123** [minecraft-linux/mcpelauncher-manifest#350]
Minecraft (x86):
  Supported on your Device? Yes
  Game Installed? No
  Launcher Installed? Yes
Minecraft (armeabi-v7a):
  Supported on your Device? N/A
  Game Installed? Yes
  Launcher Installed? No
Minecraft (arm64-v8a):
  Supported on your Device? N/A
  Game Installed? No
  Launcher Installed? No
Minecraft (x86_64):
  Supported on your Device? N/A
  Game Installed? No
  Launcher Installed? No

**Comment by ChristopherHX** [comment]
```
Minecraft (armeabi-v7a):
Supported on your Device? N/A
Game Installed? Yes
```
You found an **arm** phone apk (no your pc needs x86 apk), please buy the game.
