### ISSUE TITLE
collapse

### ISSUE THREAD

**Issue by 234huhu** [minecraft-linux/mcpelauncher-manifest#353]
Minecraft (x86_64):
  Supported on your Device? Yes
  Game Installed? No
  Launcher Installed? Yes
Minecraft (x86):
  Supported on your Device? No
  Game Installed? No
  Launcher Installed? Yes
Minecraft (armeabi-v7a):
  Supported on your Device? N/A
  Game Installed? Yes
  Launcher Installed? No
Minecraft (arm64-v8a):
  Supported on your Device? N/A
  Game Installed? No
  Launcher Installed? No

**Comment by ChristopherHX** [comment]
Using macOS 10.15, it cannot run arm apks.
You need x86_64 apks (very rare)

Likly this bug
https://github.com/minecraft-linux/mcpelauncher-ui-manifest/issues/22
