### ISSUE TITLE
why not working to import apk?

### ISSUE THREAD

**Issue by Andrei700** [minecraft-linux/mcpelauncher-manifest#365]
why?

**Comment by Andrei700** [comment]
https://drive.google.com/file/d/1SO5GGIiKiPdorsIp1HP_72ATPTJeE9i3/view

**Comment by Andrei700** [comment]
why not working?

**Comment by Mhowser** [comment]
You most likely have an ARM apk. This launcher REQUIRES an x86 or x86_64
apk obtained by signing in to google from the launcher, which will download
the correct apk needed. You also need to have purchased Minecraft from the
google play store.
