### ISSUE TITLE
The app only works with older version/always exits with error

### ISSUE THREAD

**Issue by szalony9szymek** [minecraft-linux/mcpelauncher-manifest#367]
I logged in with google. Latest version does not install, only the "latest" out of the older version list (1.14.something)
Also, when i use the working version on exit(on clicking X) it gives an error(0)

**Comment by ChristopherHX** [comment]
The other two "newer" app's exits "most of the time" without errors ("beta" is excluded)
Please "upgrade" the launcher, but they might be a bit unstable in another way.
[You find it here](
https://github.com/ChristopherHX/mcpelauncher-manifest/releases)
This allow playing Minecraft PE till 1.16.10.02 inclusive, but won't work for current beta

**Comment by szalony9szymek** [comment]
i get a failed to open zip 21 error now with 1.16.10.02 and 1.16.1.02

**Comment by ChristopherHX** [comment]
open zip 21 error is an error, **which is only appearing for pirated apks**.
Please use the google play download feature or use valid apk (no pirated apks are _mostly_  invalid and illegal).
Using the Aurora store as apk source and spoofing a x86 (or x86_64 only ng) device works too as far as I used the launcher.
To get 1.16.10.02:
If you opted into google play beta, opt out play store app minecraft page (for getting it without a versionsdb update)
Start the launcher select google play latest (if you changed the default version), it will download a valid apk for you.

**Comment by szalony9szymek** [comment]
Would it be possible for you to send me the apk? I own the game ( https://i.ibb.co/0YVRLjp/Screenshot-20200801-210050-Google-Play-Store.jpg )
I am kind of scared to input my google password into the launcher
Thanks

**Comment by szalony9szymek** [comment]
Alright used google it worked

**Comment by szalony9szymek** [comment]
For anyone ahving the same issue with the older version/the error on closing the game,update the launx
cher. For anyone having the zip issue, use google login
