### ISSUE TITLE
1.16.20.03 doesn't work

### ISSUE THREAD

**Issue by atifc1234** [minecraft-linux/mcpelauncher-manifest#380]
i know that there are many issues with the same problem but now i'm getting a different error then what i had gotten before. I use mac os catalina and the error is as follows: 
Minecraft (x86_64):
  Supported on your Device? Yes
  Game Installed? No
  Launcher Installed? Yes
Minecraft (x86):
  Supported on your Device? No
  Game Installed? No
  Launcher Installed? Yes
Minecraft (armeabi-v7a):
  Supported on your Device? N/A
  Game Installed? Yes
  Launcher Installed? No
Minecraft (arm64-v8a):
  Supported on your Device? N/A
  Game Installed? No
  Launcher Installed? No
it also exited with a non-zero error code.

**Comment by atifc1234** [comment]
it gives that error immediately after i press play.

**Comment by ChristopherHX** [comment]
No armeabi-v7a apks will never run with this launcher on intel macs.
Additionally 1.16.20.3 is _currently_ unsupported.
You would need an x86_64 apk.
Minecraft 1.16.10.02 is the latest working Minecraft version.
Mojang changed to much in past month.

I know this errormessage is missleading, but just buying the game and login with google is easier.

**Comment by T1ChuyUwU** [comment]
Dear ChristopherHX, I have the game bought on android but it is more comfortable to play it on PC. Although I do not have Windows 10, this version of macOS is very useful to me so I will be patient to make this version compatible. I send you the best cheers from Mexico.
