### ISSUE TITLE
player data resets on server after closing the game entirly and reopening

### ISSUE THREAD

**Issue by tuxinal** [minecraft-linux/mcpelauncher-manifest#390]
from my understanding upon starting minecraft the game gives you a unique id for being identified when opening a multiplayer game the launcher removes that id every time you open (or close i haven't really checked the code) the launcher and minecraft gives you a new id and any server that you have opened will not recognize you and boom your stuff is gone
i am not logged in to xbox account for... reasons i am not sure if this will happen if i have logged in to my xbox account

also i am using the flathub version

**Comment by ChristopherHX** [comment]
_I cannot reproduce this with offical dedicated server 1.16.20.03 and flatpak on ubuntu 20.04 with and without xboxlive_

**Comment by tuxinal** [comment]
its not user permission its the entire inventory and position and all of that stuff gone.

make sure you completely close the launcher and reopen it

also i did copy everything from the appimage data folder (~/.local/share/mcpelauncher) to the flathub data folder (~/.var/app/io.mrarm.mcpelauncher/data/mcpelauncher/) could that be the problem?

**Comment by tuxinal** [comment]
i have cleared out the flathub versions data folder(only leaving the versions and profile directory) and also tried a fresh BDS hosted on my laptop and the issue still persists

**Comment by ChristopherHX** [comment]
> make sure you completely close the launcher and reopen it

I don't unserstand, I killed both the server (https://www.minecraft.net/en-us/download/server/bedrock) and the client (https://flathub.org/apps/details/io.mrarm.mcpelauncher) completly.
I only loose my inventory if I..
- ...switch my xbox account to another one (switch back restores)
- ...change my username ingame (switch back restores)
- ...play one a weird featured server

Sorry I'm pretty confused.

**Comment by tuxinal** [comment]
are you aware of where this ID is stored?

**Comment by ChristopherHX** [comment]
Oh I got it, I did this and never had this issue again.
`flatpak --user override --persist=../../../data io.mrarm.mcpelauncher`

**Comment by tuxinal** [comment]
where should i run this? in the home folder?

**Comment by ChristopherHX** [comment]
anywhere on your pc, flatpak relative

**Comment by tuxinal** [comment]
now its working! probably should specify that somewhere
