### ISSUE TITLE
Won't let me open the game

### ISSUE THREAD

**Issue by DevArxify** [minecraft-linux/mcpelauncher-manifest#394]
Hi, it won't let me open the game, I don't know why, I have the version installed and when I want to open it, it crashes. Can someone help me with this problem? My operating system is: macOS High Sierra

**Comment by kushagraPP** [comment]
same problem

**Comment by HelloThereYeet** [comment]
yeah, it wouldnt open. i upgraded my laptop to macOs Catalina, still didint work. so i really dont know what to do.
i hope we can find the problem sometime soon

**Comment by ChristopherHX** [comment]
There is currently no new stable update, 1.16.10 is the last working version.

An unstable Preview of the next Launcher Update for 1.16.20-100 can be found here
https://github.com/ChristopherHX/mcpelauncher-manifest/releases/tag/stable
Sumary of the Interesting part
> ### very unstable preview (next generation)
> #### [for GNU/Linux (Link to download page)](https://github.com/ChristopherHX/linux-packaging-scripts/releases/tag/ng.appimage)
> Minecraft (x86, x86_64) 1.1 - 1.16.100 may work
> #### [for OS X Yosemite 10.10, El Capitan 10.11, macOS Sierra 10.12, High Sierra 10.13, Mojave 10.14, Catalina 10.15 and later (Intel mac) (Link to download page)](https://github.com/ChristopherHX/osx-packaging-scripts/releases/tag/ng.dmg)
> Minecraft (x86_64) 1.14.60.5 - 1.16.100 may work on modern x86_64
> ~~Minecraft (x86) 1.1.0 - 1.16.0.66, 1.16.1.02 works on x86_64 (till 10.14 Mojave)~~, **no sound 1.16.20+, beta 1.16.0.67+**,

**Comment by arxifythedev** [comment]
goddamn this is from 3 years ago 😂 i'ma close this because i don't even use my macbook anymore
