### ISSUE TITLE
Crashes upon running the game "Process exited with unexpected exit code: 6"

### ISSUE THREAD

**Issue by VitaaXX** [minecraft-linux/mcpelauncher-manifest#407]
Always crashes the game when trying to run it, the crash report is:

15:53:05 Info  [Launcher] Version: client e3958c2 / manifest abea115
15:53:05 Info  [Launcher] CPU: GenuineIntel Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz
15:53:05 Info  [Launcher] CPU supports SSSE3: YES
15:53:05 Trace [Launcher] Loading hybris libraries
15:53:05 Trace [HybrisUtils] Loaded OS library libm.dylib
load_library: Undefined symbol ynf
load_library: Undefined symbol y1f
load_library: Undefined symbol sincosf
load_library: Undefined symbol sincos
load_library: Undefined symbol significandl
load_library: Undefined symbol scalbf
load_library: Undefined symbol jnf
load_library: Undefined symbol j1f
load_library: Undefined symbol j0f
load_library: Undefined symbol gammaf_r
load_library: Undefined symbol finitef
load_library: Undefined symbol gamma_r
load_library: Undefined symbol gammaf
load_library: Undefined symbol y0f
load_library: Undefined symbol dremf
load_library: Undefined symbol fedisableexcept
load_library: Undefined symbol sincosl
load_library: Undefined symbol significandf
load_library: Undefined symbol feenableexcept
15:53:05 Trace [HybrisUtils] Loaded OS library libz.dylib
15:53:05 Trace [HybrisUtils] Loaded OS library /Applications/Minecraft Bedrock Launcher.app/Contents/Resources/mcpelauncher/lib/native/x86/libfmod.dylib
load_library: Undefined symbol _ZN4FMOD14ChannelControl15set3DAttributesEPK11FMOD_VECTORS3_
load_library: Undefined symbol glMultMatrixf
load_library: Undefined symbol glFogf
load_library: Undefined symbol glFogfv
load_library: Undefined symbol glColorPointer
load_library: Undefined symbol glVertexPointer
load_library: Undefined symbol glOrthof
load_library: Undefined symbol glRotatef
load_library: Undefined symbol glScalef
load_library: Undefined symbol glDisableClientState
load_library: Undefined symbol glPopMatrix
load_library: Undefined symbol glTranslatef
load_library: Undefined symbol glColor4f
load_library: Undefined symbol glLightModelf
load_library: Undefined symbol glAlphaFunc
load_library: Undefined symbol glVertexAttribPointer
load_library: Undefined symbol glVertexAttrib3fv
load_library: Undefined symbol glVertexAttrib3f
load_library: Undefined symbol glVertexAttrib2fv
load_library: Undefined symbol glVertexAttrib1fv
load_library: Undefined symbol glValidateProgram
load_library: Undefined symbol glUseProgram
load_library: Undefined symbol glUniformMatrix4fv
load_library: Undefined symbol glUniformMatrix3fv
load_library: Undefined symbol glMatrixMode
load_library: Undefined symbol glUniformMatrix2fv
load_library: Undefined symbol glUniform4fv
load_library: Undefined symbol glUniform3iv
load_library: Undefined symbol glUniform3fv
load_library: Undefined symbol glUniform2fv
load_library: Undefined symbol glUniform1iv
load_library: Undefined symbol glUniform1i
load_library: Undefined symbol glUniform1fv
load_library: Undefined symbol glTexSubImage2D
load_library: Undefined symbol glTexParameteri
load_library: Undefined symbol glUniform3f
load_library: Undefined symbol glTexParameterf
load_library: Undefined symbol glStencilOpSeparate
load_library: Undefined symbol glStencilMask
load_library: Undefined symbol glLightfv
load_library: Undefined symbol glStencilFunc
load_library: Undefined symbol glShaderSource
load_library: Undefined symbol glUniform1f
load_library: Undefined symbol glShaderBinary
load_library: Undefined symbol glHint
load_library: Undefined symbol glScissor
load_library: Undefined symbol glGetBufferParameteriv
load_library: Undefined symbol glRenderbufferStorage
load_library: Undefined symbol glReadPixels
load_library: Undefined symbol glPixelStorei
load_library: Undefined symbol glDeleteTextures
load_library: Undefined symbol glIsBuffer
load_library: Undefined symbol glLineWidth
load_library: Undefined symbol glIsEnabled
load_library: Undefined symbol glGetVertexAttribiv
load_library: Undefined symbol glGetUniformLocation
load_library: Undefined symbol glGetTexParameteriv
load_library: Undefined symbol glGetVertexAttribPointerv
load_library: Undefined symbol glViewport
load_library: Undefined symbol glGetTexParameterfv
load_library: Undefined symbol glIsTexture
load_library: Undefined symbol glGetString
load_library: Undefined symbol glCopyTexImage2D
load_library: Undefined symbol glIsProgram
load_library: Undefined symbol glVertexAttrib4fv
load_library: Undefined symbol glGetUniformiv
load_library: Undefined symbol glUniform3i
load_library: Undefined symbol glGetShaderPrecisionFormat
load_library: Undefined symbol glGetShaderiv
load_library: Undefined symbol glGetRenderbufferParameteriv
load_library: Undefined symbol glGetProgramiv
load_library: Undefined symbol glShadeModel
load_library: Undefined symbol glGetIntegerv
load_library: Undefined symbol glGetFloatv
load_library: Undefined symbol glUniform2i
load_library: Undefined symbol glGetError
load_library: Undefined symbol glGetBooleanv
load_library: Undefined symbol glVertexAttrib4f
load_library: Undefined symbol glGetAttribLocation
load_library: Undefined symbol glGetActiveUniform
load_library: Undefined symbol glTexParameteriv
load_library: Undefined symbol glGetActiveAttrib
load_library: Undefined symbol glStencilMaskSeparate
load_library: Undefined symbol glGenRenderbuffers
load_library: Undefined symbol glCompressedTexSubImage2D
load_library: Undefined symbol glGetProgramInfoLog
load_library: Undefined symbol glDeleteShader
load_library: Undefined symbol glGenBuffers
load_library: Undefined symbol glSampleCoverage
load_library: Undefined symbol glGenTextures
load_library: Undefined symbol glGetVertexAttribfv
load_library: Undefined symbol glUniform4iv
load_library: Undefined symbol glFrontFace
load_library: Undefined symbol glPushMatrix
load_library: Undefined symbol glUniform2iv
load_library: Undefined symbol glIsShader
load_library: Undefined symbol glBindFramebuffer
load_library: Undefined symbol glFramebufferTexture2D
load_library: Undefined symbol glUniform4i
load_library: Undefined symbol glClearStencil
load_library: Undefined symbol glDeleteRenderbuffers
load_library: Undefined symbol glFinish
load_library: Undefined symbol glBlendFuncSeparate
load_library: Undefined symbol glBindAttribLocation
load_library: Undefined symbol glClear
load_library: Undefined symbol glEnableVertexAttribArray
load_library: Undefined symbol glStencilFuncSeparate
load_library: Undefined symbol glPolygonOffset
load_library: Undefined symbol glDisable
load_library: Undefined symbol glDetachShader
load_library: Undefined symbol glReleaseShaderCompiler
load_library: Undefined symbol glCompressedTexImage2D
load_library: Undefined symbol glBindRenderbuffer
load_library: Undefined symbol glDepthMask
load_library: Undefined symbol glIsFramebuffer
load_library: Undefined symbol glGetUniformfv
load_library: Undefined symbol glUniform4f
load_library: Undefined symbol glAttachShader
load_library: Undefined symbol glLoadIdentity
load_library: Undefined symbol glFramebufferRenderbuffer
load_library: Undefined symbol glStencilOp
load_library: Undefined symbol glDisableVertexAttribArray
load_library: Undefined symbol glIsRenderbuffer
load_library: Undefined symbol glDeleteProgram
load_library: Undefined symbol glDrawArrays
load_library: Undefined symbol glBlendEquationSeparate
load_library: Undefined symbol glCompileShader
load_library: Undefined symbol glVertexAttrib1f
load_library: Undefined symbol glDeleteFramebuffers
load_library: Undefined symbol glDeleteBuffers
load_library: Undefined symbol glTexParameterfv
load_library: Undefined symbol glLinkProgram
load_library: Undefined symbol glGenerateMipmap
load_library: Undefined symbol glCullFace
load_library: Undefined symbol glEnableClientState
load_library: Undefined symbol glVertexAttrib2f
load_library: Undefined symbol glTexImage2D
load_library: Undefined symbol glDrawElements
load_library: Undefined symbol glGenFramebuffers
load_library: Undefined symbol glCreateShader
load_library: Undefined symbol glGetFramebufferAttachmentParameteriv
load_library: Undefined symbol glClearColor
load_library: Undefined symbol glCreateProgram
load_library: Undefined symbol glClearDepthf
load_library: Undefined symbol glBlendFunc
load_library: Undefined symbol glBindBuffer
load_library: Undefined symbol glGetShaderInfoLog
load_library: Undefined symbol glCheckFramebufferStatus
load_library: Undefined symbol glBufferSubData
load_library: Undefined symbol glNormalPointer
load_library: Undefined symbol glActiveTexture
load_library: Undefined symbol glFogx
load_library: Undefined symbol glColorMask
load_library: Undefined symbol glBufferData
load_library: Undefined symbol glDepthFunc
load_library: Undefined symbol glFlush
load_library: Undefined symbol glTexCoordPointer
load_library: Undefined symbol glCopyTexSubImage2D
load_library: Undefined symbol glGetAttachedShaders
load_library: Undefined symbol glDepthRangef
load_library: Undefined symbol glBlendEquation
load_library: Undefined symbol glGetShaderSource
load_library: Undefined symbol glEnable
load_library: Undefined symbol glBlendColor
load_library: Undefined symbol glUniform2f
load_library: Undefined symbol glBindTexture
15:53:05 Trace [Launcher] Loading Minecraft library
linker: dlopen(name="libminecraftpe.so", flags=0x0, extinfo=(null), caller="(null)", caller_ns=@0x4a8184, targetSdkVersion=10000) ...
linker: find_libraries(ns=): task=libminecraftpe.so, is_dt_needed=0
linker: load_library(ns=, task=libminecraftpe.so, flags=0x0, search_linked_namespaces=1): calling open_library with realpath=
linker: load_library(ns=, task=libminecraftpe.so, flags=0x0, realpath=/Users/vitaa/Library/Application Support/mcpelauncher/versions/1.16.100.57/lib/x86/libminecraftpe.so, search_linked_namespaces=1)
linker: load_library(ns=, task=libminecraftpe.so): Adding DT_NEEDED task: liblog.so
linker: load_library(ns=, task=libminecraftpe.so): Adding DT_NEEDED task: libandroid.so
linker: load_library(ns=, task=libminecraftpe.so): Adding DT_NEEDED task: libEGL.so
linker: load_library(ns=, task=libminecraftpe.so): Adding DT_NEEDED task: libfmod.so
linker: load_library(ns=, task=libminecraftpe.so): Adding DT_NEEDED task: libm.so
linker: load_library(ns=, task=libminecraftpe.so): Adding DT_NEEDED task: libc++_shared.so
linker: load_library(ns=, task=libminecraftpe.so): Adding DT_NEEDED task: libdl.so
linker: load_library(ns=, task=libminecraftpe.so): Adding DT_NEEDED task: libc.so
linker: find_libraries(ns=): task=liblog.so, is_dt_needed=1
linker: find_library_internal(ns=, task=liblog.so): Already loaded (by soname): liblog.so
linker: find_libraries(ns=): task=libandroid.so, is_dt_needed=1
linker: find_library_internal(ns=, task=libandroid.so): Already loaded (by soname): libandroid.so
linker: find_libraries(ns=): task=libEGL.so, is_dt_needed=1
linker: find_library_internal(ns=, task=libEGL.so): Already loaded (by soname): libEGL.so
linker: find_libraries(ns=): task=libfmod.so, is_dt_needed=1
linker: find_library_internal(ns=, task=libfmod.so): Already loaded (by soname): libfmod.so
linker: find_libraries(ns=): task=libm.so, is_dt_needed=1
linker: find_library_internal(ns=, task=libm.so): Already loaded (by soname): libm.so
linker: find_libraries(ns=): task=libc++_shared.so, is_dt_needed=1
linker: load_library(ns=, task=libc++_shared.so, flags=0x0, search_linked_namespaces=1): calling open_library with realpath=
linker: load_library(ns=, task=libc++_shared.so, flags=0x0, realpath=/Users/vitaa/Library/Application Support/mcpelauncher/versions/1.16.100.57/lib/x86/libc++_shared.so, search_linked_namespaces=1)
linker: load_library(ns=, task=libc++_shared.so): Adding DT_NEEDED task: libc.so
linker: load_library(ns=, task=libc++_shared.so): Adding DT_NEEDED task: libdl.so
linker: find_libraries(ns=): task=libdl.so, is_dt_needed=1
linker: find_library_internal(ns=, task=libdl.so): Already loaded (by soname): libdl.so
linker: find_libraries(ns=): task=libc.so, is_dt_needed=1
linker: find_library_internal(ns=, task=libc.so): Already loaded (by soname): libc.so
linker: find_libraries(ns=): task=libc.so, is_dt_needed=1
linker: find_library_internal(ns=, task=libc.so): Already loaded (by soname): libc.so
linker: find_libraries(ns=): task=libdl.so, is_dt_needed=1
linker: find_library_internal(ns=, task=libdl.so): Already loaded (by soname): libdl.so
linker: ... dlclose(realpath="/Users/vitaa/Library/Application Support/mcpelauncher/versions/1.16.100.57/lib/x86/libminecraftpe.so"@0x3749610) ... load group root is "/Users/vitaa/Library/Application Support/mcpelauncher/versions/1.16.100.57/lib/x86/libminecraftpe.so"@0x3749610
linker: ... dlclose: calling destructors for "/Users/vitaa/Library/Application Support/mcpelauncher/versions/1.16.100.57/lib/x86/libminecraftpe.so"@0x3749610 ... 
linker: ... dlclose: calling destructors for "/Users/vitaa/Library/Application Support/mcpelauncher/versions/1.16.100.57/lib/x86/libminecraftpe.so"@0x3749610 ... done
linker: ... dlclose: calling destructors for "/Users/vitaa/Library/Application Support/mcpelauncher/versions/1.16.100.57/lib/x86/libc++_shared.so"@0x3749770 ... 
linker: ... dlclose: calling destructors for "/Users/vitaa/Library/Application Support/mcpelauncher/versions/1.16.100.57/lib/x86/libc++_shared.so"@0x3749770 ... done
linker: ... dlclose: unloading "/Users/vitaa/Library/Application Support/mcpelauncher/versions/1.16.100.57/lib/x86/libminecraftpe.so"@0x3749610 ...
linker: ... dlclose: unloading "/Users/vitaa/Library/Application Support/mcpelauncher/versions/1.16.100.57/lib/x86/libc++_shared.so"@0x3749770 ...
linker: ... dlclose: unload_si was not linked - not unloading external references ...
linker: ... dlopen failed: cannot locate symbol "__memset_chk" referenced by "/Users/vitaa/Library/Application Support/mcpelauncher/versions/1.16.100.57/lib/x86/libminecraftpe.so"...
Signal 11 received
Backtrace elements: 7
#0 0   mcpelauncher-client32               0x001de5e1 _ZN12CrashHandler12handleSignalEiPv + 273
#1 1   libsystem_platform.dylib            0xa7d03bae _sigtramp + 46
#2 2   ???                                 0xffffffff 0x0 + 4294967295
#3 3   mcpelauncher-client32               0x001e0c02 _ZNSt3__1plIcNS_11char_traitsIcEENS_9allocatorIcEEEENS_12basic_stringIT_T0_T1_EEOS9_PKS6_ + 50
#4 4   mcpelauncher-client32               0x001e1464 _ZN14MinecraftUtils16loadMinecraftLibEv + 148
#5 5   mcpelauncher-client32               0x0006f7d9 main + 4537
#6 6   libdyld.dylib                       0xa7b1a051 start + 1
Dumping stack...

Process exited with unexpected exit code: 6

hope this is fixed soon

**Comment by nazthelizard122** [comment]
i have a similar issue but i just get "Process exited with unexpected exit code: 6" thats literally it

**Comment by ChristopherHX** [comment]
There is only a crashlog window named gamelog.
It opens only if it crashs, or you enabled it with show gamelog then it is allways visible.
**This line is the end of all crashlogs**, only the number may vary.

If you disabled the gamelog, then enable it again or it is blank without any information than a crash.
`Process exited with unexpected exit code: 6`

_I may close this as stale issue_

**Comment by ChristopherHX** [comment]
Please don't open issues if you aren't willing to respond in a reasonable amount of time.
