### ISSUE TITLE
I cant run the game and i cant pin point what wrong with my system

### ISSUE THREAD

**Issue by NickWilde263** [minecraft-linux/mcpelauncher-manifest#410]
Minecraft (x86):
  Supported on your Device? Yes
  Game Installed? No
  Launcher Installed? Yes
Minecraft (armeabi-v7a):
  Supported on your Device? N/A
  Game Installed? Yes
  Launcher Installed? No
Minecraft (arm64-v8a):
  Supported on your Device? N/A
  Game Installed? No
  Launcher Installed? No
Minecraft (x86_64):
  Supported on your Device? N/A
  Game Installed? No
  Launcher Installed? No

The game log is not make sense for me to fix by myself and i cant run the game

**Comment by ChristopherHX** [comment]
Sign in to google and download the game via the launcher.
You imported an **arm apk**, but you need a **x86 apk**.

**Comment by NickWilde263** [comment]
the game apk extract properly no error indicating i import arm apk

**Comment by NickWilde263** [comment]
i tried 4 apk from different site and version

**Comment by NickWilde263** [comment]
> Sign in to google and download the game via the launcher.
> You imported an **arm apk**, but you need a **x86 apk**.

it require me to buy the game

**Comment by ChristopherHX** [comment]
Obviously you need to buy the game, everything else is illegal and unsupported.
Then you will have access to all previous versions of Minecraft (Android) too.

**Comment by NickWilde263** [comment]
if like that why there are import apk

**Comment by NickWilde263** [comment]
the apk i use is install properly on my android

**Comment by ChristopherHX** [comment]
This means nothing, because your android is 90% an arm device.
Your pc has a different cpu type than your android device.
Also android x86 sometimes have an arm emulator which this launcher doesn't have.

**Comment by NickWilde263** [comment]
oh ok

**Comment by NickWilde263** [comment]
it need an installed Minecraft in x86 Android i literally need install x86 Minecraft on real android first then extract it from android then it work

**Comment by NickWilde263** [comment]
Here the apk i use for anyone have same issue
Google Drive Link for the file i use if you have same issue 

https://drive.google.com/file/d/1JJ1F_mqzUG0MJ6CyeHPXf3eXvVeFPcMa/view?usp=sharing

**Comment by IceCruelStuff** [comment]
> Here the apk i use for anyone have same issue
> Google Drive Link for the file i use if you have same issue
> 
> https://drive.google.com/file/d/1JJ1F_mqzUG0MJ6CyeHPXf3eXvVeFPcMa/view?usp=sharing

it says access denied

**Comment by NickWilde263** [comment]
wait ok
maybe i set wrong permmisiion

**Comment by NickWilde263** [comment]
try again

**Comment by ChristopherHX** [comment]
# Do not link to apks here that is illegal and harm this project

**Comment by NickWilde263** [comment]
ok

**Comment by NickWilde263** [comment]
sorry i dont know about that
