### ISSUE TITLE
using data directory feature disables use of microsoft accounts

### ISSUE THREAD

**Issue by peebowo** [minecraft-linux/mcpelauncher-manifest#415]
when you use the data directory feature and put it on a directory, the microsoft sign in doesn't work

**Comment by ChristopherHX** [comment]
What do you mean by?
> the data directory feature

How do I reproduce this?
Which OS?
Which Launcher Version?
Which Minecraft Version?

The login provider for xbox live and internal storage support have been changed a lot since you opened this issue.

**Comment by peebowo** [comment]
nvm fixied it a while ago xD
