### ISSUE TITLE
Minecraft has exited with a non-zero error code. (1.2-1.16.40)

### ISSUE THREAD

**Issue by BeastlyGhost** [minecraft-linux/mcpelauncher-manifest#419]
01:43:50 Info  [Launcher] Version: client 4432ade / manifest 830d61c
01:43:50 Info  [Launcher] CPU: AuthenticAMD AMD Phenom(tm) II X2 565 Processor
01:43:50 Info  [Launcher] CPU supports SSSE3: NO
01:43:50 Trace [Launcher] Loading hybris libraries
01:43:50 Trace [HybrisUtils] Loaded OS library /tmp/.mount_MinecrbrePon/usr/share/mcpelauncher/libs/native/libfmod.so.9.16
01:43:50 Trace [HybrisUtils] Loaded OS library libm.so.6
01:43:50 Trace [HybrisUtils] Loaded OS library libz.so.1
01:43:50 Info  [Launcher] Creating window
01:43:50 Trace [Launcher] Loading gamepad mappings: /tmp/.mount_MinecrbrePon/usr/share/mcpelauncher/gamecontrollerdb.txt
01:43:50 Trace [Launcher] Loading Minecraft library
01:43:51 Info  [Launcher] Loaded Minecraft library
01:43:51 Debug [Launcher] Minecraft is at offset 0xe7b91000
01:43:51 Trace [AppPlatform] Vtable size = 169
01:43:51 Trace [Patch] Patching - original: 85 83 87 86 129
01:43:51 Trace [Patch] Patching - result: 233 107 49 239 29
01:43:51 Trace [JNIVM] Unresolved symbol jnivm_com_mojang_minecraftpe_MainActivity_unpackMonoAssemblies
01:43:51 Trace [JNIVM] Unresolved symbol jnivm_com_mojang_minecraftpe_MainActivity_getFormattedDateString
01:43:51 Trace [JNIVM] Unresolved symbol jnivm_com_mojang_minecraftpe_MainActivity_getFileTimestamp
01:43:51 Trace [JNIVM] Unresolved symbol jnivm_com_mojang_minecraftpe_MainActivity_getAvailableMemory
01:43:51 Trace [JNIVM] Unresolved symbol jnivm_com_mojang_minecraftpe_MainActivity_createDeviceID
01:43:51 Trace [JNIVM] Unresolved symbol jnivm_org_apache_http_Header_getName
01:43:51 Trace [JNIVM] Unresolved symbol jnivm_org_apache_http_Header_getValue
libevdev_new_from_fd error -22 (/dev/input/js0)
libevdev_new_from_fd error -22 (/dev/input/js1)
01:43:52 Trace [WindowCallbacks] Gamepad connected #1
01:43:52 Trace [WindowCallbacks] Gamepad connected #0
01:43:52 Warn  [Launcher] Android stub called
01:43:52 Warn  [Launcher] Android stub called
01:43:52 Warn  [Launcher] Android stub called
01:43:52 Warn  [Launcher] Android stub called
01:43:52 Warn  [Launcher] Android stub called
01:43:52 Error [JNIVM] Object not found in current local layer
01:43:52 Debug [HttpCallStaticGlue] Successfully registerered HttpCall methods
01:43:52 Error [JNIVM] Object not found in current local layer
01:43:52 Debug [XSAPI.Android] Successfully registerered HttpCall methods
01:43:52 Error [JNIVM] Object not found in current local layer
01:43:52 Debug [HttpCallStaticGlue] Successfully registerered HttpCall methods
01:43:52 Error [JNIVM] Object not found in current local layer
01:43:52 Debug [XboxLiveAppConfig] Successfully registerered XboxLiveAppConfig methods
01:43:52 Error [JNIVM] Object not found in current local layer
01:43:52 Debug [XSAPI.Android] Successfully registerered HttpCall tcuiMethods
01:43:52 Trace [XBOXLive] Reading xbox config file
terminate called after throwing an instance of 'std::runtime_error'
  what():  mkdir failed, path = /home/ender/.cache/mcpelauncher/cll
Signal 6 received
Backtrace elements: 16
#0 /tmp/.mount_MinecrbrePon/usr/bin/./mcpelauncher-client(_ZN12CrashHandler12handleSignalEiPv+0xf1) [0x82d22e1]
#1 linux-gate.so.1(__kernel_sigreturn+0) [0xf7f3d560]
#2 linux-gate.so.1(__kernel_vsyscall+0x9) [0xf7f3d549]
#3 /usr/lib32/libc.so.6(gsignal+0xca) [0xf75fc1ea]
#4 /usr/lib32/libc.so.6(abort+0x129) [0xf75e440e]
#5 /usr/lib32/libstdc++.so.6(+0x75980) [0xf793b980]
#6 /usr/lib32/libstdc++.so.6(+0x837c7) [0xf79497c7]
#7 /usr/lib32/libstdc++.so.6(+0x83853) [0xf7949853]
#8 /usr/lib32/libstdc++.so.6(+0x83bb5) [0xf7949bb5]
#9 /tmp/.mount_MinecrbrePon/usr/bin/./mcpelauncher-client(_ZN8FileUtil14mkdirRecursiveERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x276) [0x83622b6]
#10 /tmp/.mount_MinecrbrePon/usr/bin/./mcpelauncher-client(_ZN14XboxLiveHelper7initCllERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x1ef) [0x826e1df]
#11 /tmp/.mount_MinecrbrePon/usr/bin/./mcpelauncher-client(_ZN5jnivm3com9microsoft4xbox3idp7interop7Interop7InitCLLEP7_JNIEnvP7_jclassPNS_7android7content7ContextEPNS_4java4lang6StringE+0x163) [0x82375f3]
#12 /tmp/.mount_MinecrbrePon/usr/bin/./mcpelauncher-client(jnivm_com_microsoft_xbox_idp_interop_Interop_InitCLL+0x40) [0x8238ba0]
#13 /tmp/.mount_MinecrbrePon/usr/bin/./mcpelauncher-client(_Z17CallStaticMethodVP7_JNIEnvP7_jclassP10_jmethodIDP6jvalue+0x43) [0x8282783]
#14 /tmp/.mount_MinecrbrePon/usr/bin/./mcpelauncher-client(_Z17CallStaticMethodVP7_JNIEnvP7_jclassP10_jmethodIDPc+0x90) [0x8282850]
#15 HYBRIS _JNIEnv::CallStaticVoidMethod(_jclass*, _jmethodID*, ...)+61 in libminecraftpe.so+0x236ebfd [0xe9effbfd]
Dumping stack...
#780 HYBRIS (null)+-353147236 in libminecraftpe.so+0x33a569c [0xeaf3669c]
#782 HYBRIS _JNIEnv::CallStaticVoidMethod(_jclass*, _jmethodID*, ...)+61 in libminecraftpe.so+0x236ebfd [0xe9effbfd]
#787 HYBRIS (null)+-358381359 in libminecraftpe.so+0x2ea78d1 [0xeaa388d1]
#793 HYBRIS (null)+-353147236 in libminecraftpe.so+0x33a569c [0xeaf3669c]
#794 HYBRIS xbox::services::java_interop::init_cll()+1273 in libminecraftpe.so+0x24cce19 [0xea05de19]
#802 HYBRIS (null)+-352084924 in libminecraftpe.so+0x34a8c44 [0xeb039c44]
#810 HYBRIS (null)+-353147236 in libminecraftpe.so+0x33a569c [0xeaf3669c]
#811 HYBRIS (null)+-352084924 in libminecraftpe.so+0x34a8c44 [0xeb039c44]
#815 HYBRIS (null)+-353212916 in libminecraftpe.so+0x339560c [0xeaf2660c]
#817 HYBRIS (null)+-353872672 in libminecraftpe.so+0x32f44e0 [0xeae854e0]
#818 HYBRIS (null)+-353872120 in libminecraftpe.so+0x32f4708 [0xeae85708]
#825 HYBRIS (null)+-352085160 in libminecraftpe.so+0x34a8b58 [0xeb039b58]
#828 HYBRIS (null)+-353874168 in libminecraftpe.so+0x32f3f08 [0xeae84f08]
#855 HYBRIS (null)+-352085160 in libminecraftpe.so+0x34a8b58 [0xeb039b58]
#859 HYBRIS (null)+-352086016 in libminecraftpe.so+0x34a8800 [0xeb039800]
#860 HYBRIS (null)+-352086072 in libminecraftpe.so+0x34a87c8 [0xeb0397c8]
#861 HYBRIS (null)+-352086064 in libminecraftpe.so+0x34a87d0 [0xeb0397d0]
#863 HYBRIS (null)+-352084924 in libminecraftpe.so+0x34a8c44 [0xeb039c44]
#866 HYBRIS operator new(unsigned int)+39 in libminecraftpe.so+0x28f7427 [0xea488427]
#874 HYBRIS (null)+-363991226 in libminecraftpe.so+0x294df46 [0xea4def46]
#879 HYBRIS (null)+-363991321 in libminecraftpe.so+0x294dee7 [0xea4deee7]
#886 HYBRIS xbox::services::system::xbox_live_services_settings::xbox_live_services_settings()+286 in libminecraftpe.so+0x24c1f0e [0xea052f0e]
#887 HYBRIS operator new(unsigned int)+12 in libminecraftpe.so+0x28f740c [0xea48840c]
#898 HYBRIS operator delete(void*)+28 in libminecraftpe.so+0x28f514c [0xea48614c]
#901 HYBRIS (null)+-364333047 in libminecraftpe.so+0x28fa809 [0xea48b809]
#910 HYBRIS operator delete(void*)+28 in libminecraftpe.so+0x28f514c [0xea48614c]
#912 HYBRIS (null)+-363983018 in libminecraftpe.so+0x294ff56 [0xea4e0f56]
#913 HYBRIS (null)+-364327911 in libminecraftpe.so+0x28fbc19 [0xea48cc19]
#915 HYBRIS (null)+-364205161 in libminecraftpe.so+0x2919b97 [0xea4aab97]
#916 HYBRIS (null)+-353147236 in libminecraftpe.so+0x33a569c [0xeaf3669c]
#918 HYBRIS (null)+-353147236 in libminecraftpe.so+0x33a569c [0xeaf3669c]
#922 HYBRIS operator delete(void*)+28 in libminecraftpe.so+0x28f514c [0xea48614c]
#924 HYBRIS (null)+-353147236 in libminecraftpe.so+0x33a569c [0xeaf3669c]
#926 HYBRIS xbox::services::log_entry::~log_entry()+133 in libminecraftpe.so+0x234d5a5 [0xe9ede5a5]
#928 HYBRIS operator delete(void*)+6 in libminecraftpe.so+0x28f5136 [0xea486136]
#929 HYBRIS (null)+-353147236 in libminecraftpe.so+0x33a569c [0xeaf3669c]
#930 HYBRIS (null)+-363982996 in libminecraftpe.so+0x294ff6c [0xea4e0f6c]
#933 HYBRIS (null)+-364000679 in libminecraftpe.so+0x294ba59 [0xea4dca59]
#936 HYBRIS (null)+-353147236 in libminecraftpe.so+0x33a569c [0xeaf3669c]
#938 HYBRIS xbox::services::java_interop::finish_initialization(_JNIEnv*, _jobject*, _jmethodID*, bool)+926 in libminecraftpe.so+0x24cc52e [0xea05d52e]

Process exited with unexpected exit code: 6

**Comment by ChristopherHX** [comment]
_Please update the launcher, this issue was fixed a half year ago._
1.16.10 is the max version after all updates applied.

You can also download a preview with 1.16.40.
https://github.com/ChristopherHX/mcpelauncher-manifest/releases/tag/stable

**Comment by ChristopherHX** [comment]
@Dunuty Where do you find such an old version of my fork?
It should tell you if there is an update available

Your crash is with version
https://github.com/ChristopherHX/mcpelauncher-manifest/commit/830d61c3f32c2d3260f65284e2063c41e42966ad
Fixed 4 days after the version you have still installed
https://github.com/ChristopherHX/mcpelauncher-manifest/commit/b4136d74769a988e2c73b01e3cf6c9dda995d2c2
