### ISSUE TITLE
No Audio

### ISSUE THREAD

**Issue by JoshuaDoes** [minecraft-linux/mcpelauncher-manifest#42]
When using any other program, audio works 100% normally and I've never had any issues with it. In fact, in earlier versions of mcpelauncher-client, the audio worked just fine. But for the past week or so since switching over to the Ubuntu PPA (and ever since, regardless of source or pre-compiled), I've had no audio in the game and have not been able to resolve it. If this is a known issue and fixes are also known, it'd be much appreciated!

I can provide logs if needbe.

**Comment by MCMrARM** [comment]
https://github.com/minecraft-linux/mcpelauncher-manifest/wiki/Troubleshooting#no-audio
