### ISSUE TITLE
crashed, can be reproduced

### ISSUE THREAD

**Issue by nazthelizard122** [minecraft-linux/mcpelauncher-manifest#420]
[crash.docx](https://github.com/minecraft-linux/mcpelauncher-manifest/files/5481827/crash.docx)
file is too big to copy&paste

**Comment by ChristopherHX** [comment]
This version will be archived soon and replaced not worth fixing old code.
I know that it leaks memory so your error after playing longer must happen after some hours.

**Comment by nazthelizard122** [comment]
It takes at least 3 hours that time it took over 12 hours I'm pretty new to this stuff but I understand what it says when you say memory leakage does that mean that the memory the game takes up gets lower and lower until crash?

**Comment by ChristopherHX** [comment]
Yes the **free** memory for the game gets lower and lower until the system throws bad_alloc and kills the launcher.
_The old 32bit launcher cannot use more than 4GB of memory_

**Comment by nazthelizard122** [comment]
so rather than leak the memory explodes

**Comment by nazthelizard122** [comment]
Is there a temporary fix to stop Minecraft from crashing?

**Comment by ChristopherHX** [comment]
Install the preview of the new launcher
named ng, there is no fix for the old broken stable version.
ng shouldn't leak memory while using xboxlive, but has known memory corruption crashes, e.g. mutex lock failed => restart the launcher

How much ram do you have?
Reducing the renderdistance reduces memory usage.
My PC has 16GB and never got that error, but never ran the game as long as you did.

**Comment by nazthelizard122** [comment]
16 gb ddr3 I'll try that I'll let you know what happens

**Comment by ChristopherHX** [comment]
Download https://github.com/ChristopherHX/linux-packaging-scripts/releases/download/ng.appimage/Minecraft_Bedrock_Launcher-x86_64.0.0.592.AppImage
make it exectuable and run it

**Comment by nazthelizard122** [comment]
Ok thanks I'll get you know what happens! Also I haven't fully checked this, but going to the nether on a server crashes the game

**Comment by nazthelizard122** [comment]
Ok update: latest beta crashes due to incompatibility latest non-beta version is still running no issues I noticed in the beta there was 10 gb ram being used isn't anything intristing but may need to be fixed
