### ISSUE TITLE
Game crash with latest Ubuntu .deb and .AppImage launcher and MCPE 1.14.0.4

### ISSUE THREAD

**Issue by Rasmez** [minecraft-linux/mcpelauncher-manifest#425]
My system: Old i3-2350M laptop, 4 Gb of DDR3 RAM runing Lubuntu 20.04.4 LTS x64 updated at the time of writting.

Game Log

it seems that Minecraft has crashed

Minecraft has exited with a non-zero error code.

16:37:50 Info  [Launcher] Version: client c735370 / manifest e405b8c
16:37:50 Info  [Launcher] CPU: GenuineIntel        Intel(R) Core(TM) i3-2350M CPU @ 2.30GHz
16:37:50 Info  [Launcher] CPU supports SSSE3: YES
16:37:50 Trace [Launcher] Loading hybris libraries
16:37:50 Trace [HybrisUtils] Loaded OS library /usr/share/mcpelauncher/libs/native/libfmod.so.9.16
16:37:50 Trace [HybrisUtils] Loaded OS library libm.so.6
16:37:50 Trace [HybrisUtils] Loaded OS library libz.so.1
16:37:50 Trace [Launcher] Loading Minecraft library
16:37:51 Info  [Launcher] Loaded Minecraft library
16:37:51 Debug [Launcher] Minecraft is at offset 0xeb5d4000
16:37:51 Trace [Launcher] Initializing vtables
16:37:51 Error [MinecraftSymbols] Unresolved symbol: _ZN3App4initER10AppContext
16:37:51 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App4quitERKSsS1_
16:37:51 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App6updateEv
16:37:51 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App16setRenderingSizeEii
16:37:51 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App17setUISizeAndScaleEiif
16:37:51 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App10wantToQuitEv
16:37:51 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServiceLocatorI11AppPlatformE15mDefaultServiceE
16:37:51 Error [MinecraftSymbols] Unresolved symbol: _ZN11AppPlatform12showKeyboardERKSsibbbiRKN3glm5tvec2IfLNS2_9precisionE0EEE
16:37:51 Error [MinecraftSymbols] Unresolved symbol: _ZNK11AppPlatform22getHardwareInformationEv
16:37:51 Error [MinecraftSymbols] Unresolved symbol: _ZN17AppResourceLoaderC1ESt8functionIFN4Core10PathBufferISsEEvEE
16:37:51 Error [MinecraftSymbols] Unresolved symbol: _ZN10Automation16AutomationClientC2ER13IMinecraftApp
16:37:51 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance7getUserEv
16:37:51 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance15_startLeaveGameEv
16:37:51 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance16_syncDestroyGameEv
16:37:51 Error [MinecraftSymbols] Unresolved symbol: _ZNK13CommandOutput11getMessagesEv
16:37:51 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender9translateERKSt6vectorISsSaISsEE
16:37:51 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSenderC2ERN10Automation16AutomationClientE
16:37:51 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSenderD2Ev
16:37:51 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender4sendERK13CommandOriginRK13CommandOutput
16:37:51 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender22registerOutputCallbackERKSt8functionIFvR19AutomationCmdOutputEE
16:37:51 Error [MinecraftSymbols] Unresolved symbol: _ZN6Common23getGameVersionStringNetEv
16:37:51 Error [MinecraftSymbols] Unresolved symbol: _ZN30ExternalFileLevelStorageSourceC2EPN4Core15FilePathManagerESt10shared_ptrI22SaveTransactionManagerE
16:37:51 Error [MinecraftSymbols] Unresolved symbol: _ZN30ExternalFileLevelStorageSource18createLevelStorageER9SchedulerRKSsRK15ContentIdentityRK19IContentKeyProvider
16:37:51 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourceLoadManagerC2Ev
16:37:51 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourceLoadManager4syncE16ResourceLoadType
16:37:51 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n3getERKSsRKSt6vectorISsSaISsEE
16:37:51 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n14chooseLanguageERKSs
16:37:51 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n13loadLanguagesER19ResourcePackManagerR19ResourceLoadManagerRKSs
16:37:51 Error [MinecraftSymbols] Unresolved symbol: _ZN5Level16createRandomSeedEv
16:37:51 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettingsC2Ev
16:37:51 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettingsC2ERKS_
16:37:51 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettings15parseSeedStringERKSsj
16:37:51 Error [MinecraftSymbols] Unresolved symbol: _ZN9Minecraft11getCommandsEv
16:37:51 Error [MinecraftSymbols] Unresolved symbol: _ZNK9Minecraft8getLevelEv
16:37:51 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftCommands15setOutputSenderESt10unique_ptrI19CommandOutputSenderSt14default_deleteIS1_EE
16:37:51 Error [MinecraftSymbols] Unresolved symbol: _ZNK17MinecraftCommands23requestCommandExecutionESt10unique_ptrI13CommandOriginSt14default_deleteIS1_EERKSsib
16:37:51 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftEventingC2ERKSs
16:37:51 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftEventing4initEv
16:37:51 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGameC2EiPPc
16:37:51 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGameD2Ev
16:37:51 Error [MinecraftSymbols] Unresolved symbol: _ZNK13MinecraftGame8isInGameEv
16:37:51 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame16requestLeaveGameEbb
16:37:51 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame24doPrimaryClientReadyWorkESt8functionIFvvEE
16:37:51 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame21getPrimaryUserOptionsEv
16:37:51 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame24getPrimaryClientInstanceEv
16:37:51 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame14startLeaveGameEv
16:37:51 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame17continueLeaveGameEv
16:37:51 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame14setTextboxTextERKSsi
16:37:51 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel32navigateToXblConsoleSignInScreenERKSsS1_
16:37:51 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel41navigateToXblConsoleSignInSucceededScreenERKN6Social12SignInResultESt8functionIFvS1_EEb
16:37:51 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel11leaveScreenEv
16:37:51 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social14MultiplayerXBLC2Ev
16:37:51 Error [MinecraftSymbols] Unresolved symbol: _ZTV22NullTextToSpeechClient
16:37:51 Error [MinecraftSymbols] Unresolved symbol: _ZNK7Options13getFullscreenEv
16:37:51 Error [MinecraftSymbols] Unresolved symbol: _ZN7Options13setFullscreenEb
16:37:51 Error [MinecraftSymbols] Unresolved symbol: _ZN15PermissionsFileC2ERKSs
16:37:51 Error [MinecraftSymbols] Unresolved symbol: _ZN19SkinPackKeyProviderC2Ev
16:37:51 Error [MinecraftSymbols] Unresolved symbol: _ZN19PackManifestFactoryC2ER14IPackTelemetry
16:37:51 Error [MinecraftSymbols] Unresolved symbol: _ZN17PackSourceFactoryC2Ev
16:37:51 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepositoryC2ER18IMinecraftEventingR19PackManifestFactoryR29IContentAccessibilityProviderPN4Core15FilePathManagerER17PackSourceFactoryb
16:37:51 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepository21addWorldResourcePacksERKN4Core4PathE
16:37:51 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepository12refreshPacksEv
16:37:51 Error [MinecraftSymbols] Unresolved symbol: _ZN18ContentTierManagerC2Ev
16:37:51 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManagerC2ESt8functionIFN4Core10PathBufferISsEEvEERK18ContentTierManagerb
16:37:51 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManager8setStackESt10unique_ptrI17ResourcePackStackSt14default_deleteIS1_EE21ResourcePackStackTypeb
16:37:51 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManager17onLanguageChangedEv
16:37:51 Error [MinecraftSymbols] Unresolved symbol: _ZN12PackInstanceC2EP12ResourcePackibP12PackSettings
16:37:51 Error [MinecraftSymbols] Unresolved symbol: _ZTV17ResourcePackStack
16:37:51 Error [MinecraftSymbols] Unresolved symbol: _ZN17ResourcePackStack3addE12PackInstanceRK22ResourcePackRepositoryb
16:37:51 Error [MinecraftSymbols] Unresolved symbol: _ZN22SaveTransactionManagerC2ESt8functionIFvbEE
16:37:51 Error [MinecraftSymbols] Unresolved symbol: _ZN9Scheduler17processCoroutinesENSt6chrono8durationIxSt5ratioILx1ELx1000000000EEEE
16:37:51 Error [MinecraftSymbols] Unresolved symbol: _ZN18MinecraftScheduler6clientEv
16:37:51 Error [MinecraftSymbols] Unresolved symbol: _ZN19ServerCommandOriginC2ERKSsR11ServerLevel22CommandPermissionLevel
16:37:51 Error [MinecraftSymbols] Unresolved symbol: _ZN16EducationOptionsC2EP19ResourcePackManager
16:37:51 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstanceC2ER13IMinecraftAppR30ServerInstanceEventCoordinator
16:37:51 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance16initializeServerER13IMinecraftAppR9WhitelistP15PermissionsFilePN4Core15FilePathManagerENSt6chrono8durationIxSt5ratioILx1ELx1EEEESsSsSs13LevelSettingsib20ConnectionDefinitionbRKSt6vectorISsSaISsEESsRKN3mce4UUIDER18IMinecraftEventingR22ResourcePackRepositoryRK18ContentTierManagerR19ResourcePackManagerSt8functionIFSt10unique_ptrI12LevelStorageSt14default_deleteIS10_EER9SchedulerEERKSsP9LevelDataSsSsSZ_I16EducationOptionsS11_IS1C_EEPSW_SY_IFvvEES1H_P13ServerMetricsP13DebugEndPointb
16:37:51 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstanceD2Ev
16:37:51 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance17startServerThreadEv
16:37:51 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance13leaveGameSyncEv
16:37:51 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance20queueForServerThreadESt8functionIFvvEE
16:37:51 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12MajorVersionE
16:37:51 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12MinorVersionE
16:37:51 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12PatchVersionE
16:37:51 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants15RevisionVersionE
16:37:51 Error [MinecraftSymbols] Unresolved symbol: _ZNK6Social4User11getLiveUserEv
16:37:51 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social12XboxLiveUser22_handleUISignInNoErrorERN4xbox8services6system14sign_in_resultESt8functionIFvNS_12SignInResultEbEE
16:37:51 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN9GameStore18onStoreInitializedEb
16:37:51 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN9GameStore22onQueryProductsSuccessERKSt6vectorI11ProductInfoSaIS1_EE
16:37:51 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social11UserManager17CreateUserManagerEv
16:37:51 Error [MinecraftSymbols] Unresolved symbol: _ZN2v82V810InitializeEv
16:37:51 Error [MinecraftSymbols] Unresolved symbol: _ZN2v82V818InitializePlatformEPNS_8PlatformE
16:37:51 Error [MinecraftSymbols] Unresolved symbol: _ZNK4pplx4taskIN4xbox8services16xbox_live_resultINS2_6system26token_and_signature_resultEEEE3getEv
16:37:51 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl15getOpenGLVendorEv
16:37:51 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl17getOpenGLRendererEv
16:37:51 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl16getOpenGLVersionEv
16:37:51 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl19getOpenGLExtensionsEv
16:37:51 Error [MinecraftSymbols] Unresolved symbol: _ZN3mce8Platform3OGL12InitBindingsEv
terminate called after throwing an instance of 'std::runtime_error'
  what():  Found no way to resolve library version, Minecraft version likely unsupported
Signal 6 received
Backtrace elements: 15
#0 /usr/bin/mcpelauncher-client(_ZN12CrashHandler12handleSignalEiPv+0xc5) [0x568360a9]
#1 linux-gate.so.1(__kernel_sigreturn+0) [0xf7f24b60]
#2 linux-gate.so.1(__kernel_vsyscall+0x9) [0xf7f24b49]
#3 /lib/i386-linux-gnu/libc.so.6(gsignal+0xc6) [0xf77604c6]
#4 /lib/i386-linux-gnu/libc.so.6(abort+0x130) [0xf77483f7]
#5 /lib/i386-linux-gnu/libstdc++.so.6(+0x7db54) [0xf7ae0b54]
#6 /lib/i386-linux-gnu/libstdc++.so.6(+0x8bdc8) [0xf7aeedc8]
#7 /lib/i386-linux-gnu/libstdc++.so.6(+0x8be51) [0xf7aeee51]
#8 /lib/i386-linux-gnu/libstdc++.so.6(__cxa_rethrow+0) [0xf7aef190]
#9 /usr/bin/mcpelauncher-client(_Z21minecraft_get_versionPiS_S_S_+0x13a) [0x56888f44]
#10 /usr/bin/mcpelauncher-client(_ZN16MinecraftVersion4initEv+0x34) [0x568378a2]
#11 /usr/bin/mcpelauncher-client(_ZN14MinecraftUtils18initSymbolBindingsEPv+0x44) [0x5683779a]
#12 /usr/bin/mcpelauncher-client(main+0x10bc) [0x567df7e0]
#13 /lib/i386-linux-gnu/libc.so.6(__libc_start_main+0xf5) [0xf7749ee5]
#14 /usr/bin/mcpelauncher-client(_start+0x31) [0x567de241]
Dumping stack...
#4 HYBRIS (null)+-285843872 in libminecraftpe.so+0x3991e60 [0xeef65e60]
#13 HYBRIS (null)+-346210304 in libminecraftpe.so+0x0000 [0xeb5d4000]
#33 HYBRIS (null)+-225052200 in libminecraftpe.so+0x738b9d8 [0xf295f9d8]
#34 HYBRIS (null)+-285781552 in libminecraftpe.so+0x39a11d0 [0xeef751d0]
#35 HYBRIS (null)+-285788576 in libminecraftpe.so+0x399f660 [0xeef73660]
#38 HYBRIS (null)+-224668112 in libminecraftpe.so+0x73e9630 [0xf29bd630]
#39 HYBRIS (null)+-285774432 in libminecraftpe.so+0x39a2da0 [0xeef76da0]
#40 HYBRIS (null)+-285781456 in libminecraftpe.so+0x39a1230 [0xeef75230]
#75 HYBRIS (null)+-285731296 in libminecraftpe.so+0x39ad620 [0xeef81620]
#79 HYBRIS (null)+-285716688 in libminecraftpe.so+0x39b0f30 [0xeef84f30]
#108 HYBRIS (null)+-256198340 in libminecraftpe.so+0x55d793c [0xf0bab93c]
#109 HYBRIS (null)+-285692415 in libminecraftpe.so+0x39b6e01 [0xeef8ae01]
#111 HYBRIS (null)+-256198340 in libminecraftpe.so+0x55d793c [0xf0bab93c]
#113 HYBRIS (null)+-256198340 in libminecraftpe.so+0x55d793c [0xf0bab93c]
#114 HYBRIS (null)+-256198399 in libminecraftpe.so+0x55d7901 [0xf0bab901]
#116 HYBRIS (null)+-256198340 in libminecraftpe.so+0x55d793c [0xf0bab93c]
#117 HYBRIS (null)+-256198399 in libminecraftpe.so+0x55d7901 [0xf0bab901]
#119 HYBRIS (null)+-256198340 in libminecraftpe.so+0x55d793c [0xf0bab93c]
#120 HYBRIS (null)+-256198399 in libminecraftpe.so+0x55d7901 [0xf0bab901]
#122 HYBRIS (null)+-256198340 in libminecraftpe.so+0x55d793c [0xf0bab93c]
#123 HYBRIS (null)+-256198399 in libminecraftpe.so+0x55d7901 [0xf0bab901]
#125 HYBRIS (null)+-256198340 in libminecraftpe.so+0x55d793c [0xf0bab93c]
#126 HYBRIS (null)+-256198399 in libminecraftpe.so+0x55d7901 [0xf0bab901]
#128 HYBRIS (null)+-256198340 in libminecraftpe.so+0x55d793c [0xf0bab93c]
#129 HYBRIS (null)+-256198399 in libminecraftpe.so+0x55d7901 [0xf0bab901]
#131 HYBRIS (null)+-256198340 in libminecraftpe.so+0x55d793c [0xf0bab93c]
#132 HYBRIS (null)+-256198399 in libminecraftpe.so+0x55d7901 [0xf0bab901]
#134 HYBRIS (null)+-256198340 in libminecraftpe.so+0x55d793c [0xf0bab93c]
#135 HYBRIS (null)+-256198399 in libminecraftpe.so+0x55d7901 [0xf0bab901]
#137 HYBRIS (null)+-256198340 in libminecraftpe.so+0x55d793c [0xf0bab93c]
#138 HYBRIS (null)+-256198399 in libminecraftpe.so+0x55d7901 [0xf0bab901]
#140 HYBRIS (null)+-256198340 in libminecraftpe.so+0x55d793c [0xf0bab93c]
#141 HYBRIS (null)+-256198399 in libminecraftpe.so+0x55d7901 [0xf0bab901]
#143 HYBRIS (null)+-256198340 in libminecraftpe.so+0x55d793c [0xf0bab93c]
#144 HYBRIS (null)+-256198399 in libminecraftpe.so+0x55d7901 [0xf0bab901]
#146 HYBRIS (null)+-256198340 in libminecraftpe.so+0x55d793c [0xf0bab93c]
#147 HYBRIS (null)+-256198399 in libminecraftpe.so+0x55d7901 [0xf0bab901]
#149 HYBRIS (null)+-256198340 in libminecraftpe.so+0x55d793c [0xf0bab93c]
#150 HYBRIS (null)+-256198399 in libminecraftpe.so+0x55d7901 [0xf0bab901]
#152 HYBRIS (null)+-256198340 in libminecraftpe.so+0x55d793c [0xf0bab93c]
#153 HYBRIS (null)+-256198399 in libminecraftpe.so+0x55d7901 [0xf0bab901]
#155 HYBRIS (null)+-256198340 in libminecraftpe.so+0x55d793c [0xf0bab93c]
#156 HYBRIS (null)+-256198399 in libminecraftpe.so+0x55d7901 [0xf0bab901]
#158 HYBRIS (null)+-256198340 in libminecraftpe.so+0x55d793c [0xf0bab93c]
#159 HYBRIS (null)+-256198399 in libminecraftpe.so+0x55d7901 [0xf0bab901]
#161 HYBRIS (null)+-256198340 in libminecraftpe.so+0x55d793c [0xf0bab93c]
#162 HYBRIS (null)+-256198399 in libminecraftpe.so+0x55d7901 [0xf0bab901]
#164 HYBRIS (null)+-256198340 in libminecraftpe.so+0x55d793c [0xf0bab93c]
#165 HYBRIS (null)+-256198399 in libminecraftpe.so+0x55d7901 [0xf0bab901]
#167 HYBRIS (null)+-256198340 in libminecraftpe.so+0x55d793c [0xf0bab93c]
#168 HYBRIS (null)+-256198399 in libminecraftpe.so+0x55d7901 [0xf0bab901]
#170 HYBRIS (null)+-256198340 in libminecraftpe.so+0x55d793c [0xf0bab93c]
#171 HYBRIS (null)+-256198399 in libminecraftpe.so+0x55d7901 [0xf0bab901]
#173 HYBRIS (null)+-256198340 in libminecraftpe.so+0x55d793c [0xf0bab93c]
#174 HYBRIS (null)+-256198399 in libminecraftpe.so+0x55d7901 [0xf0bab901]
#176 HYBRIS (null)+-256198340 in libminecraftpe.so+0x55d793c [0xf0bab93c]
#177 HYBRIS (null)+-256198399 in libminecraftpe.so+0x55d7901 [0xf0bab901]
#179 HYBRIS (null)+-256198340 in libminecraftpe.so+0x55d793c [0xf0bab93c]
#180 HYBRIS (null)+-256198399 in libminecraftpe.so+0x55d7901 [0xf0bab901]
#182 HYBRIS (null)+-256198340 in libminecraftpe.so+0x55d793c [0xf0bab93c]
#183 HYBRIS (null)+-256198399 in libminecraftpe.so+0x55d7901 [0xf0bab901]
#185 HYBRIS (null)+-256198340 in libminecraftpe.so+0x55d793c [0xf0bab93c]
#186 HYBRIS (null)+-256198399 in libminecraftpe.so+0x55d7901 [0xf0bab901]
#188 HYBRIS (null)+-256198340 in libminecraftpe.so+0x55d793c [0xf0bab93c]
#189 HYBRIS (null)+-256198399 in libminecraftpe.so+0x55d7901 [0xf0bab901]
#191 HYBRIS (null)+-256198340 in libminecraftpe.so+0x55d793c [0xf0bab93c]
#192 HYBRIS (null)+-256198399 in libminecraftpe.so+0x55d7901 [0xf0bab901]
#194 HYBRIS (null)+-256198340 in libminecraftpe.so+0x55d793c [0xf0bab93c]
#195 HYBRIS (null)+-256198399 in libminecraftpe.so+0x55d7901 [0xf0bab901]
#197 HYBRIS (null)+-256198340 in libminecraftpe.so+0x55d793c [0xf0bab93c]
#198 HYBRIS (null)+-256198399 in libminecraftpe.so+0x55d7901 [0xf0bab901]
#200 HYBRIS (null)+-256198340 in libminecraftpe.so+0x55d793c [0xf0bab93c]
#201 HYBRIS (null)+-256198399 in libminecraftpe.so+0x55d7901 [0xf0bab901]
#206 HYBRIS (null)+-256198340 in libminecraftpe.so+0x55d793c [0xf0bab93c]
#207 HYBRIS (null)+-256198399 in libminecraftpe.so+0x55d7901 [0xf0bab901]
#209 HYBRIS (null)+-256198340 in libminecraftpe.so+0x55d793c [0xf0bab93c]
#212 HYBRIS (null)+-256198340 in libminecraftpe.so+0x55d793c [0xf0bab93c]
#213 HYBRIS (null)+-256198399 in libminecraftpe.so+0x55d7901 [0xf0bab901]
#743 HYBRIS (null)+-346210304 in libminecraftpe.so+0x0000 [0xeb5d4000]
Process exited with unexpected exit code: 6

Any suggestion in what to do? English is not my native language btw, feel free to correct me or something.

**Comment by nazthelizard122** [comment]
How was this made? What are the steps to reproduce it?

**Comment by ChristopherHX** [comment]
Please update the launcher, that old launcher is unsupported
https://github.com/ChristopherHX/linux-packaging-scripts/releases/tag/ng.appimage

**Pirating the game is bad very bad**, no one else would still play 1.14.0.4 today, instead of 1.16.40

**Comment by Rasmez** [comment]
Indeed, pirating the game it's very very bad. But the reason that I used 1.14.0.4 was because supposedly, was the latest version tested when and where I check (in the wrong site apparently).

I'm sorry for being too dumb to identify the latest version of the launcher in the spagetti mess that it is this... "project" and test an "unused" version, and being called a pirate for that, what a shame, really.

PS: I legally own almost the Java, Win10 and Bedrock versions of Minecraft, acquired either by buying directly from Mojang (Java) or recieved as a gift code (Win10 from Microsoft for owning Java previously and PE from my cousin in the last year's xmas). I keep an archive of that backups of all versions that I can download from the launchers for testing, simply for funzies and to study the evolution of the game, as aspiring developer is a major source of inspiration and education.
