### ISSUE TITLE
Throwing an egg while playing on a server crashes the game (1.8.0.24)

### ISSUE THREAD

**Issue by cloudrac3r** [minecraft-linux/mcpelauncher-manifest#43]
I'm playing on a server controlled by the server software from the same authors. 4 eggs in hand, I'm standing a couple blocks away from the egg's target, and there's a few chickens in a 1x1 hole directly below where the egg would impact. When the egg impacts, the game freezes for a second or two, then crashes.

Client: AMD Ryzen 5 1500X, Sapphire Nitro RX 570, 8 GB system RAM.

Game version: 1.8.0.24

Client error log: https://cadence.moe/pastes/94

There's no errors in the server console.

This happened twice in a row, so I assume it's a persistent issue. The second time I tried it, I did some other stuff first for a minute or two, which worked fine, so it's definitely something to do with the egg.

I haven't checked if this happens while playing a local world.

**Comment by Mhowser** [comment]
Are you using a resource pack?
Currently there is a bug where missing textures cause a client crash, and
the egg particles might be a cause of that as well.

**Comment by cloudrac3r** [comment]
No resource packs or behaviour packs are installed.

I've copied the server world to my local machine and opened it. It starts me as a new player rather than loading my old profile, so with commands I gave myself some eggs and then threw them. The game kept running.

Either it's something to do with server/client interaction, or it's to do with my specific character profile.

**Comment by MCMrARM** [comment]
Can't reproduce

**Comment by MCMrARM** [comment]
Well if I am to debug it I'll likely need to reproduce the issue first reliably.

I'd suggest the people affected by the issue to delete the game version in the metalauncher and redownload it, who knows, maybe the issue is in fact corrupted assets.
This might be just a random MC:PE bug though.

**Comment by Lantizia** [comment]
That rules me out - I've only ever used your launcher as of about an hour ago, so this is a new machine which has never used/downloaded any other version.

**Comment by Lantizia** [comment]
OK so I just tried this again with a completely new world - no problems.

So it must be (as suspected earlier by Mhowser) that it is related to resource packs.
The realm I was on when I reported the issue was started on a Nintendo Switch and is using the 'Natural Texture Pack' - as also seen here on the MS Store... https://www.microsoft.com/en-gb/p/minecraft-natural-texture-pack/bqrbkrhfn7zv?activetab=pivot:overviewtab

**Comment by MCMrARM** [comment]
Nice. So the texture pack issue.
Is there a non-store texture pack I can get this to crash with?

**Comment by cloudrac3r** [comment]
Reminder that I'm using the default resource packs. Also, there's no problem with displaying the broken egg particles, it's just the thrown egg that is the issue.

**Comment by DarkoGNU** [comment]
I also have this issue. It always happens to me after playing at least a couple of minutes, one time I throwed an egg just after joining a server and it worked just fine. Default texture pack. Two logs for you, although I don't think it's necessary (some people uploaded them):
https://cadence.moe/pastes/97
https://cadence.moe/pastes/98

**Comment by MCMrARM** [comment]
This is as far as I am aware a MCPE bug as I've heard of it happening on Windows 10 Edition from at least a single person.

**Comment by cloudrac3r** [comment]
Seems to be fixed in 1.10.0.7.
