### ISSUE TITLE
What bugs were fixed?

### ISSUE THREAD

**Issue by nazthelizard122** [minecraft-linux/mcpelauncher-manifest#438]
I noticed the launcher had an update I'm hopeful that the memleak is patched if not I'll write another issue I'm glad 1.16.200 works now but ill stick to 1.16.101 for now I just started afking if it crashes like I said I'd write another issue.

**Comment by ChristopherHX** [comment]
I fully discontinued my fork, ng is much different.
ng has two arm AppImages (lots of 0 changes for x86)

Theres is no known memleak in ng.
In ng has known instability, you have to deal with it.

**Comment by nazthelizard122** [comment]
Cool, is there a fix for the instability?

**Comment by ChristopherHX** [comment]
I cannot follow you weird logic.
**You can contribute a fix**, if there weren't known instability then you wouldn't notice it.

My own fix is using my win10 edition, I got it free from my ancient java premium account.
