### ISSUE TITLE
crash exit code 6

### ISSUE THREAD

**Issue by nazthelizard122** [minecraft-linux/mcpelauncher-manifest#439]
22:17:33 Info  [Launcher] Version: client 951c238 / manifest 640cfc8
22:17:33 Info  [Launcher] CPU: GenuineIntel Intel(R) Core(TM) i3-4130 CPU @ 3.40GHz
22:17:33 Info  [Launcher] CPU supports SSSE3: YES
22:17:33 Trace [Launcher] Loading hybris libraries
22:17:33 Trace [HybrisUtils] Loaded OS library libm.so.6
22:17:33 Trace [HybrisUtils] Loaded OS library libz.so.1
22:17:33 Trace [HybrisUtils] Loaded OS library /tmp/.mount_MC_068WPGtlO/usr/share/mcpelauncher/lib/native/x86_64/libfmod.so.12.0
22:17:33 Trace [Launcher] Loading Minecraft library
22:17:34 Info  [Launcher] Loaded Minecraft library
22:17:34 Debug [Launcher] Minecraft is at offset 0x0x7f352c440000
22:17:34 Info  [Launcher] Game version: 0.0.0.0
22:17:34 Info  [Launcher] Applying patches
22:17:34 Info  [Launcher] Initializing JNI
22:17:34 Error [JniSupport] Missing native symbol: Java_com_mojang_minecraftpe_MainActivity_nativeRegisterThis
22:17:34 Error [JniSupport] Missing native symbol: Java_com_mojang_minecraftpe_MainActivity_nativeUnregisterThis
22:17:34 Info  [Launcher] Executing main thread
22:17:34 Trace [JniSupport] Invoking nativeRegisterThis
22:17:34 Trace [JniSupport] Invoking ANativeActivity_onCreate
22:17:34 Warn  [Main] Android stub called
22:17:34 Warn  [Main] Android stub called
22:17:34 Warn  [Main] Android stub called
22:17:34 Warn  [Main] Android stub called
22:17:34 Info  [Launcher] Loading gamepad mappings
22:17:34 Trace [Launcher] Loading gamepad mappings: /tmp/.mount_MC_068WPGtlO/usr/share/mcpelauncher/gamecontrollerdb.txt
22:17:34 Info  [Launcher] Creating window
22:17:34 Info  [Minecraft] android_main starting. internalDataPath is '/internal', externalDataPath is '/external'
22:17:34 Trace [JniSupport] Invoking start activity callbacks
22:17:34 Info  [Minecraft] NO LOG FILE! - AppPlatform_android::setStorageDirectory - using External dir - CurrentFileStoragePath is now '/home/naz/.local/share/mcpelauncher/'
22:17:34 Warn  [Main] Android stub called
22:17:34 Warn  [Main] Android stub called
22:17:34 Warn  [Minecraft] NO LOG FILE! - [Device Lost] The graphics context was gained
22:17:34 Warn  [Minecraft] MinecraftGame::init && MinecraftGame::setSize!
22:17:35 Debug [HttpCallStaticGlue] Successfully registerered HttpCall methods
22:17:35 Debug [XboxLiveAppConfig] Successfully registerered XboxLiveAppConfig methods
22:17:35 Debug [XSAPI.Android] Successfully registerered HttpCall tcuiMethods
22:17:35 Debug [XSAPI.Android] Successfully registerered telemetryMethods
22:18:31 Info  [Minecraft] NO LOG FILE! - opening /home/naz/.local/share/mcpelauncher/minecraftpe/blob_cache
mcpelauncher-client: ../nptl/pthread_mutex_lock.c:149: __pthread_mutex_lock: Assertion `PTHREAD_MUTEX_TYPE (mutex) == PTHREAD_MUTEX_ERRORCHECK_NP' failed.
Signal 6 received
Backtrace elements: 9
#0 /tmp/.mount_MC_068WPGtlO/usr/bin/./mcpelauncher-client(_ZN12CrashHandler12handleSignalEiPv+0xfc) [0xb704bc]
#1 /lib/x86_64-linux-gnu/libpthread.so.0(+0x153c0) [0x7f355684e3c0]
#2 /lib/x86_64-linux-gnu/libc.so.6(gsignal+0xcb) [0x7f3555a6418b]
#3 /lib/x86_64-linux-gnu/libc.so.6(abort+0x12b) [0x7f3555a43859]
#4 /lib/x86_64-linux-gnu/libc.so.6(+0x25729) [0x7f3555a43729]
#5 /lib/x86_64-linux-gnu/libc.so.6(+0x36f36) [0x7f3555a54f36]
#6 /lib/x86_64-linux-gnu/libpthread.so.0(pthread_mutex_lock+0x255) [0x7f3556845215]
#7 /tmp/.mount_MC_068WPGtlO/usr/bin/./mcpelauncher-client(_ZN4shim18pthread_mutex_lockEPNS_6bionic15pthread_mutex_tE+0x1d) [0xbfc46d]
#8 HYBRIS std::__ndk1::mutex::lock()+0x6 in /home/naz/.local/share/mcpelauncher/versions/1.16.101.01/lib/x86_64/libc++_shared.so+0x0x995c6 [0x0x7f354d8195c6]
Dumping stack...
#53 HYBRIS operator delete(void*)+0x15 in /home/naz/.local/share/mcpelauncher/versions/1.16.101.01/lib/x86_64/libminecraftpe.so+0x0x931eee5 [0x0x7f353575eee5]
#55 HYBRIS pplx::task<unsigned char>::_ContinuationTaskHandle<unsigned char, void, pplx::details::_WhenAllImpl<void, pplx::task<void>*>::_Perform(pplx::task_options const&, pplx::task<void>*, pplx::task<void>*)::'lambda'(unsigned char), std::__ndk1::integral_constant<bool, false>, pplx::details::_TypeSelectorNoAsync>::_Continue(std::__ndk1::integral_constant<bool, false>, pplx::details::_TypeSelectorNoAsync) const+0xb2 in /home/naz/.local/share/mcpelauncher/versions/1.16.101.01/lib/x86_64/libminecraftpe.so+0x0x46097a2 [0x0x7f3530a497a2]
#58 HYBRIS vtable for std::__ndk1::__function::__func<pplx::details::_WhenAllImpl<void, pplx::task<void>*>::_Perform(pplx::task_options const&, pplx::task<void>*, pplx::task<void>*)::'lambda'(unsigned char), std::__ndk1::allocator<pplx::details::_WhenAllImpl<void, pplx::task<void>*>::_Perform(pplx::task_options const&, pplx::task<void>*, pplx::task<void>*)::'lambda'(unsigned char)>, void (unsigned char)>+0x10 in /home/naz/.local/share/mcpelauncher/versions/1.16.101.01/lib/x86_64/libminecraftpe.so+0x0xb38b3d0 [0x0x7f35377cb3d0]
#268 HYBRIS Concurrency::streams::details::streambuf_state_manager<unsigned char>::close(unsigned int)+0x631 in /home/naz/.local/share/mcpelauncher/versions/1.16.101.01/lib/x86_64/libminecraftpe.so+0x0x471cfe1 [0x0x7f3530b5cfe1]
#281 HYBRIS std::__ndk1::mutex::lock()+0x6 in /home/naz/.local/share/mcpelauncher/versions/1.16.101.01/lib/x86_64/libc++_shared.so+0x0x995c6 [0x0x7f354d8195c6]
#283 HYBRIS pplx::details::_Task_impl_base::_Wait()+0x8c in /home/naz/.local/share/mcpelauncher/versions/1.16.101.01/lib/x86_64/libminecraftpe.so+0x0x460f44c [0x0x7f3530a4f44c]
#293 HYBRIS (null)+0x7f3535798e1c in /home/naz/.local/share/mcpelauncher/versions/1.16.101.01/lib/x86_64/libminecraftpe.so+0x0x9358e1c [0x0x7f3535798e1c]
#317 HYBRIS web::http::inline_continuation::~inline_continuation()+0x5f in /home/naz/.local/share/mcpelauncher/versions/1.16.101.01/lib/x86_64/libminecraftpe.so+0x0x934cecf [0x0x7f353578cecf]
#339 HYBRIS web::http::details::http_msg_base::_complete(unsigned long, std::exception_ptr const&)+0x4b4 in /home/naz/.local/share/mcpelauncher/versions/1.16.101.01/lib/x86_64/libminecraftpe.so+0x0x934cb84 [0x0x7f353578cb84]
#342 HYBRIS vtable for std::__ndk1::basic_istringstream<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >+0x18 in /home/naz/.local/share/mcpelauncher/versions/1.16.101.01/lib/x86_64/libminecraftpe.so+0x0xb393c10 [0x0x7f35377d3c10]
#343 HYBRIS (null)+0x7f354d874ab0 in /home/naz/.local/share/mcpelauncher/versions/1.16.101.01/lib/x86_64/libc++_shared.so+0x0xf4ab0 [0x0x7f354d874ab0]
#345 HYBRIS (null)+0x7f354d874ab0 in /home/naz/.local/share/mcpelauncher/versions/1.16.101.01/lib/x86_64/libc++_shared.so+0x0xf4ab0 [0x0x7f354d874ab0]
#348 HYBRIS vtable for std::__ndk1::basic_streambuf<char, std::__ndk1::char_traits<char> >+0x10 in /home/naz/.local/share/mcpelauncher/versions/1.16.101.01/lib/x86_64/libminecraftpe.so+0x0xb38d250 [0x0x7f35377cd250]
#349 HYBRIS (null)+0x7f354d874ab0 in /home/naz/.local/share/mcpelauncher/versions/1.16.101.01/lib/x86_64/libc++_shared.so+0x0xf4ab0 [0x0x7f354d874ab0]
#358 HYBRIS (null)+0x7f3537c31fd8 in /home/naz/.local/share/mcpelauncher/versions/1.16.101.01/lib/x86_64/libminecraftpe.so+0x0xb7f1fd8 [0x0x7f3537c31fd8]
#364 HYBRIS (null)+0x7f3537c31fd8 in /home/naz/.local/share/mcpelauncher/versions/1.16.101.01/lib/x86_64/libminecraftpe.so+0x0xb7f1fd8 [0x0x7f3537c31fd8]
#383 HYBRIS web::http::client::details::request_context::complete_request(unsigned long)+0x2d in /home/naz/.local/share/mcpelauncher/versions/1.16.101.01/lib/x86_64/libminecraftpe.so+0x0x933eb0d [0x0x7f353577eb0d]
#387 HYBRIS web::http::client::details::asio_context::read_headers()+0xb8a in /home/naz/.local/share/mcpelauncher/versions/1.16.101.01/lib/x86_64/libminecraftpe.so+0x0x93a281a [0x0x7f35357e281a]
#389 HYBRIS (null)+0x7f354d874ab0 in /home/naz/.local/share/mcpelauncher/versions/1.16.101.01/lib/x86_64/libc++_shared.so+0x0xf4ab0 [0x0x7f354d874ab0]
#390 HYBRIS (null)+0x7f354d874ab0 in /home/naz/.local/share/mcpelauncher/versions/1.16.101.01/lib/x86_64/libc++_shared.so+0x0xf4ab0 [0x0x7f354d874ab0]
#391 HYBRIS (null)+0x7f354d874ab0 in /home/naz/.local/share/mcpelauncher/versions/1.16.101.01/lib/x86_64/libc++_shared.so+0x0xf4ab0 [0x0x7f354d874ab0]
#396 HYBRIS (null)+0x7f354d874ab0 in /home/naz/.local/share/mcpelauncher/versions/1.16.101.01/lib/x86_64/libc++_shared.so+0x0xf4ab0 [0x0x7f354d874ab0]
#413 HYBRIS std::__ndk1::ctype<char>::id+(nil) in /home/naz/.local/share/mcpelauncher/versions/1.16.101.01/lib/x86_64/libc++_shared.so+0x0xf3e98 [0x0x7f354d873e98]
#414 HYBRIS (null)+0x7f354d874ab0 in /home/naz/.local/share/mcpelauncher/versions/1.16.101.01/lib/x86_64/libc++_shared.so+0x0xf4ab0 [0x0x7f354d874ab0]
#416 HYBRIS vtable for std::__ndk1::basic_istream<char, std::__ndk1::char_traits<char> >+0x18 in /home/naz/.local/share/mcpelauncher/versions/1.16.101.01/lib/x86_64/libminecraftpe.so+0x0xb799600 [0x0x7f3537bd9600]
#418 HYBRIS vtable for std::__ndk1::basic_istream<char, std::__ndk1::char_traits<char> >+0x40 in /home/naz/.local/share/mcpelauncher/versions/1.16.101.01/lib/x86_64/libminecraftpe.so+0x0xb799628 [0x0x7f3537bd9628]
#424 HYBRIS (null)+0x7f354d874ab0 in /home/naz/.local/share/mcpelauncher/versions/1.16.101.01/lib/x86_64/libc++_shared.so+0x0xf4ab0 [0x0x7f354d874ab0]
#443 HYBRIS web::http::client::details::asio_context::handle_status_line(boost::system::error_code const&)+0x5c9 in /home/naz/.local/share/mcpelauncher/versions/1.16.101.01/lib/x86_64/libminecraftpe.so+0x0x939edb9 [0x0x7f35357dedb9]
#455 HYBRIS (null)+0x7f354d874ab0 in /home/naz/.local/share/mcpelauncher/versions/1.16.101.01/lib/x86_64/libc++_shared.so+0x0xf4ab0 [0x0x7f354d874ab0]
#456 HYBRIS vtable for std::__ndk1::basic_istream<char, std::__ndk1::char_traits<char> >+0x18 in /home/naz/.local/share/mcpelauncher/versions/1.16.101.01/lib/x86_64/libminecraftpe.so+0x0xb799600 [0x0x7f3537bd9600]
#458 HYBRIS vtable for std::__ndk1::basic_istream<char, std::__ndk1::char_traits<char> >+0x40 in /home/naz/.local/share/mcpelauncher/versions/1.16.101.01/lib/x86_64/libminecraftpe.so+0x0xb799628 [0x0x7f3537bd9628]
#464 HYBRIS (null)+0x7f354d874ab0 in /home/naz/.local/share/mcpelauncher/versions/1.16.101.01/lib/x86_64/libc++_shared.so+0x0xf4ab0 [0x0x7f354d874ab0]
#477 HYBRIS (null)+0x11 in /home/naz/.local/share/mcpelauncher/versions/1.16.101.01/lib/x86_64/libminecraftpe.so+0x0x9513601 [0x0x7f3535953601]
#483 HYBRIS boost::asio::detail::read_until_delim_string_op<boost::asio::ssl::stream<boost::asio::basic_stream_socket<boost::asio::ip::tcp>&>, boost::asio::basic_streambuf_ref<std::__ndk1::allocator<char> >, boost::_bi::bind_t<void, boost::_mfi::mf1<void, web::http::client::details::asio_context, boost::system::error_code const&>, boost::_bi::list2<boost::_bi::value<std::__ndk1::shared_ptr<web::http::client::details::asio_context> >, boost::arg<1> (*)()> > >::operator()(boost::system::error_code const&, unsigned long, int)+0x431 in /home/naz/.local/share/mcpelauncher/versions/1.16.101.01/lib/x86_64/libminecraftpe.so+0x0x939f701 [0x0x7f35357df701]
#487 HYBRIS boost::system::detail::cat_holder<void>::system_category_instance+(nil) in /home/naz/.local/share/mcpelauncher/versions/1.16.101.01/lib/x86_64/libminecraftpe.so+0x0xb38a528 [0x0x7f35377ca528]
#501 HYBRIS boost::asio::ssl::detail::io_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp>, boost::asio::ssl::detail::read_op<boost::asio::mutable_buffers_1>, boost::asio::detail::read_until_delim_string_op<boost::asio::ssl::stream<boost::asio::basic_stream_socket<boost::asio::ip::tcp>&>, boost::asio::basic_streambuf_ref<std::__ndk1::allocator<char> >, boost::_bi::bind_t<void, boost::_mfi::mf1<void, web::http::client::details::asio_context, boost::system::error_code const&>, boost::_bi::list2<boost::_bi::value<std::__ndk1::shared_ptr<web::http::client::details::asio_context> >, boost::arg<1> (*)()> > > >::operator()(boost::system::error_code, unsigned long, int)+0x3cd in /home/naz/.local/share/mcpelauncher/versions/1.16.101.01/lib/x86_64/libminecraftpe.so+0x0x939fcfd [0x0x7f35357dfcfd]
#505 HYBRIS boost::system::detail::cat_holder<void>::system_category_instance+(nil) in /home/naz/.local/share/mcpelauncher/versions/1.16.101.01/lib/x86_64/libminecraftpe.so+0x0xb38a528 [0x0x7f35377ca528]
#513 HYBRIS boost::asio::detail::reactive_socket_recv_op<boost::asio::mutable_buffers_1, boost::asio::ssl::detail::io_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp>, boost::asio::ssl::detail::read_op<boost::asio::mutable_buffers_1>, boost::asio::detail::read_until_delim_string_op<boost::asio::ssl::stream<boost::asio::basic_stream_socket<boost::asio::ip::tcp>&>, boost::asio::basic_streambuf_ref<std::__ndk1::allocator<char> >, boost::_bi::bind_t<void, boost::_mfi::mf1<void, web::http::client::details::asio_context, boost::system::error_code const&>, boost::_bi::list2<boost::_bi::value<std::__ndk1::shared_ptr<web::http::client::details::asio_context> >, boost::arg<1> (*)()> > > > >::do_complete(void*, boost::asio::detail::scheduler_operation*, boost::system::error_code const&, unsigned long)+0x122 in /home/naz/.local/share/mcpelauncher/versions/1.16.101.01/lib/x86_64/libminecraftpe.so+0x0x93a0132 [0x0x7f35357e0132]
#524 HYBRIS boost::system::detail::cat_holder<void>::system_category_instance+(nil) in /home/naz/.local/share/mcpelauncher/versions/1.16.101.01/lib/x86_64/libminecraftpe.so+0x0xb38a528 [0x0x7f35377ca528]
#533 HYBRIS web::http::client::details::asio_context::handle_status_line(boost::system::error_code const&)+(nil) in /home/naz/.local/share/mcpelauncher/versions/1.16.101.01/lib/x86_64/libminecraftpe.so+0x0x939e7f0 [0x0x7f35357de7f0]
#538 HYBRIS boost::system::detail::cat_holder<void>::system_category_instance+(nil) in /home/naz/.local/share/mcpelauncher/versions/1.16.101.01/lib/x86_64/libminecraftpe.so+0x0xb38a528 [0x0x7f35377ca528]
#543 HYBRIS boost::asio::detail::scheduler::do_run_one(boost::asio::detail::conditionally_enabled_mutex::scoped_lock&, boost::asio::detail::scheduler_thread_info&, boost::system::error_code const&)+0x34e in /home/naz/.local/share/mcpelauncher/versions/1.16.101.01/lib/x86_64/libminecraftpe.so+0x0x9387e4e [0x0x7f35357c7e4e]
#557 HYBRIS boost::asio::detail::scheduler::run(boost::system::error_code&)+0xd1 in /home/naz/.local/share/mcpelauncher/versions/1.16.101.01/lib/x86_64/libminecraftpe.so+0x0x93878e1 [0x0x7f35357c78e1]
#569 HYBRIS (null)+0x7f3537fd4cd0 in /home/naz/.local/share/mcpelauncher/versions/1.16.101.01/lib/x86_64/libminecraftpe.so+0x0xbb94cd0 [0x0x7f3537fd4cd0]
#575 HYBRIS crossplat::threadpool::thread_start(void*)+0x4a in /home/naz/.local/share/mcpelauncher/versions/1.16.101.01/lib/x86_64/libminecraftpe.so+0x0x93b766a [0x0x7f35357f766a]
#577 HYBRIS boost::system::detail::cat_holder<void>::system_category_instance+(nil) in /home/naz/.local/share/mcpelauncher/versions/1.16.101.01/lib/x86_64/libminecraftpe.so+0x0xb38a528 [0x0x7f35377ca528]
#589 HYBRIS crossplat::threadpool::detach_from_java(void*)+(nil) in /home/naz/.local/share/mcpelauncher/versions/1.16.101.01/lib/x86_64/libminecraftpe.so+0x0x93b7760 [0x0x7f35357f7760]

Process exited with unexpected exit code: 6

**Comment by ChristopherHX** [comment]
*"Random crash**, can you tell my why this happens and what to do against it?
It doesn't happen all the time, mostly during start or while inside setting.

Ng has known instability, you have to deal with it.

**Comment by nazthelizard122** [comment]
Ok, I was wondering if there was a way to make a sound when I crash or even better an automated script that relaunches Minecraft and puts me back where I was
