### ISSUE TITLE
Pre-menu crash

### ISSUE THREAD

**Issue by xEzeit** [minecraft-linux/mcpelauncher-manifest#46]
log error:

19:04:09 Info  [Launcher] Version: client bff35c5 / manifest f662578
19:04:09 Info  [Launcher] CPU: GenuineIntel Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
19:04:09 Info  [Launcher] CPU supports SSSE3: YES
19:04:09 Trace [Launcher] Loading hybris libraries
19:04:09 Trace [HybrisUtils] Loaded OS library /Applications/Minecraft Bedrock Launcher.app/Contents/Resources/mcpelauncher/libs/native/libfmod.dylib
19:04:09 Trace [HybrisUtils] Loaded OS library libm.dylib
19:04:09 Trace [Launcher] Loading Minecraft library
19:04:10 Info  [Launcher] Loaded Minecraft library
19:04:10 Debug [Launcher] Minecraft is at offset 0x2d46000
19:04:10 Error [MinecraftSymbols] Unresolved symbol: _ZN15ResourceLoaders14registerLoaderE18ResourceFileSystemSt10unique_ptrI14ResourceLoaderSt14default_deleteIS2_EE
19:04:10 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN4xbox8services12local_config28get_value_from_local_storageERKSsS3_S3_
19:04:10 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN4xbox8services12local_config28write_value_to_local_storageERKSsS3_S3_S3_
19:04:10 Error [MinecraftSymbols] Unresolved symbol: _ZN4xbox8services6system12auth_manager23initialize_default_nsalEN4pplx18cancellation_tokenE
19:04:10 Error [MinecraftSymbols] Unresolved symbol: _ZN4xbox8services6system12auth_manager21initialize_title_nsalERKSsN4pplx18cancellation_tokenE
19:04:10 Error [MinecraftSymbols] Unresolved symbol: _ZN4xbox8services6system12auth_manager32internal_get_token_and_signatureESsRKSsS4_SsRKSt6vectorIhSaIhEEbbS4_N4pplx18cancellation_tokenE
19:04:10 Error [MinecraftSymbols] Unresolved symbol: _ZN16EducationOptionsC2EP19ResourcePackManager
19:04:10 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstanceC2ER13IMinecraftAppR30ServerInstanceEventCoordinator
19:04:10 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance16initializeServerER13IMinecraftAppR9WhitelistP15PermissionsFileP15FilePathManagerNSt6chrono8durationIxSt5ratioILx1ELx1EEEESsSsSs13LevelSettingsibiiibRKSt6vectorISsSaISsEESsRKN3mce4UUIDER18IMinecraftEventingR22ResourcePackRepositoryRK18ContentTierManagerR19ResourcePackManagerSt8functionIFSt10unique_ptrI12LevelStorageSt14default_deleteISY_EER9SchedulerEERKSsP9LevelDataSsSsSX_I16EducationOptionsSZ_IS1A_EEPSU_SW_IFvS17_EES1F_
19:04:10 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance17startServerThreadEv
19:04:10 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance13leaveGameSyncEv
19:04:10 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance20queueForServerThreadESt8functionIFvvEE
19:04:10 Error [MinecraftSymbols] Unresolved symbol: _ZN2v82V810InitializeEv
19:04:10 Error [MinecraftSymbols] Unresolved symbol: _ZN2v82V818InitializePlatformEPNS_8PlatformE
19:04:10 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourceLoadManagerC2Ev
19:04:10 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n13loadLanguagesER19ResourcePackManagerR19ResourceLoadManagerRKSs
19:04:10 Error [MinecraftSymbols] Unresolved symbol: _ZN12PackInstanceC2EP12ResourcePackibP12PackSettings
19:04:10 Error [MinecraftSymbols] Unresolved symbol: _ZNK13MinecraftGame8isInGameEv
19:04:10 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame24doPrimaryClientReadyWorkESt8functionIFvvEE
19:04:10 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame17continueLeaveGameEv
19:04:10 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame14setTextboxTextERKSsi
19:04:10 Error [MinecraftSymbols] Unresolved symbol: _ZN18MinecraftScheduler6clientEv
19:04:10 Error [MinecraftSymbols] Unresolved symbol: _ZTV22NullTextToSpeechClient
19:04:10 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App4quitERKSsS1_
19:04:10 Error [MinecraftSymbols] Unresolved symbol: _ZN15PermissionsFileC2ERKSs
19:04:10 Error [MinecraftSymbols] Unresolved symbol: _ZN11AppPlatform12showKeyboardERKSsibbbiRK4Vec2
19:04:10 Error [MinecraftSymbols] Unresolved symbol: _ZN22SaveTransactionManagerC2ESt8functionIFvbEE
19:04:10 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social12XboxLiveUser22_handleUISignInNoErrorERN4xbox8services6system14sign_in_resultESt8functionIFvNS_12SignInResultEbEE
19:04:10 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepositoryC2ER18IMinecraftEventingR19PackManifestFactoryR29IContentAccessibilityProviderP15FilePathManagerR17PackSourceFactoryb
19:04:10 Error [MinecraftSymbols] Unresolved symbol: _ZN30ExternalFileLevelStorageSourceC2EP15FilePathManagerSt10shared_ptrI22SaveTransactionManagerE
19:04:10 Error [MinecraftSymbols] Unresolved symbol: _ZN30ExternalFileLevelStorageSource18createLevelStorageER9SchedulerRKSsRK15ContentIdentityRK19IContentKeyProvider
19:04:10 Error [MinecraftSymbols] Unresolved symbol: _ZN15ContentIdentity5EMPTYE
19:04:10 Info  [Launcher] Game version: 1.2.5
19:04:10 Info  [Launcher] Applying patches
19:04:10 Trace [Store] Vtable size = 30
19:04:10 Trace [Patch] Patching - original: 85 83 87 86 131
19:04:10 Trace [Patch] Patching - result: 233 11 219 86 252
19:04:10 Trace [Patch] Patching - original: 85 83 87 86 129
19:04:10 Trace [Patch] Patching - result: 233 11 230 139 250
19:04:10 Trace [Patch] Patching - original: 85 83 87 86 129
19:04:10 Trace [Patch] Patching - result: 233 171 197 196 250
19:04:10 Trace [Patch] Patching - original: 85 83 87 86 129
19:04:10 Trace [Patch] Patching - result: 233 251 218 196 250
19:04:10 Trace [Patch] Patching - original: 85 83 87 86 129
19:04:10 Trace [Patch] Patching - result: 233 235 205 196 250
19:04:10 Trace [Patch] Patching - original: 85 83 87 86 129
19:04:10 Trace [Patch] Patching - result: 233 43 70 196 250
19:04:10 Trace [Patch] Patching - original: 85 83 87 86 129
19:04:10 Trace [Patch] Patching - result: 233 107 69 196 250
19:04:10 Trace [Patch] Patching - original: 85 83 87 86 129
19:04:10 Trace [Patch] Patching - result: 233 155 46 198 250
19:04:10 Trace [Patch] Patching - original: 83 87 86 131 236
19:04:10 Trace [Patch] Patching - result: 233 59 209 196 250
19:04:10 Trace [Patch] Patching - original: 85 83 87 86 129
19:04:10 Trace [Patch] Patching - result: 233 27 239 196 250
19:04:10 Trace [Patch] Patching - original: 49 192 195 141 182
19:04:10 Trace [Patch] Patching - result: 233 75 219 80 252
19:04:10 Trace [Patch] Patching - original: 83 131 236 24 232
19:04:10 Trace [Patch] Patching - result: 233 235 49 228 250
19:04:10 Trace [Patch] Patching - original: 137 84 36 4 137
19:04:10 Trace [Patch] Patching - result: 232 101 240 158 250
19:04:10 Trace [Patch] Patching - original: 70 12 131 248 2
19:04:10 Trace [Patch] Patching - result: 232 113 240 158 250
19:04:10 Trace [Patch] Patching - original: 85 83 87 86 131
19:04:10 Trace [Patch] Patching - result: 233 59 135 91 252
19:04:10 Trace [Patch] Patching - original: 85 83 87 86 129
19:04:10 Trace [Patch] Patching - result: 233 27 132 91 252
19:04:10 Trace [Patch] Patching - original: 83 87 86 131 236
19:04:10 Trace [Patch] Patching - result: 233 219 132 91 252
19:04:10 Error [SplitscreenPatch] Not patching splitscreen - incompatible code
Signal 11 received
Backtrace elements: 5
#0 0   mcpelauncher-client                 0x00116f3e _ZN12CrashHandler12handleSignalEiPv + 318
#1 1   libsystem_platform.dylib            0xa758a02b _sigtramp + 43
#2 2   ???                                 0xffffffff 0x0 + 4294967295
#3 3   mcpelauncher-client                 0x0007c823 main + 10787
#4 4   libdyld.dylib                       0xa7281611 start + 1
Dumping stack...
#13 HYBRIS (null)+57128532 in libminecraftpe.so+0x935654 [0x367b654]
#74 HYBRIS (null)+93895913 in libminecraftpe.so+0x2c45ce9 [0x598bce9]
#358 HYBRIS (null)+47472640 in libminecraftpe.so+0x0000 [0x2d46000]
Process exited with unexpected exit code: 6

**Comment by MCMrARM** [comment]
I'm closing the issue as it applied to a really old release.
