### ISSUE TITLE
Add Ability to Install Mods

### ISSUE THREAD

**Issue by GabeCoder** [minecraft-linux/mcpelauncher-manifest#460]
Mods are really fun to use in Minecraft, regardless of the version. Without the ability to add mods, the experience of Minecraft gets a lot more boring. Important add-ons are also really helpful for those gamers because how will you backup your world if you can’t add a world export add-on?

Also, can you add the ability to import worlds? It gets really frustrating when it is completely impossible to do so.

**Comment by nazthelizard122** [comment]
It's not impossible you just need to know where to put the world file

**Comment by ReallyFunnyGuyGabe** [comment]
> It's not impossible you just need to know where to put the world file

Okay, but what about add-ons/mods?
Can’t you add the ability to add texture packs?

**Comment by nazthelizard122** [comment]
Same thing
