### ISSUE TITLE
Resource and Behavior Packs

### ISSUE THREAD

**Issue by GabeCoder** [minecraft-linux/mcpelauncher-manifest#463]
I know that you can open the Minecraft folder or whatever it's called, but where exactly do you put resource and behavior packs? I need to add a world export addon.

**Comment by ChristopherHX** [comment]
Why don't you read the faq page first?
https://mcpelauncher.readthedocs.io/en/latest/faq.html

The World export button is an exclusive feature of the win10 edition, more than an addon could change.

Althought the World export button was available via an included gamehack in a [previous version of this Launcher with Minecaft 0.12-1.13.0.9, 1.13.0.34, 1.14.1.5](https://github.com/minecraft-linux/mcpelauncher-manifest/tree/b3dd620f9cc1de747be5f4d39a43d7882a9741d0)

**Comment by GabeCoder** [comment]
> Why don't you read the faq page first?
> https://mcpelauncher.readthedocs.io/en/latest/faq.html
> 
> The World export button is an exclusive feature of the win10 edition, more than an addon could change.
> 
> Althought the World export button was available via an included gamehack in a [previous version of this Launcher with Minecaft 0.12-1.13.0.9, 1.13.0.34, 1.14.1.5](https://github.com/minecraft-linux/mcpelauncher-manifest/tree/b3dd620f9cc1de747be5f4d39a43d7882a9741d0)

Silly me, I just found out the solution.

**Comment by EmeraldSans** [comment]
My behavior packs don't load up in the launcher after correctly inserting the .mcaddon in the behavior pack folder.
