### ISSUE TITLE
Frame Rate Drops in Fullscreen

### ISSUE THREAD

**Issue by GabeCoder** [minecraft-linux/mcpelauncher-manifest#465]
Whenever I enter full screen mode in Minecraft, the frame rate drops significantly. Before, it was 60fps, then it drops to 30fps. I changed some settings in options.txt to increase the frame rate (turning off vsync, setting full screen value), and it worked, at least without full screen. The frame rate changed to 120fps, which got me hyped, but it still purposely drops to 30fps whenever I enter full screen mode.
Are there specific settings for how many FPS there can be for full screen mode? If so, which settings?
Is there a method to patch this?

**Comment by GabeCoder** [comment]
@ChristopherHX Update: Just want to make sure this issue is noticeable.

**Comment by ChristopherHX** [comment]
Please stop to mention me, no one else does this. You have no special entitlements.

**Comment by GabeCoder** [comment]
> Please stop to mention me, no one else does this. You have no special entitlements.

Okay, just hoping that there is a way to fix this problem.

**Comment by GabeCoder** [comment]
Still though, how can I fix this?

**Comment by Dreamedc2015** [comment]
> Still though, how can I fix this?

you could just run it windowed
or just wait till fixed 
lower your game settings if you `need` to be in full screen

**Comment by GabeCoder** [comment]
> > Still though, how can I fix this?
> 
> you could just run it windowed
> or just wait till fixed
> lower your game settings if you `need` to be in full screen

Okay, I lowered the settings. For now, I’ll play the game full screen and wait for the fix. Anyway, thanks for the tips.

**Comment by GabeCoder** [comment]
I also realized that in the update log that this is mentioned in the known errors section.

**Comment by GabeCoder** [comment]
I also realized that the problem has been mentioned in the update log, so I’ll wait for the bug fix. I’m sure you’ll be able to patch it. You got this!

**Comment by GabeCoder** [comment]
Oh, and when do you expect this bug to be patched?

**Comment by GabeCoder** [comment]
I also realized that this was mentioned in the known problems section.
I just understood that.
