### ISSUE TITLE
License error using .apk file..

### ISSUE THREAD

**Issue by Haus3master** [minecraft-linux/mcpelauncher-manifest#466]
Hello, I have been trying to install and play minecraft pe 1.16.200.02 which is fully supported and is playable on ng appimage .617 to be exact and anything above that results in a license error, that's why, I tired installing the flatpak version but this issue is persistent, here are a few images regarding this, the launcher is the flatpak version...![IMG_2021-02-28-00-01-55-131.jpg](https://user-images.githubusercontent.com/66825701/109397557-40bd4f80-795d-11eb-89ce-3964b73155f9.jpg)
And then, the second screenshot is the result of launching with the flatpak launcher and any appimage launcher above the .617 version...
![IMG_2021-02-28-00-02-44-334.jpg](https://user-images.githubusercontent.com/66825701/109397570-4fa40200-795d-11eb-973f-04814d7b8fb6.jpg)
PS: I'm ready to provide further logs and info and will be more than happy to test anything you ask me to...
My PC is the raspberry Pi 3B+ running raspberry Pi OS 32bit...
I already created an issue regarding this in the issue page of the flatpak launcher, but just wanted to bring this to your attention, and, I sincerely apologise if I have caused any amount of annoyance by posting the same issue in 2 different repositories...

**Comment by Haus3master** [comment]
This has been already answered in the o other repository, thanks again!

**Comment by JCluzet** [comment]
what have you done ?
