### ISSUE TITLE
Sign-In Website not loading

### ISSUE THREAD

**Issue by IfgiU** [minecraft-linux/mcpelauncher-manifest#477]
Hi!
First of all, really great job for getting this running!
I'm kinda of a noob just trying out Linux, so I'm sorry if I'm a Idiot.
So, whenever I try to Log-In, I can type in my E-Mail Address and my Password, but the Page where it says youre GamerTag and "Let's go!" doesn't really load except for the Button, but it's unklickable.

Bye!
-IfgiU

**Comment by ChristopherHX** [comment]
Known issue of the Linux AppImage, and macOS DMG for 10.10/11
Please look here for a workaround https://github.com/ChristopherHX/mcpelauncher-manifest/issues/232#issuecomment-803624424

I will lock this issue to avoid discussions about this in multiple issues, feel free to ask in the referenced issue if you have any questions about my workaround.

**Comment by ChristopherHX** [comment]
Introduced and fixed by microsoft. Checked Today.
