### ISSUE TITLE
macOS: Process exited with unexpected exit code: 9

### ISSUE THREAD

**Issue by yangm97** [minecraft-linux/mcpelauncher-manifest#48]
When running in [64bit-only mode](http://osxdaily.com/2018/04/04/run-64-bit-mode-mac-os/), the game won't launch.

**Comment by yangm97** [comment]
Are there any plans to add a wrapper or something? Seems like the next version of macOS is going to drop native 32bit support.

**Comment by yangm97** [comment]
No problem, just passing by the apps I use to remind of the imminent _32bit doomsday_. It looks like a bunch of people are trying to make a wrapper though, I guess it wouldn't need a kext, seems like either DOSbox or wine have been running 32bit binaries foreign binaries as 64bit process.

So infuriating that Mojang still does not release native macOS binaries or even 64bit android ones though.

Anyway great work on this project!

**Comment by MCMrARM** [comment]
Yeah, I'd appreciate a 64-bit official builds for many reasons, particularly so we could use >4GB of RAM, and building it on Linux would be less of a pain.

I have no idea about what would it require - it all depends how far will Apple go in disabling it, and about how Darwin handles 32-bit apps. I'd have to investigate it, but this is not worth spending the time on now, as it would take a lot of time to do it and probably would introduce a lot of new issues.
