### ISSUE TITLE
Couple Bugs

### ISSUE THREAD

**Issue by GabeCoder** [minecraft-linux/mcpelauncher-manifest#480]
Although you are currently working on 1.16.210 as a beta release, I just want to point out a few bugs in the game.

1. Skins
Whenever I exit the game and launch it again, the skin I assign to my profile disappears, so I need to reselect it. This doesn't seem like a large error, however, as it isn't like crashing the game.
2. Marketplace
The only reason I go to the Marketplace is to download the Minecraft Original Music Pack so I can get the true Minecraft experience. However, I can't connect to the Marketplace, so I can't search up my favorite Marketplace pack.
NOTE: I use the ARMEABI-V7A version instead of Google Play's version since it is more stable and crashes less often. This paragraph may solve other players' problems that involve the instability of the launcher.

I'm only pointing these out for you to know in the future.

**Comment by GabeCoder** [comment]
8 hours and this issue hasn’t been noticed yet.
Yep, still waiting for the Marketplace and skin issue to be resolved.

**Comment by GabeCoder** [comment]
It seems that my issue is being ignored by people. This is a serious issue that needs to be addressed.
Every time I reopen the game, all the skins get deleted, and then I can’t open the Marketplace.
Somebody needs to respond to this issue.

**Comment by GabeCoder** [comment]
Please respond to this issue already, as it has been ignored by everyone but me.
I’m getting tired of having to get people aware of this.

**Comment by nazthelizard122** [comment]
Wait, Christopher is doing other things please be patient

**Comment by GabeCoder** [comment]
> Wait, Christopher is doing other things please be patient

Finally someone is aware of this issue.

**Comment by nazthelizard122** [comment]
Cool

**Comment by GabeCoder** [comment]
Yeah, the skin problem doesn’t really seem much.
