### ISSUE TITLE
Textures offset by 1 

### ISSUE THREAD

**Issue by guppy42** [minecraft-linux/mcpelauncher-manifest#485]
All 3d representations of items - placed or carried seem to have their texture shifted over by 1 "pixel" i both directions

This causes the border to get shifted to the opposite side and held items looks broken, items that are not full blocks gets holes in them ( see torch in the attached image )

![Broken textures example](https://user-images.githubusercontent.com/6497829/113547782-cf715c00-95ee-11eb-8f41-c0ef32001380.png)

There are no resources enabled neither globally nor in the world.

Launcher version: Minecraft_Bedrock_Launcher-x86_64-0.0.648.AppImage
Game version: 1.16.210.05 ( "latest from google play" )
Graphics card: GTX 970 ( Driver 450.102.04 )
Distro: Linux Mint 20.1 Ulyssa 
Kernel: Linux guppybox 5.4.0-70-generic #78-Ubuntu SMP Fri Mar 19 13:29:52 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

It does not appear to be resolution dependent, I've tried (windowed) 720p, 1080p, (fullscreen) 4k

There appears to be no other bug reports on this issue, which is strange as it's highly anoying.

I've also tested it on a Ubuntu Cinnamon 20.04 LTS with a GTX 1060 it displays the same behaviour

**Comment by sonic2kk** [comment]
It is a known issue introduced with the Android x86 builds of Pocket Edition. I suggest voting for the Jira issue: https://bugs.mojang.com/browse/MCPE-121068

**Comment by ChristopherHX** [comment]
No longer happen in this launcher, I invested more than 12 hours to find a way to hide this bug. (update to v0.2.1)
