### ISSUE TITLE
Missing native symbol on JNI support

### ISSUE THREAD

**Issue by Kylianalex** [minecraft-linux/mcpelauncher-manifest#489]
OS : Manjaro 21.0.1 Ornara
CPU architecture : x86_64
GPU drivers : video-nvidia
Launcher version : 20210417 (The Sonic Master) (build 0)
Game version : 1.16.220.02 (X86_64)
Crash log : https://pastebin.com/CrDajLGD

i can provide more informations
i tried 1.16.210.05 (X86_64) and it worked

**Comment by Dreamedc2015** [comment]
Your not using an official build your unlikely to get help with it

**Comment by Kylianalex** [comment]
Used the official appimage and no error
