### ISSUE TITLE
crafting table not working minecraft 1.16.220.02 (x86_64)

### ISSUE THREAD

**Issue by Awiteb** [minecraft-linux/mcpelauncher-manifest#490]
I cannot use the crafting table

**Comment by Awiteb** [comment]
# Some pictures

https://prnt.sc/11u0qfk
https://prnt.sc/11u0ly8
https://prnt.sc/11u0p7x

**Comment by ChristopherHX** [comment]
Duplicate of https://github.com/minecraft-linux/mcpelauncher-manifest/issues/478
