### ISSUE TITLE
Block Texture

### ISSUE THREAD

**Issue by BlckqFlorian** [minecraft-linux/mcpelauncher-manifest#493]
Many blocks does not have the right texture.

![grafik](https://user-images.githubusercontent.com/38558911/115912993-525c3880-a470-11eb-8d57-bb67f5ee9062.png)
![grafik](https://user-images.githubusercontent.com/38558911/115913070-6b64e980-a470-11eb-8c1e-b3e2cb000559.png)
![grafik](https://user-images.githubusercontent.com/38558911/115913135-7c155f80-a470-11eb-8e1f-fdc43dda796d.png)

**Comment by guppy42** [comment]
See answer in #485

**Comment by ChristopherHX** [comment]
No longer happen in this launcher, I invested more than 12 hours to find a way to hide this bug. (update to v0.2.1)
