### ISSUE TITLE
Xboxlive Sign in error

### ISSUE THREAD

**Issue by MeWnoJinsei** [minecraft-linux/mcpelauncher-manifest#5]
Traceback:
......
17:55:06 Trace [Launcher] HTTPRequestInternalAndroid::send stub called
17:55:06 Trace [Launcher] HTTPRequestInternalAndroid::send stub called
17:55:06 Debug [XSAPI.Android] sign_in_impl: will be showing UI
17:55:06 Debug [XSAPI.Android] sign_in_impl: native activity, continuing on
17:55:06 Trace [XboxLive] log_telemetry_signin 0 Entering
17:55:06 Trace [Launcher] init_sign_in_activity 1
17:55:06 Trace [XboxLive] invoke_auth_flow
17:55:06 Trace [XboxLive] Sign in error: Could not connect to the daemon
17:55:06 Trace [Launcher] init_sign_in_activity 6
17:55:06 Trace [XboxLive] log_telemetry_signin 0 Exiting - runtime_error
17:55:06 Trace [Launcher] HTTPRequestInternalAndroid::send stub called
......

**Comment by MCMrARM** [comment]
Please join the discord, where I'll be able to help you fix this issue: https://discord.gg/TaUNBXr
