### ISSUE TITLE
Does not start

### ISSUE THREAD

**Issue by Gambulec** [minecraft-linux/mcpelauncher-manifest#50]
When I press the play, a flashing window appears with the game and after a while I get it:

19:25:18 Info  [Launcher] Version: client bff35c5 / manifest f662578
19:25:18 Info  [Launcher] CPU: GenuineIntel               Intel(R) Pentium(R) D CPU 3.40GHz
19:25:18 Info  [Launcher] CPU supports SSSE3: NO
19:25:18 Trace [Launcher] Loading hybris libraries
19:25:18 Trace [HybrisUtils] Loaded OS library /usr/share/mcpelauncher/libs/native/libfmod.so.9.16
19:25:18 Trace [HybrisUtils] Loaded OS library libm.so.6
19:25:18 Trace [Launcher] Loading Minecraft library
19:25:20 Info  [Launcher] Loaded Minecraft library
19:25:20 Debug [Launcher] Minecraft is at offset 0xe9e8c000
19:25:20 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance16initializeServerER13IMinecraftAppR9WhitelistP15PermissionsFileP15FilePathManagerNSt6chrono8durationIxSt5ratioILx1ELx1EEEESsSsSs13LevelSettingsibiiibRKSt6vectorISsSaISsEESsRKN3mce4UUIDER18IMinecraftEventingR22ResourcePackRepositoryRK18ContentTierManagerR19ResourcePackManagerSt8functionIFSt10unique_ptrI12LevelStorageSt14default_deleteISY_EER9SchedulerEERKSsP9LevelDataSsSsSX_I16EducationOptionsSZ_IS1A_EEPSU_SW_IFvS17_EES1F_
19:25:20 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance16_syncDestroyGameEv
19:25:20 Error [MinecraftSymbols] Unresolved symbol: _ZN28DedicatedServerCommandOriginC2ERKSsR9Minecraft
19:25:20 Info  [Launcher] Game version: 1.9.0.3
19:25:20 Info  [Launcher] Applying patches
19:25:20 Trace [Store] Vtable size = 33
19:25:20 Trace [Patch] Patching - original: 85 83 87 86 131
19:25:20 Trace [Patch] Patching - result: 233 136 110 75 107
19:25:20 Trace [Patch] Patching - original: 83 87 86 131 236
19:25:20 Trace [Patch] Patching - result: 233 199 163 90 106
19:25:20 Trace [Patch] Patching - original: 85 83 87 86 129
19:25:20 Trace [Patch] Patching - result: 233 63 85 225 104
19:25:20 Trace [Patch] Patching - original: 85 83 87 86 129
19:25:20 Trace [Patch] Patching - result: 233 127 148 31 105
19:25:20 Trace [Patch] Patching - original: 85 83 87 86 129
19:25:20 Trace [Patch] Patching - result: 233 213 164 31 105
19:25:20 Trace [Patch] Patching - original: 85 83 87 86 129
19:25:20 Trace [Patch] Patching - result: 233 73 145 31 105
19:25:20 Trace [Patch] Patching - original: 85 83 87 86 129
19:25:20 Trace [Patch] Patching - result: 233 101 252 30 105
19:25:20 Trace [Patch] Patching - original: 85 83 87 86 129
19:25:20 Trace [Patch] Patching - result: 233 235 249 30 105
19:25:20 Trace [Patch] Patching - original: 85 83 87 86 129
19:25:20 Trace [Patch] Patching - result: 233 133 50 33 105
19:25:20 Trace [Patch] Patching - original: 83 87 86 131 236
19:25:20 Trace [Patch] Patching - result: 233 195 153 31 105
19:25:20 Trace [Patch] Patching - original: 85 83 87 86 129
19:25:20 Trace [Patch] Patching - result: 233 127 196 31 105
19:25:20 Trace [Patch] Patching - original: 49 192 195 141 182
19:25:20 Trace [Patch] Patching - result: 233 11 48 69 107
19:25:20 Trace [Patch] Patching - original: 83 131 236 8 232
19:25:20 Trace [Patch] Patching - result: 233 207 30 61 105
19:25:20 Trace [Patch] Patching - original: 137 76 36 4 137
19:25:20 Trace [Patch] Patching - result: 232 74 55 242 104
19:25:20 Trace [Patch] Patching - original: 36 88 139 65 12
19:25:20 Trace [Patch] Patching - result: 232 85 55 242 104
19:25:20 Trace [Patch] Patching - original: 85 83 87 86 131
19:25:20 Trace [Patch] Patching - result: 233 112 79 78 107
19:25:20 Trace [Patch] Patching - original: 85 83 87 86 129
19:25:20 Trace [Patch] Patching - result: 233 253 77 78 107
19:25:20 Trace [Patch] Patching - original: 83 87 86 131 236
19:25:20 Trace [Patch] Patching - result: 233 201 78 78 107
19:25:20 Trace [Patch] Patching - original: 85 137 229 83 87
19:25:20 Trace [Patch] Patching - result: 233 146 59 218 104
19:25:20 Trace [Patch] Patching - original: 83 86 131 236 20
19:25:20 Trace [Patch] Patching - result: 233 109 155 175 106
19:25:20 Trace [Patch] Patching - original: 232 13 121 245 253
19:25:20 Trace [Patch] Patching - result: 232 177 62 98 105
19:25:20 Info  [Launcher] Creating window
19:25:20 Trace [Launcher] Loading gamepad mappings: /usr/share/mcpelauncher/gamecontrollerdb.txt
19:25:20 Trace [Launcher] Loading gamepad mappings: /usr/share/mcpelauncher/gamecontrollerdb.txt
19:25:21 Trace [Launcher] Initializing AppPlatform (vtable)
19:25:21 Trace [AppPlatform] Vtable size = 255
19:25:21 Trace [Launcher] Initializing AppPlatform (create instance)
19:25:21 Trace [Launcher] Initializing AppPlatform (initialize call)
19:25:21 Trace [AppPlatform] createDeviceID (from file): b287a31a-450b-4959-8175-dd69270a3d0e
19:25:21 Info  [Launcher] OpenGL: version: OpenGL ES 3.1 Mesa 18.0.5, renderer: AMD CAICOS (DRM 2.50.0 / 4.15.0-43-generic, LLVM 6.0.0), vendor: X.Org
19:25:21 Trace [Launcher] Initializing MinecraftGame (create instance)
19:25:21 Trace [AppPlatform] getSystemRegion: en_US
19:25:21 Trace [Launcher] Initializing MinecraftGame (init call)
19:25:21 Info  [Launcher] Game initialized
19:25:21 Trace [AppPlatform] getDataUrl: /home/jarek/.local/share/mcpelauncher/versions/1.9.0.3/assets/
19:25:21 Info  [Cohtml] Initializing COHTML ver. 1.14.0.5
19:25:21 Debug [Cohtml] Opening task channel 2 on family 0
19:25:21 Debug [Cohtml] Opening task channel 0 on family 0
19:25:21 Info  [Cohtml] Coherent Renoir library initialized!
19:25:21 Info  [Cohtml] COHTML library initialized!
19:25:21 Debug [Cohtml] Opening task channel 2 on family 1
19:25:21 Info  [Cohtml] Failed to load dynamic library: MediaDecoders_Android.so with error: Cannot load library: load_library[1115]: Library 'libMediaDecoders_Android.so' not found
19:25:21 Debug [Cohtml] Inspector is disabled
19:25:21 Debug [Cohtml] Opening task channel 2 on family 2
19:25:21 Debug [Cohtml] Opening task channel 0 on family 2
19:25:21 Debug [Cohtml] Opening task channel 0 on family 1
19:25:21 Warn  [Cohtml] Unable to load default font name Droid Sans
19:25:23 Trace [AppPlatform] getDataUrl: /home/jarek/.local/share/mcpelauncher/versions/1.9.0.3/assets/
19:25:23 Error [XSAPI.Android] read_local_storage: ifstream failureMalformed token
19:25:23 Trace [XboxLive] Reading xbox config file
19:25:23 Error [XSAPI.Android] java interop not initialized properly
19:25:23 Trace [Launcher] Creating store
Process exited with unexpected exit code: 4

**Comment by arvati** [comment]
some problem.

```
16:01:07 Info  [Launcher] Version: client b63fb08 / manifest 769df90
16:01:07 Info  [Launcher] CPU: GenuineIntel Genuine Intel(R) CPU           T2050  @ 1.60GHz
16:01:07 Info  [Launcher] CPU supports SSSE3: NO
16:01:07 Trace [Launcher] Loading hybris libraries
16:01:07 Trace [HybrisUtils] Loaded OS library /home/xxxxx/minecraft/mcpelauncher/mcpelauncher-linux-bin/libs/native/libfmod.so.9.16
16:01:07 Trace [HybrisUtils] Loaded OS library libm.so.6
16:01:07 Trace [Launcher] Loading Minecraft library
16:01:11 Info  [Launcher] Loaded Minecraft library
16:01:11 Debug [Launcher] Minecraft is at offset 0xaf639000
16:01:11 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance16_syncDestroyGameEv
16:01:11 Info  [Launcher] Game version: 1.9.0
16:01:11 Info  [Launcher] Applying patches
16:01:11 Trace [Store] Vtable size = 33
16:01:11 Trace [Patch] Patching - original: 85 83 87 86 131
16:01:11 Trace [Patch] Patching - result: 233 108 149 190 79
16:01:11 Trace [Patch] Patching - original: 83 87 86 131 236
16:01:11 Trace [Patch] Patching - result: 233 69 55 205 78
16:01:11 Trace [Patch] Patching - original: 85 83 87 86 129
16:01:11 Trace [Patch] Patching - result: 233 253 248 83 77
16:01:11 Trace [Patch] Patching - original: 85 83 87 86 129
16:01:11 Trace [Patch] Patching - result: 233 61 56 146 77
16:01:11 Trace [Patch] Patching - original: 85 83 87 86 129
16:01:11 Trace [Patch] Patching - result: 233 41 72 146 77
16:01:11 Trace [Patch] Patching - original: 85 83 87 86 129
16:01:11 Trace [Patch] Patching - result: 233 107 52 146 77
16:01:11 Trace [Patch] Patching - original: 85 83 87 86 129
16:01:11 Trace [Patch] Patching - result: 233 15 159 145 77
16:01:11 Trace [Patch] Patching - original: 85 83 87 86 129
16:01:11 Trace [Patch] Patching - result: 233 3 156 145 77
16:01:11 Trace [Patch] Patching - original: 85 83 87 86 129
16:01:11 Trace [Patch] Patching - result: 233 123 212 147 77
16:01:11 Trace [Patch] Patching - original: 83 87 86 131 236
16:01:11 Trace [Patch] Patching - result: 233 151 59 146 77
16:01:11 Trace [Patch] Patching - original: 85 83 87 86 129
16:01:11 Trace [Patch] Patching - result: 233 83 102 146 77
16:01:11 Trace [Patch] Patching - original: 49 192 195 141 182
16:01:11 Trace [Patch] Patching - result: 233 187 97 184 79
16:01:11 Trace [Patch] Patching - original: 83 131 236 8 232
16:01:11 Trace [Patch] Patching - result: 233 111 131 175 77
16:01:11 Trace [Patch] Patching - original: 137 76 36 4 137
16:01:11 Trace [Patch] Patching - result: 232 175 152 100 77
16:01:11 Trace [Patch] Patching - original: 36 88 139 65 12
16:01:11 Trace [Patch] Patching - result: 232 186 152 100 77
16:01:11 Trace [Patch] Patching - original: 85 83 87 86 131
16:01:11 Trace [Patch] Patching - result: 233 44 99 193 79
16:01:11 Trace [Patch] Patching - original: 85 83 87 86 129
16:01:11 Trace [Patch] Patching - result: 233 151 97 193 79
16:01:11 Trace [Patch] Patching - original: 83 87 86 131 236
16:01:11 Trace [Patch] Patching - result: 233 99 98 193 79
16:01:11 Trace [Patch] Patching - original: 85 137 229 83 87
16:01:11 Trace [Patch] Patching - result: 233 32 157 76 77
16:01:11 Trace [Patch] Patching - original: 83 86 131 236 20
16:01:11 Trace [Patch] Patching - result: 233 123 78 34 79
16:01:11 Trace [Patch] Patching - original: 232 61 104 245 253
16:01:11 Trace [Patch] Patching - result: 232 49 187 212 77
16:01:11 Info  [Launcher] Creating window
16:01:11 Trace [Launcher] Loading gamepad mappings: /home/xxxxxxx/minecraft/mcpelauncher/build/gamecontrollerdb/gamecontrollerdb.txt
16:01:11 Trace [Launcher] Loading gamepad mappings: /usr/share/mcpelauncher/gamecontrollerdb.txt
16:01:11 Trace [Launcher] Initializing AppPlatform (vtable)
16:01:11 Trace [AppPlatform] Vtable size = 256
16:01:11 Trace [Launcher] Initializing AppPlatform (create instance)
16:01:11 Trace [Launcher] Initializing AppPlatform (initialize call)
16:01:11 Trace [AppPlatform] createDeviceID (from file): c3369786-4059-4b37-bdcb-0542bb8c2016
16:01:11 Info  [Launcher] OpenGL: version: OpenGL ES 2.0 Mesa 18.3.2, renderer: Mesa DRI Intel(R) 945GM x86/MMX/SSE2, vendor: Intel Open Source Technology Center
16:01:11 Trace [Launcher] Initializing MinecraftGame (create instance)
16:01:11 Trace [AppPlatform] getSystemRegion: en_US
16:01:11 Trace [Launcher] Initializing MinecraftGame (init call)
16:01:11 Info  [Launcher] Game initialized
16:01:11 Trace [WindowCallbacks] Gamepad connected #0
16:01:11 Trace [AppPlatform] getDataUrl: /home/xxxxxx/.local/share/mcpelauncher/versions/1.9.0.15/assets/
16:01:11 Info  [Cohtml] Initializing COHTML ver. 1.14.0.5
16:01:11 Debug [Cohtml] Opening task channel 2 on family 0
16:01:11 Debug [Cohtml] Opening task channel 0 on family 0
16:01:11 Info  [Cohtml] Coherent Renoir library initialized!
16:01:11 Info  [Cohtml] COHTML library initialized!
16:01:11 Debug [Cohtml] Opening task channel 2 on family 1
16:01:11 Info  [Cohtml] Failed to load dynamic library: MediaDecoders_Android.so with error: Cannot load library: load_library[1115]: Library 'libMediaDecoders_Android.so' not found
16:01:11 Debug [Cohtml] Inspector is disabled
16:01:11 Debug [Cohtml] Opening task channel 2 on family 2
16:01:11 Debug [Cohtml] Opening task channel 0 on family 2
16:01:11 Debug [Cohtml] Opening task channel 0 on family 1
16:01:11 Warn  [Cohtml] Unable to load default font name Droid Sans
16:01:11 Error [Shader] An error was detected when compiling a shader
0:70(32): error: `VIEWPORT_SIZE' undeclared
0:70(32): error: type mismatch
0:70(26): error: operands to arithmetic operators must be numeric
0:70(20): error: cannot construct `vec2' from a non-numeric data type
0:74(51): warning: `pixel_step' used uninitialized
0:76(49): warning: `pixel_step' used uninitialized

16:01:11 Error [Shader] An error was detected when linking a shader program
error: program lacks a fragment shader

16:01:11 Error [Shader] An error was detected when compiling a shader
0:72(32): error: `VIEWPORT_SIZE' undeclared
0:72(32): error: type mismatch
0:72(26): error: operands to arithmetic operators must be numeric
0:72(20): error: cannot construct `vec2' from a non-numeric data type
0:76(51): warning: `pixel_step' used uninitialized
0:78(49): warning: `pixel_step' used uninitialized
0:89(46): warning: `pixel_step' used uninitialized
0:91(49): warning: `pixel_step' used uninitialized

16:01:11 Error [Shader] An error was detected when linking a shader program
error: program lacks a fragment shader

16:01:12 Trace [AppPlatform] getDataUrl: /home/xxxxxxx/.local/share/mcpelauncher/versions/1.9.0.15/assets/
16:01:12 Error [XSAPI.Android] read_local_storage: ifstream failureMalformed token
16:01:12 Trace [XboxLive] Reading xbox config file
16:01:12 Error [XSAPI.Android] java interop not initialized properly
16:01:12 Trace [Launcher] Creating store
16:01:12 Trace [Store] registerLicenseChangeCallback
Process exited with unexpected exit code: 4
```

**Comment by Mhowser** [comment]
Did you get your apk from the play store or did you manually extract.

**Comment by MCMrARM** [comment]
`16:01:07 Info  [Launcher] CPU supports SSSE3: NO` is a death flag. If this is found in the log this means the launcher does not support your PC, unfortunately.
