### ISSUE TITLE
No sound is heard from my minecraft

### ISSUE THREAD

**Issue by MrSlixX** [minecraft-linux/mcpelauncher-manifest#513]
Help me, when I get into my minecraft, neither the menu sounds nor in a game

**Comment by ChristopherHX** [comment]
Incomplete bug report.
Unknown OS.
Unknown CPU.
Unknown Minecraft Version.
Unknown Minecraft Architecture

Very old mac devices only supports sound till minecraft 1.16.10. You can technically compile 32bit pulseaudio and build the launcher from source, thats to time consuming for me.
