### ISSUE TITLE
[Feature Request] Worlds/Resource Packs shortcut button in launcher

### ISSUE THREAD

**Issue by TheAlienDrew** [minecraft-linux/mcpelauncher-manifest#518]
To be clear, I already know about https://github.com/minecraft-linux/mcpelauncher-manifest/issues/463, and where the locations are. I also am not expecting any kind of this functionality to be enabled in-game, as I'm just suggesting this for the launcher itself (as I'm sure that would be a lot easier to implement).

So would it be possible, and a maybe a good idea?

**Comment by ChristopherHX** [comment]
Gamedata button is already there.
So yes I could add three new buttons without huge changes. 
- minecraft worlds
- behavior packs
- resource packs

**Comment by TheAlienDrew** [comment]
Maybe it could be a dropdown button item (similar to my little mockup)
![image](https://user-images.githubusercontent.com/19640692/120563028-7fc7ca80-c3bc-11eb-80a7-6c699841319b.png)

**Comment by ChristopherHX** [comment]
> Maybe it could be a dropdown button item (similar to my little mockup)

I'm not that familar with qt5 qml to implement such things in a reasonable amount of time. Feel free to open a PR to change the design. Added as four basic buttons, storage tab.
