### ISSUE TITLE
Error when launching with 1.8.0.11

### ISSUE THREAD

**Issue by MaltronCraft** [minecraft-linux/mcpelauncher-manifest#52]
/usr/bin/mcpelauncher-client: error while loading shared libraries: libEGL.so.1: cannot open shared object file: No such file or directory
Process exited with unexpected exit code: 127

**Comment by MCMrARM** [comment]
You must install GL drivers, this section applies: https://mcpelauncher.readthedocs.io/en/latest/troubleshooting.html#graphics-performance-issues-software-rendering
