### ISSUE TITLE
Worlds Don't Export

### ISSUE THREAD

**Issue by GabeCoder** [minecraft-linux/mcpelauncher-manifest#533]
A few months ago, I decided to add the "World Export Addon" to Minecraft so I could backup my important worlds, such as my survival world and my server's world. The problem is that I can't actually export my worlds directly from the game after updating to 1.17. The "Export World" button actually exported the world in earlier versions, and I've tested it on my iPad to see if 1.17 doesn't let me backup anything, and the button actually exported the world, so I deemed the launcher the main problem. I wanted to see if you could fix the problem because backups are **very** important to me.

**Comment by ChristopherHX** [comment]
This launcher is only an experiment.
Why cannot you backup your world folder?
https://mcpelauncher.readthedocs.io/en/latest/faq.html#where-are-my-worlds

Just backup that folder, it contains all your worlds.
Copy it back then they are restored.
Android doesn't have this button, this is the android version.

**Comment by GabeCoder** [comment]
> This launcher is only an experiment.
> Why cannot you backup your world folder?
> https://mcpelauncher.readthedocs.io/en/latest/faq.html#where-are-my-worlds
> 
> Just backup that folder, it contains all your worlds.
> Copy it back then they are restored.
> Android doesn't have this button, this is the android version.

Only an experiment, eh? Okay.

**Comment by GabeCoder** [comment]
Just so you know, I tried reactivating the World Export Addon. Nothing worked. I'll also answer your questions.
> This launcher is only an experiment.
Does that mean the launcher is still in beta, or does it mean that it actually is just to test players as subjects?
> Why cannot you backup your world folder?
I'm more of a one-click person. It basically means that I like to export worlds with only one button.

**Comment by GabeCoder** [comment]
I will explain more on why I’d rather use the World Export Addon to backup my worlds.
1. It’s a lot easier to export worlds with only one click, which is better than using a file manager to find the hidden Minecraft launcher folder.
2. The world itself is exported as a .ZIP format, which is compatible with the Minecraft Importer app I have. Any other formats are incompatible.
3. Constantly archiving the worlds with the file manager is a lot harder to get used to.

**Comment by GabeCoder** [comment]
I will explain more on why I’d rather use the World Export Addon to backup my worlds.
1. It’s a lot easier to export worlds with only one click, which is better than using a file manager to find the hidden Minecraft launcher folder.
2. The world itself is exported as a .ZIP format, which is compatible with the Minecraft Importer app I have. Any other formats are incompatible.
3. The sur

**Comment by GabeCoder** [comment]
I visited the webpage of the World Export Addon and realized that the problem involves the addon itself, not the launcher. Sorry for the inconvenience.
