### ISSUE TITLE
Game freeze then crashed when player is drowned 

### ISSUE THREAD

**Issue by bramaudi** [minecraft-linux/mcpelauncher-manifest#537]
I have installed version 1.17 and latest launcher, when player is out of air underwater then game is starting to freeze before crash.

Error Log: https://pastebin.com/dt3bKVpM

**Comment by xproot** [comment]
This issue also happens to me, this needs to get more relevant.

**Comment by bramaudi** [comment]
After a quite long time, I came back and installed again with the latest one and it worked, using the Minecraft version 1.18.0.02 and with the latest launcher from forked repo (Link is available on the official website https://mcpelauncher.readthedocs.io/)

So I assume this bug is fixed so closed this issue.
