### ISSUE TITLE
 does not allow me to put crafted items in my inventory

### ISSUE THREAD

**Issue by zahkk** [minecraft-linux/mcpelauncher-manifest#553]
Every single time I try to put a crafted item into my inventory it always glitches. I am on Chrome OS by the way.

**Comment by ironboy36** [comment]
I have a bug that I cant craft a crafting table or anything else
![Screen Shot 2021-07-01 at 8 08 57 AM](https://user-images.githubusercontent.com/77495097/124122176-cd7b3580-da43-11eb-959f-b67d63166446.png)

**Comment by ChristopherHX** [comment]
[There is a big red warning in the Launcher with a workaround, you can click it or click this one](https://github.com/minecraft-linux/mcpelauncher-manifest/issues/478#issuecomment-822441250).

**This is an unresolved Minecraft Android bug, this Launcher cannot do much against it.**
