### ISSUE TITLE
I can't craft anything in survival!

### ISSUE THREAD

**Issue by ironboy36** [minecraft-linux/mcpelauncher-manifest#554]
I can't craft **nothing** not even a crafting table but the only thing I **can** craft is a **button**
Please fix this bug in the game.
![Screen Shot 2021-07-01 at 8 13 32 AM](https://user-images.githubusercontent.com/77495097/124122805-7fb2fd00-da44-11eb-99fd-98e888455dee.png)
![Screen Shot 2021-07-01 at 8 08 57 AM](https://user-images.githubusercontent.com/77495097/124122842-89d4fb80-da44-11eb-9e1a-3399930929bb.png)

**Comment by ChristopherHX** [comment]
[There is a big red warning in the Launcher with a workaround, you can click it or click this one](https://github.com/minecraft-linux/mcpelauncher-manifest/issues/478#issuecomment-822441250).

**This is an unresolved Minecraft Android bug, this Launcher cannot do much against it.**

**Comment by ironboy36** [comment]
I am gonna close this and continue to the other bug.
