### ISSUE TITLE
 The specified file is not compatible with the launcher

### ISSUE THREAD

**Issue by OGFris** [minecraft-linux/mcpelauncher-manifest#56]
I tried with two different versions but each time I tried to import the apk file it fails to extract with the error ` The specified file is not compatible with the launcher`

**Comment by MCMrARM** [comment]
You must use a x86 apk.

**Comment by MCMrARM** [comment]
Please sign in to a Google account instead.

**Comment by OGFris** [comment]
yeah my bad i just did that but i got another error 
`/usr/bin/mcpelauncher-client: error while loading shared libraries: libEGL.so.1: cannot open shared object file: No such file or directory
Process exited with unexpected exit code: 127
`

**Comment by MCMrARM** [comment]
Install OpenGL drivers, eg. `libegl1-mesa-dev:i386`
