### ISSUE TITLE
I meet problem when I build it on deepinOS

### ISSUE THREAD

**Issue by MCredbear** [minecraft-linux/mcpelauncher-manifest#57]
Here is my log:
redbear@redbear-PC:~/mcpelauncher/build$ make -j2
[  6%] Built target nlohmann_json_ext
[  6%] Built target gamecontrollerdb
[  9%] Built target eglut
[ 14%] Built target linux-gamepad
[ 15%] Built target base64
[ 17%] Built target logger
[ 20%] Built target file-util
[ 35%] Built target hybris
[ 37%] Built target filepicker
[ 49%] Built target simpleipc
[ 54%] Built target gamewindow
[ 67%] Built target cll-telemetry
[ 69%] Built target minecraft-symbols
[ 70%] Built target mcpelauncher-common
[ 71%] Built target daemon-client-utils
[ 78%] Built target mcpelauncher-core
[ 81%] Built target msa-daemon-client
[ 84%] Built target mcpelauncher-server
[ 86%] Built target mcpelauncher-just
[ 87%] Linking CXX executable mcpelauncher-client
/usr/local/lib/libcurl.so: 无法添加符号: 文件格式错误
collect2: error: ld returned 1 exit status
make[2]: *** [mcpelauncher-client/CMakeFiles/mcpelauncher-client.dir/build.make:339：mcpelauncher-client/mcpelauncher-client] 错误 1
make[1]: *** [CMakeFiles/Makefile2:1068：mcpelauncher-client/CMakeFiles/mcpelauncher-client.dir/all] 错误 2
make: *** [Makefile:141：all] 错误 2

Can anyone give me some advice?(May be you can't read Chinese,sorry)

**Comment by MCMrARM** [comment]
Install 32-bit curl
