### ISSUE TITLE
Showing Achivements not working

### ISSUE THREAD

**Issue by xproot** [minecraft-linux/mcpelauncher-manifest#595]
Keep in mind: **I still can get achievements, just can't see them in the game.** (Also I can't tell if this is a Mojang bug or a mcpelauncher one, in Windows 10 edition the button can show up sometimes and sometimes it doesn't, haven't tried a resource pack)
Edit 1: Tried it on my android phone, it doesn't crash so probably launcher bug.

Version: Minecraft 1.17.11.01 (X86_64)
OS: Ubuntu 20.04.3 LTS 
Kernel: 5.11.0-27-generic

I noticed there was no achievements button in the game when first loading it up, and the one in the skin editor does not work. Once I tried a custom GUI resource pack it appeared but when I click it, it instantly crashes my game **(LOG: https://paste.debian.net/plain/1209604**

Funnily enough I was playing in my world until I got a KDE Notification showing that the Xbox app in my phone showed a new achievement I had gotten in Minecraft for Android

**Comment by ChristopherHX** [comment]
Fixed by mojang in 1.17.30.22 (x86_64, beta), your phone has a different version of the game so not affected.
Also the xbox.com is enough to manage archivements, on linux.

**Comment by ChristopherHX** [comment]
Fixed in ng by https://github.com/minecraft-linux/mcpelauncher-manifest/commit/75ec84ca75d3305621a8ac534bf8b1812eb2ded3.
