### ISSUE TITLE
Crash on Google Sign-in (AppImage)

### ISSUE THREAD

**Issue by jess-sch** [minecraft-linux/mcpelauncher-manifest#60]
```
qrc:/qml/ThemedControls/PlayButton.qml:8:30: Unable to assign null to QString
Version list loaded, entry count: 69
[4470:4500:0301/191558.594456:ERROR:nss_util.cc(712)] Error initializing NSS with a persistent database (sql:/home/lumi/.pki/nssdb): NSS error code: -8023
[4470:4500:0301/191558.594585:ERROR:nss_util.cc(201)] Error initializing NSS without a persistent database: NSS error code: -8023
[4470:4500:0301/191558.594600:FATAL:nss_util.cc(203)] nss_error=-8023, os_error=0
#0 0x7fc84a20516e <unknown>
#1 0x7fc84a2178ae <unknown>
#2 0x7fc84a9d42da <unknown>
#3 0x7fc84a9d46e0 <unknown>
#4 0x7fc84a902dc5 <unknown>
#5 0x7fc84a7ef7e7 <unknown>
#6 0x7fc84a7baad7 <unknown>
#7 0x7fc84995189a <unknown>
#8 0x7fc849952e06 <unknown>
#9 0x7fc849954dd7 <unknown>
#10 0x7fc849b2d857 <unknown>
#11 0x7fc849e640b0 <unknown>
#12 0x7fc84a27ac59 <unknown>
#13 0x7fc84a21fff0 <unknown>
#14 0x7fc84a221cbd <unknown>
#15 0x7fc84a222178 <unknown>
#16 0x7fc84a223610 <unknown>
#17 0x7fc84a21f095 <unknown>
#18 0x7fc84a23bbba <unknown>
#19 0x7fc849b66a68 <unknown>
#20 0x7fc849b66c4b <unknown>
#21 0x7fc84a253890 <unknown>
#22 0x7fc84a24f96d <unknown>
#23 0x7fc8470bc58e start_thread
#24 0x7fc846cb46a3 __GI___clone

[1:1:0100/000000.419344:ERROR:broker_posix.cc(41)] Invalid node channel message
[1]    4470 abort (core dumped)  ./minecraft-bedrock-launcher.AppImage
```

**Comment by Conanzhou** [comment]
qml: Failed to load news
terminate called after throwing an instance of 'std::runtime_error'
  what():  No auth cookie field returned
Received signal 6
#0 0x7fac1dcc2e0e <unknown>
#1 0x7fac1dcbffc3 <unknown>
#2 0x7fac1dcc2d85 <unknown>
#3 0x7fac1b1773c0 <unknown>
#4 0x7fac1acaad7f __GI_raise
#5 0x7fac1ac95672 __GI_abort
#6 0x7fac1b05f58e __gnu_cxx::__verbose_terminate_handler()
#7 0x7fac1b065dfa __cxxabiv1::__terminate()
#8 0x7fac1b065e57 std::terminate()
#9 0x7fac1b0660ac __cxa_throw
#10 0x5622f2e7eb0b <unknown>
#11 0x5622f2eb835e <unknown>
#12 0x5622f2eb8730 std::_Function_handler<>::_M_invoke()
#13 0x5622f2eb8e5f _ZN7playapi11merged_taskINS_13http_responseENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEJEE4callEv
#14 0x5622f2eb8f04 _ZN7playapi11merged_taskINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEvJEE4callEv
#15 0x5622f2e8f927 GoogleLoginHelper::onLoginFinished()
#16 0x7fac2263c980 QMetaObject::activate()
#17 0x7fac231d248f QDialog::finished()
#18 0x5622f2eaf78d GoogleLoginWindow::onUrlChanged()
#19 0x7fac2263c980 QMetaObject::activate()
#20 0x7fac22381a26 QWebEngineView::urlChanged()
#21 0x7fac2263c980 QMetaObject::activate()
#22 0x7fac22370ec6 QWebEnginePage::urlChanged()
#23 0x7fac22370f45 <unknown>
#24 0x7fac1c19765d <unknown>
#25 0x7fac1da68160 <unknown>
#26 0x7fac1d7657d8 <unknown>
#27 0x7fac1d768cca <unknown>
#28 0x7fac1d783427 <unknown>
#29 0x7fac1d7aad10 <unknown>
#30 0x7fac1d7ab4f3 <unknown>
#31 0x7fac1c54df4a <unknown>
#32 0x7fac1df443ed <unknown>
#33 0x7fac1e299781 <unknown>
#34 0x7fac1e299b2e <unknown>
#35 0x7fac1dc2a9e0 <unknown>
#36 0x7fac1dc49d09 <unknown>
#37 0x7fac1dc4ab34 <unknown>
#38 0x7fac1dc4af68 <unknown>
#39 0x7fac1c117ef5 <unknown>
#40 0x7fac2263d0bb QObject::event()
#41 0x7fac22fdae24 QApplicationPrivate::notify_helper()
#42 0x7fac22fe25f1 QApplication::notify()
#43 0x7fac22611df9 QCoreApplication::notifyInternal2()
#44 0x7fac22614ee8 QCoreApplicationPrivate::sendPostedEvents()
#45 0x7fac226686c4 <unknown>
#46 0x7fac1a0a47bf g_main_context_dispatch
#47 0x7fac1a0a6739 <unknown>
#48 0x7fac1a0a677e g_main_context_iteration
#49 0x7fac22667c99 QEventDispatcherGlib::processEvents()
#50 0x7fac22610a8c QEventLoop::exec()
#51 0x7fac22618de6 QCoreApplication::exec()
#52 0x5622f2e85e5d main
#53 0x7fac1ac97223 __libc_start_main
#54 0x5622f2e867ae _start
  r8: 0000000000000000  r9: 00007ffc2d7974b0 r10: 0000000000000008 r11: 0000000000000246
 r12: 00005622fb804420 r13: 00007ffc2d7977f0 r14: 00007ffc2d797a80 r15: 00007ffc2d797a68
  di: 0000000000000002  si: 00007ffc2d7974b0  bp: 00007fac1ae326a0  bx: 0000000000000006
  dx: 0000000000000000  ax: 0000000000000000  cx: 00007fac1acaad7f  sp: 00007ffc2d7974b0
  ip: 00007fac1acaad7f efl: 0000000000000246 cgf: 002b000000000033 erf: 0000000000000000
 trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
Calling _exit(1). Core file will not be generated.

**Comment by fazo96** [comment]
Same problem. Works by installing using instructions for arch linux but the AppImage crashes when clicking sign in with google

**Comment by 0A0X** [comment]
Same here, launcher crashes when clicking on the sign in button.

**Comment by loper12** [comment]
It works if you compile the launcher. Luckily, there is an easy script! Clone [this](https://github.com/minecraft-linux/linux-packaging-scripts) repository, and go into the folder, then follow the steps [here](https://github.com/minecraft-linux/linux-packaging-scripts/wiki) you should get the packages in no time.

**Comment by Syndicate6690** [comment]
Same issue here, on an Arch-based system, multilib enabled, x86_64. Only occurs when trying to sign in with a Google account. I've been told in the Discord that this is normal and known. 
```
qrc:/qml/ThemedControls/PlayButton.qml:8:30: Unable to assign null to QString
Version list loaded, entry count: 139
[11483:11534:0616/072408.665374:ERROR:nss_util.cc(712)] Error initializing NSS with a persistent database (sql:/home/syndicate/.pki/nssdb): NSS error code: -8023
[11483:11534:0616/072408.665451:ERROR:nss_util.cc(201)] Error initializing NSS without a persistent database: NSS error code: -8023
[11483:11534:0616/072408.665460:FATAL:nss_util.cc(203)] nss_error=-8023, os_error=0
#0 0x7f07dca2216e <unknown>
#1 0x7f07dca348ae <unknown>
#2 0x7f07dd1f12da <unknown>
#3 0x7f07dd1f16e0 <unknown>
#4 0x7f07dd11fdc5 <unknown>
#5 0x7f07dd00c7e7 <unknown>
#6 0x7f07dcfd7ad7 <unknown>
#7 0x7f07dc16e89a <unknown>
#8 0x7f07dc16fe06 <unknown>
#9 0x7f07dc171dd7 <unknown>
#10 0x7f07dc34a857 <unknown>
#11 0x7f07dc6810b0 <unknown>
#12 0x7f07dca97c59 <unknown>
#13 0x7f07dca3cff0 <unknown>
#14 0x7f07dca3ecbd <unknown>
#15 0x7f07dca3f178 <unknown>
#16 0x7f07dca40610 <unknown>
#17 0x7f07dca3c095 <unknown>
#18 0x7f07dca58bba <unknown>
#19 0x7f07dc383a68 <unknown>
#20 0x7f07dc383c4b <unknown>
#21 0x7f07dca70890 <unknown>
#22 0x7f07dca6c96d <unknown>
#23 0x7f07d96cfa92 start_thread
#24 0x7f07d930dcd3 __GI___clone

Aborted (core dumped)
```

**Comment by MCMrARM** [comment]
The workaround is to use LD_PRELOAD for nss3, eg. `LD_PRELOAD=/usr/lib/libnss3.so ./Minecraft_Bedrock_Launcher.AppImage`

**Comment by EthanWeegee** [comment]
The workaround isn't fixing the issue for me, when signing in and agreeing to Google terms I get this:
```
http response body: 
terminate called after throwing an instance of 'std::runtime_error'
  what():  No auth cookie field returned
Aborted (core dumped)
```

Running openSUSE Leap 15, just compiled the launcher inside an Ubuntu guest VM. The LD_PRELOAD makes no difference. Using the Ubuntu guest I can sign in, but the launcher interface isn't properly/fully rendered and nothing happens outside of console output, which _does_ receive the Auth field.I can successfully sign in with the Ubuntu guest, however, although the workaround was necessary.

**Comment by Mhowser** [comment]
Do you have nss installed in your VM?

https://askubuntu.com/questions/61931/how-to-install-libnss3-dev

**Comment by EthanWeegee** [comment]
I've since figured it out; I had to download and extract the Ubuntu .deb release, and use the binaries from that (after gathering missing libraries). The Ubuntu VM wasn't required for that.

**Comment by zeroepoch** [comment]
On Fedora I had to use `LD_PRELOAD=/usr/lib64/libnss3.so ./Minecraft_Bedrock_Launcher.AppImage`, but then I ran into the same problem with the C++ exception error that @EthanWeegee reported.
