### ISSUE TITLE
error: initializer element is not constant 

### ISSUE THREAD

**Issue by quizhizhe** [minecraft-linux/mcpelauncher-manifest#61]
There are a lot of problems when i use make -j12.                                       /home/android/mcpelauncher/libhybris/src/jb/dlfcn.c:220:17: error: initializer element is not constant                              /home/android/mcpelauncher/libhybris/src/jb/dlfcn.c:220:17: note:(near initialization for 'libdl_symtab[1].st_value')
/home/android/mcpelauncher/libhybris/src/jb/dlfcn.c:225:17: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]                                                                  st_value: (Elf32_Addr) &android_dlclose,                                    ^                                                /home/android/mcpelauncher/libhybris/src/jb/dlfcn.c:225:17: error: initializer element is not constant
/home/android/mcpelauncher/libhybris/src/jb/dlfcn.c:225:17: note:(near initialization for 'libdl_symtab[2].st_value')               /home/android/mcpelauncher/libhybris/src/jb/dlfcn.c:230:17: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]                                                                  st_value: (Elf32_Addr) &android_dlsym,                                      ^                                                /home/android/mcpelauncher/libhybris/src/jb/dlfcn.c:230:17: error: initializer element is not constant                              /home/android/mcpelauncher/libhybris/src/jb/dlfcn.c:230:17: note:(near initialization for 'libdl_symtab[3].st_value')               /home/android/mcpelauncher/libhybris/src/jb/dlfcn.c:235:17: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]                                                                  st_value: (Elf32_Addr) &android_dlerror,
/home/android/mcpelauncher/libhybris/src/jb/dlfcn.c:235:17: error: initializer element is not constant                              /home/android/mcpelauncher/libhybris/src/jb/dlfcn.c:235:17: note:(near initialization for 'libdl_symtab[4].st_value')               /home/android/mcpelauncher/libhybris/src/jb/dlfcn.c:240:17: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]                                                                  st_value: (Elf32_Addr) &android_dladdr,                                     ^                                                /home/android/mcpelauncher/libhybris/src/jb/dlfcn.c:240:17: error: initializer element is not constant
/home/android/mcpelauncher/libhybris/src/jb/dlfcn.c:240:17: note:(near initialization for 'libdl_symtab[5].st_value')               /home/android/mcpelauncher/libhybris/src/jb/dlfcn.c:246:17: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]                                                                  st_value: (Elf32_Addr) &android_dl_unwind_find_exidx,                       ^                                                /home/android/mcpelauncher/libhybris/src/jb/dlfcn.c:246:17: error: initializer element is not constant                              /home/android/mcpelauncher/libhybris/src/jb/dlfcn.c:246:17: note:(near initialization for 'libdl_symtab[6].st_value')               /home/android/mcpelauncher/libhybris/src/jb/dlfcn.c:254:17: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]                                                                  st_value: (Elf32_Addr) &android_dl_iterate_phdr
/home/android/mcpelauncher/libhybris/src/jb/dlfcn.c:254:17: error: initializer element is not constant                              /home/android/mcpelauncher/libhybris/src/jb/dlfcn.c:254:17: note:(near initialization for 'libdl_symtab[7].st_value')               /home/android/mcpelauncher/libhybris/src/jb/dlfcn.c:260:17: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]                                                                  st_value: (Elf32_Addr) &android_get_application_target_sdk_version,                                                                           ^                                                /home/android/mcpelauncher/libhybris/src/jb/dlfcn.c:260:17: error: initializer element is not constant                              /home/android/mcpelauncher/libhybris/src/jb/dlfcn.c:260:17: note:(near initialization for 'libdl_symtab[8].st_value')               libhybris/CMakeFiles/hybris.dir/build.make:254: recipe for target 'libhybris/CMakeFiles/hybris.dir/src/jb/dlfcn.c.o' failed
make[2]: *** [libhybris/CMakeFiles/hybris.dir/src/jb/dlfcn.c.o] Error 1                                                             make[2]: *** Waiting for unfinished jobs....                      /home/android/mcpelauncher/libhybris/src/hooks_io.c: In function stat64_to_bionic_stat':                                            /home/android/mcpelauncher/libhybris/src/hooks_io.c:129:20: error: 'struct stat64' has no member named '__st_ino'                        b->__st_ino = s->__st_ino;                                                       ^                                             libhybris/CMakeFiles/hybris.dir/build.make:422: recipe for target 'libhybris/CMakeFiles/hybris.dir/src/hooks_io.c.o' failed         make[2]: *** [libhybris/CMakeFiles/hybris.dir/src/hooks_io.c.o] Error 1
CMakeFiles/Makefile2:360: recipe for target 'libhybris/CMakeFiles/hybris.dir/all' failed                                            make[1]: *** [libhybris/CMakeFiles/hybris.dir/all] Error 2        make[1]: *** Waiting for unfinished jobs....                      [ 34%] Linking CXX static library libmcpelauncher-common.a        [ 34%] Built target mcpelauncher-common                           Makefile:127: recipe for target 'all' failed                      make: *** [all] Error 2

**Comment by MCMrARM** [comment]
OS?

**Comment by quizhizhe** [comment]
ubuntu 16.04 
aarch64

**Comment by parkerlreed** [comment]
Still running into this on aarch64 Linux

https://gist.github.com/parkerlreed/9c4becf7cab5671e093b7efb3827983d

**Comment by parkerlreed** [comment]
gcc 9.3.0-1
