### ISSUE TITLE
I meet problem when downloading APK

### ISSUE THREAD

**Issue by MCredbear** [minecraft-linux/mcpelauncher-manifest#63]
I cannot download minecraft,I'm a Chinese,so I use v2ray to connect google's server,my system is deepin,here is my log:

http request: https://android.clients.google.com/fdfe/delivery?doc=com.mojang.minecraftpe&ot=1&vc=872100007&fdcf=1&fdcf=2, body = 
http response body: 
�*J�
����ו����q�0
api response body = payload {
  deliveryResponse {
    status: 3
  }
}
serverMetadata {
  latencyMillis: 17
}
serverLogsCookie: "\010\022\232\001\027\n\023\010\206\204\331\320\327\225\341\002\025\207\202\265\001\035q\211\0070\020\004"

[libprotobuf FATAL /usr/include/google/protobuf/repeated_field.h:1408] CHECK failed: (index) < (current_size_): 
qml: Download failed: CHECK failed: (index) < (current_size_):

**Comment by MCMrARM** [comment]
Do you have MC purchased on that Google Play accunt?

**Comment by Mhowser** [comment]
Also are you trying to download a beta version?

**Comment by MCredbear** [comment]
> 您是否在Google Play上购买了MC？

No......

**Comment by Mhowser** [comment]
You have to purchase Minecraft on the play store first.
