### ISSUE TITLE
Stuck at "Let's go" when trying to join servers

### ISSUE THREAD

**Issue by sa6ta6ni6c** [minecraft-linux/mcpelauncher-manifest#636]
**Screenshots**
https://user-images.githubusercontent.com/44274397/143005762-7ed91a8a-dbb2-4d33-8f16-df6107455985.png

**Desktop (please complete the following information):**
 - OS: [Manjaro linux]
 - Version [v0.3.0.1] (game version 1.17.41)
 - Flatpak

**GameLog**
13:12:39 Info  [Launcher] Version: client 2b3993e / manifest 50fd0e2
13:12:39 Info  [Launcher] CPU: GenuineIntel Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
13:12:39 Info  [Launcher] CPU supports SSSE3: YES
13:12:39 Trace [Launcher] Loading hybris libraries
13:12:39 Trace [REDIRECT] /data/data/com.mojang.minecraftpe to /home/sa6ta6ni6c/.var/app/io.mrarm.mcpelauncher/data/mcpelauncher/
13:12:39 Trace [REDIRECT] /data/data/app/proc/24/cmdline to /home/sa6ta6ni6c/.var/app/io.mrarm.mcpelauncher/data/mcpelauncher/
13:12:39 Trace [REDIRECT] /data/data/app/bin/mcpelauncher-client to /home/sa6ta6ni6c/.var/app/io.mrarm.mcpelauncher/data/mcpelauncher/
13:12:39 Trace [REDIRECT] /data/data to /home/sa6ta6ni6c/.var/app/io.mrarm.mcpelauncher/data/mcpelauncher/
13:12:39 Trace [LinkerUtils] Loaded OS library libm.so.6
13:12:39 Trace [LinkerUtils] Loaded OS library libz.so.1
13:12:40 Trace [LinkerUtils] Loaded OS library /app/share/mcpelauncher/lib/native/x86_64/libfmod.so.12.0
load_library: Undefined symbol glFogf
load_library: Undefined symbol glNormalPointer
load_library: Undefined symbol glColorPointer
load_library: Undefined symbol glTexCoordPointer
load_library: Undefined symbol glVertexPointer
load_library: Undefined symbol glOrthof
load_library: Undefined symbol glLightfv
load_library: Undefined symbol glRotatef
load_library: Undefined symbol glScalef
load_library: Undefined symbol glMatrixMode
load_library: Undefined symbol glDisableClientState
load_library: Undefined symbol glPopMatrix
load_library: Undefined symbol glTranslatef
load_library: Undefined symbol glPushMatrix
load_library: Undefined symbol glColor4f
load_library: Undefined symbol glEnableClientState
load_library: Undefined symbol glAlphaFunc
load_library: Undefined symbol glVertexAttrib4f
load_library: Undefined symbol glVertexAttrib2fv
load_library: Undefined symbol glVertexAttrib2f
load_library: Undefined symbol glVertexAttrib1fv
load_library: Undefined symbol glUseProgram
load_library: Undefined symbol glUniformMatrix4fv
load_library: Undefined symbol glShadeModel
load_library: Undefined symbol glGenRenderbuffers
load_library: Undefined symbol glGetVertexAttribiv
load_library: Undefined symbol glGenerateMipmap
load_library: Undefined symbol glUniform4i
load_library: Undefined symbol glVertexAttribPointer
load_library: Undefined symbol glFramebufferRenderbuffer
load_library: Undefined symbol glDisable
load_library: Undefined symbol glReadPixels
load_library: Undefined symbol glTexParameteriv
load_library: Undefined symbol glUniform3fv
load_library: Undefined symbol glDrawElements
load_library: Undefined symbol glDrawArrays
load_library: Undefined symbol glGenBuffers
load_library: Undefined symbol glGetTexParameteriv
load_library: Undefined symbol glDisableVertexAttribArray
load_library: Undefined symbol glGetShaderiv
load_library: Undefined symbol glGetActiveUniform
load_library: Undefined symbol glEnableVertexAttribArray
load_library: Undefined symbol glBlendEquationSeparate
load_library: Undefined symbol glBindRenderbuffer
load_library: Undefined symbol glScissor
load_library: Undefined symbol glDepthRangef
load_library: Undefined symbol glDetachShader
load_library: Undefined symbol glDeleteProgram
load_library: Undefined symbol glDepthMask
load_library: Undefined symbol glGenFramebuffers
load_library: Undefined symbol glBufferData
load_library: Undefined symbol glEnable
load_library: Undefined symbol glStencilMaskSeparate
load_library: Undefined symbol glCompileShader
load_library: Undefined symbol glBlendEquation
load_library: Undefined symbol glBindTexture
load_library: Undefined symbol glGetBooleanv
load_library: Undefined symbol glMultMatrixf
load_library: Undefined symbol glGetAttachedShaders
load_library: Undefined symbol glUniform2fv
load_library: Undefined symbol glStencilMask
load_library: Undefined symbol glBlendColor
load_library: Undefined symbol glClearDepthf
load_library: Undefined symbol glBindAttribLocation
load_library: Undefined symbol glAttachShader
load_library: Undefined symbol glTexImage2D
load_library: Undefined symbol glDeleteBuffers
load_library: Undefined symbol glFogfv
load_library: Undefined symbol glGetFramebufferAttachmentParameteriv
load_library: Undefined symbol glFrontFace
load_library: Undefined symbol glBlendFunc
load_library: Undefined symbol glActiveTexture
load_library: Undefined symbol glDeleteRenderbuffers
load_library: Undefined symbol glDeleteTextures
load_library: Undefined symbol glBufferSubData
load_library: Undefined symbol glGetError
load_library: Undefined symbol glIsBuffer
load_library: Undefined symbol glDeleteFramebuffers
load_library: Undefined symbol glTexParameterf
load_library: Undefined symbol glHint
load_library: Undefined symbol glIsRenderbuffer
load_library: Undefined symbol glVertexAttrib3fv
load_library: Undefined symbol glCheckFramebufferStatus
load_library: Undefined symbol glCopyTexImage2D
load_library: Undefined symbol glClear
load_library: Undefined symbol glDepthFunc
load_library: Undefined symbol glClearColor
load_library: Undefined symbol glUniform2f
load_library: Undefined symbol glGetUniformLocation
load_library: Undefined symbol glUniform1fv
load_library: Undefined symbol glUniformMatrix2fv
load_library: Undefined symbol glGenTextures
load_library: Undefined symbol glReleaseShaderCompiler
load_library: Undefined symbol glColorMask
load_library: Undefined symbol glCreateShader
load_library: Undefined symbol glIsProgram
load_library: Undefined symbol glVertexAttrib1f
load_library: Undefined symbol glUniform3f
load_library: Undefined symbol glCopyTexSubImage2D
load_library: Undefined symbol glVertexAttrib3f
load_library: Undefined symbol glCreateProgram
load_library: Undefined symbol glGetBufferParameteriv
load_library: Undefined symbol glGetIntegerv
load_library: Undefined symbol glCompressedTexSubImage2D
load_library: Undefined symbol glCullFace
load_library: Undefined symbol glGetProgramiv
load_library: Undefined symbol glGetProgramInfoLog
load_library: Undefined symbol glGetShaderInfoLog
load_library: Undefined symbol glGetActiveAttrib
load_library: Undefined symbol glSampleCoverage
load_library: Undefined symbol glGetShaderPrecisionFormat
load_library: Undefined symbol glBlendFuncSeparate
load_library: Undefined symbol glGetShaderSource
load_library: Undefined symbol glIsFramebuffer
load_library: Undefined symbol glViewport
load_library: Undefined symbol glFramebufferTexture2D
load_library: Undefined symbol glGetString
load_library: Undefined symbol glUniformMatrix3fv
load_library: Undefined symbol glGetTexParameterfv
load_library: Undefined symbol glIsTexture
load_library: Undefined symbol glDeleteShader
load_library: Undefined symbol glGetUniformfv
load_library: Undefined symbol glStencilFuncSeparate
load_library: Undefined symbol glGetFloatv
load_library: Undefined symbol glGetUniformiv
load_library: Undefined symbol glBindFramebuffer
load_library: Undefined symbol glIsEnabled
load_library: Undefined symbol glGetVertexAttribfv
load_library: Undefined symbol glIsShader
load_library: Undefined symbol glLineWidth
load_library: Undefined symbol glLinkProgram
load_library: Undefined symbol glPixelStorei
load_library: Undefined symbol glClearStencil
load_library: Undefined symbol glFinish
load_library: Undefined symbol glPolygonOffset
load_library: Undefined symbol glGetAttribLocation
load_library: Undefined symbol glRenderbufferStorage
load_library: Undefined symbol glLoadIdentity
load_library: Undefined symbol glShaderSource
load_library: Undefined symbol glStencilOp
load_library: Undefined symbol glGetRenderbufferParameteriv
load_library: Undefined symbol glStencilFunc
load_library: Undefined symbol glStencilOpSeparate
load_library: Undefined symbol glGetVertexAttribPointerv
load_library: Undefined symbol glTexParameterfv
load_library: Undefined symbol glValidateProgram
load_library: Undefined symbol glFlush
load_library: Undefined symbol glUniform1iv
load_library: Undefined symbol glTexParameteri
load_library: Undefined symbol glLightModelf
load_library: Undefined symbol glUniform2i
load_library: Undefined symbol glUniform4iv
load_library: Undefined symbol glShaderBinary
load_library: Undefined symbol glUniform1f
load_library: Undefined symbol glFogx
load_library: Undefined symbol glVertexAttrib4fv
load_library: Undefined symbol glBindBuffer
load_library: Undefined symbol glUniform1i
load_library: Undefined symbol glUniform2iv
load_library: Undefined symbol glCompressedTexImage2D
load_library: Undefined symbol glUniform3i
load_library: Undefined symbol glUniform3iv
load_library: Undefined symbol glUniform4f
load_library: Undefined symbol glUniform4fv
13:12:40 Info  [ModLoader] Loading mods
13:12:40 Info  [ModLoader] Loading mod: libcrypto.so
13:12:40 Warn  [ModLoader] Mod /app/share/mcpelauncher/mcpelauncher-updates-bin/x86_64/libcrypto.so does not have a mod_preinit function
13:12:40 Info  [ModLoader] Loading mod: libssl.so
13:12:40 Warn  [ModLoader] Mod /app/share/mcpelauncher/mcpelauncher-updates-bin/x86_64/libssl.so does not have a mod_preinit function
13:12:40 Info  [ModLoader] Loading mod: libmcpelauncherupdates.so
13:12:40 Info  [ModLoader] Loaded 3 mods
13:12:40 Trace [Launcher] Loading Minecraft library
13:12:40 Info  [Launcher] Loaded Minecraft library
13:12:40 Debug [Launcher] Minecraft is at offset 0x0x7f151cb00000
13:12:40 Info  [ModLoader] Loading mods
13:12:40 Info  [ModLoader] Loading mod: libcrypto.so
13:12:40 Warn  [ModLoader] Mod /app/share/mcpelauncher/mcpelauncher-updates-bin/x86_64/libcrypto.so does not have a mod_init function
13:12:40 Info  [ModLoader] Loading mod: libssl.so
13:12:40 Warn  [ModLoader] Mod /app/share/mcpelauncher/mcpelauncher-updates-bin/x86_64/libssl.so does not have a mod_init function
13:12:40 Info  [ModLoader] Loading mod: libmcpelauncherupdates.so
13:12:40 Info  [ModLoader] Loaded 6 mods
13:12:40 Info  [Launcher] Game version: 0.0.0.0
13:12:40 Info  [Launcher] Applying patches
13:12:40 Debug [CorePatches] Failed to patch, vtable _ZTV21AppPlatform_android23 not found
13:12:40 Info  [Launcher] Initializing JNI
13:12:40 Error [JniSupport] Missing native symbol: Java_com_mojang_minecraftpe_MainActivity_nativeRegisterThis
13:12:40 Error [JniSupport] Missing native symbol: Java_com_mojang_minecraftpe_MainActivity_nativeUnregisterThis
13:12:40 Error [JniSupport] Missing native symbol: Java_com_microsoft_xal_browser_WebView_urlOperationSucceeded
13:12:40 Info  [Launcher] Executing main thread
13:12:40 Trace [Minecraft] Entering JNI_OnLoad 0x7f15278ff640
13:12:40 Trace [Minecraft] JNI_OnLoad completed
13:12:40 Trace [JniSupport] Invoking nativeRegisterThis
13:12:40 Trace [JniSupport] Invoking ANativeActivity_onCreate
13:12:40 Warn  [Main] Android stub called
13:12:40 Warn  [Main] Android stub called
13:12:40 Warn  [Main] Android stub called
13:12:40 Warn  [Main] Android stub called
13:12:40 Info  [Launcher] Loading gamepad mappings
13:12:40 Trace [Launcher] Loading gamepad mappings: /app/share/mcpelauncher/gamecontrollerdb.txt
13:12:40 Trace [Launcher] Loading gamepad mappings: /app/share/mcpelauncher/gamecontrollerdb.txt
13:12:40 Info  [Launcher] Creating window
13:12:40 Info  [Minecraft] android_main starting. internalDataPath is '/internal', externalDataPath is '/external'
13:12:40 Trace [JniSupport] Invoking start activity callbacks
13:12:40 Error [MCPE] *** setCachedDeviceId(b5f51049-5f4d-4a1b-8a5c-fed39a1f0247)
13:12:40 Info  [Bedrock] configureBreakpad with directory: /crash, sessionid is: 832bccf7-635c-4e0f-ab25-4b0476fe5104
13:12:40 Info  [Bedrock] configureBreakpad called, directory is: /crash, sessionid is: 832bccf7-635c-4e0f-ab25-4b0476fe5104
13:12:40 Info  [Minecraft] NO LOG FILE! - [] AppPlatform_android::setStorageDirectory - using External dir - CurrentFileStoragePath is now '/home/sa6ta6ni6c/.var/app/io.mrarm.mcpelauncher/data/mcpelauncher/'
13:12:41 Warn  [Main] Android stub called
13:12:41 Warn  [Main] Android stub called
13:12:41 Warn  [Minecraft] NO LOG FILE! - [] [Device Lost] The graphics context was gained
13:12:41 Warn  [Minecraft] MinecraftGame::init && MinecraftGame::setSize!
13:12:41 Debug [HttpCallStaticGlue] Successfully registerered HttpCall methods
13:12:41 Debug [XboxLiveAppConfig] Successfully registerered XboxLiveAppConfig methods
13:12:41 Debug [XSAPI.Android] Successfully registerered HttpCall tcuiMethods
13:12:41 Debug [XSAPI.Android] Successfully registerered telemetryMethods
13:13:32 Info  [Minecraft] NO LOG FILE! - [] opening /home/sa6ta6ni6c/.var/app/io.mrarm.mcpelauncher/data/mcpelauncher/minecraftpe/blob_cache
13:13:46 Info  [Minecraft] NO LOG FILE! - [] opening /home/sa6ta6ni6c/.var/app/io.mrarm.mcpelauncher/data/mcpelauncher/minecraftpe/blob_cache

Process exited with unexpected exit code: 9

**Comment by sa6ta6ni6c** [comment]
Note: always happens, when im trying to break something in the water

**Comment by tassaron** [comment]
In my experience, breaking something in water while standing in water has the chance to set your player's position variable to NaN which makes any client crash upon logging in. The only way I could fix is writing some Python code to restore my player data to a backup (script is in a repo on my profile). The easier solution is to restore a backup of the entire world including player data.

In future, you must do this unstable activity on an official client to avoid corrupting any data. Sorry but that's what happens with an unofficial client :(

**Comment by sa6ta6ni6c** [comment]
FIxed it by joining servers from my phone
