### ISSUE TITLE
Not really an issue, but ray tracing works?

### ISSUE THREAD

**Issue by rsmwall** [minecraft-linux/mcpelauncher-manifest#643]
I'm building a PC and plan to stop using Windows in time, but I would like to continue playing Minecraft Bedrock, I would like to know if Ray Tracing works if the person has an RTX graphics card in the launcher or this function will only be enabled using the version original on Windows.

**Comment by ghost** [comment]
No it won't work for many reasons but the main one is that it is running the android versions gsl engin and not the windows 10 render dragonengin

**Comment by zERO123331** [comment]
will they add the renderdragon eninge to mobile?
and if yes will you then be able to use rtx?

**Comment by yllekz** [comment]
> will they add the renderdragon eninge to mobile? and if yes will you then be able to use rtx?

To be clear, this is not an official Mojang product, and if it's not in the Android version, you won't find it here. You'll have to look out for news on feature updates to the Android version of Minecraft if you want to see this, and it won't come from this repo.
