### ISSUE TITLE
Launcher exits with code 6 while playing

### ISSUE THREAD

**Issue by lbirkert** [minecraft-linux/mcpelauncher-manifest#652]
**Describe the bug**
Launcher terminates itself with code 6 probably caused by playing in fullscreen mode.

**Expected behavior**
Not crashing.

**Log**
```
terminating with uncaught exception of type std::__ndk1::system_error: mutex lock failed: +��c�
abort message: terminating with uncaught exception of type std::__ndk1::system_error: mutex lock failed: +��c�
Signal 6 received
Backtrace elements: 5
#0 /app/bin/mcpelauncher-client(_ZN12CrashHandler12handleSignalEiPv+0x165) [0x635165]
#1 /usr/lib/x86_64-linux-gnu/libpthread.so.0(+0x12e60) [0x7fa3c91dfe60]
#2 /usr/lib/x86_64-linux-gnu/libc.so.6(gsignal+0x10b) [0x7fa3c8b554bb]
#3 /usr/lib/x86_64-linux-gnu/libc.so.6(abort+0x11e) [0x7fa3c8b3e867]
#4 LINKER (null)+0x7fa3c792508c in /home/kek/.var/app/io.mrarm.mcpelauncher/data/mcpelauncher/versions/1.18.2.03/lib/x86_64/libc++_shared.so+0x0xa508c [0x0x7fa3c792508c]
Dumping stack...
#5 LINKER (null)+0x7fa3c792508c in /home/kek/.var/app/io.mrarm.mcpelauncher/data/mcpelauncher/versions/1.18.2.03/lib/x86_64/libc++_shared.so+0x0xa508c [0x0x7fa3c792508c]
#6 LINKER (null)+0x7fa3c793b3a8 in /home/kek/.var/app/io.mrarm.mcpelauncher/data/mcpelauncher/versions/1.18.2.03/lib/x86_64/libc++_shared.so+0x0xbb3a8 [0x0x7fa3c793b3a8]
#13 LINKER (null)+0x7fa3bee40e06 in /home/kek/.var/app/io.mrarm.mcpelauncher/data/mcpelauncher/versions/1.18.2.03/lib/x86_64/libminecraftpe.so+0x0x25c0e06 [0x0x7fa3bee40e06]
#14 LINKER (null)+0x7fa3bee40df4 in /home/kek/.var/app/io.mrarm.mcpelauncher/data/mcpelauncher/versions/1.18.2.03/lib/x86_64/libminecraftpe.so+0x0x25c0df4 [0x0x7fa3bee40df4]
#15 LINKER (null)+0x7fa3c086d230 in /home/kek/.var/app/io.mrarm.mcpelauncher/data/mcpelauncher/versions/1.18.2.03/lib/x86_64/libminecraftpe.so+0x0x3fed230 [0x0x7fa3c086d230]
#19 LINKER (null)+0x7fa3bee40df9 in /home/kek/.var/app/io.mrarm.mcpelauncher/data/mcpelauncher/versions/1.18.2.03/lib/x86_64/libminecraftpe.so+0x0x25c0df9 [0x0x7fa3bee40df9]
#21 LINKER (null)+0x7fa3c000acad in /home/kek/.var/app/io.mrarm.mcpelauncher/data/mcpelauncher/versions/1.18.2.03/lib/x86_64/libminecraftpe.so+0x0x378acad [0x0x7fa3c000acad]
#22 LINKER (null)+0x7fa3c000ac98 in /home/kek/.var/app/io.mrarm.mcpelauncher/data/mcpelauncher/versions/1.18.2.03/lib/x86_64/libminecraftpe.so+0x0x378ac98 [0x0x7fa3c000ac98]
#30 LINKER (null)+0x7fa3bffed502 in /home/kek/.var/app/io.mrarm.mcpelauncher/data/mcpelauncher/versions/1.18.2.03/lib/x86_64/libminecraftpe.so+0x0x376d502 [0x0x7fa3bffed502]
#32 LINKER (null)+0x7fa3c0012280 in /home/kek/.var/app/io.mrarm.mcpelauncher/data/mcpelauncher/versions/1.18.2.03/lib/x86_64/libminecraftpe.so+0x0x3792280 [0x0x7fa3c0012280]
#34 LINKER (null)+0x7fa3bffed502 in /home/kek/.var/app/io.mrarm.mcpelauncher/data/mcpelauncher/versions/1.18.2.03/lib/x86_64/libminecraftpe.so+0x0x376d502 [0x0x7fa3bffed502]
#49 LINKER (null)+0x7fa3c7943200 in /home/kek/.var/app/io.mrarm.mcpelauncher/data/mcpelauncher/versions/1.18.2.03/lib/x86_64/libc++_shared.so+0x0xc3200 [0x0x7fa3c7943200]
#64 LINKER (null)+0x7fa3c7943200 in /home/kek/.var/app/io.mrarm.mcpelauncher/data/mcpelauncher/versions/1.18.2.03/lib/x86_64/libc++_shared.so+0x0xc3200 [0x0x7fa3c7943200]
#83 LINKER (null)+0x7fa3c7880000 in /home/kek/.var/app/io.mrarm.mcpelauncher/data/mcpelauncher/versions/1.18.2.03/lib/x86_64/libc++_shared.so+0x(nil) [0x0x7fa3c7880000]
#91 LINKER (null)+0x7fa3c79431ff in /home/kek/.var/app/io.mrarm.mcpelauncher/data/mcpelauncher/versions/1.18.2.03/lib/x86_64/libc++_shared.so+0x0xc31ff [0x0x7fa3c79431ff]
#98 LINKER (null)+0x7fa3c001ae40 in /home/kek/.var/app/io.mrarm.mcpelauncher/data/mcpelauncher/versions/1.18.2.03/lib/x86_64/libminecraftpe.so+0x0x379ae40 [0x0x7fa3c001ae40]
#102 LINKER (null)+0x7fa3c7943211 in /home/kek/.var/app/io.mrarm.mcpelauncher/data/mcpelauncher/versions/1.18.2.03/lib/x86_64/libc++_shared.so+0x0xc3211 [0x0x7fa3c7943211]
#162 LINKER (null)+0x7fa3c6cda048 in /home/kek/.var/app/io.mrarm.mcpelauncher/data/mcpelauncher/versions/1.18.2.03/lib/x86_64/libminecraftpe.so+0x0xa45a048 [0x0x7fa3c6cda048]
#165 LINKER (null)+0x7fa3bf2a26c4 in /home/kek/.var/app/io.mrarm.mcpelauncher/data/mcpelauncher/versions/1.18.2.03/lib/x86_64/libminecraftpe.so+0x0x2a226c4 [0x0x7fa3bf2a26c4]
#219 LINKER (null)+0x7fa3c79431fd in /home/kek/.var/app/io.mrarm.mcpelauncher/data/mcpelauncher/versions/1.18.2.03/lib/x86_64/libc++_shared.so+0x0xc31fd [0x0x7fa3c79431fd]
#225 LINKER (null)+0x7fa3c79431fd in /home/kek/.var/app/io.mrarm.mcpelauncher/data/mcpelauncher/versions/1.18.2.03/lib/x86_64/libc++_shared.so+0x0xc31fd [0x0x7fa3c79431fd]
#231 LINKER (null)+0x7fa3c79431fd in /home/kek/.var/app/io.mrarm.mcpelauncher/data/mcpelauncher/versions/1.18.2.03/lib/x86_64/libc++_shared.so+0x0xc31fd [0x0x7fa3c79431fd]
#277 LINKER (null)+0x7fa3c7943200 in /home/kek/.var/app/io.mrarm.mcpelauncher/data/mcpelauncher/versions/1.18.2.03/lib/x86_64/libc++_shared.so+0x0xc3200 [0x0x7fa3c7943200]
#297 LINKER (null)+0x7fa3c79431f3 in /home/kek/.var/app/io.mrarm.mcpelauncher/data/mcpelauncher/versions/1.18.2.03/lib/x86_64/libc++_shared.so+0x0xc31f3 [0x0x7fa3c79431f3]
#308 LINKER (null)+0x7fa3c792508c in /home/kek/.var/app/io.mrarm.mcpelauncher/data/mcpelauncher/versions/1.18.2.03/lib/x86_64/libc++_shared.so+0x0xa508c [0x0x7fa3c792508c]
#309 LINKER (null)+0x7fa3c793dcc0 in /home/kek/.var/app/io.mrarm.mcpelauncher/data/mcpelauncher/versions/1.18.2.03/lib/x86_64/libc++_shared.so+0x0xbdcc0 [0x0x7fa3c793dcc0]
#318 LINKER typeinfo for std::__ndk1::system_error+(nil) in /home/kek/.var/app/io.mrarm.mcpelauncher/data/mcpelauncher/versions/1.18.2.03/lib/x86_64/libc++_shared.so+0x0xecd80 [0x0x7fa3c796cd80]
#319 LINKER typeinfo for __cxxabiv1::__shim_type_info+(nil) in /home/kek/.var/app/io.mrarm.mcpelauncher/data/mcpelauncher/versions/1.18.2.03/lib/x86_64/libc++_shared.so+0x0xeecd8 [0x0x7fa3c796ecd8]
#320 LINKER (null)+0x7fa3c7943288 in /home/kek/.var/app/io.mrarm.mcpelauncher/data/mcpelauncher/versions/1.18.2.03/lib/x86_64/libc++_shared.so+0x0xc3288 [0x0x7fa3c7943288]
#323 LINKER typeinfo for std::exception+(nil) in /home/kek/.var/app/io.mrarm.mcpelauncher/data/mcpelauncher/versions/1.18.2.03/lib/x86_64/libc++_shared.so+0x0xef888 [0x0x7fa3c796f888]
#328 LINKER typeinfo for std::exception+(nil) in /home/kek/.var/app/io.mrarm.mcpelauncher/data/mcpelauncher/versions/1.18.2.03/lib/x86_64/libc++_shared.so+0x0xef888 [0x0x7fa3c796f888]
#330 LINKER (null)+0x7fa3c793ce0a in /home/kek/.var/app/io.mrarm.mcpelauncher/data/mcpelauncher/versions/1.18.2.03/lib/x86_64/libc++_shared.so+0x0xbce0a [0x0x7fa3c793ce0a]
#332 LINKER typeinfo for std::__ndk1::system_error+(nil) in /home/kek/.var/app/io.mrarm.mcpelauncher/data/mcpelauncher/versions/1.18.2.03/lib/x86_64/libc++_shared.so+0x0xecd80 [0x0x7fa3c796cd80]
#334 LINKER typeinfo for std::exception+(nil) in /home/kek/.var/app/io.mrarm.mcpelauncher/data/mcpelauncher/versions/1.18.2.03/lib/x86_64/libc++_shared.so+0x0xef888 [0x0x7fa3c796f888]
#341 LINKER (null)+0x7fa3c7943288 in /home/kek/.var/app/io.mrarm.mcpelauncher/data/mcpelauncher/versions/1.18.2.03/lib/x86_64/libc++_shared.so+0x0xc3288 [0x0x7fa3c7943288]
#346 LINKER (null)+0x7fa3c792524e in /home/kek/.var/app/io.mrarm.mcpelauncher/data/mcpelauncher/versions/1.18.2.03/lib/x86_64/libc++_shared.so+0x0xa524e [0x0x7fa3c792524e]
#366 LINKER (null)+0x7fa3c794023d in /home/kek/.var/app/io.mrarm.mcpelauncher/data/mcpelauncher/versions/1.18.2.03/lib/x86_64/libc++_shared.so+0x0xc023d [0x0x7fa3c794023d]
#386 LINKER (null)+0x51 in /home/kek/.var/app/io.mrarm.mcpelauncher/data/mcpelauncher/versions/1.18.2.03/lib/x86_64/libc++_shared.so+0x0xba8d1 [0x0x7fa3c793a8d1]
#390 LINKER (null)+0x7fa3c79401e2 in /home/kek/.var/app/io.mrarm.mcpelauncher/data/mcpelauncher/versions/1.18.2.03/lib/x86_64/libc++_shared.so+0x0xc01e2 [0x0x7fa3c79401e2]
#420 LINKER crossplat::threadpool::thread_start(void*)+(nil) in /home/kek/.var/app/io.mrarm.mcpelauncher/data/mcpelauncher/versions/1.18.2.03/lib/x86_64/libminecraftpe.so+0x0x3dabb50 [0x0x7fa3c062bb50]
#476 LINKER (null)+0x7fa3c7974efc in /home/kek/.var/app/io.mrarm.mcpelauncher/data/mcpelauncher/versions/1.18.2.03/lib/x86_64/libc++_shared.so+0x0xf4efc [0x0x7fa3c7974efc]
#482 LINKER (null)+0x7fa3c793afa3 in /home/kek/.var/app/io.mrarm.mcpelauncher/data/mcpelauncher/versions/1.18.2.03/lib/x86_64/libc++_shared.so+0x0xbafa3 [0x0x7fa3c793afa3]
#484 LINKER (null)+0x9d in /home/kek/.var/app/io.mrarm.mcpelauncher/data/mcpelauncher/versions/1.18.2.03/lib/x86_64/libc++_shared.so+0x0xba91d [0x0x7fa3c793a91d]
#485 LINKER (null)+0x7fa3c6d0c3c0 in /home/kek/.var/app/io.mrarm.mcpelauncher/data/mcpelauncher/versions/1.18.2.03/lib/x86_64/libminecraftpe.so+0x0xa48c3c0 [0x0x7fa3c6d0c3c0]
#490 LINKER crossplat::threadpool::thread_start(void*)+0x126 in /home/kek/.var/app/io.mrarm.mcpelauncher/data/mcpelauncher/versions/1.18.2.03/lib/x86_64/libminecraftpe.so+0x0x3dabc76 [0x0x7fa3c062bc76]
#492 LINKER (null)+0x7fa3c6719918 in /home/kek/.var/app/io.mrarm.mcpelauncher/data/mcpelauncher/versions/1.18.2.03/lib/x86_64/libminecraftpe.so+0x0x9e99918 [0x0x7fa3c6719918]
#504 LINKER crossplat::threadpool::detach_from_java(void*)+(nil) in /home/kek/.var/app/io.mrarm.mcpelauncher/data/mcpelauncher/versions/1.18.2.03/lib/x86_64/libminecraftpe.so+0x0x3dabc90 [0x0x7fa3c062bc90]
Why does some people think exit code 6 is meaningful? It is just a unix signal number.

Process exited with unexpected exit code: 6
```

**Comment by LPS13** [comment]
also having similar failure. occurs at about 77% of loading after pressing play.
using a  raspberry Pi3B+ running bash/raspian Linux raspberrypi 5.10.63-v7+ #1496 SMP Wed Dec 1 15:58:11 GMT 2021 armv7l GNU/Linux

noteworthy items in the log are several warnings and an error that said "stack corruption detected"
and a seemingly "smart-remark" in the stack-dump about a code 6
is that the "corruption" that was detected? perhaps the download image was faulty? hacked?
this was installed via pi-apps. re-installation produces identical results.

here is the log...

`
11:22:12 Info  [Launcher] Version: client 1e44372 / manifest 1da5aa2
11:22:12 Trace [Launcher] Loading hybris libraries
11:22:12 Trace [REDIRECT] /data/data/com.mojang.minecraftpe to /home/pi/.local/share/mcpelauncher/
11:22:12 Trace [REDIRECT] /data/data/tmp/.mount_MCBedr5I9ywg/usr/proc/12068/cmdline to /home/pi/.local/share/mcpelauncher/
11:22:12 Trace [REDIRECT] /data/data/tmp/.mount_MCBedr5I9ywg/usr/bin/./mcpelauncher-client to /home/pi/.local/share/mcpelauncher/
11:22:12 Trace [REDIRECT] /data/data to /home/pi/.local/share/mcpelauncher/
11:22:13 Trace [LinkerUtils] Loaded OS library libz.so.1
11:22:13 Warn  [FMOD] Failed to load host libfmod: 'Failed to find data file: lib/native/armeabi-v7a/libfmod.so.10.20', use experimental pulseaudio backend if available
11:22:13 Trace [Launcher] Loading Minecraft library
Found hook: _Znaj @ 0x671a20
Found hook: _Znwj @ 0x672078
Found hook: _ZnwjSt11align_val_t @ 0x673ae4
Found hook: OPENSSL_cpuid_setup @ 0x888f2c
Found hook: _ZN11AppPlatform16showMousePointerEv @ 0x8671c0
Found hook: _ZN11AppPlatform16hideMousePointerEv @ 0x867194
11:22:17 Info  [Launcher] Loaded Minecraft library
11:22:17 Debug [Launcher] Minecraft is at offset 0x0x69980000
11:22:17 Info  [Launcher] Game version: 0.0.0.0
11:22:17 Info  [Launcher] Applying patches
11:22:17 Debug [CorePatches] Failed to patch, vtable _ZTV21AppPlatform_android23 not found
11:22:17 Info  [Launcher] Initializing JNI
11:22:18 Error [JniSupport] Missing native symbol: Java_com_mojang_minecraftpe_MainActivity_nativeRegisterThis
11:22:18 Error [JniSupport] Missing native symbol: Java_com_mojang_minecraftpe_MainActivity_nativeUnregisterThis
11:22:18 Error [JniSupport] Missing native symbol: Java_com_microsoft_xal_browser_WebView_urlOperationSucceeded
11:22:18 Info  [Launcher] Executing main thread
11:22:18 Trace [Minecraft] Entering JNI_OnLoad 0x708bef40
11:22:18 Trace [Minecraft] JNI_OnLoad completed
11:22:18 Trace [JniSupport] Invoking nativeRegisterThis
11:22:18 Trace [JniSupport] Invoking ANativeActivity_onCreate
11:22:18 Warn  [Main] Android stub called
11:22:18 Warn  [Main] Android stub called
11:22:18 Warn  [Main] Android stub called
11:22:18 Warn  [Main] Android stub called
11:22:18 Info  [Launcher] Loading gamepad mappings
11:22:18 Trace [Launcher] Loading gamepad mappings: /tmp/.mount_MCBedr5I9ywg/usr/share/mcpelauncher/gamecontrollerdb.txt
11:22:18 Info  [Launcher] Creating window
11:22:18 Info  [Minecraft] android_main starting. internalDataPath is '/internal', externalDataPath is '/external'
11:22:18 Trace [JniSupport] Invoking start activity callbacks
11:22:18 Error [MCPE] *** setCachedDeviceId(b6c4564b-63c9-460c-8673-b08cb7267d86)
11:22:18 Info  [Bedrock] configureBreakpad with directory: /crash, sessionid is: 719c572a-5581-460f-94f8-f637acc90055
11:22:18 Info  [Bedrock] configureBreakpad called, directory is: /crash, sessionid is: 719c572a-5581-460f-94f8-f637acc90055
11:22:18 Info  [Minecraft] NO LOG FILE! - AppPlatform_android::setStorageDirectory - using External dir (NEW) - CurrentFileStoragePath is now '/home/pi/.local/share/mcpelauncher/'
11:22:18 Warn  [Main] Android stub called
11:22:19 Warn  [Minecraft] NO LOG FILE! - [Device Lost] The graphics context was gained
11:22:19 Warn  [Minecraft] MinecraftGame::init && MinecraftGame::setSize!
11:22:23 Debug [HttpCallStaticGlue] Successfully registerered HttpCall methods
11:22:23 Debug [XboxLiveAppConfig] Successfully registerered XboxLiveAppConfig methods
11:22:23 Debug [XSAPI.Android] Successfully registerered HttpCall tcuiMethods
11:22:23 Debug [XSAPI.Android] Successfully registerered telemetryMethods
stack corruption has been detected
Signal 6 received
Backtrace elements: 2
#0 /tmp/.mount_MCBedr5I9ywg/usr/bin/./mcpelauncher-client(_ZN12CrashHandler12handleSignalEiPv+0x140) [0x884eb4]
#1 /lib/arm-linux-gnueabihf/libc.so.6(__default_sa_restorer+0) [0x7677b110]
Dumping stack...
#35 LINKER std::__ndk1::recursive_mutex::unlock()+0x8 in /home/pi/.local/share/mcpelauncher/versions/1.18.12.01/lib/armeabi-v7a/libc++_shared.so+0x0x5e39d [0x0x697de39d]
#57 LINKER (null)+0x6c1e30b7 in /home/pi/.local/share/mcpelauncher/versions/1.18.12.01/lib/armeabi-v7a/libminecraftpe.so+0x0x28630b7 [0x0x6c1e30b7]
#63 LINKER (null)+0x6c1e335d in /home/pi/.local/share/mcpelauncher/versions/1.18.12.01/lib/armeabi-v7a/libminecraftpe.so+0x0x286335d [0x0x6c1e335d]
#100 LINKER (null)+0x6d657469 in /home/pi/.local/share/mcpelauncher/versions/1.18.12.01/lib/armeabi-v7a/libminecraftpe.so+0x0x3cd7469 [0x0x6d657469]
#108 LINKER (null)+0x6d657469 in /home/pi/.local/share/mcpelauncher/versions/1.18.12.01/lib/armeabi-v7a/libminecraftpe.so+0x0x3cd7469 [0x0x6d657469]
#116 LINKER Scripting::GenericModuleBindingFactory::GenericModuleBindingFactory(std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >, Scripting::UUID)+0x2 in /home/pi/.local/share/mcpelauncher/versions/1.18.12.01/lib/armeabi-v7a/libminecraftpe.so+0x0x5db6567 [0x0x6f736567]
#124 LINKER Scripting::GenericModuleBindingFactory::GenericModuleBindingFactory(std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >, Scripting::UUID)+0x2 in /home/pi/.local/share/mcpelauncher/versions/1.18.12.01/lib/armeabi-v7a/libminecraftpe.so+0x0x5db6567 [0x0x6f736567]
#157 LINKER (null)+0x6c9a3ad1 in /home/pi/.local/share/mcpelauncher/versions/1.18.12.01/lib/armeabi-v7a/libminecraftpe.so+0x0x3023ad1 [0x0x6c9a3ad1]
#160 LINKER (null)+0x6c9a3ae7 in /home/pi/.local/share/mcpelauncher/versions/1.18.12.01/lib/armeabi-v7a/libminecraftpe.so+0x0x3023ae7 [0x0x6c9a3ae7]
#179 LINKER (null)+(nil) in /home/pi/.local/share/mcpelauncher/versions/1.18.12.01/lib/armeabi-v7a/libminecraftpe.so+0x0x5e7e451 [0x0x6f7fe451]
#180 LINKER (null)+(nil) in /home/pi/.local/share/mcpelauncher/versions/1.18.12.01/lib/armeabi-v7a/libminecraftpe.so+0x0x5e7e499 [0x0x6f7fe499]
#341 LINKER (null)+0x6c9a3abd in /home/pi/.local/share/mcpelauncher/versions/1.18.12.01/lib/armeabi-v7a/libminecraftpe.so+0x0x3023abd [0x0x6c9a3abd]
#423 LINKER (null)+0x6c9a3b43 in /home/pi/.local/share/mcpelauncher/versions/1.18.12.01/lib/armeabi-v7a/libminecraftpe.so+0x0x3023b43 [0x0x6c9a3b43]
#424 LINKER (null)+0x6f926cf4 in /home/pi/.local/share/mcpelauncher/versions/1.18.12.01/lib/armeabi-v7a/libminecraftpe.so+0x0x5fa6cf4 [0x0x6f926cf4]
#426 LINKER (null)+0x6f926d08 in /home/pi/.local/share/mcpelauncher/versions/1.18.12.01/lib/armeabi-v7a/libminecraftpe.so+0x0x5fa6d08 [0x0x6f926d08]
#427 LINKER (null)+0x6dbb66a5 in /home/pi/.local/share/mcpelauncher/versions/1.18.12.01/lib/armeabi-v7a/libminecraftpe.so+0x0x42366a5 [0x0x6dbb66a5]
#428 LINKER vtable for Core::FileStdStreamBuf+0x8 in /home/pi/.local/share/mcpelauncher/versions/1.18.12.01/lib/armeabi-v7a/libminecraftpe.so+0x0x5fa82f8 [0x0x6f9282f8]
#429 LINKER (null)+0x69809310 in /home/pi/.local/share/mcpelauncher/versions/1.18.12.01/lib/armeabi-v7a/libc++_shared.so+0x0x89310 [0x0x69809310]
#445 LINKER (null)+0x6f926d1c in /home/pi/.local/share/mcpelauncher/versions/1.18.12.01/lib/armeabi-v7a/libminecraftpe.so+0x0x5fa6d1c [0x0x6f926d1c]
#452 LINKER (null)+0x69809310 in /home/pi/.local/share/mcpelauncher/versions/1.18.12.01/lib/armeabi-v7a/libc++_shared.so+0x0x89310 [0x0x69809310]
#471 LINKER (null)+0x6dbb912b in /home/pi/.local/share/mcpelauncher/versions/1.18.12.01/lib/armeabi-v7a/libminecraftpe.so+0x0x423912b [0x0x6dbb912b]
#485 LINKER (null)+0x6c34ab9d in /home/pi/.local/share/mcpelauncher/versions/1.18.12.01/lib/armeabi-v7a/libminecraftpe.so+0x0x29cab9d [0x0x6c34ab9d]
#489 LINKER (null)+0x6c34ab85 in /home/pi/.local/share/mcpelauncher/versions/1.18.12.01/lib/armeabi-v7a/libminecraftpe.so+0x0x29cab85 [0x0x6c34ab85]
#493 LINKER mce::BlobHelper::resize(mce::Blob&, unsigned int)+0x52 in /home/pi/.local/share/mcpelauncher/versions/1.18.12.01/lib/armeabi-v7a/libminecraftpe.so+0x0x29ca8db [0x0x6c34a8db]
#495 LINKER mce::Blob::defaultDeleter(unsigned char*)+(nil) in /home/pi/.local/share/mcpelauncher/versions/1.18.12.01/lib/armeabi-v7a/libminecraftpe.so+0x0x29caad9 [0x0x6c34aad9]
#501 LINKER (null)+0x28 in /tmp/.mount_MCBedr5I9ywg/usr/share/mcpelauncher/lib/armeabi-v7a/libc.so+0x0xec8 [0x0x70900ec8]
#507 LINKER (null)+0x6c1e1a49 in /home/pi/.local/share/mcpelauncher/versions/1.18.12.01/lib/armeabi-v7a/libminecraftpe.so+0x0x2861a49 [0x0x6c1e1a49]
#511 LINKER (null)+0x6c1e30b7 in /home/pi/.local/share/mcpelauncher/versions/1.18.12.01/lib/armeabi-v7a/libminecraftpe.so+0x0x28630b7 [0x0x6c1e30b7]
#517 LINKER (null)+0x6c1e335d in /home/pi/.local/share/mcpelauncher/versions/1.18.12.01/lib/armeabi-v7a/libminecraftpe.so+0x0x286335d [0x0x6c1e335d]
#521 LINKER (null)+0x6c1e3437 in /home/pi/.local/share/mcpelauncher/versions/1.18.12.01/lib/armeabi-v7a/libminecraftpe.so+0x0x2863437 [0x0x6c1e3437]
#537 LINKER (null)+0x6dbb86c3 in /home/pi/.local/share/mcpelauncher/versions/1.18.12.01/lib/armeabi-v7a/libminecraftpe.so+0x0x42386c3 [0x0x6dbb86c3]
#544 LINKER (null)+0x6c1c2cc5 in /home/pi/.local/share/mcpelauncher/versions/1.18.12.01/lib/armeabi-v7a/libminecraftpe.so+0x0x2842cc5 [0x0x6c1c2cc5]
#550 LINKER renoir::ThirdParty::stbi_zlib_decode_malloc_guesssize_headerflag(char const*, int, int, int*, int)+0x5d in /home/pi/.local/share/mcpelauncher/versions/1.18.12.01/lib/armeabi-v7a/libminecraftpe.so+0x0x4d12e0a [0x0x6e692e0a]
#561 LINKER cohtml::dom::Document::OnNewStylesheet(cohtml::dom::Node*, cohtml::IntrusivePtr<cohtml::css::ParsedStylesheet, cohtml::TaggedStdAllocator<cohtml::css::ParsedStylesheet, (cohtml::MemTags::MemTagsType)8> >&, csl::dyn_array_vector<cohtml::css::MediaExpression, cohtml::TaggedStdAllocator<cohtml::css::MediaExpression, (cohtml::MemTags::MemTagsType)8> >*)+0x1733 in /home/pi/.local/share/mcpelauncher/versions/1.18.12.01/lib/armeabi-v7a/libminecraftpe.so+0x0x4d82e08 [0x0x6e702e08]
#592 LINKER (null)+0x6fc6616c in /home/pi/.local/share/mcpelauncher/versions/1.18.12.01/lib/armeabi-v7a/libminecraftpe.so+0x0x62e616c [0x0x6fc6616c]
Why does some people think exit code 6 is meaningful? It is just a unix signal number.

Process exited with unexpected exit code: 6
`
