### ISSUE TITLE
Invisible Rain/Snow

### ISSUE THREAD

**Issue by xPanosGRx** [minecraft-linux/mcpelauncher-manifest#653]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Linux, macOS]
 - Version [e.g. v0.3.0-AppImage-x86_64-0.0.677 (build 677)]
 - Installation Type [e.g. AppImage, flatpak, dmg or built from source]

Not supported is a similar looking app in the snap store.

**Additional context**

**Comment by xPanosGRx** [comment]
Hello there @ChristopherHX. Ive noticed a bug during exploring one of my worlds and that is invisible rain and snow.
Neither the rain nor the snow appear when its raining/snowing. I hope this is fixable and if you know how to fix that maybe you could consider to. Thanks i will let you know if i see any other bugs but i would be very glad if you fix this one!!!

**Comment by ChristopherHX** [comment]
That's not how it works.You mentioned me more that 2 time, without any valid reason.
You had luck that Mojang fixed it in 1.18.10.

**Comment by xPanosGRx** [comment]
Ok sorry i didnt know
