### ISSUE TITLE
CPU Intel i5 2400

### ISSUE THREAD

**Issue by N0aah02** [minecraft-linux/mcpelauncher-manifest#657]
**CPU/GPU Bug on Window Creation**

**Expected behavior**
I was hoping to be able to play, I'm currently also making my own server on which I urgently need to be online ingame!

**Screenshots**
![MCPE-ErrorCode11](https://user-images.githubusercontent.com/82420028/152549008-e1a1ecd7-69f9-4b84-870c-123e849776fe.gif)

**PC Information:**
 - OS: [Ubuntu 20.04 LTS (Focal Fossa)]
 - Version [v0.3.2-flatpak-amd64 (build 34)]
 - Installation Type [Flatpak]

**Comment by ChristopherHX** [comment]
Screenshots / gifs of launcher logs are useless, please copy it into a codeblock. There is a copy button in the error window.
