### ISSUE TITLE
code 6 failure while loading. also having similar failure. occurs at about 77% of loading after pressing play.

### ISSUE THREAD

**Issue by LPS13** [minecraft-linux/mcpelauncher-manifest#665]
also having similar failure. occurs at about 77% of loading after pressing play.
using a  raspberry Pi3B+ running bash/raspian Linux raspberrypi 5.10.63-v7+ #1496 SMP Wed Dec 1 15:58:11 GMT 2021 armv7l GNU/Linux

noteworthy items in the log are several warnings and an error that said "stack corruption detected"
and a seemingly "smart-remark" in the stack-dump about a code 6
is that the "corruption" that was detected? perhaps the download image was faulty? hacked?
this was installed via pi-apps. re-installation produces identical results.

here is the log...

`
11:22:12 Info  [Launcher] Version: client 1e44372 / manifest 1da5aa2
11:22:12 Trace [Launcher] Loading hybris libraries
11:22:12 Trace [REDIRECT] /data/data/com.mojang.minecraftpe to /home/pi/.local/share/mcpelauncher/
11:22:12 Trace [REDIRECT] /data/data/tmp/.mount_MCBedr5I9ywg/usr/proc/12068/cmdline to /home/pi/.local/share/mcpelauncher/
11:22:12 Trace [REDIRECT] /data/data/tmp/.mount_MCBedr5I9ywg/usr/bin/./mcpelauncher-client to /home/pi/.local/share/mcpelauncher/
11:22:12 Trace [REDIRECT] /data/data to /home/pi/.local/share/mcpelauncher/
11:22:13 Trace [LinkerUtils] Loaded OS library libz.so.1
11:22:13 Warn  [FMOD] Failed to load host libfmod: 'Failed to find data file: lib/native/armeabi-v7a/libfmod.so.10.20', use experimental pulseaudio backend if available
11:22:13 Trace [Launcher] Loading Minecraft library
Found hook: _Znaj @ 0x671a20
Found hook: _Znwj @ 0x672078
Found hook: _ZnwjSt11align_val_t @ 0x673ae4
Found hook: OPENSSL_cpuid_setup @ 0x888f2c
Found hook: _ZN11AppPlatform16showMousePointerEv @ 0x8671c0
Found hook: _ZN11AppPlatform16hideMousePointerEv @ 0x867194
11:22:17 Info  [Launcher] Loaded Minecraft library
11:22:17 Debug [Launcher] Minecraft is at offset 0x0x69980000
11:22:17 Info  [Launcher] Game version: 0.0.0.0
11:22:17 Info  [Launcher] Applying patches
11:22:17 Debug [CorePatches] Failed to patch, vtable _ZTV21AppPlatform_android23 not found
11:22:17 Info  [Launcher] Initializing JNI
11:22:18 Error [JniSupport] Missing native symbol: Java_com_mojang_minecraftpe_MainActivity_nativeRegisterThis
11:22:18 Error [JniSupport] Missing native symbol: Java_com_mojang_minecraftpe_MainActivity_nativeUnregisterThis
11:22:18 Error [JniSupport] Missing native symbol: Java_com_microsoft_xal_browser_WebView_urlOperationSucceeded
11:22:18 Info  [Launcher] Executing main thread
11:22:18 Trace [Minecraft] Entering JNI_OnLoad 0x708bef40
11:22:18 Trace [Minecraft] JNI_OnLoad completed
11:22:18 Trace [JniSupport] Invoking nativeRegisterThis
11:22:18 Trace [JniSupport] Invoking ANativeActivity_onCreate
11:22:18 Warn  [Main] Android stub called
11:22:18 Warn  [Main] Android stub called
11:22:18 Warn  [Main] Android stub called
11:22:18 Warn  [Main] Android stub called
11:22:18 Info  [Launcher] Loading gamepad mappings
11:22:18 Trace [Launcher] Loading gamepad mappings: /tmp/.mount_MCBedr5I9ywg/usr/share/mcpelauncher/gamecontrollerdb.txt
11:22:18 Info  [Launcher] Creating window
11:22:18 Info  [Minecraft] android_main starting. internalDataPath is '/internal', externalDataPath is '/external'
11:22:18 Trace [JniSupport] Invoking start activity callbacks
11:22:18 Error [MCPE] *** setCachedDeviceId(b6c4564b-63c9-460c-8673-b08cb7267d86)
11:22:18 Info  [Bedrock] configureBreakpad with directory: /crash, sessionid is: 719c572a-5581-460f-94f8-f637acc90055
11:22:18 Info  [Bedrock] configureBreakpad called, directory is: /crash, sessionid is: 719c572a-5581-460f-94f8-f637acc90055
11:22:18 Info  [Minecraft] NO LOG FILE! - AppPlatform_android::setStorageDirectory - using External dir (NEW) - CurrentFileStoragePath is now '/home/pi/.local/share/mcpelauncher/'
11:22:18 Warn  [Main] Android stub called
11:22:19 Warn  [Minecraft] NO LOG FILE! - [Device Lost] The graphics context was gained
11:22:19 Warn  [Minecraft] MinecraftGame::init && MinecraftGame::setSize!
11:22:23 Debug [HttpCallStaticGlue] Successfully registerered HttpCall methods
11:22:23 Debug [XboxLiveAppConfig] Successfully registerered XboxLiveAppConfig methods
11:22:23 Debug [XSAPI.Android] Successfully registerered HttpCall tcuiMethods
11:22:23 Debug [XSAPI.Android] Successfully registerered telemetryMethods
stack corruption has been detected
Signal 6 received
Backtrace elements: 2
#0 /tmp/.mount_MCBedr5I9ywg/usr/bin/./mcpelauncher-client(_ZN12CrashHandler12handleSignalEiPv+0x140) [0x884eb4]
#1 /lib/arm-linux-gnueabihf/libc.so.6(__default_sa_restorer+0) [0x7677b110]
Dumping stack...
#35 LINKER std::__ndk1::recursive_mutex::unlock()+0x8 in /home/pi/.local/share/mcpelauncher/versions/1.18.12.01/lib/armeabi-v7a/libc++_shared.so+0x0x5e39d [0x0x697de39d]
#57 LINKER (null)+0x6c1e30b7 in /home/pi/.local/share/mcpelauncher/versions/1.18.12.01/lib/armeabi-v7a/libminecraftpe.so+0x0x28630b7 [0x0x6c1e30b7]
#63 LINKER (null)+0x6c1e335d in /home/pi/.local/share/mcpelauncher/versions/1.18.12.01/lib/armeabi-v7a/libminecraftpe.so+0x0x286335d [0x0x6c1e335d]
#100 LINKER (null)+0x6d657469 in /home/pi/.local/share/mcpelauncher/versions/1.18.12.01/lib/armeabi-v7a/libminecraftpe.so+0x0x3cd7469 [0x0x6d657469]
#108 LINKER (null)+0x6d657469 in /home/pi/.local/share/mcpelauncher/versions/1.18.12.01/lib/armeabi-v7a/libminecraftpe.so+0x0x3cd7469 [0x0x6d657469]
#116 LINKER Scripting::GenericModuleBindingFactory::GenericModuleBindingFactory(std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >, Scripting::UUID)+0x2 in /home/pi/.local/share/mcpelauncher/versions/1.18.12.01/lib/armeabi-v7a/libminecraftpe.so+0x0x5db6567 [0x0x6f736567]
#124 LINKER Scripting::GenericModuleBindingFactory::GenericModuleBindingFactory(std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >, Scripting::UUID)+0x2 in /home/pi/.local/share/mcpelauncher/versions/1.18.12.01/lib/armeabi-v7a/libminecraftpe.so+0x0x5db6567 [0x0x6f736567]
#157 LINKER (null)+0x6c9a3ad1 in /home/pi/.local/share/mcpelauncher/versions/1.18.12.01/lib/armeabi-v7a/libminecraftpe.so+0x0x3023ad1 [0x0x6c9a3ad1]
#160 LINKER (null)+0x6c9a3ae7 in /home/pi/.local/share/mcpelauncher/versions/1.18.12.01/lib/armeabi-v7a/libminecraftpe.so+0x0x3023ae7 [0x0x6c9a3ae7]
#179 LINKER (null)+(nil) in /home/pi/.local/share/mcpelauncher/versions/1.18.12.01/lib/armeabi-v7a/libminecraftpe.so+0x0x5e7e451 [0x0x6f7fe451]
#180 LINKER (null)+(nil) in /home/pi/.local/share/mcpelauncher/versions/1.18.12.01/lib/armeabi-v7a/libminecraftpe.so+0x0x5e7e499 [0x0x6f7fe499]
#341 LINKER (null)+0x6c9a3abd in /home/pi/.local/share/mcpelauncher/versions/1.18.12.01/lib/armeabi-v7a/libminecraftpe.so+0x0x3023abd [0x0x6c9a3abd]
#423 LINKER (null)+0x6c9a3b43 in /home/pi/.local/share/mcpelauncher/versions/1.18.12.01/lib/armeabi-v7a/libminecraftpe.so+0x0x3023b43 [0x0x6c9a3b43]
#424 LINKER (null)+0x6f926cf4 in /home/pi/.local/share/mcpelauncher/versions/1.18.12.01/lib/armeabi-v7a/libminecraftpe.so+0x0x5fa6cf4 [0x0x6f926cf4]
#426 LINKER (null)+0x6f926d08 in /home/pi/.local/share/mcpelauncher/versions/1.18.12.01/lib/armeabi-v7a/libminecraftpe.so+0x0x5fa6d08 [0x0x6f926d08]
#427 LINKER (null)+0x6dbb66a5 in /home/pi/.local/share/mcpelauncher/versions/1.18.12.01/lib/armeabi-v7a/libminecraftpe.so+0x0x42366a5 [0x0x6dbb66a5]
#428 LINKER vtable for Core::FileStdStreamBuf+0x8 in /home/pi/.local/share/mcpelauncher/versions/1.18.12.01/lib/armeabi-v7a/libminecraftpe.so+0x0x5fa82f8 [0x0x6f9282f8]
#429 LINKER (null)+0x69809310 in /home/pi/.local/share/mcpelauncher/versions/1.18.12.01/lib/armeabi-v7a/libc++_shared.so+0x0x89310 [0x0x69809310]
#445 LINKER (null)+0x6f926d1c in /home/pi/.local/share/mcpelauncher/versions/1.18.12.01/lib/armeabi-v7a/libminecraftpe.so+0x0x5fa6d1c [0x0x6f926d1c]
#452 LINKER (null)+0x69809310 in /home/pi/.local/share/mcpelauncher/versions/1.18.12.01/lib/armeabi-v7a/libc++_shared.so+0x0x89310 [0x0x69809310]
#471 LINKER (null)+0x6dbb912b in /home/pi/.local/share/mcpelauncher/versions/1.18.12.01/lib/armeabi-v7a/libminecraftpe.so+0x0x423912b [0x0x6dbb912b]
#485 LINKER (null)+0x6c34ab9d in /home/pi/.local/share/mcpelauncher/versions/1.18.12.01/lib/armeabi-v7a/libminecraftpe.so+0x0x29cab9d [0x0x6c34ab9d]
#489 LINKER (null)+0x6c34ab85 in /home/pi/.local/share/mcpelauncher/versions/1.18.12.01/lib/armeabi-v7a/libminecraftpe.so+0x0x29cab85 [0x0x6c34ab85]
#493 LINKER mce::BlobHelper::resize(mce::Blob&, unsigned int)+0x52 in /home/pi/.local/share/mcpelauncher/versions/1.18.12.01/lib/armeabi-v7a/libminecraftpe.so+0x0x29ca8db [0x0x6c34a8db]
#495 LINKER mce::Blob::defaultDeleter(unsigned char*)+(nil) in /home/pi/.local/share/mcpelauncher/versions/1.18.12.01/lib/armeabi-v7a/libminecraftpe.so+0x0x29caad9 [0x0x6c34aad9]
#501 LINKER (null)+0x28 in /tmp/.mount_MCBedr5I9ywg/usr/share/mcpelauncher/lib/armeabi-v7a/libc.so+0x0xec8 [0x0x70900ec8]
#507 LINKER (null)+0x6c1e1a49 in /home/pi/.local/share/mcpelauncher/versions/1.18.12.01/lib/armeabi-v7a/libminecraftpe.so+0x0x2861a49 [0x0x6c1e1a49]
#511 LINKER (null)+0x6c1e30b7 in /home/pi/.local/share/mcpelauncher/versions/1.18.12.01/lib/armeabi-v7a/libminecraftpe.so+0x0x28630b7 [0x0x6c1e30b7]
#517 LINKER (null)+0x6c1e335d in /home/pi/.local/share/mcpelauncher/versions/1.18.12.01/lib/armeabi-v7a/libminecraftpe.so+0x0x286335d [0x0x6c1e335d]
#521 LINKER (null)+0x6c1e3437 in /home/pi/.local/share/mcpelauncher/versions/1.18.12.01/lib/armeabi-v7a/libminecraftpe.so+0x0x2863437 [0x0x6c1e3437]
#537 LINKER (null)+0x6dbb86c3 in /home/pi/.local/share/mcpelauncher/versions/1.18.12.01/lib/armeabi-v7a/libminecraftpe.so+0x0x42386c3 [0x0x6dbb86c3]
#544 LINKER (null)+0x6c1c2cc5 in /home/pi/.local/share/mcpelauncher/versions/1.18.12.01/lib/armeabi-v7a/libminecraftpe.so+0x0x2842cc5 [0x0x6c1c2cc5]
#550 LINKER renoir::ThirdParty::stbi_zlib_decode_malloc_guesssize_headerflag(char const*, int, int, int*, int)+0x5d in /home/pi/.local/share/mcpelauncher/versions/1.18.12.01/lib/armeabi-v7a/libminecraftpe.so+0x0x4d12e0a [0x0x6e692e0a]
#561 LINKER cohtml::dom::Document::OnNewStylesheet(cohtml::dom::Node*, cohtml::IntrusivePtr<cohtml::css::ParsedStylesheet, cohtml::TaggedStdAllocator<cohtml::css::ParsedStylesheet, (cohtml::MemTags::MemTagsType)8> >&, csl::dyn_array_vector<cohtml::css::MediaExpression, cohtml::TaggedStdAllocator<cohtml::css::MediaExpression, (cohtml::MemTags::MemTagsType)8> >*)+0x1733 in /home/pi/.local/share/mcpelauncher/versions/1.18.12.01/lib/armeabi-v7a/libminecraftpe.so+0x0x4d82e08 [0x0x6e702e08]
#592 LINKER (null)+0x6fc6616c in /home/pi/.local/share/mcpelauncher/versions/1.18.12.01/lib/armeabi-v7a/libminecraftpe.so+0x0x62e616c [0x0x6fc6616c]
Why does some people think exit code 6 is meaningful? It is just a unix signal number.

Process exited with unexpected exit code: 6
`

_Originally posted by @LPS13 in https://github.com/minecraft-linux/mcpelauncher-manifest/issues/652#issuecomment-1052383669_

**Comment by ChristopherHX** [comment]
> raspberry Pi3B+

Could you try a **64bit aarch64** operating system and AppImage? I know your hardware supports it, since you don't mentioned raspberry Pi2.

Otherwise I would suggest to change the game version to an older version like **1.18.0**.

> stack corruption has been detected

Stack corruptions are generally **hard to debug**, this error doesn't happen on x86_64 as far I tested myself.

This error is new to me, not reported before so unlikly happen on older game versions.

I'm currently not working on this project, don't expect much in the following months.

**Comment by LPS13** [comment]
> Could you try a 64bit aarch64 operating system and AppImage?
  this is something i could try after obtaining an unused sd card for the purpose. can you link me to an OS image?

**Comment by ChristopherHX** [comment]
> can you link me to an OS image?

I use the 64bit image of ubuntu-server 20.04 lts, it is now a bit dated. It works for me on a weaker raspberry Pi3B.
https://ubuntu.com/download/raspberry-pi

- enabled the v3d drivers in config.txt
- installed kde desktop via the commandline, since it is a server image

Doing this on a raspberry Pi3B have unsolved weird inverted lights in graphics, since my workaround with older mesa 1.13 doesn't seem to work with 64bit aarch64.

**Comment by LPS13** [comment]
I used the raspberry imager to install Raspberry Pi's newly released 64bit os with desktop onto a new sd card, then installed the "pi-apps" utility (because that how i did it before) then installed minecraft bedrock. i had some seaming lock ups while trying to establish and validate contections to my google and microsoft accounts.  after linking up to my google and microsoft accounts it ran successsfully, no errors. however once in game play it is slower than molasses in January! On a raspberrry Pi 3B+ it was turning out about 5fps in daylight. and would crawl to a painfully low 0.06 and slower if around a light sourcein the dark. so the game works on 3B+ running a 64bit os, but is unplayably slow due to my hardware i am asuming.
