### ISSUE TITLE
Game Crashes With a non-zero code

### ISSUE THREAD

**Issue by Shivam-Shubham** [minecraft-linux/mcpelauncher-manifest#667]
Minecraft (x86):
  Supported on your Device? Yes
  Game Installed? No
  Launcher Installed? Yes
Minecraft (armeabi-v7a):
  Supported on your Device? N/A
  Game Installed? Yes
  Launcher Installed? No
Minecraft (arm64-v8a):
  Supported on your Device? N/A
  Game Installed? No
  Launcher Installed? No
Minecraft (x86_64):
  Supported on your Device? N/A
  Game Installed? No
  Launcher Installed? No
Some thing this the launcher is showing How to Fix

**Comment by ChristopherHX** [comment]
Update the launcher, that version is very outdated. See https://mcpelauncher.readthedocs.io/en/latest/.
