### ISSUE TITLE
Minecraft has exited with non zero code

### ISSUE THREAD

**Issue by AlexLexusYTXD** [minecraft-linux/mcpelauncher-manifest#668]
It is crashing...
Minecraft has exited with non zero error code on macOS High Sierra 10.13.6 with the unofficial linux launcher.
**To Reproduce**
1. Go to Linux Launcher
2. Click on 'Play'
3. See error (Minecraft (x86):
  Supported on your Device? Yes
  Game Installed? No
  Launcher Installed? Yes
Minecraft (armeabi-v7a):
  Supported on your Device? N/A
  Game Installed? No
  Launcher Installed? No
Minecraft (arm64-v8a):
  Supported on your Device? N/A
  Game Installed? No
  Launcher Installed? No
Minecraft (x86_64):
  Supported on your Device? N/A
  Game Installed? Yes
  Launcher Installed? No.   )

**Expected behavior**
I was expecting for it to launch

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [macOS]
 - Version [macOS High Sierra 10.13.6]
 - Installation Type [dmg]

Not supported is a similar looking app in the snap store.

**Additional context**
I WANT IT SO MUCH :(
here the screenshot :D
![Screen Shot 2022-03-06 at 1 08 05 PM](https://user-images.githubusercontent.com/101063628/156942454-f0a1d422-2be6-46f1-87c2-7362e52d9052.png)
Thank you for helping me.

**Comment by AlexLexusYTXD** [comment]
help

**Comment by deffelovers** [comment]
it seems because the launcher you downloaded has the x86 architecture, while the minecraft version installed has the x86_64 architecture,

try to download minecraft apk which has the same architecture as the launcher, you can try to download this version of minecraft x86:

https://apkmodhere.com/minecraft/com.mojang.minecraftpe/download?version=1.14.1.5&type=x86

it's work for me.

**Comment by ChristopherHX** [comment]
@deffelovers **DO NOT PROVIDE LINKS TO APKS!**

**Comment by ChristopherHX** [comment]
Old version, this error has been removed more than a year ago.
