### ISSUE TITLE
MSA daemon could not be found on appimage

### ISSUE THREAD

**Issue by masrourmouad** [minecraft-linux/mcpelauncher-manifest#67]

**Comment by Charadon** [comment]
I'm getting this issue also, when I click sign-in ingame, the sign in window doesn't work. And running the appimage in the terminal doesn't throw up any errors. I'm running debian 9 if that information helps.

**Comment by ChristopherHX** [comment]
Fixed with my PR (merged) https://github.com/minecraft-linux/linux-packaging-scripts/pull/3
