### ISSUE TITLE
A win32 port on windows 7 sp2+

### ISSUE THREAD

**Issue by gitdrug** [minecraft-linux/mcpelauncher-manifest#672]
**Is your feature request related to a problem? Please describe.**
A port on Windows 7 sp2+ so non Windows 10 users can play Minecraft Bedrock

**Describe the solution you'd like**
A port to Windows 7 sp2 and above so people who don't use Windows 10 can play Minecraft Bedrock

**Describe alternatives you've considered**
Android Emulator, but i don't trust any of the Android Emulators out their

**Comment by Mhowser** [comment]
Windows 7 has been End of life for several years, just find a Linux distro you like and used that instead.

**Comment by Max-RM** [comment]
> **Is your feature request related to a problem? Please describe.** A port on Windows 7 sp2+ so non Windows 10 users can play Minecraft Bedrock
> 
> **Describe the solution you'd like** A port to Windows 7 sp2 and above so people who don't use Windows 10 can play Minecraft Bedrock
> 
> **Describe alternatives you've considered** Android Emulator, but i don't trust any of the Android Emulators out their

Use MCEE or OptiCraft (modified MCEE) or McChinaDev (chinese MCBE win32)
As you can see it works: https://youtu.be/xct-8FYVcEg
