### ISSUE TITLE
Game Freezes on startup

### ISSUE THREAD

**Issue by TheHypeTrain** [minecraft-linux/mcpelauncher-manifest#68]
When I lick "play", the game window appears but only as a white screen. I have tried updating the launcher and re-downloading the game file, but the problem persists. The game log does not  seem to offer any error code except 
"Error [XSAPI.Android] java interop not initialized properly"
It seems to only affect newly downloaded versions, but previously installed versions stop working if I delete and redownload them.
On a possibly related note, the news is no longer showing up either.
Here is the whole log:
14:59:55 Info  [Launcher] Version: client b31d2a6 / manifest e79f522
14:59:55 Info  [Launcher] CPU: AuthenticAMD AMD E-300 APU with Radeon(tm) HD Graphics
14:59:55 Info  [Launcher] CPU supports SSSE3: YES
14:59:55 Trace [Launcher] Loading hybris libraries
14:59:55 Trace [HybrisUtils] Loaded OS library /home/tht/mcpelauncher/mcpelauncher-linux-bin/libs/native/libfmod.so.9.16
14:59:55 Trace [HybrisUtils] Loaded OS library libm.so.6
14:59:55 Trace [Launcher] Loading Minecraft library
15:00:02 Info  [Launcher] Loaded Minecraft library
15:00:02 Debug [Launcher] Minecraft is at offset 0xe9064000
15:00:02 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance16initializeServerER13IMinecraftAppR9WhitelistP15PermissionsFileP15FilePathManagerNSt6chrono8durationIxSt5ratioILx1ELx1EEEESsSsSs13LevelSettingsibiiibRKSt6vectorISsSaISsEESsRKN3mce4UUIDER18IMinecraftEventingR22ResourcePackRepositoryRK18ContentTierManagerR19ResourcePackManagerSt8functionIFSt10unique_ptrI12LevelStorageSt14default_deleteISY_EER9SchedulerEERKSsP9LevelDataSsSsSX_I16EducationOptionsSZ_IS1A_EEPSU_SW_IFvS17_EES1F_
15:00:02 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance16_syncDestroyGameEv
15:00:02 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social12XboxLiveUser22_handleUISignInNoErrorERN4xbox8services6system14sign_in_resultESt8functionIFvNS_12SignInResultEbEE
15:00:02 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManagerC2ESt8functionIFSsvEERK18ContentTierManager
15:00:02 Error [MinecraftSymbols] Unresolved symbol: _ZN28DedicatedServerCommandOriginC2ERKSsR9Minecraft
15:00:02 Info  [Launcher] Game version: 1.11.0.8
15:00:02 Info  [Launcher] Applying patches
15:00:02 Trace [Store] Vtable size = 34
15:00:02 Trace [Patch] Patching - original: 85 83 87 86 131
15:00:02 Trace [Patch] Patching - result: 233 188 239 12 108
15:00:02 Trace [Patch] Patching - original: 83 87 86 131 236
15:00:02 Trace [Patch] Patching - result: 233 139 235 110 107
15:00:02 Trace [Patch] Patching - original: 85 83 87 86 129
15:00:02 Trace [Patch] Patching - result: 233 227 222 100 105
15:00:02 Trace [Patch] Patching - original: 85 83 87 86 129
15:00:02 Trace [Patch] Patching - result: 233 19 32 163 105
15:00:02 Trace [Patch] Patching - original: 85 83 87 86 129
15:00:02 Trace [Patch] Patching - result: 233 105 48 163 105
15:00:02 Trace [Patch] Patching - original: 85 83 87 86 129
15:00:02 Trace [Patch] Patching - result: 233 221 28 163 105
15:00:02 Trace [Patch] Patching - original: 85 83 87 86 129
15:00:02 Trace [Patch] Patching - result: 233 249 135 162 105
15:00:02 Trace [Patch] Patching - original: 85 83 87 86 129
15:00:02 Trace [Patch] Patching - result: 233 127 133 162 105
15:00:02 Trace [Patch] Patching - original: 85 83 87 86 129
15:00:02 Trace [Patch] Patching - result: 233 25 190 164 105
15:00:02 Trace [Patch] Patching - original: 83 87 86 131 236
15:00:02 Trace [Patch] Patching - result: 233 87 37 163 105
15:00:02 Trace [Patch] Patching - original: 85 83 87 86 129
15:00:02 Trace [Patch] Patching - result: 233 19 80 163 105
15:00:02 Trace [Patch] Patching - original: 49 192 195 141 182
15:00:02 Trace [Patch] Patching - result: 233 207 174 6 108
15:00:02 Trace [Patch] Patching - original: 83 131 236 8 232
15:00:02 Trace [Patch] Patching - result: 233 163 168 192 105
15:00:02 Trace [Patch] Patching - original: 137 76 36 4 137
15:00:02 Trace [Patch] Patching - result: 232 238 192 117 105
15:00:02 Trace [Patch] Patching - original: 36 88 139 65 12
15:00:02 Trace [Patch] Patching - result: 232 249 192 117 105
15:00:02 Trace [Patch] Patching - original: 85 83 87 86 131
15:00:02 Trace [Patch] Patching - result: 233 132 202 15 108
15:00:02 Trace [Patch] Patching - original: 85 83 87 86 129
15:00:02 Trace [Patch] Patching - result: 233 81 201 15 108
15:00:02 Trace [Patch] Patching - original: 83 87 86 131 236
15:00:02 Trace [Patch] Patching - result: 233 29 202 15 108
15:00:02 Trace [Patch] Patching - original: 85 137 229 83 87
15:00:02 Trace [Patch] Patching - result: 233 150 147 93 105
15:00:02 Trace [Patch] Patching - original: 83 86 131 236 20
15:00:02 Trace [Patch] Patching - result: 233 97 86 96 107
15:00:02 Trace [Patch] Patching - original: 232 253 244 182 253
15:00:02 Trace [Patch] Patching - result: 232 149 134 230 105
15:00:02 Info  [Launcher] Creating window
15:00:02 Trace [Launcher] Loading gamepad mappings: /home/tht/mcpelauncher/build/gamecontrollerdb/gamecontrollerdb.txt
15:00:02 Trace [Launcher] Loading gamepad mappings: /usr/local/share/mcpelauncher/gamecontrollerdb.txt
15:00:02 Trace [Launcher] Loading gamepad mappings: /usr/local/share/mcpelauncher/gamecontrollerdb.txt
15:00:02 Trace [Launcher] Initializing AppPlatform (vtable)
15:00:02 Trace [AppPlatform] Vtable size = 260
15:00:02 Trace [Launcher] Initializing AppPlatform (create instance)
15:00:02 Trace [Launcher] Initializing AppPlatform (initialize call)
15:00:02 Trace [AppPlatform] createDeviceID (from file): a322f99b-6b5a-4aac-af93-cefa2583038b
15:00:02 Info  [Launcher] OpenGL: version: OpenGL ES 3.1 Mesa 18.2.8, renderer: AMD PALM (DRM 2.50.0 / 4.15.0-20-generic, LLVM 7.0.0), vendor: X.Org
15:00:02 Trace [Launcher] Initializing MinecraftGame (create instance)
15:00:02 Trace [AppPlatform] getSystemRegion: en_US
15:00:02 Trace [Launcher] Initializing MinecraftGame (init call)
15:00:02 Info  [Launcher] Game initialized
libevdev_new_from_fd error -22 (/dev/input/js0)
15:00:02 Trace [WindowCallbacks] Gamepad connected #0
15:00:02 Trace [AppPlatform] getDataUrl: /home/tht/.local/share/mcpelauncher/versions/1.11.0.8/assets/
15:00:03 Trace [AppPlatform] getDataUrl: /home/tht/.local/share/mcpelauncher/versions/1.11.0.8/assets/
15:00:03 Trace [XboxLive] Reading xbox config file
15:00:03 Error [XSAPI.Android] java interop not initialized properly
15:00:03 Trace [Launcher] Creating store
15:00:03 Trace [Store] registerLicenseChangeCallback
15:00:03 Trace [Store] getStoreId: android.googleplay
15:00:03 Trace [Store] restoreFromCache

**Comment by TheHypeTrain** [comment]
Ok so apparently this does not affect version 1.9.0.15. News is still not working

**Comment by Mhowser** [comment]
News currently does not load due to mojang changing the API format, I
believe @mrarm is looking at it.

**Comment by MCMrARM** [comment]
Please update your launcher.
