### ISSUE TITLE
RenderDragon versions don't work (1.18.30/1.19 betas)

### ISSUE THREAD

**Issue by GameParrot** [minecraft-linux/mcpelauncher-manifest#681]
**Describe the bug**
When starting any version that uses RenderDragon, the game crashes because of missing symbols

**To Reproduce**
1. Launch 1.18.30.04
5. See crash

**Expected behavior**
The game should start

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS 12.2.1
 - Version Built from commit 680d827b4bd2bb7a078d57d4957a20bacdb6ffd5
 - Installation Type built from source

Not supported is a similar looking app in the snap store.

**Additional context**
If I add the missing symbols to android_symbols.h, the window appears but crashes after a few seconds.
Crash log:

15:41:48 Info  [Launcher] Version: client 1e44372 / manifest 680d827
15:41:48 Info  [Launcher] CPU: GenuineIntel Intel(R) Core(TM) i3-8100 CPU @ 3.60GHz
15:41:48 Info  [Launcher] CPU supports SSSE3: YES
15:41:48 Trace [Launcher] Loading hybris libraries
15:41:48 Trace [REDIRECT] /data/data/com.mojang.minecraftpe to /Users/$USER/Documents/Minecraft Bedrock Installations/Beta11/
15:41:48 Trace [REDIRECT] /data/data/Applications/Minecraft Bedrock Launcher.app/Contents/proc/84772/cmdline to /Users/$USER/Documents/Minecraft Bedrock Installations/Beta11/
15:41:48 Trace [REDIRECT] /data/data/Applications/Minecraft Bedrock Launcher.app/Contents/MacOS/./mcpelauncher-client to /Users/$USER/Documents/Minecraft Bedrock Installations/Beta11/
15:41:48 Trace [REDIRECT] /data/data to /Users/$USER/Documents/Minecraft Bedrock Installations/Beta11/
15:41:48 Trace [LinkerUtils] Loaded OS library libm.dylib
15:41:48 Trace [LinkerUtils] Loaded OS library libz.dylib
15:41:48 Trace [LinkerUtils] Loaded OS library /Applications/Minecraft Bedrock Launcher.app/Contents/Resources/mcpelauncher/lib/native/x86_64/libfmod.dylib
15:41:48 Trace [Launcher] Loading Minecraft library
15:41:48 Error [MinecraftUtils] Failed to load Minecraft: dlopen failed: cannot locate symbol "ANativeWindow_getWidth" referenced by "/Users/$USER/Library/Application Support/mcpelauncher/versions/1.19.0.24/lib/x86_64/libminecraftpe.so"...
15:41:48 Error [Launcher] Failed to load Minecraft library, please reinstall or wait for an update to support the new release

Incompatible Minecraft installation, please select a different or older Version
This Launcher is a free Open Source Software which usually fell behind official updates from Google Play
In some cases there are missing game files,
missing Symbols expected to be provided by this Launcher via updates
 or otherwise broke the Launcher

Crash log if missing symbols are added to android_symbols.h:

15:46:50 Info  [Launcher] Version: client 1e44372 / manifest 680d827
15:46:50 Info  [Launcher] CPU: GenuineIntel Intel(R) Core(TM) i3-8100 CPU @ 3.60GHz
15:46:50 Info  [Launcher] CPU supports SSSE3: YES
15:46:50 Trace [Launcher] Loading hybris libraries
15:46:50 Trace [REDIRECT] /data/data/com.mojang.minecraftpe to /Users/$USER/Documents/1.19 test/
15:46:50 Trace [REDIRECT] /data/data/Users/$USER/mcpelauncher-manifest copy/build/proc/84989/cmdline to /Users/$USER/Documents/1.19 test/
15:46:50 Trace [REDIRECT] /data/data/Users/$USER/mcpelauncher-manifest copy/build/mcpelauncher-client/mcpelauncher-client to /Users/$USER/Documents/1.19 test/
15:46:50 Trace [REDIRECT] /data/data to /Users/$USER/Documents/1.19 test/
15:46:50 Trace [LinkerUtils] Loaded OS library libm.dylib
15:46:50 Trace [LinkerUtils] Loaded OS library libz.dylib
15:46:50 Warn  [FMOD] Failed to load host libfmod: 'Failed to find data file: lib/native/x86_64/libfmod.dylib', use experimental pulseaudio backend if available
15:46:50 Trace [Launcher] Loading Minecraft library
Found hook: _ZN11AppPlatform16showMousePointerEv @ 0x101270d40
Found hook: _ZN11AppPlatform16hideMousePointerEv @ 0x101270d20
15:46:50 Info  [Launcher] Loaded Minecraft library
15:46:50 Debug [Launcher] Minecraft is at offset 0x0x1077c0000
15:46:50 Info  [Launcher] Game version: 0.0.0.0
15:46:50 Info  [Launcher] Applying patches
15:46:50 Debug [CorePatches] Failed to patch, vtable _ZTV21AppPlatform_android23 not found
15:46:51 Error [GLCOREPATCH] Failed to apply glcorepatch: Failed to find gl::supportsImmediateMode
15:46:51 Info  [Launcher] Initializing JNI
15:46:51 Error [JniSupport] Missing native symbol: Java_com_mojang_minecraftpe_MainActivity_nativeRegisterThis
15:46:51 Error [JniSupport] Missing native symbol: Java_com_mojang_minecraftpe_MainActivity_nativeUnregisterThis
15:46:51 Error [JniSupport] Missing native symbol: Java_com_microsoft_xal_browser_WebView_urlOperationSucceeded
15:46:51 Info  [Launcher] Executing main thread
15:46:51 Trace [Minecraft] Entering JNI_OnLoad 0x700004958000
15:46:51 Trace [Minecraft] JNI_OnLoad completed
15:46:51 Trace [JniSupport] Invoking nativeRegisterThis
15:46:51 Trace [JniSupport] Invoking ANativeActivity_onCreate
15:46:51 Warn  [Main] Android stub called
15:46:51 Warn  [Main] Android stub called
15:46:51 Warn  [Main] Android stub called
15:46:51 Warn  [Main] Android stub called
15:46:51 Info  [Launcher] Loading gamepad mappings
15:46:51 Trace [Launcher] Loading gamepad mappings: /Users/$USER/mcpelauncher-manifest copy/build/gamecontrollerdb/gamecontrollerdb.txt
15:46:51 Info  [Launcher] Creating window
15:46:51 Info  [Minecraft] android_main starting. internalDataPath is '/internal', externalDataPath is '/external'
15:46:51 Trace [JniSupport] Invoking start activity callbacks
15:46:51 Error [MCPE] *** setCachedDeviceId(26838f02-d5d5-41ee-8152-1183653fd917)
15:46:51 Info  [Bedrock] configureBreakpad with directory: /crash, sessionid is: c6c10d1c-8b04-4c9a-8bba-cf15a2b74c85
15:46:51 Info  [Bedrock] configureBreakpad called, directory is: /crash, sessionid is: c6c10d1c-8b04-4c9a-8bba-cf15a2b74c85
15:46:51 Info  [Minecraft] NO LOG FILE! - AppPlatform_android::setStorageDirectory - using External dir (NEW) - CurrentFileStoragePath is now '/Users/$USER/Documents/1.19 test/'
15:46:51 Warn  [Main] Android stub called
15:46:51 Warn  [Main] Android stub called
15:46:51 Warn  [Minecraft] NO LOG FILE! - [Graphics] The graphics context was gained
15:46:51 Warn  [Minecraft] MinecraftGame::init && MinecraftGame::setSize!
15:46:51 Warn  [Minecraft] NO LOG FILE! - [Graphics] The graphics context was gained
terminating
abort message: terminating
Signal 6 received
Backtrace elements: 5
#0 0   mcpelauncher-client                 0x0000000101280510 _ZN12CrashHandler12handleSignalEiPv + 320
#1 1   libsystem_platform.dylib            0x00007ff81d628e2d _sigtramp + 29
#2 2   libEGL.dylib                        0x0000000105617000 __dso_handle + 0
#3 3   libsystem_c.dylib                   0x00007ff81d55fd10 abort + 123
#4 4   ???                                 0x000000010572508c 0x0 + 4386345100
Dumping stack...
#4 LINKER (null)+0x105725160 in /Users/$USER/Library/Application Support/mcpelauncher/versions/1.19.0.24/lib/x86_64/libc++_shared.so+0x0xa5160 [0x0x105725160]
#175 LINKER (null)+0x10574327c in /Users/$USER/Library/Application Support/mcpelauncher/versions/1.19.0.24/lib/x86_64/libc++_shared.so+0x0xc327c [0x0x10574327c]
#179 LINKER (null)+0x10574327c in /Users/$USER/Library/Application Support/mcpelauncher/versions/1.19.0.24/lib/x86_64/libc++_shared.so+0x0xc327c [0x0x10574327c]
#182 LINKER (null)+0x10572508c in /Users/$USER/Library/Application Support/mcpelauncher/versions/1.19.0.24/lib/x86_64/libc++_shared.so+0x0xa508c [0x0x10572508c]
#208 LINKER (null)+0x105774efc in /Users/$USER/Library/Application Support/mcpelauncher/versions/1.19.0.24/lib/x86_64/libc++_shared.so+0x0xf4efc [0x0x105774efc]
#209 LINKER (null)+0x10573ac30 in /Users/$USER/Library/Application Support/mcpelauncher/versions/1.19.0.24/lib/x86_64/libc++_shared.so+0x0xbac30 [0x0x10573ac30]
#220 LINKER (null)+0x10572518a in /Users/$USER/Library/Application Support/mcpelauncher/versions/1.19.0.24/lib/x86_64/libc++_shared.so+0x0xa518a [0x0x10572518a]
#341 LINKER (null)+0x105774ef8 in /Users/$USER/Library/Application Support/mcpelauncher/versions/1.19.0.24/lib/x86_64/libc++_shared.so+0x0xf4ef8 [0x0x105774ef8]
#342 LINKER (null)+0x10573ac30 in /Users/$USER/Library/Application Support/mcpelauncher/versions/1.19.0.24/lib/x86_64/libc++_shared.so+0x0xbac30 [0x0x10573ac30]
#346 LINKER (null)+0x105774efc in /Users/$USER/Library/Application Support/mcpelauncher/versions/1.19.0.24/lib/x86_64/libc++_shared.so+0x0xf4efc [0x0x105774efc]
#347 LINKER (null)+0x10573ac30 in /Users/$USER/Library/Application Support/mcpelauncher/versions/1.19.0.24/lib/x86_64/libc++_shared.so+0x0xbac30 [0x0x10573ac30]
#356 LINKER (null)+0x10573afa3 in /Users/$USER/Library/Application Support/mcpelauncher/versions/1.19.0.24/lib/x86_64/libc++_shared.so+0x0xbafa3 [0x0x10573afa3]
#358 LINKER std::terminate()+0x38 in /Users/$USER/Library/Application Support/mcpelauncher/versions/1.19.0.24/lib/x86_64/libc++_shared.so+0x0xbaf48 [0x0x10573af48]
#360 LINKER (null)+0x10c8388b6 in /Users/$USER/Library/Application Support/mcpelauncher/versions/1.19.0.24/lib/x86_64/libminecraftpe.so+0x0x50788b6 [0x0x10c8388b6]
#361 LINKER vtable for mce::framebuilder::BgfxFrameBuilder+0x10 in /Users/$USER/Library/Application Support/mcpelauncher/versions/1.19.0.24/lib/x86_64/libminecraftpe.so+0x0xca922d8 [0x0x1142522d8]
#362 LINKER (null)+0x113922da4 in /Users/$USER/Library/Application Support/mcpelauncher/versions/1.19.0.24/lib/x86_64/libminecraftpe.so+0x0xc162da4 [0x0x113922da4]
#366 LINKER (null)+0x10de1858d in /Users/$USER/Library/Application Support/mcpelauncher/versions/1.19.0.24/lib/x86_64/libminecraftpe.so+0x0x665858d [0x0x10de1858d]
#373 LINKER (null)+0x114434d38 in /Users/$USER/Library/Application Support/mcpelauncher/versions/1.19.0.24/lib/x86_64/libminecraftpe.so+0x0xcc74d38 [0x0x114434d38]
#374 LINKER (null)+0x10ddacb01 in /Users/$USER/Library/Application Support/mcpelauncher/versions/1.19.0.24/lib/x86_64/libminecraftpe.so+0x0x65ecb01 [0x0x10ddacb01]
#382 LINKER (null)+0x10dd8e3ed in /Users/$USER/Library/Application Support/mcpelauncher/versions/1.19.0.24/lib/x86_64/libminecraftpe.so+0x0x65ce3ed [0x0x10dd8e3ed]
#383 LINKER (null)+0x114080640 in /Users/$USER/Library/Application Support/mcpelauncher/versions/1.19.0.24/lib/x86_64/libminecraftpe.so+0x0xc8c0640 [0x0x114080640]
#384 LINKER (null)+0x10dd7e55f in /Users/$USER/Library/Application Support/mcpelauncher/versions/1.19.0.24/lib/x86_64/libminecraftpe.so+0x0x65be55f [0x0x10dd7e55f]
#396 LINKER (null)+0x10dd93078 in /Users/$USER/Library/Application Support/mcpelauncher/versions/1.19.0.24/lib/x86_64/libminecraftpe.so+0x0x65d3078 [0x0x10dd93078]
#397 LINKER (null)+0x113dbca88 in /Users/$USER/Library/Application Support/mcpelauncher/versions/1.19.0.24/lib/x86_64/libminecraftpe.so+0x0xc5fca88 [0x0x113dbca88]
#408 LINKER (null)+0x10c846354 in /Users/$USER/Library/Application Support/mcpelauncher/versions/1.19.0.24/lib/x86_64/libminecraftpe.so+0x0x5086354 [0x0x10c846354]
#409 LINKER vtable for Bedrock::Memory::InternalHeapAllocator+0x10 in /Users/$USER/Library/Application Support/mcpelauncher/versions/1.19.0.24/lib/x86_64/libminecraftpe.so+0x0xc4dabf8 [0x0x113c9abf8]
#414 LINKER (null)+0x10de3539f in /Users/$USER/Library/Application Support/mcpelauncher/versions/1.19.0.24/lib/x86_64/libminecraftpe.so+0x0x667539f [0x0x10de3539f]
#418 LINKER (null)+0x10dd77ff9 in /Users/$USER/Library/Application Support/mcpelauncher/versions/1.19.0.24/lib/x86_64/libminecraftpe.so+0x0x65b7ff9 [0x0x10dd77ff9]
#446 LINKER (null)+0x10dd678df in /Users/$USER/Library/Application Support/mcpelauncher/versions/1.19.0.24/lib/x86_64/libminecraftpe.so+0x0x65a78df [0x0x10dd678df]
#453 LINKER (null)+0x113dba240 in /Users/$USER/Library/Application Support/mcpelauncher/versions/1.19.0.24/lib/x86_64/libminecraftpe.so+0x0xc5fa240 [0x0x113dba240]
#459 LINKER (null)+0x113dba1c0 in /Users/$USER/Library/Application Support/mcpelauncher/versions/1.19.0.24/lib/x86_64/libminecraftpe.so+0x0xc5fa1c0 [0x0x113dba1c0]
#472 LINKER (null)+0x10de03980 in /Users/$USER/Library/Application Support/mcpelauncher/versions/1.19.0.24/lib/x86_64/libminecraftpe.so+0x0x6643980 [0x0x10de03980]
#478 LINKER (null)+0x10dd729b4 in /Users/$USER/Library/Application Support/mcpelauncher/versions/1.19.0.24/lib/x86_64/libminecraftpe.so+0x0x65b29b4 [0x0x10dd729b4]
#486 LINKER (null)+0x10db639ae in /Users/$USER/Library/Application Support/mcpelauncher/versions/1.19.0.24/lib/x86_64/libminecraftpe.so+0x0x63a39ae [0x0x10db639ae]
#492 LINKER (null)+0x10ddac913 in /Users/$USER/Library/Application Support/mcpelauncher/versions/1.19.0.24/lib/x86_64/libminecraftpe.so+0x0x65ec913 [0x0x10ddac913]
#502 LINKER (null)+0x10dd81416 in /Users/$USER/Library/Application Support/mcpelauncher/versions/1.19.0.24/lib/x86_64/libminecraftpe.so+0x0x65c1416 [0x0x10dd81416]
#508 LINKER (null)+0x1144583b8 in /Users/$USER/Library/Application Support/mcpelauncher/versions/1.19.0.24/lib/x86_64/libminecraftpe.so+0x0xcc983b8 [0x0x1144583b8]
#529 LINKER (null)+0x113dbbfe8 in /Users/$USER/Library/Application Support/mcpelauncher/versions/1.19.0.24/lib/x86_64/libminecraftpe.so+0x0xc5fbfe8 [0x0x113dbbfe8]
#547 LINKER (null)+0x113dbbde8 in /Users/$USER/Library/Application Support/mcpelauncher/versions/1.19.0.24/lib/x86_64/libminecraftpe.so+0x0xc5fbde8 [0x0x113dbbde8]
#578 LINKER (null)+0x10dd7fd69 in /Users/$USER/Library/Application Support/mcpelauncher/versions/1.19.0.24/lib/x86_64/libminecraftpe.so+0x0x65bfd69 [0x0x10dd7fd69]
#580 LINKER (null)+0x10c7fff2b in /Users/$USER/Library/Application Support/mcpelauncher/versions/1.19.0.24/lib/x86_64/libminecraftpe.so+0x0x503ff2b [0x0x10c7fff2b]
#582 LINKER (null)+0x113c69301 in /Users/$USER/Library/Application Support/mcpelauncher/versions/1.19.0.24/lib/x86_64/libminecraftpe.so+0x0xc4a9301 [0x0x113c69301]
#590 LINKER (null)+0x1142e1020 in /Users/$USER/Library/Application Support/mcpelauncher/versions/1.19.0.24/lib/x86_64/libminecraftpe.so+0x0xcb21020 [0x0x1142e1020]
#599 LINKER (null)+0x113c69308 in /Users/$USER/Library/Application Support/mcpelauncher/versions/1.19.0.24/lib/x86_64/libminecraftpe.so+0x0xc4a9308 [0x0x113c69308]
#605 LINKER (null)+0x113c69278 in /Users/$USER/Library/Application Support/mcpelauncher/versions/1.19.0.24/lib/x86_64/libminecraftpe.so+0x0xc4a9278 [0x0x113c69278]
#619 LINKER (null)+0x113c691f8 in /Users/$USER/Library/Application Support/mcpelauncher/versions/1.19.0.24/lib/x86_64/libminecraftpe.so+0x0xc4a91f8 [0x0x113c691f8]
#632 LINKER (null)+0x10c7e8e1c in /Users/$USER/Library/Application Support/mcpelauncher/versions/1.19.0.24/lib/x86_64/libminecraftpe.so+0x0x5028e1c [0x0x10c7e8e1c]
Why does some people think exit code 6 is meaningful? It is just a unix signal number.

**Comment by GameParrot** [comment]
1.18.30 was just released today and does not work.

**Comment by p0ryae** [comment]
> 1.18.30 was just released today and does not work.

I can confirm. Plus, I cant even try running it because this error keeps popping up:
![image](https://user-images.githubusercontent.com/59381835/164116585-f8f40f62-6362-4a8d-b714-a8c9641c20ff.png)


Why would the devs not even let the apk crash? 🤔 preventing us to check the game logs at the first place is a weird move.

**Comment by ChristopherHX** [comment]
Feel free to contribute 1.18.30+ support, I drastically reduced development ( 1 October 2021 ) after 2+ years abuse for piracy.

>  preventing us to check the game logs at the first place is a weird move.

A developer wouldn't debug the game from mcpelauncher-ui, compile the launcher and run mcpelauncher-client from an c++ ide with gdb. You may need to install ubuntu 20.04 or you may fail to compile or debug it this app.

Related to https://github.com/ChristopherHX/mcpelauncher-manifest/issues/48#issuecomment-1103003097

**Comment by p0ryae** [comment]
Thanks. Didn't know that existed.

I'll take a look at it soon.

**Comment by Etaash-mathamsetty** [comment]
> Feel free to contribute 1.18.30+ support, I drastically reduced development ( 1 October 2021 ) after 2+ years abuse for piracy.
> 
> > preventing us to check the game logs at the first place is a weird move.
> 
> A developer wouldn't debug the game from mcpelauncher-ui, compile the launcher and run mcpelauncher-client from an c++ ide with gdb. You may need to install ubuntu 20.04 or you may fail to compile or debug it this app.
> 
> Related to [ChristopherHX#48 (comment)](https://github.com/ChristopherHX/mcpelauncher-manifest/issues/48#issuecomment-1103003097)

from personal experience getting stuff to work on ubuntu is such a pain, I wonder why you went the ubuntu route...

**Comment by Etaash-mathamsetty** [comment]
> Feel free to contribute 1.18.30+ support, I drastically reduced development ( 1 October 2021 ) after 2+ years abuse for piracy.
> 
> > preventing us to check the game logs at the first place is a weird move.
> 
> A developer wouldn't debug the game from mcpelauncher-ui, compile the launcher and run mcpelauncher-client from an c++ ide with gdb. You may need to install ubuntu 20.04 or you may fail to compile or debug it this app.
> 
> Related to [ChristopherHX#48 (comment)](https://github.com/ChristopherHX/mcpelauncher-manifest/issues/48#issuecomment-1103003097)

we can also try validating ownership of the game, but that doesn't stop people since you can just make a fork with the validation check removed... that sucks

**Comment by ChristopherHX** [comment]
This is fixed for linux and the crash on macOS is caused by external code.

_Eventually I find someday a workaround or the externel code fixes the Issue.

**Comment by ChristopherHX** [comment]
As per https://github.com/ChristopherHX/osx-packaging-scripts/releases/tag/v0.5.100-390 now also closed for macOS.
