### ISSUE TITLE
Custom server is not staying

### ISSUE THREAD

**Issue by MDrapper** [minecraft-linux/mcpelauncher-manifest#683]
On macOS Game version 1.18.12.01 when I add a custom server and then restart the game server has disappeared and I have to add it again.

**Comment by wertie3020** [comment]
same on linux pop-os using flatpak sins version 1.18.10.04 if i go back to a older version the custom servers are still there

**Comment by nobody5050** [comment]
also experiencing on ubuntu 22.04 flatpack

**Comment by ChristopherHX** [comment]
Fixed in ng by https://github.com/minecraft-linux/mcpelauncher-manifest/commit/75ec84ca75d3305621a8ac534bf8b1812eb2ded3.
