### ISSUE TITLE
1.19.30+ is not compatible

### ISSUE THREAD

**Issue by daemonspudguy** [minecraft-linux/mcpelauncher-manifest#691]
**Is your feature request related to a problem? Please describe.**
Release 1.19 is out.
**Describe the solution you'd like**
The ability to use release 1.19

**Comment by QuentinDOS** [comment]
Would love to see this, wanting to play with my friends on my realm but I can't connect anymore to it and so I'm stuck waiting to play or playing on my phone I guess which I'm not even considering an option honestly.

**Comment by severtheskyline** [comment]
I hope the skin bug is fixed with 1.19

**Comment by Teunboeke** [comment]
I wanna play servers everthing is oudated

**Comment by Avisator1** [comment]
Yeah

**Comment by Zapiano** [comment]
what have to be done to solve this issue?

**Comment by ChristopherHX** [comment]
For 1.18.30 - 1.19.21, please go to this issue: https://github.com/minecraft-linux/mcpelauncher-manifest/issues/685#issuecomment-1229465135

Additionally 1.19.30 needs this patch https://github.com/minecraft-linux/libc-shim/commit/00f1daa68526c50ece1f0bfed97b612a43bbe22b, this is not yet included in flathub beta

New version support has been throttled due to missing contributors. I'm almost the only one, who still contributes code to this project.

**Comment by BongoEADGC6** [comment]
What can we do to help get this working for the newer versions?

Someone may be able to help if people knew what the issues that are being faced were.

**Comment by ChristopherHX** [comment]
1.18.30 / 1.19.30 public developer preview

You have to clone minecraft-linux/mcpelauncher-manifest ng or qt6 recursive and pull the latest version of the mcpelauncher-client, mcpelauncher-core, libc-shim submodules from the master branches.
_It is possible that this fails to compile and you need to resolve these issues yourself._

You can expect a lot of new bugs, this repo isn't updated yet and needs more testing.

See wiki for how to compile.

> What can we do to help get this working for the newer versions?

From pinned messages discord:
> - Find out how to make the opengl backend of  https://chromium.googlesource.com/angle/angle compatible with the  renderdragon engine.

Linux is almost working fine with 1.19.30.

**Comment by ChristopherHX** [comment]
Closed via https://github.com/minecraft-linux/mcpelauncher-manifest/commit/4c7dadf29df543856db9b73f8a7b220e65d489a2

**Comment by ClaimedXD** [comment]
How do i download these new versions that are compatibal i look ALL over youtube trying to find it but this it all i found

**Comment by ChristopherHX** [comment]
Install or Update this app on your linux device https://flathub.org/apps/details/io.mrarm.mcpelauncher. On some linux distros you can find the same app in the Store App under "Minecraft Bedrock Launcher".
If you prefer an AppImage file you find a link on the wiki, there is a link to our wiki in the repository description.

> How do i download these new versions that are compatibal 

If you didn't change any settings the launcher will allow you to get 1.19.40.02 by just pressing "Download and Play".

If you are on macOS you need to be very patient, it is unlikely to be released there in the following months.

_No I'm not a youtuber and are not creating any videos about this Launcher_

**Comment by pricepewitt** [comment]
dude thank you so so much for being helpful. I would rly like to compensate you, if I can get this to work pls give me your Venmo and I will srsly tip you. This is me and my gfs fav game and we can't play together rn, so I'm trying rly hard to get this to work! Thank you for contributing to this project, it is so appreciated.

**Comment by pricepewitt** [comment]
follow up, I am on MacOS, so am I screwed?

**Comment by pricepewitt** [comment]
> Install or Update this app on your linux device https://flathub.org/apps/details/io.mrarm.mcpelauncher. On some linux distros you can find the same app in the Store App under "Minecraft Bedrock Launcher". If you prefer an AppImage file you find a link on the wiki, there is a link to our wiki in the repository description.
> 
> > How do i download these new versions that are compatibal
> 
> If you didn't change any settings the launcher will allow you to get 1.19.40.02 by just pressing "Download and Play".
> 
> If you are on macOS you need to be very patient, it is unlikely to be released there in the following months.
> 
> _No I'm not a youtuber and are not creating any videos about this Launcher_

is there any amount I can pay you to help me figure this out on MacOS?

**Comment by ChristopherHX** [comment]
1.19.40 is coming soon to macOS

Programmers can try to follow this discord channel to get it today: https://discord.com/channels/429580677617418240/452451848066957314/1056002434289389598

**Comment by mnkhprre** [comment]
> 1.19.40 is coming soon to macOS
> 
> Programmers can try to follow this discord channel to get it today: https://discord.com/channels/429580677617418240/452451848066957314/1056002434289389598


the discord link is broken it seems

**Comment by ChristopherHX** [comment]
> the discord link is broken it seems

You might need to join the server, it is a valid link for me.
https://discord.gg/TaUNBXr

**Comment by ChristopherHX** [comment]
macOS renderdragon has been released in prerelease https://github.com/ChristopherHX/osx-packaging-scripts/releases/tag/v0.5.100-390
