### ISSUE TITLE
crash by start up

### ISSUE THREAD

**Issue by megamichi** [minecraft-linux/mcpelauncher-manifest#693]
/tmp/.mount_MinecrYdyQhl/usr/bin/./mcpelauncher-client: error while loading shared libraries: libEGL.so.1: cannot open shared object file: No such file or directory
Process exited with unexpected exit code: 127

**Comment by Youska35** [comment]
mine crashes also has anyone found a way to fix this?

**Comment by ChristopherHX** [comment]
_This bug report is invalid_, you have not filled the issue template._

Install `libEGL.so.1`, but without knowing anything about your Linux Distribution this is all I can provide.
