### ISSUE TITLE
Stuck On "Please Wait... ..." 

### ISSUE THREAD

**Issue by Virtualffg** [minecraft-linux/mcpelauncher-manifest#702]
My launcher has been stuck on please wait for a long long while now and I have been using the appimage as an alternative which has it has been working great with few minor inconveniences such as not being able to copy and paste.

Does anyone have any idea on what is wrong with this, or on what process it's stuck on? The version list shows only downloaded versions and the troubleshooter says it failed to obtain gameversion while the appimage works perfectly compared to the flatpak version. I unistalled it deleted all data reinstalled everything and it keeps bugging out anything more i could try?

**Comment by Virtualffg** [comment]
I have also noticed that on the appimage there is support for x86 but the flatpak one says it's incompatible

**Comment by smoliicek** [comment]
Flatpak version is broken. Happens to me too. You must use .appimage.

**Comment by ChristopherHX** [comment]
Fixed in flatpak v0.4.0, the AppImage won't receive this update.
