### ISSUE TITLE
[QUESTION] End of development 

### ISSUE THREAD

**Issue by adv3r** [minecraft-linux/mcpelauncher-manifest#703]
Is this true that the Linux Minecraft Launcher is a discontinued project? The are some rumors among MCPE community that 1.18 is the last version that could be playable with this launcher...

Thanks in advance for your answer!

**Comment by TwilightSublime** [comment]
yes

**Comment by ChristopherHX** [comment]
No, see commit history
- https://github.com/minecraft-linux/mcpelauncher-manifest/commits/ng
- https://github.com/minecraft-linux/mcpelauncher-ui-manifest/commits/ng

> The are some rumors among MCPE community that 1.18 is the last version that could be playable with this launcher...

It's true that 1.19 doesn't work yet.
"No latest version support" is not the same as "End of Development", your opinion might be different.
