### ISSUE TITLE
1.19

### ISSUE THREAD

**Issue by ghost** [minecraft-linux/mcpelauncher-manifest#704]
I still cannot play 1.19 yet, I'm sure I have updated the launcher and I still cannot use it. I have waited and checked here constantly for updates, I do not want to be a bother to the people that allow us to even have this launcher but I have a series I'm doing with my friends that I cannot attend because of this.

**Comment by Teunboeke** [comment]
Yea same im also waiting but it's already over 2 weeks now 🤔

**Comment by nobody5050** [comment]
duplicates #691

**Comment by hirqkii** [comment]
where is the update guys

**Comment by Mhowser** [comment]
@hirqkii spamming the developer will only slow the process down, try doing something more constructive with your time.
