### ISSUE TITLE
THE CROSSHAIR ON ANY CUSTOM PACK DOES NOT SHOW! ONLY SHOWS WITH A WHITE BOX COVERING IT!

### ISSUE THREAD

**Issue by shaun756** [minecraft-linux/mcpelauncher-manifest#705]
Look at this picture for more detail  ---> (https://user-images.githubusercontent.com/81907808/179406012-fc50f8d4-4cf7-4f26-aa0a-eea9a36e6764.png)

**Comment by ChristopherHX** [comment]
_This bug report is invalid_, you have neither filled the issue template or provided the broken pack.

> THE CROSSHAIR ON ANY CUSTOM PACK DOES NOT SHOW!

No your custom pack is just incompatible, I added a custom pack with a crosshair on macOS x86_64 and it has a transparent background.
