### ISSUE TITLE
Gamepad support

### ISSUE THREAD

**Issue by Pedro1234-code** [minecraft-linux/mcpelauncher-manifest#707]
**Is your feature request related to a problem? Please describe.**
I want the gamepad support for the launcher

**Describe the solution you'd like**
I want to be able to use a gamepad on the launcher.

**Comment by ChristopherHX** [comment]
Available since over 3 years.
https://mcpelauncher.readthedocs.io/en/latest/troubleshooting.html#the-controller-doesn-t-work-at-all-or-you-want-to-remap-your-gamepad-buttons-analogsticks-dpad-and-triggers

**Comment by Pedro1234-code** [comment]
In my case, I have a Xbox One S controller connected via bluetooth and it simply doesn't work. Already tried everything, and it runs perfectly on Steam and Xcloud.

Here is my log: 

17:52:56 Info  [Launcher] Version: client 1e44372 / manifest 680d827
17:52:56 Info  [Launcher] CPU: GenuineIntel Intel(R) Core(TM) i3-10110U CPU @ 2.10GHz
17:52:56 Info  [Launcher] CPU supports SSSE3: YES
17:52:56 Trace [Launcher] Loading hybris libraries
17:52:56 Trace [REDIRECT] /data/data/com.mojang.minecraftpe to /home/pedro/.local/share/mcpelauncher/
17:52:56 Trace [REDIRECT] /data/data/tmp/.mount_MinecrNMcoRd/usr/proc/39681/cmdline to /home/pedro/.local/share/mcpelauncher/
17:52:56 Trace [REDIRECT] /data/data/tmp/.mount_MinecrNMcoRd/usr/bin/./mcpelauncher-client to /home/pedro/.local/share/mcpelauncher/
17:52:56 Trace [REDIRECT] /data/data to /home/pedro/.local/share/mcpelauncher/
17:52:56 Trace [LinkerUtils] Loaded OS library libm.so.6
17:52:56 Trace [LinkerUtils] Loaded OS library libz.so.1
17:52:56 Trace [LinkerUtils] Loaded OS library /tmp/.mount_MinecrNMcoRd/usr/share/mcpelauncher/lib/native/x86_64/libfmod.so.12.0
17:52:56 Trace [Launcher] Loading Minecraft library
Found hook: _ZN11AppPlatform16showMousePointerEv @ 0xb80250
Found hook: _ZN11AppPlatform16hideMousePointerEv @ 0xb80220
17:52:56 Info  [Launcher] Loaded Minecraft library
17:52:56 Debug [Launcher] Minecraft is at offset 0x0x7f1d71240000
17:52:56 Info  [Launcher] Game version: 0.0.0.0
17:52:56 Info  [Launcher] Applying patches
17:52:56 Debug [CorePatches] Failed to patch, vtable _ZTV21AppPlatform_android23 not found
17:52:56 Info  [Launcher] Initializing JNI
17:52:56 Error [JniSupport] Missing native symbol: Java_com_mojang_minecraftpe_MainActivity_nativeRegisterThis
17:52:56 Error [JniSupport] Missing native symbol: Java_com_mojang_minecraftpe_MainActivity_nativeUnregisterThis
17:52:56 Error [JniSupport] Missing native symbol: Java_com_microsoft_xal_browser_WebView_urlOperationSucceeded
17:52:56 Info  [Launcher] Executing main thread
17:52:56 Trace [Minecraft] Entering JNI_OnLoad 0x7f1d917ff640
17:52:56 Trace [Minecraft] JNI_OnLoad completed
17:52:56 Trace [JniSupport] Invoking nativeRegisterThis
17:52:56 Trace [JniSupport] Invoking ANativeActivity_onCreate
17:52:56 Warn  [Main] Android stub called
17:52:56 Warn  [Main] Android stub called
17:52:56 Warn  [Main] Android stub called
17:52:56 Warn  [Main] Android stub called
17:52:56 Info  [Launcher] Loading gamepad mappings
17:52:56 Trace [Launcher] Loading gamepad mappings: /tmp/.mount_MinecrNMcoRd/usr/share/mcpelauncher/gamecontrollerdb.txt
17:52:56 Info  [Launcher] Creating window
17:52:56 Info  [Minecraft] android_main starting. internalDataPath is '/internal', externalDataPath is '/external'
17:52:56 Trace [JniSupport] Invoking start activity callbacks
17:52:56 Error [MCPE] *** setCachedDeviceId(674f18bb-5b9a-4452-844f-6271e8fc2f80)
17:52:56 Info  [Bedrock] configureBreakpad with directory: /crash, sessionid is: 13a5d58b-b3d7-49c6-9dee-d65d879dae29
17:52:56 Info  [Bedrock] configureBreakpad called, directory is: /crash, sessionid is: 13a5d58b-b3d7-49c6-9dee-d65d879dae29
17:52:56 Info  [Minecraft] NO LOG FILE! - AppPlatform_android::setStorageDirectory - using External dir (NEW) - CurrentFileStoragePath is now '/home/pedro/.local/share/mcpelauncher/'
17:52:56 Warn  [Main] Android stub called
17:52:56 Warn  [Main] Android stub called
17:52:56 Warn  [Minecraft] NO LOG FILE! - [Device Lost] The graphics context was gained
17:52:56 Warn  [Minecraft] MinecraftGame::init && MinecraftGame::setSize!
17:52:57 Debug [HttpCallStaticGlue] Successfully registerered HttpCall methods
17:52:57 Debug [XboxLiveAppConfig] Successfully registerered XboxLiveAppConfig methods
17:52:57 Debug [XSAPI.Android] Successfully registerered HttpCall tcuiMethods
17:52:57 Debug [XSAPI.Android] Successfully registerered telemetryMethods
17:52:59 Info  [Minecraft] NO LOG FILE! - Time played notifier not required for 'en'
libevdev_new_from_fd error -22 (/dev/input/js0)
17:53:14 Trace [WindowCallbacks] Gamepad connected #0
LinuxJoystick::pool error

**Comment by ChristopherHX** [comment]
> Already tried everything

What have you tried? Based on your log you haven't correctly tried to create a gamepad mapping otherwise the file path would be in the log.
Please follow the wiki to add an gamepad mapping to this file for your controller `~/.local/share/mcpelauncher/gamecontrollerdb.txt`

You have to put a line like this for your controller into the file mentioned above
```
030000005e040000ea02000008040000,Microsoft Xbox One S,a:b0,b:b1,back:b6,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,guide:b8,leftshoulder:b4,leftstick:b9,lefttrigger:a2,leftx:a0,lefty:a1,rightshoulder:b5,rightstick:b10,righttrigger:a5,rightx:a3,righty:a4,start:b7,x:b2,y:b3,platform:Linux,
```

> 17:53:14 Trace [WindowCallbacks] Gamepad connected #0

Your gamepad is detected by the launcher

Steam and Xcloud are big companies vs a very small open source project and have better useability

**Comment by mdaffailhami** [comment]
> > Already tried everything
> 
> What have you tried? Based on your log you haven't correctly tried to create a gamepad mapping otherwise the file path would be in the log. Please follow the wiki to add an gamepad mapping to this file for your controller `~/.local/share/mcpelauncher/gamecontrollerdb.txt`
> 
> You have to put a line like this for your controller into the file mentioned above
> 
> ```
> 030000005e040000ea02000008040000,Microsoft Xbox One S,a:b0,b:b1,back:b6,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,guide:b8,leftshoulder:b4,leftstick:b9,lefttrigger:a2,leftx:a0,lefty:a1,rightshoulder:b5,rightstick:b10,righttrigger:a5,rightx:a3,righty:a4,start:b7,x:b2,y:b3,platform:Linux,
> ```
> 
> > 17:53:14 Trace [WindowCallbacks] Gamepad connected #0
> 
> Your gamepad is detected by the launcher
> 
> Steam and Xcloud are big companies vs a very small open source project and have better useability

What is "030000005e040000ea02000008040000"?

**Comment by ChristopherHX** [comment]
> What is "030000005e040000ea02000008040000"?

The gampad id. This is described in the wiki.
