### ISSUE TITLE
Curl Download Error

### ISSUE THREAD

**Issue by utzlol** [minecraft-linux/mcpelauncher-manifest#716]
**Describe the bug**
The message appear when downloading minecraft is finish and it only happens with version 1.18 and higher

Failed to perform http request to url : CURLcode 23 Details: Failure writing output to destination

**Comment by ChristopherHX** [comment]
Do you run out of disk space on /tmp?

_I removed the link to non redistributable content and deleted the orignal comment_

**Comment by utzlol** [comment]
That's right. It works after temporary directory expanded.

**Comment by ChristopherHX** [comment]
Flatpak is affected

**Comment by ChristopherHX** [comment]
Fix rolled out for the qt6 branch of mcpelauncher-ui-manifest, https://github.com/minecraft-linux/mcpelauncher-ui-manifest/commit/485df2e65790bea348cf9397e4ad49b3002dbe8d.
Moving the apk download location into the mcpelauncher data folder, no longer store the apks into the default tmp location.

**Comment by ChristopherHX** [comment]
To download the game using the webbrowser there  is now a way described at the link target
_Issue Group https://github.com/minecraft-linux/mcpelauncher-wiki/issues/89, to backlink everything together_
