### ISSUE TITLE
Progress for adding 1.19.50 support

### ISSUE THREAD

**Issue by ChristopherHX** [minecraft-linux/mcpelauncher-manifest#719]
- [x] fmod update, need to load a newer fmod version to provide the requested symbols.
Probably not easy to do version detection, when a new fmod is needed. **Workaround** run with flag `-df`, you may need pulseaudio during compiling the launcher to have sound.
New Reference `_ZN4FMOD14ChannelControl19get3DMinMaxDistanceEPfS1_`
- [x] `lstat` needs to be added to `libc-shim`
New reference `lstat` from `libc++_shared.so` and more, contributed by @0xCatPKG 2022-10-22

Planned for 2023.

**Comment by GameParrot** [comment]
Manually adding the symbols to the fmod symbols file results in the game opening with sound (with the bundled fmod). However, the game freezes on exit unless `--disable-fmod` is passed (passing `--disable-fmod` results in no sound for me). Maybe an option to choose the fmod library path could be added to `mcpelauncher-client` and the launcher UI (`mcpelauncher-ui-qt`) could set the path depending on the version launched. I am using Linux Mint 21.
Edit: I was able to build with PulseAudio and get sound without `--disable-fmod` (causes the freeze on exit when using PulseAudio)

**Comment by ChristopherHX** [comment]
@GameParrot Thank you for experimenting, the missing fmod symbol is indeed in the current mcpelauncher-linux-bin of fmod so no update is necessary.

I added all missing fmod symbols from a readelf dump to the list https://github.com/minecraft-linux/minecraft-imported-symbols/commit/05168fbf6eda5ca83978deeefc896a5d3fca4d2c

I will close this once this has been merged into this meta repo.
