### ISSUE TITLE
1.19.31 just won't install

### ISSUE THREAD

**Issue by tanoninhlol** [minecraft-linux/mcpelauncher-manifest#723]
That's the error that's making it not download ( i have mobile bedrock on my phone)

Failed to perform http request to  : CURLcode 23 Details: Failure writing output to destination

**Comment by ChristopherHX** [comment]
Please download the AppImage, known issue with 4GB of RAM or lower and using the flatpak.

The game size is growing and the flatpak only allocates 10% of your RAM size for tmp files, but the game now takes more than 400MB.

Duplicate of #716
