### ISSUE TITLE
Marketplace not working

### ISSUE THREAD

**Issue by mysnappyNT0980** [minecraft-linux/mcpelauncher-manifest#754]
The marketplace says "invalid session"
when i restart the game it still says the same
i already logged on

I am playing on 1.19.41 I'm pretty sure

**Comment by ghost** [comment]
the last update fixed it for me, although i still cannot download legacy texture from marketplace, and select custom skin texture (says, "this is not a minecraft skin, silly") and cannot create new characters others dont load

**Comment by ghost** [comment]
okay chaning the file path makes it recongnize the skin, i think file paths are bugged (mine had a space in a folders name and the file itself had a bracket in the name, this should normally not be a problem though)

update: ok wrong, its a special character i just realized in the folder's name (#53)
