### ISSUE TITLE
Sprinting is... weird?

### ISSUE THREAD

**Issue by lightyisreal** [minecraft-linux/mcpelauncher-manifest#761]
Basically, whenever I sprint it instantly stops.

**To Reproduce**
Steps to reproduce the behavior (at least, this is all I can get):
1. Try sprinting using the CTRL key
2. After you release the CTRL key, it should stop sprinting instantly

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Version v0.8.0-flatpak-qt6 (build 55)
 - Installation Type: Flatpak

**Comment by lightyisreal** [comment]
Seems to happen more when I press either A or D while sprinting

**Comment by lightyisreal** [comment]
It happens on the latest version, 1.19.51. My guess is probably because of some changes on the game code rather than the launcher code

**Comment by ZonyaZap** [comment]
I've heard backwards sprint got patched in 1.19.40, maybe they patched it so good, you can only only sprint forwards and not diagonally? Downgrading to 1.19.31 fixed this issue for me.

**Comment by lightyisreal** [comment]
> I've heard backwards sprint got patched in 1.19.40, maybe they patched it so good, you can only only sprint forwards and not diagonally? Downgrading to 1.19.31 fixed this issue for me.

I have to run the latest version for some stuff, but it's strange it doesn't work. In Windows diagonal sprinting works flawlessly

**Comment by ChristopherHX** [comment]
Please report it to [mojang](https://bugs.mojang.com/projects/MCPE/issues/), seems like an x86/x86_64 android bug.  I can reproduce this in bluestacks, which has nothing in common other than the x86_64 arch.

This bug doesn't happen on my arm based phone....

**Comment by ZonyaZap** [comment]
Can confirm, I plugged in a keyboard and mouse to my phone (obviously arm based) and had no problem sprinting diagonally on latest version of Minecraft at the time of writing this.

**Comment by ChristopherHX** [comment]
Raspberry Pi 4 using launcher version v0.8.0 not affected by this bug. So the inputs the launcher creates are valid to allow sprinting diagonally.

_I don't have time to fix mojangs game bugs for intel and amd devices_
