### ISSUE TITLE
Unable to join friends' games, and they are unable to join mine

### ISSUE THREAD

**Issue by Scaprod** [minecraft-linux/mcpelauncher-manifest#765]
**Describe the bug**
The bug prevents me from joining a player hosted game, and other people from joining my hosted game, even if I invite them.

**To Reproduce**
1. Have a friend host a game
2. Go to your friends list
3. Click on the friend that is hosting
This will eventually time out.

Alternative:
1. Host a game
2. Have a friend go to their friends list
They will not be able to see your game, even if you invite them.

**Expected behavior**
I expected to be able to connect to my friends' servers, and for them to connect to mine.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Manjaro Linux
 - Version: Unknown (build Unknown)
 - Installation Type: Built from source

**Additional context**
Version 1.19.51.01 was used for this. It also tells me that my Microsoft account was disconnected.

**Comment by Scaprod** [comment]
Update: I have managed to figure out that my Minecraft PE build number is 12894694, which is one number behind the MCPE build number on my phone, and of my other friends. Is this related?

**Comment by guighub** [comment]
I have this problem too, the invite screen also says my Microsoft account was disconnected even though I signed in and can see my friends in the list.

**Comment by Z3R0C1PH3R** [comment]
Samee, whenever i try to join my friends world it gets stuck on this screen 
![image](https://user-images.githubusercontent.com/59080407/216540154-14c34fee-88c9-4138-8d82-9303ff4e936c.png)

**Comment by DerHalbGrieche** [comment]
Yep, I have the exact problems described above

**Comment by argonptg** [comment]
Issue still present on 1.19.60

**Comment by antonioastro** [comment]
I also have this same issue. I got around this because we are on the same internet connection and connecting via LAN, but today for seemingly no reason at all this stopped working too
