### ISSUE TITLE
Add toggle for Metal on macOS

### ISSUE THREAD

**Issue by GameParrot** [minecraft-linux/mcpelauncher-manifest#768]
**Is your feature request related to a problem? Please describe.**
In the release notes, it states that Metal was disabled due to bug reports

**Describe the solution you'd like**
An option to enable/disable Metal in the Launcher settings

**Describe alternatives you've considered**

**Additional context**
To get Metal to work better, you have to request OpenGL ES 3.0 in window_glfw.cpp

**Comment by GameParrot** [comment]
Metal with OpenGL ES 2.0 requested: 
![Screen Shot 2023-01-27 at 6 43 00 AM  1-27-23](https://user-images.githubusercontent.com/85067619/215078715-d86da6f0-64b3-4792-b33e-41430d381c87.jpg)

Metal with OpenGL ES 3.0 requested:
![Screen Shot 2023-01-27 at 6 41 50 AM  1-27-23](https://user-images.githubusercontent.com/85067619/215078771-5ca18b5a-0299-4e11-a7fa-9c78504c0943.jpg)


Also, the low memory error does not occur with OpenGL ES 3.0 requested.

**Comment by ChristopherHX** [comment]
Which difference do you notice? between es2 and es3

For me are looking both screenshots the same. All reported bugs with renderdragon couldn't be reproduced on my end.

- broken menu in 1.18.12
- blackscreen (Only reproducable for me with macOS 10.13 sdk + target 10.10/10.12)

**Comment by GameParrot** [comment]
> Which difference do you notice? between es2 and es3
> 
> For me are looking both screenshots the same. All reported bugs with renderdragon couldn't be reproduced on my end.
> 
>     * broken menu in 1.18.12
> 
>     * blackscreen (Only reproducable for me with macOS 10.13 sdk + target 10.10/10.12)

If you zoom in, you can see that distant textures don't look as good with es2. These images are in 4k and the difference may be unnoticeable on a lower resolution screen. Also, the game shows a low memory error when joining a world with es2, but not with es3. I also think the bugs reported with metal only happen on certain hardware or macOS versions (maybe asking users to submit info about their device (like their GPU) could help. My guess is that the issues occur more on older Macs.)

**Comment by ChristopherHX** [comment]
> My guess is that the issues occur more on older Macs.

Do you think they have something older than a intelhd4000 from 2012 and macOS 10.13+ with a metal2 GPU? I don't think there a many devices, which could match

> the game shows a low memory error

Sounds like a 4k only issue, my 1366x768 doesn't show it under metal.

Seems like only the metal backend renders via es2, opengl uses es3 on renderdragon.

**Comment by GameParrot** [comment]
> > My guess is that the issues occur more on older Macs.
> 
> Do you think they have something older than a intelhd4000 from 2012 and macOS 10.13+ with a metal2 GPU? I don't think there a many devices, which could match
> 
> > the game shows a low memory error
> 
> Sounds like a 4k only issue, my 1366x768 doesn't show it under metal.
> 
> Seems like only the metal backend renders via es2, opengl uses es3 on renderdragon.

Sounds possible that it is only with gpus older than a intelhd 4000. Also, the metal backend uses es2 because the major version requested in window_glfw.cpp is 2. If you set that to 3, then metal uses es3. The Launcher could always load the OpenGL backend for gpus that have problems with the metal backend.

**Comment by ChristopherHX** [comment]
> The Launcher could always load the OpenGL backend for gpus that have problems with the metal backend.

I don't want to add such a complexity.

The angle source code has been altered to have metal by default and use opengl on old macOS < 10.13 or i386 or without a metal 2 gpu.

**Comment by ChristopherHX** [comment]
_You can always copy the libEGL.dylib + libGLESv2.dylib from my 0.6.0 dmg file into another release and metal is back for 1.19.51 and other game versions_

**Comment by ChristopherHX** [comment]
Merged, metal is opt in.
