### ISSUE TITLE
More info about the 56% freeze

### ISSUE THREAD

**Issue by GameParrot** [minecraft-linux/mcpelauncher-manifest#771]
Here is some more information I found regarding the 56% freeze:
- On Linux, the `Graphics context gained` message is logged twice before and once after the `MinecraftGame::init && MinecraftGame::setSize` message when the game does not freeze at 56%. When the game does freeze at 56%, the `Graphics context gained` is logged once before the `MinecraftGame::init && MinecraftGame::setSize` message and twice after.
- on macOS, the `Graphics context gained` is logged once before the `MinecraftGame::init && MinecraftGame::setSize` message no matter what. When the game does not freeze, it is logged once after, just like linux. It is logged twice after when it freezes, just like linux.
- I have not been able to get the x86_64 version passed 56% on a 2014 Macbook Air running High Sierra. I have been able to get the x86 version working, however.

**Comment by ChristopherHX** [comment]
Yes seeing multiple `Graphics context gained` in the log sounds like a potential problem. Maybe the game logic assumes init has failed and retry? Other way around I just ignored it after seeing the loading screen.

> I have not been able to get the x86_64 version passed 56%

I'm able to use the x86_64 version on both Sierra and Mojave.

_You have no idea how many hours of trial and error it took me last year to get rid of the blackscreen of 1.18.30+ on linux, it was very close to give up._

Why opening a new issue? This is the third in this repo.

**Comment by GameParrot** [comment]
A temporary solution could be to have the Launcher detect if the game will freeze using the log messages and kill the game if it detects that it will freeze.

> Yes seeing multiple `Graphics context gained` in the log sounds like a potential problem. Maybe the game logic assumes init has failed and retry? Other way around I just ignored it after seeing the loading screen.

I think that is likely the problem. I also edited fake_egl.cpp to make it print every EGL function call and I did not notice a difference between when it froze and when it did not freeze. On my hardware, it happens like 15-20% of the time.

**Comment by ChristopherHX** [comment]
Does https://github.com/minecraft-linux/mcpelauncher-client/pull/40 make the issue happen **0%** of the time?

**Comment by ChristopherHX** [comment]
Graphics context gained is still printed multiple times, but does not cause problems for me

**Comment by GameParrot** [comment]
> 

That fixed it for me on both Linux and a 2019 iMac running macOS Monterey. I have not tested it on the 2014 MacBook Air yet.
