### ISSUE TITLE
Minecraft gets stuck at 56% in MacOS

### ISSUE THREAD

**Issue by GamerBoyTapan** [minecraft-linux/mcpelauncher-manifest#777]
**Describe the bug**
Minecraft Latest Compatible version is stuck at 56%. It gests stuck at 
11:08:54 Debug [XSAPI.Android] Successfully registerered HttpCall tcuiMethods
in the log file

**To Reproduce**
11:08:50 Info  [Launcher] Version: client 458673e / manifest 773cb50
11:08:50 Info  [Launcher] CPU: GenuineIntel VirtualApple @ 2.50GHz
11:08:50 Info  [Launcher] CPU supports SSSE3: YES
11:08:50 Trace [Launcher] Loading hybris libraries
11:08:50 Trace [REDIRECT] /data/data/com.mojang.minecraftpe to /Users/tapan/Library/Application Support/mcpelauncher/
11:08:50 Trace [REDIRECT] /data/data/Applications/Minecraft Bedrock Launcher.app/Contents/proc/3445/cmdline to /Users/tapan/Library/Application Support/mcpelauncher/
11:08:50 Trace [REDIRECT] /data/data/Applications/Minecraft Bedrock Launcher.app/Contents/MacOS/./mcpelauncher-client to /Users/tapan/Library/Application Support/mcpelauncher/
11:08:50 Trace [REDIRECT] /data/data to /Users/tapan/Library/Application Support/mcpelauncher/
11:08:50 Trace [LinkerUtils] Loaded OS library libm.dylib
11:08:50 Trace [LinkerUtils] Loaded OS library libz.dylib
11:08:50 Trace [LinkerUtils] Loaded OS library /Applications/Minecraft Bedrock Launcher.app/Contents/Resources/mcpelauncher/lib/native/x86_64/libfmod.dylib
11:08:50 Trace [Launcher] Loading Minecraft library
11:08:50 Error [MinecraftUtils] Failed to load Minecraft: dlopen failed: cannot locate symbol "glBindRenderbuffer" referenced by "/Users/tapan/Library/Application Support/mcpelauncher/versions/1.19.51.01/lib/x86_64/libminecraftpe.so"...
11:08:50 Info  [Launcher] Loading gamepad mappings
11:08:50 Trace [Launcher] Loading gamepad mappings: /Applications/Minecraft Bedrock Launcher.app/Contents/Resources/mcpelauncher/gamecontrollerdb.txt
11:08:50 Info  [Launcher] Creating window
Found hook: _ZN11AppPlatform16showMousePointerEv @ 0x102412fc0
Found hook: _ZN11AppPlatform16hideMousePointerEv @ 0x102412fa0
11:08:51 Info  [Launcher] Loaded Minecraft library
11:08:51 Debug [Launcher] Minecraft is at offset 0x115BC0000
11:08:51 Info  [Launcher] Game version: 0.0.0.0
11:08:51 Info  [Launcher] Applying patches
11:08:51 Debug [CorePatches] Failed to patch, vtable _ZTV21AppPlatform_android23 not found
11:08:51 Info  [Launcher] Initializing JNI
11:08:51 Error [JniSupport] Missing native symbol: Java_com_mojang_minecraftpe_MainActivity_nativeRegisterThis
11:08:51 Error [JniSupport] Missing native symbol: Java_com_mojang_minecraftpe_MainActivity_nativeInitializeWithApplicationContext
11:08:51 Error [JniSupport] Missing native symbol: Java_com_mojang_minecraftpe_MainActivity_nativeUnregisterThis
11:08:51 Error [JniSupport] Missing native symbol: Java_com_mojang_minecraftpe_MainActivity_nativeinitializeLibHttpClient
11:08:51 Error [JniSupport] Missing native symbol: Java_com_microsoft_xal_browser_WebView_urlOperationSucceeded
11:08:51 Info  [Launcher] Executing main thread
11:08:51 Trace [Minecraft] Entering JNI_OnLoad 0x309f4b000
11:08:51 Trace [Minecraft] JNI_OnLoad completed
11:08:51 Trace [JniSupport] Invoking nativeRegisterThis
11:08:51 Trace [JniSupport] Invoking ANativeActivity_onCreate
11:08:51 Warn  [Main] Android stub called
11:08:51 Warn  [Main] Android stub called
11:08:51 Warn  [Main] Android stub called
11:08:51 Warn  [Main] Android stub called
11:08:51 Info  [Minecraft] android_main starting. internalDataPath is '/internal', externalDataPath is '/external'
11:08:51 Trace [JniSupport] Invoking start activity callbacks
11:08:51 Error [MCPE] *** setCachedDeviceId(b8e42799-f4d5-43d6-8382-8a735837122e)
11:08:51 Info  [Bedrock] configureBreakpad with directory: /crash, sessionid is: 42a5a70e-e87d-4ff9-890f-1219f6d8cfaf
11:08:51 Info  [Bedrock] configureBreakpad called, directory is: /crash, sessionid is: 42a5a70e-e87d-4ff9-890f-1219f6d8cfaf
11:08:51 Info  [Minecraft] NO LOG FILE! - AppPlatform_android::setStorageDirectory - using External dir (NEW) - CurrentFileStoragePath is now '/Users/tapan/Library/Application Support/mcpelauncher/'
11:08:51 Warn  [Minecraft] NO LOG FILE! - [Graphics] The graphics context was gained
11:08:51 Warn  [Minecraft] MinecraftGame::init && MinecraftGame::setSize!
11:08:51 Warn  [FakeEGL] eglQueryString 308d
11:08:51 Warn  [Main] Android stub called
11:08:51 Warn  [Main] Android stub called
11:08:52 Warn  [Minecraft] NO LOG FILE! - [Graphics] The graphics context was gained
11:08:52 Warn  [Minecraft] NO LOG FILE! - [Graphics] The graphics context was gained
11:08:53 Warn  [Main] Android stub called
11:08:54 Debug [HttpCallStaticGlue] Successfully registerered HttpCall methods
11:08:54 Debug [XboxLiveAppConfig] Successfully registerered XboxLiveAppConfig methods
11:08:54 Debug [XSAPI.Android] Successfully registerered HttpCall tcuiMethods

**Expected behavior**
I Thought it would open.

**Screenshots**

<img width="1174" alt="Screenshot 2023-02-04 at 11 11 41 AM" src="https://user-images.githubusercontent.com/104846980/216751008-76e0985c-5d21-4278-a516-05f81959d499.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Version Minecraft_Bedrock_Launcher_v0.8.0-macOS-x86_64-0.0.394_macOS_10.10.0.dmg
 - Installation Type dmg

**Additional context**
Bruh I spent money pls fix

**Comment by ChristopherHX** [comment]
> Bruh I spent money

I also spent money and I need to fix my issues myself.

Anyways, you can be lucky that I found a way to fix this 1 year old issue before you reported it.

Please update to v0.8.1 and your problem is gone. Otherwise 1.18.12 was never affected.
