### ISSUE TITLE
Launcher Crashes When Trying TO Launch Minecraft 

### ISSUE THREAD

**Issue by EVOonchromebook** [minecraft-linux/mcpelauncher-manifest#779]
Whenever i Click On play when in the launcher, The game pauses then crashes instantly. I have tried restarting my device etc nothing seems to work. This has only happened since the new launcher update

1. open launcher
2. Click on play
3. Game Crashes

 - OS: Chrome OS
 - Version Minecraft_Bedrock_Launcher-arm_aarch64-v0.3.3.683.AppImage
 - Installation Appimage

**Comment by AlexLexusYTXD** [comment]
well big e

**Comment by ChristopherHX** [comment]
A problematic change has been reverted. There were stack corruption for arm64 devices.

Next time please provide the correct version, use the version shown in the launcher main page.

Until the next update, downgrade to https://github.com/ChristopherHX/linux-packaging-scripts/releases/tag/v0.8.0-700

**Comment by ChristopherHX** [comment]
Fixed in 0.8.5
