### ISSUE TITLE
Amazon Support

### ISSUE THREAD

**Issue by ghost** [minecraft-linux/mcpelauncher-manifest#781]
**Sign in with Amazon**

I was wondering if it's possible to sign in with Amazon? I would love if there is an option where you could sign in with Amazon.

**Comment by TheKrafter** [comment]
this app uses the google play store, so that'd probably require a large development effort and lots of time.

**Comment by AYT04** [comment]
> this app uses the google play store, so that'd probably require a large development effort and lots of time.

I was wondering if it were possible for me to change the URL from Google to Amazon, as I own the game via Amazon's store not Google. Its seems like a simple thing to add, but I'm guessing there is more than to just that. Just curious.

**Comment by Mhowser** [comment]
It is not, amazon does not have any API for downloading the app.

**Comment by AYT04** [comment]
> It is not, amazon does not have any API for downloading the app.

Alright, thanks for letting me know.
