### ISSUE TITLE
Exporting Structure Block Files.

### ISSUE THREAD

**Issue by garynosmash** [minecraft-linux/mcpelauncher-manifest#782]
The exporting mcstructure files was added to mobile bedrock around 1.16, but the button remained hidden, with a resource pack it was able to show the button and export the structure file on mobile.  When i try this on my laptop running Ubuntu with the resource pack it spins indefinitely and doesn't export the file

**Comment by GameParrot** [comment]
I have a fix for this locally, and I will make a PR soon.
