### ISSUE TITLE
The store does not work from 1.19

### ISSUE THREAD

**Issue by paperlyly** [minecraft-linux/mcpelauncher-manifest#787]
**Describe the bug**
You can't download skins, textures, maps or clothes of the store

**To Reproduce**
1. Open the store2
2. try to download any skins pack
3. you are downloading forever or says that the store had connection problems

I understand that it is not normal that the bears cannot be used, Thanks for your attention, and thanks for this beautiful launcher!

**Desktop (please complete the following information):**
 - OS: manjaro
 - Version 0.8.1
 - Installation Type appimage

**Comment by ChristopherHX** [comment]
Fixed version 0.8.5
