### ISSUE TITLE
Stuck on "DOWNLAOD AND PLAY Please wait..."

### ISSUE THREAD

**Issue by sangoku116** [minecraft-linux/mcpelauncher-manifest#79]
I am running manjaro linux, I have installed the following from the AUR `mcpelauncher-msa-git mcpelauncher-msa-ui-qt-git mcpelauncher-linux-git mcpelauncher-ui-git` . I signed in using my google account after purchasing the game. Now I am stuck on a white loading screen with "DOWNLOAD AND PLAY Please wait..." in the green box at the bottom right.

**Comment by Mhowser** [comment]
Did you agree to Google's ToS? There should have been a dialogue box that
pops up right after you sign in and you must select "I agree" to download
Minecraft.

**Comment by MCMrARM** [comment]
Currently Google Play login is broken unfortunately, I'm working on fixing this.

**Comment by sangoku116** [comment]
> Currently Google Play login is broken unfortunately, I'm working on fixing this.
Awesome, thank you. I managed to play the game by selecting the version at the bottom left, but latest(google play) is indeed broken.

**Comment by maxdrash** [comment]
`http request: https://android.clients.google.com/fdfe/uploadDeviceConfig, body = 
� (
http response body: 97Error retrieving information from server. [DF-DFERH-01]J�
�Ѩ������
#�i
api response body = commands {
  displayErrorMessage: "Error retrieving information from server. [DF-DFERH-01]"
}
serverLogsCookie: 

http request: https://android.clients.google.com/fdfe/toc, body = 
http response body: 
2X*4J�
�׳����E��
�
api response body = payload {
  tocResponse {
    requiresUploadDeviceConfig: true
  }
}
`

Yes, it's broken.

**Comment by MCMrARM** [comment]
The workaround is to manually pick the version (click the pencil in bottom left, select the version) and it'll download and install it. I'll be fixing this later.

**Comment by maxdrash** [comment]
Thanks for this tip.
Was not working too, but after deleting theses directories and re-apply a version with the pencil I was able to download and launch mcpe: 
.config/Minecraft\ Linux\ Launcher/
.local/share/mcpelauncher/
.local/share/Minecraft\ Linux\ Launcher/
.cache/Minecraft\ Linux\ Launcher/

But another problem appears: the launcher claim libEGL.so but this lib are already already installed x86_64 and i386 too.
Same this the appimage.

**Comment by maxdrash** [comment]
Hi.
Have you any idea ?

Thanks.

/usr/bin/mcpelauncher-client: error while loading shared libraries: libEGL.so.1: cannot open shared object file: No such file or directory
Process exited with unexpected exit code: 127

**Comment by maxdrash** [comment]
I've installed all libegl with x86 dependancies from repos and it works now.

**Comment by Mhowser** [comment]
Please close the issue if it is resolved

**Comment by maxdrash** [comment]
It's not solved.
We can get around the problem but it is not solved.

**Comment by Mhowser** [comment]
Oh ok, gotcha.

**Comment by MCMrARM** [comment]
Google Play login issue is solved.

**Comment by ghost** [comment]
google play login is fixed but i still have this issue on v0.3.2 build 34 from flatpak (amd64)
