### ISSUE TITLE
Wrong SSSE3 detection.

### ISSUE THREAD

**Issue by inferrna** [minecraft-linux/mcpelauncher-manifest#793]
Shows "No SSSE3" for my 2680v2

![image](https://user-images.githubusercontent.com/4245277/219850316-0d8c64c4-384b-4f3b-9fec-5a6a15f32395.png)

OS: Clear Linux
CPU: Xeon 2680v2

**Comment by ChristopherHX** [comment]
It's the old SSSE3 check, the newer one with `Compatible` is working. 

_Do you report this error, because you cannot open the game?_

On my system is the old SSSE3 check working, because the launcher (`mcpelauncher-client -v`) doesn't fail due to a fatal error.

**Comment by ChristopherHX** [comment]
Fixed  https://github.com/minecraft-linux/mcpelauncher-ui-qt/commit/6b983d896109993002e658a6bd011a2352c4c401?diff=unified

You will see another error, based on your bug report.
