### ISSUE TITLE
MICROSOFT ACCOUNT DISCONNECTED EVERY TIME

### ISSUE THREAD

**Issue by AlexLexusYTXD** [minecraft-linux/mcpelauncher-manifest#798]
**Error**
I cannot invite anyone to my world, nor I can join my friends.

**To Reproduce**
1. Go to MC launcher
2. Launch MC
3. Make a singleplayer world
4. Click ESC
5. "Oops! Your microsoft account was disconnected..."

**Expected behavior**
It was meant to let me invite my friends to my world or join my friends' worlds.

**Screenshots**
![Screen Shot 2023-02-22 at 3 26 20 PM](https://user-images.githubusercontent.com/101063628/220786485-3ea0f438-a794-4e94-ab7c-a0cffacfa181.png)

**Desktop:**
 - OS: [macOS]
 - Version [v0.8.1-macOS-x86_64-0.2.4]
 - Installation Type [dmg

**Additional context**
Affected versions: 1.19.40.00 and higher (?)

**Comment by AlexLexusYTXD** [comment]
P.S: I can still join servers, and I tried logging in or logging out multiple times, and still it wasn't fixed.

**Comment by AlexLexusYTXD** [comment]
@ChristopherHX

**Comment by ghost** [comment]
oh as far as i played its just a message, that.. exists, nothing past that as far as i know its not harming
as you are actually logged in

**Comment by eithe** [comment]
Also seeing the same. I tried with two different xbox accounts + created new worlds, signed in and out many times. Also tried on new install (this time with flatpak just so I could run a seperate instance).

**Comment by mr-sihc** [comment]
hellooo, this message is useless i told you all, you can still join lan + online servers
and access marketplace and etc. this isnt problematic in the slightest, you can even still invite guests, so dont try doing all reinstall and relogins and stupid
