### ISSUE TITLE
Skin is never loaded and can't download DLC from marketplace

### ISSUE THREAD

**Issue by Evaghetti** [minecraft-linux/mcpelauncher-manifest#801]
**Describe the bug**
The game runs fine, but if i log in to my microsoft account, it never loads my skin. Also if i go into the marketplace to download DLC that i bought in another device, it only shows the checking download message

**To Reproduce**
Steps to reproduce the behavior for skins:
1. When the game is opened, log into your microsoft account
2. Once it is logged in, and the marketplace option is able to be interacted with, wait a bit
3. Username shows up, but the skin doesn't, after a while you will receive a message saying it wasn't possible to load character 3

Steps to reproduce the behavior for DLC:
1. Repeat steps one and two from the other bug
2. Open the marketplace and got to "My Content"
3. Choose whatever DLC you have and try to download it 

**Expected behavior**
Download both the skin and the DLC

**Screenshots**
Skin problem:
![Captura de tela de 2023-02-26 16-02-12](https://user-images.githubusercontent.com/20467759/221431702-878bb737-b373-4bf9-b73a-e6920540bde5.png)
![Captura de tela de 2023-02-26 16-11-17](https://user-images.githubusercontent.com/20467759/221431712-065226e7-dca1-4744-8658-c1fa8358cf1c.png)

DLC problem:
![Captura de tela de 2023-02-26 16-05-10](https://user-images.githubusercontent.com/20467759/221431725-867731de-6652-4987-a2a6-a9ef86f58b5d.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22,04.1
 - Version x86_64-v0.8.1.701.AppImage
 - Installation Type AppImage

**Additional context**

**Comment by ChristopherHX** [comment]
Fixed version 0.8.5
