### ISSUE TITLE
Latest Version 1.19.70.02

### ISSUE THREAD

**Issue by fl00dg4t35** [minecraft-linux/mcpelauncher-manifest#804]
Super cool and useful project y'all :)

Got locked out of my buddies realm because I can't update. 
I'm sure you're already on it, but figured I'd put in a request anyway :) Keep up the great work :)

**Comment by alyssamyers4902** [comment]
I am having the same issue!

**Comment by crystalcommunication** [comment]
It works fine if you enable the Dev options and enable "Show unverified versions"

**Comment by alyssamyers4902** [comment]
> It works fine if you enable the Dev options and enable "Show unverified versions"

Hi! Where is this option located? I would love to play again! Thanks!

**Comment by crystalcommunication** [comment]
The instructions are in #797. For what it's worth, I only tested it on Linux.

**Comment by alyssamyers4902** [comment]
> The instructions are in #797. For what it's worth, I only tested it on Linux.

I'm able to play this way! Thanks for the suggestion :)

**Comment by ChristopherHX** [comment]
Done
