### ISSUE TITLE
Will not connect to friend game on Switch

### ISSUE THREAD

**Issue by kreptafire** [minecraft-linux/mcpelauncher-manifest#811]
Apologies if this has already been answered. I ran into an interesting bug where I can see the cross-platform game being played by a friend on the switch, but when I try to connect to it, the connection times out and is unable to connect. Interestingly, I tried connecting to the exact same game from my windows PC and had zero issues. 

I also couldn't add the friend on the mcpelauncher version on my steam deck but I was able to on the windows version. Not sure if this is a related bug and has to do with how friends are handled.

**Comment by sketch54** [comment]
I'm having the same problem, are you using the Flatpak version or .AppImage? I'm using the .AppImage and I'm wondering if that's the common problem here.

**Comment by kreptafire** [comment]
I installed it through the discover app store on my steam deck, so I think it's the flatpak version?

**Comment by sketch54** [comment]
I also installed the Flatpak version to test it and despite being a higher version than the .AppImage, the issue still persists. I looked through some of the other issues posted on the repo and saw that there were problems like ours marked as resolved. It seems that someone made a [pull request](https://github.com/minecraft-linux/mcpelauncher-client/pull/51) which fixed it and it got merged, but you'd have to compile it from source at this point as no official release has been made yet with the fix.

**Comment by kreptafire** [comment]
How does one go about getting a new release pushed with the changes?

**Comment by sketch54** [comment]
For us we'll likely have to wait for an update on Flathub if we don't want to [compile it from source](https://mcpelauncher.readthedocs.io/en/latest/source_build/index.html#source-build). As I said before, another option is using the .AppImage but I think it's further behind than the Flathub release. I would hope that we get an update soon because this seems to be a widespread issue and a pretty big one at that.

**Comment by ChristopherHX** [comment]
This launcher has ci builds built by GitHub Actions, so snapshots have binaries. You just need to find them, there are not harder to find than the PR.

I created a new release with friend joining support of 1.19.73, but the next update will take longer.
