### ISSUE TITLE
Latest mcpe does not launch

### ISSUE THREAD

**Issue by pcs3rd** [minecraft-linux/mcpelauncher-manifest#82]
> 20:17:18 Info  [Launcher] Version: client b63fb08 / manifest fc11ccf
20:17:18 Info  [Launcher] CPU: GenuineIntel       Intel(R) Celeron(R) CPU  N3060  @ 1.60GHz
20:17:18 Info  [Launcher] CPU supports SSSE3: YES
20:17:18 Trace [Launcher] Loading hybris libraries
20:17:18 Trace [HybrisUtils] Loaded OS library /usr/share/mcpelauncher/libs/native/libfmod.so.9.16
20:17:18 Trace [HybrisUtils] Loaded OS library libm.so.6
20:17:18 Trace [Launcher] Loading Minecraft library
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to load Minecraft: Cannot load library: load_library[1115]: Library '/home/raymond/.local/share/mcpelauncher/versions/1.11.1.2/libs/libminecraftpe.so' not found
Signal 6 received
Backtrace elements: 13
#0 /usr/bin/mcpelauncher-client(_ZN12CrashHandler12handleSignalEiPv+0xc5) [0x58347f83]
#1 linux-gate.so.1(__kernel_sigreturn+0) [0xe7b41a10]
#2 linux-gate.so.1(__kernel_vsyscall+0x10) [0xe7b41a40]
#3 /lib/i386-linux-gnu/libc.so.6(gsignal+0xc2) [0xe741c832]
#4 /lib/i386-linux-gnu/libc.so.6(abort+0x121) [0xe741dcc1]
#5 /usr/lib/i386-linux-gnu/libstdc++.so.6(+0x6e91d) [0xe777a91d]
#6 /usr/lib/i386-linux-gnu/libstdc++.so.6(+0x760d4) [0xe77820d4]
#7 /usr/lib/i386-linux-gnu/libstdc++.so.6(+0x7613d) [0xe778213d]
#8 /usr/lib/i386-linux-gnu/libstdc++.so.6(+0x7643c) [0xe778243c]
#9 /usr/bin/mcpelauncher-client(_ZN14MinecraftUtils16loadMinecraftLibERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x10e) [0x58349332]
#10 /usr/bin/mcpelauncher-client(main+0xfcb) [0x582fc087]
#11 /lib/i386-linux-gnu/libc.so.6(__libc_start_main+0xf1) [0xe7407e81]
#12 /usr/bin/mcpelauncher-client(+0x1b0ad1) [0x582faad1]
Dumping stack...
Process exited with unexpected exit code: 6

**Comment by Mhowser** [comment]
What is your environment?

**Comment by MCMrARM** [comment]
How are you launching the launcher?

**Comment by pcs3rd** [comment]
I'm sorry, Github is not sending emails to me or showing I have any alerts. 
@Mhowser, my enviroment is ubuntu bionic beaver (on a crouton chroot). [(dnschneid/crouton)](https://github.com/dnschneid/crouton)
@MCMrARM, What exactly do you mean? I launch the launcher from mainly LXDE desktop, but sometimes I launch from command line.

**Comment by MCMrARM** [comment]
This has nothing to do with the MCPE versions, the game is improperly extracted, hence my question. If you are using the Qt launcher please redownload the version (delete it from top right settings -> versions first; then press Download and Play).

**Comment by pcs3rd** [comment]
Ok.
