### ISSUE TITLE
"Unable to Connect" error when trying to connect to friend's game

### ISSUE THREAD

**Issue by sudoharun** [minecraft-linux/mcpelauncher-manifest#820]
**Describe the bug**
"Unable to Connect" error when trying to connect to friend's game

**To Reproduce**
1. Go to Friends tab
2. A friend is on their world and their game pops up
3. Click on Friends' game

**Expected behavior**
You should be on their world now

**Screenshots**
![mcpe1](https://user-images.githubusercontent.com/123123333/232319780-451a63d7-211f-4bfa-b51a-42f5673324b5.png)
![mcpe2](https://user-images.githubusercontent.com/123123333/232319786-1a1ebd23-cd0c-48f7-b1ac-6fb777f5d791.png)
![mcpe3](https://user-images.githubusercontent.com/123123333/232319791-16fa522f-505e-4209-8240-d3a2e70a6a32.png)

**Desktop:**
 - OS: EndeavourOS Linux
 - Version: 0.9.0-713
 - Installation Type: AUR (mcbelauncher-bin 0.9.0-713)

**Comment by GameParrot** [comment]
https://bugs.mojang.com/browse/MCPE-36190

**Comment by GameParrot** [comment]
Works sometimes for me

**Comment by sudoharun** [comment]
I'm trying to do this on 2 Linux systems with each other, and both using the same version and everything is the same even down to the distro (not hardware though).

**Comment by GameParrot** [comment]
Are they on the same network? It has almost never worked for me with 2 devices on the same network, but it has worked over the internet.

**Comment by sudoharun** [comment]
Yes, they are on the same network. Would I have to create a virtual hotspot (for 1 device) then in order for it to work perhaps?

**Comment by GameParrot** [comment]
Maybe try putting them on separate networks. You should also be able to use LAN multiplayer if you sign out or unfriend them.

**Comment by ChristopherHX** [comment]
I remember it worked two weeks ago on my side, but now it's broken for me if this launcher hosts the game (same network). Hosted by my android phone, can be connected from this Launcher.

_However I don't really care about this feature of xbox live_

**Comment by sudo-harun** [comment]
> Maybe try putting them on separate networks. You should also be able to use LAN multiplayer if you sign out or unfriend them.

I'll try this and get back to you.

**Comment by sudo-harun** [comment]
Unfortunately I can't connect to any other networks, and also the reason why I brought this issue up is because of **achievements**. Me and the family member I wanna play with wanna get achievements together, otherwise we would just continue playing on our free server instead of logging out and playing a LAN game. If this issue isn't resolved, then we just gotta work with what we got and forget about achievements until there is a fix.

**Comment by sudoharun** [comment]
Unfortunately I can't connect to any other networks

They also don't pop up as a LAN game either even after unfriending them.

Also the reason why I brought this issue up is because of achievements. Me and the family member I wanna play with wanna get achievements together, otherwise we would just continue playing on our free server instead of logging out and playing a LAN game. If this issue isn't resolved, then we just gotta work with what we got and forget about achievements until there is a fix I guess.

**Comment by ChristopherHX** [comment]
Just copy your world to https://www.minecraft.net/en-us/download/server/bedrock and connect to the local server.

If you don't see the official bds server just add it per ip in external server.

Or is it impossible to earn achievements in bds without cheats enabled?

**Comment by sudoharun** [comment]
I see the bds on the machine hosting the server but only on that one.

Also you can't earn achievements on external servers as far as I know.

Maybe it's because one of the machines only supports 2.4GHz WiFi and the other supports both 2.4GHz and 5GHz?

**Comment by ChristopherHX** [comment]
> I see the bds on the machine hosting the server but only on that one.

bds allow connection by ip, that's no problem if you are signed in to your ms account.

> Also you can't earn achievements on external servers as far as I know.

That's wrong, I just unlocked an achivement via bds connected by ip. This is my config file:
```
server-name=Dedicated Server
# Used as the server name
# Allowed values: Any string without semicolon symbol.

gamemode=survival
# Sets the game mode for new players.
# Allowed values: "survival", "creative", or "adventure"

force-gamemode=true
# force-gamemode=false (or force-gamemode  is not defined in the server.properties)
# prevents the server from sending to the client gamemode values other
# than the gamemode value saved by the server during world creation
# even if those values are set in server.properties after world creation.
# 
# force-gamemode=true forces the server to send to the client gamemode values
# other than the gamemode value saved by the server during world creation
# if those values are set in server.properties after world creation.

difficulty=normal
# Sets the difficulty of the world.
# Allowed values: "peaceful", "easy", "normal", or "hard"

allow-cheats=false
# If true then cheats like commands can be used.
# Allowed values: "true" or "false"

max-players=10
# The maximum number of players that can play on the server.
# Allowed values: Any positive integer

online-mode=true
# If true then all connected players must be authenticated to Xbox Live.
# Clients connecting to remote (non-LAN) servers will always require Xbox Live authentication regardless of this setting.
# If the server accepts connections from the Internet, then it's highly recommended to enable online-mode.
# Allowed values: "true" or "false"

allow-list=false
# If true then all connected players must be listed in the separate allowlist.json file.
# Allowed values: "true" or "false"

server-port=65001
# Which IPv4 port the server should listen to.
# Allowed values: Integers in the range [1, 65535]

server-portv6=65002
# Which IPv6 port the server should listen to.
# Allowed values: Integers in the range [1, 65535]

enable-lan-visibility=false
# Listen and respond to clients that are looking for servers on the LAN. This will cause the server
# to bind to the default ports (19132, 19133) even when `server-port` and `server-portv6`
# have non-default values. Consider turning this off if LAN discovery is not desirable, or when
# running multiple servers on the same host may lead to port conflicts.
# Allowed values: "true" or "false"

view-distance=32
# The maximum allowed view distance in number of chunks.
# Allowed values: Positive integer equal to 5 or greater.

tick-distance=4
# The world will be ticked this many chunks away from any player.
# Allowed values: Integers in the range [4, 12]

player-idle-timeout=30
# After a player has idled for this many minutes they will be kicked. If set to 0 then players can idle indefinitely.
# Allowed values: Any non-negative integer.

max-threads=8
# Maximum number of threads the server will try to use. If set to 0 or removed then it will use as many as possible.
# Allowed values: Any positive integer.

level-name=My bds
# Allowed values: Any string without semicolon symbol or symbols illegal for file name: /\n\r\t\f`?*\\<>|\":

level-seed=
# Use to randomize the world
# Allowed values: Any string

default-player-permission-level=member
# Permission level for new players joining for the first time.
# Allowed values: "visitor", "member", "operator"

texturepack-required=false
# Force clients to use texture packs in the current world
# Allowed values: "true" or "false"

content-log-file-enabled=true
# Enables logging content errors to a file
# Allowed values: "true" or "false"

compression-threshold=1
# Determines the smallest size of raw network payload to compress
# Allowed values: 0-65535

compression-algorithm=zlib
# Determines the compression algorithm to use for networking
# Allowed values: "zlib", "snappy"

server-authoritative-movement=server-auth
# Allowed values: "client-auth", "server-auth", "server-auth-with-rewind"
# Enables server authoritative movement. If "server-auth", the server will replay local user input on
# the server and send down corrections when the client's position doesn't match the server's.
# If "server-auth-with-rewind" is enabled and the server sends a correction, the clients will be instructed
# to rewind time back to the correction time, apply the correction, then replay all the player's inputs since then. This results in smoother and more frequent corrections.
# Corrections will only happen if correct-player-movement is set to true.

player-movement-score-threshold=20
# The number of incongruent time intervals needed before abnormal behavior is reported.
# Disabled by server-authoritative-movement.

player-movement-action-direction-threshold=0.85
# The amount that the player's attack direction and look direction can differ.
# Allowed values: Any value in the range of [0, 1] where 1 means that the
# direction of the players view and the direction the player is attacking
# must match exactly and a value of 0 means that the two directions can
# differ by up to and including 90 degrees.

player-movement-distance-threshold=0.3
# The difference between server and client positions that needs to be exceeded before abnormal behavior is detected.
# Disabled by server-authoritative-movement.

player-movement-duration-threshold-in-ms=500
# The duration of time the server and client positions can be out of sync (as defined by player-movement-distance-threshold)
# before the abnormal movement score is incremented. This value is defined in milliseconds.
# Disabled by server-authoritative-movement.

correct-player-movement=false
# If true, the client position will get corrected to the server position if the movement score exceeds the threshold.


server-authoritative-block-breaking=trur
# If true, the server will compute block mining operations in sync with the client so it can verify that the client should be able to break blocks when it thinks it can.

chat-restriction=None
# Allowed values: "None", "Dropped", "Disabled"
# This represents the level of restriction applied to the chat for each player that joins the server.
# "None" is the default and represents regular free chat.
# "Dropped" means the chat messages are dropped and never sent to any client. Players receive a message to let them know the feature is disabled.
# "Disabled" means that unless the player is an operator, the chat UI does not even appear. No information is displayed to the player.

disable-player-interaction=false
# If true, the server will inform clients that they should ignore other players when interacting with the world. This is not server authoritative.

client-side-chunk-generation-enabled=true
# If true, the server will inform clients that they have the ability to generate visual level chunks outside of player interaction distances.

disable-persona=false
disable-custom-skins=false
# Client avatar personalization options
```

_This launcher is buggy, especially on macOS and flatpak lan discovery is not always working._

**Comment by sudoharun** [comment]
Ah I see. I thought you couldn't earn achievements on external servers because I already had a server I made through [aternos.org](aternos.org) and we couldn't unlock any achievements.

Also I am unable to connect via IP for some reason. On the host machine I am able to connect, even via external server, but on the other machine it just says "Unable to Connect". I put in the host machines IPV4 address though on both and same port too. I even tried it with your config but still nothing.

**Comment by ChristopherHX** [comment]
> Also I am unable to connect via IP for some reason

No idea what's wrong with your local network.
- disabling ipv6 in the home network / linux device is always a bad idea and make the game unhappy (even if you still have ipv4 internet)
- I get "Unable to Connect" on win11 edition (same host both bds and game), due to the firewall of windows apps and the suggestion of the bds readme to add an except to the rule just says invalid parameter
- Check your firewall if you have any
- Use the native unsandboxed AppImage instead of a vm / flatpak / etc.
- Don't try to connect via ipv6 address, I couldn't get this working in bedrock via entering the full ipv6 manually in win10, android or this launcher

If cannot even connect by ip, both devices can never play together with the server in the same network.

> we couldn't unlock any achievements.

If you world has ever enabled cheats or other gamemodes than survival achivements are blocked.

E.g. `/tp` is unavailable on the achivements enabled server

**Comment by sudoharun** [comment]
Ok, I'll see if I am able to unlock an achievement on an aternos server without cheats activated and get back to you.

**Comment by sudoharun** [comment]
Closing as this is fixed in the recent update.

**Comment by Magicrafter13** [comment]
I'm having this same issue on the same OS (Endeavor), and I discovered that by turning off the firewall (firewalld, included in the installation by default), it works. So it seems to be a firewall issue for me at least, but I'm not sure what to do to allow this particular traffic. I'm on a network labeled as part of the "home" zone too, which I would expect to be more lenient...

Edit: setting it to the trusted zone allows the game to work, so I guess I can start by looking through the differences between the two zones, but if anyone has any insight it would be much appreciated.
