### ISSUE TITLE
Minecraft apk fails to download

### ISSUE THREAD

**Issue by kreptafire** [minecraft-linux/mcpelauncher-manifest#827]
Minecraft launcher loads but every time I try to download minecraft it simply hangs at 99% and fails to complete. Yes I am signed into Google and have agreed to the tos.

This worked fine before I uninstalled and reinstalled the launcher.

**Comment by kreptafire** [comment]
The only way I was able to get around this issue was downloading everything on a different Linux install and manually copying the installation folders over...

**Comment by Mhowser** [comment]
You probably didn't need to do it that way, just delete the installation folder and reinstall the launcher.
