### ISSUE TITLE
Minecraft has exited with a non-zero error code

### ISSUE THREAD

**Issue by PlumpCashews** [minecraft-linux/mcpelauncher-manifest#83]
/usr/bin/mcpelauncher-client: error while loading shared libraries: libEGL.so.1: cannot open shared object file: No such file or directory
Process exited with unexpected exit code: 127

**Comment by Mhowser** [comment]
Did you get the 32bit graphics drivers?

Sudo apt install libegl1-mesa:i386 libegl1-mesa-drivers:i386
libegl-mesa0:i386

**Comment by PlumpCashews** [comment]
sudo apt install libegl1-mesa:i386 worked, thank you!
