### ISSUE TITLE
Launcher crashes with Signal number 11 in SoundSystemFMOD::load() (libfmod)

### ISSUE THREAD

**Issue by rcbjBlueMars** [minecraft-linux/mcpelauncher-manifest#833]
**Describe the bug**

Shortly after joining a realm, the launcher crashes with the following error:

Signal 11 received
Backtrace elements: 16
#0 /app/bin/mcpelauncher-client(_ZN12CrashHandler12handleSignalEiPv+0x12c) [0x557827f25d6c]
#1 /usr/lib/x86_64-linux-gnu/libpthread.so.0(+0x12e60) [0x7fa9c02fae60]
#2 /app/share/mcpelauncher/lib/native/x86_64/libfmod.so.12.0(+0x128e69) [0x7fa9bef28e69]
#3 /app/share/mcpelauncher/lib/native/x86_64/libfmod.so.12.0(+0x122a0e) [0x7fa9bef22a0e]
#4 /app/share/mcpelauncher/lib/native/x86_64/libfmod.so.12.0(+0x3f98a) [0x7fa9bee3f98a]
#5 /app/share/mcpelauncher/lib/native/x86_64/libfmod.so.12.0(+0x3fa8c) [0x7fa9bee3fa8c]
#6 /app/share/mcpelauncher/lib/native/x86_64/libfmod.so.12.0(+0x3af10) [0x7fa9bee3af10]
#7 /app/share/mcpelauncher/lib/native/x86_64/libfmod.so.12.0(+0x3af10) [0x7fa9bee3af10]
#8 /app/share/mcpelauncher/lib/native/x86_64/libfmod.so.12.0(+0xebd6c) [0x7fa9beeebd6c]
#9 /app/share/mcpelauncher/lib/native/x86_64/libfmod.so.12.0(+0xec4e8) [0x7fa9beeec4e8]
#10 /app/share/mcpelauncher/lib/native/x86_64/libfmod.so.12.0(+0xee361) [0x7fa9beeee361]
#11 /app/share/mcpelauncher/lib/native/x86_64/libfmod.so.12.0(+0xee56c) [0x7fa9beeee56c]
#12 /app/share/mcpelauncher/lib/native/x86_64/libfmod.so.12.0(+0x10178f) [0x7fa9bef0178f]
#13 /app/share/mcpelauncher/lib/native/x86_64/libfmod.so.12.0(+0xf9c30) [0x7fa9beef9c30]
#14 /app/share/mcpelauncher/lib/native/x86_64/libfmod.so.12.0(_ZN4FMOD6System12createStreamEPKcjP22FMOD_CREATESOUNDEXINFOPPNS_5SoundE+0x16e) [0x7fa9beef2d1e]
#15 LINKER SoundSystemFMOD::load(Core::Path const&, bool)+0x700 in /home/user1/.var/app/io.mrarm.mcpelauncher/data/mcpelauncher/versions/1.19.83.01/lib/x86_64/libminecraftpe.so+0x0xd033990 [0x0x7fa972df3990]
Dumping stack...
#16 LINKER SoundSystemFMOD::load(Core::Path const&, bool)+0x700 in /home/user1/.var/app/io.mrarm.mcpelauncher/data/mcpelauncher/versions/1.19.83.01/lib/x86_64/libminecraftpe.so+0xd033990 [0x7fa972df3990]
program failed with unix signal number: 11

Process exited with unexpected exit code: 11

**To Reproduce**

1. Launch minecraft bedrock edition launcher.
2. Click green play Minecraft 1.19.83.01 button.
3. Minecraft loads.
4. Click Play button on home screen.
5. Join a World.
6. World loads
7. Play the game (just start moving around) for a few seconds. It's been as fast as three seconds as long as 20 seconds.
8. Game crashes with error above.

**Expected behavior**

Game play continues without crashing.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Pop!_OS 22.04 LTS 64-bit, Gnome Version 42.5, X11
 - Version 0.9.0 Build 63
 - Installation Type: Flatpak (Pop!_OS pop! shop package manager)

**Additional context**
16GB memory
12th Gen Intel core i5-124P X16
Mesa Intel Graphics ADL GT2

Full log:

3:19:06 Info  [Launcher] Version: client 4b4d8b0 / manifest e7556b0
13:19:06 Info  [Launcher] CPU: GenuineIntel 12th Gen Intel(R) Core(TM) i5-1240P
13:19:06 Info  [Launcher] CPU supports SSSE3: YES
13:19:06 Trace [Launcher] Loading hybris libraries
13:19:06 Trace [REDIRECT] /data/data/com.mojang.minecraftpe to /home/user1/.var/app/io.mrarm.mcpelauncher/data/mcpelauncher/
13:19:06 Trace [REDIRECT] /data/data/app/proc/41/cmdline to /home/user1/.var/app/io.mrarm.mcpelauncher/data/mcpelauncher/
13:19:06 Trace [REDIRECT] /data/data/app/bin/mcpelauncher-client to /home/user1/.var/app/io.mrarm.mcpelauncher/data/mcpelauncher/
13:19:06 Trace [REDIRECT] /data/data to /home/user1/.var/app/io.mrarm.mcpelauncher/data/mcpelauncher/
13:19:06 Trace [REDIRECT] . to /home/user1/.var/app/io.mrarm.mcpelauncher/data/mcpelauncher/versions/1.19.83.01/assets/
13:19:06 Trace [LinkerUtils] Loaded OS library libm.so.6
13:19:06 Trace [LinkerUtils] Loaded OS library libz.so.1
13:19:06 Trace [LinkerUtils] Loaded OS library /app/share/mcpelauncher/lib/native/x86_64/libfmod.so.12.0
13:19:06 Info  [Launcher] Loading gamepad mappings
13:19:06 Trace [Launcher] Loading gamepad mappings: /app/share/mcpelauncher/gamecontrollerdb.txt
13:19:06 Trace [Launcher] Loading gamepad mappings: /app/share/mcpelauncher/gamecontrollerdb.txt
13:19:06 Info  [Launcher] Creating window
13:19:06 Trace [Launcher] Loading Minecraft library
Found hook: _ZN11AppPlatform16showMousePointerEv @ 0x557827f125a0
Found hook: _ZN11AppPlatform16hideMousePointerEv @ 0x557827f12580
13:19:06 Info  [Launcher] Loaded Minecraft library
13:19:06 Debug [Launcher] Minecraft is at offset 0x7FA965DC0000
13:19:06 Info  [Launcher] Game version: 0.0.0.0
13:19:06 Info  [Launcher] Applying patches
13:19:06 Debug [CorePatches] Failed to patch, vtable _ZTV21AppPlatform_android23 not found
13:19:06 Info  [Launcher] Initializing JNI
13:19:06 Error [JniSupport] Missing native symbol: Java_com_mojang_minecraftpe_MainActivity_nativeRegisterThis
13:19:06 Error [JniSupport] Missing native symbol: Java_com_mojang_minecraftpe_MainActivity_nativeInitializeWithApplicationContext
13:19:06 Error [JniSupport] Missing native symbol: Java_com_mojang_minecraftpe_MainActivity_nativeUnregisterThis
13:19:06 Error [JniSupport] Missing native symbol: Java_com_mojang_minecraftpe_MainActivity_nativeinitializeLibHttpClient
13:19:06 Error [JniSupport] Missing native symbol: Java_com_microsoft_xal_browser_WebView_urlOperationSucceeded
13:19:06 Error [JniSupport] Missing native symbol: Java_com_mojang_minecraftpe_PlayIntegrity_nativePlayIntegrityComplete
13:19:06 Info  [Launcher] Executing main thread
13:19:06 Trace [Minecraft] Entering JNI_OnLoad 0x7fa9ad47f640
13:19:06 Trace [Minecraft] JNI_OnLoad completed
13:19:06 Trace [JniSupport] Invoking nativeRegisterThis
13:19:06 Trace [JniSupport] Invoking ANativeActivity_onCreate
13:19:06 Warn  [Main] Android stub called
13:19:06 Warn  [Main] Android stub called
13:19:06 Warn  [Main] Android stub called
13:19:06 Warn  [Main] Android stub called
13:19:06 Info  [Minecraft] android_main starting. internalDataPath is '/internal', externalDataPath is '/external'
13:19:06 Trace [JniSupport] Invoking start activity callbacks
13:19:06 Error [MCPE] *** setCachedDeviceId(86cfce0c-59da-4c3b-8c32-11bf575fa750)
13:19:06 Info  [Bedrock] configureBreakpad with directory: /crash, sessionid is: 30322628-58e7-40a4-82b0-1096123dd47f
13:19:06 Info  [Bedrock] configureBreakpad called, directory is: /crash, sessionid is: 30322628-58e7-40a4-82b0-1096123dd47f
13:19:06 Info  [Minecraft] NO LOG FILE! - AppPlatform_android::setStorageDirectory - using External dir (NEW) - CurrentFileStoragePath is now '/home/user1/.var/app/io.mrarm.mcpelauncher/data/mcpelauncher/'
13:19:06 Warn  [Minecraft] NO LOG FILE! - [Graphics] The graphics context was gained
13:19:06 Warn  [Minecraft] NO LOG FILE! - [Graphics] The graphics context was gained
13:19:06 Warn  [Minecraft] MinecraftGame::init && MinecraftGame::setSize!
13:19:06 Warn  [FakeEGL] eglQueryString 308d
13:19:06 Warn  [Main] Android stub called
13:19:06 Warn  [Main] Android stub called
13:19:06 Warn  [Main] Android stub called
13:19:06 Debug [HttpCallStaticGlue] Successfully registerered HttpCall methods
13:19:06 Debug [XboxLiveAppConfig] Successfully registerered XboxLiveAppConfig methods
13:19:06 Debug [XSAPI.Android] Successfully registerered HttpCall tcuiMethods
13:19:08 Info  [Minecraft] NO LOG FILE! - Time played notifier not required for 'en'
13:19:10 Warn  [Main] Android stub called
13:19:16 Info  [Minecraft] NO LOG FILE! - opening /home/user1/.var/app/io.mrarm.mcpelauncher/data/mcpelauncher/minecraftpe/blob_cache
13:22:11 Info  [Minecraft] NO LOG FILE! - opening /home/user1/.var/app/io.mrarm.mcpelauncher/data/mcpelauncher/games/com.mojang/minecraftWorlds/u7BzZN5XLQA=/db
13:22:12 Info  [Minecraft] NO LOG FILE! - Player connected: bugieboo001, xuid: 
13:22:13 Trace [Minecraft] NO LOG FILE! - DBStorage - Compaction Starting...
13:22:13 Trace [Minecraft] NO LOG FILE! - DBStorage - Compaction Complete.
13:22:13 Trace [Minecraft] NO LOG FILE! - Scheduling AutoCompaction...
13:22:13 Trace [Minecraft] NO LOG FILE! - DBStorage - Compaction Starting...
13:22:17 Info  [Minecraft] NO LOG FILE! - Player Spawned: bugieboo001 xuid: 
13:22:21 Trace [Minecraft] NO LOG FILE! - DBStorage - Compaction Complete.
13:22:21 Trace [Minecraft] NO LOG FILE! - Scheduling AutoCompaction...
Signal 11 received
Backtrace elements: 16
#0 /app/bin/mcpelauncher-client(_ZN12CrashHandler12handleSignalEiPv+0x12c) [0x557827f25d6c]
#1 /usr/lib/x86_64-linux-gnu/libpthread.so.0(+0x12e60) [0x7fa9c02fae60]
#2 /app/share/mcpelauncher/lib/native/x86_64/libfmod.so.12.0(+0x128e69) [0x7fa9bef28e69]
#3 /app/share/mcpelauncher/lib/native/x86_64/libfmod.so.12.0(+0x122a0e) [0x7fa9bef22a0e]
#4 /app/share/mcpelauncher/lib/native/x86_64/libfmod.so.12.0(+0x3f98a) [0x7fa9bee3f98a]
#5 /app/share/mcpelauncher/lib/native/x86_64/libfmod.so.12.0(+0x3fa8c) [0x7fa9bee3fa8c]
#6 /app/share/mcpelauncher/lib/native/x86_64/libfmod.so.12.0(+0x3af10) [0x7fa9bee3af10]
#7 /app/share/mcpelauncher/lib/native/x86_64/libfmod.so.12.0(+0x3af10) [0x7fa9bee3af10]
#8 /app/share/mcpelauncher/lib/native/x86_64/libfmod.so.12.0(+0xebd6c) [0x7fa9beeebd6c]
#9 /app/share/mcpelauncher/lib/native/x86_64/libfmod.so.12.0(+0xec4e8) [0x7fa9beeec4e8]
#10 /app/share/mcpelauncher/lib/native/x86_64/libfmod.so.12.0(+0xee361) [0x7fa9beeee361]
#11 /app/share/mcpelauncher/lib/native/x86_64/libfmod.so.12.0(+0xee56c) [0x7fa9beeee56c]
#12 /app/share/mcpelauncher/lib/native/x86_64/libfmod.so.12.0(+0x10178f) [0x7fa9bef0178f]
#13 /app/share/mcpelauncher/lib/native/x86_64/libfmod.so.12.0(+0xf9c30) [0x7fa9beef9c30]
#14 /app/share/mcpelauncher/lib/native/x86_64/libfmod.so.12.0(_ZN4FMOD6System12createStreamEPKcjP22FMOD_CREATESOUNDEXINFOPPNS_5SoundE+0x16e) [0x7fa9beef2d1e]
#15 LINKER SoundSystemFMOD::load(Core::Path const&, bool)+0x700 in /home/user1/.var/app/io.mrarm.mcpelauncher/data/mcpelauncher/versions/1.19.83.01/lib/x86_64/libminecraftpe.so+0x0xd033990 [0x0x7fa972df3990]
Dumping stack...
#16 LINKER SoundSystemFMOD::load(Core::Path const&, bool)+0x700 in /home/user1/.var/app/io.mrarm.mcpelauncher/data/mcpelauncher/versions/1.19.83.01/lib/x86_64/libminecraftpe.so+0xd033990 [0x7fa972df3990]
program failed with unix signal number: 11

Process exited with unexpected exit code: 11

**Comment by Rania-Mounhime** [comment]
I am experiencing the exact same error. Is there a solution for this yet?

**Comment by rcbjBlueMars** [comment]
I haven't made any progress with finding a solution. My kid started having problems on Sunday morning with the game crashing. As of last night, the behavior was still the same.

**Comment by Rania-Mounhime** [comment]
Same states here, singleplayer does work for me now but as soon as a friend joins it crashes.

**Comment by rcbjBlueMars** [comment]
This issue was resolved when minecraft was automatically upgraded to v1.20.
