### ISSUE TITLE
Minecraft crashes when starting with Wayland

### ISSUE THREAD

**Issue by argonptg** [minecraft-linux/mcpelauncher-manifest#835]
**Describe the bug**
When you launch minecraft using Wayland (not Xwayland), it crashes and returns with this gamelog:
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  glfwInit error

Process exited with unexpected exit code: 6
```

**To Reproduce**
1. Enable wayland on the flatpak
2. Try to launch Minecraft

**Expected behavior**
I expected for Minecraft to launch

**Screenshots**
![image](https://github.com/minecraft-linux/mcpelauncher-manifest/assets/94653435/2c467bfb-8909-47be-b7ed-89f2219f9df4)
![image](https://github.com/minecraft-linux/mcpelauncher-manifest/assets/94653435/23d564e5-8fb1-499c-b3fe-bef211e981a6)

**Desktop (please complete the following information):**
 - OS: Pop!_OS 22.04
 - Version: Most recent Flatpak version (06/01/23)
 - Installation Type: Flatpak

**Comment by ChristopherHX** [comment]
Not a bug, glfw wayland support was too experimental in fall 2022 and broke gamepad input. In 2020 resizing the window was unreliable and it had freezing issues.

There is no release of glfw yet with both wayland and x11 support, everything is only on the master branch.

**Comment by rakshit087** [comment]
How can I run this application on XOrg?

**Comment by Hellscaped** [comment]
> How can I run this application on XOrg?

switch your windowing system to xorg via your login manager, and run the program.

**Comment by argonptg** [comment]
> Not a bug, glfw wayland support was too experimental in fall 2022 and broke gamepad input. In 2020 resizing the window was unreliable and it had freezing issues.
> 
> There is no release of glfw yet with both wayland and x11 support, everything is only on the master branch.

I will close this issue as this isn't a bug
