### ISSUE TITLE
Black screen after Mesa upgrade from 23.0.3 to 23.1.1

### ISSUE THREAD

**Issue by brauliobo** [minecraft-linux/mcpelauncher-manifest#836]
After upgrading Mesa in Archlinux from version 23.0.3 to 23.1.0 or 23.1.1 the client loads the game but with a black screen. Game sound is working.

Just downgrading back to Mesa to 23.0.3 using Archlinux archive makes it work again

**Comment by brauliobo** [comment]
Works now with 23.1.3

**Comment by ChristopherHX** [comment]
> Works now with 23.1.3

With launcher release 0.9.0? If it works with launcher release 0.10.0 then the mesa issue is resolved by disabling the new feature of mesa 23.1.
