### ISSUE TITLE
Game crashes when function keys are pressed

### ISSUE THREAD

**Issue by dysphie** [minecraft-linux/mcpelauncher-manifest#84]
The game is crashing for me whenever function keys are pressed.
I'm running the AppImage on Debian 9.9 (Stretch)

Repro steps:
- Launch game
- Hit any function key from F1-F12

Crash log: https://pastebin.com/raw/TwAT4EcN

**Comment by MCMrARM** [comment]
Will investigate

**Comment by Ladizii** [comment]
```
Dumping stack...
#29 HYBRIS (null)+-251029648 in libminecraftpe.so+0x2618770 [0xf1099770]
#30 HYBRIS (null)+-251029712 in libminecraftpe.so+0x2618730 [0xf1099730]
#87 HYBRIS Keyboard::_states+0 in libminecraftpe.so+0x6c57838 [0xf56d8838]
#118 HYBRIS (null)+-179637076 in libminecraftpe.so+0x6a2e4ac [0xf54af4ac]
#120 HYBRIS ScreenRenderBatch::_populateRenderControlsCollection(UIControl&, BatchClippingState const&, BatchClippingState const&, BatchVisualState const&, ClippedControlMetadata&, bool)+1330 in libminecraftpe.so+0x2615e52 [0xf1096e52]
#148 HYBRIS (null)+-179637076 in libminecraftpe.so+0x6a2e4ac [0xf54af4ac]
#152 HYBRIS mce::RenderContextOGL::drawIndexed(mce::PrimitiveMode, unsigned int, unsigned int)+275 in libminecraftpe.so+0x38f8233 [0xf2379233]
#158 HYBRIS (null)+-179637076 in libminecraftpe.so+0x6a2e4ac [0xf54af4ac]
#160 HYBRIS ScreenRenderBatch::_populateRenderControlsCollection(UIControl&, BatchClippingState const&, BatchClippingState const&, BatchVisualState const&, ClippedControlMetadata&, bool)+1421 in libminecraftpe.so+0x2615ead [0xf1096ead]
#170 HYBRIS (null)+-179637245 in libminecraftpe.so+0x6a2e403 [0xf54af403]
#172 HYBRIS (null)+-179637248 in libminecraftpe.so+0x6a2e400 [0xf54af400]
#175 HYBRIS (null)+-179637076 in libminecraftpe.so+0x6a2e4ac [0xf54af4ac]
#176 HYBRIS UIAnimFlipbook::tick(UIControl&, float)+404 in libminecraftpe.so+0x210cf94 [0xf0b8df94]
#189 HYBRIS (null)+-204850425 in libminecraftpe.so+0x5222b07 [0xf3ca3b07]
#190 HYBRIS operator delete(void*)+6 in libminecraftpe.so+0x51cb8b6 [0xf3c4c8b6]
#191 HYBRIS (null)+-179637076 in libminecraftpe.so+0x6a2e4ac [0xf54af4ac]
#192 HYBRIS (null)+-204849684 in libminecraftpe.so+0x5222dec [0xf3ca3dec]
#198 HYBRIS (null)+-179637076 in libminecraftpe.so+0x6a2e4ac [0xf54af4ac]
#200 HYBRIS ScreenRenderBatch::_populateRenderControlsCollection(UIControl&, BatchClippingState const&, BatchClippingState const&, BatchVisualState const&, ClippedControlMetadata&, bool)+1421 in libminecraftpe.so+0x2615ead [0xf1096ead]
#212 HYBRIS (null)+-204847872 in libminecraftpe.so+0x5223500 [0xf3ca4500]
#226 HYBRIS (null)+-179637076 in libminecraftpe.so+0x6a2e4ac [0xf54af4ac]
#235 HYBRIS (null)+-179637076 in libminecraftpe.so+0x6a2e4ac [0xf54af4ac]
#264 HYBRIS _ProfilerLiteTimer::~_ProfilerLiteTimer()+24 in libminecraftpe.so+0x16cda98 [0xf014ea98]
#284 HYBRIS (null)+-286968437 in libminecraftpe.so+0x3d258b [0xeee5358b]
#285 HYBRIS (null)+-268419076 in libminecraftpe.so+0x1582ffc [0xf0003ffc]
#291 HYBRIS _ProfilerLiteTimer::~_ProfilerLiteTimer()+24 in libminecraftpe.so+0x16cda98 [0xf014ea98]
#322 HYBRIS (null)+-286968437 in libminecraftpe.so+0x3d258b [0xeee5358b]
#518 HYBRIS (null)+-179637076 in libminecraftpe.so+0x6a2e4ac [0xf54af4ac]
Process exited with unexpected exit code: 6
```


This is what logs when I attempt to use a function key to change my volume.
I have the version from AUR on Manjaro.

**Comment by Mhowser** [comment]
Post FULL log please

**Comment by harjitmoe** [comment]
I have a keyboard in which the function keys serve as shortcuts for volume etc by default, the function key behaviour is attained by pressing them with Fn.&ensp;I am running Ubuntu 16.04.

When I try to change my volume with the keyboard keys, the game immediately crashes with (for instance, if I start it and immediately try) the following log: ```
16:08:18 Info  [Launcher] Version: client 9d41f29 / manifest 88ad96a
16:08:18 Info  [Launcher] CPU: AuthenticAMD AMD A6-7310 APU with AMD Radeon R4 Graphics    
16:08:18 Info  [Launcher] CPU supports SSSE3: YES
16:08:18 Trace [Launcher] Loading hybris libraries
16:08:18 Trace [HybrisUtils] Loaded OS library /usr/share/mcpelauncher/libs/native/libfmod.so.9.16
16:08:18 Trace [HybrisUtils] Loaded OS library libm.so.6
16:08:18 Trace [HybrisUtils] Loaded OS library libz.so.1
16:08:18 Trace [Launcher] Loading Minecraft library
16:08:26 Info  [Launcher] Loaded Minecraft library
16:08:26 Debug [Launcher] Minecraft is at offset 0xe753e000
16:08:26 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance16_syncDestroyGameEv
16:08:26 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social12XboxLiveUser22_handleUISignInNoErrorERN4xbox8services6system14sign_in_resultESt8functionIFvNS_12SignInResultEbEE
16:08:26 Info  [Launcher] Game version: 1.11.4
16:08:26 Info  [Launcher] Applying patches
16:08:26 Trace [Store] Vtable size = 34
16:08:26 Trace [Patch] Patching - original: 85 83 87 86 131
16:08:26 Trace [Patch] Patching - result: 233 53 242 108 31
16:08:26 Trace [Patch] Patching - original: 83 87 86 131 236
16:08:26 Trace [Patch] Patching - result: 233 119 156 208 30
16:08:26 Trace [Patch] Patching - original: 85 83 87 86 129
16:08:26 Trace [Patch] Patching - result: 233 123 33 199 28
16:08:26 Trace [Patch] Patching - original: 85 83 87 86 129
16:08:26 Trace [Patch] Patching - result: 233 159 98 5 29
16:08:26 Trace [Patch] Patching - original: 85 83 87 86 129
16:08:26 Trace [Patch] Patching - result: 233 181 114 5 29
16:08:26 Trace [Patch] Patching - original: 85 83 87 86 129
16:08:26 Trace [Patch] Patching - result: 233 1 95 5 29
16:08:26 Trace [Patch] Patching - original: 85 83 87 86 129
16:08:26 Trace [Patch] Patching - result: 233 51 198 4 29
16:08:26 Trace [Patch] Patching - original: 85 83 87 86 129
16:08:26 Trace [Patch] Patching - result: 233 45 186 4 29
16:08:26 Trace [Patch] Patching - original: 85 83 87 86 129
16:08:26 Trace [Patch] Patching - result: 233 17 242 6 29
16:08:26 Trace [Patch] Patching - original: 83 87 86 131 236
16:08:26 Trace [Patch] Patching - result: 233 47 89 5 29
16:08:26 Trace [Patch] Patching - original: 85 83 87 86 129
16:08:26 Trace [Patch] Patching - result: 233 223 131 5 29
16:08:27 Trace [Patch] Patching - original: 49 192 195 141 182
16:08:27 Trace [Patch] Patching - result: 233 139 181 102 31
16:08:27 Trace [Patch] Patching - original: 83 131 236 8 232
16:08:27 Trace [Patch] Patching - result: 233 185 219 34 29
16:08:27 Trace [Patch] Patching - original: 137 76 36 4 137
16:08:27 Trace [Patch] Patching - result: 232 202 237 215 28
16:08:27 Trace [Patch] Patching - original: 36 88 139 65 12
16:08:27 Trace [Patch] Patching - result: 232 213 237 215 28
16:08:27 Trace [TexelAAPatch] Found patch at @2a6e
16:08:27 Trace [TexelAAPatch] LDR instruction invalid; patch incompatible
16:08:27 Trace [Patch] Patching - original: 85 83 87 86 131
16:08:27 Trace [Patch] Patching - result: 233 97 137 111 31
16:08:27 Trace [Patch] Patching - original: 85 83 87 86 129
16:08:27 Trace [Patch] Patching - result: 233 3 136 111 31
16:08:27 Trace [Patch] Patching - original: 83 87 86 131 236
16:08:27 Trace [Patch] Patching - result: 233 193 136 111 31
16:08:27 Trace [Patch] Patching - original: 85 137 229 83 87
16:08:27 Trace [Patch] Patching - result: 233 222 30 191 28
16:08:27 Trace [Patch] Patching - original: 83 86 131 236 20
16:08:27 Trace [Patch] Patching - result: 233 151 242 193 30
16:08:27 Trace [Patch] Patching - original: 232 109 207 184 253
16:08:27 Trace [Patch] Patching - result: 232 41 54 72 29
16:08:27 Info  [Launcher] Creating window
16:08:27 Trace [Launcher] Loading gamepad mappings: /usr/share/mcpelauncher/gamecontrollerdb.txt
16:08:27 Trace [Launcher] Loading gamepad mappings: /usr/share/mcpelauncher/gamecontrollerdb.txt
16:08:27 Trace [Launcher] Initializing AppPlatform (vtable)
16:08:27 Trace [AppPlatform] Vtable size = 260
16:08:27 Trace [Launcher] Initializing AppPlatform (create instance)
16:08:27 Trace [Launcher] Initializing AppPlatform (initialize call)
16:08:27 Trace [AppPlatform] createDeviceID (from file): 44a740a6-1693-4e0f-9f1f-b28ca702ce0e
16:08:27 Info  [Launcher] OpenGL: version: OpenGL ES 3.1 Mesa 18.0.5, renderer: AMD MULLINS (DRM 2.43.0 / 4.4.0-154-generic, LLVM 6.0.0), vendor: X.Org
16:08:27 Trace [Launcher] Initializing MinecraftGame (create instance)
16:08:27 Trace [AppPlatform] getSystemRegion: en_US
16:08:27 Trace [Launcher] Initializing MinecraftGame (init call)
16:08:27 Info  [Launcher] Game initialized
16:08:27 Trace [AppPlatform] getDataUrl: /home/har/.local/share/mcpelauncher/versions/1.11.4.2/assets/
16:08:27 Info  [Cohtml] Initializing COHTML ver. 1.0.0.6
16:08:28 Debug [Cohtml] Opening task channel 2 on family 0
16:08:28 Debug [Cohtml] Opening task channel 0 on family 0
16:08:28 Info  [Cohtml] Coherent Renoir library initialized!
16:08:28 Info  [Cohtml] COHTML library initialized!
16:08:28 Debug [Cohtml] Opening task channel 2 on family 1
16:08:28 Info  [Cohtml] Failed to load dynamic library: MediaDecoders_Android.so with error: Cannot load library: load_library[1115]: Library 'libMediaDecoders_Android.so' not found
16:08:28 Debug [Cohtml] Inspector is disabled
16:08:28 Debug [Cohtml] Opening task channel 2 on family 2
16:08:28 Debug [Cohtml] Opening task channel 0 on family 2
16:08:28 Debug [Cohtml] Opening task channel 0 on family 1
16:08:28 Warn  [Cohtml] Unable to load default font name Noto Sans
16:08:31 Trace [AppPlatform] getDataUrl: /home/har/.local/share/mcpelauncher/versions/1.11.4.2/assets/
16:08:32 Trace [XboxLive] Reading xbox config file
16:08:32 Error [XSAPI.Android] java interop not initialized properly
16:08:32 Trace [Launcher] Creating store
16:08:32 Trace [Store] registerLicenseChangeCallback
16:08:32 Trace [Store] getStoreId: android.googleplay
16:08:32 Trace [Store] restoreFromCache
16:08:32 Trace [Launcher] HTTPRequestInternalAndroid::send stub called
16:08:32 Info  [Minecraft] NO LOG FILE! - [INFO NETWORK -156096704] IPv4 supported, port: 40746
16:08:32 Info  [Minecraft] NO LOG FILE! - [INFO NETWORK -156096704] IPv6 supported, port: 53773
16:08:32 Trace [AppPlatform] isTablet: true
16:08:32 Trace [AppPlatform] getSystemRegion: en_US
16:08:32 Trace [AppPlatform] getApplicationId: com.mojang.minecraftpe
16:08:32 Trace [Launcher] HTTPRequestInternalAndroid::send stub called
16:08:32 Trace [Launcher] HTTPRequestInternalAndroid::send stub called
16:08:32 Trace [Launcher] HTTPRequestInternalAndroid::send stub called
16:08:32 Trace [Launcher] HTTPRequestInternalAndroid::send stub called
16:08:32 Trace [Store] getStoreId: android.googleplay
16:08:32 Trace [XboxLive] verify_cert_chain_platform_specific stub called
16:08:32 Trace [XboxLive] verify_cert_chain_platform_specific stub called
16:08:32 Trace [XboxLive] verify_cert_chain_platform_specific stub called
16:08:32 Trace [XboxLive] verify_cert_chain_platform_specific stub called
16:08:32 Trace [XboxLive] verify_cert_chain_platform_specific stub called
16:08:32 Trace [XboxLive] verify_cert_chain_platform_specific stub called
16:08:32 Debug [Cohtml] Force prunning all orphaned images.
16:08:32 Debug [Cohtml] Force prunning all orphaned svgs.
16:08:32 Trace [XboxLive] verify_cert_chain_platform_specific stub called
16:08:32 Trace [XboxLive] verify_cert_chain_platform_specific stub called
16:08:32 Trace [Launcher] HTTPRequestInternalAndroid::send stub called
16:08:32 Trace [Store] getStoreId: android.googleplay
16:08:32 Trace [Store] receivedLicenseResponse: true
16:08:32 Trace [Store] isGameLicensed: true
16:08:32 Warn  [Store] getExtraLicenseData - not implemented
16:08:32 Trace [Launcher] HTTPRequestInternalAndroid::send stub called
16:08:32 Trace [Launcher] HTTPRequestInternalAndroid::send stub called
16:08:34 Debug [Cohtml] Force prunning all orphaned images.
16:08:34 Debug [Cohtml] Force prunning all orphaned svgs.
16:08:34 Trace [Launcher] HTTPRequestInternalAndroid::send stub called
16:08:34 Trace [Launcher] HTTPRequestInternalAndroid::send stub called
16:08:34 Trace [Launcher] HTTPRequestInternalAndroid::send stub called
16:08:34 Trace [XboxLive] verify_cert_chain_platform_specific stub called
16:08:34 Trace [XboxLive] verify_cert_chain_platform_specific stub called
16:08:34 Trace [XboxLive] verify_cert_chain_platform_specific stub called
16:08:34 Trace [XboxLive] verify_cert_chain_platform_specific stub called
16:08:35 Trace [XboxLive] verify_cert_chain_platform_specific stub called
16:08:35 Trace [XboxLive] verify_cert_chain_platform_specific stub called
16:08:35 Trace [XboxLive] verify_cert_chain_platform_specific stub called
16:08:35 Trace [XboxLive] verify_cert_chain_platform_specific stub called
16:08:36 Trace [XboxLive] verify_cert_chain_platform_specific stub called
16:08:36 Trace [XboxLive] verify_cert_chain_platform_specific stub called
16:08:36 Trace [XboxLive] verify_cert_chain_platform_specific stub called
16:08:36 Trace [XboxLive] verify_cert_chain_platform_specific stub called
16:08:36 Trace [Store] getStoreId: android.googleplay
16:08:36 Trace [Store] onPrimaryUserConnectedToPlatform
16:08:37 Info  [Minecraft] NO LOG FILE! - [INFO NETWORK -156096704] IPv4 supported, port: 58832
16:08:37 Info  [Minecraft] NO LOG FILE! - [INFO NETWORK -156096704] IPv6 supported, port: 53029
16:08:37 Trace [Store] queryProducts
16:08:37 Trace [Store] queryProducts
16:08:37 Trace [Launcher] HTTPRequestInternalAndroid::send stub called
16:08:37 Trace [Store] queryPurchases
16:08:37 Trace [Launcher] HTTPRequestInternalAndroid::send stub called
16:08:37 Trace [Launcher] HTTPRequestInternalAndroid::send stub called
16:08:37 Trace [XboxLive] verify_cert_chain_platform_specific stub called
16:08:37 Trace [XboxLive] verify_cert_chain_platform_specific stub called
16:08:37 Trace [Launcher] HTTPRequestInternalAndroid::send stub called
16:08:37 Trace [Launcher] HTTPRequestInternalAndroid::send stub called
16:08:41 Trace [Launcher] HTTPRequestInternalAndroid::send stub called
16:08:41 Trace [XboxLive] verify_cert_chain_platform_specific stub called
16:08:41 Trace [XboxLive] verify_cert_chain_platform_specific stub called
16:08:42 Trace [XboxLive] verify_cert_chain_platform_specific stub called
16:08:42 Trace [XboxLive] verify_cert_chain_platform_specific stub called
Signal 11 received
Backtrace elements: 17
#0 /usr/bin/mcpelauncher-client(_ZN12CrashHandler12handleSignalEiPv+0xb7) [0x82cb4bf]
#1 [0xf7726b30]
#2 /usr/bin/mcpelauncher-client(_ZN15WindowCallbacks10onKeyboardEi9KeyAction+0x230) [0x829e8fc]
#3 /usr/bin/mcpelauncher-client(_ZNKSt12_Mem_fn_baseIM15WindowCallbacksFvi9KeyActionELb1EEclIJiS1_EvEEvPS0_DpOT_+0x68) [0x82a977a]
#4 /usr/bin/mcpelauncher-client(_ZNSt5_BindIFSt7_Mem_fnIM15WindowCallbacksFvi9KeyActionEEPS1_St12_PlaceholderILi1EES7_ILi2EEEE6__callIvJOiOS2_EJLj0ELj1ELj2EEEET_OSt5tupleIJDpT0_EESt12_Index_tupleIJXspT1_EEE+0xa0) [0x82a7d7a]
#5 /usr/bin/mcpelauncher-client(_ZNSt5_BindIFSt7_Mem_fnIM15WindowCallbacksFvi9KeyActionEEPS1_St12_PlaceholderILi1EES7_ILi2EEEEclIIiS2_EvEET0_DpOT_+0x66) [0x82a5a54]
#6 /usr/bin/mcpelauncher-client(_ZNSt17_Function_handlerIFvi9KeyActionESt5_BindIFSt7_Mem_fnIM15WindowCallbacksFviS0_EEPS4_St12_PlaceholderILi1EES9_ILi2EEEEE9_M_invokeERKSt9_Any_dataOiOS0_+0x3e) [0x82a39e3]
#7 /usr/bin/mcpelauncher-client(_ZNKSt8functionIFvi9KeyActionEEclEiS0_+0x50) [0x82e028c]
#8 /usr/bin/mcpelauncher-client(_ZN10GameWindow10onKeyboardEi9KeyAction+0x37) [0x82dfe13]
#9 /usr/bin/mcpelauncher-client(_ZN11EGLUTWindow25_eglutKeyboardSpecialFuncEii+0x9c) [0x82df960]
#10 /usr/bin/mcpelauncher-client() [0x8321fb1]
#11 /usr/bin/mcpelauncher-client(_eglutNativeEventLoop+0x2e) [0x8322530]
#12 /usr/bin/mcpelauncher-client(eglutMainLoop+0x52) [0x8320b40]
#13 /usr/bin/mcpelauncher-client(_ZN11EGLUTWindow7runLoopEv+0x1a) [0x82df0e6]
#14 /usr/bin/mcpelauncher-client(main+0x1668) [0x828298a]
#15 /lib/i386-linux-gnu/libc.so.6(__libc_start_main+0xf7) [0xf6ed4637]
#16 /usr/bin/mcpelauncher-client() [0x8280e51]
Dumping stack...
#12 HYBRIS Font::drawCached(ScreenContext&, std::string const&, float, float, Color const&, bool, bool, mce::MaterialPtr*, int, bool, float, Color const&)+2270 in libminecraftpe.so+0x17238ae [0xe8c618ae]
#13 HYBRIS (null)+-413933568 in libminecraftpe.so+0x0000 [0xe753e000]
#104 HYBRIS ScreenRenderBatch::_populateRenderControlsCollection(UIControl&, BatchClippingState const&, BatchClippingState const&, BatchVisualState const&, ClippedControlMetadata&, bool)+1421 in libminecraftpe.so+0x2615ead [0xe9b53ead]
#116 HYBRIS (null)+-327805696 in libminecraftpe.so+0x5223500 [0xec761500]
Process exited with unexpected exit code: 6
```

**Comment by MCMrARM** [comment]
I'll fix this tomorrow

**Comment by dysphie** [comment]
This appears to be fixed, however, it seems to have spawned another issue where I'm unable to bind actions to my Alt key (It would previously work and show a generic name like Button224)
