### ISSUE TITLE
Game stuck after clicking the start button of launcher

### ISSUE THREAD

**Issue by Yushu2606** [minecraft-linux/mcpelauncher-manifest#842]
**Describe the bug**
Game Stuck, no window was shown.

**To Reproduce**
1. Click start button
2. Launcher is hidden and nothing shown
3. See error

**Expected behavior**
A window of Minecraft was be shown.

**Desktop (please complete the following information):**
 - OS: macOS 14.0
 - Version: v0.10.0-macOS-x86_64-0.2.435 (build 435)
 - Installation Type: dmg
 - Game Version: 1.20.0.01 (X86_64)

**Additional context**
```log
09:54:19 Info  [Launcher] Version: client 8986784 / manifest df4203b
09:54:19 Info  [Launcher] CPU: GenuineIntel VirtualApple @ 2.50GHz
09:54:19 Info  [Launcher] CPU supports SSSE3: YES
09:54:19 Trace [Launcher] Loading hybris libraries
09:54:19 Trace [Launcher] linker loaded
09:54:19 Trace [REDIRECT] /data/data/com.mojang.minecraftpe to /Users/User/Library/Application Support/mcpelauncher/
09:54:19 Trace [REDIRECT] /data/data/Applications/Minecraft Bedrock Launcher.app/Contents/proc/6235/cmdline to /Users/User/Library/Application Support/mcpelauncher/
09:54:19 Trace [REDIRECT] /data/data/Applications/Minecraft Bedrock Launcher.app/Contents/MacOS/./mcpelauncher-client to /Users/User/Library/Application Support/mcpelauncher/
09:54:19 Trace [REDIRECT] /data/data to /Users/User/Library/Application Support/mcpelauncher/
09:54:19 Trace [REDIRECT] . to /Users/User/Library/Application Support/mcpelauncher/versions/1.20.0.01/assets/
09:54:19 Trace [LinkerUtils] Loaded OS library libm.dylib
09:54:19 Trace [LinkerUtils] Loaded OS library libz.dylib
09:54:19 Trace [LinkerUtils] Loaded OS library /Applications/Minecraft Bedrock Launcher.app/Contents/Resources/mcpelauncher/lib/native/x86_64/libfmod.dylib
09:54:19 Trace [Launcher] Loading Minecraft library
linker: mcpelauncher_linker_notifylldb /Users/User/Library/Application Support/mcpelauncher/versions/1.20.0.01/lib/x86_64/libc++_shared.so 0x10c700000
09:54:20 Error [MinecraftUtils] Failed to load Minecraft: dlopen failed: cannot locate symbol "glBindRenderbuffer" referenced by "/Users/User/Library/Application Support/mcpelauncher/versions/1.20.0.01/lib/x86_64/libminecraftpe.so"...
09:54:20 Info  [Launcher] Loading gamepad mappings
09:54:20 Trace [Launcher] Loading gamepad mappings: /Applications/Minecraft Bedrock Launcher.app/Contents/Resources/mcpelauncher/gamecontrollerdb.txt
09:54:20 Info  [Launcher] Creating window
linker: mcpelauncher_linker_notifylldb /Users/User/Library/Application Support/mcpelauncher/versions/1.20.0.01/lib/x86_64/libminecraftpe.so 0x11bc80000
Found hook: _ZN11AppPlatform16showMousePointerEv @ 0x1009d5b50
Found hook: _ZN11AppPlatform16hideMousePointerEv @ 0x1009d5b30
Found hook: _ZN11AppPlatform17setFullscreenModeE14FullscreenMode @ 0x1009d5b70
09:54:22 Info  [Launcher] Loaded Minecraft library
09:54:22 Debug [Launcher] Minecraft is at offset 0x11BC80000
09:54:22 Info  [Launcher] Game version: 0.0.0.0
09:54:22 Info  [Launcher] Applying patches
09:54:22 Debug [CorePatches] Failed to patch, vtable _ZTV21AppPlatform_android23 not found
09:54:22 Info  [Launcher] Initializing JNI
09:54:22 Error [JniSupport] Missing native symbol: Java_com_mojang_minecraftpe_MainActivity_nativeRegisterThis
09:54:22 Error [JniSupport] Missing native symbol: Java_com_mojang_minecraftpe_MainActivity_nativeInitializeWithApplicationContext
09:54:22 Error [JniSupport] Missing native symbol: Java_com_mojang_minecraftpe_MainActivity_nativeUnregisterThis
09:54:22 Error [JniSupport] Missing native symbol: Java_com_mojang_minecraftpe_MainActivity_nativeinitializeLibHttpClient
09:54:22 Error [JniSupport] Missing native symbol: Java_com_mojang_minecraftpe_NetworkMonitor_nativeUpdateNetworkStatus
09:54:22 Error [JniSupport] Missing native symbol: Java_com_microsoft_xal_browser_WebView_urlOperationSucceeded
09:54:22 Error [JniSupport] Missing native symbol: Java_com_mojang_minecraftpe_PlayIntegrity_nativePlayIntegrityComplete
09:54:22 Trace [Minecraft] Entering JNI_OnLoad 0x306c5b000
09:54:22 Info  [Launcher] Executing main thread
09:54:22 Trace [Minecraft] JNI_OnLoad completed
09:54:22 Trace [JniSupport] Invoking nativeRegisterThis
09:54:22 Trace [JniSupport] Invoking ANativeActivity_onCreate
09:54:22 Warn  [Main] Android stub called
09:54:22 Warn  [Main] Android stub called
09:54:22 Warn  [Main] Android stub called
09:54:22 Warn  [Main] Android stub called
09:54:22 Trace [JniSupport] Invoking start activity callbacks
09:54:22 Info  [Minecraft] android_main starting. internalDataPath is '/internal', externalDataPath is '/external'
09:54:22 Error [MCPE] *** setCachedDeviceId(<hide>)
09:54:22 Info  [Bedrock] configureBreakpad with directory: /crash, sessionid is: <hide>
```

**Comment by ChristopherHX** [comment]
~~Due to transperency of Rosetta2 is it not 100% clear if you have an intel mac. If you have one skip my questions with (m1).~~ You have an m1. CPU name in log

Have applied the Rosetta2 Workaround (m1)?

https://developer.apple.com/documentation/macos-release-notes/macos-14-release-notes

Have you tried to use the arm64 version https://github.com/minecraft-linux/mcpelauncher-manifest/discussions/819#discussion-5090919 (m1)?

Have you tried to use Metal? (Profile editor / pencil button) Or tried with OpenGL if you were using metal.

**Comment by Yushu2606** [comment]
> Have applied the Rosetta2 Workaround (m1)?
> 
yes, I'm using Rosetta2 for m2 chip
> Have you tried to use the arm64 version [#819 (comment)](https://github.com/minecraft-linux/mcpelauncher-manifest/discussions/819#discussion-5090919) (m1)?
> 
sorry but I can not found the arm64 version of this
> Have you tried to use Metal? (Profile editor / pencil button) Or tried with OpenGL if you were using metal.
> 
yes, but everything is same

**Comment by ChristopherHX** [comment]
The arm64 game launcher is included in the launcher you have installed, but hidden under developer options

- Go to settings (gear icon, don't press play)
- Switch to tab "Dev"
- Check unsupported versions (Disable this setting if you leave the experiment)
- Close settings
- Press edit profil (pencil)
- change the version from the dropdown
- select 1.19.70.02 (arm64-v8a)
- press download and play

> change the version from the dropdown

This is a long list, after "unsupported versions" is enabled it shows all variants known to the launcher. You have to scroll past the intel versions.

**Comment by Yushu2606** [comment]
> The arm64 game launcher is included in the launcher you have installed, but hidden under developer options
> 
> * Go to settings (gear icon, don't press play)
> * Switch to tab "Dev"
> * Check unsupported versions (Disable this setting if you leave the experiment)
> * Close settings
> * Press edit profil (pencil)
> * change the version from the dropdown
> * select 1.19.70.02 (arm64-v8a)
> * press download and play
> 
> > change the version from the dropdown
> 
> This is a long list, after "unsupported versions" is enabled it shows all variants known to the launcher. You have to scroll past the intel versions.

game can be open now, but it said `Failed to open Xboxlive login Window. Please look into the gamelog for more Information: mcpelauncher-webview not found` when i try to login to xbox live

**Comment by ChristopherHX** [comment]
> game can be open now, but it said `Failed to open Xboxlive login Window. Please look into the gamelog for more Information: mcpelauncher-webview not found` when i try to login to xbox live

I cannot help you with that problem, I don't own apple m series hardware.
The x86_64 launcher finds it, but as you explained it can no longer be used starting with macOS 14 on m series hardware via rosetta2.

Building an arm64 `mcpelauncher-webview` is not possible with the current CI/CD workflow.


Does adding the `path/to/x.app/Contents/MacOs/` (`path/to/x.app` this text have to be changed) folder to `PATH` env var make the error disappear or change?

**Comment by Yushu2606** [comment]
> `path/to/x.app`

thanks for your help but change this to what?

**Comment by ChristopherHX** [comment]
> change this to what?

Path to this launcher app. You can install it literally anywhere, not only in `/Applications/Minecraft Bedrock Launcher.app`.

**Comment by Yushu2606** [comment]
> > change this to what?
> 
> Path to this launcher app. You can install it literally anywhere, not only in `/Applications/Minecraft Bedrock Launcher.app`.

I added `export PATH = "/Applications/Minecraft Bedrock Launcher.app/Contents/MacOS/:$PATH"`(the app is in there) into `/private/etc/profile` but nothing changed

**Comment by ChristopherHX** [comment]
I have my doubts that your change was applied to GUI apps. (I'm also not shure that ` = ` works, usually you should avoid any spaces, e.g. bash is weird)

Try to type this into your Terminal, while the app is closed
```
PATH="/Applications/Minecraft Bedrock Launcher.app/Contents/MacOS/:$PATH" mcpelauncher-ui-qt
```

**Comment by Yushu2606** [comment]
> I have my doubts that your change was applied to GUI apps. (I'm also not shure that `=` works, usually you should avoid any spaces, e.g. bash is weird)
> 
> Try to type this into your Terminal, while the app is closed
> 
> ```
> PATH="/Applications/Minecraft Bedrock Launcher.app/Contents/MacOS/:$PATH" mcpelauncher-ui-qt
> ```

it is worked! thank you very much! I will close this issue after I ensure everything is fine
