### ISSUE TITLE
Directly import apk without Google Account

### ISSUE THREAD

**Issue by 1RandomDev** [minecraft-linux/mcpelauncher-manifest#844]
**Is your feature request related to a problem? Please describe.**
Currently you need to buy the game on Google Play and sign in with your Google Account which is really annoying.

**Describe the solution you'd like**
I would like a feature where you could directly import the Minecraft APK without having to rely on Google Play. I don't care if the Google Play Licensing API doesn't work without a signed in account.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by Mhowser** [comment]
Minecraft is a paid program which is required to sign in for downloading, it sounds like you just want to download it for free. Sorry, but this launcher will never support this, it could cause legal problems that would lead to this project shutting down.

**Comment by 1RandomDev** [comment]
Maybe there's an easy fix that I can do myself?

**Comment by Mhowser** [comment]
I'm sure there is somewhere, but it will not be discussed here.
