### ISSUE TITLE
Unable to play media (audio and video) while Minecraft is open

### ISSUE THREAD

**Issue by callyral** [minecraft-linux/mcpelauncher-manifest#845]
**Describe the bug**
While the game is open, I am unable to play audio or video outside of Minecraft. If media is playing while Minecraft starts, then the opposite happens, media is able to play while Minecraft has no audio.

**To Reproduce**
1. Open mcpelauncher
2. Click play
3. Try to play video or sound using any program (Firefox, mpv, etc)

**Expected behavior**
Minecraft being open should not interfere with other software's video or audio.

**Screenshots**
![image](https://github.com/minecraft-linux/mcpelauncher-manifest/assets/125226346/4ddc5aca-d407-44bb-984a-a9fb92c2f7b6)
![image](https://github.com/minecraft-linux/mcpelauncher-manifest/assets/125226346/04ee80b0-a7b8-469c-9564-2c3810ca9712)
(it stays loading even though my internet is fine)

**Desktop:**
 - OS: Linux (on Wayland)
 - Version v0.10.0.716-AppImage-x86_64 (build 716)
 - Installation Type AppImage

**Additional context**
I think the reason for this is most likely Pipewire, although I don't get the issue with any other programs and I'm able to play different media types at once. It's most likely not some kind of hardware limitation as I am able to play other games (like Minecraft Java) with other media playing just fine.

**Comment by AvoLadrian** [comment]
No, this is not because of the Audio Backend. 

I think this is because your Audio Drivers are not installed correctly. Or you may have not installed Pipewire ALSA.
This situation is new and has no Workarounds for now.

**Comment by callyral** [comment]
Installing `pipewire-alsa` fixes it for me. Before I only had `pipewire`, `wireplumber` and `pipewire-pulse`.
