### ISSUE TITLE
Trying to sign in on a Family Link account fails.

### ISSUE THREAD

**Issue by NexusSfan** [minecraft-linux/mcpelauncher-manifest#857]
**Describe the bug**
When trying to sign in on a Family Link managed account it says that the device is incompatible.

**To Reproduce**
1. Get a Family Link managed account.
2. Go to the sign in child window.
3. Try to log in under Family Link managed account.

**Expected behavior**
It should have just went to the parent verification screen.

**Screenshots**
![Screenshot of the error](https://github.com/minecraft-linux/mcpelauncher-manifest/assets/131726447/106fde8b-9935-4a84-be52-cfda2c83b9ba)

**Desktop:**
 - OS: Linux Mint 21.1 Cinnamon
 - Version: 0.10.0
 - Installation Type: apt

**Additional context**
This seems to be a GApps problem or something like that. I don't know.

Yes, I have tried a ["solution"](https://github.com/minecraft-linux/mcpelauncher-manifest/issues/766#issuecomment-1429693905) but it doesn't seem to work.

**Comment by NexusSfan** [comment]
It seems as the browser User Agent or browser version is outdated.
Still is not fixed.

**Comment by NexusSfan** [comment]
[This line of text](https://github.com/minecraft-linux/playdl-signin-ui-qt/blob/c80aea9fe3982be53f16b1c76b0790b03d493e99/src/googleloginwindow.cpp#L109) seems to be the user agent being defined. Maybe try switching the user agent to something new?

**Comment by ChristopherHX** [comment]
User-Agent is irrelevant, even on a real android smartphone with android 9 you see this error on a restricted account. 

Tested over a half year ago, with an android webview. The first thing what worked for me was to use fake gapps login flows.

**Comment by ChristopherHX** [comment]
The best thing is to use a **regular** account with this launcher.

You are forced to enter the credentials of the regular account in both cases, the restricted account has a login barrier.

**Comment by NexusSfan** [comment]
> User-Agent is irrelevant, even on a real android smartphone with android 9 you see this error on a restricted account.
> 
> Tested over a half year ago, with an android webview. The first thing what worked for me was to use fake gapps login flows.

Android 9 has Gapps support, and [official documentation](https://support.google.com/families/answer/7158477?hl=en&sjid=4150610134880556874-NC#zippy=:~:text=If%20you%20manage%20your%20child%E2%80%99s%20Google%20Account%20with%20Family%20Link%2C%20you%20can%20sign%20them%20in%20on%20devices%20with%20Android%205.1%20and%20higher.%20Your%20child%20can%27t%20sign%20in%20on%20devices%20with%20Android%205.0%20and%20lower%20while%20their%20account%20is%20managed%20with%20Family%20Link.) says that it should work for 5.1 and up. Is this due to bad design of the launcher's Webview?
And if so, then why not add an option to add account tokens manually?

**Comment by ChristopherHX** [comment]
> Is this due to bad design of the launcher's Webview?

No, Google Login for that kind of account needs more than a android webview. It needs to be a special gapps webview for resticted accounts to pass the check.

My regualar Google Account can sign in via Firefox and Chromium. Your account can't.

> And if so, then why not add an option to add account tokens manually?

It worked for me, if you enter the login tokens into the manual login flow.

That option only exists in qt6 versions of the launcher, e.g. AppImage bookworm and flatpak.

_Any reason why you need to login with a parental controlled account?_ The account registered as parent also need to sign in anyway or login is denied.

**Comment by NexusSfan** [comment]
> _Any reason why you need to login with a parental controlled account?_ The account registered as parent also need to sign in anyway or login is denied.

I know that.
I'm just testing some Family Link features.

> No, Google Login for that kind of account needs more than a android webview. It needs to be a special gapps webview for resticted accounts to pass the check.

Use a real Web Browser for login. I know for sure you can log in onto web browser on family link

> It worked for me, if you enter the login tokens into the manual login flow.
> 
> That option only exists in qt6 versions of the launcher, e.g. AppImage bookworm and flatpak.

Okay. So that's the only working method.
