### ISSUE TITLE
Add a default resolution setting within the launcher.

### ISSUE THREAD

**Issue by MisterSheeple** [minecraft-linux/mcpelauncher-manifest#858]
**Is your feature request related to a problem? Please describe.**
Related to #841, where the game is unable to change resolutions on Steam Deck/in Steam's gamepadui due to the maximize button not being shown in this mode. The game by default starts at a low resolution (and wrong aspect ratio), so it degrades the playing experience by not being able to change it.

**Describe the solution you'd like**
An option should be added to the launcher allowing the user to set the default resolution the game should start at.

**Describe alternatives you've considered**
N/A

**Comment by ChristopherHX** [comment]
Such a settings already exists. (Doesn't apply to f11 fullscreen)

- open profile editor
- enable custom resolution
- enter width and height in pixels

This works for x11 surfaces without window manager to get pseudo fullscreen.

I have no idea what gamemode does with a linux desktop application. After pressing f11 it's a glfw bug, which can be avoided by the AppImage release (**with touch support on steamdeck**).

**Comment by MisterSheeple** [comment]
I believe it just runs applications windowed in full screen so I don't think that'll be an issue. Thanks!
