### ISSUE TITLE
Failed to initialize Google Play API

### ISSUE THREAD

**Issue by sophiabiscottini** [minecraft-linux/mcpelauncher-manifest#859]
**Describe the bug**
When I start the launcher, it gives a warning:

**Please login again, Details:
No auth cookie field returned with statuscode: 403, body: Error=BadAuthentication**

I have already logged out and logged back into the account. Nothing changed.

I can play normally, however, I can't install new versions, because the laucher reports that I don't have Minecraft purchased.

**Screenshots**

![image](https://github.com/minecraft-linux/mcpelauncher-manifest/assets/73343507/b610f9cb-bc94-4f2f-9356-627a5e8751c1)

![image](https://github.com/minecraft-linux/mcpelauncher-manifest/assets/73343507/4b6b3d38-3cf9-479c-9911-7d53bd216be6)

![image](https://github.com/minecraft-linux/mcpelauncher-manifest/assets/73343507/ff0d4d58-10af-46d2-a814-c6cc2ed2130a)

![image](https://github.com/minecraft-linux/mcpelauncher-manifest/assets/73343507/3a76bb82-9a8a-4853-b88f-ecf2a680aa5e)

**Desktop (please complete the following information):**
 - OS: Linux (Arch Linux KDE 5 Plasma (5.27.6) - Kernel 6.4.2-arch1-1)
 - Version: v0.10.716-AppImage-x86_64-0.0.677 (build 716)
 - Installation Type:  AppImage

**Comment by sophiabiscottini** [comment]
Solution: The problem was the Google account. The password has been changed and the issue has been resolved.

**Comment by Genohki** [comment]
How did you fix it
