### ISSUE TITLE
Unable To Play 1.20

### ISSUE THREAD

**Issue by Brombos** [minecraft-linux/mcpelauncher-manifest#861]
**Describe the bug**
I like to play MineCraft so I found this,It was very reliable and then when 1.20 came out I installed it and I pressed play and this error came,
![Error Display](https://github.com/minecraft-linux/mcpelauncher-manifest/assets/138875448/f8763e5f-3431-4bb3-99dc-fb1e27ba8293)
So I went to the Dev settings and put these settings in,
![settings error](https://github.com/minecraft-linux/mcpelauncher-manifest/assets/138875448/bbc02d5a-cb69-4909-88b1-9148670bac16)
And the same error came

**To Reproduce**
1. Go to 'Profiles'
2. Click on 'Default' or use 1.20
3. Install 1.20
4. Press play
5. Error Pops Up

**Expected behavior**
I expected to Launch 1.20

**Desktop**
 - OS: Linux
 - Version: v0.9.0 (build 63)
 - Installation Type: flatpak

**Comment by ChristopherHX** [comment]
Please update your flatpak installation.

You have still version v0.9.0 while you need to update to v0.10.0 for 1.20.10.01.

You can see the latest version number here: https://flathub.org/apps/io.mrarm.mcpelauncher

run this command to apply the update (wiki: https://mcpelauncher.readthedocs.io/en/latest/getting_started/index.html#install-update-system-wide)
```sh
flatpak update
```

Unfortunately is flatpak install not able to update the package, while it works in `apt` and `dnf`.

**Comment by Brombos** [comment]
Thanks will do

**Comment by Brombos** [comment]
It worked, thanks for your time  :smile:
