### ISSUE TITLE
Wayland is forced and only software rendering is working

### ISSUE THREAD

**Issue by Haxorzz** [minecraft-linux/mcpelauncher-manifest#868]
**Describe the bug**
I had previously used flatseal to force the launcher to only use X11 (xwayland) as it was having issues, but a recent update seems to have broken it and will no longer run without wayland permissions. But when I entered the game I was getting abysmal performance which was later confirmed by the troubleshooter saying that it was running with software rendering.

**To Reproduce**
1. Use kwin wayland
2. Launch the flatpak
3. Check the troubleshooter
4. Software rendering

**Expected behavior**
GPU rendering should be working, or even x11 on its own

**Desktop (please complete the following information):**
 - OS: Manjaro Linux, wayland kwin, KDE
 - Version 0.10.0 (build 64)
 - Installation Type: flatpak

**Additional context**
Running latest nvidia on 6.1 kernel manjaro KDE wayland session.

**Comment by ChristopherHX** [comment]
You mean this change https://github.com/flathub/io.mrarm.mcpelauncher/pull/112? (The version number has not been incremented, because all merges to master are releases and flatpak don't seem to provide any information like rebuild number)

A flatpak runtime upgrade from 6.3 to 6.5 can break GPU's and fix others.

If you have affected hardware avoid using flatpak's, because your issue may appear and disappear without warning.

There are alternatives
- AppImage using system mesa
- AUR
- ~~deb/rpm repo~~ (your OS doesn't support this)

**Comment by Haxorzz** [comment]
Weirdly enough the appimage just doesn't launch. running in konsole just brings up nothing.

**Comment by GameParrot** [comment]
Nvidia gpu, right? Nvidia gpus have always had problems on xwayland. Try switching to x11 or compiling with glfw + wayland.

**Comment by Haxorzz** [comment]
Well it doesn't have any issues with any other xwayland apps? And it only started happening after an update to the app that forced the flatpak out of only x11 permissions?

**Comment by Haxorzz** [comment]
Appimage is also showing the exact same issue.

**Comment by Haxorzz** [comment]
Flatpak now works on x11 and xwayland but CPU rendering is still the only option

**Comment by Haxorzz** [comment]
Newest freedesktop platform update seems to have solved it. If anyone can comment on ways to prevent this from happening please message me.

**Comment by neondeex** [comment]
> Newest freedesktop platform update seems to have solved it. If anyone can comment on ways to prevent this from happening please message me.

Did you find a better way to fix it or just use the flatpack version?

**Comment by Haxorzz** [comment]
>  Did you find a better way to fix it or just use the flatpack version?

The issue was with the flatpack, it just fixed itself. I don't know exactly what causes it.
