### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by Bale001** [minecraft-linux/mcpelauncher-manifest#877]
**Describe the bug**
Launcher fails to login to my account.

**To Reproduce**
1. Try logging in
2. After logging in, it says that the login failed

**Expected behavior**
The login should not have failed.

**Screenshots**
<img width="630" alt="Screen Shot 2023-08-17 at 10 30 00 PM" src="https://github.com/minecraft-linux/mcpelauncher-manifest/assets/37880918/66827b70-8d72-4273-8652-26b3e02b8d51">

**Desktop (please complete the following information):**
 - OS: MacOS Monterey
 - Version v0.10.0-macOS-x86_64-0.2.435_macOS_10.13.0
 - Installation Type dmg

**Additional context**
I am on an M1 mac. I'm not sure if it's related or not. I tried opening with verbose enabled, but it didn't log anything helpful. 
I know for a fact that my login is correct, and that my account owns Minecraft.

**Comment by ChristopherHX** [comment]
Bug confirmed, requires changes to the launcher.

Either the email, userid or oauthtoken failed to extract by a server side change. (Ownership of the game is not required to get this error)

Manual login of qt6 versions of the launcher (flatpak, deb and rpm) is still working.

**Comment by ChristopherHX** [comment]
Please upgrade to v0.11.0+. The missing email is now replaced by a dummy one to avoid the bug. (You won't see your own email in settings in this case)

**Comment by Bale001** [comment]
Thanks, it's working now :D
