### ISSUE TITLE
Cannot update to v11

### ISSUE THREAD

**Issue by sunglocto** [minecraft-linux/mcpelauncher-manifest#880]
**Describe the bug**
I can't update to version 11.

**To Reproduce**
1. Click on new version banner

**Expected behavior**
Launcher updates to version 11

**Screenshots**
![image](https://github.com/minecraft-linux/mcpelauncher-manifest/assets/76428041/24436ad8-f9bb-46ad-b567-ea6524f054ac)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Version: v0.10.0.716-AppImage-x86_64 (build 716)
 - Installation Type: AUR (https://aur.archlinux.org/packages/mcbelauncher-bin)

**Comment by ChristopherHX** [comment]
I assume it's the fault of the AUR package, which stores the AppImage where you need admin rights to update the binary. 

Maybe run it with sudo? AppImagelauncher allows to install AppImages while allowing it to apply updates without sudo.

I just tested updating the exact same version of the launcher and it is not an server side issue.

You can always visit the wiki to get v11 of the launcher, the updater is best effort.
