### ISSUE TITLE
Minecraft Launcher closes itself

### ISSUE THREAD

**Issue by MisterKinn** [minecraft-linux/mcpelauncher-manifest#896]
I updated my Mac to macOS Sonoma, and I changed my Minecraft Launcher settings as #819 .
When I click Play button, Launcher Runs and closes itself immediately.
Here's the error I've got.

mcpelauncher/versions/1.20.31.01/lib/arm64-v8a/libminecraftpe.so+0x3106469 [0x15b109469]
#419 LINKER (null)+0x15b138c27 in /Users/kinn/Library/Application Support/mcpelauncher/versions/1.20.31.01/lib/arm64-v8a/libminecraftpe.so+0x3135c27 [0x15b138c27]
#420 LINKER (null)+0x15b109469 in /Users/kinn/Library/Application Support/mcpelauncher/versions/1.20.31.01/lib/arm64-v8a/libminecraftpe.so+0x3106469 [0x15b109469]
#667 LINKER (null)+0x1602651f8 in /Users/kinn/Library/Application Support/mcpelauncher/versions/1.20.31.01/lib/arm64-v8a/libminecraftpe.so+0x82621f8 [0x1602651f8]
#699 LINKER (null)+0x165c4eb48 in /Users/kinn/Library/Application Support/mcpelauncher/versions/1.20.31.01/lib/arm64-v8a/libminecraftpe.so+0xdc4bb48 [0x165c4eb48]
#735 LINKER (null)+0x160287df8 in /Users/kinn/Library/Application Support/mcpelauncher/versions/1.20.31.01/lib/arm64-v8a/libminecraftpe.so+0x8284df8 [0x160287df8]
program failed with unix signal number: 6

Process exited with unexpected exit code: 6

What should I do?

**Comment by ChristopherHX** [comment]
You didn't provide the full error and you didn't provide the launcher version you have been using (it's also it the full log)

It can happen that the first time to open the launcher fails, but retring it a second time works.

**Comment by MisterKinn** [comment]
<img width="496" alt="Screenshot 2023-10-01 at 14 13 30" src="https://github.com/minecraft-linux/mcpelauncher-manifest/assets/71118462/e0af0015-358c-4b07-91f8-2f4a0554c5ff">

This is full error.

14:12:43 Info  [Launcher] Version: client aee4cdb / manifest bc82df2
14:12:43 Trace [Launcher] Loading hybris libraries
14:12:43 Trace [Launcher] linker loaded
14:12:43 Trace [REDIRECT] /data/data/com.mojang.minecraftpe to /Users/kinn/Library/Application Support/mcpelauncher/
14:12:43 Trace [REDIRECT] /data/data/Applications/Minecraft.app/Contents/proc/5098/cmdline to /Users/kinn/Library/Application Support/mcpelauncher/
14:12:43 Trace [REDIRECT] /data/data/Applications/Minecraft.app/Contents/MacOS/./mcpelauncher-client-arm64-v8a to /Users/kinn/Library/Application Support/mcpelauncher/
14:12:43 Trace [REDIRECT] /data/data to /Users/kinn/Library/Application Support/mcpelauncher/
14:12:43 Trace [REDIRECT] . to /Users/kinn/Library/Application Support/mcpelauncher/versions/1.20.31.01/assets/
14:12:43 Trace [REDIRECT] /proc to /Users/kinn/Library/Application Support/mcpelauncher/proc/
14:12:43 Trace [LinkerUtils] Loaded OS library libm.dylib
linker: mcpelauncher_linker_notifylldb /Applications/Minecraft.app/Contents/Resources/mcpelauncher/lib/arm64-v8a/libc.so 0x104d82000
linker: mcpelauncher_linker_notifylldb /Applications/Minecraft.app/Contents/Resources/mcpelauncher/lib/arm64-v8a/liblog.so 0x104f02000
14:12:43 Trace [LinkerUtils] Loaded OS library libz.dylib
14:12:43 Trace [LinkerUtils] Loaded OS library /Applications/Minecraft.app/Contents/Resources/mcpelauncher/lib/native/arm64-v8a/libfmod.dylib
14:12:43 Trace [Launcher] Loading Minecraft library
linker: Warning: "/Users/kinn/Library/Application Support/mcpelauncher/versions/1.20.31.01/lib/arm64-v8a/libc++_shared.so" unused DT entry: unknown processor-specific (type 0x70000001 arg 0x0) (ignoring)
WARNING: linker: Warning: "/Users/kinn/Library/Application Support/mcpelauncher/versions/1.20.31.01/lib/arm64-v8a/libc++_shared.so" unused DT entry: unknown processor-specific (type 0x70000001 arg 0x0) (ignoring)
linker: mcpelauncher_linker_notifylldb /Users/kinn/Library/Application Support/mcpelauncher/versions/1.20.31.01/lib/arm64-v8a/libc++_shared.so 0x104f82000
14:12:43 Error [MinecraftUtils] Failed to load Minecraft: dlopen failed: cannot locate symbol "glBindRenderbuffer" referenced by "/Users/kinn/Library/Application Support/mcpelauncher/versions/1.20.31.01/lib/arm64-v8a/libminecraftpe.so"...
14:12:43 Info  [Launcher] Loading gamepad mappings
14:12:43 Trace [Launcher] Loading gamepad mappings: /Applications/Minecraft.app/Contents/Resources/mcpelauncher/gamecontrollerdb.txt
14:12:43 Info  [Launcher] Creating window
2023-10-01 14:12:43.432 mcpelauncher-client-arm64-v8a[5098:210340] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.
linker: mcpelauncher_linker_notifylldb /Users/kinn/Library/Application Support/mcpelauncher/versions/1.20.31.01/lib/arm64-v8a/libminecraftpe.so 0x280003000
Found hook: _ZN11AppPlatform16showMousePointerEv @ 0x100c2dee4
Found hook: _ZN11AppPlatform16hideMousePointerEv @ 0x100c2decc
Found hook: _ZN11AppPlatform17setFullscreenModeE14FullscreenMode @ 0x100c2defc
14:12:44 Info  [Launcher] Loaded Minecraft library
14:12:44 Debug [Launcher] Minecraft is at offset 0x280003000
14:12:44 Info  [Launcher] Game version: 0.0.0.0
14:12:44 Info  [Launcher] Applying patches
14:12:44 Info  [V8] Applying v8-flags --jitless
14:12:44 Debug [CorePatches] Failed to patch, vtable _ZTV21AppPlatform_android23 not found
14:12:44 Info  [Launcher] Initializing JNI
linker: mcpelauncher_linker_notifylldb /Applications/Minecraft.app/Contents/Resources/mcpelauncher/lib/arm64-v8a/libjnivmsupport.so 0x11ab03000
14:12:44 Error [JniSupport] Missing native symbol: Java_com_mojang_minecraftpe_MainActivity_nativeRegisterThis
14:12:44 Error [JniSupport] Missing native symbol: Java_com_mojang_minecraftpe_MainActivity_nativeInitializeWithApplicationContext
14:12:44 Error [JniSupport] Missing native symbol: Java_com_mojang_minecraftpe_MainActivity_nativeUnregisterThis
14:12:44 Error [JniSupport] Missing native symbol: Java_com_mojang_minecraftpe_MainActivity_nativeinitializeLibHttpClient
14:12:44 Error [JniSupport] Missing native symbol: Java_com_microsoft_xal_browser_WebView_urlOperationSucceeded
14:12:44 Error [JniSupport] Missing native symbol: Java_com_mojang_minecraftpe_PlayIntegrity_nativePlayIntegrityComplete
14:12:44 Trace [Minecraft] Entering JNI_OnLoad 0x6f54f000
14:12:44 Trace [Minecraft] JNI_OnLoad completed
14:12:44 Trace [JniSupport] Invoking nativeRegisterThis
14:12:44 Trace [JniSupport] Invoking ANativeActivity_onCreate
14:12:44 Info  [Launcher] Executing main thread
14:12:44 Warn  [Main] Android stub called
14:12:44 Warn  [Main] Android stub called
14:12:44 Warn  [Main] Android stub called
14:12:44 Warn  [Main] Android stub called
14:12:44 Info  [Minecraft] android_main starting. internalDataPath is '/internal', externalDataPath is '/external'
14:12:44 Trace [JniSupport] Invoking start activity callbacks
14:12:44 Error [MCPE] *** setCachedDeviceId(69d39ba8-a91e-4679-8603-11eb82e73c9e)
14:12:44 Info  [Bedrock] configureBreakpad with directory: /crash, sessionid is: 9b19eeca-6302-47ef-802e-17e4c8bee000
14:12:44 Info  [Bedrock] configureBreakpad called, directory is: /crash, sessionid is: 9b19eeca-6302-47ef-802e-17e4c8bee000
14:12:44 Error [XNNPACK] failed to parse the list of possible processors in /sys/devices/system/cpu/possible
14:12:44 Error [XNNPACK] failed to parse the list of present processors in /sys/devices/system/cpu/present
14:12:44 Error [XNNPACK] failed to parse both lists of possible and present processors
14:12:44 Info  [Minecraft] NO LOG FILE! - AppPlatform_android::setStorageDirectory - using External dir (NEW) - CurrentFileStoragePath is now '/Users/kinn/Library/Application Support/mcpelauncher/'
14:12:44 Error [XNNPACK] cpuinfo_get_packages_count called before cpuinfo is initialized
Signal 6 received
Backtrace elements: 11
#0 0   mcpelauncher-client-arm64-v8a       0x0000000100c3fe34 _ZN12CrashHandler12handleSignalEiPv + 332
#1 1   libsystem_platform.dylib            0x0000000183c19a24 _sigtramp + 56
#2 2   libsystem_pthread.dylib             0x0000000183beacc0 pthread_kill + 288
#3 3   libsystem_c.dylib                   0x0000000183afaa50 abort + 180
#4 4   ???                                 0x000000028cbfae38 0x0 + 10951306808
#5 5   ???                                 0x000000028cbfb12c 0x0 + 10951307564
#6 6   ???                                 0x0000000288252fa4 0x0 + 10874072996
#7 7   ???                                 0x00000002882651f8 0x0 + 10874147320
#8 8   ???                                 0x0000000288287df8 0x0 + 10874289656
#9 9   mcpelauncher-client-arm64-v8a       0x0000000100b728c8 main + 13724
#10 10  dyld                                0x0000000183871058 start + 2224
Dumping stack...
#5 LINKER (null)+0x0 in /Users/kinn/Library/Application Support/mcpelauncher/versions/1.20.31.01/lib/arm64-v8a/libminecraftpe.so+0xcbf7e38 [0x28cbfae38]
#6 LINKER (null)+0x0 in /Users/kinn/Library/Application Support/mcpelauncher/versions/1.20.31.01/lib/arm64-v8a/libminecraftpe.so+0xcbf812c [0x28cbfb12c]
#7 LINKER (null)+0x288252fa4 in /Users/kinn/Library/Application Support/mcpelauncher/versions/1.20.31.01/lib/arm64-v8a/libminecraftpe.so+0x824ffa4 [0x288252fa4]
#8 LINKER (null)+0x2882651f8 in /Users/kinn/Library/Application Support/mcpelauncher/versions/1.20.31.01/lib/arm64-v8a/libminecraftpe.so+0x82621f8 [0x2882651f8]
#9 LINKER (null)+0x288287df8 in /Users/kinn/Library/Application Support/mcpelauncher/versions/1.20.31.01/lib/arm64-v8a/libminecraftpe.so+0x8284df8 [0x288287df8]
#72 LINKER (null)+0x104dd3b94 in /Applications/Minecraft.app/Contents/Resources/mcpelauncher/lib/arm64-v8a/libc.so+0x51b94 [0x104dd3b94]
#111 LINKER (null)+0x286c2accc in /Users/kinn/Library/Application Support/mcpelauncher/versions/1.20.31.01/lib/arm64-v8a/libminecraftpe.so+0x6c27ccc [0x286c2accc]
#194 LINKER (null)+0x28dc99000 in /Users/kinn/Library/Application Support/mcpelauncher/versions/1.20.31.01/lib/arm64-v8a/libminecraftpe.so+0xdc96000 [0x28dc99000]
#207 LINKER (null)+0x286c2accc in /Users/kinn/Library/Application Support/mcpelauncher/versions/1.20.31.01/lib/arm64-v8a/libminecraftpe.so+0x6c27ccc [0x286c2accc]
#215 LINKER (null)+0x2831e6a46 in /Users/kinn/Library/Application Support/mcpelauncher/versions/1.20.31.01/lib/arm64-v8a/libminecraftpe.so+0x31e3a46 [0x2831e6a46]
#231 LINKER (null)+0x0 in /Users/kinn/Library/Application Support/mcpelauncher/versions/1.20.31.01/lib/arm64-v8a/libminecraftpe.so+0xcbf812c [0x28cbfb12c]
#235 LINKER (null)+0x288252fa4 in /Users/kinn/Library/Application Support/mcpelauncher/versions/1.20.31.01/lib/arm64-v8a/libminecraftpe.so+0x824ffa4 [0x288252fa4]
#239 LINKER (null)+0x2831091ad in /Users/kinn/Library/Application Support/mcpelauncher/versions/1.20.31.01/lib/arm64-v8a/libminecraftpe.so+0x31061ad [0x2831091ad]
#328 LINKER (null)+0x283109469 in /Users/kinn/Library/Application Support/mcpelauncher/versions/1.20.31.01/lib/arm64-v8a/libminecraftpe.so+0x3106469 [0x283109469]
#396 LINKER (null)+0x283109469 in /Users/kinn/Library/Application Support/mcpelauncher/versions/1.20.31.01/lib/arm64-v8a/libminecraftpe.so+0x3106469 [0x283109469]
#419 LINKER (null)+0x283138c27 in /Users/kinn/Library/Application Support/mcpelauncher/versions/1.20.31.01/lib/arm64-v8a/libminecraftpe.so+0x3135c27 [0x283138c27]
#420 LINKER (null)+0x283109469 in /Users/kinn/Library/Application Support/mcpelauncher/versions/1.20.31.01/lib/arm64-v8a/libminecraftpe.so+0x3106469 [0x283109469]
#667 LINKER (null)+0x2882651f8 in /Users/kinn/Library/Application Support/mcpelauncher/versions/1.20.31.01/lib/arm64-v8a/libminecraftpe.so+0x82621f8 [0x2882651f8]
#699 LINKER (null)+0x28dc4eb48 in /Users/kinn/Library/Application Support/mcpelauncher/versions/1.20.31.01/lib/arm64-v8a/libminecraftpe.so+0xdc4bb48 [0x28dc4eb48]
#735 LINKER (null)+0x288287df8 in /Users/kinn/Library/Application Support/mcpelauncher/versions/1.20.31.01/lib/arm64-v8a/libminecraftpe.so+0x8284df8 [0x288287df8]
program failed with unix signal number: 6

Process exited with unexpected exit code: 6


And the version of launcher is Version v0.11.2-macOS-x86_64-0.2.438(build 438).

And this is the screenshot of Launcher Settings.
<img width="498" alt="Screenshot 2023-10-01 at 14 15 45" src="https://github.com/minecraft-linux/mcpelauncher-manifest/assets/71118462/19996133-0686-4c34-8532-eddabdd83ef8">

**Comment by ChristopherHX** [comment]
You didn't install the latest update of the launcher. Only updating the game won't work.

Alternatively download the launcher again from and replace the application <https://github.com/minecraft-linux/macos-builder/releases/tag/v0.11.3-442>

This launcher has an in app updater, it shows you when an update is available if you open it after installing it outside of the dmg drive

**Comment by MisterKinn** [comment]
Now Minecraft Launcher works very well since I updated the Launcher.
Thanks for Everything!
