### ISSUE TITLE
sound not working....

### ISSUE THREAD

**Issue by djdisodo** [minecraft-linux/mcpelauncher-manifest#9]
on legacy one it works...

**Comment by pellcorp** [comment]
I got it working on ubuntu 18.04 with:
sudo apt-get install libpulse0:i386

**Comment by MCMrARM** [comment]
Please check https://github.com/minecraft-linux/mcpelauncher-manifest/wiki/Troubleshooting#no-audio
If it still doesn't work, reopen the issue.
