### ISSUE TITLE
MC launcher stopped working on Mac M2 Pro

### ISSUE THREAD

**Issue by mbmspmb** [minecraft-linux/mcpelauncher-manifest#917]
Guys, Minecraft is just not launching on my Mac M2 pro (14inch) Mac OS Sonoma. I've tried deleting all files, reinstalling, redownloading. Nothing is working. :(

This is the log. Please help!

16:30:59 Info  [Launcher] Version: client cd294ac / manifest 28cca8f
16:30:59 Info  [Launcher] CPU: GenuineIntel VirtualApple @ 2.50GHz
16:30:59 Info  [Launcher] CPU supports SSSE3: YES
16:30:59 Trace [Launcher] Loading hybris libraries
16:30:59 Trace [Launcher] linker loaded
16:30:59 Trace [REDIRECT] /data/data/com.mojang.minecraftpe to /Users/muneebh/Library/Application Support/mcpelauncher/
16:30:59 Trace [REDIRECT] /data/data/Applications/Minecraft Bedrock Launcher.app/Contents/proc/2669/cmdline to /Users/muneebh/Library/Application Support/mcpelauncher/
16:30:59 Trace [REDIRECT] /data/data/Applications/Minecraft Bedrock Launcher.app/Contents/MacOS/./mcpelauncher-client to /Users/muneebh/Library/Application Support/mcpelauncher/
16:30:59 Trace [REDIRECT] /data/data to /Users/muneebh/Library/Application Support/mcpelauncher/
16:30:59 Trace [REDIRECT] . to /Users/muneebh/Library/Application Support/mcpelauncher/versions/1.20.41.02/assets/
16:30:59 Trace [REDIRECT] /proc to /Users/muneebh/Library/Application Support/mcpelauncher/proc/
16:30:59 Trace [REDIRECT] /sys to /Users/muneebh/Library/Application Support/mcpelauncher/sys/
16:30:59 Trace [LinkerUtils] Loaded OS library libm.dylib
16:30:59 Trace [LinkerUtils] Loaded OS library libz.dylib
16:30:59 Trace [LinkerUtils] Loaded OS library /Applications/Minecraft Bedrock Launcher.app/Contents/Resources/mcpelauncher/lib/native/x86_64/libfmod.dylib
16:30:59 Trace [Launcher] Loading Minecraft library
linker: mcpelauncher_linker_notifylldb /Users/muneebh/Library/Application Support/mcpelauncher/versions/1.20.41.02/lib/x86_64/libc++_shared.so 0x110500000
16:31:01 Error [MinecraftUtils] Failed to load Minecraft: dlopen failed: cannot locate symbol "glBindRenderbuffer" referenced by "/Users/muneebh/Library/Application Support/mcpelauncher/versions/1.20.41.02/lib/x86_64/libminecraftpe.so"...
16:31:01 Info  [Launcher] Loading gamepad mappings
16:31:01 Trace [Launcher] Loading gamepad mappings: /Applications/Minecraft Bedrock Launcher.app/Contents/Resources/mcpelauncher/gamecontrollerdb.txt
16:31:01 Info  [Launcher] Creating window
linker: mcpelauncher_linker_notifylldb /Users/muneebh/Library/Application Support/mcpelauncher/versions/1.20.41.02/lib/x86_64/libminecraftpe.so 0x11a480000
Found hook: _ZN11AppPlatform16showMousePointerEv @ 0x10481a850
Found hook: _ZN11AppPlatform16hideMousePointerEv @ 0x10481a830
Found hook: _ZN11AppPlatform17setFullscreenModeE14FullscreenMode @ 0x10481a870
16:31:02 Info  [Launcher] Loaded Minecraft library
16:31:02 Debug [Launcher] Minecraft is at offset 0x11A480000
16:31:02 Info  [Launcher] Game version: 0.0.0.0
16:31:02 Info  [Launcher] Applying patches
16:31:02 Debug [CorePatches] Failed to patch, vtable _ZTV21AppPlatform_android23 not found
16:31:02 Info  [Launcher] Initializing JNI
16:31:02 Error [JniSupport] Missing native symbol: Java_com_mojang_minecraftpe_MainActivity_nativeRegisterThis
16:31:02 Error [JniSupport] Missing native symbol: Java_com_mojang_minecraftpe_MainActivity_nativeInitializeWithApplicationContext
16:31:02 Error [JniSupport] Missing native symbol: Java_com_mojang_minecraftpe_MainActivity_nativeUnregisterThis
16:31:02 Error [JniSupport] Missing native symbol: Java_com_mojang_minecraftpe_MainActivity_nativeinitializeLibHttpClient
16:31:02 Error [JniSupport] Missing native symbol: Java_com_microsoft_xal_browser_WebView_urlOperationSucceeded
16:31:02 Error [JniSupport] Missing native symbol: Java_com_mojang_minecraftpe_PlayIntegrity_nativePlayIntegrityComplete
16:31:02 Trace [Minecraft] Entering JNI_OnLoad 0x30e80b000
16:31:02 Info  [Launcher] Executing main thread
16:31:02 Trace [Minecraft] JNI_OnLoad completed
16:31:02 Trace [JniSupport] Invoking nativeRegisterThis
16:31:02 Trace [JniSupport] Invoking ANativeActivity_onCreate
16:31:02 Warn  [Main] Android stub called
16:31:02 Warn  [Main] Android stub called
16:31:02 Warn  [Main] Android stub called
16:31:02 Warn  [Main] Android stub called
16:31:02 Trace [JniSupport] Invoking start activity callbacks
16:31:02 Info  [Minecraft] android_main starting. internalDataPath is '/internal', externalDataPath is '/external'
16:31:02 Error [MCPE] *** setCachedDeviceId(0a2ae40d-53bc-4c2a-8c76-605cee6eaed0)
16:31:02 Info  [Bedrock] configureBreakpad with directory: /crash, sessionid is: b830ded6-b730-47b4-8814-5dfc997e461d

**Comment by ChristopherHX** [comment]
Intel versions of the game stopped working in Rosetta 2 of macOS Sonoma
No idea what apple did to only break rosetta 2.

- Press edit profil (pencil icon, next to Text Default)
- change the version from the dropdown
  - select `1.20.41.02 (arm64-v8a)`
- press download and play

I keep this issue open, because you are seeing an not working version without editing settings.

**Comment by mbmspmb** [comment]
It worked! Thank you so much!
