### ISSUE TITLE
libEGL warning: DRI2: failed to open radeonsi (search paths /usr/lib/i386-linux-gnu/dri:${ORIGIN}/dri:/usr/lib/dri)

### ISSUE THREAD

**Issue by BrianMedina0903** [minecraft-linux/mcpelauncher-manifest#92]
libEGL warning: DRI2: failed to open radeonsi (search paths /usr/lib/i386-linux-gnu/dri:${ORIGIN}/dri:/usr/lib/dri)
libEGL warning: DRI2: failed to open radeonsi (search paths /usr/lib/i386-linux-gnu/dri:${ORIGIN}/dri:/usr/lib/dri)
libEGL warning: DRI2: failed to open swrast (search paths /usr/lib/i386-linux-gnu/dri:${ORIGIN}/dri:/usr/lib/dri)
libEGL warning: DRI2: failed to open swrast (search paths /usr/lib/i386-linux-gnu/dri:${ORIGIN}/dri:/usr/lib/dri)
EGLUT: failed to initialize EGL display
Process exited with unexpected exit code: 1

**Comment by demitt** [comment]
Have the same.
Ubuntu 18.04 x64, SSD, Radeon.
libegl1-mesa:i386 is installed, but libegl1-mesa-drivers:i386 has not found in the repositories

**Comment by BrianMedina0903** [comment]
> Have the same.
> Ubuntu 18.04 x64, SSD, Radeon.
> libegl1-mesa:i386 has installed, but libegl1-mesa-drivers:i386 has not found in the repositories
> 
> **UPD:**
> Installing of libgl1-mesa-glx:i386 libgl1-mesa-dri:i386 resolves my problem.

Thank you very much, for helping me with my problem: D
