### ISSUE TITLE
x86 mcpe apk

### ISSUE THREAD

**Issue by ilobilo** [minecraft-linux/mcpelauncher-manifest#926]
I compiled the launcher and built appimage with ``-DLAUNCHER_ENABLE_GOOGLE_PLAY_LICENCE_CHECK=OFF``, because I don't own mc on *play store* and I want to use an external apk.
where can I get the x86 mcpe?

**Comment by ChristopherHX** [comment]
No, redistributing apks is against the term of use of Minecraft Bedrock Play Store, supporting piracy will be the end of this project for me.
