### ISSUE TITLE
Reenable Apk import feature for modding purposes, security reasons (unencrypted Google token storing) and potential Google account ban

### ISSUE THREAD

**Issue by ghost** [minecraft-linux/mcpelauncher-manifest#934]
Here's your corrected text:

**Is your feature request related to a problem? Please describe the problem.**

The problem is that users risk getting their Google accounts stolen, hacked, or banned due to the insecure storage of the token, which could be abused by malware. Additionally, using a third-party client to access the Play Store violates Google's ToS and may result in a ban (as I experienced with Aurora Store after just two weeks).

**Describe the solution you'd like**

I would like to propose re-enabling the APK import feature, but with a warning about piracy and the dangers of downloading APKs from unofficial sources.

**Comment by ChristopherHX** [comment]
> The problem is that you risk getting your Google account stolen

You can revoke the token remotely at any time, password is never stored anywhere.

You can suggest how to encrypt it. Ask every time for a password to decrypt?

> had this before with Aurora Store after just 2 weeks

Google didn't ban me for using the gplayapi, since Aug/Sep. 2019. I read that primary short lived throw away accounts not associated with real android devices or purchases were banned.

What did you do with your google account?

_Had even used the Aurora Store, before the ban wave. That tool made itself useless for me after it disallowed intel device spoofing on my phone_

> Reenable Apk import feature for modding purposes

Not disabled for modding purposes, button is active in settings if ownership has been proven.

"downloading APKs from unofficial sources" is illegal and I prefer not to mention it anywhere.

_There is an undocumented toggle to reenable the whole import apk only flow in the UI, beware **documenting or redistributing** builds of that configuration can **make me halt public development** and only legacy game version would work_ (Dev halt has already happened between Nov. 2021 - Sep. 2022)

**Comment by ChristopherHX** [comment]
> Reenable Apk import feature for modding purposes

You could also not own the game, because also pirates wouldn't know that this button is not disabled for game owners.

**Comment by ghost** [comment]
> You could also not own the game, because also pirates wouldn't know that this button is not disabled for game owners.

Good to know, but the other two reasons I mentioned keep me from using the feature. I don't want to risk getting my entire Google account banned or hacked because of this. Many people, including me, have valuable things on their Google Accounts that they don't want to lose due to a ban from Google or because of malware that steals the unencrypted token. I once created a temporary account for using Aurora Store, a third-party Google Play client that also requires login, and it only took two weeks for the account to be banned. Using Google's services through third-party clients violates their ToS, which also affects Bedrock Launcher.

Additionally, I would appreciate it if you didn't call me a "pirate." I consider piracy to be unethical and stealing, and I don't want to be blamed as one. I'm simply pointing out the security issues and problems with using this client via a Google Account.

**Comment by ChristopherHX** [comment]
> Also don't call me a "pirate"

Sorry I'm not a native english speaker and might misphrase my statement. I don't know if you own the game.

Pirates made sites distributing the game and linking to my work. Then I tried to stop them from doing their buisness by enforcing login and telling them I don't like what they are doing. They continued, until I hard disabled latest version support only for them. They started claiming I would violate the GPL. I leaked the mod stopping them doing that and paused development for ca. 1 year.

Breaking the copyright law is even worse than scratching the tos in my opinion.

To comply with tos, you need to buy an intel phone/tablet all other ways break tos too.

I'm willing to add token encryption, but not going back to make piracy easy again to prebuilt packages.

**Comment by ChristopherHX** [comment]
Why is allow apk import even worse in this launcher?

This launcher actively patches the game to not check the license, this can be more easiliy abused by pirates than on Android itself.

**Comment by ChristopherHX** [comment]
Again the feature is implemented, find the toggle build it privately for your own use and deal with all bugs it causes to the ui.

`mcpelauncher-extract` also allows unpacking apks and `mcpelauncher-client` runs it for you without touching tos

**Comment by ghost** [comment]
To be honest, if the APK import feature works flawlessly after verifying that the user actually owns the game and the token encryption is secure, I would consider this issue resolved.

The major issue I have with the current implementation is that almost any software, script, or other malicious actors could easily grab the token and gain full access to the user's Google Account. If the token were encrypted (perhaps with a random key for each user), it would undoubtedly make it more secure.

**Comment by ChristopherHX** [comment]
Encryption of
- email
- accountid
- account token
- token cache

Can now be enabled, in the latest code. Might take some hours to hit nightly or manifest, then it needs to be tested.

Security now depends on your password, that should never be saved by the launcher.

AES-256-CBC encryption stored as base64

> that almost any software, script or else could just grap the token and get full access to your Google Account

still possible if you leave the key blank, then it has to be stored on disk as an empty padsword is too weak.

**Comment by ghost** [comment]
I'm sad to say that I'm not a cryptographical expert, but the combination of AES-256-CBC and base64 sounds good. I also think that password security is fine, since people should use secure passwords regardless.

All in all, it sounds great what you have done so far. I will close this issue as soon as it hits the stable release, and if no major issues related to it are found.

**Comment by ChristopherHX** [comment]
It hit stable in v0.15.0 and obviously an usability issue occurred as setting a password leads to a password prompt and asking for it everytime you open the launcher

**Comment by ghost** [comment]
I don't really mind; it's better than having no security at all. And I'm not sure, but wasn't there an option to not encrypt? I can't really remember. If not, then you could consider adding this feature if people mind, or changing the way things work.
