### ISSUE TITLE
Unable to Connect to World

### ISSUE THREAD

**Issue by AwayCoast23465** [minecraft-linux/mcpelauncher-manifest#943]
**Describe the bug**
When I try to join my Friends Minecraft World, I get the vague issue 'Unable to connect to world'. also i get this 'issue' when i start the launcher (I say it in quotations because it doesnt prevent me from playing servers)

'Please login again, Details:
Failed to perform http request to https://android.clients.google.com/auth : CURLcode 7 Details: Failed to connect to android.clients.google.com port 443 after 5021 ms: Couldn't connect to server'

**To Reproduce**
1. Try to join multiplayer world
2. Get unable to connect to world/see error

**Expected behavior**
To join the multiplayer world

**Screenshots**
<img width="850" alt="Screenshot 2024-02-05 at 2 39 19 am" src="https://github.com/minecraft-linux/mcpelauncher-manifest/assets/113707774/9e6d4f78-9963-44e7-8d1a-3786d6378967">
<img width="625" alt="Screenshot 2024-02-05 at 2 39 11 am" src="https://github.com/minecraft-linux/mcpelauncher-manifest/assets/113707774/042299b7-c036-4159-b9ec-11fcb1d92153">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version 14.0

**Comment by ChristopherHX** [comment]
Unrelated to screenshot 2, that one means your internet is not stable or needs a vpn.

Please try the nightly, I expect it should make it possible to connect. Althought it's buggy and might not be fully connected to xbox live at the first try

it's as easy as getting a "Nightly" here : <https://github.com/minecraft-linux/mcpelauncher-manifest#nightly-prebuilds>

Related https://github.com/minecraft-linux/mcpelauncher-manifest/issues/963
