### ISSUE TITLE
Cant launch Minecraft after latest update (crash) - flatpak only

### ISSUE THREAD

**Issue by glubbfreund** [minecraft-linux/mcpelauncher-manifest#946]
**Describe the bug**
Cant launch Minecraft after latest update (crash)

**To Reproduce**
1. Start MCPE Launcher
2. Click on Play
3. Crash, see log
4. 
**Expected behavior**
Game launches as in prev. Version

**Desktop (please complete the following information):**
 - OS: Debian 12 (Linux)
 - latest update 
 - flatpak

**Additional context**
08:19:15 Info  [Launcher] Version: client 58bcdc2 / manifest 64a8374
08:19:15 Info  [Launcher] CPU: GenuineIntel Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
08:19:15 Info  [Launcher] CPU supports SSSE3: YES
08:19:15 Trace [Launcher] Loading hybris libraries
08:19:15 Trace [Launcher] linker loaded
terminate called after throwing an instance of 'std::runtime_error'
  what():  glfwInit error
Signal 6 received
Backtrace elements: 16
#0 /app/bin/mcpelauncher-client(_ZN12CrashHandler12handleSignalEiPv+0x12c) [0x5582625386fc]
#1 /usr/lib/x86_64-linux-gnu/libc.so.6(+0x3f100) [0x7f4847a3f100]
#2 /usr/lib/x86_64-linux-gnu/libc.so.6(+0x91204) [0x7f4847a91204]
#3 /usr/lib/x86_64-linux-gnu/libc.so.6(raise+0x1e) [0x7f4847a3f04e]
#4 /usr/lib/x86_64-linux-gnu/libc.so.6(abort+0xd7) [0x7f4847a287fc]
#5 /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xa9a59) [0x7f4847ea9a59]
#6 /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xb577a) [0x7f4847eb577a]
#7 /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xb57e5) [0x7f4847eb57e5]
#8 /usr/lib/x86_64-linux-gnu/libstdc++.so.6(__cxa_rethrow+0) [0x7f4847eb5a70]
#9 /app/bin/mcpelauncher-client(_ZN17GLFWWindowManagerC1Ev+0xc5) [0x55826253fc05]
#10 /app/bin/mcpelauncher-client(_ZN17GameWindowManager13createManagerEv+0x23) [0x55826253fda3]
#11 /app/bin/mcpelauncher-client(_ZN17GameWindowManager10getManagerEv+0x44) [0x55826253fa04]
#12 /app/bin/mcpelauncher-client(main+0x1610) [0x5582623f71e0]
#13 /usr/lib/x86_64-linux-gnu/libc.so.6(+0x2958a) [0x7f4847a2958a]
#14 /usr/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x8b) [0x7f4847a2964b]
#15 /app/bin/mcpelauncher-client(_start+0x25) [0x5582623f5535]
Dumping stack...
program failed with unix signal number: 6

Prozess wurde mit einen unerwarteten exitcode Beendet: 6

**Comment by glubbfreund** [comment]
Issue only occurs on flatpak version. Missing dependency (glfw)?

**Comment by RodoMa92** [comment]
Yeah, same here on deck. glfw fails initialization.

**Comment by RodoMa92** [comment]
Yep, now it works fine. Thanks :)

**Comment by ChristopherHX** [comment]
_At this time, the fix wasn't even deployed_
I cannot recommend to install the test versions due to not beeing updateable, I have to uninstall the test version each time I install them

It can still take some minutes, then just update again

**Comment by RodoMa92** [comment]
> _At this time, the fix wasn't even deployed_
> I cannot recommend to install the test versions due to not beeing updateable, I have to uninstall the test version each time I install them
> 
> It can still take some minutes, then just update again

Good to know, I'll reinstall it shortly then.
