### ISSUE TITLE
No Audio - Troubleshooting page didn't help

### ISSUE THREAD

**Issue by theEpicality** [minecraft-linux/mcpelauncher-manifest#95]
Hey there. I'm running your launcher on an Arch Linux distro and almost everything seems to work perfectly. The only issue I'm having is that the audio doesn't work. I have PulseAudio 12.2 using '/run/user/1000/pulse' as the runtime directory, and have '/home/*name*/.config/pulse' as the state directory. Any idea what's wrong?

**Comment by MCMrARM** [comment]
Install 32-bit pulse libs.
