### ISSUE TITLE
Library not loaded: /Users/runner/work/ghat3/ghat3/openssl/../ssl64/lib/libcrypto.3.dylib

### ISSUE THREAD

**Issue by olivia1246** [minecraft-linux/mcpelauncher-manifest#954]
**Describe the bug**
When I boot up Minecraft 1.20.62.02 on my Mac it fails to find the libcrypto.3.dylib

**To Reproduce**
1. Click Play Button
2. See error

**Expected behavior**
I expected all the libraries to be found and loaded and then start booting up Minecraft.

**Screenshots**
![Screenshot 2024-03-03 at 01 18 09](https://github.com/minecraft-linux/mcpelauncher-manifest/assets/135425765/79fb3fb4-ba4c-4dc1-96ad-46bc0de0edf3)

**Desktop (please complete the following information):**
 - OS: macOS Sonoma 14.3.1 arm64 (M2)
 - Version: Nightly (f1c13ff - commit)
 - Installation Type: .dmg

**Additional context**
File exists on my computer at the path: /opt/homebrew/opt/openssl/lib/libcrypto.3.dylib (redirects to /opt/homebrew/Cellar/openssl@3/3.2.1/lib/libcrypto.3.dylib)

**Comment by ChristopherHX** [comment]
Is the normal release still working?

**Comment by ChristopherHX** [comment]
Also as version please use the version displayed on the main screen of the launcher, the nightly tag / sha is not a real version identifier

**Comment by olivia1246** [comment]
> Is the normal release still working?

Thank you this did work and the game launched.

> Also as version please use the version displayed on the main screen of the launcher, the nightly tag / sha is not a real version identifier

Sorry I couldn't find the version located anywhere in the nightly it only contained: Version Unknown (build Unknown)

I will close this for now as I've found a solution.

**Comment by ChristopherHX** [comment]
Actually it lools like you downloaded the m1 test built before, that has been assembled by manually.. Thank you for letting me know that it contained such a big bug, others said it would had worked however they are seem to be wrong about this.
