### ISSUE TITLE
Version 1.20.71 does not appear

### ISSUE THREAD

**Issue by olligobber** [minecraft-linux/mcpelauncher-manifest#956]
**Describe the bug**
Version 1.20.71 does not appear in the launcher as a version that can be installed.

**To Reproduce**
1. Open launcher
2. Click button to edit profile in bottom left
3. Open version dropdown
4. Observe that no version after 1.20.62.02 is visible

**Expected behavior**
Version 1.20.71.01 should be visible

**Screenshots**
I can't screenshot the dropdown window

**Desktop (please complete the following information):**
 - Arch Linux
 - v0.13.0.786-AppImage-x86_64 (build 786)
 - Using this AUR package: https://aur.archlinux.org/packages/mcpelauncher-appimage

**Additional context**
It looks like the version was added to the list of versions here: https://github.com/minecraft-linux/mcpelauncher-versiondb/commit/a2583fbe810d2da63e33080f9f97dd97ecb74538

I have tried closing and reopening the launcher so that it updates its list of versions.

I have tried enabling beta versions, it shows 1.20.80 and 1.20.70, but when connecting to a server running 1.20.71 it says that 1.20.70 is out of date and on 1.20.80 it says the host is out of date.

**Comment by Eunuched** [comment]
Enable "Show unverified versions" in Launcher Settings > Dev

**Comment by olligobber** [comment]
> Enable "Show unverified versions" in Launcher Settings > Dev

I have tried that and it still does not show up in the list. I have turned on the options to show unverified versions, beta versions, and incompatible versions, and none of them make 1.20.71 show up in the list.

**Comment by kejuuu** [comment]
i found 1.20.71 on x86_64 but not the arm64-v8a on the launcher

**Comment by olligobber** [comment]
> i found 1.20.71 on x86_64 but not the arm64-v8a on the launcher

I am looking for x86_64, but scrolling down I don't see it for any architecture.

**Comment by olligobber** [comment]
Not sure if it will help, but I got a screenshot of the version dropdown:
![2024-03-15-013813_4176x1504_scrot](https://github.com/minecraft-linux/mcpelauncher-manifest/assets/11549963/a05713fe-ab28-47bd-8595-008675fbec0d)

**Comment by olligobber** [comment]
I just tried removing all the config files I could find in `~/.config` and `~/.local/share` that related to mcpelauncher, and removing and doing a clean install of the aur package, and the version list still looks the same.

**Comment by kejuuu** [comment]
i succesfully got the version by reinstalling everything, it shows up in my version dropdown

**Comment by olligobber** [comment]
> i succesfully got the version by reinstalling everything, it shows up in my version dropdown

I tried the same again after reading this, it still doesn't show. Maybe there's some config file I'm not seeing that I need to remove so it gets replaced with an updated version, but I don't see it anywhere. Short of wiping my whole drive and reinstalling the OS from scratch, which seems a bit extreme, I'm not sure what else I can try.

**Comment by olligobber** [comment]
Updating the launcher to 0.14.0 fixed it
