### ISSUE TITLE
AppImage nightly 0.14.0.258 not starting on Debian with wayland

### ISSUE THREAD

**Issue by wilfison** [minecraft-linux/mcpelauncher-manifest#960]
**Describe the bug**
QT cannot start a new wayland session.

**To Reproduce**
1. set appimage file as executable
2. run `./Minecraft_Bedrock_Launcher-bookworm.AppImage`

**Expected behavior**
It was expected to open the main launcher window

**Screenshots**
![image](https://github.com/minecraft-linux/mcpelauncher-manifest/assets/15096079/42718774-8c01-4194-8ca0-b261155c85e2)

**Desktop:**
 - OS: Debian GNU/Linux 12 (bookworm)
 - Version: v0.14.0.258
 - Installation Type: AppImage

**Additional context**

I can run the application by adding the following environment variable below:

```shell
export QT_QPA_PLATFORM=wayland-egl

./Minecraft_Bedrock_Launcher-bookworm-x86_64-v0.14.0.258.AppImage
```

**Comment by ChristopherHX** [comment]
I did retest the arm64 bookworm AppImage and it still works fine on wayland session.

_As long I'm on ubuntu 22.04 lts, I cannot run the bookworm AppImage on my system and have no intent to use a vm to diagnose problems_

Why don't you use the apt ppa?
- smaller (use system libs)
- updates via apt
