### ISSUE TITLE
[ not a bug ] workaround for the drowned issue

### ISSUE THREAD

**Issue by theotheroracle** [minecraft-linux/mcpelauncher-manifest#961]
i'm currently experiencing the drowned xbox live login issue with the appimage on nixos, however i was able to login without the popup by using the aka.ms/remoteconnect website if you enable remote login in the account settings, i hope this helps anyone else who encounters this issue

**Comment by Aahanv** [comment]
how do you use this @theotheroracle please elaborate?

**Comment by theotheroracle** [comment]
@Aahanv  in the account settings theres an option to use remote login, then once enabled. restart minecraft and try to login again, it will provide instructions to login from another device

**Comment by Aahanv** [comment]
@theotheroracle THANK YOU SO MUCH. YOU DONT KNOW HOW MUCH I NEEDED THIS!!!!! I CAN FINALLY PLAY MINECRAFT OMFG YOU ARE THE GOAT THANK YOU THANK THANK YOU

**Comment by theotheroracle** [comment]
happy to help 💖

**Comment by ghost** [comment]
@theotheroracle IT WORKED!! TYSM <3

**Comment by Oughie** [comment]
@theotheroracle I know this is one year old, but do you know whether this still works? I've enabled the option `Settings > Account > Use Remote Connect for Microsoft account Sign In (requires restart)`, restarted minecraft and clicked on the `Sign in` button again, yet I still get the `Drowned` error message. Any ideas?
