### ISSUE TITLE
Lastes version (1.20.73) is unsupported

### ISSUE THREAD

**Issue by Efka2280** [minecraft-linux/mcpelauncher-manifest#966]
When I try to run the latest Minecraft 1.20.73, I get the following error:

`Your previously downloaded Minecraft Version might be unsupported or just corrupted.
if you wanted to play a Beta or a new Release please wait patiently for an update,
please choose a compatible version from the profile Editor
otherwise if you have updated the Launcher recently.
e.g. a crash please delete it in Settings,
then download it again via the updated Launcher.`

I am able to load other Minecraft Bedrock versions with this launcher

 - OS: Linux Mint
 - Version 0.13.0 (Buid 74)
 - Flatpak

**Comment by ChristopherHX** [comment]
@Efka2280 Could you please install updates? See https://mcpelauncher.readthedocs.io/ for how you can do this.

Note: 1.20.7x is supported since Version 0.14.0 released ca. 3 weeks ago
