### ISSUE TITLE
Cannot download beta version

### ISSUE THREAD

**Issue by infrustrationMC** [minecraft-linux/mcpelauncher-manifest#97]
The launcher seems to be unable to download the beta versions. When I choose 1.12.0.6 for example and click the "Download and Play" button, the bar "Downloading Minecraft" appears for about 0,6s for the first time and then disapper. The next times I click it, the bar just instantly disappears.

**Comment by Mhowser** [comment]
You need to sign up as a tester in order to download beta builds

please see this section in the Troubleshooting page of the Wiki

https://mcpelauncher.readthedocs.io/en/latest/troubleshooting.html#the-launcher-crashes-when-i-press-download-and-play
