### ISSUE TITLE
Option to disable Vsync

### ISSUE THREAD

**Issue by fan87** [minecraft-linux/mcpelauncher-manifest#974]
**Is your feature request related to a problem? Please describe.**
The input latency is too high to be competitive in PvP, also the FPS is locked

**Describe the solution you'd like**
An option that hooks into eglSwapInterval (`fake_egl.cpp`), I did clone this repository and force it always be 0, and the problem was solved, probably configured in `mcpelauncher-client-settings.txt`

**Describe alternatives you've considered**
Making changes to the code

**Comment by ChristopherHX** [comment]
options.txt of the game also allows to control vsync, so I didn't have the need myself to add anything for it in the launcher

**Comment by fan87** [comment]
Wow, I never knew that MCPE has options.txt, thanks

**Comment by lucasmz-dev** [comment]
I think this would definitely be a nice feature to add as a lot of people probably don't know about this, I certainly didn't for a long while, and it does make a big difference in input lag, makes it kind of look like Java in ways.
