### ISSUE TITLE
The game crashes when I connect the Script debugger

### ISSUE THREAD

**Issue by AbstractScripts** [minecraft-linux/mcpelauncher-manifest#978]
**Describe the bug**
It is not possible to connect the JavaScript debugger to the game, after entering the command, the game closes

**To Reproduce**
1. Enable debugging in the behavior pack with the extension 
    https://marketplace.visualstudio.com/items?itemName=mojang-studios.minecraft-debugger
2. Type command "/script debugger connect <ip> <port>"  in chat

**Expected behavior**
The game should connect to the debugger

**Screenshots**
![image](https://github.com/minecraft-linux/mcpelauncher-manifest/assets/96104118/edc4757c-3c1c-43cb-9807-dfd7937a89d8)
![image](https://github.com/minecraft-linux/mcpelauncher-manifest/assets/96104118/7da9a501-4003-42d4-a4ee-f125c2169678)
![image](https://github.com/minecraft-linux/mcpelauncher-manifest/assets/96104118/22ff3643-a4c3-49d6-94f3-bf515db49cc4)

**Desktop (please complete the following information):**
 - OS: Linux [6.6.26-1-MANJARO]
 - Version v0.14.2 (build 78)
 - Installation Type: Flatpak

**Additional context**
Game Log: [log.txt](https://github.com/minecraft-linux/mcpelauncher-manifest/files/15272081/log.txt)

**Comment by ChristopherHX** [comment]
I only get the following message: "Failed to start debugger"

![image](https://github.com/minecraft-linux/mcpelauncher-manifest/assets/44845461/57d74e8e-9d02-4d5e-b976-19863d3db345)

_and on android 9 as well_

This buggy program might be not working so well on your Operating System or Hardware than on my own Devices.

I'm not shure if the bedrock dedicated server can be used for script debugging on ubuntu. This feature seem to target the windows app / bds.

**Comment by AbstractScripts** [comment]
Hmm, I just checked it out. It works fine on Windows, but it doesn't work on android. Apparently, because of this feature, nothing works.
