### ISSUE TITLE
Error Minecraft 1.12.0.6

### ISSUE THREAD

**Issue by BillVlad** [minecraft-linux/mcpelauncher-manifest#99]

**Comment by BillVlad** [comment]
/usr/bin/mcpelauncher-client: error while loading shared libraries: libEGL.so.1: cannot open shared object file: No such file or directory
Process exited with unexpected exit code: 127

**Comment by Mhowser** [comment]
Get the 32 bit graphics drivers, look in the wiki for which ones you need.
