### ISSUE TITLE
Game crushes on Launcher version 0.14.3(470) and version 0.15.0(472) on macOS

### ISSUE THREAD

**Issue by Chin-Me** [minecraft-linux/mcpelauncher-manifest#993]
### **Describe the bug**
Game crushes after click Play and a short showup of the game window. No Game content was loaded, not even the Minecraft icon.

### **To Reproduce**
Just launch the game in general.

### **Expected behavior**
Game crushes and a game log was generated.

### **Screenshots**
N/A

### **Desktop **
 - macOS, Chip: Apple M1 Pro
 - macOS Sonoma 14.4.1 (23E224)
 - Minecraft_Bedrock_Launcher_v0.14.3-macOS-x86_64-0.2.470_macOS_10.13.0.dmg
    Minecraft_Bedrock_Launcher_v0.15.0-macOS-x86_64-0.2.472_macOS_10.13.0.dmg

### **Additional context**
Game Log:
22:27:56 Info  [Launcher] Version: client a9e38d7 / manifest a7a2252
22:27:56 Info  [Launcher] Reading Launcher Settings File: /Users/simchin/Library/Application Support/mcpelauncher/mcpelauncher-client-settings.txt
22:27:56 Info  [Launcher] Applied Launcher Settings
22:27:56 Trace [Launcher] Loading android libraries
22:27:56 Trace [Launcher] linker loaded
22:27:56 Trace [REDIRECT] /data/data/com.mojang.minecraftpe to /Users/simchin/Library/Application Support/mcpelauncher/
22:27:56 Trace [REDIRECT] /data/data/Volumes/Minecraft Bedrock Launcher 1/Minecraft Bedrock Launcher.app/Contents/proc/84919/cmdline to /Users/simchin/Library/Application Support/mcpelauncher/
22:27:56 Trace [REDIRECT] /data/data/Volumes/Minecraft Bedrock Launcher 1/Minecraft Bedrock Launcher.app/Contents/MacOS/./mcpelauncher-client-arm64-v8a to /Users/simchin/Library/Application Support/mcpelauncher/
22:27:56 Trace [REDIRECT] /data/data to /Users/simchin/Library/Application Support/mcpelauncher/
22:27:56 Trace [REDIRECT] . to /Users/simchin/Library/Application Support/mcpelauncher/versions/1.20.81.01/assets/
22:27:56 Trace [REDIRECT] /proc to /Users/simchin/Library/Application Support/mcpelauncher/proc/
22:27:56 Trace [REDIRECT] /sys to /Users/simchin/Library/Application Support/mcpelauncher/sys/
22:27:56 Trace [LinkerUtils] Loaded OS library libm.dylib
linker: mcpelauncher_linker_notifylldb /Volumes/Minecraft Bedrock Launcher 1/Minecraft Bedrock Launcher.app/Contents/Resources/mcpelauncher/lib/arm64-v8a/libc.so 0x104282000
linker: mcpelauncher_linker_notifylldb /Volumes/Minecraft Bedrock Launcher 1/Minecraft Bedrock Launcher.app/Contents/Resources/mcpelauncher/lib/arm64-v8a/liblog.so 0x1078c2000
22:27:56 Trace [LinkerUtils] Loaded OS library libz.dylib
22:27:56 Trace [LinkerUtils] Loaded OS library /Volumes/Minecraft Bedrock Launcher 1/Minecraft Bedrock Launcher.app/Contents/Resources/mcpelauncher/lib/native/arm64-v8a/libfmod.dylib
22:27:56 Trace [Launcher] Loading Minecraft library
linker: Warning: "/Users/simchin/Library/Application Support/mcpelauncher/versions/1.20.81.01/lib/arm64-v8a/libc++_shared.so" unused DT entry: unknown processor-specific (type 0x70000001 arg 0x0) (ignoring)
WARNING: linker: Warning: "/Users/simchin/Library/Application Support/mcpelauncher/versions/1.20.81.01/lib/arm64-v8a/libc++_shared.so" unused DT entry: unknown processor-specific (type 0x70000001 arg 0x0) (ignoring)
linker: mcpelauncher_linker_notifylldb /Users/simchin/Library/Application Support/mcpelauncher/versions/1.20.81.01/lib/arm64-v8a/libc++_shared.so 0x107942000
22:27:56 Error [MinecraftUtils] Failed to load Minecraft: dlopen failed: cannot locate symbol "glBindRenderbuffer" referenced by "/Users/simchin/Library/Application Support/mcpelauncher/versions/1.20.81.01/lib/arm64-v8a/libminecraftpe.so"...
22:27:56 Info  [Launcher] Loading gamepad mappings
22:27:56 Trace [Launcher] Loading gamepad mappings: /Volumes/Minecraft Bedrock Launcher 1/Minecraft Bedrock Launcher.app/Contents/Resources/mcpelauncher/gamecontrollerdb.txt
22:27:56 Info  [Launcher] Creating window
2024-06-07 22:27:56.380 mcpelauncher-client-arm64-v8a[84919:9202422] WARNING: Secure coding is automatically enabled for restorable state! However, not on all supported macOS versions of this application. Opt-in to secure coding explicitly by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState:.
linker: mcpelauncher_linker_notifylldb /Users/simchin/Library/Application Support/mcpelauncher/versions/1.20.81.01/lib/arm64-v8a/libminecraftpe.so 0x145f84000
Found hook: _ZN11AppPlatform16showMousePointerEv @ 0x102dfad58
Found hook: _ZN11AppPlatform16hideMousePointerEv @ 0x102dfad40
Found hook: _ZN11AppPlatform17setFullscreenModeE14FullscreenMode @ 0x102dfad70
Found hook: _ZN3rtc10getifaddrsEPP7ifaddrs @ 0x102f1f650
Found hook: _ZN3rtc11freeifaddrsEP7ifaddrs @ 0x102f1f92c
22:27:56 Info  [Launcher] Loaded Minecraft library
22:27:56 Debug [Launcher] Minecraft is at offset 0x145F84000
22:27:56 Info  [Launcher] Game version: 0.0.0.0
22:27:56 Info  [Launcher] Applying patches
22:27:56 Info  [V8] Applying v8-flags --jitless
22:27:56 Debug [CorePatches] Failed to patch, vtable _ZTV21AppPlatform_android23 not found
22:27:56 Info  [Launcher] Initializing JNI
linker: mcpelauncher_linker_notifylldb /Volumes/Minecraft Bedrock Launcher 1/Minecraft Bedrock Launcher.app/Contents/Resources/mcpelauncher/lib/arm64-v8a/libjnivmsupport.so 0x123d83000
22:27:56 Error [JniSupport] Missing native symbol: Java_com_mojang_minecraftpe_MainActivity_nativeRegisterThis
22:27:56 Error [JniSupport] Missing native symbol: Java_com_mojang_minecraftpe_MainActivity_nativeInitializeWithApplicationContext
22:27:56 Error [JniSupport] Missing native symbol: Java_com_mojang_minecraftpe_MainActivity_nativeUnregisterThis
22:27:56 Error [JniSupport] Missing native symbol: Java_com_mojang_minecraftpe_MainActivity_nativeInitializeXboxLive
22:27:56 Error [JniSupport] Missing native symbol: Java_com_mojang_minecraftpe_MainActivity_nativeinitializeLibHttpClient
22:27:56 Error [JniSupport] Missing native symbol: Java_com_mojang_minecraftpe_MainActivity_nativeInitializeLibHttpClient
22:27:56 Error [JniSupport] Missing native symbol: Java_com_microsoft_xal_browser_WebView_urlOperationSucceeded
22:27:56 Error [JniSupport] Missing native symbol: Java_com_mojang_minecraftpe_PlayIntegrity_nativePlayIntegrityComplete
22:27:56 Trace [Minecraft] Entering JNI_OnLoad 0x6d427000
22:27:56 Trace [Minecraft] JNI_OnLoad completed
22:27:56 Trace [JniSupport] Invoking nativeRegisterThis
22:27:56 Trace [JniSupport] Invoking ANativeActivity_onCreate
22:27:56 Info  [Launcher] Executing main thread
22:27:56 Warn  [Main] Android stub called
22:27:56 Warn  [Main] Android stub called
22:27:56 Warn  [Main] Android stub called
22:27:56 Warn  [Main] Android stub called
22:27:56 Trace [JniSupport] Invoking start activity callbacks
22:27:56 Info  [Minecraft] android_main starting. internalDataPath is '/internal', externalDataPath is '/external'
22:27:56 Error [MCPE] *** setCachedDeviceId(667c3aa5-2b93-4bed-8b4b-cad7b1ac4b8b)
22:27:56 Info  [Bedrock] configureBreakpad with directory: /crash, sessionid is: 79d0bc90-6322-4a68-9f3b-4548843c2175
22:27:56 Info  [Bedrock] configureBreakpad called, directory is: /crash, sessionid is: 79d0bc90-6322-4a68-9f3b-4548843c2175
22:27:56 Info  [Minecraft] NO LOG FILE! - AppPlatform_android::setStorageDirectory - using External dir (NEW) - CurrentFileStoragePath is now '/Users/simchin/Library/Application Support/mcpelauncher/'
22:27:56 Warn  [Minecraft] NO LOG FILE! - [Graphics] The graphics context was gained
22:27:56 Warn  [Minecraft] NO LOG FILE! - [Graphics] The graphics context was gained
22:27:56 Warn  [Minecraft] MinecraftGame::init && MinecraftGame::setSize!
22:27:56 Warn  [FakeEGL] eglQueryString 308d
22:27:56 Warn  [Main] Android stub called
22:27:56 Info  [GL] Vendor: Google Inc. (Apple)
22:27:56 Info  [GL] Renderer: ANGLE (Apple, Apple M1 Pro, OpenGL 4.1 Metal - 88)
22:27:56 Info  [GL] Version: OpenGL ES 3.0.0 (ANGLE 2.1.22420 git hash: a3a43254afd1)
22:27:56 Info  [GL] Vendor: Google Inc. (Apple)
22:27:56 Info  [GL] Renderer: ANGLE (Apple, Apple M1 Pro, OpenGL 4.1 Metal - 88)
22:27:56 Info  [GL] Version: OpenGL ES 3.0.0 (ANGLE 2.1.22420 git hash: a3a43254afd1)
22:27:56 Warn  [Main] Android stub called
22:27:56 Info  [Minecraft] NO LOG FILE! - AppPlatform_android::setStorageDirectory - using AppData dir - CurrentFileStoragePath is now '/Users/simchin/Library/Application Support/mcpelauncher/'
linker: mcpelauncher_linker_notifylldb /Users/simchin/Library/Application Support/mcpelauncher/versions/1.20.81.01/lib/arm64-v8a/libMediaDecoders_Android.so 0x140582000
22:27:56 Info  [GL] Vendor: Google Inc. (Apple)
22:27:56 Info  [GL] Renderer: ANGLE (Apple, Apple M1 Pro, OpenGL 4.1 Metal - 88)
22:27:56 Info  [GL] Version: OpenGL ES 3.0.0 (ANGLE 2.1.22420 git hash: a3a43254afd1)
22:27:56 Warn  [Main] Android stub called
22:27:57 Debug [HttpCallStaticGlue] Successfully registerered HttpCall methods
22:27:57 Debug [XboxLiveAppConfig] Successfully registerered XboxLiveAppConfig methods
22:27:57 Debug [XSAPI.Android] Successfully registerered HttpCall tcuiMethods
libc++abi: terminating due to uncaught exception of type std::runtime_error: Unknown socket family when converting sockaddr from host
Signal 6 received
Backtrace elements: 19
#0 0   mcpelauncher-client-arm64-v8a       0x0000000102ef8ad8 _ZN12CrashHandler12handleSignalEiPv + 280
#1 1   libsystem_platform.dylib            0x000000018ff83584 _sigtramp + 56
#2 2   libsystem_pthread.dylib             0x000000018ff52c20 pthread_kill + 288
#3 3   libsystem_c.dylib                   0x000000018fe5fa20 abort + 180
#4 4   libc++abi.dylib                     0x000000018ff09d30 _ZN10__cxxabiv130__aligned_malloc_with_fallbackEm + 0
#5 5   libc++abi.dylib                     0x000000018fef9fcc _ZL28demangling_terminate_handlerv + 320
#6 6   libobjc.A.dylib                     0x000000018fb981e0 _ZL15_objc_terminatev + 160
#7 7   libc++abi.dylib                     0x000000018ff090f4 _ZSt11__terminatePFvvE + 16
#8 8   libc++abi.dylib                     0x000000018ff0c348 __cxa_get_exception_ptr + 0
#9 9   libc++abi.dylib                     0x000000018ff0c28c _ZN10__cxxabiv1L22exception_cleanup_funcE19_Unwind_Reason_CodeP17_Unwind_Exception + 0
#10 10  mcpelauncher-client-arm64-v8a       0x0000000102f1f910 _ZN4shim10getifaddrsEPPNS_6bionic7ifaddrsE + 704
#11 11  ???                                 0x0000000152627c78 0x0 + 5677153400
#12 12  ???                                 0x0000000152626fe4 0x0 + 5677150180
#13 13  ???                                 0x00000001526285c0 0x0 + 5677155776
#14 14  ???                                 0x0000000152641e74 0x0 + 5677260404
#15 15  ???                                 0x0000000152640764 0x0 + 5677254500
#16 16  ???                                 0x0000000152656f58 0x0 + 5677346648
#17 17  libsystem_pthread.dylib             0x000000018ff52f94 _pthread_start + 136
#18 18  libsystem_pthread.dylib             0x000000018ff4dd34 thread_start + 8
Dumping stack...
#12 LINKER rtc::BasicNetworkManager::CreateNetworks(bool, std::__ndk1::vector<std::__ndk1::unique_ptr<rtc::Network, std::__ndk1::default_delete<rtc::Network>>, std::__ndk1::allocator<std::__ndk1::unique_ptr<rtc::Network, std::__ndk1::default_delete<rtc::Network>>>>*) const+0x38 in /Users/simchin/Library/Application Support/mcpelauncher/versions/1.20.81.01/lib/arm64-v8a/libminecraftpe.so+0xc6a3c78 [0x152627c78]
#13 LINKER rtc::BasicNetworkManager::UpdateNetworksOnce()+0x44 in /Users/simchin/Library/Application Support/mcpelauncher/versions/1.20.81.01/lib/arm64-v8a/libminecraftpe.so+0xc6a2fe4 [0x152626fe4]
#14 LINKER rtc::BasicNetworkManager::UpdateNetworksContinually()+0x28 in /Users/simchin/Library/Application Support/mcpelauncher/versions/1.20.81.01/lib/arm64-v8a/libminecraftpe.so+0xc6a45c0 [0x1526285c0]
#15 LINKER rtc::Thread::Dispatch(absl::AnyInvocable<void () &&>)+0xa4 in /Users/simchin/Library/Application Support/mcpelauncher/versions/1.20.81.01/lib/arm64-v8a/libminecraftpe.so+0xc6bde74 [0x152641e74]
#16 LINKER rtc::Thread::ProcessMessages(int)+0xbc in /Users/simchin/Library/Application Support/mcpelauncher/versions/1.20.81.01/lib/arm64-v8a/libminecraftpe.so+0xc6bc764 [0x152640764]
#17 LINKER (null)+0x152656f58 in /Users/simchin/Library/Application Support/mcpelauncher/versions/1.20.81.01/lib/arm64-v8a/libminecraftpe.so+0xc6d2f58 [0x152656f58]
#237 LINKER absl::internal_any_invocable::EmptyManager(absl::internal_any_invocable::FunctionToCall, absl::internal_any_invocable::TypeErasedState*, absl::internal_any_invocable::TypeErasedState*)+0x0 in /Users/simchin/Library/Application Support/mcpelauncher/versions/1.20.81.01/lib/arm64-v8a/libminecraftpe.so+0xc62768c [0x1525ab68c]
#244 LINKER rtc::BasicNetworkManager::CreateNetworks(bool, std::__ndk1::vector<std::__ndk1::unique_ptr<rtc::Network, std::__ndk1::default_delete<rtc::Network>>, std::__ndk1::allocator<std::__ndk1::unique_ptr<rtc::Network, std::__ndk1::default_delete<rtc::Network>>>>*) const+0x38 in /Users/simchin/Library/Application Support/mcpelauncher/versions/1.20.81.01/lib/arm64-v8a/libminecraftpe.so+0xc6a3c78 [0x152627c78]
#247 LINKER (null)+0x153e16640 in /Users/simchin/Library/Application Support/mcpelauncher/versions/1.20.81.01/lib/arm64-v8a/libminecraftpe.so+0xde92640 [0x153e16640]
#249 LINKER (null)+0x153e16640 in /Users/simchin/Library/Application Support/mcpelauncher/versions/1.20.81.01/lib/arm64-v8a/libminecraftpe.so+0xde92640 [0x153e16640]
#255 LINKER (null)+0x153e16000 in /Users/simchin/Library/Application Support/mcpelauncher/versions/1.20.81.01/lib/arm64-v8a/libminecraftpe.so+0xde92000 [0x153e16000]
#262 LINKER rtc::BasicNetworkManager::UpdateNetworksOnce()+0x44 in /Users/simchin/Library/Application Support/mcpelauncher/versions/1.20.81.01/lib/arm64-v8a/libminecraftpe.so+0xc6a2fe4 [0x152626fe4]
#281 LINKER (null)+0x153e16000 in /Users/simchin/Library/Application Support/mcpelauncher/versions/1.20.81.01/lib/arm64-v8a/libminecraftpe.so+0xde92000 [0x153e16000]
#286 LINKER (null)+0x153e16640 in /Users/simchin/Library/Application Support/mcpelauncher/versions/1.20.81.01/lib/arm64-v8a/libminecraftpe.so+0xde92640 [0x153e16640]
#288 LINKER rtc::BasicNetworkManager::UpdateNetworksContinually()+0x28 in /Users/simchin/Library/Application Support/mcpelauncher/versions/1.20.81.01/lib/arm64-v8a/libminecraftpe.so+0xc6a45c0 [0x1526285c0]
#297 LINKER (null)+0x153e1669c in /Users/simchin/Library/Application Support/mcpelauncher/versions/1.20.81.01/lib/arm64-v8a/libminecraftpe.so+0xde9269c [0x153e1669c]
#304 LINKER (null)+0x153e16640 in /Users/simchin/Library/Application Support/mcpelauncher/versions/1.20.81.01/lib/arm64-v8a/libminecraftpe.so+0xde92640 [0x153e16640]
#306 LINKER rtc::Thread::Dispatch(absl::AnyInvocable<void () &&>)+0xa4 in /Users/simchin/Library/Application Support/mcpelauncher/versions/1.20.81.01/lib/arm64-v8a/libminecraftpe.so+0xc6bde74 [0x152641e74]
#317 LINKER (null)+0x153e16640 in /Users/simchin/Library/Application Support/mcpelauncher/versions/1.20.81.01/lib/arm64-v8a/libminecraftpe.so+0xde92640 [0x153e16640]
#320 LINKER rtc::Thread::ProcessMessages(int)+0xbc in /Users/simchin/Library/Application Support/mcpelauncher/versions/1.20.81.01/lib/arm64-v8a/libminecraftpe.so+0xc6bc764 [0x152640764]
#323 LINKER void absl::internal_any_invocable::RemoteManagerNontrivial<webrtc::SafeTask(rtc::scoped_refptr<webrtc::PendingTaskSafetyFlag>, absl::AnyInvocable<void () &&>)::'lambda'()>(absl::internal_any_invocable::FunctionToCall, absl::internal_any_invocable::TypeErasedState*, absl::internal_any_invocable::TypeErasedState*)+0x0 in /Users/simchin/Library/Application Support/mcpelauncher/versions/1.20.81.01/lib/arm64-v8a/libminecraftpe.so+0xc6276cc [0x1525ab6cc]
#324 LINKER void absl::internal_any_invocable::RemoteInvoker<false, void, webrtc::SafeTask(rtc::scoped_refptr<webrtc::PendingTaskSafetyFlag>, absl::AnyInvocable<void () &&>)::'lambda'()&&>(absl::internal_any_invocable::TypeErasedState*)+0x0 in /Users/simchin/Library/Application Support/mcpelauncher/versions/1.20.81.01/lib/arm64-v8a/libminecraftpe.so+0xc627690 [0x1525ab690]
#327 LINKER absl::internal_any_invocable::EmptyManager(absl::internal_any_invocable::FunctionToCall, absl::internal_any_invocable::TypeErasedState*, absl::internal_any_invocable::TypeErasedState*)+0x0 in /Users/simchin/Library/Application Support/mcpelauncher/versions/1.20.81.01/lib/arm64-v8a/libminecraftpe.so+0xc62768c [0x1525ab68c]
#337 LINKER (null)+0x153e16640 in /Users/simchin/Library/Application Support/mcpelauncher/versions/1.20.81.01/lib/arm64-v8a/libminecraftpe.so+0xde92640 [0x153e16640]
#340 LINKER (null)+0x152656f58 in /Users/simchin/Library/Application Support/mcpelauncher/versions/1.20.81.01/lib/arm64-v8a/libminecraftpe.so+0xc6d2f58 [0x152656f58]
#389 LINKER (null)+0x152656e74 in /Users/simchin/Library/Application Support/mcpelauncher/versions/1.20.81.01/lib/arm64-v8a/libminecraftpe.so+0xc6d2e74 [0x152656e74]
#690 LINKER (null)+0x153e16640 in /Users/simchin/Library/Application Support/mcpelauncher/versions/1.20.81.01/lib/arm64-v8a/libminecraftpe.so+0xde92640 [0x153e16640]
program failed with unix signal number: 6

Process exited with unexpected exit code: 6

**Comment by TobiasGrether** [comment]
Can confirm this is an issue, same here.

**Comment by ChristopherHX** [comment]
Not saw this error before, I need to guess about why this happened as this doesn't get generated on my test system.

I will try to patch this, but you need to try nightly dmg's, so I don't create another patch release with that bug

**Comment by TobiasGrether** [comment]
> Not saw this error before, I need to guess about why this happened as this doesn't get generated on my test system.
> 
> I will try to patch this, but you need to try nightly dmg's, so I don't create another patch release with that bug

Thats fine, I can run nightly dmgs. Could you ping me here or on discord once you have a nightly DMG out I can test?

**Comment by Chin-Me** [comment]
> Not saw this error before, I need to guess about why this happened as this doesn't get generated on my test system.
> 
> I will try to patch this, but you need to try nightly dmg's, so I don't create another patch release with that bug

No problem for me. Could you please tell me whenever you have an avaliable nightly version?  Thank you very much for paying so much effort on this project.

**Comment by ChristopherHX** [comment]
@Chin-Me @TobiasGrether 
Here is an zipped dmg of a change
https://github.com/minecraft-linux/mcpelauncher-manifest/actions/runs/9423130340/artifacts/1580728822

Or https://github.com/minecraft-linux/mcpelauncher-manifest/releases/tag/nightly
361+

**Comment by TobiasGrether** [comment]
@ChristopherHX Just tested with the provided DMG, here is an updated crash log. From the timing, it appears to crash at the same location as before, but with a different error.

https://gist.github.com/TobiasGrether/ae839267d93afa62397fd84b3386c22a

**Comment by ChristopherHX** [comment]
> crash at the same location as before

No, now it's no longer in my source code

mutex lock failure is known as non deterministic fatal error, usually avoided by retry

**Comment by TobiasGrether** [comment]
> > crash at the same location as before
> 
> No, now it's no longer in my source code
> 
> mutex lock failure is known as non deterministic fatal error, usually avoided by retry

Woops yeah that seems to have fixed it. Retry fixes the crash and game starts normally. Thanks!

**Comment by ChristopherHX** [comment]
Does local lan multiplayer between two games and xbox line friend multiplayer work on the same AccessPoint?

I mean this is about a crash in a component that was needed to restore these functionality.
The fix basically filters those entries out, but no idea if there are still enough valid entries for webrtc to succeed

**Comment by Chin-Me** [comment]
> Does local lan multiplayer between two games and xbox line friend multiplayer work on the same AccessPoint?
> 
> I mean this is about a crash in a component that was needed to restore these functionality. The fix basically filters those entries out, but no idea if there are still enough valid entries for webrtc to succeed

I just tested with the nightly build and everything works fine currently. Do you mean that I should test LAN multiplayer and Xbox Live multiplayer? I'll do that later.

**Comment by ChristopherHX** [comment]
Fix released as 0.15.1(473), I recommend to uninstall any nightly version so you can continue getting notified about updates and the max-game-version is correctly versioned

> Do you mean that I should test LAN multiplayer and Xbox Live multiplayer? 

Yes, but excluding regular servers

**Comment by Chin-Me** [comment]
> Fix released as 0.15.1(473), I recommend to uninstall any nightly version so you can continue getting notified about updates and the max-game-version is correctly versioned
> 
> > Do you mean that I should test LAN multiplayer and Xbox Live multiplayer?
> 
> Yes, but excluding regular servers

I tested LAN mutiplayer and Xbox Service in the newest build 473, LAN seems working fine but Xbox Friends doesn't really work. The guest can't see the host's world in Friends tab. The host can invite friends and the friends can recieve the invitation. However the guest can't join the world. The guest client will show "We can't connect you to this world." I'm not sure if it's a common problem in all versions. I tested 0.14.2 and got the same result. But I'm sure I have succeeded with Xbox Mutilplayer Service in a certain version of the Launcher before.

**Comment by Chin-Me** [comment]
> > Fix released as 0.15.1(473), I recommend to uninstall any nightly version so you can continue getting notified about updates and the max-game-version is correctly versioned
> > > Do you mean that I should test LAN multiplayer and Xbox Live multiplayer?
> > 
> > 
> > Yes, but excluding regular servers
> 
> I tested LAN mutiplayer and Xbox Service in the newest build 473, LAN seems working fine but Xbox Friends doesn't really work. The guest can't see the host's world in Friends tab. The host can invite friends and the friends can recieve the invitation. However the guest can't join the world. The guest client will show "We can't connect you to this world." I'm not sure if it's a common problem in all versions. I tested 0.14.2 and got the same result. But I'm sure I have succeeded with Xbox Mutilplayer Service in a certain version of the Launcher before.

I think we need other tests to confirm this issue. The Xbox service isn't very stable in my region. 
@TobiasGrether Would you have time to test with Xbox Mutiplayer?

**Comment by ChristopherHX** [comment]
..

- Xbox live friend invites are not known to work
- I never did Xbox live friend over internet, only success is in the same network
- Only way to connect to console editions, as they have no custom external server support
- Sometimes just doesn't work, even on win10 edition

....Working LAN multiplayer is good enough and the more reliable of both methods

I think this issue can be closed now

**Comment by Chin-Me** [comment]
> ..
> 
>     * Xbox live friend invites are not known to work
> 
>     * I never did Xbox live friend over internet, only success is in the same network
> 
>     * Only way to connect to console editions, as they have no custom external server support
> 
>     * Sometimes just doesn't work, even on win10 edition
> 
> 
> ....Working LAN multiplayer is good enough and the more reliable of both methods
> 
> I think this issue can be closed now

Thanks for replying. Xbox is indeed not stable for mutilplayer. Maybe I'll consider to set up a server to play with my friends next time. I'll close this issue.
