### ISSUE TITLE
Re-integrate Dev settings

### ISSUE THREAD

**Issue by alextecplayz** [minecraft-linux/mcpelauncher-manifest#994]
**Is your feature request related to a problem? Please describe.**
Now that v0,15,0 is out, the Developer settings have been deprecated, which means Beta versions cannot be played (even if I already had Beta versions enabled prior to the launcher update)

Also, the changelog wording is vague:
> Developer Settings mode are deprecated again for regular User, because they have been misused to break the Launcher without knowing it

"regular User", what do you mean by that, because it's not clear? Can it be enabled again in some way that is hidden, such as a sequence, a hidden button or something to be added in a configuration file?

**Describe the solution you'd like**
Add or document a way to access and enable Beta versions, or the Dev menu in the launcher again.

**Comment by alextecplayz** [comment]
Looking into this, it seems that if you open the launcher with the [--enable-devmode flag](https://github.com/search?q=repo%3Aminecraft-linux%2Fmcpelauncher-ui-qt+QCommandline&type=code), it will show the Dev tab. This will allow you to play Beta and to access the Dev options as usual
![image](https://github.com/minecraft-linux/mcpelauncher-manifest/assets/63851536/4b3e5603-616f-463f-8340-9a71de305819)

It would have been nice if this was documented on the launcher wiki or somewhere else.

I'll close the issue, it seems that I just needed to dig through the code of the UI.

**Comment by forgeworksdev** [comment]
Heya! Quick note:

As a way to help newer players to access beta:

 flatpak run io.mrarm.mcpelauncher -d
