### ISSUE TITLE
macOS build for ARM (Apple Silicon)

### ISSUE THREAD

**Issue by ondrejmirtes** [minecraft-linux/mcpelauncher-manifest#997]
Hi, maybe I'm really stupid, but I only see x86_64 builds for macOS. I looked in these places:

* https://github.com/minecraft-linux/mcpelauncher-manifest/releases
* https://github.com/minecraft-linux/macos-builder/releases

When I download it and run it (`Minecraft_Bedrock_Launcher_v0.15.1-macOS-x86_64-0.2.473_macOS_10.13.0.dmg`), it shows up as "Intel" and not "Apple" in Activity Monitor.

Where can I download ARM build of mcpelauncher? Thanks.

**Comment by ChristopherHX** [comment]
> Where can I download ARM build of mcpelauncher?

A full arm64 dmg, doesn't exist.
This project has no active apple m-series developer, this needs hardware for testing purposes or results in an big overhead with m1 ci services and automate clicking through the app.

The only ARM binary in the intel dmg is `mcpelauncher-client-arm64-v8a` with three arch (x86/x86_64/arm64) dependencies, which doesn't make apple show the app as ARM

An universal dmg would be twice as large than what we currently have

E.g. playing the game doesn't make use of Rosetta 2, while downloading/starting the game does use Rosetta 2

**Comment by ondrejmirtes** [comment]
Thank you!
