### ISSUE TITLE
There no longer seems to be a Settings > Dev tab anymore

### ISSUE THREAD

**Issue by pganssle** [minecraft-linux/mcpelauncher-manifest#999]
**Describe the bug**
In the most recent version of the MCPE Launcher, there no longer seems to be a "Dev" tab under settings. In [this issue](https://github.com/minecraft-linux/mcpelauncher-manifest/issues/797), the instructions for allowing unverified / untested versions involves navigating to "Settings" and then to the "Dev" tab, but this no longer exists, and I do not see "Show unverified versions" anywhere in the other settings.

**To Reproduce**
1. Open the launcher
2. Click the "settings" icon.
3. Observe the lack of a "Dev" tab

**Expected behavior**
Either the Dev tab should appear, or there should be an option to show the Dev tab, or the options that existed on the Dev tab should be migrated into the other settings tabs and the instructions that refer to the Dev tab should be updated.

**Screenshots**
![image](https://github.com/minecraft-linux/mcpelauncher-manifest/assets/1377457/d4e1f750-d703-4545-9132-d63b2e14986c)

**Desktop (please complete the following information):**
 - OS: Linux (Arch Linux)
 - Version: v0.15.0.795-AppImage-x86_64 (Build 795)
 - Installation Type: AppImage  (via [AUR package mcpelauncher-appimage](https://aur.archlinux.org/packages/mcpelauncher-appimage))

**Additional context**

**Comment by pganssle** [comment]
Ah, it looks like this "Dev" tab only appears if you launch the application with `-d`. My mistake.

**Comment by ChristopherHX** [comment]
I have added this note to the linked issue, that might make it more obvious
![image](https://github.com/minecraft-linux/mcpelauncher-manifest/assets/44845461/a165d8fa-3751-4d71-a572-a630fd9446f1)

**Comment by yumey-me-8000** [comment]
i also use arch linux and i am using the beta and i need no  -d command
